### ISSUE TITLE
Crash between NEResources and forestry 4.2.x

### ISSUE THREAD

**Issue by border999** [ForestryMC/ForestryMC#1005]
https://github.com/hilburn/NotEnoughResources/issues/63

**Comment by border999** [comment]
just thought I would bring this to your attention

**Comment by way2muchnoise** [comment]
Should be fixed in hilburn/NotEnoughResources@6e8eec21511094380a19d4050540ff54459af501
I'm trying to get a build out as fast as possible

**Comment by mezz** [comment]
@way2muchnoise please get those from the `GameRegistry`'s `findBlock()` and `findItem()` to avoid this kind of issue. I think it's something like:

``` java
GameRegistry.findItemStack("Forestry", "apatite", 1)
```

You should be able to do this  by only referencing Forestry's API and with Forge, no internal Forestry classes.

**Comment by way2muchnoise** [comment]
yeah guess we should change to doing that @mezz

**Comment by mezz** [comment]
thanks!
