### ISSUE TITLE
Farm Block Recipes broken

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#1006]
Hey mezz,
the farm block recipes are broken, if i want to craft a farm gearbox out of quartz i get the gearbox out of stone brick as output (same with Valve, Hatch and Controller)
http://imgur.com/MakWN8U
Tested with 4.2.1.48 and 4.2.1.854-unstable
LG Aik

**Comment by mezz** [comment]
Thanks for the report! Fixed in the latest unstable build.
