### ISSUE TITLE
backpack superposition bug

### ISSUE THREAD

**Issue by CG-man** [ForestryMC/ForestryMC#1008]
backpack superposition can to copy some block or other things,so  i  have to  ban this  on  on my server,
sorry ,my english is very bad ,...

**Comment by mezz** [comment]
Thank you for the report!
Is this problem in the newest version, Forestry 4.2.1?

**Comment by CG-man** [comment]
when player   one time to make some backpacks  , backpacks  can superposition ,so , when you deposited some things  in  backpacks ,then  dispersed them , the things is copy the things.
and i have a new bug,why my farm can't to planting wheat, only receiving them.
lol

**Comment by mezz** [comment]
I do not understand you.
I'm sorry.

**Comment by davetheknave** [comment]
I have the same bug. The backpacks will stack if their contents are identical. For example, if I have two empty miners backpacks, and access them simultaneously, I can place a diamond into both, then separate them and take out the same diamond out of each of them, giving me two diamonds. This is with Forestry 4.2.2.50

**Comment by mezz** [comment]
Thank you, that clarifies the issue for me

**Comment by leagris** [comment]
##### Two things I'd do to prevent backpack stacking:
1. Restrict backpack stack size to 1
   
   ``` Java
   setMaxStackSize(1);
   ```
2. Assign each backpack an Unique Identifier NBT
   
   ``` Java
   import java.util.UUID;
   // ...
   stackTagCompound.setString("UUID", UUID.randomUUID());
   ```

**Comment by mezz** [comment]
Backpacks already have a unique ID, it looks like this issue is because they can stack.
