### ISSUE TITLE
Bucket fluid dupe bug

### ISSUE THREAD

**Issue by abculatter2** [ForestryMC/ForestryMC#1009]
Reported on the IRC, putting here on request:

When right-clicking a carpenter with a Railcraft creosote bucket (I did not test any other buckets) when the carpenter has less then 1000mb of space left, the tank is filled but the fluid in the bucket is not consumed.

Additionally, it seems that crossbred leaves (or at least the ones which result from crossbreeding vanilla birch and oak) are transparent even when the graphics settings are set to 'fast'. This also causes a visual glitch with adjacent leaf blocks which allows you to see through blocks.

**Comment by mezz** [comment]
Thanks for the report!
Looks like the leaves issue has been reported actually: https://github.com/ForestryMC/ForestryMC/issues/995
Fluid dupe is new.
