### ISSUE TITLE
Mutation knowledge not synchronized live between Arborist Chest and Alyzer

### ISSUE THREAD

**Issue by leagris** [ForestryMC/ForestryMC#1010]
Having learnt Kapok+Yello Meranthi ⇒ Spiri from an Escritoire memory game knowledge note, I did not get the mutation shown into Alyzer slot IV, but it was shown into an Arborist Chest.

After a few minutes it was shown into the Alyzer as well.

Opening the arborist chest is enough to get data updated and having the Allyzer to dissplay the new learnt mutation.

**Comment by mezz** [comment]
Thanks for the report!
I have made the latest version sync the breeding tracker automatically when the player logs in and when they discover new species or mutations. Please try out the latest dev version and let me know if you find an issue with it.
