### ISSUE TITLE
Forestry for 1.6.4 crashing (Thaumcraft conflict of some sort?)

### ISSUE THREAD

**Issue by NINTENPUG** [ForestryMC/ForestryMC#1013]
So, I have a whole bunch of mods installed, but sadly, when I tried to install Forestry (I've tried multiple versions for 1.6.4), it makes my game crash.

[Here's the crash report](https://gist.github.com/NINTENPUG/31cd4fc6a564487ab1c0). From what I can read, it's having issues with Thaumcraft, which is kind of strange, since they should be compatible. Another option would be that it won't work with my version of forge, but I doubt that too.

I would understand if I won't be helped due to it being a legacy version, but any help would be greatly appreciated!

**Comment by mezz** [comment]
This looks like a bug with Thaumcraft trying to do stuff with a Forestry Log. 
It may be an ID conflict, I don't really know. 
Sorry I'm not able to help much, my modding experience is 1.7.10 and later.
I recommend looking at mod packs from that time and basing yours on those versions.
