### ISSUE TITLE
Carpenter stops working after one use

### ISSUE THREAD

**Issue by Shahelion** [ForestryMC/ForestryMC#1014]
I'm making Impregnated casings, I have seed oil in the Carpenter and plenty of Acacia logs. However, after it made the first one, it said "no recipe found". I've tried clearing the crafting grid, emptying the inventory, emptying the tank and refilling it, nothing works. Using version 3.6.12.3

![image](https://cloud.githubusercontent.com/assets/6917535/11862284/fc9840ac-a43d-11e5-9052-e20b0fa2a884.png)

**Comment by mezz** [comment]
The Impregnated casing recipe requires 250mb of seed oil.
Forestry 4 has better error message that let you know when you need more fluid.

**Comment by Shahelion** [comment]
Yeah, I checked back shortly after and realized the problem. I figured it would have an additional error tab for not enough fluid, while still showing the output item, instead of simply saying no recipe found.
