### ISSUE TITLE
Compatibility with IC2-experimental "Biomass"

### ISSUE THREAD

**Issue by mtaalas** [ForestryMC/ForestryMC#1015]
I found a bug just today where forestry installed, the IC2-exp produces wrong/weird type of biomass that can't be used by the IC2-exp machines like "Fluid Heat Generator".

I filed the bug report here: http://bt.industrial-craft.net/view.php?id=1783 (sorry for the typos, i'm tired)

But gist of the matter is, that both IC2 and Forestry use "Biomass" that's produced differently and has different ID. It would be great if you could improve the compatibility between mods so that the liquids thus  generated would be interchangeable or at least completely different.

**Comment by mezz** [comment]
Thanks for the report!
Judging by the IC2 report, they don't want them to be interchangeable. Sorry.
