### ISSUE TITLE
Apiary Cart GUI crash server

### ISSUE THREAD

**Issue by leagris** [ForestryMC/ForestryMC#1017]
Interacting with an Apiary Cart crashed server:
https://gist.github.com/leagris/0dd13cc3addd2ed95c62#file-crash-2015-12-22_20-35-33-server-txt

**Comment by mezz** [comment]
How strange. I'll look into it soon.

**Comment by leagris** [comment]
@Mezz likely another client side call from server-side.

**Comment by mezz** [comment]
I just crashed a server with this... top priority!

**Comment by mezz** [comment]
It was an obfuscation issue. My interface used the same name as minecraft (`getEntityId`), and it got caught in the obfuscater.
