### ISSUE TITLE
NEI Crash

### ISSUE THREAD

**Issue by Shahelion** [ForestryMC/ForestryMC#1018]
https://github.com/Chicken-Bones/NotEnoughItems/issues/313

**Comment by mezz** [comment]
Thanks for the report!
NEIPlugins is very outdated, it has been replaced by NEIIntegration.

**Comment by mezz** [comment]
Also remove NEIForestry, not even sure where you found that, I think it's over 2 years since it was last updated

**Comment by Shahelion** [comment]
I don't have any mod called NEIForestry...but thank you c:
