### ISSUE TITLE
Updated to version 4.2.1 Forestry

### ISSUE THREAD

**Issue by kostay99** [ForestryMC/ForestryMC#1019]
Hello, there is such an error, what could be wrong.
https://gist.githubusercontent.com/kostay99/62f18b6c7fc2fec699b0/raw/e51c46b4d88b3282dcdc31699a22eadc49405775/forestry_1.7.10-4.2.1.48

**Comment by Nirek-K** [comment]
That looks to be related to compat in neresouces  NotEnoughResources? I believe has alreday been fixed on their side.

**Comment by kostay99** [comment]
Thank you! I've updated the NEI Resources and the problem was solved.
