### ISSUE TITLE
Thermionic Fabricator Won't Take Power

### ISSUE THREAD

**Issue by HideAwayDk** [ForestryMC/ForestryMC#1020]
![thermionic fabricator](https://cloud.githubusercontent.com/assets/7749454/11978452/061e0fdc-a98c-11e5-98a7-01e33bd3f6be.jpg)
Hey :)

I use the last Forestry 4.2.3.51 And i can't power the Thermionic Fabricator i tryed with TE and EnderIO :(

**Comment by mezz** [comment]
Thanks for the report!
Currently the Thermionic Fabricator is waiting for a recipe before heating up.

**Comment by Blue64** [comment]
Have you also tried with Extra Utilities? I can't even count how many times I had to rely on those Hyper Transfer Nodes for cross mod RF compatibility lol
