### ISSUE TITLE
Forestry 4.2.3 Error on World Creation

### ISSUE THREAD

**Issue by Drakoflame** [ForestryMC/ForestryMC#1021]
I've copied what I think is needed to help solve this error, it is stupidly easy to re-create should someone need it. http://pastebin.com/vvmSLHT4 if anyone has any ideas on whats happening, from what I can tell, forestry is missing something nessesary for generating a new world... and if there are any requirements I don't know what they are, because either I'm blind as a bat, or the Curseforge page doesn't have them there

**Comment by mezz** [comment]
Thanks for the report!
"This is a private paste", I can't view it.

**Comment by Drakoflame** [comment]
Woops! I'll fix that, go ahead and check it again: http://pastebin.com/vvmSLHT4

**Comment by mezz** [comment]
Try updating or removing CMIP

**Comment by Drakoflame** [comment]
What is CMIP? And I'm using the latest version available on Curse

**Comment by mezz** [comment]
It's a mod you have installed, and it's the one crashing. http://www.curse.com/mc-mods/minecraft/237207-cmip

Please see this issue: https://github.com/ForestryMC/ForestryMC/issues/961
I recommend updating it, and if that doesn't work, you should remove it.

**Comment by Drakoflame** [comment]
aaaaah, Okay! thanks for the help Mezz :3
