### ISSUE TITLE
Undistinguishable pollination colour for multiple species

### ISSUE THREAD

**Issue by leagris** [ForestryMC/ForestryMC#1022]
- forestry_1.7.10-4.2.3.51
- forge-1.7.10-10.13.4.1614-1.7.10-universal
##### Species with indistinguishable pollination colour:
- Date Palm
- Papaya

![2015-12-24_13 41 49](https://cloud.githubusercontent.com/assets/1111474/11994761/7f649c5e-aa44-11e5-9412-0503f39b820a.png)

![2015-12-28_15 18 33](https://cloud.githubusercontent.com/assets/1111474/12019933/948e1792-ad76-11e5-842c-480f4a43a7ca.png)

**Comment by leagris** [comment]
If not already the case, all leaf colours should be in client-side configuration .
It could also provide a good option for colour-blinds, to choose their own secondary colours or even set grey-scales as it was in previous versions.

**Comment by mezz** [comment]
I agree colorblind mode would be good.
I'm going to keep changes minimal until a 1.8.8 branch is ready though.

I don't think all leaf colors need to by client-configurable. They should have reasonable defaults.
