### ISSUE TITLE
Raintank does not work with sticky piston

### ISSUE THREAD

**Issue by Zyles** [ForestryMC/ForestryMC#1023]
When I try to push a raintank with sticky piston it will not move. Is there a technical reason for this?

Also isn't the correct spelling "rain tank"?

Thanks.

**Comment by mezz** [comment]
Sticky pistons will not move anything that has a "tile entity". This includes chests, raintanks, furnaces, anything that stores stuff or has special abilities basically. 

I'm not sure why it's spelled that way, I guess I can fix it without too much worry.
