### ISSUE TITLE
Stuck on 1.7.10-3.6.6.24 version

### ISSUE THREAD

**Issue by DadYoshi** [ForestryMC/ForestryMC#1024]
Server wont start when I try 1.7.10-4.2.3.51

Here is crash rpt
[crash-2015-12-28_15.14.02-server.txt](https://github.com/ForestryMC/ForestryMC/files/73527/crash-2015-12-28_15.14.02-server.txt)

**Comment by mezz** [comment]
Thanks for the report!
Duplicate of https://github.com/ForestryMC/ForestryMC/issues/857
