### ISSUE TITLE
Server multifarm cannot auto input with either vanilla hopper or other mods pipes.

### ISSUE THREAD

**Issue by Joccob** [ForestryMC/ForestryMC#1027]
Server using: Kcauldron 1.7.10 latest official 1517.168
Forestry version: 4.2.2.50 (not the latest forestry because the minimum forge version is 1566 )

As mentioned in the title, my multifarm works fine except it can't auto input anything via farm hatch. I tried ender IO item conduit, extra utilities transfer node and vanilla hopper. Weird thing is that I tried to test in single player mode and everything works fine...I'm not sure if this is a bug or its just because of the cauldron version. 

![Image of Multifarm](http://i.imgur.com/UHXrAFz.png)

**Comment by mezz** [comment]
Thanks for the report!
Make sure the farm permissions tab is set to public. If it's protected or private it can't be automated.

**Comment by Joccob** [comment]
Oh, I guess that's it. I tried again and it works!
