### ISSUE TITLE
Crash with loot from Chromaticraft's chroma dimension 

### ISSUE THREAD

**Issue by Reignofmagic** [ForestryMC/ForestryMC#1031]
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/530#issuecomment-168269651

As I am not familiar with forestry code I cant point to a spot where this might happen.

**Comment by mezz** [comment]
Thanks for the report!
After looking into it I've found the bug is on his side, I'll discuss with him in the other comment thread.

**Comment by Reignofmagic** [comment]
No worries, just hope to get this sorted for both of ya!
