### ISSUE TITLE
multifarms have issues with branches

### ISSUE THREAD

**Issue by bear989** [ForestryMC/ForestryMC#1033]
most trees now have an extra log past the trunk horizontally, and the multifarm isn't breaking them causing the leaves to never decay and eventually because stalled out.

**Comment by mezz** [comment]
Thanks for the report!
Please try the latest version (4.2.4), it should resolve this issue (once you clear the existing floating branches).

**Comment by lOmicronl** [comment]
I'm running 4.2.4, and have not encountered any problems with this... with one exception, which I came here to report. The multifarm fails to catch the disconnected log parts that sometimes spawn above the main trunk on papaya trees.

Trees I have not yet tested: kapok, yellow meranti, date palm, blue mahoe, sipiri, baobab. All others I've checked and they run flawlessly. Only the papaya appears to screw up.

**Comment by lOmicronl** [comment]
Update: I finally tested all trees. Except the Sipiri, which didn't want to grow in my test world. Why is it the only tree with special growth requirements? Recommendation: Make it grow everywhere, like all others.

The Papaya and the Baobab have issues with not being harvested correctly in v4.2.4, the other trees are ok.

**Comment by mezz** [comment]
Thank you for testing!

**Comment by lOmicronl** [comment]
@mezz - If it tickles your fancy, my testing ultimately produced this :) 

https://dl.dropboxusercontent.com/u/44754370/treealyze2.png

I like data!

**Comment by mezz** [comment]
A farm refactor made it better at getting branches, and a tree generation cleanup fixed the Baobab generation. This final commit closes this issue with Papaya.
