### ISSUE TITLE
Forestry Ores not recognised by Ex Nihilo Hammers

### ISSUE THREAD

**Issue by Blue64** [ForestryMC/ForestryMC#1037]
I was doing a test run looking for bugs in my personal ModPack, and I gathered some Copper & Tin from M-Ore, IC2, & Forestry, went to use an Ex Nihilo Hammer on them to double the Ores, and WAILA said that my Hammer wasn't good enough Tier, so I cheated up a Diamond Hammer, still not good enough. Unless I get some TiCon stuff going on, there's no higher Tier than Diamond Hammer, and I haven't tested any other ores yet, but if it's not giving Tin/Copper drops for a diamond hammer, I would assume the problem is widespread throughout Forestry Ores (the other ores hammered up just fine with Wood/Stone Hammers).

**Comment by mezz** [comment]
Thanks for the report!
This is an Ex Nihilo issue. I see you posted it to the correct Ex Nihilo repo already, thanks. https://bitbucket.org/MikeLydeamore/ex-nihilo/issues/30/forestry-ores-not-recognized
