### ISSUE TITLE
Forestry WaxCapsules and Tin Cans cannot be filled  with Railcraft creosote oil in any way

### ISSUE THREAD

**Issue by damnedsky** [ForestryMC/ForestryMC#1039]
Railcraft_1.7.10-9.8.0.0
forestry_1.7.10-4.2.4.52
What I tried so far:
- right clicking with a stack of capsules on a Coke Oven
- placed a stack then a single capsule in the Coke Oven slot
- filled a Forestry Bottler with creosote and tried the capsules there

Sooooo... all the Forestry capsules are called "Forestry:waxCapsule<LiquidName>" while the Railcraft one is "Railcraft:fluid.creosote.wax". Buckets and bottles filled with creosote work fine with all Forestry machines. Capsules do not. I am also reporting this on the Railcraft GitHub.

**Comment by xenexelen** [comment]
I have the same problem with the Buildcraft-Oil, then i remove all mods and add each in single steps...

Do you use BiblioWoods[Forestry][v1.7]?
=> Remove it.

**Comment by mezz** [comment]
Thanks for the report!
Sorry, this issue slipped through the cracks.

From what I can see, there is no issue with just Railcraft_1.7.10-9.8.0.0 and Forestry 4.2.9.

![2016-02-28_23 49 53](https://cloud.githubusercontent.com/assets/916092/13388604/1e96e1f0-de76-11e5-8ba5-1dc0b369ce6e.png)

For easier cross-reference, the Railcraft issue is here: https://github.com/CovertJaguar/Railcraft/issues/766

**Comment by CovertJaguar** [comment]
This is probably something on my side. I don't see how Forestry could affect it.

**Comment by mezz** [comment]
Not much has changed recently for 1.7.10 Forestry, nothing comes to mind.
