### ISSUE TITLE
Branch Version Release Request - 1.8.9

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ForestryMC/ForestryMC#1041]
This mod is wonderful and I love all the different trees could you pretty please start a 1.8.9 branch? I promise to test the shit out of it for you ;P

**Comment by mezz** [comment]
I'm working on JEI right now, 1.8.9 kind of depends on it and I want it "done" before things really blow up in popularity.
That should not take very much longer though, a month or two at most.
