### ISSUE TITLE
NPE in loot chest from Chromaticraft dimension

### ISSUE THREAD

**Issue by therodet** [ForestryMC/ForestryMC#1043]
Client crash opening some chests in Chromaticraft dimension
http://pastebin.com/tnJLMcyt/

I also get a similar crash with 'getPlankIcon' as the method in the second line

**Comment by mezz** [comment]
Thanks for the report!
For more context see here: https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/530

I will return larch icons here for now. No guarantee that it wont crash somewhere else though. Please let me know if it does.

**Comment by mezz** [comment]
You can get the updated version here, http://jenkins.ic2.player.to/job/Forestry_Dev/
    forestry_1.7.10-4.2.5.876-unstable.jar
