### ISSUE TITLE
[API Feature Request] Product control, perhaps product-specific jubilance

### ISSUE THREAD

**Issue by ReikaKalseki** [ForestryMC/ForestryMC#1045]
I would greatly like the ability to specify different world conditions for different products, so that my custom bees could produce different products based on the world around them (for example berries from trees, dyes from flowers, etc).

One way this could be done is by changing getProducts() to take the IBeeGenome and IBeeHousing arguments that isJubilant() does.

**Comment by mezz** [comment]
You should be able to do that now with the obscure method `IFlowerProvider.affectProducts`.
Just create a custom flower provider for your bees and then you'll be given the world, housing coordinates, bee, and product list.

As a warning, the flower provider API is probably the most horrible part of the API right now, and I'm waiting for Minecraft 1.8.9 to rewrite big chunks of it. This method will survive in some form though.

**Comment by ReikaKalseki** [comment]
Does that not then mean that a given bee could only have one, and that it could be overwritten by another gene?

**Comment by mezz** [comment]
That's true, a bee's flower provider allele can be changed or bred onto other bees.
The one flower provider can support everything you wanted though, altering the products based on surroundings.

The Forestry 1.7.10 API is pretty much frozen for now, because I need to let Forestry 1.8.9 get off the ground without having to resolve many changes from upstream. In 1.8.9, I can think about adding exactly what you wanted, but it will not be done for quite a while.

**Comment by ReikaKalseki** [comment]
I suppose I will just use [a massive isJubliant function](http://i.imgur.com/rZiRlHt.png) for now...

**Comment by ReikaKalseki** [comment]
I just had an idea...how well would Forestry handle dynamic production maps? I could bootstrap the isJubliant() call to set a family of variables based on the world state, and that would inform the return values for the getProducts() and getSpecialty() maps.

**Comment by mezz** [comment]
Forestry doesn't cache any of that, you're free to make it dynamic.
It will probably be strange for some other things though, like the beealyzer and NEIAddons which show bee products.

**Comment by mezz** [comment]
Relevant bee code for specialty products is here:
https://github.com/ForestryMC/ForestryMC/blob/dev/src/main/java/forestry/apiculture/genetics/Bee.java#L520-L527

**Comment by ReikaKalseki** [comment]
Yes, it will end up working like the vanilla wireless redstone and similar one-instance behaviors.

**Comment by Nedelosk** [comment]
There will be an improved product's implementation and an `IDynamicProductList` will be available in 1.14.4.
https://github.com/ForestryMC/ForestryMC/blob/d592bf52e8738374dfa468360df0d085c08544e5/src/main/java/forestry/api/genetics/products/IDynamicProductList.java#L22-L35

**Comment by ReikaKalseki** [comment]
Does that allow for the sort of thing I have done, which is products which are dependent on things such as proximity to certain blocks, or NBT data on the placing player?

**Comment by temp1011** [comment]
The method provides the world and pos. So proximity stuff is fine and you can get a `Gameprofile` by getting the `IBeeHousing` at the location which would give an identifier for the player?

**Comment by ReikaKalseki** [comment]
Fair enough.
