### ISSUE TITLE
Crash While Placing Interactive Blocks In Non-Solid Blocks

### ISSUE THREAD

**Issue by TheNexusAvenger** [ForestryMC/ForestryMC#1046]
This bug appears to be exclusive to Foresty. I can't reproduce it with a few other mods, so here are the repro steps:
1. Have a block with a non-solid block that still allows the adjacent blocks able to be focused on, such as a torch, a lever, a button, or a ladder.
2. Move your cursor over the hitbox of an adjacent block where placing a part there would be the same spot as the non-solid block.
3. Place an interactive block, such as an engine, a machine like a Fermenter, or a Bee House/Apiary. Any block that creates a gui when interacted without extra blocks like an Alveary.
4. Client crashes.

Computers tested on: Lenovo Yoga 2 (Windows 10) and Lenovo Y510P (Windows 8.1)
Java used: Java 8 Update 60
Version of Forge Used: Forge10.13.4.1558-1.7.10
Version of Foresty Used: forestry_1.7.10-4.1.1.46
Crash Report: http://pastebin.com/ABPnZdvX

This bug does not cause a world to get corrupted. Worlds can be re-opened and continued as normal.

**Comment by mezz** [comment]
Sorry, this issue fell through the cracks. 
It appears to have been  fixed when #958 was fixed, and does not crash in the latest version of Forestry.
