### ISSUE TITLE
Fluxed Queen Crashes Game

### ISSUE THREAD

**Issue by duncanwebb** [ForestryMC/ForestryMC#1047]
I used the GenDustry advanced mutator to create Fluxed Queen. Next I put the queen in an Forestry Apiary and after a while the server crashes, may be when the queen has divided in to a princess and drone. I first used a GenDustry Industrial Apiary and the same thing happened. 

I used NBTExplorer to remove the Block entity being ticked and it removed the bee and not the Apiary.

Please ask if you need anything else.

**Comment by mezz** [comment]
Thanks for the report!
Can you please provide the crash log?

**Comment by mezz** [comment]
Also I believe the Fluxed Queen is from magic bees, you should report here: https://github.com/MagicBees/MagicBees/issues
Thanks!

**Comment by duncanwebb** [comment]
Thanks and sorry for the noise. NEI reports them as belonging to forestry
