### ISSUE TITLE
The Forester's backpack will hold berries from Natura, but not apples from Mojang.

### ISSUE THREAD

**Issue by keybounce** [ForestryMC/ForestryMC#1048]
The Forester's backpack will hold berries from Natura, but not apples from Mojang.

Does not make sense; it's forest product and food in both cases.

**Comment by esotericist** [comment]
Additionally, it won't hold Wheat (from vanilla) or Barley (from Natura), despite the default config file in 4.2.10 has cropWheat, cropBarley, and cropApple in its oredict list, all of which are oredicts correctly applied to the relevant items.

**Comment by esotericist** [comment]
Okay, it looks like it might actually be a broader problem: The digger's backpack (again, in 4.2.10) isn't accepting cobblestone or dirt despite having oredict entries matching the blocks (again, with default config).

**Comment by keybounce** [comment]
I thought cobblestone went to the miner's pack (with all the stones), not the digger's pack. But dirt? ... I was sure that I had dirt going into the digger pack.

I do know that cobblestone was being picked up by some pack, along with cobble'd variants of all of Reika's stones. At least with the version of forestry on his dev server.
