### ISSUE TITLE
Biomes O' Plenty and Pam's Harvestcraft Conflict

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#1051]
I've been working on updating my modpack to the most recent versions of everything available 1.7.10, and I noticed that when Biomes O' Plenty and Pam's Harvestcraft (Together or separately) exist in my modpack, I get a launch error involving adding a crop.

At this point the launch crashes, and it's the same thing conflicting for both, adding a crop.  I can include error information, but I think I've narrowed it down to this issue.

Has anyone else experienced this?

**Comment by Nirek-K** [comment]
Really need the crashlog/console log.

**Comment by ghost** [comment]
http://pastebin.com/8pcL6GgX - With BoP
http://pastebin.com/zhC1tLC3 - With Pam's Harvestcraft (BoP removed)
Admittedly, have not tried running it with Pam's removed and BoP still in.

**Comment by Nirek-K** [comment]
Issue with disabling the farming module, will fix later tonight at some point.
