### ISSUE TITLE
LP and FORESTRY

### ISSUE THREAD

**Issue by O13SC3N3** [ForestryMC/ForestryMC#1055]
LP: 0.9.3.70
Forestry: 4.2.6.54
Forge: 1566

following error pops up in the console on startup, haven't really dived into LP/Forestry to find if a more underlying issue is involved. Posted at LP as well.

http://pastebin.com/aLGfDx2G

more

http://pastebin.com/QrSRz2jx

[https://github.com/RS485/LogisticsPipes/issues/906](url) ISSUE906

**Comment by mezz** [comment]
Thanks for the report!
This looks like a purely LP issue. Make sure you have the latest version, this error is from LP looking for a class that has changed locations in recent versions of Forestry.

Can you link to the other issue so these two issues are connected?

**Comment by hron84** [comment]
@mezz here's the link, the reported did it on wrong way. Also RS485/LogisticsPipes#906
