### ISSUE TITLE
Crash 4.2.7

### ISSUE THREAD

**Issue by O13SC3N3** [ForestryMC/ForestryMC#1056]
1.7.10
Forge 1566
FastCraft

http://pastebin.com/CMDb2dU4

**Comment by Nirek-K** [comment]
That looks like an old crash with Not enough resources, that was fixed.

**Comment by O13SC3N3** [comment]
holy crap, didnt know I didnt have the latest version... My bad, ill give it a whirl

yep im a idiot thanks :p
