### ISSUE TITLE
Bug (I can not solve).

### ISSUE THREAD

**Issue by naluisio** [ForestryMC/ForestryMC#1059]
This package of "mod" I myself created to play at my residence with my brothers and I would like to find a solution and continue my world with this mode Excellency "Forestry".

https://gist.github.com/mezz/a0a91539646546a30417

**Comment by mezz** [comment]
Thanks for the report!
Remove `BiblioWoodsForestry`, it is not compatible with Forestry 4. 
It is no longer needed, you can use the Bibliocraft Paneler to make wooden items with Forestry planks.

**Comment by naluisio** [comment]
Ho! man thanks, you is my God today, i love it.
