### ISSUE TITLE
Support for Growthcraft Community Edition

### ISSUE THREAD

**Issue by bookerthegeek** [ForestryMC/ForestryMC#1060]
Per https://github.com/ForestryMC/ForestryMC/issues/223, Growthcraft is supported, but evidently the GCE (Growthcraft Community Edition) is not

`[Client thread/INFO] [Forestry]: Module Growthcraft Plugin failed to load: GrowthCraft not found`
I am using
`growthcraft-1.7.10.2.4.0-bundle`

[LINK](http://www.curse.com/mc-mods/minecraft/235092-growthcraft-community-edition) to the mod in question.

**Comment by Nirek-K** [comment]
They probably decided to rename things..for no apparent reason, I built last against 2.2.2 complete.

**Comment by Nirek-K** [comment]
I just tested 2.4.0 complete and it does in fact work (though may not have anything for whatever was added in 2.2->2.4 no idea what those things would be)
Edit: And 'bundle' also works (sans the api, which they include in the user download for...some reason)

**Comment by bookerthegeek** [comment]
Thank you. now just to get the log file to reflect that it does work.

**Comment by Nirek-K** [comment]
If you're seeing that in the log, it is indeed not loading. Are you running only parts of the bundle or something?

**Comment by bookerthegeek** [comment]
The latest bundle from curse.

**Comment by bookerthegeek** [comment]
I also get this when I run the moduals.

**Comment by bookerthegeek** [comment]
Also, this is with the latest on curse or both forestry and GCE. The device build page was not loading when troubleshooting

**Comment by Nirek-K** [comment]
Try running the complete rather than the bundle, they're the same version. (Could also try the latest unstable forestry, jenkins i back up)

**Comment by bookerthegeek** [comment]
I'll try both tonight. Ty.

**Comment by bookerthegeek** [comment]
| Plugin Loaded? | Forestry DEV | Forestry REC |
| :-- | :-: | :-: |
| GCE Bundle | No | No |
| GCE Complete | Yes | Yes |

Hopefully my graph will explain better then my can't figgin speak/type tonight.

**Comment by Nirek-K** [comment]
Strange, you must have something messing with load order of things or something. I tested bundle (removing all the jars from the zip and putting them in the mod folder (other than api)) and it worked for me with a recent dev. Atleast you have something that works for you.

**Comment by bookerthegeek** [comment]
Interesting... where are you getting your bundle from? For the Complete I downloaded from Minecraft forums (i.e. curseforge), for the Bundle it is what curse voice downloads. I just used the zip as is... It registers GCE in the mod list and loads without needing to do anything to the zip file.

**Comment by Nirek-K** [comment]
From the link you provided/curseforge, I don't use a launcher to manage that. Opening the zip and only using the jars you want is sort of the point of that bundle setup. I'm rather suprised it would even pick it up inside the zip like that.

**Comment by bookerthegeek** [comment]
When removing from the zip, Curse Voice no longer recognizes the mod/author, and no more auto updates. Not a super problem as long as I know the workaround, but anybody making a modpack for private consumption with that launcher will not get the compatibility.

I just use it as an easy way to make sure my mods are updated in my pack.

**Comment by Nirek-K** [comment]
Well, I just tested putting the zip in the mod folder, and minecraft doesn't understand/load it at all, as expected. That launcher obviously does something to it, and is not something I can/really should try to fix. In the end it looks like use the complete edition to get things to work correctly (bundle will likely also break most any other mod trying compatibilty, I don't do anything special, just a modid lookup),

**Comment by IceDragon200** [comment]
@bookerthegeek @Nirek-K Hello, GC CE dev here https://github.com/GrowthcraftCE/Growthcraft-1.7/issues/202 related issue.

The bundle was packed with the API jar which wasn't suppose to be present.
The API was included with the core already.

I'll be opening an issue later requesting the removal of the Growthcraft Plugin in Forestry, we'll call into the Forestry API and handle the integration ourselves.
Hopefully all bug reports from there forth will be aimed at us and not you (Forestry team).
