### ISSUE TITLE
Squeezer is very "liberal" regarding oredict in Recipes

### ISSUE THREAD

**Issue by GregoriusT** [ForestryMC/ForestryMC#1061]
I just found an interessting Bug. The Squeezer is able to turn Sugar Dust into Honey, as if it were a Honey Drop. I looked into the Recipe List in NEI and didnt see a Sugar->Honey Recipe, so nobody added anything, but when I looked up "uses of Sugar" it showed a sugar to honey Recipe.

Ofcourse I updated Forestry to latest before coming here and I did check what the cause could be. Then I noticed that the Honey drop item is registered in the OreDict as "listAllsugar" (from Harvestcraft), what is ofcourse a perfectly valid use of OreDictionary, and Honey and Sugar are registered under that name (for its Recipes to have Honey and Sugar interchangable).

However, somehow the Squeezer probably reads out all the things the Honey drop is registered as, and accepts all those names and not just "dropHoney" as valid Input for that Recipe (what explains NEI only showing it when selecting "uses of Sugar"). I guess you see where the problem is, and that other Machines might have the same Problem in their Recipe System.

Sugar itself is only registered as "listAllsugar" and "dustSugar", so I am 100% sure it is not registered as "dropHoney" or something.

I hope this Issue gets fixed soon, because turning Sugar to Honey is not really something that is intended, is it? Not to mention that there must be a deeper problem being the cause of it.

**Comment by mezz** [comment]
Interesting, thanks for the report. That's definitely not working correctly.

**Comment by josephcsible** [comment]
It seems that the fix for this never made it to any versions newer than 1.7.10.
