### ISSUE TITLE
Multifarm circuits with multiple crops config disappear on server restart

### ISSUE THREAD

**Issue by leagris** [ForestryMC/ForestryMC#1063]
Using: BeyondReality pack version 2.3.8b
- forestry_1.7.10-4.2.5.881-unstable.jar
- forge-1.7.10-10.13.4.1614-1.7.10-universal.jar

https://github.com/Beyond-Reality/BeyondRealityModPack/issues/381

**Comment by mezz** [comment]
So far I have not been able to reproduce this issue under any circumstances. 
Is there any more information?

**Comment by leagris** [comment]
@mezz, since I gained access to server logs. I found it did crash during unload. Maybe not directly related but possibly causing tile NBT loss during server restart.
[crash-2016-02-28_14.00.02-server.txt](https://gist.github.com/leagris/97316f20f6aa8855e379)

**Comment by mezz** [comment]
Unfortunately the crash seems to involve codechicken.lib, I think that is the cause of the problem.
