### ISSUE TITLE
Drop Growthcraft Plugin (1.7)

### ISSUE THREAD

**Issue by IceDragon200** [ForestryMC/ForestryMC#1065]
Related #1060, https://github.com/GrowthcraftCE/Growthcraft-1.7/issues/202

**tl;dr** We'll do it on our side, since it changes frequently sometimes with breaking changes.

**Long**
In response to these issues I'd like to have the Growthcraft Plugin removed, since things change very quickly in development.

We'll handle the integration ourselves by calling into the existing Forestry API.

This should lighten the load on your side and reduce the number of bug reports regarding Growthcraft.

**Comment by Nirek-K** [comment]
Eh, not really nessicary, the null in question there is basically the only item I forgot to nullcheck, it's otherwise all behind checks to prevent such things. (I will fix that null check today Edit: Fixed.) The bundle thing as far as I could tell worked properly.

**Comment by ReikaKalseki** [comment]
I found the error [here](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/616#issuecomment-182089922). Your code is still invalid, because the _ItemStack_ is not null, the _Item inside_ is.

**Comment by mezz** [comment]
If they want to support it right now they should, our API for 1.7.10 is pretty stable and their code is changing much more.

**Comment by Nirek-K** [comment]
Has little to do with code changing, GC wasn't splittable when that was written so it was untested in that form. 1 missing null check and explosions. I've further tightened that section so it shouldn't happen.

**Comment by mezz** [comment]
This isn't about one tiny bug, it's about maintainability in the future. For instance, if they have the code, all versions of growthcraft in the future will be compatible with Forestry instead of just the latest.

**Comment by ReikaKalseki** [comment]
You only null-checked the comb, leaving the bamboo and other things to still be vulnerable. Again, it is better to simply remove the handling and let the GrowthCraft team manage it, as they are clearly far more likely to know when internal GC code changes than you are, especially in a timely manner.

**Comment by TomeWyrm** [comment]
Also, why not let GrC handle the integration on their side? It's far easier for you, and if it breaks, THEY can fix it. Their API is more unstable than yours... it makes no sense to keep doing something the hard way when someone reliable is offering you an easy out.

**Comment by IceDragon200** [comment]
I've finished on our side: https://github.com/GrowthcraftCE/Growthcraft-1.7/pull/205

Just bug testing and replacing your Proxy blockDestroy effect call and it should be good :)

I hope didn't mind, I stole some classes (The Growthcraft\* related ones and Vect (rewritten as Point3 in our API))

**Comment by mezz** [comment]
Just FYI, we have special handling for traversing over vines that can't be added via the API. That will have to stay.
Give us a version number for Growthcraft where your integration will start. We can make sure our plugin is active for older versions, and inactive after the version you give.

**Comment by IceDragon200** [comment]
@mezz 2.5.0, anything before that should use the plugin :)

**Comment by mezz** [comment]
Ok, Forestry 4.2.8 will not enable its Growthcraft plugin when 2.5.0+ is detected.
