### ISSUE TITLE
Multifarm

### ISSUE THREAD

**Issue by Jonas8990** [ForestryMC/ForestryMC#1069]
I am having a huge issue on the FTB Infinity evolved modpack with the multifarm structure. It says that it needs water, fertilizer and that there is no farmland. The thing is that it do have all of the criteria, soo it should work. And i guess that is it kinda weird cause it do registre that there is power in it. The version of forestry for minecraft is 3.6.6.24 if that is needed to know? Don't know if that is a bug or I am crazy stupid and not knowing what I am doing... I have done one of those farms before soo I guess I should know that it should work with the blocks I have placed.

Hope i get some help out there ;-)

**Comment by mezz** [comment]
You closed the bug, did you find out what was wrong?

**Comment by Jonas8990** [comment]
Uhm yeah. It was prob a but of a rush when i opened this post. But I think that the problem is that the binnie mod is not up to date in the infitnity pack. And the problem by that is that someone have reported that problem back in september. The 3.6.6.24 is a update back from september i believe. And it cannot be updated to the new one from january or february cause of the binnie mod. Sorry if i have wasted your time when asking this silly problem from an old update..
