### ISSUE TITLE
Development build server is inaccesible

### ISSUE THREAD

**Issue by IceDragon200** [ForestryMC/ForestryMC#1070]
Sorry to bother you, I'm not sure if I should report it here, but:

http://ic2api.player.to:8080/job/Forestry/
http://ic2api.player.to:8080/job/Forestry_Dev/

Neither links on the [download](http://forestryforminecraft.info/main:downloads) page work, 
I'm getting:  

```
This webpage is not available

ERR_CONNECTION_REFUSED
```

Pls fix? :cry:

PS. Do you have an irc channel I could bother folks for this kind of thing in the future?

**Comment by Nirek-K** [comment]
Those names have been phased out for some time, the actual 'download' link for unstable has the right one: http://jenkins.ic2.player.to/job/Forestry_Dev/ which does work for me.
Will have to get that changed.
#forestry on esper.
