### ISSUE TITLE
Butterflies spread out of control

### ISSUE THREAD

**Issue by leagris** [ForestryMC/ForestryMC#1071]
This is a puzzling issue since age.
Butterflies glitch north, get stuck in unloaded chunks, and because they never dies here they cause immense server load and lag when suddenly loading these chunks.

See example here:
![forestrybutterflyspam](https://cloud.githubusercontent.com/assets/1111474/13197070/63035804-d7e2-11e5-83b0-f770521dc1af.png)
![2016-02-20_14 46 27](https://cloud.githubusercontent.com/assets/1111474/13197072/757c1c8c-d7e2-11e5-9168-51cb490b8fc3.png)

**Comment by leagris** [comment]
Command `/forestry butterfly kill` does not really help because it kills only butterflies in loaded chunks.

If it is possible. I think butterflies life cycle should be handled by internal database to Forestry. This should allow to get butterflies to die even if no corresponding entity is loaded.
It means Butterflies entities should be only representation of internal database of butterflies instead of the actual butterflies instances.

**Comment by mezz** [comment]
Thanks for writing up this report.
It's definitely an issue but the solution is not perfectly clear.
There are some extra complications because butterflies can be bred. If you breed a butterfly, you don't want it to despawn.

**Comment by leagris** [comment]
Player placed butterflies: dropped item that becomes a live butterfly after a few seconds are "tamed" and won't despawn (get infinite lifecycle).
Or if you want it like bees, use pristine flag.
Lifetime does not need to be in a dedicated database but a per-world DB would permit offload genome and all instance specific data from Entity NBT. Just have butterfly entity store a Record ID and rendering info (specie).
Delete butterflies entities and Recreate butterfly entities on chunk-load from DB.
Update location on move, delete record on death/capture as item.
DB would also allow you to restrict range of butterfly. Store birth coordinates and allow some radius. Call it range trait. Birth point is where it has initially spawned.
To keep butterfly in allowed range his speed vector is inverse proportional to its distance from his birth point.

So if butterfly is at 50% or midway of his birthPoint and his maxRange limit, his speed outward would be halved and normal if moving inward.
When at the extreme allowed distance from birth point, it can only move along same distance or inward, but outward speed is 0. Should allow maintaining those random moves while keeping butterfly in a restricted area.
It is like butterfly is tied to his birthpoint by an invisible rubber leash.

**Comment by mezz** [comment]
Looks like the "going north" bug is from vanilla Minecraft, and has been fixed in 1.9: https://bugs.mojang.com/browse/MC-10046

I will still need to look into making butterflies avoid entering unloaded chunks, so they don't clump up like crazy at borders.

**Comment by CovertJaguar** [comment]
I could have sworn I fixed that "going north" bug ages ago in the Butterfly AI, or maybe that was some other pathing bug. I seem to recall there being a few. =P

**Comment by CovertJaguar** [comment]
@leagris It would be pretty simple to add another AI Task that would move Butterfly's toward their "home" position if they stray too far. Just give it a high priority.

The rest of what you describe is way overkill though.

**Comment by mezz** [comment]
I like that idea a lot.
