### ISSUE TITLE
Squeezer oredict support results in unwanted recipes

### ISSUE THREAD

**Issue by rubensworks** [ForestryMC/ForestryMC#1073]
It looks like when registering recipes via `ISqueezerManager#addRecipe` these recipes are generalized to all matching items in the oredictionary.

In EvilCraft for example, I add the squeezer recipe for Undead Log to the Blood fluid.
This Undead Log exist in the oredict as an `logWood`.
This however causes _all_ logs to be squeezable to the Blood fluid, which is not very desirable...

I think this is the source of the problem: https://github.com/ForestryMC/ForestryMC/blob/6d6af6b043301c6b7229dfa4b60bf5e29471179a/src/main/java/forestry/factory/recipes/SqueezerRecipeManager.java#L80-L85
Obviously, removing that block of code might cause some issues with other mods that depend on this behaviour.
I would suggest adding another method to the `ISqueezerManager` that has an option to explicitly disable oredictionary generalization for recipes.

This issue seems to be present in version 1.7.10-4.2.8.896, and has probably existed for a long time.

Source: CyclopsMC/EvilCraft#337

**Comment by rubensworks** [comment]
It looks like this was already reported in #1061, my bad...
I'll leave this issue open because of the suggestion for a solution, feel free to close it anyways.

**Comment by mezz** [comment]
Thanks!
This is linked from the other issue, I will take a closer look when I take on this bug.
