### ISSUE TITLE
Crash during startup with latest RotaryCraft & Forestry

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#1075]
I've sat on this one, because I figured that it would take some time for things to get sorted out after Reika released v10 of RotaryCraft. However, it's been two months, and the issue continues to persist, so I figured I'd at least make a ticket out of it.

The latest versions of RotaryCraft and Forestry are causing the game to crash (specifically, at "Loading - Initializing mods Phase 3", part 5 of 7). How latest, you ask? Well, RotaryCraft is v10d, while the version of Forestry I'm attempting to use is 4.2.8.56... so it's pretty up-to-date.

I've done some searching, but so far, I've seen no references to this issue, so I'm worried I'm doing something wrong. But, lacking anything to go on, I figured I'd post the bug report anyway.

Here's the link to the log from the launcher: http://paste.atlauncher.com/view/4c832b27

I don't know if you can help, but I hope I offered enough information for you to have some idea of what can be done.

**Comment by Nirek-K** [comment]
You have farms/farming disabled?   E:(from the log, Farming module is indeed disabled, and the source of this issue)

E: Give unstable 897 ( http://jenkins.ic2.player.to/job/Forestry_Dev/ ) a try. Should fix your issue.

**Comment by ghost** [comment]
Yup, that worked!  Thanks!

And yes, farms were disabled; that role in the modpack is meant for RotaryCraft fans and Expanded Redstone block breakers.  Forestry's inclusion is mainly for the trees and bees. :)
