### ISSUE TITLE
DragonAPI with forestry 4

### ISSUE THREAD

**Issue by macqo004** [ForestryMC/ForestryMC#1076]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1277638-forestry-for-minecraft-trees-bees-and-more?page=457#c9371

Reika said:
Something invalid is in Forestry's Centrifuge recipes, and the RC centrifuge crashes on loading it. Given my past experiences with their GrowthCraft handler, they probably have a broken mod handler.

could this be solved on your side?

**Comment by Nirek-K** [comment]
Anything unstable 885 or later should fix that. E: Or 4.2.8

**Comment by mezz** [comment]
Duplicate of https://github.com/ForestryMC/ForestryMC/issues/1075, fixed in the latest version of Forestry
