### ISSUE TITLE
NBT data lost

### ISSUE THREAD

**Issue by ResponsibleBear** [ForestryMC/ForestryMC#1083]
Hello. Just watch the video.
Carpenter and worktable bug.
Forestry version 4.2.9.57
https://www.youtube.com/watch?v=iNBBJo8wX_M&feature=youtu.be

**Comment by mezz** [comment]
Thanks for the report!
I am not able to reproduce this issue with nbt items. Which Gregtech are you using, so I can try it?

**Comment by ResponsibleBear** [comment]
Hey there. 
GregTech version is 5.09.19. 
From here http://forum.industrial-craft.net/index.php?page=Thread&threadID=11488

**Comment by BoOmka** [comment]
Gregtech 5.09.22. All GT tools still lose their data.
http://imgur.com/a/BnSYn

That bug works ONLY IN MULTIPLAYER!
Singleplayer works fine.

**Comment by Nedelosk** [comment]
The video is unavailable and I don't think that we will ever fix this so I close this.
