### ISSUE TITLE
Managed Farm puts saplings in upper slots instead of lower slots

### ISSUE THREAD

**Issue by calvissuperman** [ForestryMC/ForestryMC#1087]
I understand this is intentional, and saves time and resources for the player but I think it should be changed. The reason is I am unable to pull the saplings the farm collects from the farm until all 6 slots are filled with saplings. This is a pain for what I am doing and I'm sure others as well. A crucial step to automation is full control of everything, and when the farm controls this aspect I am not able to automate my farm the way I want it to.

I would be just fine with a simple option in the HUD, an option in the config, or even something else. I just want to control the farm to its fullest potential and this one little thing is stopping me. I understand if it's harder to implement than it sounds, and if you have more important actual bugs on your list, but I would genuinely appreciate it if you gave it a chance.

Thank you for your time,
Calvissuperman

**Comment by SandGrainOne** [comment]
Could you say something about "what you are doing"?

**Comment by mezz** [comment]
The farm is very "automatic" right now. I share your concerns, in Forestry for 1.8+ I will most likely break it up a bit.

**Comment by calvissuperman** [comment]
> Could you say something about "what you are doing"? From SandGrainOne

I'm just using a regular managed farm to farm oak saplings. I want to pull the saplings it gets from the farm right away, but instead it puts the saplings in the top slot. This means I have to wait for the farm to get 6*64 oak saplings before it will automatically pull saplings from the bottom like oak wood, and apples.

**Comment by XFactHD** [comment]
How do you want the trees to be replanted when the saplings go to the bottom slots?

**Comment by SandGrainOne** [comment]
I must agree that this was one of the concerns I had when multifarms where introduced. This and the fact that the need to produce humus was removed. I think that humus crafting should be a "factory" on the outside. It isn't hard or complex, but it does give the player a process step to automate. This is also true for the handling of saplings. 

Back to this issue. I don't think the reasoning from calvissuperman is a very good one. It is almost scary how fast a farm can collect 6 stacks of saplings. That being said, introducing something that give the player more control over this part would be great. Just need to think of to what effect.

**Comment by calvissuperman** [comment]
To what XFactHD said, I'm saying I want the sapplings it collects to be brought to the bottom slots, so you can extract them and either use them or put them back into the top slots via a pipe. As long as you get control of all inputs and outputs that's all I want. Obviously by now I've collected 6 stacks of sapplings and it's no longer a problem, but it is kinda off that you have to have 6 stacks of saplings before you can control it. Mezz already replied saying he knows whats up, so I'm satisfied. If he changes it or not I'm pretty fine with it, I just wanted to make sure they knew.
