### ISSUE TITLE
server crash when using backpacks

### ISSUE THREAD

**Issue by HoNGamer** [ForestryMC/ForestryMC#1089]
[crash-2016-03-02_22.53.10-server.txt](https://github.com/ForestryMC/ForestryMC/files/155763/crash-2016-03-02_22.53.10-server.txt)

**Comment by mezz** [comment]
Thanks for the report!
This looks like a crash from another mod that adds backpacks to Forestry.
What type of backpack did you use?

**Comment by HoNGamer** [comment]
Thanks for your answer! 
Yeah you're right. Figured out that it was the addon "More Backpacks-1.7.10-2.2.2" I used your miner's, digger's, forester's and hunter's + metallurgist's and farmer's from the addon. If i remove those it's working all perfect. [Edit]Just figured out that it's the same for all combinations from both mods. Seems like the addon has to leave ;)

**Comment by mezz** [comment]
Can you report this issue to the More Backpacks mod? It would be nice if it worked.
http://minecraft.curseforge.com/projects/chemcraft-more-backpacks
