### ISSUE TITLE
Backpacks not working

### ISSUE THREAD

**Issue by TH3Frag** [ForestryMC/ForestryMC#1090]
When I try to put items into backpacks; such as the miner's backpack; it will not take any items. When I mine things they do not go into the backpack Minecraft - 1.7.10 Forge - 10.13.4.1614 Forestry - 1.7.10-4.2.9.57.

**Comment by SandGrainOne** [comment]
Try to delete the backpack configuration files. Restart the game and see if that helps.

**Comment by TH3Frag** [comment]
Thank you; that did the trick,
