### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#1092]
For our purpuses we need 4.1.1 forestry. For some reason we getting errors during compilation. http://pastebin.com/x6DFnhY5.

**Comment by ensirius** [comment]
Solved. git checkout -b 4.1 origin/4.1.

**Comment by mezz** [comment]
The Forestry API is a git submodule. Cd into the API folder and do 'git submodule init' and then 'git submodule update' and then it should work.

**Comment by ghost** [comment]
Solved! Thanks.
