### ISSUE TITLE
TileWood lost his WoodType

### ISSUE THREAD

**Issue by Nedelosk** [ForestryMC/ForestryMC#1095]
When I place a plank or a other block with a TileWood and loging out and loging in after that . The WoodTye that the TileWood has is always larch on the client side.

**Comment by mezz** [comment]
I am going to make wood into normal blocks again, no tile entities. This issue will be fixed by that change.

**Comment by mezz** [comment]
Fixed by https://github.com/ForestryMC/ForestryMC/commit/0049d1e20d544b0d7d6a97360288568b63213172
