### ISSUE TITLE
Trade station doesn't send letter

### ISSUE THREAD

**Issue by KorDum** [ForestryMC/ForestryMC#1097]
When I send letter to trade station from my mailbox, it say me: "Trade station cannot send the response letter. You needto have a mailbox to deliver to.". But it's my mailbox, owner — my name. It's a bug?
Forestry 4.2.10.58

**Comment by mezz** [comment]
Thanks for the report!
It might be an issue if you placed the mailbox while Mojang's auth servers were down or something. Have you tried picking up and replacing the mailbox?

**Comment by KorDum** [comment]
Yes, I tried picking up and replacing the mailbox again and again after time. No effect.
How my private local server depends on Mojang's auth servers status?

**Comment by XFactHD** [comment]
Because of the player UUID/player profile which is used to "connect" the player to the mailbox.

**Comment by KorDum** [comment]
Hmm. But ordinary letters works fine.

**Comment by KorDum** [comment]
![1](https://cloud.githubusercontent.com/assets/1331559/13722106/e12ea9cc-e84a-11e5-8dc0-b590e13020a1.png)
![2](https://cloud.githubusercontent.com/assets/1331559/13722107/e15e3958-e84a-11e5-83c1-1d843acdd202.png)

"Trade station cannot send the response letter. You need to have a mailbox to deliver to.". Again and again. I own the mailbox.

But ordinary letters works fine. Why?

**Comment by mezz** [comment]
The Trade Station is trying to use exact postage and the ones you have given it have a high value.

**Comment by CovertJaguar** [comment]
I would think a more accurate error message would be called for if that is the case.

**Comment by mezz** [comment]
Absolutely.
