### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Hiranus** [ForestryMC/ForestryMC#1098]
Is there any way to solve this?
It happens as soon as I join to game.

https://gist.github.com/mezz/c478b390815f784a2baa

**Comment by Hiranus** [comment]
Ok, Solved. Minecraft for some odd reason generated parts of the world differently (WTF!?). When i deleted whole area in mcedit problem suddenly fixed itself.

**Comment by mezz** [comment]
Strange, thanks for the follow-up.
