### ISSUE TITLE
Invisible butterflies in itemframes

### ISSUE THREAD

**Issue by Ghostlyr** [ForestryMC/ForestryMC#1102]
![4564665](https://cloud.githubusercontent.com/assets/8511068/13712655/08f7729c-e7ef-11e5-8e2a-245251e2fec9.png)

Using last stable 4.2.10.58 verion. Same issue on last dev build too.
MC 1.7.10 Forge 1614. Tested on singleplayer.
No graphic-optimising mods installed. Only forestry, industrialcraft and NEI.
No errors in client and fml log.

**Comment by mezz** [comment]
Thanks for the report! 
This will probably be resolved in the Minecraft 1.8.9 version of Forestry. I'll leave this issue open though.
