### ISSUE TITLE
Sturdy Casing in inventory crafting output at login

### ISSUE THREAD

**Issue by mezz** [ForestryMC/ForestryMC#1104]
![2016-03-12_16 10 41](https://cloud.githubusercontent.com/assets/916092/13726098/1c676bec-e86d-11e5-9c98-127d9922c5f8.png)

@Nedelosk do you know anything about this? Why is there a sturdy casing there when I join a world?

**Comment by Nedelosk** [comment]
I think that is a problem with the Shape Recipe Costum.
