### ISSUE TITLE
More then one Princess from a Queen

### ISSUE THREAD

**Issue by Hakameda** [ForestryMC/ForestryMC#1110]
Rarely after a cycle completes it produces two pristine princes instead of one.

using Forestry version from Latest Beyond Reality Classic, forestry_1.7.10-4.2.9.57

I personally had it happen with Cultivated and Imperial Bees, Other players saying it happens with other species too.

No binne's Mods, Only Gendustry and Custom Bees from Beyond Reality Makers. I don't think GT bees are enabled currently

**Comment by mezz** [comment]
There is a config option to enable this. It's set to 0.0% by default, but some packs increase it.
Check the `config/forestry/apiculture.cfg` file for `second.princess`.

**Comment by Hakameda** [comment]
I will check in a bit when i get home

**Comment by Hakameda** [comment]
Yeah that was it, Sorry thought it was a bug

**Comment by mezz** [comment]
Thanks for following up, glad it wasn't something else.
