### ISSUE TITLE
Improve IItemHandler Integreation

### ISSUE THREAD

**Issue by Nedelosk** [ForestryMC/ForestryMC#1112]

**Comment by mezz** [comment]
I tested some things with ExtraUtilities transfer pipes which use `IItemHandler` capabilities. It worked fine with our blocks.

What is still needed for this issue?

**Comment by CovertJaguar** [comment]
Last I looked, Forestry didn't wasn't actually setup to feed IItemHandler instances to the inventory manipulation framework. It still assumes everything is IInventory. Maybe this has changed, but updating the Manipulator and Iterator to support IItemHandler was only half the job required to make Forestry fully compliant. It still needed the toolset functions updated to actually look for IItemHandler.

**Comment by mezz** [comment]
I am doing stuff for this now. Time for some Forestry inventory cleanup...
