### ISSUE TITLE
Unidentified item

### ISSUE THREAD

**Issue by vlademer17** [ForestryMC/ForestryMC#1113]
when trying to start up server with latest forestry and magicbees keep getting:

[Server] Server thread/ERROR [FML]: There are unidentified mappings in this world - we are going to attempt to process anyway 
[Server] Server thread/ERROR [FML]: Unidentified item: Forestry:waxCapsuleOil, id 4501 19.03 [Server] Server thread/ERROR [FML]: Unidentified item: Forestry:waxCapsuleFuel, id 4500 19.03  [Server] Server thread/ERROR [FML]: Unidentified item: Forestry:canFuel, id 4490 19.03 
[Server] Server thread/ERROR [FML]: Unidentified item: Forestry:refractoryOil, id 4512 19.03 
[Server] Server thread/ERROR [FML]: Unidentified item: Forestry:refractoryFuel, id 4511 19.03  [Server] Server thread/ERROR [FML]: Unidentified item: Forestry:bucketSeedoil, id 4519 19.03  [Server] Server thread/ERROR [FML]: Unidentified item: Forestry:canOil, id 4491

any ideas?

**Comment by mezz** [comment]
Make sure your server has the same version of Forestry. The latest Forestry removed capsules for liquids that are not available in the world, so if you have no Oil there will be no Oil capsule.
