### ISSUE TITLE
Wood Door Textures

### ISSUE THREAD

**Issue by Nedelosk** [ForestryMC/ForestryMC#1114]
We want to make wood doors for ever Wood type. And for this we need textures for the doors. Can anyone make textures for this ?

**Comment by arrrrik** [comment]
Do you want them to be re-colored vanilla style doors? Or more like the wooden doors from Natura/Witchery with unique looks to them?

EDIT: Also, I can't remember for sure what default texture size is in Forestry, but I'm thinking 16x?

**Comment by mezz** [comment]
All the vanilla doors are unique, so it would be nice to have unique Forestry doors that fit with the vanilla theme. Forestry is 16x.

**Comment by arrrrik** [comment]
Rad. I'll see what I can manage over the next week or so.

**Comment by arrrrik** [comment]
Last question: handles and hinges or no?

**Comment by mezz** [comment]
Yes. Vanilla doors all have hinges, and the wooden ones all have handles.

**Comment by arrrrik** [comment]
Here's the initial doors. Some of them I got a bit, ah, carried away on, so if you're not a fan of the more bold experiments (palm wood comes to mind) let me know and I'll do something more traditional. Also I was indecisive on a few, so there may be a few options for the same wood.

[Doors.zip](https://github.com/ForestryMC/ForestryMC/files/214455/Doors.zip)

**Comment by mezz** [comment]
I think most of them look very good!
Some may need some tweaking to look right in-game, I'll have to try them out next to their woods once they're implemented.
Giganteum could use some more texture/noise, maybe some extremely subtle wood grain.
Palm is interesting, we'll have to see how Minecraft handles the odd shape though. Hopefully it works fine.
All said, I think they look great. Thanks for contributing!

**Comment by arrrrik** [comment]
Took a second whack at Giganteum. This feels a lot better. 

Also, while I'm pulling the colors straight from the texture files, it might still be a bit off since I'm using some garbage internet program and I'm not sure it's processing them correctly. No Photoshop at work is the sad counterbalance to me having a ton of time to make textures at work. 

That said, most of the grains are pulled from the same files, so they should match with a quick HSL adjust on anything that's too "off"

![giganteum door 2](https://cloud.githubusercontent.com/assets/13837806/14454569/3ea60e0c-0069-11e6-896f-330523c6c438.png)

**Comment by CovertJaguar** [comment]
You probably can't install anything on your work comp, but if you can, Paint.net is a great lightweight editor for pixel art.

**Comment by arrrrik** [comment]
Yeah, unfortunately the work comp is a government comp, so I _definitely_ can't install anything.

**Comment by mezz** [comment]
Ok I'm most of the way through implementing these and they look good!
Turns out Palm's shape will not work without a lot of effort. Can you make a rectangular design, @arrrrik ?

**Comment by mezz** [comment]
Here's what we have without palm:

![2016-04-15_21 34 02](https://cloud.githubusercontent.com/assets/916092/14579105/2ebc8ab6-0352-11e6-8aaa-4f931e9f43c3.png)
![2016-04-15_21 34 24](https://cloud.githubusercontent.com/assets/916092/14579106/2ebcac3a-0352-11e6-9638-706c193366ae.png)
![2016-04-15_21 34 39](https://cloud.githubusercontent.com/assets/916092/14579108/2ebe98ec-0352-11e6-83e5-1075adbc3ef4.png)
![2016-04-15_21 34 48](https://cloud.githubusercontent.com/assets/916092/14579107/2ebdea50-0352-11e6-821e-b28d3a3bc04c.png)

I also made door icons to match the vanilla style, which was harder than I expected:
![door-icons](https://cloud.githubusercontent.com/assets/916092/14579114/729ee22e-0352-11e6-9b23-5ff756f05015.png)

I'm really happy with the results! The doors look very nice.

**Comment by arrrrik** [comment]
I'm really happy with how those look in world. The icons look great too!
I can definitely make a regular shaped palm door. I'll have something done tonight.

**Comment by arrrrik** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/13837806/14584610/08a27b4e-041d-11e6-8263-7f9cf9e7fc82.png)

Here's an updated palm door. I went with a "peeling paint" look, showing the palm underneath. Kept the feel tropical while showing the wood color.

**Comment by mezz** [comment]
Hmm it's a good idea but I don't like the painted look in-game with palm wood.
![2016-04-17_11 54 22](https://cloud.githubusercontent.com/assets/916092/14589289/346ae100-0493-11e6-8f53-9ba6f54aaeb9.png)

Maybe if the dominant coloring was palm, with hints of peeling paint?
You can't really paint anything else like that so it's hard to make it match in a bigger design.

**Comment by arrrrik** [comment]
Yeah, I definitely see what you mean. I didn't do this one with the planks next to it, so I forgot to think about that. Kept thinking "Tropical!" to the exclusion of "cohesion!"
![palm door 2](https://cloud.githubusercontent.com/assets/13837806/14590644/f6ca1498-04cd-11e6-9b7e-fa06db09bfd7.png)
I'm not 100% certain this will work the way I want it too, so I'll try and come up with something better tonight. It might! But, you know, maybe not.

**Comment by mezz** [comment]
![2016-04-17_16 00 40](https://cloud.githubusercontent.com/assets/916092/14590686/9c722836-04b5-11e6-8102-f7e220527cc7.png)

It's better than before but I like your other door designs more. 
Maybe you could make something with planks missing, but have the trim still around it to make it fit the rectangle requirement?

**Comment by arrrrik** [comment]
I tried that and it sadly didn't work. I'll try and do an ocean/Caribbean themed cutout for the window.

**Comment by arrrrik** [comment]
Here we go! Nautical palm door. 
![palm nautical](https://cloud.githubusercontent.com/assets/13837806/14593410/25339a0a-04f8-11e6-9e59-4b8bf9e4a758.png)

Thank god I'm making this one at home. So much easier with Photoshop

**Comment by mezz** [comment]
Looks good! There are some transparency issues around the cutout though, some of the door around it is not 100% opaque, and the glass is semi-transparent instead of like the Minecraft style (like the Ipe door).

**Comment by arrrrik** [comment]
Shoot, looks like I forgot to set my eraser opacity to 100. Easy enough fix though.

**Comment by arrrrik** [comment]
![palm door better porthole](https://cloud.githubusercontent.com/assets/13837806/14608501/f3acd29c-0553-11e6-92c1-c468fbe81085.png)

There we go.

**Comment by mezz** [comment]
Thanks! Looking good.

![2016-04-18_14 51 48](https://cloud.githubusercontent.com/assets/916092/14621064/210a5694-0575-11e6-9329-56049131f24e.png)

![doors-icons](https://cloud.githubusercontent.com/assets/916092/14621119/74f68ad4-0575-11e6-9e7a-0df53c85bb4b.png)

**Comment by mezz** [comment]
@arrrrik I just got access to ExtraTrees from Binnie! I want to add their woods to Forestry. 
Would you be able to create 39 new types of doors? No rush heh.

[logs.zip](https://github.com/ForestryMC/ForestryMC/files/329072/logs.zip)
[planks.zip](https://github.com/ForestryMC/ForestryMC/files/329073/planks.zip)

**Comment by arrrrik** [comment]
I can do that!

**Comment by mezz** [comment]
Awesome!
The doors have been getting a lot of use by builders on Forgecraft recently https://twitter.com/Rosespikes/status/744007250755235840

**Comment by arrrrik** [comment]
Oh man, that looks great. I'll probably knock a bunch out on Sunday night and hopefully have most of them done by the end of next week.

**Comment by mezz** [comment]
Sounds good. I still have a lot of work to do with the code involved, so it may take me longer to implement them.

**Comment by arrrrik** [comment]
For a variety of reasons (including the fact that there's just _so many_) it's going a bit slower. But here's what I have so far.
![alder door](https://cloud.githubusercontent.com/assets/13837806/16536646/53a13c3a-3fc2-11e6-8784-7ab461a01180.png)
![apple door](https://cloud.githubusercontent.com/assets/13837806/16536641/539f9d58-3fc2-11e6-8bca-d5887b27e950.png)
![ash door](https://cloud.githubusercontent.com/assets/13837806/16536643/53a0b076-3fc2-11e6-90d7-a876af64e1e3.png)
![beech door](https://cloud.githubusercontent.com/assets/13837806/16536642/539fbf4a-3fc2-11e6-8513-52a353677abf.png)
![box door](https://cloud.githubusercontent.com/assets/13837806/16536644/53a0c700-3fc2-11e6-8f9b-295b1385343f.png)
![brazilwood door](https://cloud.githubusercontent.com/assets/13837806/16536645/53a1815e-3fc2-11e6-8646-ed93dcea7211.png)
![butternut door 1](https://cloud.githubusercontent.com/assets/13837806/16536649/53a8cb12-3fc2-11e6-9414-6715d0c9ccad.png)
![butternut door 2](https://cloud.githubusercontent.com/assets/13837806/16536648/53a7f0e8-3fc2-11e6-9d0b-d452a0023d80.png)
![cedar door](https://cloud.githubusercontent.com/assets/13837806/16536647/53a7adc2-3fc2-11e6-9f53-7fedc01a79fd.png)
![citrus door 2](https://cloud.githubusercontent.com/assets/13837806/16536650/53aa2f20-3fc2-11e6-961b-48367cd44e9f.png)
![citrus door](https://cloud.githubusercontent.com/assets/13837806/16536651/53aa4690-3fc2-11e6-96bf-b19589d920ad.png)
![cypress door](https://cloud.githubusercontent.com/assets/13837806/16536652/53af025c-3fc2-11e6-86f4-b9dd7c5c2b0b.png)
![elder door](https://cloud.githubusercontent.com/assets/13837806/16536653/53afdc4a-3fc2-11e6-9201-e0ee59110ee5.png)

**Comment by mezz** [comment]
Very cool! This is going to take me a while, you have no time pressure.

**Comment by Nedelosk** [comment]
@arrrrik Any new textures ?
