### ISSUE TITLE
Electron tube on centrifuge and squeezer

### ISSUE THREAD

**Issue by roxasivolain90** [ForestryMC/ForestryMC#1115]
It seems like that i can't install electron tube on squeezer and centrifuge in forestry 4.2.10.58 on the infinity evolved 2.4.2 pack, i don't know what i can do for resolving this problem. Maybe some config is disabled but i didn't find anything.

**Comment by roxasivolain90** [comment]
him stupid

**Comment by mezz** [comment]
Was it because you need a circuit board? Easy mistake.
