### ISSUE TITLE
Radioactive effect of Avenging bees

### ISSUE THREAD

**Issue by Mornyngstar** [ForestryMC/ForestryMC#1117]
I recently upgraded to the newest 1.7.10-4.2.10.58 version of Forestry (also have Buildcraft, Thermal expansion, Nether ore, REI minimap and Chicken Chunks). 
While upgrading some of my bees for new traits from Avenging bees I was getting damaged from the Radioactive effect. I did have an Apiarist Suit on(made before updating version). 
I then made a new Apiarist suit just in case there was a difference between the old one I had and the updated version. I still had the same problem with taking damage. This did not happen before when I originally bred the Avenging bees.

Is this something that is a bug or what is now going to happen with the bees?

I even tried making a full lead suit to protect me (it didn't work). Also tried peaceful mode (still didn't work).

**Comment by mezz** [comment]
Thanks for the report!
Sounds like a bug to me, I'll take a look.

**Comment by mezz** [comment]
Looks like the suit was only protecting half the damage at best, which is not intentional.
