### ISSUE TITLE
Liquid Honey doesnt get sorted with Buildcraft Diamond Fluid Pipe or pumped by pump.

### ISSUE THREAD

**Issue by Elfblood** [ForestryMC/ForestryMC#1118]
Using Forestry 4.2.10.58,
Forge 10.13.4.1566
and Buildcraft 7.1.4

Iam unable to sort Liquid Honey from Squeezers with Diamond Fluid Pipes. It only flows through unfiltered slots.

Also Liquid Honey doesnt seem to get pumped up by a pump.(related?)
Tested with a 1x2 Hole, and put 2 Buckets of Honey in it. The Pump extends his siphon, but doesnt start. Same Setup works with Lava or Water.

**Comment by Nirek-K** [comment]
Does the pump normally work on other fluids than lava/water/oil? Don't remember.
For the filter, please check that you are filtering the correct type of honey (there are atleast 2, one of which is legacy honey/same honey that BoP uses)

**Comment by Elfblood** [comment]
Thx for reply, I have to verify the honey type again later.

**Comment by Elfblood** [comment]
Feeling Dumb now, indeed I confused the 2 Honey types.
Pumps work on the Forestry one also.
Im closing this.

**Comment by Nirek-K** [comment]
Glad you got it resolved. (legacy honey indeed looks the same as the current one, and can be confusing)
