### ISSUE TITLE
FTB Infinity Evolved - Backpack problem

### ISSUE THREAD

**Issue by Milerind** [ForestryMC/ForestryMC#1119]
Forestry 4 2 10 58

My Backpacks doesnt work. 
I tried 5 of the 15 Slots Backpacks in diffent Modes and all of them cant pickup items. Restarted Minecraft but it didnt help.

**Comment by mezz** [comment]
Thanks for the report!
You should delete your backpack config file, `config/forestry/backpacks.cfg`

**Comment by mezz** [comment]
Dupe of #1090

**Comment by Krivenchuk-Artem** [comment]
До сих пору существует это проблема, хд
