### ISSUE TITLE
Crash when looking up recipes in NEI

### ISSUE THREAD

**Issue by lilmoefow** [ForestryMC/ForestryMC#1120]
I reported this to Evilecraft as welll, but im also gonna leave it here, was only getting this crash when looking up the recipes for blood while in the gui of evilcraft's blood infuser

when i left click here http://imgur.com/YFsxp5k
it crashes the client

http://pastebin.com/xK70kd0p

Forge 1.7.10 - 10.13.4.1614
EvilCraft-1.7.10-0.9.5.jar
forestry_1.7.10-4.2.11.59.jar
NotEnoughItems-1.7.10-1.0.5.118-universal.jar
CodeChickenCore-1.7.10-1.0.7.47-universal.jar

**Comment by lilmoefow** [comment]
updated NEI and still getting same crash

NotEnoughItems-1.7.10-1.0.5.120-universal.jar

**Comment by Nedelosk** [comment]
I close this because I think we don't will fix this.

**Comment by lilmoefow** [comment]
lol, i didn't even know it was still open.  It was Fixed on Evil Crafts side while back.
