### ISSUE TITLE
Worktable crash

### ISSUE THREAD

**Issue by JasonMcRay** [ForestryMC/ForestryMC#1121]
Shift-clicking the water-bucket-to-pams-fresh-water recipe crashes the game. It freezes the client for few seconds and then crashes.

Pams Harvestcraft 1.7.10Lb
Forestry 4.2.11.59

Crash log: http://pastebin.com/h8qixKsq

Was able to reproduce successfully (2/2 times) Only happens when shift-clicking; clicking for a single execution of the recipe does not seem to create problems. And other crafting tables work fine

**Comment by JasonMcRay** [comment]
@mezz Is this going to be fixed in 1.7.10? Or are you moving fully to 1.8/1.9 dev?

**Comment by mezz** [comment]
I have been focused entirely on moving the mod to 1.9. 
If I fix it I may backport the fix to 1.7.10, but it is not a high priority bug at the moment.

**Comment by JasonMcRay** [comment]
Cool thanks for letting me know.

**Comment by lexjusto** [comment]
serious problem!

**Comment by Nedelosk** [comment]
This issue is nearly 2 years old. I don't think anyone will fix this bug.
