### ISSUE TITLE
Ender bees just give one drone

### ISSUE THREAD

**Issue by Furchendackel** [ForestryMC/ForestryMC#1122]
While breeding ender bees I noticed that they give you just one princess and one drone after the queen has reached its end of life - pretty bad for breeding them.

My Alveary is in a plains biome, cooled down to cold temperature, dragon egg nearby.

Forge: 10.13.4.1614
Forestry: 4.2.11.59

Other mods: AE2, Buildcraft, Buildcraft-compat, IC2 experimental, Thermal Foundation+Expansion+Dynamics, Railcraft, MinefactoryReloaded
All mods are at their latest available version (no betas or similar).

**Comment by SandGrainOne** [comment]
Please check the fertility trait. I think the Ender species should give 2 drones, but it might have changed in later versions of Forestry.

To breed them your would need to mix in another species with higher fertility and then attemt to purify it again.

**Comment by Furchendackel** [comment]
Fertility according to beealyzer is one drone, but I doubt this is really intended? Since I got only 4 princesses and 3 drones out of all the end hives, chances are high to mess things up while trying to cross breed and purify again.
Okay, I can still delete the end dimension and harvest the bees again, but I doubt that this is intended nor practicable for everyone.

**Comment by SandGrainOne** [comment]
Take a princess from another species with fertility of 4 and breed it with an Ender drone. This will give you 4 hybrid drones and plenty of chances to purify it again with higher fertility. 
But yes, there is a risk involved.

**Comment by Mornyngstar** [comment]
Ender bees have a fertility of 1,  So do other bees. This means breeding carefully so you don't breed out the species. I normally focus on getting them to the fertility rate of 2 or 4 along with the species locked in, after that I will breed back to a pure species with the exception of fertility. (currently working on Ender right now)

**Comment by SandGrainOne** [comment]
All wiki pages I have found (looked for) have said that Ender Bees have fertility of 2 so it can't be THAT long since it changed. I'm keeping this open to have the new value confirmed.

**Comment by Nirek-K** [comment]
Ender bees are indeed Fertility 1, and have been..since as far back as I can find. Suggestions here are all good ways to try getting higher fertility bees. (there is also genetic manipulation if you have either mod that provides that). And as of https://github.com/ForestryMC/ForestryMC/commit/98c56973db73b0b00ca1dee6fca7f5f07701de46 you can look to Aparists to avoid their complete extinction.
