### ISSUE TITLE
unable to load any world

### ISSUE THREAD

**Issue by Blue-Beaker** [ForestryMC/ForestryMC#1125]
When I was trying to open any world,It always return back to the title screen. Not crash.
No crash report has created.
mod list:
![image](https://cloud.githubusercontent.com/assets/17115547/14409973/ef885d26-ff54-11e5-8a0e-7448ca6dea25.png)
Version of the forestry mod is 4.2.11.59.

**Comment by mezz** [comment]
Thanks for the report!
Can you paste your client log to https://gist.github.com/ ?

**Comment by Blue-Beaker** [comment]
Sorry,I can't reach this site. Maybe it's blocked.

**Comment by mezz** [comment]
It's the same site we are on now... Try http instead of https maybe? http://gist.github.com/

**Comment by Blue-Beaker** [comment]
Oh,I reached this site by dnscrypt. Where is the client log?

**Comment by mezz** [comment]
Logs are in the `logs` folder of your minecraft folder. They're near the `resourcepacks` folder, `mods` folder, `crash-reports` folder, etc.

**Comment by ThatGuyDiamond** [comment]
Hello, Mezz, I don't know if i can write here or not, But i got the same bug as him.
I have over 150 mods in my modpack and i loved your mod, Forestry. But when loading a world, It just returns me back to the main menu..
Here is the logs when trying to load the world
https://gist.github.com/ThatGuyDiamond/83bf03ce6137061dbba203b655d44e4a
If you want the logs of when minecraft is starting, Tell me. I'd be thankful if you fix this fast. As i really want to play my modpack.

**Comment by mezz** [comment]
@ThatGuyDiamond Try updating or removing NotEnoughResources, it's causing your crash.
