### ISSUE TITLE
[Crash] java.lang.IllegalArgumentException: Adding a dirty controller to a world that has no registered controllers!

### ISSUE THREAD

**Issue by wormzjl** [ForestryMC/ForestryMC#1132]
full log
http://pastebin.com/3QyRTbs8

**Comment by Carrots4U** [comment]
Happened to our server today running the latest forestry for 1.10.2.

**Comment by Nedelosk** [comment]
@mezz Any idea what could cause this ?

**Comment by mezz** [comment]
I am not sure. The multiblock code is ported from Big Reactors, and it gets this error very rarely. I have not been able to reproduce it.

**Comment by Nedelosk** [comment]
Not occurred for a long time. I close this and reopen it if it occurs again.

**Comment by Bjonnfesk** [comment]
> Not occurred for a long time. I close this and reopen it if it occurs again.

That timing was really, really unfortunate. It just happened again. #2530
