### ISSUE TITLE
Butterfly name error

### ISSUE THREAD

**Issue by Mornyngstar** [ForestryMC/ForestryMC#1133]
Forestry 1.7.10-4.2.11.59

![picture1](https://cloud.githubusercontent.com/assets/17998468/14768189/24b341c8-0a09-11e6-905c-dc70bd984714.jpg)

This is a Minor Bug.

**Comment by Nirek-K** [comment]
It got accidently renamed from latticed in the refactor in Oct/2015, will rename the langs for the next unstable push.

**Comment by Nirek-K** [comment]
Should be fixed in unstable 909+
