### ISSUE TITLE
Austere Bees

### ISSUE THREAD

**Issue by Mornyngstar** [ForestryMC/ForestryMC#1134]
Forestry 1.7.10-4.2.11.59
I am not sure if this a bug or a normal feature for the Austere bees, but when I bred them to the best in each category with Explorer effect they stopped producing Powdery Combs. I plan on breeding them back to Creeper effect and see if this fixes them.

![picture2](https://cloud.githubusercontent.com/assets/17998468/14768216/ef66fda6-0a09-11e6-8352-f4c4d5ad51bc.jpg)
![picture3](https://cloud.githubusercontent.com/assets/17998468/14768221/1e65f490-0a0a-11e6-9e96-d74645782c5d.jpg)
![picture4](https://cloud.githubusercontent.com/assets/17998468/14768227/3dd33158-0a0a-11e6-8fde-13f4965ed0a9.jpg)

**Comment by Nirek-K** [comment]
If outside of their prefered climate they will not (basically if they won't run with None/None.

**Comment by mezz** [comment]
Thanks for the report!
You need a Hot/Arid climate (or simulate it in the Alveary) in order to make these bees "jubilant". They will only produce their specialty if they are jubilant.
