### ISSUE TITLE
Fireproof Log Compatibility

### ISSUE THREAD

**Issue by jjc54** [ForestryMC/ForestryMC#1136]
Would it be possible to add all oredict "logs" and "planks" to the fireproof system in Forestry? I thought I could make Greatwood Trees or just the vanilla logs fireproof but it seems I can't, in 1.7.10 at least. Just a nifty feature, thanks!

**Comment by CovertJaguar** [comment]
If I had to guess, I'd say this depends on overriding the fire spread functions on Block. I don't think this is something you can just "add" a block to without being able to edit its class file. But I haven't looked at it so I could be wrong.

**Comment by mezz** [comment]
This has me thinking, it might be possible to do this in 1.8+ by making new blocks and using the block models from the regular woods.

**Comment by jjc54** [comment]
Oh cool! I just wanted to get the conversation started while you are in the midst of updating just in case it is possible to do in the newer versions.

**Comment by mezz** [comment]
After looking into this, there is no easy way to do it without creating lots of tile entities or creating tons of new blocks. I'm going to just stick to forestry woods and work on adding fireproof variants of vanilla (see https://github.com/ForestryMC/ForestryMC/issues/1028).
