### ISSUE TITLE
Some error icons are missing

### ISSUE THREAD

**Issue by mezz** [ForestryMC/ForestryMC#1143]
Error messages for some things are missing icons, it just has a blank space where the icon goes.

Requires Redstone
Missing Resources
Missing Liquid Resources

Check for others as well, there may be more.

![2016-04-27_19 11 42](https://cloud.githubusercontent.com/assets/916092/14873480/ea29cc98-0cab-11e6-8ced-1f242bc502ff.png)

**Comment by Yulife** [comment]
What will the png names be? :) Then I could make them ASAP for Unity.
