### ISSUE TITLE
Escritoire item is facing the wrong way

### ISSUE THREAD

**Issue by mezz** [ForestryMC/ForestryMC#1146]
It is facing back/right, it should be facing forward/right like the other item blocks.

![2016-04-27_19 21 50](https://cloud.githubusercontent.com/assets/916092/14873611/4fd4c678-0cad-11e6-8bb4-bc3cfd704571.png)

**Comment by Nedelosk** [comment]
![2016-04-29_20 03 54](https://cloud.githubusercontent.com/assets/10259214/14925012/81718092-0e45-11e6-904c-49ca09a3a3e3.png)
