### ISSUE TITLE
Many items are held at the wrong angle or are the wrong size

### ISSUE THREAD

**Issue by mezz** [ForestryMC/ForestryMC#1147]
In first-person, many items are rotated strangely and held too low.
In third-person, they also have rotation issues and may be too big.

![2016-04-27_19 46 08](https://cloud.githubusercontent.com/assets/916092/14873986/b6598610-0cb0-11e6-9afa-053be5a87ea9.png)

![2016-04-27_19 45 15](https://cloud.githubusercontent.com/assets/916092/14873984/ae50fdea-0cb0-11e6-85b7-4d5551074191.png)

**Comment by Nedelosk** [comment]
![2016-04-29_20 00 10](https://cloud.githubusercontent.com/assets/10259214/14924983/5bbef834-0e45-11e6-8c7c-0609ae87d3c1.png)
![2016-04-29_20 00 13](https://cloud.githubusercontent.com/assets/10259214/14924988/6323d3c4-0e45-11e6-94b8-783a7399cdfc.png)
