### ISSUE TITLE
Cocoon Item Texture

### ISSUE THREAD

**Issue by Nedelosk** [ForestryMC/ForestryMC#1148]
Can anyone make textures for a cocoon item ?
We need 3 textures for 3 ages of the cocoon.

**Comment by mezz** [comment]
Can we use the block model? I think most vanilla things use the block model except for doors and minecarts.

**Comment by mezz** [comment]
For reference, the Cocoon block looks like this:
![2016-04-30_02 38 35](https://cloud.githubusercontent.com/assets/916092/14935164/b91cfbb6-0e7c-11e6-8526-cbb843b50b31.png)

**Comment by Yulife** [comment]
I made some models and some corresponding item textures :)
![2016-04-30_14-26-40](https://cloud.githubusercontent.com/assets/8559428/14935883/c9a5e82a-0ee1-11e6-872a-23934c798c26.gif)
[Download](https://www.dropbox.com/s/nhpkxyxpjkaxb23/Cocoons.zip?dl=0)

**Comment by Nedelosk** [comment]
Thanks! Looking good.

**Comment by mezz** [comment]
@Yulife they look extremely good, thanks..

**Comment by Yulife** [comment]
No problem :) If you need more models just ask
