### ISSUE TITLE
Error Icons that are used for 2 different errors do not display

### ISSUE THREAD

**Issue by mezz** [ForestryMC/ForestryMC#1151]
Here is one example:

![2016-04-30_01 22 07](https://cloud.githubusercontent.com/assets/916092/14934815/fae9a3b0-0e71-11e6-922d-05fc147768a0.png)

![2016-04-30_01 20 28](https://cloud.githubusercontent.com/assets/916092/14934806/cebe2040-0e71-11e6-9ef6-6f68eb876641.png)

The same "noLiquid" icon is used by multiple `EnumErrorCode`s.

It works for `NO_RESOURCE_LIQUID` but is missing for `NO_SPACE_TANK` .

**Comment by Nedelosk** [comment]
![2016-05-01_13 24 56](https://cloud.githubusercontent.com/assets/10259214/14941555/198f928c-0fa0-11e6-94a0-6e298c2a8dce.png)
