### ISSUE TITLE
Farm Multiblock crash

### ISSUE THREAD

**Issue by jjc54** [ForestryMC/ForestryMC#1158]
MC: 1.9
Forge: forge-12.16.1.1898
Forestry: forestry_1.9-5.0.0.8
Optifine: OptiFine_1.9.0_HD_U_B3

Crash upon placing a multblock farm related block
Crash log: http://pastebin.com/5c8Nf0QU

**Comment by mezz** [comment]
Thanks!

**Comment by Nedelosk** [comment]
Fixed
