### ISSUE TITLE
Treealyzer Shift Click 

### ISSUE THREAD

**Issue by jjc54** [ForestryMC/ForestryMC#1160]
MC: 1.9
 Forge: forge-12.16.1.1898
 Forestry: forestry_1.9-5.0.0.8
 Optifine: OptiFine_1.9.0_HD_U_B3

Can't shift-click trees or honey in like you can in the other analyzers.

**Comment by mezz** [comment]
Do you mean Beealyzer or Treealyzer? Bees or Trees? You have Treealyzer + Bee in your report.

**Comment by jjc54** [comment]
Oh sorry for that typo, this is just for the treealyzer. Beealyzer works fine!

**Comment by mezz** [comment]
Thanks!

**Comment by Nedelosk** [comment]
I can shift-click trees or honey in the treealyzer.

**Comment by mezz** [comment]
@Nedelosk can you shift-click vanilla saplings too?

**Comment by jjc54** [comment]
Yeah it's fixed now for some weird reason. Maybe it was a false alarm:/
