### ISSUE TITLE
Backpack persists upon item switching

### ISSUE THREAD

**Issue by jjc54** [ForestryMC/ForestryMC#1162]
MC: 1.9
 Forge: forge-12.16.1.1898
 Forestry: forestry_1.9-5.0.0.8
 Optifine: OptiFine_1.9.0_HD_U_B3

Watch the hotbar in the images. When switching from a backpack to another item in the hotbar, the backpack is still displayed as being held.
Screenshots: http://imgur.com/a/yYM8v

**Comment by mezz** [comment]
I think this is from a change I made, I'll take a look.
