### ISSUE TITLE
Reloading Textures breaks Crate Textures

### ISSUE THREAD

**Issue by jjc54** [ForestryMC/ForestryMC#1163]
MC: 1.9
 Forge: forge-12.16.1.1898
 Forestry: forestry_1.9-5.0.0.8
 Optifine: OptiFine_1.9.0_HD_U_B3

Looking through the carpenter recipes there are some weird ones in there.
Screenshots: http://imgur.com/a/meXW5

**Comment by jjc54** [comment]
This issue is mainly with the crate texture looking like the cherry door texture.

**Comment by mezz** [comment]
I think the bug here is that the crate texture bugs out when textures are reloaded for any reason. 
Can you force a texture reload with F3+T to check?

**Comment by jjc54** [comment]
Hmm I just tried that and they still look like cherry doors. However, restarting my instance works and they look like crates again!

**Comment by mezz** [comment]
My guess is that if the crates look correct and you press F3+T, it will break them. Can you confirm?

**Comment by jjc54** [comment]
Correct. Loading any resourcepacks does the same.

**Comment by mezz** [comment]
Ok thanks
