### ISSUE TITLE
Circuit board recipes missing from JEI

### ISSUE THREAD

**Issue by jjc54** [ForestryMC/ForestryMC#1165]
MC: 1.9
 Forge: forge-12.16.1.1898
 Forestry: forestry_1.9-5.0.0.8
 Optifine: OptiFine_1.9.0_HD_U_B3

All 4 circuit board types have no recipes.

**Comment by mezz** [comment]
Missing from JEI or unable to craft in the carpenter?

**Comment by jjc54** [comment]
Umm they are still craftable. When I craft one it allows me to view it's recipe. However, I cannot view the recipe if just scrolling through JEI and clicking on it.

**Comment by mezz** [comment]
Ok thanks.
