### ISSUE TITLE
Raintank not doing it's job

### ISSUE THREAD

**Issue by jjc54** [ForestryMC/ForestryMC#1166]
MC: 1.9
 Forge: forge-12.16.1.1898
 Forestry: forestry_1.9-5.0.0.8
 Optifine: OptiFine_1.9.0_HD_U_B3

Raintank does not collect rain when it is raining.

**Comment by mezz** [comment]
Are you in a desert or under a roof? It should only collect if rain is actually hitting it.
(I am not surprised if it's broken, I just need to make sure)

**Comment by jjc54** [comment]
I thought that was the case too. Tested first in a dry/arid biome, then moved to a normal/normal. Has clear access to the sky but still won't collect water.
