### ISSUE TITLE
Crash on startup (Missing RF API in jar)

### ISSUE THREAD

**Issue by auboli77** [ForestryMC/ForestryMC#1168]
Crash on launch, with not other mods, just forestry and forge. If I add McJtyLib Minecraft launches and works fine. 
Using: 
Forge 12.16.1.1904
Forestry 1.9-5.0.0.10
McJtyLib 1.9.0-1.8.4(Does not crash if you use this)

http://pastebin.com/dmLcSQqa

**Comment by mezz** [comment]
Thanks for the report!
This probably means we're missing RF from our jar.
