### ISSUE TITLE
Bee life cycle indicator desync

### ISSUE THREAD

**Issue by auboli77** [ForestryMC/ForestryMC#1171]
Life cycle indicator inside apiary and beehouse shows bee is still working..(alveary seems to work fine) Reloading the word or unloading and reloading chunks fixes it. 

Using:
Forge 12.16.1.1904
Forestry 1.9-5.0.0.10

![](https://i.imgur.com/XfzjnLo.png)

**Comment by mezz** [comment]
I wasn't able to reproduce the issue in the latest version. Please try it out and let me know if this problem has been fixed for you.

![2016-05-19_02 16 38](https://cloud.githubusercontent.com/assets/916092/15388678/ee0ccb54-1d67-11e6-8fd9-73d30a17881f.png)

**Comment by auboli77** [comment]
Still a problem using:
Forge 12.16.1.1907
Forestry 1.9-5.0.0.30

I place down an apiary and put a queen inside, then close the GUI and open it some time later(before queen dies). Then I close the GUI again and don't open until queen dies.

**Comment by mezz** [comment]
Thanks, with the new steps I was able to find and solve the problem. Please let me know if you see a desync again.
