### ISSUE TITLE
Leaves stack size

### ISSUE THREAD

**Issue by auboli77** [ForestryMC/ForestryMC#1182]
When a tree is grown leaves look fine, if I shear a few leaves they change. On pictures, waila shows what stack sizes they are, it will drop that many leaf blocks if sheard. In the end stack size drops to 0. 
At this point you can't get the leaf block, but it will still drop saplings. 

https://imgur.com/a/1V1hY

Using:
Forge 12.16.1.1906
Forestry 1.9-5.0.0.21

**Comment by mezz** [comment]
Thanks for the report!
Probably mixing up stack size and metadata for the dropped stack.
