### ISSUE TITLE
Portable alyzer

### ISSUE THREAD

**Issue by auboli77** [ForestryMC/ForestryMC#1183]
Crash when shift clicking honey drops into portable alyzer with saplings inside. Steps used: shift click vanilla saplings inside, then shift click honey drops. 
Also portable alyzer will not take honey drops or honeydew if there is no bee/sapling/butterfly inside it. And texture is not working. 

http://pastebin.com/vQGUfMwL

Using:
Forge 12.16.1.1906
Forestry 1.9-5.0.0.21

**Comment by LuxusDarkangel** [comment]
Portable Alyzer is still missing texture and model. 
Log if needed: http://pastebin.com/UZ7h3xSz

**Comment by mezz** [comment]
Can you make a new issue @LuxusDarkangel ? Things often get overlooked when there are too many reports in the same issue.

**Comment by LuxusDarkangel** [comment]
Sure, #1196
