### ISSUE TITLE
Grafters doesn't take damage + no recipe

### ISSUE THREAD

**Issue by LuigiHutch** [ForestryMC/ForestryMC#1188]
Tested with:
Forge 12.16.1.1906
Forestry 1.9-5.0.0.21

Two grafter issues:
- [ ] Neither of the grafters seem to take damage when breaking leaves.
- [ ] The proven grafter doen't seem to have a recipe but the normal grafter has a recipe

**Comment by Nirek-K** [comment]
Proven frames and grafters are a villager trading thing. (which may not be implemented in 1.9 yet)

**Comment by LuigiHutch** [comment]
Ah, good to know :)

**Comment by auboli77** [comment]
Grafters only work on forestry leaf blocks, they take damage and drop saplings as expected. 
On vanilla trees they don't take damage and they don't drop saplings every time. 
This may be intended behavior.

**Comment by mezz** [comment]
The grafter only give 100% sapling drop chance on Forestry leaves, so it should only take damage on those.

**Comment by LuigiHutch** [comment]
Ah yes, that is correct. Sorry for the false bug report! Closing
