### ISSUE TITLE
Random crash, prevents world load

### ISSUE THREAD

**Issue by lanAnderson** [ForestryMC/ForestryMC#1192]
Not sure if this one is strictly Forestry related, but the only way the world would load again was if Forestry was removed.

[Crash report](http://pastebin.com/0LzCJpQ4)
[When trying to reload world](https://paste.ee/p/7cvYW)

**Comment by mezz** [comment]
Thanks for the report!
The first report shows a crash with WAILA.
The second one shows a crash from Resourceful crops `An unknown persistent registry type "resourcefulcrops:seeds" has been encountered. This Forge instance cannot understand it.`.
Try updating those mods. If you still crash, you should report to the one that is crashing you.
