### ISSUE TITLE
Charcoal pile

### ISSUE THREAD

**Issue by Nedelosk** [ForestryMC/ForestryMC#1193]
I have the idea to add charcoal pile to forestry.
What do you think about that ?

That are the result from my first try to implement that.
![2016-04-07_03 35 51](https://cloud.githubusercontent.com/assets/10259214/15370456/6876ddf2-1d37-11e6-8d6a-3c96ce687825.png)

**Comment by mezz** [comment]
I like this idea, I think it makes sense as a feature for Forestry.

TerrafirmaCraft already has a very similar feature: http://wiki.terrafirmacraft.com/Charcoal
You may want to look there for inspiration and discuss with @Kittychanley (current TFC dev)

**Comment by Yulife** [comment]
As for the aesthetics, maybe try out stairs instead of slopes? Slopes don't look very minecraft-esque, unless you have Carpenter's in your pack.
