### ISSUE TITLE
Crash on item render.

### ISSUE THREAD

**Issue by LuxusDarkangel** [ForestryMC/ForestryMC#1194]
Forestry version: 5.0.0.22
Forge version: 12.16.1.1907
Crash report: http://pastebin.com/fLGGXiFd
Steps to reproduce: Open the apiculture creative tab and scroll down, it will crash when you reach the problematic item.

**Comment by mezz** [comment]
Thanks for the report!
Looks like I accidentally imported JEI's Translator class instead of Forestry's.
