### ISSUE TITLE
Problem loading loot tables on startup

### ISSUE THREAD

**Issue by LuxusDarkangel** [ForestryMC/ForestryMC#1195]
Forestry version: 5.0.0.22
Forge version: 12.16.1.1907
Log: http://pastebin.com/DXZC44YH

**Comment by mezz** [comment]
Thanks for the report!
Working on this one now.

**Comment by mezz** [comment]
Relates to this: https://github.com/MinecraftForge/MinecraftForge/issues/2860
I had a bad understanding of how the loot tables should be formatted.
