### ISSUE TITLE
Portable Alyzer still missing model and texture

### ISSUE THREAD

**Issue by LuxusDarkangel** [ForestryMC/ForestryMC#1196]
Log if needed: http://pastebin.com/UZ7h3xSz

**Comment by mezz** [comment]
Looks fine to me on the latest version. Maybe your version isn't up to date?

![2016-05-19_01 21 19](https://cloud.githubusercontent.com/assets/916092/15387115/0fb369f0-1d60-11e6-9256-0946d9b9e2a9.png)

**Comment by LuxusDarkangel** [comment]
Sorry, I was using the same version I used in the other reports (latest at that moment:5.0.0.22)
Keeps happening in 5.0.0.26, and in this version engines are missing textures too.
http://i.imgur.com/sbZWRnL.png
http://i.imgur.com/pbJoEnh.png
