### ISSUE TITLE
[Suggestion] Bee particles should be more sporadic

### ISSUE THREAD

**Issue by LuxusDarkangel** [ForestryMC/ForestryMC#1197]
Right now they look more like flying ants instead of bees. The animation looks cool but should be a lot more casual.

**Comment by mezz** [comment]
It's a good suggestion. First I wanted to test that I can get the bees doing something orderly, next I want to make some of the bees go randomly exploring, flying around players, etc.

**Comment by mezz** [comment]
Improved the bee particles. Some will randomly wander, some will fly at the player. All of them are a bit more randomized so they don't make perfectly straight lines.
