### ISSUE TITLE
Untextured particles

### ISSUE THREAD

**Issue by auboli77** [ForestryMC/ForestryMC#1200]
These blocks have untextured particles when running/jumping on them:
- all three chests
- Escritoire
- Analyzer
- all three engines
- Still
- Bottler
- Carpenter
- Squeezer
- Moistener
- Fermenter
- Centrifuge
- Rainmaker

Using:
Forge 12.16.1.1907
Forestry 1.9-5.0.0.31

**Comment by mezz** [comment]
After looking deeper into this for a while, it looks like the easiest way is to define those models in JSON. This is something we need to do anyway.

**Comment by mezz** [comment]
note to self:
LatvianModder has pointed out that it's possible to include a JSON file just to define the particle textures, and it's what he did for IronChests.
See https://github.com/LatvianModder/ironchest/blob/master/src/main/resources/assets/ironchest/blockstates/BlockIronChest.json#L11

**Comment by CovertJaguar** [comment]
Oh? I'll probably need that too. 

Probably easier/better than fixing the particle override code (which I think is doable without too much effort, but this is better).
