### ISSUE TITLE
Greenhouse multiblock condition

### ISSUE THREAD

**Issue by auboli77** [ForestryMC/ForestryMC#1201]
Greenhouse on picture 1 is not recognised as valid multiblock on picture 2 it works. Multiblock should probably require whole ring on top level or none.

https://imgur.com/a/JDNEp

Using:
Forge 12.16.1.1907
Forestry 1.9-5.0.0.31

**Comment by Nedelosk** [comment]
This is not a bug. The greenhouse blocks have to be connected with another block.
