### ISSUE TITLE
Portable Alyzer

### ISSUE THREAD

**Issue by auboli77** [ForestryMC/ForestryMC#1216]
Portable Alyzer fuel slot is not accessible if there is no bee/sapling/butterfly inside it. 
Help tab says it needs specimen first, but I think it should be able take fuel first as well.

Using:
Forge 12.16.1.1907
Forestry 1.9-5.0.0.31

**Comment by auboli77** [comment]
Found few more problems:
- [x] Can't shift click items into Portable Alyzer.
- [x] Can't see info about already analized items when placing them directly to slots I, II, III, IV or V. Need to put items into slot ? first and then you can move them to all slots.
- [ ] Items won't pocess if you move your cursor at the moment you place them into Portable Alyzer. You can get it to process if you click on any slot in Portable Alyzer GUI.

This is on Forestry 1.9-5.0.0.42

**Comment by auboli77** [comment]
This issue is not fully fixed.

https://www.youtube.com/watch?v=W8KL-Na5n-c

**Comment by mezz** [comment]
Hm is was working fine for me. Are you on a server, or anything else you can tell me about your setup?

**Comment by auboli77** [comment]
I tested in singleplayer world. 

Using:
Forge 12.16.1.1907
Forestry 1.9-5.0.0.82
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

**Comment by auboli77** [comment]
You can just click to put items in that slot and move the mouse without releasing your mouse button, move it by one pixel and release, it will not process.
