### ISSUE TITLE
Crash trying to grow a jungle sapling with bonemeal

### ISSUE THREAD

**Issue by auboli77** [ForestryMC/ForestryMC#1219]
http://pastebin.com/5SjTiESa

Using:
Forge 12.16.1.1907
Forestry 1.9-5.0.0.32

**Comment by mezz** [comment]
Thanks for the report!
Can you please paste it again to https://gist.github.com/ ? Pastebin is down right now so I can't access the crash report, and gist is nicer to use imo.

**Comment by auboli77** [comment]
Sure thing, will use gist from now on.
https://gist.github.com/auboli77/e6ad61dd968e81effdba863044b5c56d
