### ISSUE TITLE
Some trees are desyncing and growing without leaves

### ISSUE THREAD

**Issue by auboli77** [ForestryMC/ForestryMC#1221]
Papaya, Date Palm and Jungle trees desync when grown with bonemeal, there is only one block shown on the client side(picture 1). When blocks are updated there is only tree trunk, no leaves(picture 2).

https://imgur.com/a/bkm8J

Using:
Forge 12.16.1.1907
Forestry 1.9-5.0.0.34

**Comment by auboli77** [comment]
This is fixed, can't reproduce in Forestry 1.9-5.0.0.37.

**Comment by mezz** [comment]
The trees were crashing when they started to generate fruit/cocoa pods, I think that was causing weird things like this.
