### ISSUE TITLE
Apiarist Villager has broken trade

### ISSUE THREAD

**Issue by PsychotycGoat** [ForestryMC/ForestryMC#1227]
Apiarist Villager asks for Oak Wood with a broken damage modifier (32767), which is impossible to get, therefore breaking the trade sequence. Using latest version as of May 23rd.

**Comment by mezz** [comment]
Thanks for the report!
Is this for Minecraft 1.7.10 or 1.8.9?

**Comment by PsychotycGoat** [comment]
1.7.10, my bad.

**Comment by mezz** [comment]
Ah ok. Sorry, but I wasn't able to get to this in 1.7.10. The trade system in 1.8.9 is much better and I've fixed it there.
This is a duplicate of the issue here: https://github.com/ForestryMC/ForestryMC/issues/846
Thanks again for reporting!

**Comment by PsychotycGoat** [comment]
for some reason I didn't find #846 ... all good then!
