### ISSUE TITLE
Incorrect upside down stair model

### ISSUE THREAD

**Issue by LuigiHutch** [ForestryMC/ForestryMC#1228]
Forestry 5.0.0.69
Forge 12.16.1.1907

Forestry stairs render incorrectly when placed upside down.

Forestry Cherry Stairs:
![2016-05-24_10 42 22](https://cloud.githubusercontent.com/assets/9326429/15499548/b1b28322-219c-11e6-80bf-8e7f89dcb47c.png)

Vanilla Stairs:
![2016-05-24_10 45 19](https://cloud.githubusercontent.com/assets/9326429/15499558/bf19c822-219c-11e6-8507-1ecc89c2bd63.png)

**Comment by mezz** [comment]
Thanks for the report! Looks like I messed up the models or they changed them somehow. Should be an easy fix.
