### ISSUE TITLE
All fireproof blocks work as fuel

### ISSUE THREAD

**Issue by auboli77** [ForestryMC/ForestryMC#1237]
Using:
Forge 12.16.1.1907
Forestry 1.9-5.0.0.76

**Comment by auboli77** [comment]
@Nedelosk, I think this made all wood blocks not work as fuel.

**Comment by Nedelosk** [comment]
I don't have an idea how we can fix this.

**Comment by CovertJaguar** [comment]
It's hacky, but you could detect when Block.getMaterial() is being called by the furnace and return something different for that call. Doing this requires inspecting the stacktrace though.

**Comment by mezz** [comment]
For a clean solution I need to change `IFuelHandler` in Forge but it will have to wait for 1.12 probably.
More discussion here: https://github.com/MinecraftForge/MinecraftForge/pull/3627

**Comment by mezz** [comment]
Fixed in 1.12
