### ISSUE TITLE
[Server thread/ERROR] IStateMapper, BlockRegistryArboriculture

### ISSUE THREAD

**Issue by aubreybailey** [ForestryMC/ForestryMC#1239]
please and thank you. you're the best. We're all waiting with bated breath :grinning: 
Crash on load for cli server mode but not graphical
Running Forge 1907, windows 10, minecraft redist java 8, and only Forestry.

https://gist.github.com/mezz/860a22511b997f37fc6536ce43c06cd1

**Comment by aking4125** [comment]
Most likely isn't Server ready but wanna drop this anyways just incase. 
[crash-2016-05-24_20.01.38-server.txt](https://github.com/ForestryMC/ForestryMC/files/280742/crash-2016-05-24_20.01.38-server.txt)

Client seems to work fine.

**Comment by mezz** [comment]
Thanks for the report!
Looks like the server is trying to access a client-only thing.

**Comment by aking4125** [comment]
The fix works for the mod on it's own. But I'm getting a crash once I add all my mods back into the server. So this must have something to do with another mod, though I currently don't know which one. I'll manually re-add each mod one each and see what happens. Here's the crash report: 

[crash-2016-05-25_19.58.00-server.txt](https://github.com/ForestryMC/ForestryMC/files/283194/crash-2016-05-25_19.58.00-server.txt)

**Comment by mezz** [comment]
This is a different error, can you please paste it in a new issue?

**Comment by aking4125** [comment]
Roger. Will do.
