### ISSUE TITLE
Analysed charcoal uses

### ISSUE THREAD

**Issue by auboli77** [ForestryMC/ForestryMC#1241]
Can't lookup uses for analysed charcoal in JEI. If charcoal is not analysed it shows its burn time.

Using:
Forge 12.16.1.1907
Forestry 1.9-5.0.0.87
JEI 1.9.4-3.4.0.204

**Comment by mezz** [comment]
@Nedelosk why does charcoal have genetics instead of making normal charcoal? This seems strange to me.

**Comment by Nedelosk** [comment]
Because the forestry charcoal have another burntime than the minecraft charcoal. And the burn time of the forestry charcoal come from the allele combustibility in the genetic data of the charcoal.

**Comment by mezz** [comment]
Can you try to make only 1 charcoal where the burn time is from ItemStack.metaData?
