### ISSUE TITLE
If you break the top half of a Greenhouse Door with an empty hand in will drop the door

### ISSUE THREAD

**Issue by auboli77** [ForestryMC/ForestryMC#1242]
Using:
Forge 12.16.1.1907
Forestry 1.9-5.0.0.87

**Comment by Nedelosk** [comment]
Yes, that is an vanilla bug the iron door do that too.

**Comment by mezz** [comment]
Confirmed, this is the bug: https://bugs.mojang.com/browse/MC-4378
