### ISSUE TITLE
Giant Sequoia is using fireproof logs as its trunk

### ISSUE THREAD

**Issue by auboli77** [ForestryMC/ForestryMC#1243]
Using:
Forge 12.16.1.1907
Forestry 1.9-5.0.0.87

**Comment by mezz** [comment]
That is expected. Sequoias are naturally very fire-resistant, and so these trees (Coast Sequoia and Giant Sequoia) are the source of the fireproof tree gene.

**Comment by auboli77** [comment]
This makes normal Sequoia wood and items unobtainable. I would suggest a new carpenter recipe Sequoia wood(fireproof) with ethanol makes normal wood.

**Comment by mezz** [comment]
You can breed the fireproof gene out of the Sequoias. Generally though, fireproof is desirable.

**Comment by auboli77** [comment]
Did not think of that... Almost found a use for ethanol in Forestry, almost.
