### ISSUE TITLE
Opening Greenhouse GUI causes a drop in fps, from 90fps to 6fps(in my case)

### ISSUE THREAD

**Issue by auboli77** [ForestryMC/ForestryMC#1244]
Using:
Forge 12.16.1.1907
Forestry 1.9-5.0.0.87

**Comment by mezz** [comment]
Thanks for the report!
Can you try on the latest version? I saw no fps drop compared to opening my player inventory.

**Comment by auboli77** [comment]
Tried on Forestry_1.9.4-5.0.4.121, this is what I get..
http://imgur.com/a/VswPP

**Comment by Nedelosk** [comment]
I think it is my update code.
