### ISSUE TITLE
Greenhouse humidity regulation

### ISSUE THREAD

**Issue by auboli77** [ForestryMC/ForestryMC#1245]
Can't regulate humidity inside of a greenhouse, it goes up and down if you use heaters or fans. 
With this I could not make it warm and damp, if you heat it up enough to make it damp it will also be hot and not warm.
Dryer is not changing the humidity in any way.
I assumed the sprinkler is for making greenhouse more humid, but that also does not work, I am supplying water and it is being used.

Using:
Forge 12.16.1.1907
Forestry 1.9-5.0.0.87

**Comment by Nedelosk** [comment]
I think it is fixed with the last version. @auboli77 Can you test it ?

**Comment by auboli77** [comment]
Forestry 1.9-5.0.0.88 in the last version of 1.9 branch on Jenkins. Its building from 1.9.4 branch it seems, as I don't see your commits.

**Comment by mezz** [comment]
1.9.4 branch is broken so I am switching it back to 1.9 for now. Should have a new build up with Nedelosk's fixes in a few minutes.

**Comment by auboli77** [comment]
Tested in Forestry 1.9-5.0.0.91 and it is working as expected.
