### ISSUE TITLE
Giant Sequoia sapling

### ISSUE THREAD

**Issue by auboli77** [ForestryMC/ForestryMC#1247]
If I am reading the code right there is less then 2,9%(2.9%) chance to get a villager with Giant Sequoia sapling.
There are 35 different saplings in Forestry.
That means 1 of every 35 Arborist villagers will be selling it. 

This may be intended, just wanted to make sure.

**Comment by mezz** [comment]
It is meant to be quite rare, it's more of a bonus than a normal tree.
