### ISSUE TITLE
Forestry Capsules, Canisters, etc, completely uncompatible with Buildcraft

### ISSUE THREAD

**Issue by Rednecklawrence** [ForestryMC/ForestryMC#1249]
Buildcraft Version: 7.1.16
Buildcraft Compat Version: 7.1.5
Forestry Version: 4.2.12.60
 So I've been having this issue where I cannot fill Forestry canisters or wax capsules with any buildcraft liquids. I have tries mucking about with config and what not, but I have not been able to fix it. there is no crashing happening, just the simple lack of being able to store BC liquids in forestry Caps/Cans. Just tell be if you people need logs, or entire mod lists, or what ever, cause I don't know what you'll need to fix this. Thanks!

**Comment by mezz** [comment]
Is this for fluids in the world or from a BC tank?
Do they pick up water normally?
Have you tried filling them the bottler?
Thanks!

**Comment by Rednecklawrence** [comment]
This is for everything. I have craftguide, and wax/cans show up that have water, lava, seed oil, etc in them, but there are not even any recipes for oil or fuel, etc from buildcraft. Yes, they pick up water normally, in world and in tanks, and in the bottler. The bottler successfully fills them with water and lava, but not BC stuff. Heres the wax recipes i have. Its the same for the cans, except they have a shitload of different fruit juices available, but no BC fluids.
![capture](https://cloud.githubusercontent.com/assets/19580717/15561042/2993eaf8-22af-11e6-8c02-5dca813e45f3.PNG)

**Comment by Rednecklawrence** [comment]
Also, I tried with ethanol in wax caps and in buckets, and neither will fill a BC combustion engine.... they'll sit in the inventory, but not go to its internal tank.

**Comment by mezz** [comment]
Hmm okay. I'm working on moving to 1.9.4 so this issue may have to wait a while for BC to update.

**Comment by Rednecklawrence** [comment]
actually, found the culprit. I'm using binnies mods 2.0-pre14 and a patcher (Binnie patcher 1.8) and I removed the both of them, and it worked. But I cant really discontinue using extra bees... any suggestions?

**Comment by mezz** [comment]
Oh sorry for some reason I assumed this was a 1.9 bug, I've been getting like 20 of those a day recently.

You should report this bug to Binnie Patcher: https://github.com/Chocohead/Binnie-Patcher/issues
They should be able to sort it out.
