### ISSUE TITLE
lepidopterology.genetics.ButterflyRoot Server Crash

### ISSUE THREAD

**Issue by whatthedrunk** [ForestryMC/ForestryMC#1259]
Not sure how to explin this one but my server seems to crash when butterflies do there thing. These 2 crashes seem to happen. 
http://pastebin.com/AncRGdQB
http://pastebin.com/VhBRxDvv

**Comment by mezz** [comment]
Thanks for the report!
Looks like Forestry is stuck in an infinite loop of checking a block, and that causes a crash with no good description somehow. I'll fix it on our side and talk to Forge about the error report.
