### ISSUE TITLE
Possible conflict with Biomes O Plenty

### ISSUE THREAD

**Issue by drewbit** [ForestryMC/ForestryMC#1260]

**Comment by drewbit** [comment]
Derp, hit enter before writing things.

Happens randomly in the world, feels like it only happens when world loads an area. Forestry is named in the Stacktrace so.

http://pastebin.com/qUWprKW5

Forestry Version: forestry_1.9.4-5.0.0.100

**Comment by mezz** [comment]
Thanks for the report!
From the stack trace, some desert Forestry bees are seeing if they can plant cactus on BoP grass. The grass is crashing when it checks if it can sustain the cactus and allow it to be planted.
Please report this to Biomes O Plenty here: https://github.com/Glitchfiend/BiomesOPlenty/issues
Link back to this issue so they can follow up if needed.

**Comment by mezz** [comment]
Turned out to be a Forge issue MinecraftForge/MinecraftForge#2941
