### ISSUE TITLE
[1.9.4] java.lang.NullPointerException: Initializing game

### ISSUE THREAD

**Issue by Xiaminou** [ForestryMC/ForestryMC#1262]
Crash Report: http://pastebin.com/XTpWz3p0

**Comment by mezz** [comment]
Thanks for the report!
Someone is putting a null name into the Ore Dictionary somehow.
I have defended against it so Forestry will not crash.

**Comment by Xiaminou** [comment]
Yeah turns out it was Extra Utilities which is why I closed the issue.

**Comment by mezz** [comment]
Next time please reply with the solution, so that others who find the issue can learn the solution to their problem.
