### ISSUE TITLE
[1.9.4] Fireproof Birch and Spruce textures (or names) are switched

### ISSUE THREAD

**Issue by primetoxinz** [ForestryMC/ForestryMC#1264]
as per title

![2016-06-01_17 05 29](https://cloud.githubusercontent.com/assets/4721642/15725759/5c7178b6-281b-11e6-81b6-7425e50eefde.png)
![2016-06-01_17 05 30](https://cloud.githubusercontent.com/assets/4721642/15725760/5ed41da2-281b-11e6-8893-2f14b6216ad1.png)

**Comment by mezz** [comment]
Thanks for the report!
Fixed in the latest alpha
