### ISSUE TITLE
Crash on loading items in world after breaking chest

### ISSUE THREAD

**Issue by drewbit** [ForestryMC/ForestryMC#1266]
Player broke a chest, had some forestry items in it. Now whenever people go near the items they crash with the following log:

http://paste.ee/p/RzSAN

Forestry Version: forestry_1.9.4-5.0.1.112

**Comment by drewbit** [comment]
Looks like it's only happening to saplings gotten in previous versions.

**Comment by mezz** [comment]
Sorry, the genetics of many things in the alpha was broken today.
You can clear them by changing a config setting in `forestry/common.cfg`  
`clear.invalid.chromosomes=true`
