### ISSUE TITLE
[1.9.4] NoSuchMethodError on Server Startup

### ISSUE THREAD

**Issue by GodNero** [ForestryMC/ForestryMC#1268]
- Minecraft - 1.9.4
- Forge - 1936 & 1939
- Forestry - 5.0.2.114
- No other mods present
# 

I am getting server crashes with forestry 5.0.2.114, happens before world file generation on 2 version of Forge. I have Crash logs for each and both are below, there are no other mods present while attempting to create server. If there is anything else I can do to help let me know.
# 

Crash Log (Forge 1936) - http://pastebin.com/ufFHmEJh
Crash Log (Forge 1939) - http://pastebin.com/hdTGp5Jc

**Comment by mezz** [comment]
Thanks for the report!

**Comment by GodNero** [comment]
Confirmed new version is working fine, now I am testing it against mods. I will open a new issue should I find any logged and repeatable errors. Thanks for the fast response on this mezz ;)
