### ISSUE TITLE
[1.9.4] Random crashes from world gen with BoP

### ISSUE THREAD

**Issue by jawsawn** [ForestryMC/ForestryMC#1270]
https://gist.github.com/JAWSAWN/6c571036fd94e8578fc9dbfa44473508

It sometimes crashes to desktop while generating a new world.
Also could randomly happen while generating new chunks.

latest forge, latest forestry and latest BoP

**Comment by GirafiStudios** [comment]
Duplicate of https://github.com/ForestryMC/ForestryMC/issues/1260 . It's actually a problem with Biomes O' Plenty and is already reported to the author :)

**Comment by mezz** [comment]
Thanks for the report!
We are aware of this problem, please see https://github.com/Glitchfiend/BiomesOPlenty/issues/763
Duplicate of https://github.com/ForestryMC/ForestryMC/issues/1260

**Comment by mezz** [comment]
This turned out to be a Forge issue MinecraftForge/MinecraftForge#2941
