### ISSUE TITLE
Add more bees and trees

### ISSUE THREAD

**Issue by 0Navis0** [ForestryMC/ForestryMC#1271]
Ender hives exist, so why not nether hives ? ;)

**Comment by Yulife** [comment]
They exist in ExtraBees I think. Not sure if that is getting ported though  😅

**Comment by quienti** [comment]
We don't have any news of Binnie very long time :(
If @mezz is okay, I can probably create a pull request to add new bees in Forestry
And why not trees and butterfly if I will can and time ^^

**Comment by CovertJaguar** [comment]
Pity we don't even know if @binnie567 would be willing to let someone else take over. His license is unfortunately very vague (pretty much just All Right Reserved I believe).

**Comment by quienti** [comment]
Yes, because the mod adds many interesting addons ...

Perhaps a small group of members may write a new mod as his model ? ( If it is possible , of course, I do not know how "license" work exactly ... )

Or maybe someone has the opportunity to communicate with him?

**Comment by CovertJaguar** [comment]
Well there is nothing preventing anyone from starting from scratch on a new Bee/Tree mod.

**Comment by mezz** [comment]
In one month it will have been 1 year since BInnie's Mods last release. 
At that point I should start MoreBees or ResourceBees as an addon (not in regular Forestry) and start a project to add more trees directly to Forestry.

**Comment by quienti** [comment]
I like your idea @mezz ! :D 

From this weekend, I will begin to re learn to develop Forge and why not help you for this addons.

**Comment by mezz** [comment]
@SirSengir are you able to contact Binnie at all? We could really use clarification on his mod license. Can we re-use his texture assets? His code? Could someone be allowed to keep the mod alive?

**Comment by SandGrainOne** [comment]
Maybe turning Sinister into a mundane bee in the Nether?

**Comment by Jadziyah** [comment]
@mezz Yes yes yes! That's a project myself and many others have been waiting for a while! As you have recently noticed on reddit I'm a huge fan of Forestry and ExtraTrees :D  Having that lovely variety of trees and machines added into Forestry, a stable, professionally worked on mod that isn't in danger of dying, would be a dream come true. And a reborn MoreBees mod would delight an even wider audience. I hope you can figure out the licensing issues!

**Comment by SirSengir** [comment]
@mezz Unfortunately I have no way to contact @binnie567 apart from what everyone else has access to (i.e. Twitter, Github). I fear he may finally have dropped from the face of the earth for good...

**Comment by IsaakTheDragon** [comment]
@mezz I hope you do this, that will be insanely awesome!

**Comment by Shadows-of-Fire** [comment]
Unless bitbucket is automated in how it assigns things, which I doubt it is, @binnie567 seems to be around on there.  So it might be feasible to try and contact him through that.  It doesn't seem like it's automated, since only some issue have assignees.  And if nobody else is messing with that repo, the last issue that was assigned was a week ago.  The only thing is, there's no actual activity tracker.

**Comment by mezz** [comment]
His bitbucket permissions allow the person submitting the bug to assign and prioritize, which is why it looks like everything is _super urgent_.

**Comment by Shadows-of-Fire** [comment]
Well. That's quite odd.  I wonder if there are any other possible mediums of communication that he actually checks.

**Comment by Shadows-of-Fire** [comment]
Last activity I can actually see is he acknowledged the existence of forestry 4.  There also seems to be another user named p-schneider that has write access on the repo.  That user seems even harder to contact.

**Comment by 0Navis0** [comment]
Wow it seems that my little suggestion inspired a lot of people to add new awesome content to Forestry. ^^

**Comment by quienti** [comment]
I have find this during my research
https://github.com/vSkyD1/Binnies-Mods

It is not an "official" but maybe this github can help ?

**Comment by 0Navis0** [comment]
If you plan to add Binnie's mods to Forestry itself, why not add Magic Bees and Gendustry in same time ?

**Comment by mezz** [comment]
@quienti consider that repo off-limits, it should not exist. We are not able to copy code from Binnie's without permission.

@Hypsellis only the trees are planned for being added to Forestry. The other stuff (resource bees) changes the balance of the mod and the game dramatically.

**Comment by 0Navis0** [comment]
Aw why ?

**Comment by mezz** [comment]
> The other stuff (resource bees) changes the balance of the mod and the game dramatically.

**Comment by 0Navis0** [comment]
Yeah I understood, but I don't see how. Is there now way to rebalance the mod and the game ?

**Comment by mezz** [comment]
No. Forestry by itself doesn't allow for the creation of all kinds of resources. The play-style is completely different when magic bees and extra bees are added. The goals are completely different.

**Comment by Nirek-K** [comment]
Basically adding that into the mod fully, would change the perception of balance in forestry entirely. Mezz did say he was considering a seperate bee addon mod at some point. But not baked in.

**Comment by 0Navis0** [comment]
Hm ok. Anyway I'm impatient to see what you guys plan. You do awesome work. <3

**Comment by quienti** [comment]
@mezz I understand, It's logical and normal !

So, your plan is to add more tree in Forestry and and bees in `Ressource Bees`
But, without bees, have you another plan for this mod ?

**Comment by CovertJaguar** [comment]
_it lives..._

**Comment by mezz** [comment]
Good news: @CovertJaguar helped me get in touch with Binnie!

![binnie-permission](https://cloud.githubusercontent.com/assets/916092/16285763/ece14cce-388c-11e6-90ac-3f9dbf248078.png)

> Hey mezz
> 
> You have every permission to do with my code as you like. I've made it public, but I'd rather someone who understands Forestry well look after/take what they want from it.

**Comment by CovertJaguar** [comment]
**ALIVE! IT'S ALIVE!**

**Comment by LuxusDarkangel** [comment]
Oh boy, OH BOY, I can't wait to see some bee-related repository in mezz's profile.

**Comment by Jadziyah** [comment]
Oh @mezz that's so awesome!!! Bees and trees be free! :D

**Comment by quienti** [comment]
Awesome !! :D

**Comment by xeronut** [comment]
Hmm.. what are the chances the Wood/Glass/Tile/Panelworker machines end up as at least an addon?

**Comment by Jadziyah** [comment]
Yes hopefully those machines will be included with the new Forestry additions, as they do work with those items after all.

Another question would be what about the stuff in Binnie Core mod? The production of various beers, wines, and liquors is fun and could be even more so if all the gaping holes are fixed. And the fancy glasses!

**Comment by mezz** [comment]
Those machines are unlikely to get ported, but I am making sure the woods are compatible with Chisels and Bits so you can do all that stuff and more.

Other parts of Binnie's mods are very low priority. I still have a lot to work on with Forestry and it wouldn't be a good idea to take on more right now. There are bugs in the original code, and porting anything from 1.7.10 to 1.8+ is also very difficult and time consuming. Updating Binnie's Mods entirely could be as much work as updating Forestry itself.

**Comment by RossRKK** [comment]
@mezz I was speaking to Binnie the other day about working on future versions of Binnie's mods and he suggested that I ask to see if it would be possible for me work with you since you've already done some work on updating the mods.

**Comment by mezz** [comment]
@RossRKK I welcome your help!
We have a project here, porting the whole mod: https://github.com/ForestryMC/Binnie
Please try it out, it's still in a pretty broken state. 

I will accept PRs for fixes, just try to keep them small. 
It's easier to look over lots of small PRs than one big one.
