### ISSUE TITLE
Forestry villager house generating incorrectly

### ISSUE THREAD

**Issue by LuigiHutch** [ForestryMC/ForestryMC#1272]
Forestry 5.0.4.121
Forge 12.17.0.1937

Normal Superflat world
Seed: 5074102534929648016
Coordinates: X -1369, Z 777
![2016-06-03_18 04 17](https://cloud.githubusercontent.com/assets/9326429/15786719/0bf36ac4-29b6-11e6-87ba-3116094c09ea.png)

**Comment by mezz** [comment]
Hah! That part extends out a bit, so vanilla minecraft thinks it's the ground and replaced it with road. I will have to extend the village house bounding box a little.
