### ISSUE TITLE
Villagers unable to open forestry doors

### ISSUE THREAD

**Issue by LuigiHutch** [ForestryMC/ForestryMC#1273]
Forestry 5.0.4.121
Forge 12.17.0.1937

Villagers are unable to open forestry doors

**Comment by mezz** [comment]
Poor villagers! I had no idea.

**Comment by mezz** [comment]
Looks like it was broken accidentally by the change here: https://github.com/ForestryMC/ForestryMC/issues/1237

Villagers will only recognize doors that are Material.WOOD, no other material.

**Comment by CovertJaguar** [comment]
Material code in Minecraft is horrible, so much stuff hardcoded to specific materials.
