### ISSUE TITLE
forestry.core.genetics.Genome.getChromosomes

### ISSUE THREAD

**Issue by whatthedrunk** [ForestryMC/ForestryMC#1276]
I get this local crash when joining a server. Local works just fine.
http://pastebin.com/Z787q5FM

**Comment by mezz** [comment]
Thanks for the report!
One of the first Forestry 5 release broke all the genes.
In your `config/forestry/common.cfg` set `genetics.clear.invalid.chromosomes` to true.

**Comment by whatthedrunk** [comment]
That was super quick thanks!

**Comment by whatthedrunk** [comment]
Leaving this here because its probably related
http://pastebin.com/WmkN2dVP

Would you recommend me just removing forestry from the server and adding it again?
