### ISSUE TITLE
1.7.10 forestry terminates singleplayer world upon creation. conflict with nei integration.

### ISSUE THREAD

**Issue by michaelproeber** [ForestryMC/ForestryMC#1284]
latest version of both.

http://pastebin.com/6E0ZPsaJ

here's the crash log in between the server (singleplayer world) starting and the server stopping.

posted issue on /nei-integration too. https://github.com/Tonius/NEI-Integration/issues/105

**Comment by Nirek-K** [comment]
The 'latest' version of integration does not have forestry integration, as forestry took over that itself.

**Comment by michaelproeber** [comment]
I see. is there any way to keep nei integration without having to have the world close every time I make one?

**Comment by Nirek-K** [comment]
You don't have the latest integration, or you would not have that issue.

**Comment by michaelproeber** [comment]
oh...I thought I did. I updated almost all 200 mods in the modpack but I guess I missed that one. thanks.
