### ISSUE TITLE
[1.9.4] java.lang.IllegalArgumentException: Cannot get property PropertyEnum

### ISSUE THREAD

**Issue by JCMais** [ForestryMC/ForestryMC#1292]
Forge: 12.17.0.1951
Forestry: 5.0.4.121
OptiFine: 1.9.4_HD_U_B5

This is an issue that only occurs with OptiFine **and** when using shaders.
Happened when breaking a wood pile.

Crash log: https://gist.github.com/JCMais/6b479629a5205406519ea85460ca6451

I know optifine is generally not supported by mods, but it doesn't hurt to post it here.

**Comment by mezz** [comment]
Thanks for the report!
This is the same issue as https://github.com/ForestryMC/ForestryMC/issues/1300
I am working around it by not rendering the pile when there is an issue. It may not render, but it shouldn't crash.
I'm leaving this issue open. WAILA being broken is not surprising, but the pile should render correctly in the world.

**Comment by mezz** [comment]
This seem to be working OK so I am closing this issue.
