### ISSUE TITLE
MultiFarm Crashing Server

### ISSUE THREAD

**Issue by Vealor** [ForestryMC/ForestryMC#1293]
FTB Infinity Evolved 2.5.0
Forestry: 4.2.11.59
AgriCraft: 1.5.0

Server has crashed multiple times within the hour, all seem to happen when the farm is turned on/given power.  Two prior farms were running, one with trees and another in manual with only 4 different crops from Agricraft.  A third farm was made and has 1 of each type of crop from agricraft on it (nearly) and a large covered section for mushrooms and netherwart, only after these were placed did the crashes start.  Only 4x4x4 farms were used.  Can provide further details/screenshots.

Full Crash report here (most recent, other prior crash logs available):
http://pastebin.com/akN1QzM3

Would love to continue using the multiblock farm!

**Comment by mezz** [comment]
Thanks for the report!
Looks like your version is outdated, the latest Forestry for Minecraft 1.7.10 is version 4.2.12.60.
http://minecraft.curseforge.com/projects/forestry/files/2296588
Can you try it out and paste the crash here if it's still broken? It would really help me pin down the issue.

**Comment by Nirek-K** [comment]
At a guess it's a particular crop from agricraft throwing a null somewhere it shouldnt. Full orchard/cropstick farm?

**Comment by Nirek-K** [comment]
Actually, it might be either netherwart or shrooms, because of the way I get drops, I'm looking into it.

**Comment by Vealor** [comment]
@mezz I would love to update it, but I need to adhere to the FTB Launcher preset downloads for the pack, if they had a 2.5.1 or such that had that version of forestry, I would be happy to update.  I need to provide the simplicity for the server users unfortunately.

@Nirek-K I will remove all of the agricraft crops and add them in individually over a period of time to see if I can determine if one of them is causing the crash! Thank you for your suggestion :).  Will update when I find something.

**Comment by Nirek-K** [comment]
Edit: its actually not either of those, hmm.
Yeah, finding the one you use that's crashing would be great, almost impossible for me to find on this end with the way agricraft creates new crops based on the other mods, way too many permutations. From there I can find out why and get it fixed. I will add a failsafe to the inventory collector to prevent it from crashing in that way, would really like to see what weirdness this crop is doing though.

**Comment by Vealor** [comment]
Found the culprit!

Sesame Seeds Seed
![crashseed](https://cloud.githubusercontent.com/assets/6099022/15808501/c47164d4-2b2d-11e6-833d-82a12dbc036c.png)

Once placed into an Agricraft crop, when attempting to be harvested it's an immediate server crash.

**Comment by Nirek-K** [comment]
hmm k, will look into why it's weird. Thanks.  (and apparently hc updated and added more crap I need to add anyway, neat.)

**Comment by Nirek-K** [comment]
I have a pretty good idea why that happens, I'll fix it today. (any other crop that literally has no 'produce' and only gives seeds would cause that, in the context of orchard/cropsticks) In case there are any others like that.

**Comment by Vealor** [comment]
Thanks for your help Nirek-K :)

I'm assuming that this can't be fixed in the modpack we are currently using and would be best to avoid until a more recent version of forestry is used....

**Comment by Nirek-K** [comment]
unless they update, probably not, but it literally only affects the crop types I stated, which may only be that specific one.

**Comment by Vealor** [comment]
Thanks very much!

**Comment by Nirek-K** [comment]
hmm, I spoke too soon, sesame seeds do actually have sesame seed seeds..bizzarely. This actually looks like something that needs special casing on agricraft side, in my testing they don't produce seseame seed 'produce' from cropsticks even harvested manually, only 'seeds', which makes them broken on crop sticks entirely, which is why it fails when harvested by the farm.

**Comment by Nirek-K** [comment]
I fixed the crash portion of things on our side with that commit there. It will harvest and produce nothing, its an issue with the cropstick side of things providing a null stack rather than the 'produce' stack and nothing I can change here. I did plop an issue about it on their tracker, no idea if they would fix it for 1.7 though. This commit also updated hc compat in general, so you could plant sesameseeds not in cropsticks and it would work.

**Comment by mezz** [comment]
Fixed in version 4.2.13
