### ISSUE TITLE
Incompatibility with SpongeForge

### ISSUE THREAD

**Issue by LuxusDarkangel** [ForestryMC/ForestryMC#1296]
SpongeForge for 1.9.4 has just been released, so i'm not sure if it's a problem on their end or yours, but i'm sure you can easily clarify it.

Crash-Report: http://pastebin.com/9rqFG6H4
Forestry version: 5.0.9.142
SpongeForge version: 5.0.0-BETA-1406

**Comment by mezz** [comment]
Thanks for the report!
The best thing you can do is test if it works without SpongeForge. In this case, it works fine without. 
Their goal is compatibility, it's not something I can fix on my end. Please help them out by reporting any SpongeForge issues to them directly here: https://github.com/SpongePowered/SpongeForge/issues
