### ISSUE TITLE
Recipe for Fuel Can missing

### ISSUE THREAD

**Issue by jdno** [ForestryMC/ForestryMC#1297]
Hey,

I have a weird problem, and hope I can get some help here.

I run a server with FTB Infinity Evolved 2.5.0, and the recipe for Fuel Cans seems to be missing. It can't be found in NEI, and neither the Bottler nor the Liquid Transposer are able to fill fuel (from a refinery) into cans.

Searching the internet did not yield any helpful results. Would really appreciate some help locating the issue.

Best regards,
jdno

**Comment by mezz** [comment]
Thanks for the report!
Forestry only recognizes Buildcraft fuel. Maybe another mod swapped it out for their own type of fuel?
This is no longer an issue in Forestry 5.

**Comment by jdno** [comment]
Oh that might me the reason. If it's fixed in Forestry 5, don't mind and feel free to close the issue. Love Forestry, by the way. ❤️

**Comment by mezz** [comment]
Alright, thanks!
