### ISSUE TITLE
Cans/Capsules filled with mod added fluids in have a water texture rather than the fluids texture

### ISSUE THREAD

**Issue by LuigiHutch** [ForestryMC/ForestryMC#1299]
Forge 12.17.0.1950
Forestry 5.0.9.142]

Cans/Capsules filled with mod added fluids in have a water texture rather than the fluids texture:
![2016-06-06_22 22 18](https://cloud.githubusercontent.com/assets/9326429/15838448/f6068700-2c35-11e6-8267-51b03b5bf6a4.png)

As you can see only the forestry fluid filled capsules have a texture inside. I tested with fluids added by industrialcraft-2-2.5.7-ex19.jar and Tinkers Construct 1.9.4-2.3.1.jenkins229

Thanks
- LuigiHutch

**Comment by mezz** [comment]
Thanks for the report!
Forestry has its own list of known fluid colors. Unknown fluids are colored as water. It would be much better to do it like the universal bucket and use the actual fluid texture instead.
