### ISSUE TITLE
1.9.4-5.0.9.143 crashes dedicated Forge 1.9.4 build 1954 on startup (Farseek)

### ISSUE THREAD

**Issue by kreezxil** [ForestryMC/ForestryMC#1302]
Issue:  forestry-1.9.4-5.0.9.143 crashes dedicated Forge 1.9.4 build 1954 on startup

Crash Report:
https://gist.github.com/fc158e6d8484ccd40d3585e3baedc638

fml server latest:
https://gist.github.com/bf6c0cb71c13d68abe6804f372cb158f

**Comment by GirafiStudios** [comment]
Duplicate of https://github.com/ForestryMC/ForestryMC/issues/1248

**Comment by mezz** [comment]
Thanks for the report!
Please see the underlying Farseek issue here: https://github.com/delvr/Farseek/issues/10
