### ISSUE TITLE
Add localization for villager names

### ISSUE THREAD

**Issue by way2muchnoise** [ForestryMC/ForestryMC#1306]
`entity.Villager.<name of career>` are the keys. Needed for showing off the trades in [JER](https://github.com/way2muchnoise/JustEnoughResources)
Little preview:
![](http://puu.sh/plIrL/31e52090b9.gif)

**Comment by Darkhax** [comment]
This issue also affects the career display in [WAWLA](https://github.com/Darkhax-Minecraft/WAWLA)
