### ISSUE TITLE
[Suggestion] Add Binnie's mods to Forestry itself.

### ISSUE THREAD

**Issue by LuxusDarkangel** [ForestryMC/ForestryMC#1310]
In my opinion, bees and trees lacks a lot of features and playability, which i used to fulfill with Binnie's Mods. Now binnie disappeared and probably there won't be any releases in the near future, if at all. Maybe it's time to finally add all those features to Forestry?

**Comment by mezz** [comment]
That's pretty much what this issue has become about: https://github.com/ForestryMC/ForestryMC/issues/1271

**Comment by LuxusDarkangel** [comment]
Whoops, i saw it while searching for related issues, but thought it was only about the Nether Hives. Sorry, and i can't wait to see your new bee addon!
