### ISSUE TITLE
Crashing when looking at any butterfly

### ISSUE THREAD

**Issue by ConnorRowe** [ForestryMC/ForestryMC#1311]
FTB Unstable 1.9 **4.0.6**
Forestry **1.9.4-5.0.10.147**
Forge **12.17.0.1957**

Every time I look at any butterfly entity it completely crashes the client. I have to be fairly close to it for it to crash. It happens no matter the species.

Here is the crash report:
http://pastebin.com/C1wcTwnN

**Comment by ConnorRowe** [comment]
Also, when I use the command `/forestry bfly kill` it returns this error:

http://pastebin.com/LQsszQZD

**Comment by mezz** [comment]
Thanks for the report!
Fixed in 5.0.11
