### ISSUE TITLE
[1.9.4] Almost duplicate textures for butterfly/moth entity/items

### ISSUE THREAD

**Issue by HanPrower** [ForestryMC/ForestryMC#1312]
I understand the item textures are due to the modelling system, but I also know that the basic Minecraft modelling system isn't strictly stuck within the relevant textures folder. (In PureBDcraft we use the chest entity texture map for the Chest Minecart item model...).

So, to save resources, is it not possible to replace the actual entity textures with the square item textures  and then refer the item models to those instead?

**Comment by mezz** [comment]
I don't understand the problem with how it is now, can you explain?

**Comment by HanPrower** [comment]
It's the case of textures being loaded into the game. At 16x it's not really an issue, but for HD packs resources run out quickly so near duped textures seem a waste.

**Comment by mezz** [comment]
Ah ok, I didn't realize they had been copied.

**Comment by Nedelosk** [comment]
The entity textures is currently not loaded as a sprite into the game. When I use the entity texture for the item rendering the texture is not 16x16 but 16x32.

**Comment by mezz** [comment]
Oh, I see they are not exactly identical. Item is 32x32 and entity is 64x32. Is is possible to have the entity use the item texture, and remove the 64x32 texture?

**Comment by HanPrower** [comment]
@mezz Not sure if you're asking me if it's possible or one of your fellow devs, but there's no reason why you it can't be done.

It's "simply" a case of replacing the 64x32 entity textures with the 32x32 item textures, changing all the item json models to point at the entity files, and to remap the entity renderer for in-world.

**Comment by Nedelosk** [comment]
Currently I working on remapping the butterfly item textures. From 32x32 to 16x16.

**Comment by Nedelosk** [comment]
From 30.3 to 27.7 percentOfTextureMap. I think that is good.

**Comment by mezz** [comment]
Nice, I will include this change in the next TextureDump update.
