### ISSUE TITLE
Fatal error on world loading 1.7.10 (single player)

### ISSUE THREAD

**Issue by saquerof** [ForestryMC/ForestryMC#1313]
[fml-client-latest.zip](https://github.com/ForestryMC/ForestryMC/files/310392/fml-client-latest.zip)

[2016-06-11-5.log.gz](https://github.com/ForestryMC/ForestryMC/files/310390/2016-06-11-5.log.gz)

I'm getting a fatal error on world loading on every version above 6.3.20 (single player) and after I'm getting put into the multiplier lobby.if i take out forestry all goes fine,so ill post the launcher, has the game is not crashing i don't get a crash report. the current version im testing on was forestry_1.7.10-4.2.5.53
but like i said it happen on all above 6.3.20

the launcher state this, 

http://pastebin.com/HvYRg4dL

**Comment by Nirek-K** [comment]
You need to update Nei Integration.

**Comment by saquerof** [comment]
thanks for telling me, i wasnt able to understand why it was happening and sorry for posting that here

**Comment by Nirek-K** [comment]
Nei Integration had Forestry support, until Forestry 4 where Forestry took over itself (and newer versions of Nei Integration disable support for Forestry 4+)
