### ISSUE TITLE
Crash when looking at strange forestry leaves

### ISSUE THREAD

**Issue by ConnorRowe** [ForestryMC/ForestryMC#1314]
Unstable 1.9 **4.0.6**
Forestry **1.9.4-5.0.12.149**
Waila **1.7.0-B3_1.9.4**

On a mundane larch tree, there are these strange plain green leaves and if I look at them, my client crashes. In the crash report there is nothing about forestry so it may just be a problem with Waila but I thought I'd put it here anyway.

[Screenshot.](http://i.imgur.com/CCWtZhH.png)
[Crash report.](http://pastebin.com/PuFNk5Gh)

**Comment by GirafiStudios** [comment]
I have been getting this crash too. I don't think there is anything Forestry can do about it though, looks like a problem with Wailas raytracing :)

**Comment by mezz** [comment]
Thanks for the report!
I'll look into this soon.
In the meantime, I recommend using TOP, it has a config setting to work without holding the probe item. It's being actively maintained and the author McJty is awesome.
http://minecraft.curseforge.com/projects/the-one-probe
