### ISSUE TITLE
Sapling drops. 

### ISSUE THREAD

**Issue by bookerthegeek** [ForestryMC/ForestryMC#1315]
So a bit of an odd request....

Would it be doable to add a configuration for a few things? 
- Make all saplings that drop convert to Forestry saplings.
- An ability to modify the sapling drop rate per tree and for each level of breeding a tribute that controls saplings drop rate. This would effect all saplings from all modded trees, or an IMC so mods could add their tree to Forestry. 
- Set world gen to only use Forestry trees. 
- configurable drop rates per tree with a grafted, and the ability to add other grafted from add-ons
- The ability for modded farms to increase the drop rate through configuration changes.

Sorry if this seems confusing,  feel free to ask for clarification on any of it.

**Comment by mezz** [comment]
This is not possible right now. 
Worldgen trees are on the agenda, see https://github.com/ForestryMC/ForestryMC/issues/872
Making the world into a Forestry conversion is not on the agenda. Forestry is made to work alongside other mods, not take over.
I'm not sure I understand the requests for drop rate configs. It doesn't seem like something many people would use. If the drop rates are bad, they should be changed.

**Comment by bookerthegeek** [comment]
The reason for the modifiable drop rates is to force players down a specific progression line by forcing them to breed trees to set up automated farms. Akin to a super hard mode.

The ability to add moded trees as Forestry trees is so that mods can add compatible by making their trees follow Forestry breeding, and able to be used in the breeding.

**Comment by mezz** [comment]
I think what you're asking for is too much work for me, honestly. It is not a reasonable request.

**Comment by bookerthegeek** [comment]
Understood. Thank you for taking the time to think about it.
