### ISSUE TITLE
1.9.4 Crash with .153 version on world load

### ISSUE THREAD

**Issue by MokahTGS** [ForestryMC/ForestryMC#1318]
Getting a crash with the latest version on saved world load:

http://pastebin.com/8KbzmvAE

**Comment by whatthedrunk** [comment]
I just loaded my world with .154 and got the same crash.

**Comment by RealGrep** [comment]
Can confirm it still happens in .154.

**Comment by mezz** [comment]
Fixed in .155 which will be up momentarily.
