### ISSUE TITLE
No_Circuit_Layout should be Invalid_Layout

### ISSUE THREAD

**Issue by Nirek-K** [ForestryMC/ForestryMC#1320]
The errorstate No_Circuit_Layout only seems to appear when building a board with tubes over their limits, giving a No Layouts Found, check game settings. Error which is rather confusing. State should be changed, at least in description to 'Invalid Layout, check tube limits' or similar.

**Comment by mezz** [comment]
I'm thinking of removing the limits.

**Comment by Nedelosk** [comment]
I close this because circuit have not limits anymore.
