### ISSUE TITLE
[1.9.4] [Idea] Add tooltip for multiblock blocks

### ISSUE THREAD

**Issue by hron84** [ForestryMC/ForestryMC#1323]
I think it would be good either to add some in-game guide to the mod (take look at the IGW mod), or adding some tooltips to building blocks. For example, I still cannot figure out which Greenhouse block does what, but it was same for MultiFarm blocks when it was introduced. I had to wait for some videos and/or FTBwiki updates to figure things out. This is not so newcomer-friendly.

**Comment by CovertJaguar** [comment]
Railcraft Multi-Blocks have primitive tool tips like this, but my structures are generally just cubes and rectangles, sometimes hollow. Forestry is more complex.

**Comment by hron84** [comment]
@CovertJaguar not neccessarily. Most Forestry multiblocks are just cubes or rectangles too, but not built from same block. If you build e.g. a greenhouse, it has a lot of tips on chat (which is a kinda good idea), but no info about which block does what. That could be improved by a "primitive tooltip" a lot.

**Comment by hron84** [comment]
Thank you very much!
