### ISSUE TITLE
Greenhouse tips

### ISSUE THREAD

**Issue by Majestyc2k1** [ForestryMC/ForestryMC#1327]
Can we get some tips on building/operating the Greenhouse in 1.9.4? I know it needs to be at least 5 blocks tall, but I was having trouble figuring out what blocks for the floor. It didn't like grass, dirt, air and bog earth. Thanks.

**Comment by mezz** [comment]
Use the greenhouse brick blocks for the floor

**Comment by mezz** [comment]
I think this confusion will be solved by #1323
