### ISSUE TITLE
[Crash] java.lang.NullPointerException: Updating screen events

### ISSUE THREAD

**Issue by AO77777** [ForestryMC/ForestryMC#1328]
Full log:

http://pastebin.com/MznEZPf0

**Comment by mezz** [comment]
Thanks for the report!
Do you have any steps to reproduce the error?

**Comment by AO77777** [comment]
Can be reproduced in a test world by clicking on any wheat (Normal mouldy decaying) in the working slot of a moistener with any wheat (Normal mouldy decaying) taken directly from the reservoir of the machine. 

![2016-06-23_20 27 34](https://cloud.githubusercontent.com/assets/20087128/16317185/ddc1591e-3981-11e6-808e-6e5fe4e428fa.png)

![2016-06-23_20 32 22](https://cloud.githubusercontent.com/assets/20087128/16317198/e5b8e8e4-3981-11e6-8fda-2d096dedc9d0.png)

**Comment by mezz** [comment]
Thanks, that's extremely specific. I would have never figured it out.

**Comment by mezz** [comment]
Fixed in the latest version, it will be backported to 1.7.10 soon
