### ISSUE TITLE
[1.7.10] Bee mutations that require a block as foundation is impossible in an Alvery.

### ISSUE THREAD

**Issue by wmrojer** [ForestryMC/ForestryMC#1330]
Tested with Forestry 4.2.13.61 and Forge Forge 10.13.4.1614-1.7.10

It seems to be impossible to get bee mutations that requires a specific block as a foundation in an Alvery. In an Apiery it works.

Checking the code I found that forestry.core.genetics.mutations.MutationConditionRequiresResource is checking for blocks that are instanceof IBeeHousing trying to get down below the Alvery. But there are no block that implements that interface. 
The same issue is also in forestry.core.genetics.mutations.MutationConditionRequiresResourceOreDict.
I did not find any class that all Alvery blocks and Apiery block extend/implement. So the logic problably needs to be rewritten.

I have run it in debug and verified that this is the place where it fails the check for mutation since it will not find the required block since it is checking inside the alvery. For the apiery the Y-1 it starts with is enough so there it will find the block.

And easy fix would be to check the blocks Y-1, Y-2 and Y-3 for the required block instead of trying to determine when we are outside the alvery/apiery.

`

```
public float getChance(World world, int x, int y, int z, IAllele allele0, IAllele allele1, IGenome genome0, IGenome genome1) {
    Block block;
    int meta;
    int i = 1;
    do {
        block = world.getBlock(x, y - i, z);
        meta = world.getBlockMetadata(x, y - i, z);
        if (ItemStackUtil.equals(block, meta, blockRequired)) {
            return 1f;
        }
        i++;
    } while (i<4);

    return 0f;
}
```

`

**Comment by mezz** [comment]
Thanks for the report!
`IBeeHousing` is implemented by the tile entities for the Alveary, Apiary, etc. Checking the block instead of the tile entity is an error.

**Comment by Nirek-K** [comment]
Should be fixed in https://github.com/ForestryMC/ForestryMC/commit/56adc25fdffc1cd66e7de503e7a76ff2507271e6
