### ISSUE TITLE
1.9.4 compatibility

### ISSUE THREAD

**Issue by LuxusDarkangel** [ForestryMC/ForestryMC#1331]
I know it's possible to keep a mod compatible with 1.9.4 and 1.10 in the same version, but not sure if that can be applied to Forestry?

Doesn't seem too hard, because a lot of lazy modders are doing it, and well... they wouldn't if it was hard.

**Comment by mezz** [comment]
Forestry has some things that can't be bridged between 1.9.4 and 1.10. Specifically the village generation. The best policy for me is to move on to 1.10, since most 1.9.4 mods work there too. Anyone who is not on 1.10 now will not take very long to get there, it took me about 15 minutes.
