### ISSUE TITLE
[1.7.10] Lag issue with WorldGuard

### ISSUE THREAD

**Issue by importnil** [ForestryMC/ForestryMC#1332]
Hello, I have this WarmRoast log:
https://drive.google.com/file/d/0B5WYQGKL2BioNGVpOVVxczVnYXM/view
(download and open it)

My server is living for more than half a year and like 2 weaks ago it started to lag until I finally managed to check WR logs and timings. Timings report that WG takes 20%+ CPU time, while it's clear that there's something wrong with Forestry as well.

My Forestry version is 4.2.12-58, is this hopefully fixed in latest 4.2.14 or has something to do with my setup, or has a chance to be fixed?

Thank you!

**Comment by mezz** [comment]
Thanks for the report!
The farm uses a player's game profile to place and break blocks. When they are offline, it looks like WorldGuard/CraftBukkit are spending some extra CPU time to check permissions on this offline player. Maybe this (very frequent checks) is a situation they just haven't run into in testing, it's not a common case.

You should report to WorldGuard or CraftBukkit and link back here. I don't think Forestry is doing anything particularly slow here, all the time is spent in CraftBukkit.

**Comment by Nedelosk** [comment]
No reaction so I close this.

**Comment by Eufranio** [comment]
Reported to WorldGuard (since no one did it): http://dev.enginehub.org/youtrack/issue/WORLDGUARD-3800
