### ISSUE TITLE
[1.94] Bees killing off animals, leaving behind their drops.

### ISSUE THREAD

**Issue by eggyplantsu** [ForestryMC/ForestryMC#1333]
The new wild bees hostility is eradicating passive animals/villagers but don't have the AI brains to avoid hives. Could the bees weaken but not kill NPCs only as a bee hive killed off all the animals before I made a animal husbandry farm and killed off half of the villagers in a village?

**Comment by mezz** [comment]
Only the wild bees attack, domesticated ones in villages do not. In either case I agree, the bees should only attack hostile mobs, they should get along fine with passive ones.
