### ISSUE TITLE
Wither Skeleton Drops don't go in Hunter's Backpack (v1.10.2)

### ISSUE THREAD

**Issue by Wolftousen** [ForestryMC/ForestryMC#1335]
The head does, but not the other drops (bones, drops of evil, ribs)

Minecraft version 1.10.2
Mod File Version: 1.10-5.1.7.188

**Comment by Wolftousen** [comment]
Also, blaze hearts (Molten Core) don't either

**Comment by SandGrainOne** [comment]
You can actually change that yourself by adding the items to the configuration file. 

The Forestry team would never be able to keep up with what other mods might add as drops, so they made it configurable.

**Comment by mezz** [comment]
These are not default drops, mods add them. Either you can add them in the config file, or the mods can add their items to the backpack via the API.
