### ISSUE TITLE
[1.7.10] Tried to read NBT tag that was too big

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#1337]
![](http://i.nentify.me/mzLkVkFn.png)

When entering an area of the world, there is a period of lag and no messages are sent/received from the client, then they're kicked with the message above.

Client log: http://pastebin.com/7nF4F7Ek

(Note: Most times the bad packet was 53, not sure why it's "-235340674" in the log this time. However, it was only 53 when I was testing with Thermos and -235340674 with plain Forge)

I removed a few mods at a time and the issue seemed go away and re-appear after testing with and without Forestry.

Forge version: 10.13.4.1614
Forestry version: 4.2.13.61

**Comment by Nirek-K** [comment]
that is usually caused by having an item with an nbt tag that is too long, ie if you have bags inside of bags inside of bags of items.

**Comment by ghost** [comment]
This is caused when a particular chunk is loaded. I've tried erasing the chunk with WorldEdit, but this didn't help. I would assume deleting the region would probably fix it, but I'd rather not go to such drastic measures if possible.

**Comment by mezz** [comment]
There doesn't seem to be a good way to diagnose this issue.
If deleting the chunk did not fix the message, then you did not delete the right chunk.
If you can narrow down which tile is causing the problem I may be able to help, but unfortunately without that I can only guess at the situation.
Can you give another try to figuring out which chunk is causing the problem?

**Comment by ghost** [comment]
I just ended up restoring an older version of the region. I'll have a play around, but I'm 99% sure I deleted the correct chunk as well as neighbouring chunks (went in with a render distance of 2 from multiple directions to figure out which one it was). I'm using binnie patcher, so it could potentially stem from there/binnie's mods affecting a Forestry machine or chunk/region data or something. I tried without binnie's first and it still crashed, but maybe the data was still in the Forestry 'whatever' (seeing as I deleted the chunks I don't know if a machine could have caused it, maybe the TE still existed, I don't know).

Thanks for your time though. I'll see if I can figure anything else out in the meantime.

**Comment by CovertJaguar** [comment]
It's possible using a NBT editor to find and remove specific NBT tags from your world.

https://github.com/jaquadro/NBTExplorer/releases

It is however slightly tedious as you have to find the correct region file (.mca).

If you did that, you could in theory inspect the data directly and tell exactly what caused the error in the first place.
