### ISSUE TITLE
Butterfly NullPointerException

### ISSUE THREAD

**Issue by JackDraco** [ForestryMC/ForestryMC#1339]
Forestry version 1.9.4-5.0.9.143

FTB Unstable 1.10 pack

First time (and every time since) encountering a butterfly:

http://pastebin.com/bjWvCbB1

**Comment by GirafiStudios** [comment]
Fixed in https://github.com/ForestryMC/ForestryMC/commit/ab88e7d57cc603d50e5e80f97748812987d8b106 24 days ago.

**Comment by mezz** [comment]
Thanks for the report!
This is a duplicate of #1311
