### ISSUE TITLE
[1.10] Crates can look odd due to merged models

### ISSUE THREAD

**Issue by HanPrower** [ForestryMC/ForestryMC#1343]
For example, here's the oak sapling crated when using PureBDcraft:
![2016-07-04_14 16 47](https://cloud.githubusercontent.com/assets/1781312/16561632/1711ba60-41f2-11e6-8557-22434bd5bc61.png)

You might hit this issue a lot with RPs that have custom models for things.

Either you'll need to force the overlay item/generated model for crated items (if possible) or just use the texture instead of the item models.

**Comment by Nedelosk** [comment]
I have added a way to add content models for the crate. You only have to create a folder with the name "crates" in the forestry item model folder and add you json file with the name of the uid of the crate in this folder.

**Comment by Nedelosk** [comment]
For the vanilla sapling is the uid: minecraft.sapling. + 0 = oke , 1 = spruce, 2 = birch, 3 = jungle, 4 = acacia, 5 dark oak

**Comment by HanPrower** [comment]
Ah, thanks @Nedelosk. I'll give it a try soon and let you know how it goes :+1:

**Comment by HanPrower** [comment]
Appears to work perfectly. Nice :+1: 

![2016-07-23_23 16 22](https://cloud.githubusercontent.com/assets/1781312/17080531/8951fffc-512b-11e6-9455-353c0ca55bd3.png)

If you're all happy from a dev viewpoint feel free to close this :)
