### ISSUE TITLE
Support for Agricultural Expansion crops in the multifarm

### ISSUE THREAD

**Issue by Dragnier** [ForestryMC/ForestryMC#1346]
This mod is rather fun and it would be helpful if it were supported in the multi-farms.
http://mods.curse.com/mc-mods/minecraft/245339-agricultural-expansion

**Comment by Nirek-K** [comment]
looks like some variation on the magical crops theme, neat. I'll do something with it at some point, Forestry 1.9/1.10 is still very alpha

**Comment by Nedelosk** [comment]
I close this because I have added it to our MultiFarm todo list: #1471
