### ISSUE TITLE
Forestry Multifarms and Magical Crops harvest metadata issue

### ISSUE THREAD

**Issue by Trisscar05** [ForestryMC/ForestryMC#1347]
Playing a modpack called "Best of Both Skyblocks", which combines AgSkies2 and SkyFactory. I got very tired of ender io farms needing a vacuum hopper above them to catch the extra drops they would somehow not have room for when harvesting, so I thought I'd swap to multifarms since I saw that support was recently added for it.
The issue is that, while on managed crops settings the magical crop seeds go in fine; when the machine attempts to harvest them they get spat out into the world with an extra ":1" on their numerical tag. Planting and subsequently breaking the affected seeds doesn't fix them sadly, but if I pick up a non :1 seed with affected seeds in my inventory, they will revert to the affected variety and vice versa.
I suspect this is actually an issue affecting most of the modpack, since I can't use storage drawers with the seeds either without weird issues, but I was hoping yall would know what's going wrong here so I can go fix it.

**Comment by Nirek-K** [comment]
That sounds like something buggy with whatever version of magical crops/other scripting you're using, the managed farm literally just calls the blockbreak on the plant.

**Comment by Trisscar05** [comment]
......Holy crap, the pack maker decided to use the 0.1 alpha version of 'Crops..... wut.
Thx for the point in the right direction, I'll get the LAN host to update and report back if something goes wrong again.
_spends five minutes muttering about bad pack making decisions_
