### ISSUE TITLE
Fix support for IC2 in 1.10.2

### ISSUE THREAD

**Issue by 016Nojr** [ForestryMC/ForestryMC#1348]
It might not be implemented yet, but even though IC2 integration is enabled, I can't get the "Rubberized Electron Tubes" to use in the Forestry farm to automatic farm ruibber.

**Comment by mezz** [comment]
Thanks for the report!
Hm it was working in 1.9. I'll take a look.

**Comment by 016Nojr** [comment]
Thanks for checking it :)

**Comment by mezz** [comment]
Fixed in 5.1.11
