### ISSUE TITLE
Support for Actually Additions in Orchard Mode

### ISSUE THREAD

**Issue by utoc** [ForestryMC/ForestryMC#1349]
Good day!

I would like to request support for Actually Additions mod crops in the Forestry mutlifarm: Flax, Coffee, Rice and Canola seeds.  I tested this today and found that it didn't not work so I assume that support has to be added in.

Their curseforge is available here:  http://minecraft.curseforge.com/projects/actually-additions

Their github is here:  https://github.com/Ellpeck/ActuallyAdditions

If I have neglected any vital information or otherwise dun goofed, please remove this issue and chastise me as needed.  Thanks so much!

**Comment by utoc** [comment]
@Ellpeck is the besty PR maker.  Thanks bro

**Comment by mezz** [comment]
Ah yep. Implemented here https://github.com/ForestryMC/ForestryMC/pull/1491

**Comment by Nirek-K** [comment]
Looking at the pr/merge, it was added directly to the wheat tube, and not also orchard (not a problem or anything, just adding info) will tag it for orchard as well when I get around to messing with stuff.
Edit: Done.
