### ISSUE TITLE
Feature for adding Forestry resources to existing chunks

### ISSUE THREAD

**Issue by EoD** [ForestryMC/ForestryMC#135]
Beehives get removed when loading a 1.7.2 savegame in 1.7.10.
New beehives should spawn in chunks where the old beehives have been removed. Or just respawn it the whole world of a 1.7.2 save.

That is NOT a duplicate of #133. I intentionally created a new bug, as this bug is about respawning them.

**Comment by mezz** [comment]
Added in the latest unstable. Thanks Myst for some of the logic from MagicBees
