### ISSUE TITLE
1.10.2 - Crash when taking damage from tropical bees

### ISSUE THREAD

**Issue by Peach774** [ForestryMC/ForestryMC#1350]
I took 1 tick of damage from tropical bees and then I crashed: http://pastebin.com/QavzFxSK

**Comment by mezz** [comment]
Thanks for the report!
You crashed when the tropical bees attempted to apply a poison potion effect to you. It looks like another mod has a threading issue and may be trying to protect you from poison. Do you have any armor or items that might do that?

**Comment by Peach774** [comment]
Several, notably Blood Magic Living Armor and Psi Armor (with code)

**Comment by mezz** [comment]
I tested for a while but I haven't been able to reproduce this bug. Can you try with just one of your defenses at at time to see if we can narrow it down? It might require more than one, but it would be nice if it was just one mod causing it.

**Comment by Peach774** [comment]
Yeah, I'll try and narrow it down.

**Comment by Peach774** [comment]
It was in an industrial apiary from gendustry, it may be their fault

**Comment by Nedelosk** [comment]
I don't can reproduce this bug. And I think this is not a forestry bug.
