### ISSUE TITLE
Bronze Recipie's Incorrect amount. 1.10.2

### ISSUE THREAD

**Issue by Landriss** [ForestryMC/ForestryMC#1351]
Build: 1.10.2-5.1.10.192

Any recipe that requires a Bronze Ingot is requiring 4 ingots per slot instead of 1.
In testing Bronze from mods works normal. Its only the Forestry Bronze.

**Comment by mezz** [comment]
Thanks for the report!

**Comment by LatvianModder** [comment]
Same here with tin in Smoker and bronze in Habitat Locator - both say it needs 9 ingots per slot

**Comment by LatvianModder** [comment]
Ok just checked, this bug can be seen in other mods, so it must be another mod causing it, not forestry. Possibly a JEI bug? Only happens with ingots. Not sure what causes it. I dont have any recipe altering mods installed.

**Comment by mezz** [comment]
This happens when another mod edits an itemstack from a recipe. Please try to narrow down which mod is doing it so we can report to them. I know it's not JEI but it could be from some mod's JEI integration.

**Comment by Nedelosk** [comment]
I think any mod change the stack size of  the stack that is registered in the ore dict.

**Comment by mezz** [comment]
The recipe item is not altered intentionally, it's a bug from another mod. I have seen this issue from IC2 recently, maybe it was never reported?

**Comment by Nedelosk** [comment]
Yes I think I have found the bug.

**Comment by Landriss** [comment]
Confirmed it appears to be IC2 as well.
(Scratch that, I removed IC2 and it did in fact change the stack value but it did not change it to zero.)

**Comment by CovertJaguar** [comment]
@sfPlayer1 poke

**Comment by Player3324** [comment]
Our bronze recipe takes dusts, not ingots. I don't see how IC2 is involved, but it could be a bug hidden somewhere of course.

If it's a crafting recipe it doesn't matter btw., the crafting code always ignores the stack size.

**Comment by Nedelosk** [comment]
I have found the bug. It is the compressor recipe. You set the stack size of the ore dict stack to 9.

**Comment by Nedelosk** [comment]
You only have to copy the ore dict stack before you change the stack size of it.

**Comment by CovertJaguar** [comment]
> If it's a crafting recipe it doesn't matter btw., the crafting code always ignores the stack size.

@sfPlayer1 I don't think that is true any longer. I've had several people ask me about the "new ability to have recipes with variable sized stacks", making these bugs really annoying.

**Comment by mezz** [comment]
It could affect other recipe types where sized stacks are valid too, so I don't try to cover up this type of issue in JEI.

**Comment by Player3324** [comment]
It was a bug in IC2's jei module, should be fixed now.

**Comment by mezz** [comment]
Cool. The IC2 bug report is here: http://bt.industrial-craft.net/view.php?id=1925
