### ISSUE TITLE
[1.9.4/1.10.2] Config Option to Increase Ore Generation

### ISSUE THREAD

**Issue by Ayrrow** [ForestryMC/ForestryMC#1353]
As per title, it would be nice to have this as an option. I quite like having higher than normal world gen as it makes mining less tedious. Forestry is the only mod currently that generates Copper and Tin, but I also have others which can take advantage of them.

**Comment by mezz** [comment]
Thanks for the suggestion!
I think this is more the job of a mod like CofhCore that takes over ore generation entirely. It doesn't make a lot of sense to add this to Forestry when a more general mod could do it better and work with many different mods.
