### ISSUE TITLE
Issue: Both bee & tree villagers don't have their zombie variant.

### ISSUE THREAD

**Issue by eggyplantsu** [ForestryMC/ForestryMC#1354]
While trying to cure a farmer villager to feed the rest of my villagers in my artificial village, it transformed into a bee villager.

So after discovering this, I decided to see how zombies will infect these villagers, I tossed some villagers into a pit 
(using /Summon villager ~ ~ ~ {Profession:"5" or "6"} command for only forestry type professions ) 
and infected them with a zombie, the villagers turn into regular zombies.

more testing and using the command /summon Zombie ~ ~ ~ {IsVillager:1} the regular zombie that sometimes spawn with a 1/7 chance could probably be the forestry villagers that were invalid and returned as regular zombies, there is no value after 7 with the command /summon Zombie ~ ~ ~ {ZombieType:7}   (6 gives a husk)   (tested in 1.10.2)   (forestry_1.10.2-5.1.10.192)

( I am closing this issue because I am thinking this is a problem that relates to Minecraft's coding, so its something more forge api related.)

**Comment by mezz** [comment]
Interesting! Thanks for looking into it. I only just added the zombie villager textures and haven't had a chance to test. I tried it out and I can confirm what you found.

**Comment by CovertJaguar** [comment]
@cpw mentioned something about dual ids or something for zombie villagers and that the Minecraft system was awful.
