### ISSUE TITLE
Game crashes when I attempt to take apiarist's backpack out of the the Refined Storage crafting grid

### ISSUE THREAD

**Issue by pactuslupus** [ForestryMC/ForestryMC#1356]
Minecraft version 1.9.4{modded}forge- 12.18.0.2010
I have allocated about 4gb of RAM

Unfortunately it doesn't generate a bug report. However, the error I get is

"Internal Exception: java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes"

The backpack has several dozen bees in it, with about half of them being analyzed...if that is important. The system is powered by Ender IO stirling generator...again if that is important. I would tell you how many and what kind of bees I have, but I can't remove the backpack without crashing.

Others have repeated the error for me as well.

Not sure if this is a Refined Storage issue, Forestry issue, or what, but I've reported it to my server administrator, and they suggested I forward it on to the mod authors, so here we are.  Let me know if you need any more information, or would like me to try other things to see if I can repeat the error. I will be reporting this to the Refined Storage mod author as well.

Thanks!

**Comment by CovertJaguar** [comment]
NBT packet overflow.

**Comment by raoulvdberge** [comment]
I don't think this is a Forestry issue, but a Refined Storage one

**Comment by mezz** [comment]
Backpacks with bees have an unusually large amount of NBT, I think this is a Refined Storage issue. Have you reported to them?

**Comment by raoulvdberge** [comment]
Yes, I'm the author. You can close this issue
