### ISSUE TITLE
Error when trying to join a server with the same version of Forestry (1.10.2-5.1.13.202)

### ISSUE THREAD

**Issue by Gemini04126** [ForestryMC/ForestryMC#1359]
I don't exactly know WHY this happens, but the error is:
Internal Exception: java.lang.IllegalArgumentException: The name forestry:doors.walnut has been registered twice, for Block{null} and Block{forestry:doors.walnut}.

**Comment by mezz** [comment]
Thanks for the report!
That's strange. I was not able to reproduce this. Do you have any more information?

**Comment by Gemini04126** [comment]
It seems that by switching my resource pack, it was fixed... HOW DOES THAT EVEN WORK?

**Comment by mezz** [comment]
I have no idea... I'm going to file this under "cosmic rays" or something. 
Let me know if it happens again and we can investigate.
