### ISSUE TITLE
1.10 Some items crash rendering when NBT data is missing

### ISSUE THREAD

**Issue by williewillus** [ForestryMC/ForestryMC#1360]
See: https://github.com/sinkillerj/ProjectE/issues/1306#issuecomment-234612137

The ItemOverride for the Pile is not considering that the tag may be absent, as they usually are in ProjectE's transmutation tables (The transmute system does not map NBT tags so they are stripped in the table).

I understand that it could be viewed as partially a PE thing, but there can be scenarios from other mods where the NBT tags aren't present and shouldn't be relied on to be present.

**Comment by Nedelosk** [comment]
Thanks for the report!

**Comment by mezz** [comment]
Stripping NBT from many Forestry items makes them useless or broken.
ProjectE should consider this problem too.

**Comment by williewillus** [comment]
Not sure of the best way to retain things, though. We don't distinguish NBT when doing transmutations (yet, anyway) so the original author just made it strip tags when adding to the knowledge pool, and we haven't changed it since.

We could just capture the tag as it was when the item was learned I guess but that would let you dupe power in NBT-backed batteries for example by just learning a fully charged one instead of an empty one.

**Comment by mezz** [comment]
It's the same problem JEI runs into, you need an interpreter for NBT if you want to make sense of it since there are so many ways to use it. That requires specific mod integration though. Wish we had a better way.
