### ISSUE TITLE
Crash on Startup when disabling "Lepidopterology" module

### ISSUE THREAD

**Issue by ManMan36** [ForestryMC/ForestryMC#1362]
When I disable the "Lepidopterology" module on forestry version 1.10.2_5.2.2.2.211 I get the following crash.

http://pastebin.com/D9v4EazE

Whenever I run it with the aforementioned module enabled, it will load as normal. I am unsure if this is the case for other modules; I have not tested them.

**Comment by mezz** [comment]
Thanks for the report!
