### ISSUE TITLE
[MC 1.10.2] Crash on camouflaging greenhouse bricks

### ISSUE THREAD

**Issue by XEridaniTribalX** [ForestryMC/ForestryMC#1363]
Upon trying to camouflage the greenhouse bricks with a block from Chisel, I crashed to desktop, and this log ([http://pastebin.com/p025SK76](url)) was generated. Whenever I load the save afterwards, I will crash as soon as the world loads, and get the same crash log.

**Comment by Nedelosk** [comment]
Thanks for the report!
