### ISSUE TITLE
Carpenter Error

### ISSUE THREAD

**Issue by Tesereser** [ForestryMC/ForestryMC#1364]
While making Enhanced Circuit Board ,I supplied the recipe with 2 kinds of bronze ingot like the screenshot below , in this way, I can consume something with less resources。
![image](https://cloud.githubusercontent.com/assets/17476139/17271946/1fc03e28-56bc-11e6-818f-85b4287b0a1e.png)

**Comment by Nedelosk** [comment]
Combined with #1527: #1545
