### ISSUE TITLE
Drops bug with SpongeForge installed

### ISSUE THREAD

**Issue by MastaC729** [ForestryMC/ForestryMC#1365]
With SpongeForge installed, when you try to drop an itemstack with more than one item, the items immediately come back to your inventory.

See https://github.com/SpongePowered/SpongeForge/issues/738 for more information.

**Comment by ftog-thorgal** [comment]
It's not just with stacks but also with a variety of different items. We did quite a lot of testing on this, and here are a few of the things that were causing issues:
- Cobblestone: Q=worked, D=worked
- Coal: Q=failed, D=worked
- Redstone: Q=failed, D=worked
- Botania Petals on Petal Apothecary: Q=failed, D=failed
- Anything in to a Mana Pool: Q=failed, D=failed

Legend
Q = pressing "q" to drop a single item from your hotbar
D = dragging item out of your inventory on to empty space (to drop it)

You can actually see the items drop for a split second and then come right back in your inventory, just like if you are wearing a strong magnet.

**Comment by mezz** [comment]
That's very strange. Forestry doesn't have any hotkey for Q, and doesn't use ASM or reflection at all.
Maybe SpongeForge has an issue with pickup handlers? Forestry has two. 

One for registering when a player picks up genetic items:
https://github.com/ForestryMC/ForestryMC/blob/mc-1.10/src/main/java/forestry/core/PickupHandlerCore.java#L25

And one for the backpacks which automatically pick up items:
https://github.com/ForestryMC/ForestryMC/blob/mc-1.10/src/main/java/forestry/storage/PickupHandlerStorage.java#L25

Please let me know if you need more information.

**Comment by theneedforsneed** [comment]
Fixed by Sponge and can be closed.
