### ISSUE TITLE
[1.7.10] Impossible to breed bees that require Hellish temperature in an Alvery.

### ISSUE THREAD

**Issue by wmrojer** [ForestryMC/ForestryMC#1366]
When placing an Alveary in the Nether it will say temperature is Hot 199%, but an Apiary will say temperature Hellish 199%. Even when putting 3 Alveary Heaters in the Alveary it will still only say the temperature is Hot 249%. It's impossible to get the alveary to see the temperature as Hellish. So Bee's that has temperature requirement "Hellish / None" can't be breed in an Alveary, only in an Apiery.

Forestry 4.2.14.62
Forge 1.7.10-10.13.4.1614

The AlvearyController.getTemperature() that handles Alvearys is using EnumTemperature.getFromValue(float rawTemp) that can never return Hellish while the tileEntity TileApiary that handles Apiary extends TileBeeHousingBase who's getTemperature() is using EnumTemperature.getFromBiome(BiomeGenBase biomeGenBase, int x, int y, int z) that will return Hellish when in a Hell biome.

But having AlvearyController get temperature as Hellish just based on it being in a Hell biome is problably not a good solution since then you would not be able to use Alveary Fans to lower the temperature.

**Comment by wmrojer** [comment]
This bug was introduced in 2 august 2015 [Fix Alveary temperature modifiers have no effect](https://github.com/ForestryMC/ForestryMC/commit/48a59c2ca7632421b234796001a0513b134229bc) and it also seems to exists in the 1.9.4 and 1.10 branches of Forestry.

**Comment by mezz** [comment]
Thanks for the report!
Fixed in Forestry 4.2.15. I'll fix it in the 1.10 branch as well.
