### ISSUE TITLE
[1.10.2] [Bug] Power from forestry engine crash mineceraft 

### ISSUE THREAD

**Issue by Dijkstra1-zz** [ForestryMC/ForestryMC#1368]
I made clockwork engines yesterday, three one on a carpenter, centrifuge and a squeezer, all in line put a clockwork engine one each, all faced the way they where meant, cranked the one on the carpenter, let go and server closed, restart the server and it crashed from it again.

I had quick look at the crash report and what I gather from it would have crash if I had used any of the forestry engines, but I may be wrong I have not look into source code can not say for sure.

Minecraft version: 1.10.2
Forge version:  1.10.2-12.18.1.2026
Forestry version: 1.10.2-5.2.3.213

Edit:
Forgot the crash report thanks @KnightMiner 
Crash report: https://gist.github.com/mezz/3cd1de4eccdb4a548c521190e2227f47

**Comment by KnightMiner** [comment]
Link the crash report please.

**Comment by Dijkstra1-zz** [comment]
Do not know if you get notified about post being edited, so just thought you should I linked the crash report at the top.

**Comment by mezz** [comment]
Thanks for the report!
Looks like Tesla changed their ModId: https://github.com/Darkhax-Minecraft/Tesla/commit/69f27fc3e225138c06390716e9ed1b19f36c74be
I'll update Forestry to work with it. There will be issues with other mods until everyone updates.

**Comment by mezz** [comment]
Fixed in version 5.2.5
