### ISSUE TITLE
[1.10.2] Forestry Crashes Minecraft

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#1370]
Hey guys, 

I have several mods loaded. Without Forestry everything loads fine. When I load forestry it crashes Minecraft when Forge loads the mods.

I tried the two latest versions: 5.2.4.215 and 5.2.3.213

Here is the Crash report:

https://gist.github.com/mezz/73c1a85eb376d65eb1ceecebb12bb296

I use the latest Minecraft: 1.10.2
and the latest Forge: 12.18.1.2044

**Comment by mezz** [comment]
Thanks for the report!
It looks like something else is shipping an old version of the Forestry API, or something strange like that. Can you paste your full client log to https://gist.github.com and link it here?

**Comment by ghost** [comment]
https://gist.github.com/RavingCraze/ee14f4ee9f2a4ad6bb52960d5d417ca6#file-moony-forestry-crash-on-1-10-2

**Comment by mezz** [comment]
Thanks, unfortunately it does not have the information I'm looking for either. 
Please link `fml-client-latest.log` here, it will show where the APIs are loaded from.

**Comment by mrpenguin24** [comment]
Crashes me too

**Comment by mezz** [comment]
@mrpenguin24 Please paste your `fml-client-latest.log` to https://gist.github.com and link it here so I can solve this issue.

**Comment by ghost** [comment]
Hope thats the right one: https://gist.github.com/RavingCraze/68157d6a643d29399df32a00145b70bb

**Comment by CovertJaguar** [comment]
It looks to me like all the API modules are being loaded from the Forestry Jar. Does that leave coremods?

**Comment by mezz** [comment]
I think so, yes.

Please try removing these coremods jars one at a time to see if it fixes the issue. 

```
  LoadingPlugin (RandomThings-MC1.10-3.7.4.jar)
  AppleCore (AppleCore-mc1.10.2-1.3.5.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.45-beta.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
  BetterFoliageLoader (BetterFoliage-MC1.10-2.0.13.jar)
```

Sorry if this is a hassle, I'm pretty certain Forestry is not the actual cause of the problem here but I'd like to help find out what is breaking it.

**Comment by ghost** [comment]
I was going through the list. I always deactivated one core mod and if it didn't changed I reactivated it and deactivated the next. (Obviously I also deactivated the mods that require these core mods)

When deactivating "shetiphiancore-1.10.0-3.3.0.jar" + EnderTanks and Multi-Storage the game loaded finally. 
I then activated "shetiphiancore-1.10.0-3.3.0.jar" without the other mods again and it still worked. 

Long story short: Now everything works with the exact same mods (I also enabled EnderTanks and Multi-Storage) and I have NO idea why. xD Maybe I have inserted to many mods at once, but maybe it was an incompatibility with another mods. (While testing I was updating some of the other mods.)

So whoever has this problem: Try to load each core mod individually and that maybe fixes it!
Thanks at mezz for your support!
If I run into further problems I'll report it!
