### ISSUE TITLE
[1.10.2-5.1.12.200] Apiarist and Arborist Villager Trades 

### ISSUE THREAD

**Issue by Jasems** [ForestryMC/ForestryMC#1372]
Minor problem, but in our latest world Bee trades seem to be on the green Arborist villager and trees on the yellow Apiarist guy.

**Comment by mezz** [comment]
Thanks for the report!
I don't see this issue with a new world. Make sure you have the latest version of Forge, there have been some villager changes somewhat recently. Any existing villagers in your world will stay broken though, new villagers need to be created to test.

**Comment by bhi-elliot** [comment]
This just happened on my server.
It had been running normally (yellow Apiarist had beekeeping trades} for about a month.
Suddenly they changed jobs. Apiarist now has Aborist items and vice versa.

Might have happened when I restarted the server yesterday, but I do that every few days, and like I said it's been a stable environment for almost a month (so many restarts).

Java version: 1.8.0_144
minecraft_server.1.11.2
forge-1.11.2-13.20.1.2454-universal
spongeforge-1.11.2-2393-6.1.0-BETA-2592
Forestry 5.3.4.165
