### ISSUE TITLE
Forestry killed Minecraft!....Maybe.

### ISSUE THREAD

**Issue by MouthyOne** [ForestryMC/ForestryMC#1374]
Just opened it upfor the first time on this computer and it failed on startup. Trying to run skyblock infinity expert mode.

https://gist.github.com/anonymous/57d72f7e7d37229d6ba0ca10f736da5a

**Comment by mezz** [comment]
Thanks for the report.
Forestry is not even in that list of mods...  some coremod from that list is trying to access Forestry's API and failing.

**Comment by MouthyOne** [comment]
Oh my mistake. Sorry
