### ISSUE TITLE
Minor error on console during startup when storage module is disabled

### ISSUE THREAD

**Issue by utoc** [ForestryMC/ForestryMC#1375]
Error here: http://pastebin.com/hnig9qyJ

This was on a new map, error seen during startup.  As best I can tell, it was only an error and it may not have any negative impact.  It doesn't appear to repeat during worldgen.  Just reporting it in case it needs attention.

**Comment by Nedelosk** [comment]
Have you fixed it @mezz ?

**Comment by mezz** [comment]
No, Minecraft loads all the loot even if it is not used, so I need to make a new solution.

**Comment by mezz** [comment]
The proper solution for this is to split up the loot tables for every plugin so they do not try to load items form other plugins.
