### ISSUE TITLE
Crash on Savegame load: forestry_1.10.2-5.2.7.220

### ISSUE THREAD

**Issue by MokahTGS** [ForestryMC/ForestryMC#1377]
Getting a crash loading a savegame:

http://pastebin.com/mMYwkawq

**Comment by CovertJaguar** [comment]
Possible duplicate of #1368

Try updating to the latest version.

**Comment by Nedelosk** [comment]
He uses the last version: forestry{5.2.7.220} (forestry_1.10.2-5.2.7.220.jar)

**Comment by MokahTGS** [comment]
Yup...it is the latest version

**Comment by MokahTGS** [comment]
Would removing TESLA temporarily fix this issue?

**Comment by mezz** [comment]
This is the opposite problem, your TESLA is out of date :).
It should work if you update it to Tesla-1.10.2-1.2.1.42
https://minecraft.curseforge.com/projects/tesla/files
