### ISSUE TITLE
Infernal farm is not available in manual mode

### ISSUE THREAD

**Issue by EnderiumSmith** [ForestryMC/ForestryMC#1379]
For some reason the blazing electron tube can only be used for managed farms which means that if i want to farm nether wart i have to either deal with the farm's inefficient water placement or have a farm only for nether wart and trees.

There is no reason a manual farm can't have nether wart. The same apply for arboretum actually.

**Comment by mezz** [comment]
Yeah, makes sense.
There are lots of legacy reasons for the farm being strange the way it is... it's a lot cleaner now so it may be time to reconsider the way the farm works.

**Comment by EnderiumSmith** [comment]
@mezz It would also be a good idea if manual farms would replant a crop with the same type of crop so the farms can benefit from the row growth boost and allow you to grow an equal amount of crops that use the same electron tube.

**Comment by Nirek-K** [comment]
The orchard tube would do what you want there, for 99% of things.
(the row boost thing, not netherwart, though I technically could add it, and you can grow it using something like agricraft anyway)
