### ISSUE TITLE
crash on load up with forestry 1.10.2-5.2.8.223

### ISSUE THREAD

**Issue by SDUBZ** [ForestryMC/ForestryMC#1382]
crashlog:[crash-2016-08-12_18.17.30-client.txt](https://github.com/ForestryMC/ForestryMC/files/414860/crash-2016-08-12_18.17.30-client.txt)

forge version: 1.10.2-2050
fml client log: 
[fml-client-latest (2).txt](https://github.com/ForestryMC/ForestryMC/files/414868/fml-client-latest.2.txt)

**Comment by MokahTGS** [comment]
Yup...Same.  Here's the crash log:

http://pastebin.com/vHKdnLyn

**Comment by MakeLord95** [comment]
occures on forestry .228, using forge 2052 too... :/
