### ISSUE TITLE
Crash on start-up 1.10-2

### ISSUE THREAD

**Issue by Jesperson** [ForestryMC/ForestryMC#1383]
Crash report: http://pastebin.com/XA8WjVwL
Forge v.: 1.10-2-12.18.1.2011

**Comment by squirrelkiller** [comment]
[crash-2016-08-12_06.24.01-client.txt](https://github.com/ForestryMC/ForestryMC/files/415114/crash-2016-08-12_06.24.01-client.txt)
have another, same issue from that report.

**Comment by Nedelosk** [comment]
Thanks for the report!
But this is a duplicate of #1382.
