### ISSUE TITLE
Crash on Minecraft startup forestry_1.10.2-5.2.8.228.jar

### ISSUE THREAD

**Issue by October45** [ForestryMC/ForestryMC#1385]
Crash report: http://pastebin.com/Lg1aemqs

**Comment by Moustik2002** [comment]
Hi, Same here : http://pastebin.com/Ep0XYWru

**Comment by MakerTim** [comment]
Dube of #1384

**Comment by Nedelosk** [comment]
Thanks for the report!
But this is a duplicate of #1382.
