### ISSUE TITLE
1.9+ crops dont work corectely with multifarms

### ISSUE THREAD

**Issue by EnderiumSmith** [ForestryMC/ForestryMC#1390]
Beet roots are assigned to vegetables but they have seeds thus they should be assigned to crops(wheat).
Chorus fruit is not available at all.

**Comment by mezz** [comment]
There are all good suggestions. 
Can you please split them into one github issue per suggestion and close this one?

**Comment by EnderiumSmith** [comment]
@mezz or I could edit this one and open only one new.

**Comment by mezz** [comment]
It is easier for me to stay organized if you make new issues, that way the issues do not have unrelated information and also no information is lost. They can be 1 line long or just a title, I can keep better track as long as they are split up properly.
