### ISSUE TITLE
1.10.2-5.2.8.235-236 Client crash

### ISSUE THREAD

**Issue by kerenon** [ForestryMC/ForestryMC#1395]
Forge: 12.18.1.2065
Forestry: 1.10.2-5.2.9.237.jar
Crashlog: [https://pastebin.com/0ZEtWxfJ](https://pastebin.com/0ZEtWxfJ)

One of our players (small family server) is getting a strange crash. We were unable to pinpoint an exact cause, but it seem it has something to do with farms and/or butterflies. There is nothing about it in the server log, the client just closes randomly. Tried forestry 236 and 237, with forge 2061, 2064 and 2065.

Edit: Tried again to visit the same area on the server, and now I've got a server crash too: [https://pastebin.com/0aiWfK81](https://pastebin.com/0aiWfK81). Don't know if the two are connected, but it's suspicious.

**Comment by mezz** [comment]
Thanks for the report!
From the first report this appears to be an issue with the greenhouse. It's still being worked on and has some bugs.
The second crash is most likely the same issue.

**Comment by kerenon** [comment]
"Funny" thing is I am 100% sure nobody on the server built anything that resembles a greenhouse. Fact is, nobody even knew forestry has greenhouses. We're unable to load the world without mcediting out the affected area, but I'm positive, the only things there are a max size tree farm, a few enderio conduits, a mekanism wind generator, 4 storage drawers, 3 forestry trees, and a large amount (50+) of butterflies. Nothing else.

**Comment by mezz** [comment]
Well, it's not a full greenhouse but the`BlockGreenhouseDoor` is the cause of the crash in the crash log you gave me.

**Comment by CovertJaguar** [comment]
Hmm....I dunno, I looked at the code, all it does is call world.getTileEntity() in Block.getActualState(). If that's wrong, then a lot my stuff is screwed.

**Comment by kerenon** [comment]
I had some spare time, and tried to do some testing. Today I managed to load the map, by editing the playerdata and moving everyone from the area. Then I tried to move back, and everything worked for a while. I was literally doing nothing, just standing. Not even looking around. It took ~6 minutes (seems random) and my client crashed, but this time the server survived.

For now I've cut out the area from my live map, so I'm not in a hurry. I've tried replicating the problem on a new map, but couldn't.

I don't know what to think, and I don't know how or what to test, so if you need anything from me, or have any idea what to test, I'd be happy to help.

**Comment by Nedelosk** [comment]
I don't think that that is a bug on our side, I think a other mod have a problem with remove or add tile entities.
