### ISSUE TITLE
Rebalance electron tube crop type

### ISSUE THREAD

**Issue by EnderiumSmith** [ForestryMC/ForestryMC#1396]
Currently some electron tubes are unbalanced. A reed farm requires diamonds but i can automate it in vanilla with a BUD. I suggest rebalancing the electron tube crop types to match the product more.

Here is an example:

Copper tube-cactus
-cactus can be automated without restone

Tin tube-reeds
-easy to automate with vanilla

Lapis tube-pumpkin and melon
-can be automated with vanilla but take more space
-pumpkins and melons are rare, just like lapis

Iron tube-Wheat(and beet roots)
-can be automated with vanilla but harder than pumpkin
-a crop as basic as iron

Bronze tube-Vegetables
-can be automated like wheat
-fits bronze just like wheat fits iron

Infernal tube-nether wart
-just like before

Apatite tube-mushrooms
-just like before
-mushrooms use already existing nutrients instead of photosynthesis so the apatite fits.

Ender tube-chorus plant
-change recipe to use popped chorus or enderpearls
-no need to explain why it fits.

Gold tube-arboretum
-you cant automate this without a dedicated mod item
-wood actually fits gold: they are both items that you dont have a lot unless you get an autofarm in which case you get 17000 and they also have been in the game from early on
-should also work in manual mode

Obsidian tube-bog earth
-both are related to earth, water and change
-bog earth is not that essential and easy to farm by hand early on but needs a dedicated machine like trees
-obsidian also fits with gold like bog earth fits with trees

From here i kinda started to run out of tubes:

Quartz tube-coco beans
-like quartz, once you get access to one you can easily get more
-coco beans is not that useful to autofarm
-quartz tube needs to be added

Diamond OR Emerald-orchard
-the orchard offers a unique harvesting method to a system that is already a challenge to automate with anything but the multifarm
-the orchard also has the biggest output due to the vertical size and genetically modified trees can produce a lot
-it is also not essential as all products can be replaced by other crops

This list was an example to a possible configuration. How is it?

**Comment by mezz** [comment]
Sounds good to me. I think we should consider reducing the number of tubes/modes while we're at it though.
Cactus and Sugar Cane can be combined, same goes for combining Vegetables and Wheat.

**Comment by EnderiumSmith** [comment]
@mezz Isn't a problem that cactus and reeds use different amounts of water?
And if crops and vegetables are combined the manual farm will need to replant a crop with the same crop or a different farm will be needed for each crop and it isn't a multifarm that way.

But the arboretum and orchard should be separated. And the arboretum should be able to be used for manual farms.

What do you propose for the electron tubes if those 2 are combined?

**Comment by mezz** [comment]
My main concern is that the farm is very hard to use without studying the documentation for a long time. If someone sets up a farm that can farm wheat but not carrots, that's a bit confusing. They often believe it is broken.

Water consumption is not a large consideration for me, it is very easy to get infinite water. I would try to find a balance between the existing consumption requirements but it should not be a stopping point.

If the farm is going to share more crops in one area, it will need to replant properly. This is a new feature that would make the farm easier to use.

I agree that arboretum and orchard should be separated. It does not make sense to have different functions between manual and automatic, it is complicated and confusing.

I'm not sure which tubes to use. The farm is already very expensive to build for early-game. I think that gating some of the tubes behind resources is not extremely important, except for stuff like the ender tube and the infernal tube.

By the way, the ender tube is currently used for integration with Extra Utilities' Ender Lilies. It should be expanded to include anything that grows on end stone, like the chorus plant.

**Comment by EnderiumSmith** [comment]
@mezz water should be a consideration. What if i make a desert survival modpack where the low water consumption of the cactus is essential in making a profit?
Reed and cactus cant be combined efficiently and are quite different in terms of water requirements so they should be kept separated.

Should the bronze tube be used for coco beans? Or use tin and use bronze for reeds?

**Comment by CovertJaguar** [comment]
You could make the farm "smarter" as in have it detect the plant type and adjust accordingly. I'm not sure how possible that is with the current implementation, but it might be worth some kind of redesign.

**Comment by ilordnightmarei** [comment]
i wold like to add the possibility to use the speed and efficiency upgrades with the multi block farm  and or be able to have  auto and manual farms on the same  machine multi block just realized i have a setup that uses auto and manual so only think id like to see is speed and efficiency ones

**Comment by Nirek-K** [comment]
Adding more gearboxes/powering them increases the multifarm speed linearly, and it is already quite efficent/low cost. Auto/manual farms do have to be kept seperate though, mostly meaning having one of each. (sidenote, if you want 'smart' plant logic, use the orchard tube, it does much of what you want already, as it just cuts back the plant to 0 growth rather than harvesting (and works with most plants the other tubes do and is largely the only way to sanely have a large diverse harvestcraft field etc for example)

**Comment by Nedelosk** [comment]
@mezz Is there anything that speaks against making the farm "smarter" ?

**Comment by mezz** [comment]
The farm code is just a lot of work, I am not sure it's a good idea to change it at this point.
It may be a better idea to reintroduce the old-style farm blocks and do what you want with those, so players can use them or the big farm.

**Comment by Nedelosk** [comment]
What about the logic of the new old-style farms ? Using the logic classes of the multiblock farm and rewrite them a little bit or creating new ones ?

**Comment by mezz** [comment]
They should probably the existing ones because of mod compatibility...
I have bad memories of working on farm code though, you should do what you think is best.
