### ISSUE TITLE
Wild end bees should get along with endermen

### ISSUE THREAD

**Issue by EnderiumSmith** [ForestryMC/ForestryMC#1398]
Wild end bees should not attack end creatures like endermen and shulkers when calm. Bees angered by a player punching the hive should attack everything.

**Comment by mezz** [comment]
Looks like shulkers will not be attacked because they are classified as "Golems" like the Iron Golem and Snowman. 
I'll make sure hives do not attack semi-passive vanilla mobs like Endermen or Pigmen unless the hive is angry.

**Comment by EnderiumSmith** [comment]
@mezz Shouldn't the type of hive determine the mob that is not attacked? End bees should attack pigmen. And why are golems ignored by wild bees?

**Comment by mezz** [comment]
The general rule is that bees should not attack passive mobs, and endermen and pigmen are somewhat passive. I am not taking the bees' local environment into consideration, there isn't a scenario where a wild end hive would be in the nether. I think that golems would not pose any threat to bees, same as other passive mobs, so they are not attacked.
