### ISSUE TITLE
Butterfly items render using inactive species

### ISSUE THREAD

**Issue by EnderiumSmith** [ForestryMC/ForestryMC#1402]
Butterfly items use the inactive species for rendering.The entitys render right so when you catch them they appear to drop a different butterfly. Other traits like size seem to be used from the active side.
http://imgur.com/a/GEiDH
Also whats the difference between lifespan and metabolism?

**Comment by mezz** [comment]
Where was this fixed @Nedelosk ?

**Comment by Nedelosk** [comment]
I have fixed it in my greenhouse PR. https://github.com/ForestryMC/ForestryMC/commit/a20fbbe60f701a5e31752b2bfb6eeda6312c2f81#diff-3c8da7077fb95cb8e7b72f27b718dbb9L52

**Comment by mezz** [comment]
Thanks. Please keep changes separate when you can, so it is easier to confirm where changes happen.
