### ISSUE TITLE
Worktable allows for infinite item creation in certain situations

### ISSUE THREAD

**Issue by utoc** [ForestryMC/ForestryMC#1403]
This is a really weird one that one of my users came across today.  The premise is this:  If the worktable is unable to "save the recipe for easy recall" indicated by the item being available to be clicked in the upper right box of the worktable GUI, even if you pull an item from the result box, your materials do not get used and you may continue to pull items freely.

I tested this with Mekanism's Digital miner which has two non-stackable ingredients and I think this is part of how the bug works although I couldn't find any other recipes this worked with

Its very easy to repeat and works 9 times out of 10 using the miner as an example.

Place the crafting ingredients in the recipe 3x3.  Place only enough ingredients in the supply 2x9 to make one resulting item.  Click the item result box, you'll receive the resulting item but no ingredients are depleted.  Shift clicking will fill your inventory.  The item is never saved in the favorites.

I'm running FML 2065 anf Forestry 5.2.9.237.

If there are any troubleshooting steps I can take or anything I can to help narrow down the cause, please let me know

**Comment by mezz** [comment]
The Digital Miner has some items in the recipe with strange NBT: `{mekdata:{}}` that was throwing off the worktable. I made it so that it is more careful to check that it can actually craft the item before it tries. 

This prevents crafting the Digital Miner until its NBT strangeness is resolved, but the infinite item glitch here is fixed.

**Comment by Renadarain** [comment]
Can confirm infinite items as follows:

Hi :)

When using the Forestry Worktable to create Lumien Blend you have unlimited resources when shift-clicking - as in it does not remove the ingredients from the table.

MC: 1.11.2
Forge: 1.11.2-13.20.0.2315-installer
forestry_1.11.2-5.3.4.111
Cofh Core: 1.11.2-4.2.2.7-universal
T.E: 1.11.2-5.2.3.6-universal
T.D: 1.11.2-2.2.3.6-universal
T.F: 1.11.2-2.2.2.4-universal

Regards,
Renada

**Comment by mezz** [comment]
This has been fixed in 1.10 and above.
