### ISSUE TITLE
Farm Control Block Not Accepting Redstone Signal

### ISSUE THREAD

**Issue by Utildayael** [ForestryMC/ForestryMC#1405]
So I have a 5x5x4 multiform which is working properly with one exception, I can't shut it off! Well, I can by breaking the multiblock but I can't shut it off with redstone via the farm control block. 

I've tried moving it around the multiblock on levels 1, 2. I've tried a level on it from the side and no dice but then read it has to be top/bottom to stop entire farm. Ok no problem. Tossed it up on top layer and put a level on top of it. Nothing. Put it on bottom layer with a  level on bottom. Nothing. Can't seem to get it to recognize redstone signal. I'm assuming it would flag in the UI that it was disabled by redstone just like the Forestry machines? Even if not, I watched the farm continue to  harvest trees so it clearly wasn't stopping. :(

MC 1.10.2
Forestry 5.2.9.237
Forge 12.18.1.2065

Thanks!

**Comment by Nedelosk** [comment]
I have fixed this issue with 043571b659ca3ca9b7d62b6ed0a44049b58a9c66.

**Comment by Utildayael** [comment]
Thanks!
