### ISSUE TITLE
Accept Humus input in Multiblock farm

### ISSUE THREAD

**Issue by Zorgatone** [ForestryMC/ForestryMC#1406]
I'm not able to manually input humus blocks to the multiblock farm, is it by design?
Could you possibly add the option to manually craft humus, and input it to the farm?
I think that would be very useful, especially when you can't find enough apatite and you aren't able to produce fertilizer. The way I'm crafting Humus blocks is with Mulch that I get from squeezing Apples (which come from the farm).
Considering that I have a way to produce dirt blocks, the farm could accept my manually-crafted Humus blocks, and output sand blocks (consumed humus) and replace those automatically. This way I could have a self-sustaining farm (powered with charcoal) that won't rely on limited fertilizer

**Comment by temp1011** [comment]
This has been included in https://github.com/ForestryMC/ForestryMC/pull/1948 right? Just checking so I don't try and work on something pointless.

**Comment by Nedelosk** [comment]
@temp1011 Yes
https://github.com/ForestryMC/ForestryMC/blob/05d1eb87ce1132fb82e2c60d10324697ab2d44da/src/main/java/forestry/farming/ModuleFarming.java#L210
