### ISSUE TITLE
Floating desert acacia "trees" appear in the middle of nowere

### ISSUE THREAD

**Issue by EnderiumSmith** [ForestryMC/ForestryMC#1408]
http://imgur.com/a/ZgZk3
These things started appearing after using desert acacia.
It seems that a copy of the tree spawns high up and in the N-W edge of the chunkload radius.
They seem to correlate with _hybrid_ saplings planted. I haven't broken any of them but the slim group correlates with the acacia-balsa sapling planted near some sequoia. The second thick group correlates with a recently planted group of acacia-sequoia sapling which is what made me realize they're connected.
Other hybrids don't produce this but i haven't tried acacia secondary.

**Comment by chantrykomori** [comment]
I can attest to this, and it's replicable.

**Comment by CovertJaguar** [comment]
One of the funner bugs I've seen recently.
