### ISSUE TITLE
Fermenter not accepting forestry fertilizer

### ISSUE THREAD

**Issue by jasoninsane** [ForestryMC/ForestryMC#1410]
using minecraft 1.10.2 with forge 1.10.2-forge1.10.2-12.18.1.2075 and mod version forestry_1.10.2-5.2.9.241. I have tried compost, fertilizer and mulch in the fermenter and it will not accept either one.

**Comment by mezz** [comment]
Thanks for the report!
You closed this issue, did you find a solution?
