### ISSUE TITLE
1.10.2 - Cannot add Wheat to a multifarm

### ISSUE THREAD

**Issue by viper2g1** [ForestryMC/ForestryMC#1412]
I've created a farm using an Intricate Circuit Board with the following: Arboretum, Arboretum, Crop Carm, Vegetable Farm.  I've added water and fertilizer.  I'm in a desert biome.  I can add potatoes, carrots, and sapplings just fine.  I am unable to add wheat (minecraft:wheat) to the farm.  I also tried Mouldy Wheat (forestry:mouldyWheat) which doesn't work either.

Forestry: 1.10.2-5.2.9.241
Forge: 1.10.2 - 12.18.1.2073

**Comment by Nirek-K** [comment]
if you mean into the gui to plant, you would want seeds, not actual wheat.

**Comment by viper2g1** [comment]
I feel like a giant idiot.
