### ISSUE TITLE
Improve charcoal pile multiblock

### ISSUE THREAD

**Issue by EnderiumSmith** [ForestryMC/ForestryMC#1416]
The current implementation for the charcoal pile is not very good. Its not intuitive and the size is quite limiting. I suggest using a entirely different multiblock system for them.
The charcoal pile should work similar to the terrafirmacraft one:
-It can be any size and any shape. Lighting in will activate all connected ones.
-The structure needs to be covered in full, solid, non-flammable blocks. If any neighboring blocks are not valid the log pile will turn to a fire block in the next random block tick. Then neighboring log piles will be next to a invalid block and will disappear as well if the fire doesn't get them first. If a log pile finds a neighboring air block on block update/activation it will place fire there.
-no fancy render or loan blocks.

Another feature could be creosote oil production if railcraft is installed(after it updates):
-when the charcoal pile completes, creosote oil will accumulate in rain tanks placed under the structure.
The rain tanks need enough capacity to collect all creosote at once. They will only collect from log piles above them and need to touch the structure.

**Comment by Nedelosk** [comment]
I have improved the pile in 1.11.2.
