### ISSUE TITLE
Nullpointer ITeslaConsumer

### ISSUE THREAD

**Issue by ilightwas** [ForestryMC/ForestryMC#1417]
http://pastebin.com/gu6Je30f

Put down a mekanism machine, like a metallurgic infuser for example, place a forestry engine (clockwork was used), when energy goes through, the server crashes.

This issue was found in a server that I play, looking at the code I made a temporary fix, a simple check on the consumer , if null to return 0. Not sure if the issue lies within mekanism or the tesla thing. Also I didn't feel like making a pull request, since I don't quite understand the inner workings of the forestry energy system or the tesla api. I'm still learning on how to mod.

**Comment by mezz** [comment]
Thanks for the report!
Forestry checks that the machine has the capability, and only tries this if it does have the capability. The fact that a Mekanism machine returns null here is is bug. Please report this bug to Mekanism and link back here.
