### ISSUE TITLE
Tweak the effects of placed fluids

### ISSUE THREAD

**Issue by EnderiumSmith** [ForestryMC/ForestryMC#1420]
Ethanol and Biomass: should burn normally without exploding. Why would it explode? its not gasoline.
Liquid glass: it should behave like lava. Fire should not be able to exist on top of liquid glass.
Honey: should act as a drowning death trap like buildcraft oil. You cant swim in honey.
Crushed Ice: should flow slower.
Seed Oil and Short Mead: should burn.

**Comment by CovertJaguar** [comment]
Gasoline doesn't generally explode either.
