### ISSUE TITLE
Feature request: Milk Capsules ore dict with milk buckets for recipes?

### ISSUE THREAD

**Issue by KillerRamer** [ForestryMC/ForestryMC#1425]
Milks generally that liquid that's difficult to deal with/ carry around, so when I saw that I could make milk capsules I was fairly excited. However when I tried crafting a cake with milk capsules it was a no go.  Any chance of allowing this in the future? It would be greatly appreciated!

**Comment by CovertJaguar** [comment]
See! This is why Forge Recipes need to accept FluidStacks =P

**Comment by KillerRamer** [comment]
Forge plez ;-; 

But yeah... So it's something more on forge's end but something the forestry team would be cool with adding  if they can?

**Comment by Nedelosk** [comment]
I think we can add this after #1464.
