### ISSUE TITLE
Config option to slow down/disable bee flower vomit

### ISSUE THREAD

**Issue by purpleposeidon** [ForestryMC/ForestryMC#1434]

**Comment by Vexatos** [comment]
You could just breed the flowering type off the bees and make them work on cacti instead...

**Comment by purpleposeidon** [comment]
@Vexatos It's an option, but kind of an end-game solution? If you've just gotten a new species, it's not going to keep whatever flower-traits its parents had?

Oh, alternatively it'd be cool if they only spread flowers that are actually nearby. Pink tulips all over the place would be much less offensive.

**Comment by mezz** [comment]
I'm thinking that bees should only spread the flowers that are already within their range, it makes sense.

**Comment by Vexatos** [comment]
That would make a lot of sense, indeed.

**Comment by mezz** [comment]
This is fixed in the latest version.
Bees will only spread the flowers that are already within their range. 
If bees have 20 flowers in their range, they will stop planting them. This is configurable down to 0 if you want, and up to 1000.
