### ISSUE TITLE
Chisel Blocks do not render when used as Camo for Forestry Greenhouse blocks

### ISSUE THREAD

**Issue by Drullkus** [ForestryMC/ForestryMC#1440]
I know that [Fancy Fluid Storage] has fake-rendering for our blocks, with CTM included. You could check out the code to see how @Lordmau5 rendered our blocks in FFS.

![2016-10-01_16 13 13](https://cloud.githubusercontent.com/assets/5010174/19017539/245a7f9a-87f2-11e6-97fc-725ec3ec3d95.png)

![2016-10-01_16 13 30](https://cloud.githubusercontent.com/assets/5010174/19017541/3bb7a5b4-87f2-11e6-8dcb-a80f5a77cd3a.png)

**Comment by Drullkus** [comment]
Related: SleepyTrousers/EnderIO#3746

Looks like it's our end. Will update you on further information later.

**Comment by b0bst3r** [comment]
I don't know if it helps but this happens with any connected texture chisel block, non-connected texture blocks work fine.  Also the issue with EnderIO conduits http://i.imgur.com/E37oydU.png that's a connected texture chiselled stone (big tile) block, but take any non-connected texture block and it's fine.
