### ISSUE TITLE
Camouflaged Paneling recipe question.

### ISSUE THREAD

**Issue by marcin212** [ForestryMC/ForestryMC#1446]
In the Carpenter, the Camouflaged Paneling recipe requires three different dyes (red, blue and yellow).
I've noticed that it consumes 6 of any dye instead.
Is this working as intended?
https://img.bymarcin.com/screenshot-2016-10-04_03-19-54.png

forestry_1.10.2-5.2.14.263

**Comment by Nedelosk** [comment]
Thanks for the report!
I think the carpenter ore dictionary support is broken.

**Comment by mezz** [comment]
This looks like a duplicate of https://github.com/ForestryMC/ForestryMC/issues/1364
I will mark it as confirmed and make it "bug major".
