### ISSUE TITLE
Flickering Greenhouse

### ISSUE THREAD

**Issue by marcin212** [ForestryMC/ForestryMC#1447]
I built a Greenhouse like this: https://www.youtube.com/watch?v=ATtNh2QzKr8 .
After using a glass block in the camouflage slot, the whole Greenhouse starts flickering.
It only happens on multiplayer.

forestry_1.10.2-5.2.14.263

**Comment by Nedelosk** [comment]
I hope it is fixed, @marcin212 can you test it please ?

**Comment by marcin212** [comment]
@Nedelosk  Yes, it is fixed. Thank you.
