### ISSUE TITLE
1.10.2 Carpenter recipes dont consume enough items

### ISSUE THREAD

**Issue by mcenderdragon** [ForestryMC/ForestryMC#1448]
In Forestry 5..2.12.258 the Carpenter dont use enough items if you craft the Camouflaged paneling. All required items must be there, but the stacksize is not checked.

Images:
http://imgur.com/npEXQwV
http://imgur.com/HtLCw5g

**Comment by Nedelosk** [comment]
Thanks for the report!
I think the carpenter ore dictionary support is broken.

**Comment by mezz** [comment]
Duplicate of #1364
Marking it as a major bug there
