### ISSUE TITLE
Missing Blocks and Items when connecting to Server

### ISSUE THREAD

**Issue by BSKCorp** [ForestryMC/ForestryMC#1450]
Just recently updated Forestry to the lastest version (5.2.14.266) When I try to connect to my server at home on a separate machine I get a error of Fatally missing blocks and items. The client log shows it as this.
http://pastebin.com/UkWbzntR
Server log gives nothing. 

Using Forge version 12.18.1.2095

**Comment by mezz** [comment]
Thanks for the report!
If you have multiple mods that add those fluids, you should disable Forestry's in the `config/forestry/fluids.cfg` file on both the client and server. Without doing that, the client and server do not always agree on who is making the fluids, and you get the error shown.

**Comment by BSKCorp** [comment]
Thank you very much.
