### ISSUE TITLE
Game crash when placing lemon tree block

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#1451]
Was messing around in creative mode in a sp map, spawned myself 64 of the lemon tree leaves and when I tried placing it the game crashed and produced this error. 

http://pastebin.com/E1GSgHh5

I can no longer enter this map either, as it produces the same error.

**Comment by ghost** [comment]
Just tried the same thing in a new world but this time with a common walnut leaf block and same issue. EDIT: tried planting a lemon sapling, bonemealed it into a full tree, sheared one of the lemon leaves block, and when i try to place that block the error happens as well

**Comment by mezz** [comment]
Thanks for the report!
Confirmed.

**Comment by mezz** [comment]
Fixed in version 5.2.14.268
