### ISSUE TITLE
Crash for Forestry using Forge 2097

### ISSUE THREAD

**Issue by DatrixTHLK** [ForestryMC/ForestryMC#1452]
I started up minecraft and it closed out after step 2 of 7

Crash Log: https://gist.github.com/DatrixTHLK/3b524100a6421fb3b56da0e756ade2c0

Minecraft: 1.10.2
Forge: 12.18.1.2097
forestry:  5.2.14.267, 5.2.14.269

**Comment by mezz** [comment]
Thanks for the report!
Confirmed.
Since this is the new recommended version of Forge, this issue is a high priority.

**Comment by mezz** [comment]
Talked to Lex and it looks like this is actually an issue with Forge.

**Comment by mezz** [comment]
Made a PR to Forge here: https://github.com/MinecraftForge/MinecraftForge/pull/3300

**Comment by mezz** [comment]
Fixed in Forge 12.18.2.2098

**Comment by DatrixTHLK** [comment]
I see. Thanks for the heads up and finding out the real problem.

**Comment by DatrixTHLK** [comment]
Well, that's handy I am getting a 502 bad gateway error...
