### ISSUE TITLE
Soldering iron creates wrong type of circuit board upgrade 1.10.2-5.2.14.269

### ISSUE THREAD

**Issue by Giovanni-NL** [ForestryMC/ForestryMC#1453]
Steps to reproduce: 
- Set the soldering iron to 'Machine Upgrade' mode
- Insert empty basic circuit board 
- Insert blaze electron tube
- The circuit board gets created. The tooltip when hovering over the created upgrade, while still in the soldering iron says 'Speed Boost II' amongst other things. This is expected.
- Take the new circuit board out of the soldering iron.
- It now has magically become an 'Infernal Farm' upgrade, and cannot be used in machines such as  the Centrifuge. This is not expected... 

Using Forestry version 1.10.2-5.2.14.269

Version 1.10.2-5.2.13.261 did not have this bug.

**Comment by Nedelosk** [comment]
I don't can confirm, this bug.

**Comment by Nedelosk** [comment]
Can you please test it again ?

**Comment by Giovanni-NL** [comment]
I've retried this.  Our server now uses Forestry 5.2.15.291, and the issue is gone.  I can now create a machine upgrade as expected.

 I am not able to test this on the server with version .269

Since the bug seems to have disappeared in a newer version, I am closing this issue.
