### ISSUE TITLE
Keys Stick After Holding them Down For a Few Seconds

### ISSUE THREAD

**Issue by cjburkey01** [ForestryMC/ForestryMC#1454]
At first, this didn't sound like a Forestry bug to me either, but when Forestry is removed, the bug goes away.  Whenever I hold a key for about 2 or more seconds, it sticks until pressed again.  I believe this is only a Mac problem at the moment, my friend uses Windows and currently isn't having an issue.

There's no console log that might provide a clue as to the issue.

**Comment by Nedelosk** [comment]
Can anyone validate this issue, if not I will close this issue?

**Comment by cjburkey01** [comment]
I don't think it's happening anymore, I don't remember which modpack I had this issue in, so I guess for now it's closed.

**Comment by Nedelosk** [comment]
Ok, thanks
