### ISSUE TITLE
1.10.2 - Biomes O Plenty saplings are not accepted by MultiFarm

### ISSUE THREAD

**Issue by MauveCloud** [ForestryMC/ForestryMC#1458]
I built a MultiFarm in survival mode, and tried to add some BoP pine saplings, but they won't go in, either by shift+click or by manually placing them.  I checked 1.7.10 in creative mode for comparison, and in that version, they are accepted.  I also tried pink and white cherry, redwood, willow, and flowering oak.  None of those went in.  Saplings from vanilla Minecraft like birch, oak, and spruce work fine, as do Forestry saplings from a village chest (silver lime and hill cherry).

**Comment by mezz** [comment]
Thanks for the report!
The integration for BoP has not yet been added completely in 1.10.

**Comment by Nedelosk** [comment]
I close this because I have added it to our MultiFarm todo list: #1471
