### ISSUE TITLE
Multifarm sapling replanting broken in 1.10.2 version

### ISSUE THREAD

**Issue by MauveCloud** [ForestryMC/ForestryMC#1461]
Using the default "Arboretum" configuration, in previous versions a multifarm would replant saplings collected as trees grew.  In the 1.10.2, even once I removed the hopper I was using to transfer the output to a chest, the saplings just sat in the output inventory of the multifarm, not getting automatically transferred to the empty germlings inventory, let alone being replanted.

**Comment by mezz** [comment]
Thanks for the report!
This is actually the new intended behavior, it gives more control over the operation of the farm.

**Comment by MauveCloud** [comment]
Okay.  I was initially a bit upset about that, but then I remembered that there have been a few times when I've wanted to change what kind of trees I was using, which previously required manually removing the planted saplings and grown trees first to make sure no saplings of the old tree type got replanted.  With the new behavior, I can set up automation of sapling restocking via other mods (e.g. ExUtils 2 transfer node with item filter, or eventually Buildcraft), and disconnect that when I don't want them replanted.  I'm not sure how I'd do that if Forestry were the only mod installed, though.

**Comment by mezz** [comment]
Forestry does not stand alone very well, it was originally a BuildCraft addon and so it needs other mods for item/power/fluid transport.
