### ISSUE TITLE
Add Fluid Container Output Slot to all TileEntitys with Fluids

### ISSUE THREAD

**Issue by Nedelosk** [ForestryMC/ForestryMC#1464]

**Comment by mezz** [comment]
If we make this change, we should do 3 slots.
You need "input", "processing", and "output". 
This is because some containers hold more than 1 bucket of fluid. 

Example: 
You have a stack of items that hold 2 buckets each in the "input" slot. There are some empty ones in the output slot.
You take 1 bucket of fluid out of the first item, now that item must go in a "processing" slot. Without a processing slot, it has nowhere to go.

One easier solution is to make the Bottler have 3 slots for input and output, and make it push fluid to machines next to it. Then we can remove the fluid container slots from all other TileEntities.

**Comment by Nedelosk** [comment]
That is a good idea.

**Comment by mezz** [comment]
For an example of pushing fluids, see the Rain Tank. It pushes fluid to anything below it.

**Comment by Nedelosk** [comment]
1ac7a7de426f9f40aa76cdbbea02ac056bbf1d19

**Comment by CovertJaguar** [comment]
> For an example of pushing fluids, see the Rain Tank. It pushes fluid to anything below it.

I made a utility function for that in Railcraft, it is semi-complex and used often enough.
https://github.com/CovertJaguar/Railcraft/blob/e607200ef7bf8e81e4c051d849d5f513a5f63b3b/src/main/java/mods/railcraft/common/fluids/TankManager.java#L171-L171

```
    public void pull(AdjacentTileCache cache, Predicate<? super TileEntity> filter, EnumFacing[] sides, int tankIndex, int amount) {
        Collection<IFluidHandler> targets = findNeighbors(cache, filter, sides);
        pull(targets, tankIndex, amount);
    }

    public void push(AdjacentTileCache cache, Predicate<? super TileEntity> filter, EnumFacing[] sides, int tankIndex, int amount) {
        Collection<IFluidHandler> targets = findNeighbors(cache, filter, sides);
        push(targets, tankIndex, amount);
    }

    public void pull(Collection<IFluidHandler> targets, int tankIndex, int amount) {
        transfer(targets, tankIndex, (me, them) -> FluidUtil.tryFluidTransfer(me, them, amount, true));
    }

    public void push(Collection<IFluidHandler> targets, int tankIndex, int amount) {
        transfer(targets, tankIndex, (me, them) -> FluidUtil.tryFluidTransfer(them, me, amount, true));
    }

    private Collection<IFluidHandler> findNeighbors(AdjacentTileCache cache, Predicate<? super TileEntity> filter, EnumFacing[] sides) {
        List<IFluidHandler> targets = new ArrayList<>();
        for (EnumFacing side : sides) {
            TileEntity tile = cache.getTileOnSide(side);
            if (tile == null) continue;
            if (!TANK_FILTER.apply(tile, side.getOpposite())) continue;
            if (!filter.test(tile)) continue;
            IFluidHandler tank = FluidTools.getFluidHandler(side.getOpposite(), tile);
            if (tank != null)
                targets.add(tank);
        }
        return targets;
    }

    public void transfer(Collection<IFluidHandler> targets, int tankIndex, BiConsumer<IFluidHandler, IFluidHandler> transfer) {
        targets.forEach(them -> transfer.accept(get(tankIndex), them));
    }
}
```

**Comment by Nedelosk** [comment]
The bottler can now push fluids so I think that I can close this issue.
