### ISSUE TITLE
Wrong climate info when apiary is placed in greenhouse.

### ISSUE THREAD

**Issue by marcin212** [ForestryMC/ForestryMC#1469]
Only visually bug, because modest queen is working.
https://img.bymarcin.com/screenshot-2016-10-18_22-24-02.png
https://img.bymarcin.com/screenshot-2016-10-18_22-24-48.png

**Comment by Nedelosk** [comment]
@marcin212 Can you test it please ?

**Comment by marcin212** [comment]
@Nedelosk it works inversely
https://img.bymarcin.com/screenshot-2016-10-19_02-09-50.png
https://img.bymarcin.com/screenshot-2016-10-19_02-10-09.png

**Comment by Nedelosk** [comment]
Fixed with 94b0b44f51ee9cea488c507a72560cac05d4e731
