### ISSUE TITLE
[1.10.2] BeeHives are loading chunks when checking flowers

### ISSUE THREAD

**Issue by LemADEC** [ForestryMC/ForestryMC#1470]
As tested with HermitPack 1.1.0 on a dedicated server
Updated to latest forestry_1.10.2-5.2.14.288
Using Forge 12.18.2.2107 with spongeforge-1.10.2-2098-6.0.0-BETA-1819.jar

We observe lag coming from BeeHives in the profiler, looks like the mod is loading new chunks while checking for flowers.
We can also observe lag coming from calls to areItemStackEquals.
![image](https://cloud.githubusercontent.com/assets/4776032/19499312/075a1d0e-9596-11e6-8b3a-0825c119ff61.png)

**Comment by mezz** [comment]
Thanks for the clear report!
Will fix this shortly.

**Comment by mezz** [comment]
Please try with Forestry 5.2.15.290 and let me know if it fixes the issue completely.

**Comment by LemADEC** [comment]
ChunkLoading is fixed. However the areItemStackEquals() lag remains:
![image](https://cloud.githubusercontent.com/assets/4776032/19500812/e54c0a78-95a0-11e6-9dd5-03d3e1f561dd.png)

**Comment by mezz** [comment]
Ah ok, I missed that in your original report. Well we're halfway there, I'll take a look at how I can optimize that.

**Comment by mezz** [comment]
Please try with Forestry 5.2.15.291

**Comment by LemADEC** [comment]
lag is fixed, thanks!
Nota: I didn't verify if the hive still work properly.
