### ISSUE TITLE
[Request] enable BioGenerator and E-Engine when IC2 is not installed - 1.7.10

### ISSUE THREAD

**Issue by Sharkking** [ForestryMC/ForestryMC#1474]
Is there any chance that this can be done ? 

Thanks

Sharkking

**Comment by mezz** [comment]
It may be possible but they would not do anything, why would you want them without IC2?
1.7.10 development is in crash-fix-only mode, but we may be able to do this on the 1.10 branch if there's a good use for it.

**Comment by CovertJaguar** [comment]
As far as I know, the E-Net is completely absent if IC2 isn't present, so it's not like any power would flow.

**Comment by Sharkking** [comment]
I thought they are producing and recieving RF as well thats why i am asking for.
Generating Bio Ethanol seems useless without being able to put it into a generator since the BioGas Engine is the only Machine accepting it so far (without IC2).

**Comment by mezz** [comment]
Biomass is pretty good for Forestry. Ethanol is mostly useful for compatibility with other mods, it's not that great otherwise.
The electrical engine creates RF from EU, so it needs IC2 to do anything. The BioGenerator only creates EU.

**Comment by MauveCloud** [comment]
I can't find it now, but I have a vague memory of seeing a mention within the last couple of months of some other mod that uses EU separate from IC2, but isn't usable with Electrical Engines and Bio Generators.  Maybe the mod involved was TechReborn (https://minecraft.curseforge.com/projects/techreborn), or does Forestry already recognize that as a version of IC2?

**Comment by Sharkking** [comment]
So mabe an config option to enable RF generation with the BioGenerator or a BioRfGenerator for future releases ?

**Comment by Nedelosk** [comment]
I don't think that we will make this, so I close this.
