### ISSUE TITLE
Crashes while generating a new world

### ISSUE THREAD

**Issue by MainFreak** [ForestryMC/ForestryMC#1475]
Hello. I am using Forestry in my Modpack and it seems to crash the game every time I generate a new world. I tried it multiple times but it seems like the problem involves Forestry and Pam's HarvestCraft ( I will report it to them too )

I hope this Crash Report helps?
https://gist.github.com/mezz/0cf37491080b6747fb5696389c67ddbb

**Comment by mezz** [comment]
Thanks for the report!
This looks like an issue with CookingPlus and Pam's Harvestcraft. Forestry is not involved.

**Comment by MainFreak** [comment]
I am sorry. I had a lot of crashes today. This one is the one I meant. Later on I downgraded to a Forestry Version from a few days ago.

https://gist.github.com/mezz/2f233b73f2686bc5a5e75f0d38bbfc31

**Comment by mezz** [comment]
This looks like a problem from a mod that adds drops to grass. Please try removing Pam's Harvestcraft and see if you still have the issue.

**Comment by Nedelosk** [comment]
I think that this crashe doesn't come from forestry, so I close this issue.
