### ISSUE TITLE
Wood Pile processes instantly

### ISSUE THREAD

**Issue by 666lumberjack** [ForestryMC/ForestryMC#1476]
Not sure if this is intended under the new system, but right-clicking a wood pile with a flint&steel instantly processes it into ash and charcoal. Also, all species have the same carbonization and combustability, but I'm guessing those values are WiP?

**Comment by 666lumberjack** [comment]
Also, an enhancement that would be nice would be the ability to ignite the pile with anything that would set it on fire (similar to a vanilla nether portal) not just right-clicking it with a flint & steel. This would be a nice QoL thing for people who use other methods of firesetting than the flint & steel (like botania's mana blaster with a kindle lens, a thaumcraft wand with the right research once that gets updated and anything like the firestarter from Thermal Expansion if something like that is made for 1.10.2) and also allow automation of wood pile processing with some ingenuity and extra mods.

**Comment by EnderiumSmith** [comment]
can confirm. also the recipe for loan blocks got worse.
