### ISSUE TITLE
[1.10] Electrical Engines won't reliably stay connected to IC2 cables

### ISSUE THREAD

**Issue by MauveCloud** [ForestryMC/ForestryMC#1478]
This might seem like IC2's fault based on http://bt.industrial-craft.net/view.php?id=1959 but in single-player that only happens when visiting and returning from another dimension such as the Nether.  However, I've seen Electrical Engines sometimes lose connection to IC2 cables after merely exploring in the Overworld, or even fail to connect when initially loading a world, so I'm thinking Forestry might also be partially to blame here.

**Comment by marcin212** [comment]
Similar to #1401

**Comment by mezz** [comment]
Thanks for the report! 
Yes this is a duplicate. Once they fix their issue, please test and report back if it seems like there is still a problem on Forestry's side.
