### ISSUE TITLE
IC2 fertilizer not working in multifarms

### ISSUE THREAD

**Issue by Kalmeira** [ForestryMC/ForestryMC#1479]
For Forestry version 1.10.2-5.2.15.294
IC2 fertilizer will not go into a forestry multifarm and I cannot find any configs that would turn this off. I have also not found in the change logs where this feature has been removed.

**Comment by 3TUSK** [comment]
~~There is no support of using ic2 fertilizer in multifarms from beginning of time iirc.~~
~~See also: #580 #1305~~
Edit: see below.

**Comment by MauveCloud** [comment]
I just checked, and ic2 fertilizer works in a multifarm in Forestry 4.2.16.64 (for Minecraft 1.7.10).  Not only does it go into the multifarm in that version, the multifarm operates and consumes the ic2 fertilizer.

**Comment by 3TUSK** [comment]
_That is something I have never heard about..._

Edit: Found it. http://jenkins.ic2.player.to/job/Forestry/60/
