### ISSUE TITLE
Multifarm - Lag on server when multifarm planting saplings (1.7.10)

### ISSUE THREAD

**Issue by StargateMC** [ForestryMC/ForestryMC#1488]
Hi All,

I've got some serious lag on server whenever we have decent sized farms running and they need to plant saplings. I'm running v4.2.15 on forge 1614. This reduces my server from 20 tps to 2 every few seconds (I run a dedicated server with 32GB of RAM and an 8 core Xeon CPU.. so it really shouldnt...).

Can you please investigate possibly slowing down planting speed (if you even support 1.7.10)?
Check the trace attached.

![farm](https://cloud.githubusercontent.com/assets/9921203/19826881/696d01e2-9de2-11e6-8987-dba082d0d59c.png)

I'll give this a crack myself at some point, but I am not that experienced in java and have zero knowledge of Forestry's code... so it might be a quicker fix for you guys.

If you cant help, no worries :)

**Comment by mezz** [comment]
Thanks for the report!
I'll have to investigate when I have some time.

**Comment by StargateMC** [comment]
Thanks for the quick response @mezz :) Appreciate you looking into it.

**Comment by StargateMC** [comment]
@mezz Sorry to bother you mate, but can I confirm that B:farming=false disables multifarms in the Forestry config file? or is supposed to?

**Comment by mezz** [comment]
Yes, in `config/forestry/plugins.cfg`.
Disabling plugins isn't tested very often so you may run into issues. Let us know if you do.

**Comment by StargateMC** [comment]
Thanks @mezz :)
Soon as I disabled multifarms my TPS went back to 20. It removed the blocks as intended :)

**Comment by Nedelosk** [comment]
I close this, because it seems like it doesn't appears in 1.12.2 anymore and we will never fix this in 1.7.10.
