### ISSUE TITLE
[Suggestion] Double doors linked as per vanilla

### ISSUE THREAD

**Issue by xenoflot** [ForestryMC/ForestryMC#1489]
Hi,

At the moment, double doors operate independently. It would be nice if Forestry doors operated in tandem as vanilla doors do.

Cheers!

**Comment by mezz** [comment]
Vanilla doors do not work together normally, it may be a mod like Quark or Charset that changes their behavior.

**Comment by xenoflot** [comment]
Today I learned!

Well... it would be nice if Forestry doors operated in tandem as Quark or Charset doors do :-)

**Comment by mezz** [comment]
You should find out which of your mods is doing it and ask them, it may be easier for them to do it. Just link back here so they can discuss if necessary.

**Comment by xenoflot** [comment]
Will do!
