### ISSUE TITLE
1.10.2 Farm control not stopping farm

### ISSUE THREAD

**Issue by Gunner76th** [ForestryMC/ForestryMC#1494]
I have a farm control block placed in my farm (5x5x4) with the control in the bottom center. When I apply a redstone signal to it either by a lever or a block of redstone, the farm continues to operate as if there was no signal given. In the Wiki it states that the entire farm will shutdown if the control block receives a signal from the top or below. 

I also tried placing the control block on the top and the farm still continued to operate. 
I also tried placing 1 control on each side of the farm with a block of redstone attached, and still it continued to operate. It would appear that the Farm Control block is bugged and not shutting down the farm as it should regardless of where it is placed.

**Comment by mezz** [comment]
Thanks for the report!
Sounds like it's not working as intended at all.

**Comment by Gunner76th** [comment]
I guess I should note that this is for release 5.2.12.257. I do not know if this issue was addressed by later Jenkins builds. I have informed my modpack dev that forestry is seriously out of date. I am the lead Admin for our group, and I am training a new Dev who is working on maintaining our pack.

**Comment by Havanacus** [comment]
Same issue: https://github.com/ForestryMC/ForestryMC/issues/1405

It's been a few versions since I tested this but... 
Powering control blocks from the top and bottom does nothing as stated.
Powering from the sides does work, but it only stops the farm from replanting and takes a deceptively long time to show any results.  Probably working as intended, but lacks feedback.

**Comment by Gunner76th** [comment]
@Havanacus If you read the Wiki, it clearly states that powering the control block from the Top or Bottom is suppose to completely shut down the farm so that no harvesting or planting takes place. Powering it from the side is suppose to shut down that specific side so that no planting or harvesting occurs on that side. In 1.7.10 the shutdown was instant. As per the posted wiki's instruction of the intended operation of the MBS Farm, this is not working as intended.

**Comment by jadeonking** [comment]
I can also confirm on version 1.10.2-5.2.15.296 that the farm control blocks do nothing ![image](http://i.imgur.com/G4BSoF7.png)

**Comment by Terpo** [comment]
Controls on the side will work, but these only prevent replanting, not harvesting. So if you have a Gourd farm you can not switch it off, because they grow by themselves.

It would be nice of the farm simply stops harvesting when giving a redstone signal.

**Comment by Gunner76th** [comment]
I am not sure if I forgot to mention our if you failed to notice, but my
farm is a managed one with 2 melon plots, one wheat plot and one bogged
earth plot. Even if your statement was correct, which based off experience
with 1.7.10 it is not,  the bogged earth and what should have stopped,
however they do not. In 1.7.10 the control would shut down ALL operations
both planting and harvesting on both managed and unmanaged farms.

**Comment by Nedelosk** [comment]
I have fixed this issue with 043571b659ca3ca9b7d62b6ed0a44049b58a9c66.
