### ISSUE TITLE
[crasheo] place the carpenter, centrifuge and machinery etc

### ISSUE THREAD

**Issue by sergio06emilio** [ForestryMC/ForestryMC#1495]
when placed on the spinner, the carpenter I am crashea the minecraft version 1.10.2. Help me

**Comment by sergio06emilio** [comment]
[crash-2016-11-02_15.12.42-client.txt](https://github.com/ForestryMC/ForestryMC/files/567802/crash-2016-11-02_15.12.42-client.txt)

**Comment by sergio06emilio** [comment]
here are the report

**Comment by mezz** [comment]
Thanks for the report!
This seems to be a crash from the dark roleplay medieval mod, please report to them here:
https://minecraft.curseforge.com/projects/dark-roleplay-medieval/issues

**Comment by sergio06emilio** [comment]
Thanks you
