### ISSUE TITLE
Error when trying to access a forestry GUI [forestry_1.10.2-5.2.16.315.jar]

### ISSUE THREAD

**Issue by Mattsingen** [ForestryMC/ForestryMC#1499]
I get the following error on my server when I try to open either the Arborist's Chest and Bee House (haven't tried anything else)
It worked yesterday on build 312. 
 
http://pastebin.com/KxRzag0M

**Comment by mezz** [comment]
Thanks for the report!
I will fix this soon.

**Comment by Mattsingen** [comment]
I can confirm that build 316 has fixed this issue. Thanks a lot mezz.
