### ISSUE TITLE
Crates in JEI cause the GUI to disappear

### ISSUE THREAD

**Issue by Peach774** [ForestryMC/ForestryMC#1500]
When viewing creates in JEI on the newest JEI and forestry versions, the whole gui freaks out. 
![2016-11-05_19 36 28](https://cloud.githubusercontent.com/assets/5171184/20041879/e82968b6-a43d-11e6-9f30-9974d011e762.png)
![2016-11-05_17 42 29](https://cloud.githubusercontent.com/assets/5171184/20041880/ea91a672-a43d-11e6-9dfa-c5d74c254287.png)

**Comment by mezz** [comment]
Thanks for the report!
Have you confirmed this with just JEI and Forestry? 
I assume there is another mod involved, because I can't reproduce this problem with those two alone.

**Comment by Peach774** [comment]
I bet it has to do with the addition of metals which are automatically crated which could include immersive engineering or railcraft (i think it might be railcraft)

**Comment by Peach774** [comment]
Caused by Goetia. Closing because it isnt forestry's fault

**Comment by mezz** [comment]
Thanks.
For future reference, the Goetia report is here: https://github.com/RootsTeam/Goetia/issues/10
