### ISSUE TITLE
Biome painter UI unresponsive

### ISSUE THREAD

**Issue by Reginald-Halifrax** [ForestryMC/ForestryMC#1501]
The biome painter has an issue, where the biome selection UI is completely unresponsive unless you have gui scaling set to auto... I run in normal mode, and auto sets it to even larger than large. 

Luckily a biome painter isn't something I'm using often so it isn't that huge a deal. But I'm putting this out anyhow.

**Comment by mezz** [comment]
Thanks for the report!
Forestry does not have a biome painter, I think you have reported to the wrong place.

**Comment by Reginald-Halifrax** [comment]
that's embarrassing i don't know how i managed that
