### ISSUE TITLE
[1.10.2] [5.2.16.320] Bottler Creosote Duping

### ISSUE THREAD

**Issue by davidgarland** [ForestryMC/ForestryMC#1502]
Hello! I've been using Railcraft, Immersive Engineering, and Forestry together in a custom modpack.

When putting a Railcraft creosote bottle into the Bottler, more creosote is added into the internal fluid buffer but it is not removed from the insertion slot, nor does the liquid in the bottle go away-- effectively creating an infinite creosote source.

In addition, when breaking a Bottler, the "block break" particles seem to move faster than other blocks; I'm not sure why this happens.

Most all mods, including Railcraft, Forestry, and Immersive Engineering, are up to date.

Modlist:
WoodConverter
AnalogueRS
AutoRegLib
Baubles
Baubles-Hud
Better With Mods
BetterFps
Blood Magic
Botania
Charset
Chat Box
Chisels & Bits
Coral Reef
EasyBreeding
Embers
Enderthing
ExpandedBonemeal
Forestry
Guide-API
Hardcore Darkness
Immersive Engineering
Inventory Tweaks
JEI Bees
Just Enough Items
MCMultiPart
Morpheus
Nature's Compass
Persistent Bits
Quark
Railcraft
Roots
Runes of Wizardry
Runes of Wizardry - Classic Dust Pack
ShadowMC
Sound Filters
Stacksize Mod
Super Circuit Maker
Surge
The One Probe
TIS-3D
Vanilla Automation
Zoology

**Comment by mezz** [comment]
Thanks for the report!
I'll take a look at the creosote issue.
Please open a new issue for the particles, by having one problem per issue it's easier to keep track of things as they are fixed.

**Comment by davidgarland** [comment]
Sorry for the incorrect title and having 2 issues in one-- the version number I had given was from Blood Magic instead of Forestry. ^_^'

**Comment by CovertJaguar** [comment]
It seems to be a widespread issue, but not sure why: https://github.com/CovertJaguar/Railcraft/issues/1012

**Comment by mezz** [comment]
I ran into an annoying SpecialSource or ForgeGradle issue that's blocking me from testing this easily.
https://github.com/MinecraftForge/ForgeGradle/issues/336#issuecomment-260102552

**Comment by CovertJaguar** [comment]
You may need to use the dev version.
https://dl.dropboxusercontent.com/u/38558957/Minecraft/Railcraft/Railcraft_1.10.2-10.0.0-dev.jar

**Comment by davidgarland** [comment]
Took a video to demonstrate the bug, as proof and to provide a look at what's happening to see if you can figure it out.

https://youtu.be/oTSnAaDIKx8

**Comment by RogueShadow** [comment]
The same thing occurs with Canisters from Pressure Pipes

**Comment by Nedelosk** [comment]
Fixed in 1.12.2 with https://github.com/ForestryMC/ForestryMC/commit/18e10f617c436fefe1db166db1967d1136af83ba
