### ISSUE TITLE
[1.10.2] [5.2.15.296] Butterflies gravitating towards 0,0 where huge swarms are found

### ISSUE THREAD

**Issue by Jamdog** [ForestryMC/ForestryMC#1504]
**Modpack:** FTB Presents HermitPack 1.2.1
**Mod Version:** Forestry 1.10.2 - **5.2.15.296**

The title really says it all.  Butterflies are flying towards 0,0, from all over.  This means that travelling along the lines x=0 or z=0, clusters of butterflies are found, and when 0,0 is reached, there is often a swarm of hundreds of butterflies.

While this is great for lepidopterists, who can collect every butterfly in one handy spot, it does cause some lag when you are near.

This image shows the butterflies travelling south in a straight line, along the x=0 latitude.
![2016-11-08_12 46 18](https://cloud.githubusercontent.com/assets/94101/20100198/5620004c-a5b4-11e6-8d39-3ac1dea99fb9.png)

And this image shows the butterflies congregating at 0, 0,  There are about 80 butterflies in the screenshot, but the number constantly increases, and it is necessary to kill them all (or collect them) every day to prevent excessive lag.
![2016-11-08_12 48 11](https://cloud.githubusercontent.com/assets/94101/20100199/56206c6c-a5b4-11e6-8b4c-b561b32f2b5c.png)

**Comment by CovertJaguar** [comment]
So the new homing AI has a bug =P
