### ISSUE TITLE
Cross-compatibility bug with TAIGA ores generation

### ISSUE THREAD

**Issue by 0Navis0** [ForestryMC/ForestryMC#1505]
I link this issue here since Forestry is linked to this issue https://github.com/Zkaface/TAIGA/issues/56. I curruntly still researsh all the other mods involved in this issue. There is surely 4 or maybe more mods involved inside. Frankly this bug is really the strangest I ever seen. It will we be definitely not a simple one to solve.

**Comment by Nedelosk** [comment]
Is this still a thing ?

**Comment by fewizz** [comment]
No =P

**Comment by Nedelosk** [comment]
Thank you
