### ISSUE TITLE
Bee buildup during pause

### ISSUE THREAD

**Issue by Sp3rw3r** [ForestryMC/ForestryMC#1508]
When the game is paused bee particles continue to buildup. My slow pc can handle the buildup of an hour or so but when I leave the game on pause for a night it cannot handle the massive amount of bees.

Something weird happened with butterflies too. There was a huge amount of butterflies at the place where I fell into the void before. I was playing in a superflat void world. At the location where I fell off and several blocks down (negative y) there was a huge amount of butterflies. No performance issue but it looks weird.

**Comment by EnderiumSmith** [comment]
its to beautiful to be a bug. shut down your computer over night.

**Comment by Nedelosk** [comment]
I can't confirm that.

**Comment by Nedelosk** [comment]
Can anyone confirm this issue, if not I will close this it.

**Comment by EnderiumSmith** [comment]
i can confirm. build hive(i tested with alveary). press esc and wait a few minutes.
