### ISSUE TITLE
Multiblock farm not working when chunkloaded and offline

### ISSUE THREAD

**Issue by lrdfang** [ForestryMC/ForestryMC#1510]
I am not sure if this bug is on you guys or FTB, but since I saw it first with forestry I will post here and move it to them if I need to. I am playing the Direwolf 20 1.10 mod pack while using FTB Utils to chunkload. If I log out for a while and the server is empty chunkloading grows the crops just fine. However when I log in I have a fully grown farm and the multiblock farm is struggling to harvest and replant everything. From what I can tell even though everything is chunkloaded the multiblock farm stops operating when the chunks would normally unload.

**Comment by mezz** [comment]
Thanks for the report!
This issue is most likely with FTB Utils. The farm probably does not have permission from FTB Utils to alter the blocks when you are offline.

**Comment by lrdfang** [comment]
that is what I figured it was, I will take this over to the FTB Utils team and report it with them, so they know as well.

**Comment by lrdfang** [comment]
Not a bug after all I just realized my power wasn't chunk loaded. Once I got that fixed everything worked.

**Comment by mezz** [comment]
Thanks, glad it worked out.
