### ISSUE TITLE
[1.10][no clue what version but im using the FTB direwolf20 one] Item Deletion Bug

### ISSUE THREAD

**Issue by yameatmeyourdead** [ForestryMC/ForestryMC#1512]
In the carpenter, if you have a valid recipe or not selected, and you scroll wheel an item in from your inventory that is a part of the recipe you tried, it will delete.

**Comment by yameatmeyourdead** [comment]
Actually, you don't even have to have a recipe in it. Any items scroll wheeled into it will be deleted.

**Comment by Nedelosk** [comment]
That's not a bug.
