### ISSUE TITLE
[MC 1.10.2] Crash on loading world (Forestry v1.10.2-5.2.16.327.jar / Bottler)

### ISSUE THREAD

**Issue by jennybrush** [ForestryMC/ForestryMC#1513]
Crashed when I set down the bottler; then crashes each time I try to reload the singleplayer world :( 
(Note: Original crash in Forestry 1.10.2-5.2.16.326; tried version 5.2.16.327 to be sure it hadn't already been fixed - crash reports are identical)

Full crash report here: https://gist.github.com/jennybrush/8d4955aed692a7ab94c39750cd1ca390

**Comment by Nedelosk** [comment]
Duplicate: #1532
