### ISSUE TITLE
[MC 1.10.2] Short Mead (in bottle) not craftable

### ISSUE THREAD

**Issue by halaali** [ForestryMC/ForestryMC#1515]
There is currently no legit way to obtain the bottled version of short mead.

**Comment by Nedelosk** [comment]
SirSengir removed the item and made it to a potion.
2530a7fb15f511754c345fd78d61990b6a9b67d2

**Comment by SirSengir** [comment]
Sorry, wasn't quite what I had intended. Seems I went overboard when removing the infuser. Should be re-implemented as a new item.
