### ISSUE TITLE
[1.10.2, 5.2.16.323] language missmatch

### ISSUE THREAD

**Issue by Peter041098** [ForestryMC/ForestryMC#1516]
https://youtu.be/Xut0MxuIIHQ

**Comment by mezz** [comment]
The wrong language is coming from JEI.
For some reason it thinks Greek is a good fallback for missing UK English... Do you happen to have Greek as your system language or something like that?

**Comment by Peter041098** [comment]
Ok I'll have a look and see if it appears on other mods blocks 
P.s. My system language is british English

**Comment by Peter041098** [comment]
When i started Minecraft today the bug disappeared, ill try Agustin the language and see what comes up
