### ISSUE TITLE
Circuit in max sized farms disappearing

### ISSUE THREAD

**Issue by topher2010** [ForestryMC/ForestryMC#1517]
A friend and I have 3 max sized forestry farms running.  However, we are noticing that the circuit boards are disappearing at seemingly random intervals.  It's getting tiresome replacing them all the time.  We are hooked up with refined storage buses and cables, however nothing is in our inventory system in regards to circuit boards.

Thanks,

**Comment by Lunchington** [comment]
can confirm just happened to me as well. i have the 4x4x4 vegetable farm.

**Comment by topher2010** [comment]
Just curious if this has been able to be fixed in latest version or not?

**Comment by Nedelosk** [comment]
Not yet

**Comment by Nedelosk** [comment]
No further reports of disappearing circuits. So I close this issue.
