### ISSUE TITLE
Forestry Worktable has Meta Items that have durability

### ISSUE THREAD

**Issue by Speiger** [ForestryMC/ForestryMC#1519]
Forestry has a weird bug which i am not a fan of.
Since 1.9.4 metadata is a completly differend function then getItemDamage().
Yes its true that ItemStack.itemDamage has to be ItemStack.getMetadata else the moddevs who creates these items gets into trouble but here is the thing: There is now the possebility to make multi DamageItems
that means the itemDamage is split from the metadata and for example: Metadata 0 has a max damage of 12000, metadata 1 has the max damage of 60000 and metadata 2 has the damage of 25.
Forestries worktable seems to dislike these items really much and resets them to the itemDamage/metadata 0.
Now it would be nice if you could take care of that too so meta items that have damage are fully supported. Because vanilla MCs crafting table has no issues with them. (And forge recipes still use getItemDamage to compare recipes while MC vanilla uses getMetadata)

Thanks for reading

**Comment by mezz** [comment]
This has been fixed in 1.10 and above.

**Comment by Speiger** [comment]
@mezz thanks. Did you try it out with IC2C?

**Comment by mezz** [comment]
I haven't tested with IC2C specifically, but the algorithm I came up with now is much more safe than before and makes no assumptions about meta or nbt at all.

**Comment by Speiger** [comment]
Ok @mezz this is not against you. But i made these types of things too and fall on my face with it.
I suggest to test it before claiming its no longer an issue.
1 thing i can tell you you didnt account for is StackCrafting. IC2C has recipes that can take up to 28 Items in 1 Slot. And yes that is possible now. Even vanilla support that kind of recipes by default.

**Comment by mezz** [comment]
That is not the same as this issue at all.

**Comment by Speiger** [comment]
Not the same but related and same area of code.
Just trying to help. Sry if i come over rude

**Comment by mezz** [comment]
This issue is closed. If you find it was closed in error, please explain. If you find a similar but different issue, please open a new issue.

**Comment by Speiger** [comment]
well i will let other people do that. Since i am done with IC2C. Patches are still comming but mostly bugreports which are littlery so far (after 14 days) in single digit area. (1000 players and i expected more bugs).
But i gave players a lot of reasons in classic not to use Forestries crafting table after they got 2 hours into the game.
Anyway thanks for fixing that issue. I know not many devs do like random bugfixes even on unreleased mods or just let people wait +6 months to get it done or say "Version no longer supported".
(Those guys get usually on a blacklist of mods i will never use)

So yeah have a nice time.
