### ISSUE TITLE
Ender Bees flower should be something other then Dragon Egg

### ISSUE THREAD

**Issue by dabigmoose** [ForestryMC/ForestryMC#1520]
While in single player mode this is not an issue but on something like a faction server or any other multi player server, attaching it to an item that only spawns on the initial Dragon Kill can be problematic.  In reality you could just reset the end or cheat in additional eggs but if it was made to be a different flower in the end that was more plentiful....   Just a feature thought as this has come up as an issue on the server I am currently playing on.

**Comment by Nirek-K** [comment]
You can breed out that trait using ender drones into normal princess's (You can buy more drones from apiarist villagers) And in 1.9/10 the dragon is not a 1 time fight (though I have intended to add the fruit thing in the end to their flower list, need to get around to that)

**Comment by dabigmoose** [comment]
Actually while you can resume on the dragon it only drops egg on first kill causing many problems on multi player servers.  Currently eggs are dropping on some other kills but Mojang is got an issue open as a bug to close it.

**Comment by Nirek-K** [comment]
Cute, I would have thought that would be the whole point of fighting it again :p (I have not touched 1.10 as a player, so my knowledge is limited) In any case, I will look into adding the flower/fruit thing to the ender list this week, until then there is the breeding solution (some apiarist villagers have ender drone as their upper trade)

**Comment by dabigmoose** [comment]
Thank you
