### ISSUE TITLE
GUI error spam from Reliquary void tear

### ISSUE THREAD

**Issue by PONYRYDE** [ForestryMC/ForestryMC#1522]
With Reliquary installed opening any Forestry GUI continuously throws

 [Server thread/ERROR]: Unknown listener type: xreliquary.items.ItemVoidTear$VoidTearListener@5ae4b36

As seen here https://github.com/P3pp3rF1y/Reliquary/issues/186

Using 1.10.2-5.2.16.330 and Reliquary 1.10.2-1.3.3.585

**Comment by mezz** [comment]
Thanks for the report!
Fixed in the latest version.

**Comment by ProsperCraft** [comment]
Came to report, had the same issue, thank you guys for fixing it 👍
