### ISSUE TITLE
[1.10.2] Electric Engines no longer have a limit on Electron Tubes.

### ISSUE THREAD

**Issue by Dukat863** [ForestryMC/ForestryMC#1525]
I noticed that in 1.10.2 Electric Engines no longer have a limit on how many Electron Tubes of a single type they can use.
For example, if I put four Iron Electron Tubes, which decrease consumption by 1 EU/t each, I would get 20 RF/t out of 1 EU/t.
In previous versions, Electric Engines did not accept more than one Copper and Iron, and no more than two Tin and Bronze electron tubes.

**Versions**:
Minecraft 1.10.2
Forge 12.18.3.2185
Industrial Craft 2 2.6.128-ex110
Forestry 5.2.16.331

**Comment by Nedelosk** [comment]
Is this a bug or is this wanted @mezz ?

**Comment by mezz** [comment]
I do not want to limit how many Electron Tubes of a single type can be used, so we should fix the balance of these tubes.

**Comment by Nedelosk** [comment]
Related commit: https://github.com/ForestryMC/ForestryMC/commit/0df85063a1dfb4a41c5e49062c475662513a85d4
