### ISSUE TITLE
[1.10.2] Green house stop working?

### ISSUE THREAD

**Issue by Dijkstra1-zz** [ForestryMC/ForestryMC#1526]
I have a base in the extreme hills biome, which is too cold for most bees, so built a greenhouse put a heater in and my after warming up my bees were happy but when i joined the server the next, the bees though they were outside and are reading the temperature of the extreme hills biome, instead of the temperature of the greenhouse which is still warm enough for them.

**Comment by Nedelosk** [comment]
Have you a climate control in your greenhouse ? You need one to control the temperature of the greenhouse.

**Comment by Dijkstra1-zz** [comment]
![2016-12-10_22 20 34](https://cloud.githubusercontent.com/assets/11648771/21076745/56b91c6a-bf2b-11e6-815c-c21b8a838196.png)
![2016-12-10_22 20 46](https://cloud.githubusercontent.com/assets/11648771/21076746/56bc863e-bf2b-11e6-8851-5fa1b18a480d.png)
![2016-12-10_22 20 52](https://cloud.githubusercontent.com/assets/11648771/21076744/56b7ca86-bf2b-11e6-94f8-ab41f9fe6982.png)

**Comment by Nedelosk** [comment]
Thanks for the report!
