### ISSUE TITLE
Spam Error Message when using Squeezer

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#1528]
Just got into Forestry on my new server for Hermitpack and as soon as i put seeds into the Squeezer i get this error constantly spamming until i take them out. Anyone know the problem?

[19:03:52] [Server thread/ERROR] [forestry]: Unknown listener type: xreliquary.items.ItemVoidTear$VoidTearListener@7561271a

I also get this error message when putting any wood into the carpenter.

[19:11:15] [Server thread/ERROR] [forestry]: Unknown listener type: xreliquary.items.ItemVoidTear$VoidTearListener@70f95c69

Thanks.

**Comment by Nedelosk** [comment]
This bug is fixed in the last version of forestry.

**Comment by Nedelosk** [comment]
#1522

**Comment by ghost** [comment]
Thanks, will updating this individual mod break the modpack Hermitpack? ill be sure to keep a backup of world incase you dont know.

In my mod options it says i am running version 5.2.16.321, on the website it says the latest is 4.16 so im confused here.

Thanks.
