### ISSUE TITLE
Possible Dupe Bug with Backpacks?

### ISSUE THREAD

**Issue by znxster** [ForestryMC/ForestryMC#1530]
Using Modpack "Hermitpack" v1.4.0 (for MC 1.10.2).
This contains Forestry v5.2.16.321.

So here is what I did to determine it was duplicating on me.

- Emptied my inventory and removed my armour (to ensure there was no odd interaction)
- Crafted two "Digging Backpacks"
- Set both of them to resupply.
- Put one stack of gravel into each of the backpack
- Drag a stack of gravel across the empty spaces in my inventory
- Dupes

I didn't test the other backpacks but I did test with other items (cobble, clay etc) and it duped them all.

**Comment by LunyashaRu** [comment]
Confirmed. It's totally working with any kind of backpacks and items.
forestry_1.10.2-5.2.16.347

**Comment by mezz** [comment]
Thanks for the report!
Fixed in the latest version today.
