### ISSUE TITLE
[CRASH 1.10.2 / 5.2.16.330] Ticking block entity. Name: forestry.bottler // forestry.factory.tiles.TileBottler

### ISSUE THREAD

**Issue by msdossys** [ForestryMC/ForestryMC#1532]
Upgrading world from FTB Infinity Lite 1.10.2 v1.2.0 (forestry_1.10.2-5.2.16.326) to v1.3.3 (forestry_1.10.2-5.2.16.330). Bottler in world crashes server after world load. Reloaded into v1.2.0, removed bottler, and v1.3.3 starts fine. When placing bottler in world anywhere besides where it was, no crash. When placed next to other forestry items in its original location, server instantly crashes. I've attached crash report from placing the block in the world next to other forestry items.

[crash.txt](https://github.com/ForestryMC/ForestryMC/files/645024/crash.txt)

**Comment by Nedelosk** [comment]
This bug is not from forestry. This bug is from an other mod that returns null in a method that can't be null.

**Comment by Nedelosk** [comment]
I add a debug message, so we can see which handler causing the bug.

**Comment by msdossys** [comment]
Thanks for the quick response. Could you pass on the name of the other mod and any information I can take to their developers to try to fix this? Thanks!

**Comment by Nedelosk** [comment]
Can you post a new crash report made with the new version of foresty  ?

**Comment by Crowfooted** [comment]
I'm getting this same crash too - is there any way of telling which mod is causing this?

Specifically, this crash happens whenever I try to place water into the Bottler using a bucket. An empty bottler doesn't cause any problems.

**Comment by Nedelosk** [comment]
@theCorvid Crash report ?

**Comment by Crowfooted** [comment]
@Nedelosk Sure thing, [crash report here](http://pastebin.com/xZ9UVHbR).

Worth noting that I have also tried using other versions of Forestry, including the latest version (I can't remember if THIS crash is from the latest version) and the crash happens on all versions that I've tried. I can replicate the crash for you on the latest version of Forestry if you need me to, but I've looked at all the crashes and they are all with the same error.

**Comment by Nedelosk** [comment]
I don't can fix this.
