### ISSUE TITLE
[1.10.2] Forestry[5.2.16.331] Leaves replaced with Limestone Stairs

### ISSUE THREAD

**Issue by TheDarkProdigyX** [ForestryMC/ForestryMC#1540]
Hi, recently just had a crash not sure what caused it, tried to recreate it but to no avail. After trying to recreate the crash, I went about playing and I noticed all the leaves on my forestry trees' have been changed to Limestone Stairs.

Crash Report:
https://gist.github.com/TheDarkProdigyX/e5d934125ba525246d5e9513b2b15695#file-dw20-1-10-forestry-leaves-changed-to-limestone-stairs

**Comment by Nedelosk** [comment]
Same Bug as #1543
