### ISSUE TITLE
Carpenter and Thermionic Fabricator recipes are broken

### ISSUE THREAD

**Issue by Nedelosk** [ForestryMC/ForestryMC#1545]
The ore dictionary support for these machines is broken.
#1364
#1527

**Comment by vaIgarashi** [comment]
Where can I find commit that fixed the issue?

**Comment by Nedelosk** [comment]
@vagola https://github.com/ForestryMC/ForestryMC/commit/00b4b6552c3b8e1b07945556ca02376c5255d67c
