### ISSUE TITLE
Electric Engine via MFSU

### ISSUE THREAD

**Issue by PacDucor** [ForestryMC/ForestryMC#1546]
The wiki page says the engine takes any power voltage yet attempting to connect the engines via glass fiber cables to a MFSU causes them to explode. 
Running on Direwolf20 Pack v1.10.2  Forge v1.2.0

**Comment by Chocohead** [comment]
The electric engine itself is tier 3 (https://github.com/ForestryMC/ForestryMC/blob/mc-1.10/src/main/java/forestry/energy/tiles/TileEngineElectric.java#L65) but the MFSU tier 4. So either that line needs changing or the wiki.

**Comment by Nedelosk** [comment]
[The wiki page](https://forestryforminecraft.info/energy:tin)

**Comment by Nedelosk** [comment]
Can someone please change the wiki page ?

**Comment by mezz** [comment]
I think we should increase the tier of the electric engine to 4, in the wiki picture you can see it is powered by an MFSU.
