### ISSUE TITLE
Orchard does need water blocks?

### ISSUE THREAD

**Issue by nexitem** [ForestryMC/ForestryMC#1549]
I'm not sure if I understand this correctly or I'm facing a bug here, but does orchard need water source blocks in order to function?

I'm trying to make a mixed farm but I don't want it to replant seeds randomly but instead follow a exact design...

|rice|rice|rice|flax|flax|flax|flax|flax|flax|
|rice|rice|rice|flax|flax|flax|flax|flax|flax|
|rice|rice|rice|flax|flax|flax|flax|flax|flax|
|rice|rice|rice|||||||||||||||||||||||flax|flax|flax|
|rice|rice|rice|||||||||||||||||||||||flax|flax|flax|
|rice|rice|rice|||||||||||||||||||||||flax|flax|flax|
|rice|rice|rice|rice|rice|rice|flax|flax|flax|
|rice|rice|rice|rice|rice|rice|flax|flax|flax|
|rice|rice|rice|rice|rice|rice|flax|flax|flax|

Only way this works is if I place source water blocks, without them the ground will turn into sand.
btw both seeds are from actually additions. Forestry version 1.10.2-5.2.16.335

**Comment by EnderiumSmith** [comment]
you should place water blocks anyway. crops grow faster if hydrated.

**Comment by mezz** [comment]
I think what you're seeing is normal.
Humus does not need hydration, but it turns to sand after a while.
