### ISSUE TITLE
Alveary not working on server

### ISSUE THREAD

**Issue by ProgrammedSoul** [ForestryMC/ForestryMC#1550]
I'm running forestry 1.10.2-5.2.16.346, when I place a alveary in signal player client it works fine. But if I placing it on a server instead, the server and the client will send me message about the problems of the multi-block both. After the multi-block is completed, the texture changed and the client no longer posting messages, but server is still telling me the mult-block is not big enough.
![image](https://cloud.githubusercontent.com/assets/4493654/21469343/96e3a718-ca13-11e6-891e-c64c28c31d66.png)

**Comment by ProgrammedSoul** [comment]
The server console shows nothing while right clicking BTW. So not sure what king of report should I post here...

**Comment by danielrossyamitrano** [comment]
Also, I've noticed, the message states that "It must be **at least** 3x3x3 in size", implying that it could be bigger, where actually (at least as far as I understand) it cannot.

**Comment by ProgrammedSoul** [comment]
Well I think this is the message for all their multi-blocks, include the farms. The only size of Alveary is 3x3x3......I think. Also it seems the multi-block will work on server restart, but cannot be formed before restart.

**Comment by Nedelosk** [comment]
Seems like this only occurred in the 1.10.2 of forestry. We no longer maintain this version, so I will close this issue.
