### ISSUE TITLE
[1.10.2, Minor] Hives spawning Impossible flowers 

### ISSUE THREAD

**Issue by Phonavis** [ForestryMC/ForestryMC#1551]
I've noticed that flowers spawned from Hive generation can spawn flowers not native to the biome, for example Alliums in a plains biome.
This is the most Nitpick bug report I've posted in the last few years.

Forestry 5.2.16.331

**Comment by jlbrewer** [comment]
Personally, I tend to consider this a feature rather than a bug.

It makes flowers and therefore dye farmable. Other mods (Botania, Magical Crops, Agricraft) enable this much more efficiently but it's nice to have the option.

**Comment by SandGrainOne** [comment]
It currently gives you a chance to get a flower you haven't found yet yourself. This change would still enable  flower farms. What this does, is giving you controll over what flowers you farm instead of getting random flowers.

**Comment by mezz** [comment]
See this related issue https://github.com/ForestryMC/ForestryMC/issues/1434
I think the solution is to only allow bees to spawn flowers that are the same type as the ones near them.

**Comment by mezz** [comment]
This is fixed in the latest version.
Bees will only spread the flowers that are already within their range.
