### ISSUE TITLE
1.10 Ender Dragon Resurrection

### ISSUE THREAD

**Issue by Proklaus** [ForestryMC/ForestryMC#1552]
Ender Dragon spawns but simply sits in one place
You are also not able to hurt the Ender Dragon, and he is unable to hurt you.

Forestry 5.2.16.330

**Comment by Nedelosk** [comment]
I don't think that that is a forestry bug

**Comment by Proklaus** [comment]
it is 
Resurrect a Ender Dragon withs Phantasmal Bee's
Ender dragon has noAI
In MC Vanilla 1.9 the summon command changed

**Comment by Nedelosk** [comment]
Thanks for the report!

**Comment by NosajDraw** [comment]
Can confirm this bug still exists in 1.12
