### ISSUE TITLE
Infinite Creosote Oil [Railcraft]

### ISSUE THREAD

**Issue by 6TELOIV** [ForestryMC/ForestryMC#1553]
I'm running the direwolf20 pack, and if you put a bottle of creosote oil into the bottler to take liquid out of it, it doesn't take 1000mb of liquid and give an empty bottle, it just keeps taking oil and leaves the full bottle in the slot, filling up the machine with 10000mb of oil. It will do this for 1 or more bottles, however it only will take in one bottle to pull liquid from.

**Comment by Nedelosk** [comment]
Duplicate: #1502
