### ISSUE TITLE
Log Piles Missing Models

### ISSUE THREAD

**Issue by ChloeDawn** [ForestryMC/ForestryMC#1556]
**Mod version:** [5.3.0.1](https://minecraft.curseforge.com/projects/forestry/files/2362481)
**Forge version:** [1.11.2-13.20.0.2201](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.11.2-13.20.0.2201/forge-1.11.2-13.20.0.2201-changelog.txt)

**Log piles are missing unique model textures on their itemstacks, and render transparent in-world.**

![Screenshot of log piles in JEI](https://i.imgur.com/yI93Skv.png)
![In-world screenshot of log piles](https://i.imgur.com/WXpltJw.png)

**Comment by madcyph3r** [comment]
I have the same problem like the op.
Forestry:  forestry_1.11.2-5.3.0.32
Minecraft: 1.11.2
Forge: 1.11.2-13.20.0.2226


For example a teak wood (stock) is transparent.
