### ISSUE TITLE
Worktable + IC2's Forge Hammer bug 1.10.2

### ISSUE THREAD

**Issue by LunyashaRu** [ForestryMC/ForestryMC#1558]
Forge Hammer does not lose durability when using in Worktable.
Forestry 1.10.2 build 347
Industrial Craft 2 build 140

Video Example - https://www.youtube.com/watch?v=yJG079Ak3L4

**Comment by SalmonDE** [comment]
I'm sorry for asking here, but is there a workaround like removing the worktable somehow (In a config file of course)? I'm desperately looking for a solution.

**Comment by CovertJaguar** [comment]
CraftTweaker

**Comment by davqvist** [comment]
Yeah, I'm having the same issue as well. Every tool that on craft would lose durability doesn't take any durability loss.

MC 1.10.2
Forestry 5.2.17.376

**Comment by CovertJaguar** [comment]
It should probably ban container items if it can't support them properly.

**Comment by mezz** [comment]
This has been fixed in 1.10 and above.
