### ISSUE TITLE
[1.11.2] JEI not showing recipes for Carpenter

### ISSUE THREAD

**Issue by ELFrhymer** [ForestryMC/ForestryMC#1562]
I have JEI 4.2.0.210 and Forestry 5.3.0.11 and cannot view recipes related to Carpenter.

What am I doing wrong?

**Comment by mezz** [comment]
Thanks for the report!
Looks like a bug.

**Comment by ELFrhymer** [comment]
Sorry to say that, but it doesn't seem to be fixed in build 13... Is it?

**Comment by mezz** [comment]
It should be fixed in build 13.
How are you looking up recipes? Try looking at the carpenter item and looking at its uses.

**Comment by ELFrhymer** [comment]
Well, I don't know what's wrong.

forestry_1.11.2-5.3.0.13
jei_1.11.2-4.2.2.220
forge-1.11-13.19.1.2189-universal

Recipes not showing, usages for Carpenter do not open...
Any ideas how can I help you with it?
Is the forge too old?

2017-01-08 18:39 GMT+07:00 James Mitchell <notifications@github.com>:

**Comment by mezz** [comment]
Try with forestry_1.11.2-5.3.0.17

**Comment by ELFrhymer** [comment]
You nailed it! Now it works like a charm. Thanks a lot!

2017-01-09 6:39 GMT+07:00 James Mitchell <notifications@github.com>:

**Comment by mezz** [comment]
Cool, glad that works.
