### ISSUE TITLE
[1.11.2-5.3.0.14] Crash when adding fertilizer to farm 

### ISSUE THREAD

**Issue by alexhgian** [ForestryMC/ForestryMC#1565]
A crash occurs when adding fertilizer to a 3x4x3 multifarm with 1 gearbox and powered.

http://pastebin.com/qf6qGtJz

**Comment by alexhgian** [comment]
Update: It seems to crash if there is no farm hatch

**Comment by alexhgian** [comment]
Update: I also tried it with the farm hatch. I thought it was fixed, but it crash a few seconds later.

**Comment by mezz** [comment]
Thanks for the report!
Confirmed.
