### ISSUE TITLE
.349 Breaks Schematica

### ISSUE THREAD

**Issue by Utildayael** [ForestryMC/ForestryMC#1566]
Hello! Cross posting this from the Schematica issues list. We updated our server pack last night and in it, Forestry to .349 release. After that, Schematica stopped working. Please refer to this issue which contains the errors in the log as well.

https://github.com/Lunatrius/Schematica/issues/195

MC 1.10.2
forestry_1.10.2-5.2.17.349.jar

@Lunatrius is looking at it from his end as well but wanted to make you aware. The previous version we had loaded, 5.2.16.348, worked fine so it was something that changed between 348 and 349.

Cheers!

**Comment by mezz** [comment]
Thanks for the report!
I'm pushing a fix for 1.11 then back-porting it to 1.10

**Comment by mezz** [comment]
The new builds should be up soon. Please let me know if you still see a problem with them.

**Comment by Utildayael** [comment]
Thank you sir for the quick reply!
