### ISSUE TITLE
Can't See Capsule/Can Recipes

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#1569]
using game 1.11.2 forge 2216 and forestry 5.3.0.26
i just wanted to build an apiary. for it i need Impregnated Casing, but for get that, we need carpenter and seed oil. i built a squeezer, and i made Can from tin, and placed fruit in it, it started progress. okay i got seed oil but i can not get it from the squeezer. i placed Can in it, but nothing happens. can not place bucket... is it my problem? i think it is a bug

**Comment by Nedelosk** [comment]
Thanks for the report!

**Comment by ghost** [comment]
no problem. ill be happy with the next release that contains fix of it. thanks.

**Comment by GanthorPrime** [comment]
same problem here, all the machines that generate / store fluids (squeezer, fermenter, bottler..) are not filling cans nor capsules. however, you still can right click using a empty bucket to get the fluids.

this is happening to me whit all the combinations of 1.11.2 and forge version i tested so far.  is working in 1.8.x
