### ISSUE TITLE
All trees have apple oak leaves

### ISSUE THREAD

**Issue by foxygrandpa201020** [ForestryMC/ForestryMC#1572]
i have been playing with forestry recently and am just now getting into the tree breeding,but ran into a weird sight when all forestry trees that i grew only had apple oak trees.
after i saw that i figured that was my fault because the trees i was growing were planted next to oak trees, so i loaded up a new world and spawned in saplings of all sorts EX: Cherry, Giant and Coast Seqoia, Red Spruce and more. Even on a super flat world every tree i spawned only had apple oak leaves.
am i doing something wrong or is this just a bug that needs to be worked on.

any info is appreciated

**Comment by mezz** [comment]
Thanks for the report!
I need some more information about your setup to figure out what might be wrong.
Can you run the game and force a crash by holding F3+C for 10 seconds?
Then upload the crash report to https://gist.github.com and link it here.

**Comment by foxygrandpa201020** [comment]
https://gist.github.com/foxygrandpa201020/c9bffb2fbd2a443f07c87e39751186c2

**Comment by mezz** [comment]
Confirmed, and fixed in the latest version.
