### ISSUE TITLE
butterfly shift stats don't match analyzer stats

### ISSUE THREAD

**Issue by emkeev** [ForestryMC/ForestryMC#1573]
I'm working on butterfly breeding using a combination of forestry, gendustry, and biodiversity spamming. As we know, when a forestry item (bee/butterfly/sapling/serum/caterpillar) is analyzed, it usually displays the summary if you shift+mouseover the item. 

The issue: the shift+mouseover summary does not match the data in the handheld analyzer - specifically, as I've discovered, the humidity tolerance is the attribute that does not match. The analyzer data is the correct data, which makes the process slightly more cumbersome as I have to pop everything in the analyzer constantly. I haven't been able to find a pattern as to which data it's pulling into the summary. 
![2017-01-18_18 17 06](https://cloud.githubusercontent.com/assets/19229099/22116028/2c61618a-de3d-11e6-8b8f-4b41676a3400.png)

(This is the first time I've ever submitted issues regarding minecraft so please pardon if I screwed something up here)

**Comment by mezz** [comment]
Thanks for the report!
What version of Minecraft are you running?
Do bees, trees, and everything else work correctly?

**Comment by emkeev** [comment]
We're running FTB Infinity Lite 1.5.1 for Minecraft 1.10.2. I'd be happy to
supply more info as I uncover it.
