### ISSUE TITLE
[1.10.2] Butterflies crashing server every so often

### ISSUE THREAD

**Issue by drewbit** [ForestryMC/ForestryMC#1574]
Forestry Version: 5.2.17.335
Forge Version: 1.10.2-12.18.3.2185

I'm assuming this has something to do with Biome Bundle as I have that installed, not sure though. Crashes aren't consistent at all either, 2-4 hours between each one.

Log: http://pastebin.com/3gvS41xc

Let me know if you need any more information

**Comment by mezz** [comment]
Thanks for the report!
This is a very standard call to the `BiomeDictionary` by Forestry, I think the issue lies with Biome Bundle or another biome mod. Please try reporting there and link back here. If they have questions or think it may be a Forestry issue, I can respond here.
