### ISSUE TITLE
[Request] Forestry v5.3.0.28 for specifically 1.11.2 works in 1.11 :)

### ISSUE THREAD

**Issue by shortybsd** [ForestryMC/ForestryMC#1575]
No issue just missing information. Forestry 1.11.2-5.3.0.28 **does** work for 1.11 other than 1.11.2 as specified on curseforge for minecraft versions. I am so glad you made it backward compatible as it will be a while to move from 1.11 to 1.11.2. Could you guys update CurseForge to reflect what it does support? Thank you

**Comment by mezz** [comment]
Unfortunately there are some extremely small differences between Minecraft 1.11 and 1.11.2 that will cause Forestry to crash, so it is not actually compatible. I think if you use the 1.11.2 version and look at or collide with an engine or ash pile in 1.11 it should crash.

**Comment by hajtez** [comment]
Unfortunately the version of the mod you have for download is not working with Minecraft 1.11.2 . It crashes when forge wants to open the jar.

**Comment by Nedelosk** [comment]
Is this issue fixed ?

**Comment by shortybsd** [comment]
Yes, it was fixed ages ago. No issue as it was described in my first sentence. It was just missing support information for MC version as you guys only had 1.11 listed and not 1.11.2 as well. :) Back when I posted this it worked great for either version with no issues. Still works great, love you guys!
https://minecraft.curseforge.com/projects/forestry/files
