### ISSUE TITLE
Hive generation spam

### ISSUE THREAD

**Issue by Y0ungSandwich** [ForestryMC/ForestryMC#1577]
Ever since we updated to forestry 5.2.17.360 our server console is spamming:

`[17:45:28] [Server thread/ERROR] [forestry]: tried to generate a hive in an unloaded area.
>`

And we are seeing player disconnects since.

**Comment by Nedelosk** [comment]
I don't think that this message has anything to do with player disconnects. It only says that mc has tried to generate an hive in an unloaded chunk.

**Comment by mezz** [comment]
Thanks for the report!
I haven't seen other reports of this.
Can you upload your server log to https://gist.github.com/ and link it here?

**Comment by Y0ungSandwich** [comment]
Well it does spam the server console constantly,  when it does happen.  So fast that you can't even see anything else lol. It's happening randomly so I'll try to catch it again.

**Comment by Nedelosk** [comment]
@mezz https://github.com/ForestryMC/ForestryMC/blob/mc-1.11/src/main/java/forestry/apiculture/worldgen/HiveDecorator.java#L53-L54 Why +8 ?

**Comment by Nedelosk** [comment]
@mezz https://github.com/ForestryMC/ForestryMC/blob/mc-1.11/src/main/java/forestry/apiculture/worldgen/HiveDecorator.java#L53-L54 Why +8 ?

**Comment by Mcniiby** [comment]
This is happening to me as well and I have a log. 

https://gist.githubusercontent.com/anonymous/6d64e8f47b76b3c5119510b77782b0f3/raw/b11887c6b2c42ba3653785db389b7f9365523dde/Server%2520Log

I don't know if it has anything to do with retrogenning tin into the world, but that seems to be when it started.

**Comment by carif** [comment]
@mezz I am really wondering if there is any progress on this issue, as I'm having the exact same problem (and it is really annoying, just look at the time stamps):

> [22:29:01] [Server thread/ERROR] [forestry/]: tried to generate a hive in an unloaded area.
> [22:29:02] [Server thread/ERROR] [forestry/]: tried to generate a hive in an unloaded area.
> [22:29:02] [Server thread/ERROR] [forestry/]: tried to generate a hive in an unloaded area.
> [22:29:02] [Server thread/ERROR] [forestry/]: tried to generate a hive in an unloaded area.
> [22:29:03] [Server thread/ERROR] [forestry/]: tried to generate a hive in an unloaded area.
> [22:29:03] [Server thread/ERROR] [forestry/]: tried to generate a hive in an unloaded area.
> [22:29:03] [Server thread/ERROR] [forestry/]: tried to generate a hive in an unloaded area.
> [22:29:04] [Server thread/ERROR] [forestry/]: tried to generate a hive in an unloaded area.
> [22:29:04] [Server thread/ERROR] [forestry/]: tried to generate a hive in an unloaded area.
> [22:29:04] [Server thread/ERROR] [forestry/]: tried to generate a hive in an unloaded area.
> [22:29:05] [Server thread/ERROR] [forestry/]: tried to generate a hive in an unloaded area.
> [22:29:05] [Server thread/ERROR] [forestry/]: tried to generate a hive in an unloaded area.
> [22:29:05] [Server thread/ERROR] [forestry/]: tried to generate a hive in an unloaded area.
> [22:29:06] [Server thread/ERROR] [forestry/]: tried to generate a hive in an unloaded area.

Minecraft 1.11.2
Forge Mod Loader version 13.20.1.2454
forestry_1.11.2-5.3.4.165

**Comment by mezz** [comment]
This should be fixed in the next release today, let me know if you still have issues.
