### ISSUE TITLE
[1.7.10] forge: minimum version required is 10.4.13.1556

### ISSUE THREAD

**Issue by Giant3** [ForestryMC/ForestryMC#1580]
I become this error when I start Minecraft, but i use the newest version of forge: 10.13.4build 1558. The log dont generate, I dont no why.
![unbenannt](https://cloud.githubusercontent.com/assets/20421620/22522443/d95b8fcc-e8bb-11e6-80eb-4deb6098475a.jpg)

**Comment by mezz** [comment]
The latest "recommended" version of Forge is 1558, but Forestry requires a version later than that, 1566.
You can download the "latest" version (10.13.4.1614) or show all download at the bottom to pick a version.
https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.7.10.html
