### ISSUE TITLE
Multifarm Not Planting On East Side.

### ISSUE THREAD

**Issue by Frinckles** [ForestryMC/ForestryMC#1585]
It only makes sense, considering the Multifarm is a West End Girl who doesn't like East End Boys, but I'd really like to be working at maximum efficiency! 

If this issue is a dupe, delete please. Thanks for all the work on Forestry, love the mod.

Issue appears with; 
Forge-1.10.2-12.18.3.2185-universal.jar
forestry_1.10.2-5.2.17.362

        No logs to post.

I'll also reference the ancient issue of #341

**Comment by EnderiumSmith** [comment]
is the foundation intact? if you break one block it will stop at it.

**Comment by Nedelosk** [comment]
Closed because of no response and I can't replicate the bug
