### ISSUE TITLE
[1.10.2] Strange Crash

### ISSUE THREAD

**Issue by DestinyPlayer** [ForestryMC/ForestryMC#1587]
https://gist.github.com/DestinyPlayer/042109e9c5d0003e31ad89399405677d

I honestly have no idea what's happening, but a friend of mine is having this crash. I'm not. My friend does, even though we have the exact same packs and Java versions. I'm not even sure if Forestry is the cause, but this is the ONLY clue I have.

**Comment by mezz** [comment]
Thanks for the report!
Try updating Forestry to the latest version, I think it should fix the problem.

**Comment by DestinyPlayer** [comment]
Turns out it was a horribly confusing Waila bug. As in, "Crashes Java for no bloody reason and leaves no proper crash log" kinda confusing. Sorry for bothering you. Still no idea why it works perfectly for me but bugs out to death for him...

**Comment by mezz** [comment]
Hm okay. Make sure the launcher is set to use the right java version. You can have multiple java versions installed, and the launcher may not be using the latest one.
