### ISSUE TITLE
Crash with BetterQuesting

### ISSUE THREAD

**Issue by vidaj** [ForestryMC/ForestryMC#1589]
Forestry version: forestry_1.10.2-5.2.17.362

What I did: Added retrieval quest in Better Questing for a Forestry princess. Game crashed.

Crashlog: https://gist.github.com/vidaj/e4291ddcce6c3eea3ff66dc7672b22b6

**Comment by mezz** [comment]
Thanks for the report!
Please post the full crash log, not just the stack trace.

**Comment by vidaj** [comment]
Sorry about that. I have updated the gist.

**Comment by mezz** [comment]
It looks to me like the princess has an invalid genome. 
Can you show me how you created it?
There is genome validation in Forestry but it seems to have missed this particular bee somehow.

**Comment by SPMoo66** [comment]
It looks like I've got the same thing going on over here.
https://github.com/Funwayguy/BetterQuesting/issues/176
Better Questing allows you to delete NBT for task/reward items and it looks like that's the crash.

**Comment by Terpo** [comment]
I think my crash is related to this one. 
Forge: 13.20.0.2230 for Minecraft 1.11.2
Forestry: 1.11.2-5.3.3.75
https://gist.github.com/Terpo/9acfab93b5bff628c32b9d006ad39a09

I'm using HardcoreQuestingMode and added a consume task for saplings --> oreDict hand in. While iterating through the saplings it crashes always at the same point.

**Comment by mezz** [comment]
This should no longer be an issue, Forestry will set saplings and bees that have no NBT to look their default versions (like a Forest bee).
For full support of matching genetic items, you will need to use an addon like HQM's [BeeSpecific addon](https://github.com/Vexatos/BeeSpecific). I don't think BetterQuesting has an addon like that yet.
