### ISSUE TITLE
Forestry mod causing game to crash 1.11.2

### ISSUE THREAD

**Issue by Liamvanvelzen** [ForestryMC/ForestryMC#1591]
I'm on the latest launcher, with the latest forge and the latest versions of all the mods I use: Battle towers, Better achievements, Biomes o plenty, Optifine, vein miner, xaeros minimap, and of course forestry.

However, when I install forestry the launcher gets to model manager 3/5 and then crashes giving this error: [Gist](https://gist.github.com/Liamvanvelzen/c95d9bcfa74996393a09428fc8cbf5b1.js)

It runs fine without forestry, and I have allocated 6gb of ram, the latest java for 64 bit and the latest graphics drivers, and still no success.

Help me please?

**Comment by mezz** [comment]
Please try with the latest version of Forestry, yours is over a month old.
https://minecraft.curseforge.com/projects/forestry/files?filter-game-version=2020709689%3A6452&filter-status=1

**Comment by Liamvanvelzen** [comment]
I downloaded and installed that and I get the same "The game crashed whilst initializing game
Error: java.lang.ClassCastException: java.util.HashSet cannot be cast to java.util.Map" error message.
Here is the new latest log file [Gist](https://gist.github.com/Liamvanvelzen/cc43ec1e6f5e064bbc84d150f35ecc79.js)

**Comment by mezz** [comment]
This log still shows that you are using `forestry{5.3.0.9} [Forestry] (forestry_1.11.2-5.3.0.9.jar) ` which is pretty outdated.
Please make sure you have updated the right mods folder.

**Comment by Liamvanvelzen** [comment]
Okay I managed to find the latest version and now it works :D
Thank you :)
