### ISSUE TITLE
[1.11.2-5.3.1.34] Carpenter recipe for Portable Analyzer asks for Magenta Stained Glass Pane

### ISSUE THREAD

**Issue by leagris** [ForestryMC/ForestryMC#1592]
![image](https://cloud.githubusercontent.com/assets/1111474/22844671/b1b9b07c-efdf-11e6-8f59-dcdb9e93697c.png)

**Comment by leagris** [comment]
Recipe also asks for `techreborn:ingot@13` instead of Ore-Dictionary Name `ore:ingotTin`

**Comment by leagris** [comment]
Sorry, I found the cause is a bad interaction with [Auto Ore Dictionary Converter](http://www.curseforge.com/projects/auto-ore-dictionary-converter/)
See issue opened for this mod: https://github.com/MattDahEpic/AutoOreDictConvert/issues/5

**Comment by leagris** [comment]
@MattDahEpic can't find a fault on his mod https://github.com/MattDahEpic/AutoOreDictConvert/issues/5#issuecomment-279100574
@mezz if you can help a bit dig into it, maybe a solution could be found on either side.
OreDictionary unification from AODC is very convenient to avoid filling your inventories from  different flavors of the same oreDict items.

**Comment by mezz** [comment]
There are still a lot of bugs in 1.11.2, thanks for testing it out and reporting!
This is most likely a Forestry issue, there have been a lot of issues with the OreDictionary support in the carpenter lately.
We are also working on porting Binnie's mods right now which is a massive project, so it may take some time to fix this issue.
