### ISSUE TITLE
No Crafing Recipy for Royal Jelly in forestry_1.10.2-5.2.17.362.jar

### ISSUE THREAD

**Issue by De1mo** [ForestryMC/ForestryMC#1593]
Thank you for reporting!

For issues:
 * Try the latest version, it may have fixed the issue already.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

**Comment by MauveCloud** [comment]
Your bug description seems to be the default placeholder, but based on the summary, I'm not sure it's even a bug - royal jelly is normally produced by certain bees, rather than in the crafting table.  JEI Bees or Just Enough Forestry Bees (JEFB) can show you which bees produce it.

**Comment by De1mo** [comment]
Sorry first time using this :smile: 
I have JEI installed, but if i click on the bees that produce the Royal Jelly they don't open JEI that i can see what they drop.  So was more wondering if i need a Library or something else to be installed with Forestry to see that

**Comment by MauveCloud** [comment]
Like I said, JEI Bees or JEFB.  They're add-on mods to JEI; they don't come with JEI automatically.

**Comment by De1mo** [comment]
Thx for the input,never knew of that mod
