### ISSUE TITLE
[1.10.2] EnderLillySeeds not accept for farm

### ISSUE THREAD

**Issue by vvs1978** [ForestryMC/ForestryMC#1594]
Since new extrautils2  ver 1.20 changed Ender Lilly name from EnderLilly to enderlilly - forestry in minecraft 1.10.2 no more accept ender lilly seeds for farm.

**Comment by Waisse** [comment]
Can confirm, ender electron tube has <no effect> and can't be soldered.

**Comment by gradytrain** [comment]
Having a similar issue since my server updated to DW20 vers. 1.8.1 that I am unsure is related. My intricate circuit board that was running my Automatic Ender Lily multifarm was switched back to an arboretum and I can confirm that I can no longer see Ender Electron Tubes in JEI

**Comment by Obbi89** [comment]
This needs another fix.
In current ex2 versions for 1.10.2 the name changed to lowercase. This is missing in the mc-1.10 branch but is included in the fix in the mc-1.11 branch:
see:
https://github.com/ForestryMC/ForestryMC/commit/032d706fc431287cf44286d322bd2bb200481c16
and:
https://github.com/ForestryMC/ForestryMC/commit/e8366209546df55969926c49b7374095f2773d00

changing to lowercase extrautilities2 should fix the isModLoaded(ExU) returning false.

Edit:
Btw. same issue exists with Natura, they changed casing of the modid to lowercase, too.

**Comment by Nedelosk** [comment]
@Obbi89 Can you please open a new issue ?

**Comment by Obbi89** [comment]
Yes I'll do gimme sec
