### ISSUE TITLE
[1.10.2] Probable forestry bug crashes Railcraft locomotives

### ISSUE THREAD

**Issue by zTorden** [ForestryMC/ForestryMC#1595]
See more info here:
https://github.com/CovertJaguar/Railcraft/issues/1080

**Comment by mezz** [comment]
Thanks for the report!
I'll fix that property (it's definitely a mistake) and make a new build, let me know if it fixes the issue.

**Comment by zTorden** [comment]
The client doesn't crash  with 364 build where it was crashing every time with earlier version, so the issue is resolved I suppose.
