### ISSUE TITLE
(x-post reddit/ftb) 1.7.10 Modtweaking hives as recipe results

### ISSUE THREAD

**Issue by Nocty201** [ForestryMC/ForestryMC#1597]
Apologies if this is the wrong place to ask...

X-posted (kinda) from here: https://www.reddit.com/r/feedthebeast/comments/5tyvfc/1710_custom_forestry_and_the_inability_to_spawn/

I'm using Modtweaker/Minetweaker to try and set some recipes to allow players to generate their own bee hives (as naturally found) as it seems my custom world generation has broken Forestry's spawning of them - Deep Hives and Nether Hives both are missing, confirmed by an hour of flying around under the world with an XRay mod.

Some beehives are spawnable - A forest hive will be handed to you if you do a  **/give <player> Forestry.beehives:1**

The meadows hive is :2, modest :3, tropical :4, and Ender is :5 - but it's not spawnable. If I go into the End and clone one with Creative pick block, then issue the command **/mt hand** 

It tells me that the id is **Forestry.beehives:5** but attempting to **/give** myself one returns the error of **There is no such item...** , and using the numeric ID of **439:5** does the same.

As a result, I can make some of the bees work but the mod has locked out a lot of them due to how I generate the world - I'm using the Custom Ore Generation mod which completely reworks resource distribution to have large sized deposits appearing infrequently.

As all the queens/drones/princesses use copious amounts of tags (which are a pain, but seem to be at least partly supported), doing a recipe with those isn't particularly nice and so I'm hoping to keep it to hives (which also adds the random elements like Pristine/Ignoble upon breaking).

I'd love some guidance as to how best to proceed. I could invest a lot of time writing and debugging the Minetweaker scripts, but if someone knows how to force the game to allow me to spawn the rare hives so players can craft them - that would rock.

Thanks!

**Comment by MauveCloud** [comment]
I haven't figured out how to force spawning, but I figured out the proper /give syntax for the Ender hive:
`/give @p Forestry:beehives 1 5`
I think Ender Bees can also be obtained from villager trades (might only be the drones, though).

Deep Hives and Nether Hives are not part of the regular Forestry mod - see https://github.com/ForestryMC/ForestryMC/blob/4.2/src/main/java/forestry/apiculture/worldgen/HiveDescription.java

http://ftb.gamepedia.com/Hive_Bee lists Deep Hives as coming from Magic Bees and Nether Hives as coming from Extra Bees (part of Binnie's Mods)

**Comment by Nocty201** [comment]
Aah, my mistake on the non-forestry ones. Will work on that with the appropriate mods.

I can force spawn some hives (such as the Meadows with a meta of :1) but attempting to spawn one by changing the (previously working) command from :1 to :5 causes it to fail.

**Comment by MauveCloud** [comment]
I strongly suspect you are mistaken in your claim that the command you listed initially worked properly, because 1. the syntax is wrong (you need a player name or target selector for the give command - see http://minecraft.gamepedia.com/Commands#give ), 2. the item internal name is wrong (it uses a colon between Forestry and beehives, not a period), and 3. it requires the metadata as a separate parameter, not separated a colon.  When I tried the command you listed for the Forest hive, first I got "/give <player> <item> [amount] [data] [dataTag]" (telling me the syntax), then when I added `@p`, I got "There is no such item with ID Forestry.beehives:1"

However, if you mean that `/give @p Forestry:beehives 1 1` works, but `/give @p Forestry:beehives 1 5` does not, that is very strange.  For me, even `/give @p Forestry:beehives 1 9` (metadata beyond the normal set of hives) gives me an item, only it has the pink and black "missing texture" and the name is "tile.for.beehives.9.name"

**Comment by Nocty201** [comment]
You are indeed correct about the command. I had shortcut the full command because I was typing it from memory, not copy pasting. My apologies for the confusion.

I did redo my experimentation as you did, and it does indeed work with the metadata specified separately. Even to the same missing texture hives. I don't know why Ender hives don't show in NEI though, but at this point and just happy I can get the info and script them - Thank you.

For completeness sake (and in case anyone else comes looking like I have in the future), the Magic Bees hive blocks are named **MagicBees:hive** and the hives are (from meta 0 through 5) : Curious, Unusual, Resonating, _Deep_, _Infernal_, _Oblivion_. The later three (in italics) also do not show in NEI.

Standard Forestry ones are (from Meta 1 through 8): Forest, Meadows, Modest, Tropical, _Ender_, Wintry, Marshy, _Swarm_. Ender and Swarm do not appear in NEI. I vaguely remember a water hive, but that may have been as far back as 1.4.7; and it's not referenced in the java code linked above.

Thank you again for your help in showing me where I was in error!

**Comment by mezz** [comment]
Water hive, rocky hive, and others are from Binnie's Extra Bees mod.

**Comment by Nocty201** [comment]
And that explains that - I don't have Extra Bees installed.

You can tell it's been quite some time since I used Bees for much >.>

Thanks!
