### ISSUE TITLE
Lost capsule function with creosote.

### ISSUE THREAD

**Issue by DEX47** [ForestryMC/ForestryMC#1599]
1.7.10 issue with my modpack. I have lost recipe functionality between creosote and capsules.  It's a long list of mods running. If anyone knows a shortcut fix adding in the crafting with the bottler or even coke oven from railcraft using MineTweaker that would be great.

1.7.10-ExpandedIndustry-15.26.1a.jar
1.7.10_AM2-1.4.0.009.jar
AdvancedRocketry-1.7.10-1.0.4.jar
adventurebackpack-1.7.10-0.8c.jar
AgriCraft-1.7.10-1.5.0.jar
ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar
AnimationAPI-1.7.10-1.2.4.jar
arcane_engineering-0.2.7.jar
ATG-1.7.10-0.12.0.jar
Automagy-1.7.10-0.28.2.jar
autooredictconv-1.7.10-1.3.1.jar
BetterBoat-1.7.10-1.1.0.jar
BetterFoliage-MC1.7.10-2.0.14.jar
BiblioCraft[v1.11.5][MC1.7.10].jar
BiblioWoods[BiomesOPlenty][v1.9].jar
BigDoors-1.7.10-1.1.0.jar
BigReactors-0.4.3A.jar
BiomesOPlenty-1.7.10-2.1.0.1390-universal.jar
Bookshelf-1.7.10-1.0.4.187.jar
Botania r1.8-249.jar
Carpenter's Blocks v3.3.8.1 - MC 1.7.10.jar
catwalks-2.0.4.jar
Chisel-2.9.5.11.jar
ClockHUD-1.7.10-1.1.jar
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
CoFHCore-[1.7.10]3.1.3-327.jar
CollectiveFramework-1.0.0-132.jar
compactmachines-1.7.10-1.21.jar
ComputerCraft1.75.jar
ComputerCraftEdu1.74.jar
ContentTweaker-1.0.5.jar
CraftTweaker-1.7.10-3.0.11.jar
CrayTokensLite-v0.82-MC1.7.10.jar
CustomNPCs_1.7.10d(21feb16).jar
Decocraft-2.3.6.1_1.7.10.jar
deepresonance-1.1.4.jar
DynamicSurroundings-1.7.10-1.0.5.6.jar
eldritch-empires-091.jar
ElecCore-1.7.10-1.4.294.jar
ElsewhereBorder-1.7.10-1.0.0-5-universal.jar
Enchiridion 2-1.7.10-2.0.2a.jar
EnviroMine-1.3.124.jar
Exotic Birds 1.7.10 - 1.0.3b.jar
ExtraTiC-1.7.10-1.4.6.jar
extrautilities-1.2.12.jar
fastcraft-1.23.jar
FastLeafDecay-1.7.10-1.4.jar
Fireplace-Mod-1.7.10.jar
Fluxed-Core-MC1710-1.0.9.jar
Forbidden Magic-1.7.10-0.575.jar
forestry_1.7.10-4.2.16.64.jar
gadomancy-1.7.10-1.0.7.3.jar
glass_shards_mc1.7.10-1.5.2.jar
GraveStone-2.16.1.jar
Grim3212-Core-1.7.10.jar
GrimoireOfGaia3-1.7.10-1.2.7.jar
growthcraft-1.7.10-2.5.2-complete.jar
HardcoreEnderExpansion  MC-1.7.10  v1.8.6.jar
hopperductmod-1.7.10-1.3.2.jar
ice_shards_mc1.7.10-1.3.jar
ImmersiveEngineering-0.7.7.jar
immibis-core-59.1.4.jar
InventoryTweaks-1.59-dev-152.jar
journeymap-1.7.10-5.1.4p1-fairplay.jar
KoreSample-1.7.10-1.3.2.jar
LavaMonsters-1.7.10-2.2.1.jar
LibVulpes-1.7.10-0.1.12-universal.jar
malisiscore-1.7.10-0.14.3.jar
malisisdoors-1.7.10-1.13.2.jar
Mantle-1.7.10-0.3.2b.jar
Mariculture-Deluxe-1.7.10-1.2.4.2a.jar
mcjtylib-1.8.1.jar
mdecore-1.0.jar
Metallurgy-1.7.10-4.0.6.80.jar
MetallurgyCore-1.7.10-4.0.4.18.jar
MineFactoryReloaded-[1.7.10]2.8.1-174.jar
MineTweakerRecipeMaker-1.7.10-1.1.0.11.jar
Mo' Zombies 2.1.1.jar
modlist.txt
ModTweaker2-0.9.6.jar
ModularPowersuits-0.11.1.109.jar
MoreEnchantments-1.7.10-1.3.2.1.jar
Morpheus-1.7.10-1.6.10.jar
MyEssentials-Core-1.7.10-1.18r-universal.jar
MyPermissions-1.7.10-66-dev.jar
MyTown2-1.7.10-0.5.0b.jar
NomadicTents[1.7.10]-1.11.jar
NotEnoughItems-1.7.10-1.0.5.120-universal.jar
Numina-0.4.1.104.jar
OpenBlocks-1.7.10-1.5.1.jar
OpenModsLib-1.7.10-0.9.1.jar
OpenModularTurrets-1.7.10-2.2.9-232.jar
Pam's Clay Spawn 1.7.10b.jar
Pam's Harvest the Nether 1.7.10a.jar
Pam's HarvestCraft 1.7.10Lb.jar
PChan3Mods-0.7(1.7.10).jar
Peripherals++-1.3.6.jar
PPP
Practical-Logistics-1.7.10-0.2.4.jar
ProjectRed-1.7.10-4.7.0pre12.95-Base.jar
ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar
ProjectRed-1.7.10-4.7.0pre12.95-World.jar
ProjectZulu-1.7.10-1.4c2.jar
PvPTime-1.0.6.jar
Railcraft_1.7.10-9.12.2.0.jar
RefinedRelocation-mc1.7.10-1.1.28.jar
reptilemod-1.7.10-2.5.6-10.jar
rftools-4.23.jar
roguelike-1.7.10-1.5.0b.jar
RunicDungeons-1.1.7b.jar
ScottsTweaks-1.7.10-1.3.1.jar
SGCraft-1.11.3-mc1.7.10.jar
SonarCore-1.7.10-1.1.3.jar
SpecialMobs-1.7.10-3.2.2.jar
StorageDrawers-1.7.10-1.10.8.jar
StorageDrawers-BiomesOPlenty-1.7.10-1.1.1.jar
Tainted-Magic-r7.6.jar
TConstruct-1.7.10-1.8.8.jar
Thaumcraft-1.7.10-4.2.3.5.jar
ThaumcraftMobAspects-1.7.2-2A.jar
Thaumic-Dyes-[1.7.10] 1.5.1-0.jar
ThaumicExploration-1.7.10-1.1-53.jar
thaumichorizons-1.7.10-1.1.9.jar
ThermalDynamics-[1.7.10]1.2.0-171.jar
ThermalExpansion-[1.7.10]4.1.4-247.jar
ThermalFoundation-[1.7.10]1.2.5-115.jar
TravellersGear-1.7.10-1.16.6.jar
tubestuff-59.0.4.jar
twilightforest-1.7.10-2.3.7.jar
UBCOres-1.7.10-0.2.9.4.jar
UndergroundBiomesConstructs-1.7.2-0.7.jar
Waila-1.5.10_1.7.10.jar
WailaHarvestability-mc1.7.10-1.1.6.jar
Waystones-mc1.7.10-1.0.4.jar
Wild-Caves-Mod-1.7.10.jar
witchery-1.7.10-0.24.1.jar
WitchingGadgets-1.7.10-1.1.10.jar
wolfarmor-1.3.0.1.jar
worldedit-forge-mc1.7.10-6.1.1-dist.jar
WR-CBE-1.7.10-1.4.1.9-universal.jar
[1.7.10]StartingInventory-universal-1.7.10.r03.jar

**Comment by CovertJaguar** [comment]
Probably my fault, more than Forestry.

**Comment by Nedelosk** [comment]
I don't think we will make any changes on the 1.7.10 version of forestry, so I close this.
