### ISSUE TITLE
[1.11.2-5.3.1.37] strange conflict with malisisdoors

### ISSUE THREAD

**Issue by kreezxil** [ForestryMC/ForestryMC#1601]
With only the 3 mods

Forestry 1.11.20-5.3.1.37
Malisiscore 1.11.2-5.1.1
Malisisdoors 1.11.2-6.1.0

All 

the doors provided by Malisis Doors show the attached texture.

Remove Forestry and the doors render properly.

![2017-02-17_15 08 09](https://cloud.githubusercontent.com/assets/3880072/23083473/762f7d54-f523-11e6-9418-66fb9616744a.png)

fml-client-latest.log: https://gist.github.com/kreezxil/a817477852aaf0107d4b0146aade6b3a

**Comment by mezz** [comment]
Thanks for the report!
I don't really know why that could happen.
I think @Ordinastie or @Nedelosk may have a better idea of what's going.

**Comment by Ordinastie** [comment]
I'd say it's probably my fault, but the annoying part is I can't replicate the issue in dev... So, not sure how to debug that one...

**Comment by Nedelosk** [comment]
I don't think that forestry has anything to do with that.

**Comment by blackviperr** [comment]
omg. THAT'S what that was. that happened to me two weeks ago and i was like wth lol
