### ISSUE TITLE
Strange console information Conflicts

### ISSUE THREAD

**Issue by MrKRONIC** [ForestryMC/ForestryMC#1602]
Any ideas as to what this could be?

18.02 19:40:48 [Server] Server thread/ERROR [forestry]: Received an invalid 'add-backpack-items' request 'forester@integrateddynamics:menril_log:*' from mod 'integrateddynamics'. Please contact the author and report this issue. For non-existent backpack forester.
18.02 19:40:48 [Server] Server thread/ERROR [forestry]: Received an invalid 'add-backpack-items' request 'digger@terraqueous:earth_ore:0' from mod 'terraqueous'. Please contact the author and report this issue. For non-existent backpack digger.
18.02 19:40:48 [Server] Server thread/ERROR [forestry]: Received an invalid 'add-backpack-items' request 'digger@terraqueous:earth_ore:1' from mod 'terraqueous'. Please contact the author and report this issue. For non-existent backpack digger.
18.02 19:40:48 [Server] Server thread/ERROR [forestry]: Received an invalid 'add-backpack-items' request 'builder@terraqueous:earth_ore:3' from mod 'terraqueous'. Please contact the author and report this issue. For non-existent backpack builder.
18.02 19:40:48 [Server] Server thread/ERROR [forestry]: Received an invalid 'add-backpack-items' request 'builder@terraqueous:earth_ore:4' from mod 'terraqueous'. Please contact the author and report this issue. For non-existent backpack builder.
18.02 19:40:48 [Server] Server thread/ERROR [forestry]: Received an invalid 'add-backpack-items' request 'builder@terraqueous:earth_ore:6' from mod 'terraqueous'. Please contact the author and report this issue. For non-existent backpack builder.
18.02 19:40:48 [Server] Server thread/ERROR [forestry]: Received an invalid 'add-backpack-items' request 'builder@terraqueous:earth_ore:7' from mod 'terraqueous'. Please contact the author and report this issue. For non-existent backpack builder.
18.02 19:40:48 [Server] Server thread/ERROR [forestry]: Received an invalid 'add-backpack-items' request 'builder@terraqueous:earth_ore:9' from mod 'terraqueous'. Please contact the author and report this issue. For non-existent backpack builder.
18.02 19:40:48 [Server] Server thread/ERROR [forestry]: Received an invalid 'add-backpack-items' request 'builder@terraqueous:earth_ore:10' from mod 'terraqueous'. Please contact the author and report this issue. For non-existent backpack builder.
18.02 19:40:48 [Server] Server thread/ERROR [forestry]: Received an invalid 'add-backpack-items' request 'builder@terraqueous:earth_ore:12' from mod 'terraqueous'. Please contact the author and report this issue. For non-existent backpack builder.
18.02 19:40:48 [Server] Server thread/ERROR [forestry]: Received an invalid 'add-backpack-items' request 'forester@terraqueous:flowers_single:*' from mod 'terraqueous'. Please contact the author and report this issue. For non-existent backpack forester.
18.02 19:40:48 [Server] Server thread/ERROR [forestry]: Received an invalid 'add-backpack-items' request 'builder@terraqueous:hay:0' from mod 'terraqueous'. Please contact the author and report this issue. For non-existent backpack builder.
18.02 19:40:48 [Server] Server thread/ERROR [forestry]: Received an invalid 'add-backpack-items' request 'builder@terraqueous:hay:1' from mod 'terraqueous'. Please contact the author and report this issue. For non-existent backpack builder.
18.02 19:40:48 [Server] Server thread/ERROR [forestry]: Received an invalid 'add-backpack-items' request 'builder@terraqueous:hay:2' from mod 'terraqueous'. Please contact the author and report this issue. For non-existent backpack builder.
18.02 19:40:48 [Server] Server thread/ERROR [forestry]: Received an invalid 'add-backpack-items' request 'builder@terraqueous:hay:3' from mod 'terraqueous'. Please contact the author and report this issue. For non-existent backpack builder.
18.02 19:40:48 [Server] Server thread/ERROR [forestry]: Received an invalid 'add-backpack-items' request 'builder@terraqueous:hay:4' from mod 'terraqueous'. Please contact the author and report this issue. For non-existent backpack builder.
18.02 19:40:48 [Server] Server thread/ERROR [forestry]: Received an invalid 'add-backpack-items' request 'forester@terraqueous:plants:2' from mod 'terraqueous'. Please contact the author and report this issue. For non-existent backpack forester.
18.02 19:40:48 [Server] Server thread/ERROR [forestry]: Received an invalid 'add-backpack-items' request 'forester@terraqueous:foliage1:*' from mod 'terraqueous'. Please contact the author and report this issue. For non-existent backpack forester.
18.02 19:40:48 [Server] Server thread/ERROR [forestry]: Received an invalid 'add-backpack-items' request 'forester@terraqueous:foliage2:*' from mod 'terraqueous'. Please contact the author and report this issue. For non-existent backpack forester.
18.02 19:40:48 [Server] Server thread/ERROR [forestry]: Received an invalid 'add-backpack-items' request 'forester@terraqueous:foliage3:*' from mod 'terraqueous'. Please contact the author and report this issue. For non-existent backpack forester.

**Comment by Nedelosk** [comment]
This message is made by forestry because integrateddynamics uses the false uids to register her backpack items. https://github.com/CyclopsMC/IntegratedDynamics/issues/154

**Comment by rubensworks** [comment]
The Integrated Dynamics error will be fixed in the next update.

**Comment by MrKRONIC** [comment]
very nice thankyou, forestry seems to be causing issue will a few mods so i wouldnt worry to much, i had to remove it due to the bugs

**Comment by CovertJaguar** [comment]
For what it's worth, this is not a critical error. You can still play just fine, those items just won't end up in backpacks.
