### ISSUE TITLE
[1.11.2-5.3.1.37] Trunk from a tree is transparent

### ISSUE THREAD

**Issue by madcyph3r** [ForestryMC/ForestryMC#1603]
Hello,

every forestry tree has a transparent trunk. It's only the trunk, if i use it as a wood block, i have a texture. Please check this.

Minecraft version: 1.11.2
Forge version: 13.20.0.2232
Forestry version: 5.3.1.37

**Comment by Nedelosk** [comment]
I can't confirm this bug. I can see the trunks.
![2017-02-22_18 19 53](https://cloud.githubusercontent.com/assets/10259214/23223510/889329f8-f92b-11e6-8d04-8ca705290e97.png)

**Comment by liach** [comment]
@madcyph3r Do you have Optifine?

**Comment by madcyph3r** [comment]
I found out the problem. If i use the mod BetterFoliage-MC1.11.2-2.1.3, then the trunks are invisible. For now i removed the mod, Thanks for your help.
