### ISSUE TITLE
[1.11.2-5.3.1.38] Nothing go into backpacks

### ISSUE THREAD

**Issue by Gayanfalor** [ForestryMC/ForestryMC#1606]
When i cut trees and harvest some plants while having forest backpack, item are not going into the backpack but in my inventory, same for the miner backpack

Using forge 2233

**Comment by Nedelosk** [comment]
I can't confirm this bug. @Gayanfalor Maybe you have changed the mode of the backpack to locked. Or your config files are broken.

**Comment by mezz** [comment]
@Gayanfalor try deleting your backpack config files and see if that fixes the issue.

**Comment by Nedelosk** [comment]
@Gayanfalor Is this still a thing ?

**Comment by Gayanfalor** [comment]
Hmm i dont know long time i have played mc and i think there is a lot of forestry update that could possibly solve it.

I just remember sometime it was working , taking thing out of the backpack and throwing it again on the ground and it was going in inv instead of backpack it was strange.
