### ISSUE TITLE
[1.11.2-5.3.1.38] Wrong calculation for stamps in letters

### ISSUE THREAD

**Issue by Terpo** [ForestryMC/ForestryMC#1607]
Seems that the calculation for the stamp cost in letters is broken. Every letter, even if empty (only with title + descr.) costs 19n.

I think the empty inventory slots are calculated as not empty. Was a bit worried if the whole system broke but 19n ++ works fine.

**Comment by mezz** [comment]
Thanks for the report!
This probably has to do with the ItemStack changes in 1.11.
