### ISSUE TITLE
Cant add circuit board to Centrifuge

### ISSUE THREAD

**Issue by kzintiwife** [ForestryMC/ForestryMC#1609]
I had a centrifuge set up and it was working fine. updated forestry and wanted to add another centrifuge. 
I made a circuit board (Blazingx2 and goldenx2) and setup the centrifuge as i had the earlier one. For some reason, it will not accept the circuit board. I even tried it with a basic and blazing.  it will not click on.

**Comment by Nedelosk** [comment]
Fixed in the newest version.
