### ISSUE TITLE
Custom Mob Spawner Crash

### ISSUE THREAD

**Issue by TitusArmillius** [ForestryMC/ForestryMC#1613]
forestry_1.10.2-5.2.17.368

http://pastebin.com/VHPbQCpB

This crash only occurs in the BOP bayou biome so far, might occur in any swamp-style biome. 

Note that marshy hives have spawned properly in other biomes.

**Comment by Nedelosk** [comment]
Thanks for the report!
But this crash is not caused by forestry. This crash is caused by CustomSpawner.
