### ISSUE TITLE
Graphics Glitches on machines

### ISSUE THREAD

**Issue by Lethann** [ForestryMC/ForestryMC#1614]
--Using--
Modpack: Direwolf20 1.10 v1.6.2
Forestry 5.2.17.366
Graphics Card: NVidia GeForce GTX 745

The various machines that come with forestry all have graphics tearing on their faces. Confirmed with: Carpenter, Bottler, Squeezer, Centrifuge.  See attached GIF. 
![forestryglitch](https://cloud.githubusercontent.com/assets/25929754/23669143/cb42b604-0328-11e7-9671-3f631ededcd9.gif)

**Comment by mezz** [comment]
Thanks for the report!
This is an Optifine issue, but it should be worked around in the latest version of Forestry:
https://github.com/ForestryMC/ForestryMC/pull/1605

Please make sure your really have the 5.2.17 version of Forestry

**Comment by Lethann** [comment]
Right after I posted this the Direpack upgraded to 1.7 and this is fixed. However the "liquid" block is showing on the front of the machines that have it. 

![forestryglitch2](https://cloud.githubusercontent.com/assets/25929754/23876793/1854fffe-080d-11e7-999f-be0e8b924911.gif)

Forestry 5.2.17.368

Oh and just to let you know I don't have Optifine installed as it's not apart of the default Direwolf20 pack. Am using an nVidia card though.

**Comment by mezz** [comment]
Thanks for the report.

@MatthiasMann there may still be an issue with the Forestry machine overlays, do you know what this might be?

**Comment by MatthiasMann** [comment]
I think it is lighting related - maybe some surface normals are wrong?

**Comment by MrNinja93** [comment]
1.11.2 here also getting the same Z-fighting issue in 1.11.2-5.3.2.58.

I've noticed it only happens if the front/back of the machine if it faces East/West, so far never happened when facing South/North in my testing. (might assist in tracking down the root of the issue)

**Comment by falkreon** [comment]
What's probably happening, for the most part, is that cutout-mipped is no longer a default setting. I'm looking at files like centrifuge_base.png with holes cut out, and that's going to turn out a really dark gray in the rendered block, because that's what transparent pixels get flipped to now. Rendering an interface panel on top of that is *probably* what's zfighting. I'll clone and see if the trivial fix (overriding getBlockLayer in the affected blocks) works.

**Comment by falkreon** [comment]
Well, I'm finding out something you guys probably already know, which is this is a hell of a bug to try and repro in a controlled environment.

* Easiest to reproduce by holding a squeezer or a carpenter in your hand and looking at the model in-hand
* Extremely location sensitive. You could be seeing the fragments struggling for air against the z-buffer, then move 30 meters and they'll be fine.
* Locations are repeatable; if you find a location where z-fighting happens with a machine in your hand, it'll still fight, even if you leave the area, restart the client, and go to the location again.
* Placing a machine down in an area where z-fighting occurs in your hand will *not* cause the machine to z-fight on the ground. The placed-in-world problem areas are in different locations, and as such are really hard to find on purpose.

I still need to check consistency from one map to another - if it's floating point roundoff we might be able to repro just by placing a machine at exact coordinates on any map. That'd be a huge help. I'll keep at this.
