### ISSUE TITLE
[1.11.2]Creating water capsule from nothing with cooking for blockhead sink

### ISSUE THREAD

**Issue by Gayanfalor** [ForestryMC/ForestryMC#1615]
Hello,

I've seen this bug when wanting to fill empy wax capsule with water. Look at the video to see its creating a filled water capsule without using my empty ones :  https://drive.google.com/open?id=0B9iNaLFrsdUpNE5WVVdRbEFzaTg

Forestry version 5.3.2.50
forge 2252
Mc 1.11.2  playing on a server

I'll refer this issues too in the cooking for blockhead mod too becasue i dont know if its from forestry or CFBH

**Comment by BlayTheNinth** [comment]
Issue is on my side.

**Comment by Gayanfalor** [comment]
Alright :p, i have tested with only  1 capsule its not doing it, its just doing it when you have more than one
