### ISSUE TITLE
[1.10.2] Forestry Engine causing crash when loaded.

### ISSUE THREAD

**Issue by Yamorii** [ForestryMC/ForestryMC#1618]
Running a server with All The Mods: Expert
When the chunk containing the Engine is loaded it crashes the server.

[crash-2017-03-09_15.23.23-server.txt](https://github.com/ForestryMC/ForestryMC/files/831466/crash-2017-03-09_15.23.23-server.txt)
Thank you for reporting!

For issues:
 * Try the latest version, it may have fixed the issue already.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

**Comment by OrdinatorStouff** [comment]
Further detail this *MIGHT* be related to ATMRockhounding as well since it seems to be repeatable by placing a rockhounding machine with a coil in it, a forestry engine next to that rockhounding machine, then removing the coil from the rockhounding machine.
