### ISSUE TITLE
Carpentry crash

### ISSUE THREAD

**Issue by Alannahrose** [ForestryMC/ForestryMC#1619]
Hi, i'm using a 1.7.10 custom modpack, with one of the mods i am starting out in is Forestry. I built my first Carpenter, and when i tried using it, i crashed. Any idea how to fix this and whats going wrong?

[crash-2017-03-09_14.57.11-client.txt](https://github.com/ForestryMC/ForestryMC/files/832439/crash-2017-03-09_14.57.11-client.txt)

**Comment by Nedelosk** [comment]
I don't think we will make any changes on the 1.7.10 version of forestry, so I close this.
