### ISSUE TITLE
un-pollinated leaves should breed with themselves

### ISSUE THREAD

**Issue by EnderiumSmith** [ForestryMC/ForestryMC#1625]
when a leaf block that has not been pollinated drops a sapling the sapling genetics should be generated by breeding that leaf block with itself. this way its easier to get saplings with homozigous traits and allows to shuffle the traits without waiting for the bees to pollinate them. do bees even pollinate identical leaf blocks? as a trade off mutations should not be generated this way so you still have to use bees for new species.

**Comment by mezz** [comment]
That's an interesting idea. We'll have to think about the implications a little bit more before implementing it though.
Bees do not pollinate identical leaves together, mainly to speed up the pollination process by avoiding "wasting" a pollination attempt that has no chance of mutation.
