### ISSUE TITLE
[1.7.10]Can't share machine in offline mode server

### ISSUE THREAD

**Issue by l89669** [ForestryMC/ForestryMC#1626]
Client Forge: 1.7.10-1614
Forestry: latest
Thermal Dynamics: 1.2.0-171
Server: Thermos 1614-58 online-mode: false
The Access section and the chest button just DON'T show up in GUI, there is only Owner information.

**Comment by Nedelosk** [comment]
I don't think we will make any changes on the 1.7.10 version of forestry, so I close this.
