### ISSUE TITLE
Crash on Server

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#1627]
[crash-2017-03-14_19.53.40-server.txt](https://github.com/ForestryMC/ForestryMC/files/842090/crash-2017-03-14_19.53.40-server.txt)
this crash with foamfix 0.6.2 beta 2

**Comment by mezz** [comment]
Thanks for the report!
This might be an issue with Foamfix, please try removing it. 
Link the crash log here if you crash again.

**Comment by ghost** [comment]
oh... it worked. thank you!

**Comment by mezz** [comment]
Please report here: https://github.com/asiekierka/FoamFix/issues
