### ISSUE TITLE
[1.11.2 Minor] Farm Control Block

### ISSUE THREAD

**Issue by FlyingScotsman1** [ForestryMC/ForestryMC#1628]
Have found an issue where in my multifarm will not shut down and continues working fully when a redstone lever is placed and activated on the bottom, any redstone signal will not shut down the farm.

**Comment by FlyingScotsman1** [comment]
done a little bit of further testing and trying to figure out what to do, I found that a redstone signal will stop any managed multifarms from planting any new seeds or saplings but won't stop managed or manual farm from harvesting wood, cactus, etc. I don't know if this is intended behaviour or not but I have read that a redstone signal is meant to shut a farm down completely.

**Comment by Nedelosk** [comment]
The redstone signal only stops the planting of new seeds.
