### ISSUE TITLE
Config Farms

### ISSUE THREAD

**Issue by HypnoPants** [ForestryMC/ForestryMC#1629]
Is there a way to remove the automatic farms and energy production from the forestry mod whilst leaving the rest?

If not, I'd like to make that a suggestion :P

**Comment by mezz** [comment]
Yes, Forestry is modular.
See the config file `config/forestry/plugins.cfg` to disable parts of it.
You want to disable `forestry.factory` and `forestry.farming`.
Disabling plugins is not well tested, so let us know if you run into any weird bugs.

**Comment by HypnoPants** [comment]
okay, thanks :)
