### ISSUE TITLE
[1.11.2] Charcoal pile not assembling / not giving multiblock info

### ISSUE THREAD

**Issue by GanthorPrime** [ForestryMC/ForestryMC#1633]
Right clicking on wood pile block is not giving any info on the charcoal pile multiblock requirements.
Arranging in the piramid shape (tested a 9 x 9 wood pile, loam piramid) do not assemble the multiblock.

tested in forge-1.11.2-13.20.0.2252 and forestry_1.11.2-5.3.2.58

confirmed to be working on 1.10.2 whit forestry_1.10.2-5.2.17.362 for the same shape

**Comment by Nedelosk** [comment]
Thats not a bug. We have made the woodpile multiblock shapeless. Now you only have to cover it with any fireproof block and ignite one of the blocks.

**Comment by GanthorPrime** [comment]
thanks for the info, i will try that

**Comment by Terpo** [comment]
Sry if I ask, but is there anywhere any information how to build the multiblock? I'm trying to create one for the last hour but I had no luck so far.  forestry_1.11.2-5.3.3.90
I may also reference to a reddit link that is from yesterday: https://www.reddit.com/r/feedthebeast/comments/64hx94/forestry_1112_wood_piles/

**Comment by Nedelosk** [comment]
I have simplified the charcoal multiblock in 1.11. Now the multiblock is no longer bound on sizes.
You only have to cover all woodpile blocks with fireproof blocks.
![2017-04-10_21 54 06](https://cloud.githubusercontent.com/assets/10259214/24879901/a1e3e258-1e38-11e7-8f58-4598bc3c67ec.png)

![2017-04-10_21 54 16](https://cloud.githubusercontent.com/assets/10259214/24879899/9e73491a-1e38-11e7-9de1-77567b3845bb.png)

![2017-04-10_21 54 25](https://cloud.githubusercontent.com/assets/10259214/24879898/9a8fa640-1e38-11e7-817c-ffef92a0bb01.png)

 And before you close the structure, you set fire next to one of the woodpile blocks.
![2017-04-10_21 54 27](https://cloud.githubusercontent.com/assets/10259214/24879881/8db7ad5a-1e38-11e7-87e7-2436e87a49a7.png)
Than you set the last block.
![2017-04-10_21 54 39](https://cloud.githubusercontent.com/assets/10259214/24879907/a9587936-1e38-11e7-9782-e82b4f992c75.png)
And after a while the pile smokes no longer and the wood pile blocks are now charcoal blocks.
![2017-04-10_22 03 31](https://cloud.githubusercontent.com/assets/10259214/24880146/8f34b9b0-1e39-11e7-9090-c036b8632ecf.png)
The fireproof blocks are important. Special cover blocks give more charcoal than other blocks.
This blocks and how much charcoal they produce can you see under the "Charcoal Pile" category in jei.

**Comment by Nedelosk** [comment]
@mezz I think we have to update the wiki.

**Comment by Terpo** [comment]
That would be very helpful. Such cool features just aren't recognized at all if there is no documentation for it. Found out about the whole thing just reading the changelog a long time ago where it wasn't even implemented completly.

Now I can disable the charcoal coal recipe! :D ty

**Comment by mezz** [comment]
I think the wiki can be edited by anyone who signs up. Help is appreciated.
https://forestryforminecraft.info/

**Comment by Terpo** [comment]
You might want to polish that one: https://forestryforminecraft.info/other:charcoal
Its my first wiki entry for a long time.
I did not figure out how to find 48px images of the Wood Pile block.

**Comment by InjuredWolf** [comment]
is there anything regarding how long it takes per log pile?
