### ISSUE TITLE
Pretty Little Suggestion ^^

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#1634]
If i drop any bee on the ground, it should fly away, then this means no drop on ground, i destroyed it by pressing Q. Can you do this please? I will make sense. ^^ Thanks.

**Comment by mezz** [comment]
This sounds nice, but sorry I want to limit new features in Forestry. It is already a very big mod.

**Comment by 3TUSK** [comment]
@mezz I guess [this](https://github.com/3TUSK/BeeRelease) is what he wants?

**Comment by mezz** [comment]
That looks like it, yes. 
I think it would be very sad if someone accidentally tossed an important bee that way though.

**Comment by 3TUSK** [comment]
Maybe a blacklist based on genome can solve the potential issue, but deserializing that nbt tag...? Sounds like not worth for me.

**Comment by ghost** [comment]
..... you guys are really rude... you could add config at least... it is a little thing...  pressing Q will destroy a bee instead of throwing it on ground, it is all...
