### ISSUE TITLE
[Question] Regarding automation and tubes

### ISSUE THREAD

**Issue by yujukitten** [ForestryMC/ForestryMC#1635]
I personally never played on 1.7 but the Buildcraft pipes seem amazing and I have been testing Tubes and conduits trying to get similar functionality/ease like those seemed to give. The only ones I can get to work reliably in 11.2 is Extrautilities, to pass water or items to and from the multi-farms. But although they work I find the networking capabilities of ExU2 abit limited so had hoped to find a more robust option. 

11.2 -* Integrated Dynamics (integrated tunnels), pipes, as well as Xnet* do not seem to truly see the Multifarm as a receptacle. (And I cannot really find to many network systems available for 11.2 to try.)

In 10.2 Ender IO energy conduits seem to work ok and again Extra utilities will work But 
*Ender IO Item conduits, integrated dynamics(tunnels added), and a few more* 
All either partially work or seem to at times in some manner (which I can usually never determine if its me, the system or the multifarm.)

Which leads me to coming here to ask for help;
I have noticed on the wiki it is mentioned that redpower2 tubes behave differently then buildcraft tubes and it is intended. Is it just the same for these others Direction or location (N-W etc, or Up/down) make the difference ? 
Are Redpower2 tubes from red project? And is that the recommended system in 1.10.2 to use in addition to Forestry like Buildcraft seemed to be for 1.7? If so what is recommended for 11.2 or is it that we are all still waiting for Buildcraft to hopefully update to the others?  I have not managed to find any tutorials or videos showing automation that did not include Buildcrafts tubes. If I have simply missed a great guide / tutorial on how this might be achieved in 10.2 and 11.2 could someone point me in the right direction please and a huge thank you for any help. This is the last thing I need to stabilize in the modpacks before I can finally set to enjoying bees and tree breeding myself. *^^*

**Comment by EnderiumSmith** [comment]
redpower tubes are the 1.4.6 redpower tubes. EnderIO conduits work well and allow for 100% space efficiency without the cave trait. they work better when chunkloaded and when short. so use EnderIO to sort and railcraft to transport.

**Comment by yujukitten** [comment]
Ok so Ender Io will connect im just doing something wrong then. I will experiment with directional placement more Thank you for the input.

**Comment by EnderiumSmith** [comment]
enable self feed on EnderIO conduit(in in/out mode)

**Comment by yujukitten** [comment]
Thank you again for the information I have been able to get it to work on multifarm for water and items though it seems finicky I had never noticed in and out had a further setting of insert/ extract  

I will continue to experiment *^^* for some reason I still epic fail on the green house water supply. I guess perhaps 11.2 and 10.2 just are not established enough for these networks to run well with things like buildcraft appeared to.
