### ISSUE TITLE
MC 1.11.2 - Forestry Crash with Better Foliage

### ISSUE THREAD

**Issue by JonnyBrando** [ForestryMC/ForestryMC#1637]
MC is crashing: tesselating block model, forestry_leaves.

Didn't notice this issue happening with forestry_1.11.2-5.3.1.38. Jumped from 38 to 58, so, not sure when this started.

Already updated from forestry_1.11.2-5.3.2.58 to forestry_1.11.2-5.3.2.60. Same problem.

[crash-2017-03-18_12.23.41-client.txt](https://github.com/ForestryMC/ForestryMC/files/852611/crash-2017-03-18_12.23.41-client.txt)
[crash-2017-03-18_13.17.29-client.txt](https://github.com/ForestryMC/ForestryMC/files/852610/crash-2017-03-18_13.17.29-client.txt)
[fml-client-latest.txt](https://github.com/ForestryMC/ForestryMC/files/852613/fml-client-latest.txt)

**Comment by Ristovski** [comment]
This is caused by OptiFine, see [sp614x/optifine#511](https://github.com/sp614x/optifine/issues/511)

**Comment by Ravin890** [comment]
I am questioning if something like leaves were set to smart (aka the one you can see through)

**Comment by Ristovski** [comment]
@Ravin890 See [sp614x/optifine#511](https://github.com/sp614x/optifine/issues/511)
