### ISSUE TITLE
Natural Hives Question

### ISSUE THREAD

**Issue by HypnoPants** [ForestryMC/ForestryMC#1638]
Do the naturally spawning beehives also pollinate flowers, or just the player-made ones?

**Comment by mezz** [comment]
In Minecraft 1.8+ they do pollinate, but because they are just hive bees they are not very fast at it.

**Comment by HypnoPants** [comment]
ah, gotcha. I've been placing "secret" hives in creative to see the fields grow nearby on my server, where I don't have to deal with the aviary work when I'm not online.
