### ISSUE TITLE
Thermionic Fabricator & Glass Pane

### ISSUE THREAD

**Issue by Ravin890** [ForestryMC/ForestryMC#1639]
Using glass panes in the thermionic fabricator craft server after it turns into molten glass.
Crash Report: https://hastebin.com/fadegebawi.pl

I was crafting tin electron tubes and using a clockwork engine to power it on the server and got that crash.

Then to confirm I tested in a single player world and also crashed while using rftool's creative powercell for same recipe.
[crash-2017-03-23_16.45.56-server.txt](https://github.com/ForestryMC/ForestryMC/files/866175/crash-2017-03-23_16.45.56-server.txt)

**Comment by SirSengir** [comment]
I have tried reproducing that crash with no luck. Could you post a screenshot of the fabricator before it crashes (so I can see what's in the inventory).

**Comment by Nedelosk** [comment]
I have fixed it.
