### ISSUE TITLE
Forestry causing door glitch?

### ISSUE THREAD

**Issue by CowboyCassanova** [ForestryMC/ForestryMC#1642]
I'm getting [forestry]: Created: 256x128 textures-atlas in console every time i place a door and its causing the atlas to show up on vanilla wooden doors instead of their intended textures.

**Comment by mezz** [comment]
Is it this bug? https://github.com/Ordinastie/MalisisDoors/issues/134

**Comment by CowboyCassanova** [comment]
yeh thats it is there a fix aside from removing one of the mods?

**Comment by mezz** [comment]
I don't really know, please ask in that issue since they will have a better idea of what's going on.
