### ISSUE TITLE
[1.11.2 - 5.3.2.67] Apiarist Chest no better than Vanilla?

### ISSUE THREAD

**Issue by VallenFrostweaver** [ForestryMC/ForestryMC#1646]
Currently the Apiarist Chest is not counting bees (identified or otherwise) and not displaying stats of bees (identified or otherwise). It also gets stuck open.  See images below.

![bees1](https://cloud.githubusercontent.com/assets/13642054/24467257/bc8b23aa-14ab-11e7-907b-956d8cd44313.jpg)
![bees2](https://cloud.githubusercontent.com/assets/13642054/24467258/bc8bc9d6-14ab-11e7-9122-b22053118fd1.jpg)

**Comment by Nedelosk** [comment]
Duplicate: https://github.com/ForestryMC/ForestryMC/issues/954
