### ISSUE TITLE
Forestry 1.10.2 Butterflies/Cocoons causing a lot of lag.

### ISSUE THREAD

**Issue by deanowhufc** [ForestryMC/ForestryMC#1649]
Playing on a server we noticed a lot of lag happening. Downloaded and run sampler to find that the cause of the issue was Forestry butterflies. We have now killed all the butterflies, problem is we cannot get rid of cocoons. The config says the butterflies can travel 1600 blocks out meaning every tree within that area could be affected. Is there any chance you could add a command to remove said problem? Or have the cocoons disappear when butterflies are removed?

**Comment by deanowhufc** [comment]
Sorry mini update:

Seems I hadn't actually killed all butterflies, even running /kill @e[type=forestry.butterflyGE] command several times. Is there anything within Forestry that could help?

Also forgot to mention we are playing on the Direwolf 20 modpack, version 1.8.1.

**Comment by LuigiHutch** [comment]
Try /forestry butterfly kill

**Comment by ProfessorFuzz** [comment]
How do you get silk wisps?  This is one of the only places I found that actually mentions the cocoons which I assumed was how.  But I found not tool that produces it.

**Comment by ktole1999** [comment]
arent wisps a by product of bee harvesting?
