### ISSUE TITLE
[1.8.9] broken java7checker?

### ISSUE THREAD

**Issue by pPkMnh4to8994h** [ForestryMC/ForestryMC#1650]
so, i built sources of forestry for 1.8.9, but it crashing
it is way to fix it, or 1.8.9 port just unplayable?
there is no any crash reports, so i provide you [latest.log](https://gist.github.com/pPkMnh4to8994h/6cf87798e1c3575590fdda89c5336c06)
help?

**Comment by mezz** [comment]
I'm not sure how you're building it but you're kind of on your own, we never released a 1.8.9 version for a reason.
Remove the java7checker stuff from build.gradle and try again. Beyond that I can't really help you out, I don't really remember what was still broken in the version.
