### ISSUE TITLE
Greenhouse humidity

### ISSUE THREAD

**Issue by FoolishBalloon** [ForestryMC/ForestryMC#1651]
Hey!

I've just built a 5x5x5 greenhouse on a server. Since it's lacking documentation, I'm guessing on most stuff I'm doing.

I began by installing a gearbox and supplying it with power. Then I added a Greenhouse Control and a Heater, and this worked and brought the temperature up to 199%. There does seem to be some problems here though, sometimes the apiaries in it don't recognize the greenhouse's conditions, and register the temperature as if it was outside. Usually this is fixed on the hourly restarts of the server I'm playing on.

After breeding the bees I wanted, I then wanted to breed Modest bees. I installed a Dryer, but nothing happened. The F3 Overlay said that it was turned "off". I then gave up on dryer and went for Jungle bees and removed the dryer and installed a sprinkler. The sprinkler started consuming water properly, and somehow began it's animation. But the humidity didn't rise.

**Comment by Nedelosk** [comment]
The greenhouse climate system is bad in 1.10. I  have improved it in 1.11.

**Comment by FoolishBalloon** [comment]
I'm playing on Feed The Beast Beyond, so 1.11 is sadly not an option for me. Do you think it's possible to implement the improvements so they're added to Beyond?

Also, was it some bug I encountered, or did I just do something wrong?

**Comment by Nedelosk** [comment]
I have planned a backport of this improvement, but that take some time. And yes that is a bug.

**Comment by Nedelosk** [comment]
Fixed in 1.12.

**Comment by StoneLegion** [comment]
@Nedelosk Thanks looking forward to the backport for 1.10.2.
