### ISSUE TITLE
Arborists broken in Beyond.

### ISSUE THREAD

**Issue by FoolishBalloon** [ForestryMC/ForestryMC#1654]
Hello!

Since Beyond 1.3 Arborists have been broken. They don't give Forestry trades. If new arborists are spawned they get Immersive Engineering trades, and if existing arborists are traded with so they unlock new trades the new trades are Immersive Engineering ones.

**Comment by mezz** [comment]
Unfortunately I think this is a Forge issue, Forestry does not have control over the villager's professions. We just use the registry Forge gives us, I think in this case it became broken somehow.
