### ISSUE TITLE
[1.7.10] Bio Generator produced const EU/t value, regardless of the settings

### ISSUE THREAD

**Issue by KorDum** [ForestryMC/ForestryMC#1656]
Latest version of Forestry — 4.2.16.64
In gamemode config:
```
fuel {
        ethanol {
            S:generator=10.0
        }
        biomass {
            S:generator=6.0
        }
}
```
This setting affects the amount of energy put into inner buffer, but generator send to out const value — 32 EU/t.

**Comment by Nedelosk** [comment]
And what is the problem ?

**Comment by Nedelosk** [comment]
The eu that the generator produces has the value of config value * 32 (ethanol) or config value * 8 (biomass). And the generator is tier 1, so he can only send out 32 EU/t.

**Comment by KorDum** [comment]
> The eu that the generator produces has the value of config value * 32 (ethanol) or config value * 8 (biomass)

Absolutely useless without configuration EU/t.

Why the generator is tier 1 only? It's not configurable :(

**Comment by danielrossyamitrano** [comment]
I guess that burning ethanol is more efficient rather than biomass, because it last longer. It is like the impregnated frames vs the untreated ones: their output is the same, but the durations (and therefore efficincy) is different

**Comment by KorDum** [comment]
@zenieldanaku 

```
fuel {
        ethanol {
            S:generator=10.0
        }
```
This setting has no effect, if it is from 1 to 10 value. Generator produce out 32 EU/t, not more. Useless. You can only reduce the value and get a smaller output of energy if generator buffer is empty.

**Comment by zenieldanaku** [comment]
Sorry to comment on a closed issue, but I want to state something

@KorDum I wouln't call it useless because 32EU/t is a lot of power, in the **early game**.
