### ISSUE TITLE
Crash on Loading new world 1.11.2 

### ISSUE THREAD

**Issue by Erinbutt** [ForestryMC/ForestryMC#1659]
Using the latest 1.11.2 version. Crash happened when I generated a fresh world. Loaded up for a few seconds then crashed immediately after

Tried the following:
- Deleting both previous Better foliage and Forestry mods (leftovers from 1.10.2) seeing that maybe something didnt agree with how previous configs were set up: No go, still crashed
- Pulling out forestry alone fixed it
- Putting Forestry and Better Foilage together alone: Was fine until I walked around, crashed again.
-Pulled out real world (new mod by another author who has stated he had a new rendering system for some of his stuff) and was not the culprit either.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ChiselCorePlugin (Chisel-MC1.11.2-0.0.9.13.jar)
  LoadingPlugin (Quark-r1.2-90.jar)
  BetterFoliageLoader (BetterFoliage-MC1.11.2-2.1.4.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 4/13/17 10:46 PM
Description: Tesselating block model

java.lang.NullPointerException: Tesselating block model
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213)
	at forestry.core.models.ModelBlockDefault.func_188616_a(ModelBlockDefault.java:97)
	at SmartLeaves.getLeavesModel(SmartLeaves.java:50)
	at BlockModelCustomizer.getRenderModel(BlockModelCustomizer.java:30)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:72)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:54)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
	at mods.octarinecore.client.render.AbstractBlockRenderingHandler.renderWorldBlockBase(AbstractBlockRenderingHandler.kt:53)
	at mods.betterfoliage.client.render.RenderLeaves.render(RenderLeaves.kt:56)
	at mods.betterfoliage.client.Hooks.renderWorldBlock(Hooks.kt:88)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:293)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:119)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:47)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213)
	at forestry.core.models.ModelBlockDefault.func_188616_a(ModelBlockDefault.java:97)
	at SmartLeaves.getLeavesModel(SmartLeaves.java:50)
	at BlockModelCustomizer.getRenderModel(BlockModelCustomizer.java:30)

-- Block model being tesselated --
Details:
	Block: forestry:leaves[check_decay=false,decayable=true]
	Block location: World: (89,67,192), Chunk: (at 9,4,0 in 5,12; contains blocks 80,0,192 to 95,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Using AO: false
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:72)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:54)

-- Block being tesselated --
Details:
	Block type: ID #1310 (tile.for.leaves // forestry.arboriculture.blocks.BlockForestryLeaves)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (89,67,192), Chunk: (at 9,4,0 in 5,12; contains blocks 80,0,192 to 95,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
	at mods.octarinecore.client.render.AbstractBlockRenderingHandler.renderWorldBlockBase(AbstractBlockRenderingHandler.kt:53)
	at mods.betterfoliage.client.render.RenderLeaves.render(RenderLeaves.kt:56)
	at mods.betterfoliage.client.Hooks.renderWorldBlock(Hooks.kt:88)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Buttard'/1505, l='MpServer', x=80.50, y=73.00, z=252.50]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (80,64,256), Chunk: (at 0,4,0 in 5,16; contains blocks 80,0,256 to 95,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 162 game time, 162 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 74 total; [EntitySkeleton['Skeleton'/2586, l='MpServer', x=133.50, y=35.00, z=217.50], EntitySkeleton['Skeleton'/2587, l='MpServer', x=133.50, y=35.00, z=217.50], EntitySpider['Spider'/2602, l='MpServer', x=65.50, y=35.00, z=269.50], EntityZombieVillager['Zombie Villager'/2603, l='MpServer', x=62.50, y=35.00, z=272.50], EntityZombieVillager['Zombie Villager'/2604, l='MpServer', x=65.50, y=35.00, z=277.50], EntityBat['Bat'/2093, l='MpServer', x=27.70, y=40.64, z=245.75], EntityZombieVillager['Zombie Villager'/2605, l='MpServer', x=65.50, y=35.00, z=278.50], EntityBat['Bat'/2095, l='MpServer', x=31.21, y=40.23, z=236.56], EntityCowHereford['Hereford Cow'/50, l='MpServer', x=33.00, y=74.00, z=268.04], EntityItem['item.tile.gravel'/2098, l='MpServer', x=78.13, y=17.00, z=269.45], EntityCalfHereford['Hereford Calf'/51, l='MpServer', x=30.93, y=74.00, z=273.06], EntityCowHereford['Hereford Cow'/52, l='MpServer', x=40.01, y=72.00, z=266.14], EntityHenRhodeIslandRed['Rhode Island Red Hen'/53, l='MpServer', x=71.75, y=64.17, z=227.32], EntityRoosterRhodeIslandRed['Rhode Island Red Rooster'/54, l='MpServer', x=71.52, y=65.00, z=227.77], EntityChickRhodeIslandRed['Rhode Island Red Chick'/55, l='MpServer', x=71.50, y=68.00, z=231.61], EntityCowHereford['Hereford Cow'/60, l='MpServer', x=74.03, y=71.00, z=288.99], EntityBullHereford['Hereford Bull'/61, l='MpServer', x=80.46, y=72.00, z=284.55], EntitySkeleton['Skeleton'/2629, l='MpServer', x=8.50, y=17.00, z=232.50], EntitySkeleton['Skeleton'/2645, l='MpServer', x=70.50, y=43.00, z=242.50], EntityZombie['Zombie'/2134, l='MpServer', x=41.50, y=15.00, z=206.50], EntitySkeleton['Skeleton'/2646, l='MpServer', x=71.50, y=43.00, z=239.50], EntityCreeper['Creeper'/2137, l='MpServer', x=3.50, y=33.00, z=255.50], EntitySpider['Spider'/2138, l='MpServer', x=4.50, y=33.00, z=256.50], EntitySkeleton['Skeleton'/2665, l='MpServer', x=28.50, y=56.00, z=265.50], EntityPlayerSP['Buttard'/1505, l='MpServer', x=80.50, y=73.00, z=252.50], EntityGuardian['Guardian'/2686, l='MpServer', x=8.94, y=58.09, z=176.67], EntitySkeleton['Skeleton'/2689, l='MpServer', x=82.25, y=63.00, z=283.54], EntityItem['item.tile.gravel'/2184, l='MpServer', x=56.88, y=56.00, z=271.88], EntityCreeper['Creeper'/2187, l='MpServer', x=62.50, y=43.00, z=239.50], EntitySkeleton['Skeleton'/2188, l='MpServer', x=2.23, y=34.00, z=176.61], EntityCreeper['Creeper'/2190, l='MpServer', x=36.50, y=42.00, z=208.50], EntityDweller['Dweller'/2704, l='MpServer', x=45.50, y=14.00, z=284.50], EntityCreeper['Creeper'/2707, l='MpServer', x=43.30, y=38.00, z=263.50], EntityCreeper['Creeper'/2708, l='MpServer', x=44.97, y=38.00, z=263.50], EntityCreeper['Creeper'/2709, l='MpServer', x=45.50, y=38.00, z=261.50], EntitySkeleton['Skeleton'/2710, l='MpServer', x=48.50, y=38.00, z=263.50], EntityItem['item.tile.gravel'/2227, l='MpServer', x=56.13, y=56.00, z=271.13], EntityZombie['Zombie'/2746, l='MpServer', x=48.50, y=38.00, z=259.50], EntityZombie['Zombie'/2747, l='MpServer', x=49.50, y=38.00, z=262.50], EntityEnderman['Enderman'/2759, l='MpServer', x=-0.34, y=14.00, z=249.60], EntityBat['Bat'/2266, l='MpServer', x=29.25, y=58.86, z=261.42], EntityZombie['Zombie'/2829, l='MpServer', x=71.50, y=31.00, z=255.50], EntityZombie['Zombie'/2830, l='MpServer', x=73.50, y=31.00, z=256.50], EntityZombie['Zombie'/2831, l='MpServer', x=71.50, y=31.00, z=258.50], EntityCreeper['Creeper'/2832, l='MpServer', x=71.58, y=31.00, z=262.24], EntityItem['item.tile.flower_1.miners_delight'/2839, l='MpServer', x=53.06, y=34.00, z=288.77], EntityItem['item.item.berries'/2842, l='MpServer', x=63.15, y=66.00, z=203.88], EntitySpider['Spider'/2363, l='MpServer', x=58.50, y=34.00, z=252.50], EntitySpider['Spider'/2364, l='MpServer', x=60.50, y=34.00, z=251.50], EntityGuardian['Guardian'/2395, l='MpServer', x=136.02, y=54.10, z=201.25], EntitySkeleton['Skeleton'/2402, l='MpServer', x=44.50, y=15.00, z=205.50], EntityBat['Bat'/2420, l='MpServer', x=34.34, y=43.04, z=252.66], EntitySkeleton['Skeleton'/2459, l='MpServer', x=77.50, y=65.00, z=284.50], EntitySkeleton['Skeleton'/2460, l='MpServer', x=77.50, y=65.00, z=283.50], EntityBat['Bat'/2463, l='MpServer', x=72.73, y=28.25, z=285.02], EntityBat['Bat'/2465, l='MpServer', x=75.11, y=29.58, z=262.86], EntityBat['Bat'/2467, l='MpServer', x=73.35, y=29.21, z=280.96], EntityCreeper['Creeper'/2469, l='MpServer', x=48.50, y=38.00, z=259.50], EntityCreeper['Creeper'/2470, l='MpServer', x=51.50, y=38.00, z=254.50], EntityItem['item.tile.gravel'/2493, l='MpServer', x=105.19, y=39.00, z=309.13], EntitySpider['Spider'/2014, l='MpServer', x=51.70, y=43.10, z=237.36], EntityZombie['Zombie'/2016, l='MpServer', x=55.50, y=42.00, z=238.50], EntityZombie['Zombie'/2017, l='MpServer', x=52.30, y=42.00, z=239.93], EntityBat['Bat'/2547, l='MpServer', x=92.53, y=16.12, z=278.55], EntitySquid['Squid'/2037, l='MpServer', x=129.92, y=59.84, z=280.11], EntitySquid['Squid'/2038, l='MpServer', x=137.72, y=58.60, z=267.27], EntitySquid['Squid'/2039, l='MpServer', x=132.52, y=58.38, z=272.84], EntitySquid['Squid'/2040, l='MpServer', x=135.10, y=55.30, z=267.16], EntitySquid['Squid'/2041, l='MpServer', x=103.47, y=61.90, z=207.50], EntitySquid['Squid'/2042, l='MpServer', x=95.99, y=59.42, z=212.33], EntitySquid['Squid'/2043, l='MpServer', x=99.27, y=62.18, z=207.15], EntitySquid['Squid'/2044, l='MpServer', x=95.40, y=59.26, z=206.40], EntitySquid['Squid'/2045, l='MpServer', x=134.40, y=62.50, z=203.01], EntitySquid['Squid'/2046, l='MpServer', x=133.92, y=61.85, z=205.12]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:57)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2623671848 bytes (2502 MB) / 6170345472 bytes (5884 MB) up to 6170345472 bytes (5884 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144M -Xms6144M
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.38 Powered by Forge 13.20.0.2282 Optifine OptiFine_1.11.2_HD_U_B7 18 mods loaded, 18 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2282.jar) 
	UCHIJAAAA	forge{13.20.0.2282} [Minecraft Forge] (forge-1.11.2-13.20.0.2282.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCHIJAAAA	animania{1.0.4.6} [Animania] (animania-1.11.2-1.0.4.6.jar) 
	UCHIJAAAA	quark{r1.2-90} [Quark] (Quark-r1.2-90.jar) 
	UCHIJAAAA	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCHIJAAAA	betterfoliage{2.1.4} [Better Foliage] (BetterFoliage-MC1.11.2-2.1.4.jar) 
	UCHIJAAAA	biomesoplenty{6.0.2.2169} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.0.2.2169-universal.jar) 
	UCHIJAAAA	chisel{MC1.11.2-0.0.9.13} [Chisel] (Chisel-MC1.11.2-0.0.9.13.jar) 
	UCHIJAAAA	chiselsandbits{13.10} [Chisels & Bits] (chiselsandbits-13.10.jar) 
	UCHIJAAAA	props{2.4.1} [Decocraft] (Decocraft-2.4.1_1.11.2.jar) 
	UCHIJAAAA	flatcoloredblocks{mc1.11-5.1} [Flat Colored Blocks] (flatcoloredblocks-mc1.11-5.1.jar) 
	UCHIJAAAA	forestry{5.3.3.91} [Forestry] (forestry_1.11.2-5.3.3.91.jar) 
	UCHIJAAAA	jei{4.3.2.263} [Just Enough Items] (jei_1.11.2-4.3.2.263.jar) 
	UCHIJAAAA	harvestcraft{1.11.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2g.jar) 
	UCHIJAAAA	realworld{1.0} [RealWorld] (realworld-1.0.jar) 
	Loaded coremods (and transformers): 
ChiselCorePlugin (Chisel-MC1.11.2-0.0.9.13.jar)
  team.chisel.common.asm.ChiselTransformer
LoadingPlugin (Quark-r1.2-90.jar)
  vazkii.quark.base.asm.ClassTransformer
BetterFoliageLoader (BetterFoliage-MC1.11.2-2.1.4.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Launched Version: 1.11.2-forge1.11.2-13.20.0.2282
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz
	OptiFine Version: OptiFine_1.11.2_HD_U_B7
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 378.66
	OpenGlRenderer: GeForce GT 745M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by Nedelosk** [comment]
Duplicate: #1637
