### ISSUE TITLE
[1.11] Lack of recipes 

### ISSUE THREAD

**Issue by zetosuru** [ForestryMC/ForestryMC#1660]
Currently while working on a pack with a friend, we are finding an issue where none of the machine recipes are appearing in JEI. Normal crafting recipes appear, but none for say the carpenter are there. Currently we are running version 5.3.3.91

**Comment by mezz** [comment]
Did you find the solution to this?

**Comment by zetosuru** [comment]
I did. When JEI updated, the recipes appeared. Don't really understand why that hide the recipes, but it's working now.
