### ISSUE TITLE
Farm control doesn't appear to work

### ISSUE THREAD

**Issue by jeridan** [ForestryMC/ForestryMC#1662]
Built a farm, is working as expected.  Put a lever on the farm control block and it will not disable the farm..  (tested on bottom and top)

Modpack: FTB Beyond 1.5.3
Minecraft: 1.10.2
Forge: 12.18.3.2254
forestry_1.10.2-5.2.17.374

For issues:
 * Try the latest version, it may have fixed the issue already.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

**Comment by Nedelosk** [comment]
@jeridan The farm controller block only disable the planting of new seeds.

**Comment by jeridan** [comment]
Ok, I have validated that is the case.  I would prefer it work like it used to but now I know how it works.  Thanks!
