### ISSUE TITLE
Log Bundles should be able to Orient Sideways

### ISSUE THREAD

**Issue by Morvelaira** [ForestryMC/ForestryMC#1664]
Currently, log bundles will only orient up and down.  They should be able to orient sideways as well. This would make for some fantastic looking beams in houses!

-Morvelaira, Purrveyor of Doom and Cuteness, OMGThatsABigBuilder Extraordinaire

**Comment by temp1011** [comment]
This is implemented now right?

**Comment by Nedelosk** [comment]
Yes
