### ISSUE TITLE
All Bees Have the Same ID - Not Corresponding to ChestShop

### ISSUE THREAD

**Issue by 05192000** [ForestryMC/ForestryMC#1665]
With any version of Forestry, we as players well know that ALL bees (ID 4657/4656) have the same ID, in which selling bees on Multiplayer via ChestShop or any other plugin is not capable. Therefore, the issue is that it is not possible to sell bees via plugins.

Request: Add a different ID for each bee. Example: Forest Drone with an ID of 4656:1, Meadows Drone with an ID of 4546:2, and so on.

Thank you for reporting!

For issues:
 * Try the latest version, it may have fixed the issue already.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

**Comment by ktole1999** [comment]
or use a mod that supports meta data?

**Comment by mezz** [comment]
Unfortunately the bees have too much data to encode it into their meta value. There are two species per bee, two of every trait. 
This is all stored in NBT, any mod that works with bees uses this NBT to decide if one bee matches another. For instance, EnderIO has a sorting pipe for bees that only compares the species by checking the NBT.

**Comment by 05192000** [comment]
I understand but in Pam's Harvestcraft, she put a separate ID for every single item she had. I think that adding the meta to the bees will overall improve performance in accordance to other mods.

**Comment by Nedelosk** [comment]
I close this, because I don't think that we are adding this.
