### ISSUE TITLE
Greenhouse Rework

### ISSUE THREAD

**Issue by Nedelosk** [ForestryMC/ForestryMC#1668]
I want to rewrite the greenhouse. Simpler climate system, more functionality, simpler to build and more server friendly.
And we need a greenhouse wiki page.
---
- [x] Climate system
- [x] More functionality
- [x] Building
- [x] Server friendly
- [x] Wiki page
- [x] New GUI
- [x] Port to 1.12

[Branch](https://github.com/ForestryMC/ForestryMC/tree/Greenhouse)

**Comment by Nedelosk** [comment]
@mezz Do you any idea how we can test if a room is closed, without that every block around this room is a greenhouse block ?

**Comment by CovertJaguar** [comment]
Could we get Tough as Nails integration as well?

**Comment by mezz** [comment]
@Nedelosk I think you could 3d-flood-fill from a spot "inside" and check if it terminates before some max-distance. This may not be easy to implement efficiently, some more restrictions could help.

**Comment by mezz** [comment]
Tough as Nails integration would be cool.
I don't want to add features until it's very stable though.

**Comment by Nedelosk** [comment]
We need anything to signal the player that the greenhouse multiblock is assembled, like the band of the farm, any idea ?

**Comment by mezz** [comment]
Maybe spawn some green particles when it is completed?

**Comment by Nedelosk** [comment]
It would be easier and server friendlier if would not test if the greenhouse is closed.

**Comment by Nedelosk** [comment]
![2017-07-04_22 59 02](https://user-images.githubusercontent.com/10259214/27842707-af0ea442-610c-11e7-8ee0-96961717035e.png)
![2017-07-04_23 02 08](https://user-images.githubusercontent.com/10259214/27842728-dba71b42-610c-11e7-803b-fd45072a3797.png)
This is the top of the greenhouse structure. The point in the middle shows that the greenhouse is closed. If it is closed the point is green and if it is not closed it is red.
![2017-07-04_23 06 43](https://user-images.githubusercontent.com/10259214/27842801-7863f496-610d-11e7-9518-2fc8b7626a3d.png)
This is the "greenhouse screen". Its color changes with the temperature. And in the gui of the screen you can change at which position the greenhouse starts to test .
@mezz What do you think ?

**Comment by mezz** [comment]
Looks very nice!

**Comment by Nedelosk** [comment]
@mezz  I think we have to find a compromise. It's possible to test every block change if the greenhouse is closed but that's not very performant.

**Comment by mezz** [comment]
Maybe the greenhouse can only care about X and Z coordinates, and requires a flat bottom? That way you only check a 2D area for the ground, and then check each point to make sure it cannot see the sky. It might allow for some strange structures but I think it will be good enough.

**Comment by Nedelosk** [comment]
@mezz Good Idea. Would make many things easier.

**Comment by Nedelosk** [comment]
I have added an new item the "Portable Greenhouse Screen":
![2017-07-13_19 04 41](https://user-images.githubusercontent.com/10259214/28178268-258b2fa8-67fe-11e7-982d-d167b3e9ce15.png)
It shows if the greenhouse is assembled and with it you can select the edges, the height and the depth of the greenhouse. The edges, the height and the depth are important for testing if the greenhouse is closed.
The test itself starts from a position near the center top block of the greenhouse structure. And tests on the X and Z coordinates if the greenhouse is closed and on the Y coordinate if the greenhouse has a roof.

**Comment by mezz** [comment]
Nice :)
