### ISSUE TITLE
Not a bug——about the repost of FR

### ISSUE THREAD

**Issue by forestbat** [ForestryMC/ForestryMC#1671]
I'm an editor of an encyclopedia website www.mcmod.cn of Minecraft in China,because of the different between languages,and many people have trouble to use curse becuase of Google API--too slow in China,so we want to repost your mod to there for spreading RC better,and we still will direct players to curse as possible,do you agree to give us the authority?

**Comment by mezz** [comment]
Yes, you have our permission to repost it there and direct to Curse.
Actually I think it has been there for a long time. http://www.mcmod.cn/class/5.html

You may be interested in this video spotlight too, it has a lot of information in Chinese:
https://www.youtube.com/playlist?list=PLOVEazT_Yg2ceRrPqH6kJ7WN9JD25pejO
