### ISSUE TITLE
WorkTable + Bloodmagic

### ISSUE THREAD

**Issue by Lordi91** [ForestryMC/ForestryMC#1677]
MC - 1.11.2
Latest bloodmagic and forestry - when you shift click a recipe from jei in to the worktable for blook magic - it defaults to the transcendent orb - it will then convert what ever orb you have to the transcendent one if you craft the recipe - if you put a different orb into the crafting grid it will convert to that one at will - tested on server and single

**Comment by Kalmeira** [comment]
Should you really post a dupe bug like this publicly? I was on my way over to see how they wanted it reported myself.
Edit: Don't mean to sound rude, but most people do not want dupe bugs spread around.

**Comment by KnightMiner** [comment]
Github has no PM feature and it is generally bad taste sending bug reports via email or private message on another site. Dupe bugs exist, so do mods that give practically free resources, so if not this bug people have other ways to do this.

**Comment by Vectrobe** [comment]
With how easy it can be to find these bugs yourself, there's really no point in keeping it a 'secret bug report' (which is almost impossible to deal with anyway unless the dev has a private bug/activity board as well), it's also better for server and pack admins if these things are readily available.

Referencing #1403 here as well as they're somewhat similar, crafting doesn't carry items over correctly.

**Comment by mezz** [comment]
This has been fixed in 1.10 and above.
