### ISSUE TITLE
[1.7.10] crash (ItemWrench)

### ISSUE THREAD

**Issue by Felixfex** [ForestryMC/ForestryMC#1678]
Soo I am Having a Problem Right here:

[gist](https://gist.github.com/Felixfex/e1e570d2fcea3842d011c9abec388ed7)

Its Has Bugging me since i started to create a modpack for 1.7.10.
I hope you can find the problem, because i cant find it :D

**Comment by mezz** [comment]
It looks like the Buildcraft API is being included by ExtraUtilities, which is not good.
> BuildCraftAPI|tools (1.0) from extrautilities-1.2.12.jar

Try removing ExtraUtilities and see if that solves the issue.

**Comment by Felixfex** [comment]
Thank you that was the Problem :D
