### ISSUE TITLE
1.10.2 lack of butterflies

### ISSUE THREAD

**Issue by NoahNinja** [ForestryMC/ForestryMC#1680]
It says there are 28 butterflies available on the wiki, in a creative world, I only saw 6 in the creative inventory

**Comment by mezz** [comment]
Not all of the butterflies are available in the creative inventory, but they exist in the game. This is an old decision, there were similar restrictions on bees and trees before and we changed that so they're all displayed now.
I think we should include all the butterflies in the creative menu as well.

**Comment by NoahNinja** [comment]
Thanks, I didn't know that
