### ISSUE TITLE
1.11.2 - Forestry Leaves do not Decay

### ISSUE THREAD

**Issue by WillBuik** [ForestryMC/ForestryMC#1681]
The leaves of Forestry trees seem not to decay in 1.11 (Forestry version 1.11.2-5.3.3.96, Forge version 1.11.2-13.20.0.2296).  Vanilla leaves and those added by other mods decay as expected.

In the F3 details, all Forestry leaves seem to have 'decayable' metadata set to false.  This issue repros even when no other mods are installed.

**Comment by mezz** [comment]
Thanks for the report!
Confirmed, I'll release a fix soon.

**Comment by mezz** [comment]
Fixed in the next version. Old leaves will fix themselves when they get a block tick update, so they will decay normally even if the `decayable` metadata appears to be set to false for a while. New leaves will properly have `decayable` set to true when they are created.
