### ISSUE TITLE
1.11.2 Electrical Engine can't connect to 1.11.2 IC2

### ISSUE THREAD

**Issue by tehboomer** [ForestryMC/ForestryMC#1682]
forestry_1.11.2-5.3.3.96.jar electrical engine will not take in any EU from Industrialcraft-2-2.7.12-ex111.jar

I have tried with cables, insulated copper as well as glass fibre (http://imgur.com/g2lWxrM), and have also tried putting a battery into the electrical engine slot (http://imgur.com/JVsaxy4).

Neither of these methods work, rendering the electrical engine useless and also preventing any conversion between the two mods.

**Comment by Kalmeira** [comment]
The electrical engine works fine with insulated tin cables as of:
Version: forestry_1.11.2-5.3.4.99
and
Version: Industrialcraft-2-2.7.33-ex111
