### ISSUE TITLE
1.10.2 Crashing when picking up armor 

### ISSUE THREAD

**Issue by iAerosoft** [ForestryMC/ForestryMC#1683]
I'm having an issue where picking up armor causes the client's game to crash. I'm running the 1.10.2 version. Here is the error https://pastebin.com/dmNrnSSM
I first noticed when picking up an armor piece (Trench coat) from the Cyberware mod.
I then removed it and tried other armors from a different mod and it resulted in a crash. The error says something about Forestry in the console.

**Comment by Nedelosk** [comment]
Fixed in 1.12.
