### ISSUE TITLE
Game Crash With Another Mod

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#1684]
used forge 2296, forestry 5.3.4.99 and [this](https://minecraft.curseforge.com/projects/iyamatos-mob-mod?gameCategorySlug=mc-mods&projectID=267062) mod. sorry if it's not forestry's fault.
[crash-2017-05-14_23.12.08-server.txt](https://github.com/ForestryMC/ForestryMC/files/999693/crash-2017-05-14_23.12.08-server.txt)
here is the crash report.

**Comment by mezz** [comment]
I think this is a bug on their side. Their entity crashes when attacked by bees.

**Comment by ghost** [comment]
hmm, i know their entity, it teleports when hitted such like enderman. does forestry crashes when bees attack to an enderman?

**Comment by mezz** [comment]
No, it works fine.
