### ISSUE TITLE
1.11.2 Config changes in GUI reset to values in file

### ISSUE THREAD

**Issue by Arrabal-** [ForestryMC/ForestryMC#1686]
Forestry version:  5.3.4.99
Forge version:  13.20.0.2298

When disabling Copper and Tin ore generation in the config through the in game GUI, the values are reset to TRUE following a Minecraft restart.  I have confirmed that the values are not being written to common.cfg after making the change, and when Minecraft is restarted the values saved in the file replace the values set previously in the GUI.

If the values are altered in the file itself, through a text editor, those changes persist, however, again, changes made in the in-game GUI do not persist.

This applies to all config settings that reference the common.cfg.  I have not validated whether this impacts all of the various config files, however, based on updated timestamps on the other config files it looks like the other config files are being updated correctly except for plugins.cfg.

**Comment by hextrace** [comment]
Can confirm that I have seen this bug in both 1.10.2 and 1.11.2.  A temporary workaround is to manually edit and set the file read-only in order to make changes stick.
