### ISSUE TITLE
1.11.2-5.3.4.99 crashes client after giving forestry:sapling

### ISSUE THREAD

**Issue by kreezxil** [ForestryMC/ForestryMC#1687]
client crash report:
https://pastebin.com/0RtyqcwB

thanfully it's in my testworld and I can easily delete the player.

**Comment by mezz** [comment]
Thanks for the report!

The check here was useful for porting and testing that things are connected properly, but it should probably be replaced now. If there is no nbt, we should use the default species/genome/chromosome.

**Comment by Brycey92** [comment]
I, too am experiencing this issue, but it's on my server's main world and with build 155. I see you made a fix. Any estimate on when it'll be compiled and released?

**Comment by mezz** [comment]
Ah I only fixed it on 1.12. I'll backport the fix to 1.11.2 now.
We automatically build and upload to curse for each commit, usually it takes just 10-15 minutes for a new release to show up.

**Comment by Brycey92** [comment]
Thanks, mezz!
