### ISSUE TITLE
Crash after getting into a new world

### ISSUE THREAD

**Issue by Ushupiuck** [ForestryMC/ForestryMC#1689]
To  be precise, 1-2 mins right after... Mod list included in the crashfile. tried without optifine and still crashes.

[crash-2017-05-14_01.15.02-client.txt](https://github.com/ForestryMC/ForestryMC/files/1015688/crash-2017-05-14_01.15.02-client.txt)

**Comment by mezz** [comment]
Thanks for the report!
This seems to be caused by Optifine's Smart Leaves option.
Please report to them here: https://github.com/sp614x/optifine/issues
