### ISSUE TITLE
Backpack does not resupply the offhand

### ISSUE THREAD

**Issue by mezz** [ForestryMC/ForestryMC#1690]
When holding a block like stone in the offhand, with a backpack set to resupply, the offhand is not resupplied.

**Comment by tzpb8** [comment]
I have this issue too, i discovered the builders backpack and thought it would be nice to refill torches with atleast... i sometimes love to carry torches in the offhand (when mining, it is very useful) but the builders bag(s) will not refill items or blocks in offhand makes this bag much less useful (tho i find more uses for it than i expected... its a mystery to me why it won't accept stairs, they are in the same spirit as slabs for me.

So i try to lift this up for offhand backpack refill support and also to have stairs accepted into the builders bag(s).

I think all vanilla blocks or items should have a bag to accept them :P maybe it is just me.
