### ISSUE TITLE
[Mod Support] Support Mystical Agriculture Seeds

### ISSUE THREAD

**Issue by 016Nojr** [ForestryMC/ForestryMC#1692]
I was wondering if it was possible to add support for the Mystical Agriculture seeds, not sure if it's too quick into 1.11 or not. 

Maybe add an "Inferium Electron Tube" to make the circuit board for the Mystical Agriculture.

Posted this here since you have added support for other mods (atleast before).

**Comment by Nedelosk** [comment]
Duplicate: #1471
