### ISSUE TITLE
Question. API for 1.10.2

### ISSUE THREAD

**Issue by NightKosh** [ForestryMC/ForestryMC#1694]
Hello. I'm looking for an API for latest version of Forestry(for Minecraft 1.10.2). There are only 1.8.9, 1.8, multiblock and master branches in API repository, which weren't changed for 2 years. So is API for 1.10.2 even existed?

**Comment by Nedelosk** [comment]
The api is now located in the ForestryMc repository. https://github.com/ForestryMC/ForestryMC/tree/mc-1.10/src/main/java/forestry/api

**Comment by NightKosh** [comment]
So it is a part of forestry repository, and can't be used as git submodule anymore, am I right?

**Comment by Nedelosk** [comment]
Yes you have to use the maven.

**Comment by NightKosh** [comment]
Could you please explain how can it be done?

**Comment by Nedelosk** [comment]
You have to add this to your build.gradle file and than you have to run "gradlew setupDecompWorkspace" again.

> repositories {
	maven {
		name = "forestry"
		url = "http://maven.ic2.player.to/"
	}
} 
dependencies {
	deobfCompile "net.sengir.forestry:forestry_1.10.2-5.2.17.376:api"
}

**Comment by NightKosh** [comment]
Thank you very much!

**Comment by Nedelosk** [comment]
You are welcome
