### ISSUE TITLE
Peat-Fired Engine

### ISSUE THREAD

**Issue by coleweinman** [ForestryMC/ForestryMC#1695]
Version: forestry_1.10.2-5.2.17.374

For some reason I am unable to put Peat into a peat-fired engine, it just won't let me put it into the slot.

**Comment by Nedelosk** [comment]
@RedGuy54 Are you sure that you have tried it with it with forestry peat ?

**Comment by RedGuy54** [comment]
Yes, after later investigation , it might have something to do with sponge.

**Comment by coleweinman** [comment]
@Nedelosk Yes, it is the peat from forestry.

**Comment by Kalmeira** [comment]
I do not have this problem with Version: forestry_1.11.2-5.3.4.99

**Comment by RedGuy54** [comment]
@Kalmeira I
