### ISSUE TITLE
Block{forestry:doors.walnut}{328b520a} has been registered twice, using the names null and forestry:doors.walnut

### ISSUE THREAD

**Issue by Decrepitdoors** [ForestryMC/ForestryMC#1696]
I installed the latest forestry, 1.11.2-5.3.4.99 on my client and server. I get the above message when trying to join the server.

**Comment by Nedelosk** [comment]
Same bug as #1631 I think.

**Comment by Decrepitdoors** [comment]
Online mode is set to true, but yeah it seems like the same thing.
