### ISSUE TITLE
Instant crash on startup - InitializationError?

### ISSUE THREAD

**Issue by Xorbah** [ForestryMC/ForestryMC#1699]
[crash-2017-05-29_16.38.16-client.txt](https://github.com/ForestryMC/ForestryMC/files/1036718/crash-2017-05-29_16.38.16-client.txt)

As the title states.

**Comment by mezz** [comment]
Thanks for the report!
This seems to be caused by [CustomNPCs](https://minecraft.curseforge.com/projects/custom-npcs/issues). I'm not exactly sure how though. Please report to them.
