### ISSUE TITLE
Slabs not blocking light

### ISSUE THREAD

**Issue by jdkorv11** [ForestryMC/ForestryMC#1702]
Maple slabs are not blocking light in the manner that vanilla slabs do. I have not tested this with other slabs but suspect it impacts all slabs. I don't know if this is desirable behavior so I wanted to report this as the mod is currently in alpha. 

version observed: 5.3.3.97

**Comment by KnightMiner** [comment]
Code wise slabs do set their opacity to 0 which allows all light through, though I assume that was set to work around lighting issues.

Vanilla solves the lighting issues by setting the flag `useNeighborBrightness` on any stairs or slabs in its registry. Why this is not done in the BlockSlab constructor instead no one will ever know, but that is the fix to make them behave like vanilla slabs for light.

**Comment by jdkorv11** [comment]
As I mentioned, I don't know if this behavior is desirable or not. I just found it when making a dark room with a peek hole for a buildcraft moistener. Knowing forestry is in alpha I thought I should report it in case slabs are intended to function like vanilla ones

**Comment by mezz** [comment]
Thanks for the report!
Forestry slabs (and any vanilla-like blocks) are supposed to work just like vanilla.

**Comment by KnightMiner** [comment]
@Nedelosk you are going to want to set the boolean `useNeighborBrightness` to make them fully consistent with vanilla, otherwise they will be way too dark in general (top half black)

**Comment by Nedelosk** [comment]
@KnightMiner thank you 5a5793f243ea3ad0f6dee2b67aa47c5a7190d62b
