### ISSUE TITLE
Compatibility issue with Minecraft-Flux!

### ISSUE THREAD

**Issue by coleweinman** [ForestryMC/ForestryMC#1703]
Version: mcflux-1.6.1 & forestry_1.10.2-5.2.17.374

When MCFlux is installed with Forestry, it breaks some of its features, the one that I noticed was that with MCFlux installed, you can no longer put Forestry peat into a peat-fired engine. I don't know what mod exactly is to blame so I reported it on both mods. 

How to reproduce:

- Install forestry and MCFlux on 1.10.2
- Get a Peat-Fired Engine
- Get Peat and try to put it in the Engine

If you remove MCFlux, you will notice that you will then be able to put peat into the engine.

**Comment by RedGuy54** [comment]
Szewek/Minecraft-Flux#19

**Comment by Nedelosk** [comment]
Fixed in 1.12.
