### ISSUE TITLE
Feature/Config request - Ore spawn 

### ISSUE THREAD

**Issue by AshZification** [ForestryMC/ForestryMC#1704]
It is possible to add a config option for the frequency of ore spawn?  
I'd like to be able to change how much copper and tin spawn to more closely reflect their need in recipes

**Comment by mezz** [comment]
Thanks for the request!
I think people normally use a dedicated mod like Thermal Expansion to control ore generation.
It has a lot more features than we could add to Forestry. 
Here's a guide to use it: https://forum.feed-the-beast.com/threads/cofh-world-generation-users-manual.48678/

Let me know if that works for you. It wouldn't be too hard to add a config to Forestry but we have been very busy porting other mods lately, and I think the TE solution is better overall.

**Comment by CovertJaguar** [comment]
I would recommend Substratum or MMD OreSpawn over the bloat that is COFH-Core.

**Comment by AshZification** [comment]
Considering I don't want to use TE, or other tech mods (Forestry and some parts of AA are as tech as my  current project is going to go) I'll have to go with a separate ore gen mod then. Thanks.
