### ISSUE TITLE
Apiarist pipes missing

### ISSUE THREAD

**Issue by jdkorv11** [ForestryMC/ForestryMC#1705]
I'm guessing this is due to Buildcraft 8 still being under development, but currently there are no apiarist pipes in version 5.3.4.99

**Comment by LuigiHutch** [comment]
The Apiarist pipe was moved from Forestry into BuildCraft Compat a while ago. So it would not be there as BC compat isn't released yet as BC is still in alpha.

**Comment by CovertJaguar** [comment]
For what its worth, I just added some Bee filter items to Railcraft so that you can use loaders to sort them by genome traits. 1.10.2 alphas only though atm.
