### ISSUE TITLE
Scoop not craftable

### ISSUE THREAD

**Issue by xellopip** [ForestryMC/ForestryMC#1706]
Hiya,
For some reason when I put 5 sticks and a wool block into a crafting table (in the right positions) a scoop won't show up as an end result. Any answers to this?

**Comment by Nedelosk** [comment]
@xellopip Please give us more information, we only can fix the bug if we know the MC version and the  Forestry version. And could it be possible that you have used the wrong recipe. The scoop is crafted with 6 sticks and a wool block and not with 5 sticks and a wool block.

**Comment by Nedelosk** [comment]
I close this because of no response
