### ISSUE TITLE
Forestry Farms not accepting any fertilizer

### ISSUE THREAD

**Issue by cpufreak** [ForestryMC/ForestryMC#1711]
So I built a farm up, gave it everything it required, it accepted the dirt and trees (For arboretum setting) and it was accepting water, but it would simply not allow me to place any fertilizer in there.  it is Forestry version 5.3.4.101 on minecraft 1.11.2 Forge version 13.20.0.2312.

One thing I will note is I have not tried to check for a Forestry update yet, as the Jenkins seems to be down. and also, if I'm missing any info, let me know

**Comment by Deathintegrator** [comment]
Same in 1.10.2 latest version (Forge 1.10.2-12.18.3.2316). All is fine, but cant put any fertilizer or same stuff from ic2.

**Comment by Nedelosk** [comment]
@cpufreak Probably you only have to delete the farm.cfg file.

**Comment by Deathintegrator** [comment]
cant find farm.cfg in mod folder. mb in 1.10 version it has other name?

**Comment by cpufreak** [comment]
Yes, that indeed fixed the issue, thanks!
