### ISSUE TITLE
Cascade Generation

### ISSUE THREAD

**Issue by TensorTime** [ForestryMC/ForestryMC#1716]
I recently updated to using the latest version on 1.11.2 (5.3.4.109) of forestry in my pack (admittedly a big pack).  I had almost all world cascade lag under control until I made this update.  Now forestry has become the #2 offender in the pack at appearing to cause cascade generation during testing.  I'm not sure what changed because I had zero problems from forestry in the past until I made this recent update (and I've been keeping current on alpha versions as they come out).

Let me know what I can provide to help out.  There isn't a crash log of any sort.  I just start a new creative world and fly around for a bit to see who's causing (or is being reported as) world gen chunk loading.  Prior to this update, in a new world, I had next to zero cascade, if not actually zero, from forestry. 

I'm looking at anything else that changed in the pack at that time.  You can find the pack on curse here:

https://minecraft.curseforge.com/projects/my-own-sink

I'll be looking closely at the CoFH mods that were just released to see if they are causing any of these issues (CoFH Core, Thermal Ex, Thermal Dyn, Thermal Found)

Thank you for reporting!

For issues:
 * Try the latest version, it may have fixed the issue already.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

**Comment by TensorTime** [comment]
I did try a fresh config with nothing but the latest 1.11.2 Forge (2315) and Forestry latest (109) and I still get cascade generation.  It seems to occur not everywhere,  but in specific forestry generated areas like a heavily roofed forest.   

No other mods are installed when this is occurs.  Let me know what other information I can provide.

**Comment by Nedelosk** [comment]
Thank you for reporting!
@TensorTime What are you mean with cascade generation ?

**Comment by TensorTime** [comment]
Worldgen Cascade log errors.  Meaning Forestry, at least apparently,  is causing minecraft to load chunks when they shouldn't be loaded yet,  generally because some decoration is overflowing outside the chunk border.  I believe it's mostly related to very dense forests where trees are probably clipping the edges of each chunk.

**Comment by TensorTime** [comment]
Lots of mods have had this issue in 1.11.2 and 1.12.  Not sure what changed but it's worse than it was back in 1.10.2.  Here is a reddit post from mezz talking about the issue.

https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/

**Comment by mezz** [comment]
Nedelosk, I looked into this and here's what I found:
The issue for Forestry here is complicated.
We spawn trees based on the tree decoration event. The coordinates given by this event are for vanilla trees, so if we spawn based on that we can easily go outside the correct bounds. We have no good way to know where to spawn based on the vanilla tree coordinate, so I think the event needs to be modified. Even if we spawn exactly where the vanilla tree would have gone, our trees can be wider and still spill outside.

**Comment by CovertJaguar** [comment]
@TensorTime its not worse. Forge just added a big fat warning about it in 1.11.

**Comment by TensorTime** [comment]
Thanks @CovertJaguar I learned about that earlier today when talking with the Galacticraft devs on a similar issue.

**Comment by Nedelosk** [comment]
@mezz What do you think we should do ?

**Comment by mezz** [comment]
We need a PR to Forge to give the tree decoration event the original chunk coordinates so we can generate the tree in a better spot.

**Comment by temp1011** [comment]
Now that forge has the necessary features I will start looking into fixing this.

**Comment by Nedelosk** [comment]
@temp1011 Any updates?
