### ISSUE TITLE
[1.11.2] Leaves not translate with waila

### ISSUE THREAD

**Issue by quienti** [ForestryMC/ForestryMC#1719]
Forestry 5.3.4.114
Waila 1.7.1

![2017-06-25_11 52 21](https://user-images.githubusercontent.com/7326954/27515812-a85da998-59ac-11e7-8e54-d8ddde1596b1.png)

**Comment by mezz** [comment]
Waila is not updated properly any more, please try one of its replacements instead:
Hwyla, The One Probe, Fruit Phone

**Comment by quienti** [comment]
Oh, Ok, I see. I will try this night and I will give you the result
Thanks !

**Comment by Nedelosk** [comment]
It works with The One Probe:
![2017-06-26_14 11 05](https://user-images.githubusercontent.com/10259214/27538651-5271145c-5a79-11e7-9304-4c66ca1ad553.png)
