### ISSUE TITLE
Link to wiki not working

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#1720]
The website forestryforminecraft throws a 'too many redirects' error.

**Comment by ktole1999** [comment]
what is the link?

**Comment by ghost** [comment]
Sorry, I was referring to the 'wiki' links in the menu and the text on the curseforge page linking to forestryforminecraft.info. But just now there appeared a message on that site stating it is no longer maintained.

**Comment by mezz** [comment]
I don't know why it's down, hopefully it is fixed soon.
Here is the link if you're curious: http://forestryforminecraft.info/

**Comment by xannor** [comment]
My guess is that whoever owns the domain does not want to pay to host it anymore. If that is the case could maybe the contents of that wiki be moved into the github system?

**Comment by ghost** [comment]
It seems the site is back up again; apparently someone else took over. I'll close this.

**Comment by Terpo** [comment]
I'm not sure why but my latest firefox always tries to set the connection to https where I get a SSL error:
 SSL_ERROR_RX_RECORD_TOO_LONG
Edge does not try to redirect me.

**Comment by mezz** [comment]
I get `ERR_SSL_PROTOCOL_ERROR`

**Comment by Nedelosk** [comment]
I close this issue, because the link does work again.
