### ISSUE TITLE
Greenhouse Camouflage Panelings craft with missing resources

### ISSUE THREAD

**Issue by davqvist** [ForestryMC/ForestryMC#1721]
Forestry 5.2.17.376 (I checked changelog for 377 but didn't see it there)
MC 1.10.2
Forge 2316

It's hard to explain, but someone crafted the Greenhouse Panelings but Lapis and Rose Red were missing, but the crafting in the Carpenter still continued to work without needing those resources.

You can see it in action here at around 2:49:55 https://www.twitch.tv/videos/154858189

**Comment by Nedelosk** [comment]
This is fixed in 1.11.2.

**Comment by davqvist** [comment]
Okay, thanks.

**Comment by Nedelosk** [comment]
Duplicate: #1545
