### ISSUE TITLE
[1.10.2] Forestry causing invalid hash code crashes with other mods.

### ISSUE THREAD

**Issue by brisingraerowing** [ForestryMC/ForestryMC#1722]
Ref: CoFH/Feedback#310 (Crash log there, I got the same error).

It appears Forestry for 1.10 is adding Ore Dictionary entries in the wrong place, causing a crash when hash codes of equal objects are not the same.

**Comment by KingLemming** [comment]
Ehh. Maybe put a "needs confirmation" up - I can't make it happen myself. All I know is that *some* combination of mods makes things screw up.

Something you do want to make sure of though is that you aren't doing ANY oredict registration in postInit.

**Comment by Nedelosk** [comment]
We only doing oredict registration in the preInit.

**Comment by mezz** [comment]
I have looked through this pretty carefully and I don't think this is a Forestry issue.
If more information comes up that says otherwise, please post it here and I can reopen the issue.
