### ISSUE TITLE
Compatability

### ISSUE THREAD

**Issue by bookerthegeek** [ForestryMC/ForestryMC#1725]
# Heyo # 
Hello! I come bearing requests for compatibility between your wonderful mod (Mainly the Farm) and some mods.
- [Rustic](https://github.com/the-realest-stu/Rustic)
  - [Fertile Soil](https://github.com/the-realest-stu/Rustic/wiki/Fertile-Soil): Farmland Substitute.
  - [Crop Stakes](https://github.com/the-realest-stu/Rustic/wiki/Crop-Stakes) Similar to Chopsticks, but still different.
  - [Grapes](https://github.com/the-realest-stu/Rustic/wiki/Grapes) 
  - [Tomatoes](https://github.com/the-realest-stu/Rustic/wiki/Tomatoes)
  - [Chili Peppers](https://github.com/the-realest-stu/Rustic/wiki/Chili-Peppers)
  - [Olives](https://github.com/the-realest-stu/Rustic/wiki/Olives): Similar to Pam's Fruit trees, but still differant. Olives are a leaf drop.
- [Roots](https://github.com/RootsTeam/Roots)
  - Moonglow
  - Aubergine
  - Terra Moss
- [Better With Mods](https://github.com/BeetoGuy/BetterWithMods)
  - Hemp
- [Botania](https://github.com/Vazkii/Botania)
  - Mystical Flowers (From when they are generated from a Jaded Amaranthus)
---
While the farm will harvest some if not all of these, it will not plant any of them. Thank you for considering my request.

**Comment by 3TUSK** [comment]
#1471 ?

**Comment by bookerthegeek** [comment]
Thank you, did not see that.
