### ISSUE TITLE
1.12 Fertalizer causing client crash

### ISSUE THREAD

**Issue by DingoX3** [ForestryMC/ForestryMC#1726]
Method: Find apatite craft into fertalizer. Use on anything ie: plants, grass, random block
Result: Crash to desktop
Tested on server and single player. Was able to recreate on both.

Full crash report: https://pastebin.com/t6MTZuat

minecraft version: 1.12
modpack ATM3
forestry version: 1.12-5.4.0.120
forge version: 2387

**Comment by mezz** [comment]
Thanks for the report!
Fixed here: https://github.com/ForestryMC/ForestryMC/commit/ddf90f4ee060097711599185782b096261e75de2
