### ISSUE TITLE
why is it doing this! (troll arboreum)

### ISSUE THREAD

**Issue by Chromogen** [ForestryMC/ForestryMC#1727]
so my dad just came in, watching me play with forestry and asks me why i plant hakenkreuz-pattern.
so i took a closer look and he was somewhat right.
your mod just trolled me hard! have a look!

![2017-06-30_22 51 18](https://user-images.githubusercontent.com/20258319/27753739-1db148a6-5de7-11e7-892d-45ab500844a0.png)

**Comment by mezz** [comment]
The farm plants things going in the other rotation, so you must be very unlucky!

**Comment by Chromogen** [comment]
oh well xD
