### ISSUE TITLE
1.12-Pulsating dust in creative trash slot

### ISSUE THREAD

**Issue by DingoX3** [ForestryMC/ForestryMC#1729]
Not a major issue since the trash slot can still be used but I noticed this here. 
<a href="http://imgur.com/P4lWSlK"><img src="http://i.imgur.com/P4lWSlK.png" title="source: imgur.com" /></a>
Thanks for squashing that fertalizer bug so fast. Keep up the awesome work you do 👍 

minecraft version: 1.12
modpack ATM3
forestry version: 1.12-5.4.0.120
forge version: 2387

**Comment by Darkhax** [comment]
This issue is caused by the creative tab leak. The items from Forestry are in every creative tab, and the trash slot because of this. More info about this bug on [reddit](https://www.reddit.com/r/feedthebeast/comments/6h9z7f/psa_the_creativetab_leak_glitch/?st=j4njd3my&sh=5717f3f1)

**Comment by mezz** [comment]
Thanks for the report!
Thanks darkhax, the creative tab issue https://github.com/ForestryMC/ForestryMC/issues/1723 has been resolved, so this should be too.
