### ISSUE TITLE
Forestry - Blocks all look the same when placed

### ISSUE THREAD

**Issue by BUNIWARRIOR** [ForestryMC/ForestryMC#1732]
Hi i am new to your mod but i LOVE it.  

I have just two little issues.  
1) I cannot grow "ebony" trees.
2) all of my planks look the same.  they look right in inventory, right in my hand but then when I place them they are all the same color. :(

See attached screenshot
![2017-07-03_10 16 17](https://user-images.githubusercontent.com/29869246/27802481-e04b7100-5fd8-11e7-91f4-20f73cd7da50.png)

I have Forestry 5.4.0.120, with 0 child mods.

I'm running a few other mods but I do not get any error messages.

Buni

**Comment by Nedelosk** [comment]
Thanks for the report!
Fixed in the next build.

**Comment by mezz** [comment]
To answer the Ebony question:
When you try to trees, make sure you have enough saplings placed down. 
Analyze the sapling to see if it requires a 2x2 or 3x3 pattern of saplings.

**Comment by BUNIWARRIOR** [comment]
thank you!
