### ISSUE TITLE
Villagers Overwritten

### ISSUE THREAD

**Issue by WindRider739** [ForestryMC/ForestryMC#1734]
All versions are up to date.

I use forestry because it's amazing and I love bee breeding.
I use Minecraft Comes Alive because it's also fantastic.

However, for some reason, MCA overwrites Forestry villagers.

Now, first I took this issue to the MCA devs, but he said 'Mod villagers are not replaced as long as they define their own unique profession IDs. If they don't I can't do anything about it unfortunately.'

I dunno what that means. I assume you do.

Is there any way to fix this currently? If not, is there any way to fix it in the future? Either way, keep up the good work.

**Comment by Nedelosk** [comment]
The MCA issue: https://github.com/WildBamaBoy/minecraft-comes-alive/issues/789

**Comment by WindRider739** [comment]
Is there a solution in there? That's the one I read already, and basically all I got from it was 'You can't have forestry villagers if you want to run MCA because forestry villagers don't have unique IDs'

**Comment by mezz** [comment]
Forestry registers its villager profession with the Forge villager registry. 
I'm not really sure what they are talking about.

**Comment by Nedelosk** [comment]
I have no idea what he means with unique IDs. Every registered village professionr has its own name.

**Comment by Nedelosk** [comment]
@mezz It seems like the author has deleted the github repository.

**Comment by mezz** [comment]
How weird. 
The last release was in 2016 so maybe they are done with it?

**Comment by Nedelosk** [comment]
I close this issue, because he not has updated the mod since 2016 and has deleted the repository.
