### ISSUE TITLE
Can't use Biones o'plenty saplings in farms [1.11.2]

### ISSUE THREAD

**Issue by krokots** [ForestryMC/ForestryMC#1735]
Some time ago it was possible to use BoP saplings, but now they can't be planted / placed in farms.
Using:
**forestry_1.11.2-5.3.4.119
BiomesOPlenty-1.11.2-6.2.0.2254-universal
1.11.2-forge1.11.2-13.20.1.2388**

full mod list:
ActuallyAdditions-1.11.2-r110.jar
AppleSkin-mc1.11-1.0.6.jar
bdlib-1.13.2.7-mc1.11.2.jar
BiblioCraft[v2.3.2][MC1.11.2].jar
BiblioWoods[BiomesOPlenty][v2.0][MC1.11.2].jar
BiblioWoods[Forestry][v2.0][MC1.11.2].jar
BiomesOPlenty-1.11.2-6.2.0.2254-universal.jar
buildcraft-7.99.4.jar
Chameleon-1.11.2-3.1.0.jar
CodeChickenLib-1.11.2-3.0.0.274-universal.jar
CoFHCore-1.11.2-4.2.5.11-universal.jar
compatlayer-1.11.2-0.2.9.jar
forestry_1.11.2-5.3.4.119.jar
gendustry-1.6.5.7-mc1.11.2.jar
ImmersiveEngineering-0.11-62.jar
ironchest-1.11.2-7.0.24.809.jar
jei_1.11.2-4.5.0.289.jar
morebees-1.11.2-1.4.1.jar
omlib-1.11.2-3.0.0-100.jar
ompd-1.10.2-3.0.0-22.jar
openmodularturrets-1.10.2-3.0.0-158.jar
OptiFine_1.11.2_HD_U_C2.jar
StorageDrawers-1.11.2-4.2.9.jar
StorageDrawersExtras-1.11.2-2.0.0.jar
ThermalDynamics-1.11.2-2.2.5.8-universal.jar
ThermalExpansion-1.11.2-5.2.5.13-universal.jar
ThermalFoundation-1.11.2-2.2.4.8-universal.jar

**Comment by Nedelosk** [comment]
This is not a bug. In 1.11.2 we have not re added the support for Biones o'Plenty.  I have planned to working on the farming support after I have finished the rewrite of the greenhouse. Duplicate: #1471
