### ISSUE TITLE
Question about retrogeneration

### ISSUE THREAD

**Issue by jcarrete5** [ForestryMC/ForestryMC#1736]
I have added the forestry mod to a previously generated world and I was hoping to be able to retrogen forestry ores and beehives. I enabled retrogen in the config, however, I cannot confirm that the retrogen is actually working. I went around my world looking for beehives and apatite to confirm that the retrogen was working and couldn't find any. Perhaps I was just unlucky. Is there any way I can confirm that new blocks are being retogenerated in my world without running around all over the place?

Thank you

## My config
```
retrogen {
  # Creates Forestry world generation in all chunks, even if they were generated there before. [default: false]
  B:forced=false

  # Creates Forestry world generation in chunks that were created before the mod was added. [default: false]
  B:normal=true
}
```

**Comment by mezz** [comment]
You should be able to just leave it true and they will be created as you walk around your existing world.
Beehives are relatively common, you should be able to find some.
If you walk a long way without finding any, the retrogen may not be working and we should fix it.

**Comment by jcarrete5** [comment]
Ok, I can confirm that the retrogen is working. I think I just didn't give it enough time and was looking in the wrong chunks. I was able to find bee hives and different kinds of forestry trees. I'll give it time and see if more things spawn.
