### ISSUE TITLE
Forestry Machine Recipes not Appearing in JEI

### ISSUE THREAD

**Issue by jdkorv11** [ForestryMC/ForestryMC#1738]
Forestry Machine recipes are missing and not appearing in JEI. They were present in version 1.11.2-5.3.4.99, but when I upgraded to version 1.11.2-5.3.4.119 the recipes are missing. 

When clicking on an item in recipe mode in the JEI menu, it fails to show any recipe for how to make items that require forestry machines (peat, crated items, etc.)

~~I will be checking to find out exactly which version they disappeared in and will update the issue when that is known.~~

After checking each version going back from 1.11.2-5.3.4.119 to 1.11.2-5.3.4.99 I found that the latest build where the recipes are working is 1.11.2-5.3.4.100. They disappear with the logs below in builds 1.11.2-5.3.4.101 through 1.11.2-5.3.4.119

JEI version: 1.11.2-4.3.4.282

Relevant log message that I'm seeing lots of for the carpenter, squeezer, fabricator, and centrifuge

[16:07:36] [Client thread/ERROR] [jei]: No recipe category registered for recipeCategoryUid: forestry.fabricator

Full Log:
[NoRecipes.txt](https://github.com/ForestryMC/ForestryMC/files/1134086/NoRecipes.txt)

**Comment by Nedelosk** [comment]
@jdkorv11 Have you updated JEI also ? You need at least 4.5.0.286.

**Comment by jdkorv11** [comment]
Could you let me know where to find that recent of a version? The latest I've found is 4.5.0.291 found at curse: https://minecraft.curseforge.com/projects/just-enough-items-jei/files

**Comment by jdkorv11** [comment]
Update: Upgrading to JEI 4.5.0.291 fixed the issue. Apologies for the false report.
