### ISSUE TITLE
[1.12] [Suggestion] Dimension Blacklisting/Whitelisting for Worldgen

### ISSUE THREAD

**Issue by SnowShock35** [ForestryMC/ForestryMC#1739]
Hello,

I have a small suggestion to make for Forestry for Minecraft 1.12. Here's more detail on the matter:

### Issue Information 

- Minecraft 1.12
- Minecraft Forge 14.21.1.2046
- Forestry 5.4.3.129

### Issue Description

Within the common Forestry configuration file located in `.minecraft/config/forestry/common.cfg`  there are some basic values that you can use to alter the world generation, specific to enabling/disabling and retrogen. However, this is rather limiting especially with the lack of any other world generation manipulation mods such as CoFH World (prev. CoFH Core). 

The feature I'd like to see for world generation configuration for Forestry is dimension blacklisting. This would allow me (the user) to remove tree/hive/ore generation from other dimensions where you might not want Forestry trees/hives to spawn. E.g. Aroma1997's Dimension Mod, RFTools Dimensions, etc. 

I feel it would be a great addition to Forestry and it would be great to see in the mod in the future.

Thanks for creating and maintaining such a brilliant mod for all these years. 
Regards,
SnowShock35.

**Comment by Krougal** [comment]
I can't say it any better, so +1

**Comment by temp1011** [comment]
I think this is now implemented, but comment if there's more that can be added.

**Comment by SnowShock35** [comment]
I believe it is.
You have hive, tree, structure and ore generation with blacklist/whitelist right?

**Comment by temp1011** [comment]
Ah no. No structures and only whitelist. I'll add some more stuff then.
