### ISSUE TITLE
[1.12] Cannot use config to stop beehive generation

### ISSUE THREAD

**Issue by E4002X3102** [ForestryMC/ForestryMC#1740]
Forestry 5.4.3.129
Forge 14.21.1.2406

To prevent beehive generation in my world (Hate having unpleasant surprises of bumping into beehives and aggressive bees when exploring and not ready to try beekeeping yet), I modified config>world>generate>beehives>Beehives Generation Amount to 0.0 from 1.0. As the tooltip states '[Minecraft Restart Required]', I then closed Minecraft and re-opened it, the value of Beehives Generation Amount is set to 1.0 again(before I entering/creating any world) and beehives still generate in the world.

**Comment by Nedelosk** [comment]
Thank you for reporting!
This is a bug with our gui config. Dublicate of #1686
