### ISSUE TITLE
[1.12] Only Quartz-Pillar Farm-Block are craftable

### ISSUE THREAD

**Issue by fampat** [ForestryMC/ForestryMC#1741]
UPDATE
This issue exists since **forestry_1.12-5.4.2.124**
Prior to that crafting farm-blocks works as expected

I do have a strange issue, iam using the latest forge (2406) and the latest Forestry (.129).
Iam only able to build Farm-Blocks from Quarzt-Pillars, no else recipe gets recognized in the crafting table and workbench (see screenshots).

Also every click (via jei) on any other farm block than the Quartz one results in the recipe placed for the quarzt one

Maybe it has something to do with the Quartz-Pillae be the last recipe in order and only the last one can be build? I dont know...

(also was able to reproduce this with only jei and forestry installed, just click a recipe in jei and it will always populate the quarzt one)

http://imgur.com/a/Vrvs6

**Comment by mezz** [comment]
Thanks for the report!
Recipes changed a bit in 1.12, we'll have to look in to it.

**Comment by DietmarKrause** [comment]
Same here in ATM3 pack (1.12). is there an ETA when this issue is resolved?

**Comment by mezz** [comment]
Fixed in the latest build, it'll be out in a few minutes.

**Comment by mezz** [comment]
Looks like there's an issue with Forge's servers right now so the Forestry build cannot complete.
I'll try to get this out tomorrow, assuming the servers are fixed by then.

**Comment by mezz** [comment]
Forge's server is working again, so I'm starting the Forestry build again and it should be available in a few minutes.
