### ISSUE TITLE
[1.12] Crash in JEI

### ISSUE THREAD

**Issue by sclark96** [ForestryMC/ForestryMC#1742]
Forge: 2405
Version: forestry_1.12-5.4.3.129

Cause: Searching @Forestry into JEI caused the game to crash

[Crashlog](https://gist.github.com/sclark96/f1af3ed8994b43a711e603a3aabc4467)

**Comment by mezz** [comment]
Thanks for the report!
Try updating codechicken lib, and if that doesn't work try removing it and the mods that need it.
I do not see this issue with just JEI and Forestry.

**Comment by Kris1432** [comment]
Will look into that and see what mod it is, big task at hand. CCL is up to date.

**Comment by mezz** [comment]
If you're on the latest CCL and still have an issue, try removing it to see if it is involved.

**Comment by Kris1432** [comment]
Yeah, we're on the latest CCL. Will do some testing this weekend, please keep this issue open for me.

**Comment by Kris1432** [comment]
we were unable to reproduce this crash with later versions, soooo
