### ISSUE TITLE
Proposal: add "royal larvae" as a bee type

### ISSUE THREAD

**Issue by rmunn** [ForestryMC/ForestryMC#1743]
This is to support https://github.com/ForestryMC/Binnie/issues/200; the rationale behind this proposal can be explained by reading that issue, so I won't duplicate it here since it's rather long. I'm creating an issue over here because implementing https://github.com/ForestryMC/Binnie/issues/200 would require a new bee type in Forestry, so it would be good to have an issue in the Forestry repo in order to track that idea.

Also, if this works out well for 1.7.10, it might be nice to make the same change for 1.10 / 1.11 / 1.12. But I'm limiting the scope of this proposal to 1.7.10 at the moment since that's what @KorDum is currently working on for https://github.com/ForestryMC/Binnie/issues/200.

**Comment by Nedelosk** [comment]
Same as https://github.com/ForestryMC/Binnie/issues/203 @rmunn @KorDum I am think this is a good idea. But not for 1.7.10. Forestry 1.7.10 is a final version and we only fixing major bugs of it and not adding any new features. We haven't changed anything on 1.7.10 since october 2016.
@mezz What do you thinking about adding this to 1.7.10 ?

**Comment by rmunn** [comment]
I'd like to see it on 1.7.10 because that's what I'm still using (I can't give up Thaumcraft). If it gets added only to 1.10 or higher, that will still be a nice new feature for many people, but I won't be able to test it and give feedback.

**Comment by mezz** [comment]
Sorry Forestry 1.7.10 is final, I'm reluctant to add new features even on the latest version.

**Comment by rmunn** [comment]
#1744 (and https://github.com/ForestryMC/ForestryAPI/pull/24) looks like a pretty small patch, so I don't think it would create *too* much work to bring it in. It's just adding a single enum value. But you have more experience with Minecraft modding than I do: would adding a new enum value, that has never before been used, be likely to break mods all over the place? Or would it be relatively safe, and small?

**Comment by mezz** [comment]
Binnie's is also not getting new features for 1.7.10 though.

**Comment by rmunn** [comment]
The reason I ask, of course, is because having a royal larva bee type is needed for the change I proposed in https://github.com/ForestryMC/Binnie/issues/200. But if the "no changes in Forestry 1.7.10" decision is final, I'll have to come up with another way to get what I asked for in https://github.com/ForestryMC/Binnie/issues/200. Maybe the inoculator could be changed to take non-larval princesses as well as larval drones, but that breaks the mod's "feel".

Or maybe the current EnumBeeType.LARVAE type could be forced into doing double duty somehow. Maybe the `generation` counter could be used to distinguish between drone larvae and princess larvae: drone larvae have generation 0, princess larvae have generation greater than 0. Yeah, that could work.

**Comment by Nedelosk** [comment]
@rmunn The thing is from the start on we have sayed that the 1.7.10 version of https://github.com/ForestryMC/Binnie will be only a version to fix bugs and not add new features.

**Comment by rmunn** [comment]
> Binnie's is also not getting new features for 1.7.10 though.

Ah. Too bad, I was hoping that Binnie's was still under active development (seeing a new `-pre##` release on CurseForge as of four days ago told me "mods are still working on this one), that it could acquire a new feature or two.

But if there's no way for me to get princess larvae in 1.7.10, then I'm going to have to go back to the old BinniePatcher mod to get Binnie's 1.8, rather than 2.0, into my current 1.7.10 world. Alas.

Thanks for the feedback.

**Comment by rmunn** [comment]
Any objection to this idea in principle? Or would this be okay on the 1.10 / 1.11 line of development? If so, I'll change the subject to remove the `1.7.10` tag and rework it to be a suggestion only for 1.10 / 1.11 / whatever (1.12 soon, I would imagine).

**Comment by Nedelosk** [comment]
@rmunn In 1.11/ 1.12 it would be okay

**Comment by rmunn** [comment]
I won't be able to test 1.11 / 1.12 (I only have so much time for Minecraft each day, and I'm putting that time into 1.7.10 at the moment), but I'd be happy to contribute ideas and/or suggested designs for the code if that's desired. I really do like the revised designs for the Genetics side of Binnie's -- it feels really realistic and fun, with dying DNA sequences and using polymerising bacteria and all -- so I want to help enable it to gene-splice princesses as well as drones. So I'm happy to help with ideas, even if I won't be able to help test.

**Comment by Nedelosk** [comment]
In forestry 1.14.4 a feature will be added to add custom species types. I think the best idea is to move larvae later to Binnie 1.14.4 and add the royal larvae too on the Binnie side. Because they both have no function on the forestry side
