### ISSUE TITLE
Forestry tried to generate a hive in unloaded area

### ISSUE THREAD

**Issue by KristjanKr** [ForestryMC/ForestryMC#1751]
Thank you for reporting!

For issues:
 * Try the latest version, it may have fixed the issue already.
Using latest forestry for 1.11.2:  forestry_1.11.2-5.3.4.135.jar
Forge: build 2414
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.
No crash but spams log and really makes game slow af, log is here:
https://gist.github.com/KristjanKr/a5315fa114bf9db1ee6478265175ff69 or from paste.ee:
https://paste.ee/p/Bxlni

**Comment by mezz** [comment]
Thanks for the report!
This seems like it may be related to Mystcraft, does it happen without that mod?

**Comment by superninjakiwi** [comment]
It's caused by Mystcraft; a bugfix is likely to be forthcoming soon. https://github.com/XCompWiz/Mystcraft-Issues/issues/182
