### ISSUE TITLE
In 1.12 could be farm blocks made only from the Pillar Quartz block.

### ISSUE THREAD

**Issue by bocceli** [ForestryMC/ForestryMC#1756]
In 1.12 could be farm blocks made only from the Pillar Quartz block.
I'm using the lastest 1.12 build.
Thanks :)

**Comment by Obbi89** [comment]
Duplicate with #1741?
Wasn't that fixed in 73db1a608a7c03651b0f782a2294c66606d9d675

**Comment by Nedelosk** [comment]
Duplicate:  #1741
