### ISSUE TITLE
Thermionic Fabricator visual bug.

### ISSUE THREAD

**Issue by gefailter** [ForestryMC/ForestryMC#1758]
Forestry version: 1.12-5.4.3.134
Forge version: 2413

It is still functioning but doesn't have a texture. 
![](https://puu.sh/wNv7n/394972eb6d.jpg)

**Comment by mezz** [comment]
![2017-07-19_22 27 53](https://user-images.githubusercontent.com/916092/28401858-99bc10ae-6cd1-11e7-8977-bae9890be4d1.png)

It looks normal to me, please make a backup and try removing some mods to see if there is something else causing the issue.

**Comment by Nedelosk** [comment]
Closed due to no response.
