### ISSUE TITLE
Crash caused by new farm block [1.12]

### ISSUE THREAD

**Issue by sstroud** [ForestryMC/ForestryMC#1759]
With the new fix to farm blocks, I created and tried to place a stone block-farm block, which caused a crash before the block would show. I try to reload the world, I see the block missing from my inventory, then it crashes. Here is a link to the crash report: https://gist.github.com/sstroud/87449ec872a2ae11d650aa730aa895bb

**Comment by mezz** [comment]
Thanks for the report!
Please try without optifine connected textures, I think it is causing the crash here.

**Comment by sstroud** [comment]
That was it. Thanks!
