### ISSUE TITLE
[1.12][5.4.3.134] Bee Hives Spawning in SuperFlat Worlds

### ISSUE THREAD

**Issue by Kris1432** [ForestryMC/ForestryMC#1760]
Forge: 2405
Version: 5.4.3.134

Generate Structures is off, but the Bee Hives Spawn regardless.

Picture: https://puu.sh/wNNUh.png

**Comment by mezz** [comment]
Thanks for the report!
How does vanilla handle this, does grass ever grow on superflat?
Maybe hives should just avoid generating in superflat worlds.

**Comment by Kris1432** [comment]
No, grass doesn't spawn either, nothing should be in the world on the SuperFlat world type, don't worry, there are a few other mods doing this.

**Comment by SandGrainOne** [comment]
These are the world generator options related to features.
http://minecraft.gamepedia.com/Superflat#Structure_generation_options
Not sure which one or combination the Bee hives should be related to.

**Comment by KnightMiner** [comment]
`decoration` causes grass to generate, should be tied to that probably.

**Comment by Obbi89** [comment]
Yeah using decoration fixes that issue
