### ISSUE TITLE
Forestry always causes ID Mismatching

### ISSUE THREAD

**Issue by OldDogy** [ForestryMC/ForestryMC#1763]
Hello,

 I know this is a bit out there, but every modpack, and every world on every server I played hosted and administrated, since 1.10.2, One way or another gets corrupted for no reason, and it's always only forestry that gets affected.

This time after a 3rd/4th random crash on AllTheMods 3, which had nothing to do with forestry.. When the server came back up all Forestry ID's have been shuffled around.

http://prntscr.com/fxznq7

Dunno what else to say.
If you have any specific questions about it just shoot.
Cheers !

**Comment by Nedelosk** [comment]
Duplicate: #1543
