### ISSUE TITLE
[1.12][5.4.3.134] Too big Charcoal pit (i made minecraft cry with your mod)

### ISSUE THREAD

**Issue by FridgeBoy** [ForestryMC/ForestryMC#1764]
Forge 2405
https://pastebin.com/1tqZechM

I made a big charcoal pit 14x14x~30 all contained in a single chunk, which in itself causes a lot of lag as it seems the multiblock gets reformed everytime a new block is blased on/in it.

after lighting the pit it took a couple ticks before it crashed, upon reboot and rejoining you are faced with a see through multi block (sorry no picture) and a few ticks later it crashes again. 
After repaeating this 3 or 4 times the server calmed down again and didn't crash when rejoining as -i guess- a certain amount of the wood piles were already converted to charcoal

**Comment by Nedelosk** [comment]
Duplicate: #1543

**Comment by Nedelosk** [comment]
Fixed in 5.5.5.188.
