### ISSUE TITLE
[1.10.2] No Database?

### ISSUE THREAD

**Issue by ProStashio** [ForestryMC/ForestryMC#1769]
Hello there,

I am using the 1.10.2 "All The Mods!" modpack & for some reason I can't find the Apiarist's Database. Was this removed? Thanks.

**Comment by Nedelosk** [comment]
@ProStashio The Apiarist's Database isn't from forestry it's from extra bees. And extra bees isn't out for 1.10.2 yet, but we are working on it.

**Comment by ProStashio** [comment]
Do you have an idea of when it will be? Many thanks.

**Comment by Nedelosk** [comment]
Most likely soon, but not for 1.10, only for 1.11.2.

**Comment by ProStashio** [comment]
You just said you were working on it for 1.10? That's a shame, a lot of good modpacks on 1.10, not so many for 1.11.

**Comment by Nedelosk** [comment]
Currently we are working on the 1.11.2 version, but I don't know if we are porting it back to 1.10.2. Possibly if we have a stable 1.11.2 version.

**Comment by ProStashio** [comment]
I know my word doesn't mean much, but a lot of people would be grateful if you could. A lot of us are running 1.10 these days :-)
