### ISSUE TITLE
issues installing forestry

### ISSUE THREAD

**Issue by Lady92** [ForestryMC/ForestryMC#1770]
Hey,

I installed forestry 1.11.2 and it's been rejected by my server i don't have a crash report but it's saying it's an fml mod rejection when I tried to see if the mod would work. Is there a way to fix this? Or am i being dumb and missing a file??? Any help is great thanks :)

**Comment by Obbi89** [comment]
Do you have your client log?

It should be in the logs folder next to the mods folder.

**Comment by Nedelosk** [comment]
I am closing this, because of no response.
