### ISSUE TITLE
[1.12][forestry_1.12-5.4.3.144] Fertilizer/Multifarm fix

### ISSUE THREAD

**Issue by 4Brooker** [ForestryMC/ForestryMC#1771]
Currently, the multifarm doesn't work. But this is easily fixable with a quick edit.

Go to your .minecraft - config - forestry and go in the farm.cfg with an editing tool.
Change forestry:fertilizerCompound;500 to forestry:fertilizer_Compound;500 and your farms should be working.

I found out that this problem does not occur for everyone. But if you can't place fertilizer in the Multifarm, this is a fix. You could probably also delete your config folder, so it probably makes it correctly again.

Good luck with farming.

**Comment by xenxero1** [comment]
Uhm, Can you reopen this? Its still an issue that needs to be resolved and requires dev attention.

**Comment by Nedelosk** [comment]
@xenxero1 This was fixed in the in the last version. https://github.com/ForestryMC/ForestryMC/commit/62d6294da239f00e40353db79e2ac3245ee07c0f
