### ISSUE TITLE
crash if forestry.factory=false

### ISSUE THREAD

**Issue by IngmarBitter** [ForestryMC/ForestryMC#1772]
I'm trying to bake a **minimal [plugins.cfg](https://pastebin.com/ySLnxH8r)** that has **only backpacks. butterflies and the worktable**. This config file is the closest I can get to that without crashing. If I add forestry.factory=false then forestry [crashes](https://pastebin.com/ekn12HUY).
To reproduce run the Atlantica-Next mod pack v1.20 from technic launcher with forestry_1.12-5.4.3.146.jar added to the mods directory and this [plugins.cfg](https://pastebin.com/WfjEz3Qq).
Please fix.

In addition it would be great to have more options it that config file so I can really get just backpacks. butterflies and the worktable.

Thanks!

**Comment by IngmarBitter** [comment]
The comment above sounds pretty promising. I assume the fix will be applied to the next update on minecraft.curseforge.com? I'll be happy to test it once updated there.

**Comment by mezz** [comment]
Yes, we generate builds automatically so if the issue is closed here it should be up on Curse about 10 minutes later or so.

**Comment by IngmarBitter** [comment]
I confirm the crash is fixed.
Thanks for the quick resolution! 👍 

forestry.storage=true adds a lot though, could it be replaced by two options so I can do
forestry.backpacks=true
forestry.crates=false
?
I suppose I need to start a new feature request for this ?

**Comment by mezz** [comment]
Yeah please open a new issue, requesting that. It's easier to keep track that way.

**Comment by IngmarBitter** [comment]
done
