### ISSUE TITLE
Fermenter Does not accept Forestry trees that have been crossbred

### ISSUE THREAD

**Issue by thefrasca** [ForestryMC/ForestryMC#1774]
I have crossbred a blue mahoe to have apples and grow faster, but the fermenter only accepts the base blue mahoe.  Once any change to the traits takes place, it is no longer accepted.

This applies to other tree types too, I have tested with Apple Oak, Blue Mahoe, and Plum

This is minecraft 1.11.2

**Comment by Nedelosk** [comment]
@thefrasca Which forestry version do you use ?

**Comment by thefrasca** [comment]
1.11.2-5.3.2.58

**Comment by thefrasca** [comment]
This appears to be fixed in the newest version.  Closing this issue
