### ISSUE TITLE
[1.10.2] Crash when placing engines

### ISSUE THREAD

**Issue by jacky8399** [ForestryMC/ForestryMC#1776]
https://gist.github.com/jacky8399/45dd6d74324fadb03823b31c4b437623

For some reason, Forestry invokes on a method that doesn't exist in RF API when placing engines.

**Comment by Nedelosk** [comment]
@jacky8399 This is not a forestry bug. The CoFH API of railcraft is outdated. The CoFH API of railcraft has the owner "CoFHAPI". But since the version 1.4 of the cofh api the name of the api owner is "cofhapi".
@CovertJaguar I have opened a issue: https://github.com/Railcraft/Railcraft/issues/1292
