### ISSUE TITLE
backpacks. butterflies and the worktable

### ISSUE THREAD

**Issue by IngmarBitter** [ForestryMC/ForestryMC#1779]
Hi,

the mod pack I'm helping to test has some other mods that have overlapping features. 
However, your **backpacks. butterflies and the worktable** are unique.
We would like to add just those (and new blocks needed to make them).
Could you please add a configuration option for that?
(_Butterflies_ is already there, but turning on _Storage_ brings in a lot of other blocks.)

Thanks!

**Comment by mezz** [comment]
I think this is a good request.

~~@SirSengir can I split off the worktable into its own mini mod?~~

The rest of this can be solved by splitting the storage module into "backpacks" and "crates" modules. They have no real crossover so it shouldn't be too hard.

**Comment by mezz** [comment]
Actually scratch that, it would probably confuse people if the worktable was missing from Forestry, it has been there for ages.
Let's just break up the modules more.

**Comment by Nedelosk** [comment]
The backpacks and the worktable have now each there own module.
