### ISSUE TITLE
Bees not producing their specialty regardless of correct temperature / humidity

### ISSUE THREAD

**Issue by OfficerLovejoy** [ForestryMC/ForestryMC#1783]
Forestry Version 1.10.2-5.2.17.379 (current Age of Engineering pack)
I can't figure out why this is not working:
![image](https://user-images.githubusercontent.com/5771746/28849496-882b1a7e-7717-11e7-9956-ce0fe1113618.png)

I've let this setup run for around 50 cycles and still not one emerald shard...
Is it me or is this intentional?
I have had the same issue with an older forestry version on ftb-beyond, so i guess i am doing something wrong.

**Comment by mezz** [comment]
I'm not sure why that's happening. When you check it in an analyzer does it show the emerald comb as a specialty? Maybe something is wrong with the % drops.
Try reporting it to the mod that adds the Emerald Queen in 1.10.2, it's actually not from basic Forestry.

**Comment by OfficerLovejoy** [comment]
I found the solution on the MoreBees github:
the bees require a specific block directly underneath (or in case of the wither bee: on top) the apiary / alveary.
In my case i just needed to place an emerald block under my alveary and everything worked perfectly.

I also found the wiki on the MoreBees page, where you can check out which bees need which block under it:
https://github.com/Lach01298/MoreBees/wiki/Bee-Species#wither-1

Thank you for your help sir, i would not have been looking for the MoreBees github if you had not pointed out, that this bee is not originally from forestry.
