### ISSUE TITLE
Feature request. 

### ISSUE THREAD

**Issue by warplord** [ForestryMC/ForestryMC#1784]
![2017-08-03_00 50 33](https://user-images.githubusercontent.com/2938930/28896697-297b4542-77e6-11e7-8fc9-4d9d947ce8de.png)

Look at that beauty. My humble request is that a legit way is added for that amazing tree to be obtainable. It is definitely pretty awesome.

**Comment by MauveCloud** [comment]
What makes you so sure it isn't already legitimately obtainable?  Last I knew Giant Sequoia saplings had a chance of appearing as high-tier trades from Arborist villagers.  Was that broken in a recent update?

**Comment by warplord** [comment]
Well, JEI has a villager trading integration, so when u check for example the coastal sequoia sappling - it has a chance to be sold by villagers or bred with tree breeding. When u click "recipe" on the giant one - nothing shows up. No villager trades, no dungeon chest drops, no breeding possiblity - nothing.

**Comment by MauveCloud** [comment]
JEI has no documentation of such a feature.  Are you sure that isn't from some addon to JEI?

Anyway, I'd be surprised if the Forestry devs accept that as sufficient evidence that the villager trading is broken.  I can think of some alternative explanations:
1. a bug in the JEI addon preventing it from showing properly
2. the JEI addon might only show low-tier villager trades - if converted vanilla saplings are counted as breeding tier 0, Coast Sequoia is only breeding tier 3, so it might be available as a tier-1 villager trade.  Does this villager trading integration show other high-tier trades like name tags and bottles o' enchanting (from vanilla Minecraft)?  You could also check for villager trading 
3. Forestry might do something (intentionally or not) to cause this trade to be hidden from the addon - there have been "secret" recipes in some mods, so the addon might be trying to honor that.

A more reliable proof that it's broken would be to actually spawn a lot of Arborist villagers, unlock their highest-tier trades until you've gotten the rest of the tree species at least 5 times each, either as a sapling or as pollen.  If you still have no trades for Giant Sequoia by then, it will be reasonable to claim that it is unobtainable.

**Comment by warplord** [comment]
Well, if a dev can confirm or deny if it is obtainable - would be best. I would still like to have it in the survival game. It is an awesome tree.

**Comment by Obbi89** [comment]
As stated by others they are obtainable by Villagers.
You have about 1/30 chance of getting it.
Beware that you will have to level the villager about 3 times to be able get the rare items.

So all in all it is a very rare item that cannot be obtained otherwise.
