### ISSUE TITLE
Forestry doesn't work with Agricraft.

### ISSUE THREAD

**Issue by CircuitCM** [ForestryMC/ForestryMC#1785]
I've tried the orchard for my Agricraft plants, and all the other manual options. I don't know if I still might be missing something obvious, but it seems like Agricraft doesn't work with the orchard like it used to.

**Comment by CodesCubesAndCrashes** [comment]
Which version of Minecraft was this? I'm looking at this from the AgriCraft side.

**Comment by Nedelosk** [comment]
Closed because of no response
