### ISSUE TITLE
[1.11.2] Silk touch on axe gives wrong wood

### ISSUE THREAD

**Issue by Flyrija** [ForestryMC/ForestryMC#1787]
I'm using the latest 1.11.2 build, tested also with version x.119 and x.155

It was driving me insane. Everytime I chopped down a forestry tree, it dropped the wrong wood. I could reproduce it easy after my husband noticed that I have silk touch on my axe. I crafted a new axe without and everything worked as it should. I haven't found more forestry trees in my world so I don't know how it is with the other trees. 

Just a few examples:
Lime Tree -> Larch Wood
Cherry Tree -> Lime Wood
Maple Tree -> Pine Wood
Citrus Tree -> Pine Wood

**Comment by mezz** [comment]
Thanks for the report!
Fixed in the next build.
