### ISSUE TITLE
[1.12] Ender Hives no longer generate in the End

### ISSUE THREAD

**Issue by tommyTT** [ForestryMC/ForestryMC#1789]
At the moment the hives in the end are not spawning anymore. I enabled the debug mode and while the overworld generates correctly, there are absolutely no ender hives in the End. Going back to version 5.4.3.137 generates the hives in the End, but the next version 5.4.3.144 doesn't, therefore it must be related to #1766.

Minecraft: 1.12
Forge: 14.21.1.244
Mods:
  forestry_1.12-5.5.0.154
  jei_1.12-4.7.5.84

**Comment by Obbi89** [comment]
Yes indeed that is a bug I introduced.
If you use the retro gen you should see hives in the end.
I will create a quick fix for that issue.
