### ISSUE TITLE
Forestry emitting errors about item-requests from third party mods?

### ISSUE THREAD

**Issue by sibomots** [ForestryMC/ForestryMC#1790]
Interresting messages in server log on startup.
Unclear if the message is originating from Forestry or is an outcome of some mis-configuration.

Looks like the error emits  from Forestry (but could be simply a mistake on the part of other mods interacting with Forestry.  Your comments welcome on that regard.)

https://github.com/ForestryMC/ForestryMC/blob/73db1a608a7c03651b0f782a2294c66606d9d675/src/main/java/forestry/core/utils/IMCUtil.java

EDIT:  That message  spurned on by this check:
```
			IBackpackDefinition backpackDefinition = BackpackManager.backpackInterface.getBackpackDefinition(backpackUid);
			if (backpackDefinition == null) {
				String errorMessage = IMCUtil.getInvalidIMCMessageText(message);
				Log.error("{} For non-existent backpack {}.", errorMessage, backpackUid);
				return true;
			}
```
Server version: forge-1.11.2-13.20.1.2429
Multiplayer
Mods involved:
**forestry_1.11.2-5.3.4.132.jar**
terraqueous-1.11.0-1.3.14.jar
immersivepetroleum-1.11.2-1.0.7.jar

Selected entries here: [gist](https://gist.github.com/sibomots/0c90c748759f84d4b241de42cfdcb971)

Two samples:
```
[15:15:49] [Server thread/ERROR] [forestry/forestry]: Received an invalid 'add-backpack-items' request 'forester@immersiveengineering:seed' from mod 'immersiveengineering'. Please contact the author and report this issue. For non-existent backpack forester.
[15:15:49] [Server thread/ERROR] [forestry/forestry]: Received an invalid 'add-backpack-items' request 'digger@terraqueous:earth_ore:0' from mod 'terraqueous'. Please contact the author and report this issue. For non-existent backpack digger.
```

**Comment by mezz** [comment]
Other mods send requests to Forestry to add items to the backpacks.
These two mods are trying to add items to backpacks that don't exist, so Forestry logs an error.
I think that the names of the backpacks was changed a while back, so they just need to update the name in their request.
