### ISSUE TITLE
Water Bees Not Dropping (1.12)

### ISSUE THREAD

**Issue by AtollaBell** [ForestryMC/ForestryMC#1791]
I recently installed Forestry and Binnie's Mods on Forge for MC 1.12. I came across three different Water Hives - in shallow water, in various biomes - and two of them dropped Valiant princesses/drones, while the third dropped Forest bees. I would have chalked it up to it being just a shallow water glitch except the forest bees dropped in the middle of a swamp biome.

**Comment by mezz** [comment]
Thanks for the report!
This has been reported to Binnie's and fixed: https://github.com/ForestryMC/Binnie/issues/259
