### ISSUE TITLE
Forestry wood planks can not craft crafting bench or sticks or preaty much any vanilla reciept

### ISSUE THREAD

**Issue by Ramog** [ForestryMC/ForestryMC#1792]
I can't craft sticks or crafting tables in the latest version of forestry for minecraft 1.12 its version 5.5.0.154.
But the funny thing is that I can smelt it and use it as fuel source.

**Comment by Nedelosk** [comment]
This is a forge bug in 1.12. I have opened a pull request https://github.com/MinecraftForge/MinecraftForge/pull/4310.
