### ISSUE TITLE
[1.10.2] 64x64x17 green house crashes players,

### ISSUE THREAD

**Issue by DaemosDaen** [ForestryMC/ForestryMC#1793]
I do not know if this was fixed for the 1.11 or 1.12 versions, but in the DW20 pack, we build a 64x64x17 Green House, with a later of dirt and some lights in the greenhouse. After it was completed (most likely) the players in the area were crashed out of the game with the error "io.netty.handler.codec.DecoderException: Badly compressed packet - size of 3382809 is larger than protocol maximum of 2097152"

Logs are available here: https://1drv.ms/u/s!AlpZQdyrEQxIhMQepRrEjkBEBzPucg

**Comment by EnderiumSmith** [comment]
the problem with arbitrary size multiblocks is that sooner or later someone will build one larger that the game can handle

why would you think building a multiblock 16 chunks big was a good idea? how did you even craft 12500 blocks?

just divide it into smaller ones

my guess is that this would be too hard to fix for little to no benefit. am i right?

**Comment by Nedelosk** [comment]
Fixed in 1.12.
