### ISSUE TITLE
1.12.1 jei recipy crash foresty crates

### ISSUE THREAD

**Issue by tyler489** [ForestryMC/ForestryMC#1809]
Thank you for reporting!

For issues:
 * Try the latest version, it may have fixed the issue already.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.
forestry_1.12-5.5.0.161.jar
Crash when viewing forestry recipys (carpender)
https://pastebin.com/6BMF0X0e

**Comment by tyler489** [comment]
Duplicate?

**Comment by mezz** [comment]
Sorry I got mixed up with the JEI issue.

**Comment by Nedelosk** [comment]
Duplicate of #1598
