### ISSUE TITLE
Crash when looking at a multifarm block

### ISSUE THREAD

**Issue by Tmtravlr** [ForestryMC/ForestryMC#1810]
Hey, I'm glad you fixed the crash when looking at the crate recipes in jei, but sadly I found another one. It happened when I placed down a multifarm block on a server I'm playing on (just my client crashes, not the server). I also crash whenever I try to log back in, probably because I'm still looking at the block.

Forestry Version: 
1.12-5.5.0.169

Minecraft Version: 
1.12

Forge Version: 
14.21.1.2420

Steps to Duplicate:
- Place down a quartz multifarm block (it may happen with other types too).
- Look at it so it tries to render.

Crash Report:
https://gist.github.com/Tmtravlr/be379bca08c6efcf817d0a225ee03fcc

**Comment by mezz** [comment]
Thanks for the report!
I think this is caused by Optifine Connected Textures, can you try disabling them?

**Comment by Tmtravlr** [comment]
Ah, that would make sense, since I have a connected texture for quartz blocks in my resource pack.

Yep, turning connected textures off fixed the crash. Thanks! I hope you can find a way to fix it. I do love my connected textures. =)

**Comment by mezz** [comment]
I looked into it a bit but I'm not really sure what Optifine is doing.
Please report the bug to them here, I think they will have a better idea: https://github.com/sp614x/optifine/issues

**Comment by Thorf13** [comment]
I reported a similar issue to Optifine here:

https://github.com/sp614x/optifine/issues/907

sp614x replied with the following:

> Forestry crashes here: https://github.com/ForestryMC/ForestryMC/blob/mc-1.12/src/main/java/forestry/core/tiles/TileUtil.java#L54
> 
> The original crash is identical, but the CodeChicken library crashes.
> 
> The problem is outside of OptiFine and it can't be fixed by OptiFine.

Does this help at all? My crash report is posted at the link above in case it helps.
