### ISSUE TITLE
[1.12.1] When a sapling is removed by water or a piston it doesn't drop the item

### ISSUE THREAD

**Issue by DehFelix** [ForestryMC/ForestryMC#1813]
When a forestry sapling is removed by water or a piston, the item won't drop, unlikely vanila saplings.

- Minecraft : 1.12.1
- Forge : 14.22.0.2456
- Forestry :1.12-5.5.0.169

**Comment by MauveCloud** [comment]
This could be deliberate for all I know.  I've been using 4.2.16.64 (for MC 1.7.10), so I checked with that build, and it happens there too, so it is apparently not new behavior.

**Comment by DehFelix** [comment]
Yeah, now that you mentioned I remember trying something similar in a older version. It could be a technical limitation.

**Comment by mezz** [comment]
Seems like an oversight. I would never think to handle this case in a special way, maybe Minecraft has some special logic for it.

**Comment by Flyrija** [comment]
I noticed this too using forestry 1.11.2-5.3.4.155 version. Saplings accidently plated in water just dissappear.
