### ISSUE TITLE
[1.12/1.12.1] Crash when using the Greenhouse block

### ISSUE THREAD

**Issue by NovaViper** [ForestryMC/ForestryMC#1814]
When I try to place the Greenhouse block for the butterflies, the game instantly crashes with the following log at the bottom

Version: 5.5.0.169 beta build
Crash log: https://gist.github.com/NovaViper/82c2d5167d88b9fa1f0a5d28c3a8702d

**Comment by Nedelosk** [comment]
Fixed with 5.5.5.188.
