### ISSUE TITLE
Forestry Multi Farm turns vanilla birch into silver birch.

### ISSUE THREAD

**Issue by llloyd4** [ForestryMC/ForestryMC#1815]
So, on Minecraft 1.12, using the FTB Unstable 1.12 mod pack, I built a Forestry multi block farm, exported in vanilla birch saplings and it transmuted those into silver birch saplings, when I mouse over the planted saplings OneProbe reports them as silver birch and the saplings I am getting back are silver birch.

**Comment by MauveCloud** [comment]
That behavior has existed for a while, and used to be one of the few ways to obtain the starting Forestry saplings for breeding purposes.  I think worldgen Forestry trees were added sometime recently, making that somewhat less important.  However, what's so bad about them being converted to silver birch saplings?

**Comment by llloyd4** [comment]
Not saying it's bad, it works out, just it's unusual behavior. Every other tree farm, when there were other tree farms (In 1.12 there is no MFR or Ender IO *yet*) gives you what you put in, it doesn't transmute the saplings by, apparently, magic like gold from lead. >.<

**Comment by mezz** [comment]
I agree this is not really expected, and can be changed now.
