### ISSUE TITLE
[1.12] Items Copy Bug with Thermal Foundation mod

### ISSUE THREAD

**Issue by Flithor** [ForestryMC/ForestryMC#1820]
If you craft advanced materials of TF mod with canned liquid, the rest of items will be copied.
Specific operation:
1. Prepare multiple canned liquid and stack them.
2. Put other materials(multiple each) in craft GUI.
3. Put one canned liquid in craft GUI.
![ScreenShot](http://imgur.com/ZoYdYKB.png)
(All similar recipes will trigger this bug)
4. Stack the rest canned liquid in craft GUI.
![ScreenShot](http://imgur.com/8BtlOEe.png)
5. Craft!!
6. The rest of materials doubled!
![ScreenShot](http://imgur.com/IJrgxSH.png)
![ScreenShot](http://imgur.com/dFZdUr8.png)

Pls fix it soon!
========================================
(Due to this bug, I almost want to delete this world archive.)

And in these recipes, the can will be consumed (not return empty can). But these recipes should only consume liquid.
(Maybe a bug?)

**Comment by mezz** [comment]
Thanks for the report!
I tried it out and this looks like a bug with CoFH Core's liquid-accepting recipes.
Please report it to them here: https://github.com/CoFH/Feedback/issues
