### ISSUE TITLE
Alveary Stabilizer/Bee House Question

### ISSUE THREAD

**Issue by jjc54** [ForestryMC/ForestryMC#1822]
As I understand it, both of these blocks are supposed to stop any new species from appearing. So for instance if you breed Common and forest (which yields cultivated), you will never see cultivated pop up.  I assumed that one of them would make the princess retain its species trait while allowing all others traits to change but that is not the case. Are both of these blocks doing the same thing or is there something different about them?

**Comment by mezz** [comment]
That's correct, both the Alveary Stabilizer and Bee House stop all species mutations, but the genetics are still combined like normal. Their effect on species mutations is identical.

Like any place bees can live, the Bee House has other effects on lifespan, flowering, genetic decay, and production. 
Generally an Alveary is a superior place for bees, and the Alveary Stabilizer only affects mutation.

**Comment by jjc54** [comment]
Ah ok that makes sense. Thanks for the help!
