### ISSUE TITLE
[1.6.4][Question]Double princess chance in agrarian skies difficulty

### ISSUE THREAD

**Issue by skull1** [ForestryMC/ForestryMC#1823]
Im interested about the exact % chance of get a second princess on the Agrarian Skies 1 pack with AGSKSKIES difficulty, i would like to reproduce it on the 1.7.10+ version, but im afraid to make it too much easier or too much difficult if i dont know that chance(in my opinion it was perfect).

**Comment by mezz** [comment]
Unfortunately we don't have the source for Forestry going that far back, but by some random chance I have an old instance of Agrarian Skies 1 on my computer.

Looking at it with a decompiler, I see logic for spawning princesses that is unique to the `forestry-A-2.3.1.2-agskies.jar` version:
```java
int count = 1 + ((this.housing.getWorld().field_73012_v.nextInt(100) < 5) ? 1 : 0);
```
This translates to a 5% chance of spawning a second princess.
