### ISSUE TITLE
Placing Log pile deletes blocks sometimes

### ISSUE THREAD

**Issue by davqvist** [ForestryMC/ForestryMC#1825]
Forestry 5.5.0.175
MC 1.12.1
Forge 2460

When I place a log pile on some blocks, sometimes instead of placing them above the block, the log pile replaces the block and the "floor" block gets deleted. I haven't found a pattern when it happens, but it is definitely reproducible. You can try Brick Stairs for example.

As this is hard to replicate, I tested this on stream, this took quite a while, but I showed it to Hellfire later as you can see starting from 4:52:10 https://www.twitch.tv/videos/169003744

**Comment by Nedelosk** [comment]
Thank you for reporting!

**Comment by mezz** [comment]
Thanks for the report!
I was not able to reproduce this issue with just Forestry. I tried recreating your setup but nothing bad happened.
Maybe there was a desync and the stairs were not really placed on the server? It's hard to tell what's happening exactly.  I checked and the logic for placing wood piles is the same as any vanilla block.

**Comment by davqvist** [comment]
So, the short clip was just showing it to Hellfire. I discovered it way earlier where I heavily tested, starting from around 3:35:50. But what I noticed that it happened to Loam and Dirt also, so it seems maybe not Forestry related, but I wonder what would cause that. I mean a desync is possible, but still seems weird. I guess I have to test a bit more.

**Comment by davqvist** [comment]
Okay, I did more investigating and it seems that this happens with blocks from other mods as well and I have already a suspicion which mod is responsible for this. So, seems not caused by Forestry, sorry for the wrong alert.
