### ISSUE TITLE
Breaking Charcoal Block drops itself and single Charcoal

### ISSUE THREAD

**Issue by davqvist** [ForestryMC/ForestryMC#1826]
Forestry 5.5.0.175
MC 1.12.1
Forge 2460

I'm not 100% sure this is a bug, but after using the Charcoal pit, breaking the Charcoal blocks, it drops both the block and the items. I assume the block shouldn't drop as I get around the amount of Charcoal items that I am supposed to, already.

**Comment by Nedelosk** [comment]
Duplicate of #1767
