### ISSUE TITLE
Multifarm

### ISSUE THREAD

**Issue by nkendera** [ForestryMC/ForestryMC#1831]
Trees chopped down from farm used to auto break all the leaves, but after update leaves aren't broken but despawn naturally, which prohibits other trees from growing. Is this intentional?

**Comment by mezz** [comment]
As far as I can remember, Forestry farms have not chopped down the leaves, so it is intentional.
However there are many solutions to leaves, you can try a Munchdew from Botania, a Leaf-Eating Generator from Actually Additions, or just a mod like Fast Leaf Decay.
