### ISSUE TITLE
Forestry Trade station owner protection?

### ISSUE THREAD

**Issue by Akitori** [ForestryMC/ForestryMC#1832]
Heya, so I wanted to ask if trade stations are normally supposed to be edited by other players, or if that's a bug?

I want to make custom 'creative' trade stations for players to trade daily coins to, but with my testing other players can edit the trades/steal the coins. Not really concerned as i can embed them in bedrock/barriers, but i wanted to know if this was intentional.

**Comment by mezz** [comment]
The permissions system in Forestry was intentionally removed because it was pretty complicated and custom. I think it's better to use bedrock or use mods that are specialized in protecting block access.
