### ISSUE TITLE
[1.12.1][5.5.0.178] Item in players hand gets deleted by farm

### ISSUE THREAD

**Issue by freund17** [ForestryMC/ForestryMC#1833]
I came along the following bug:
When the farm places saplings, the itemstack in the players main hand gets deleted.

Steps to reproduce:
1. Build a working farm
2. Supply the farm with power, fertilizer, dirt, ... the usual stuff...
3. Watch it placing down the humus
4. Hold an item / itemstack in your main hand
5. Watch it disappear once the farm places saplings

I'm on minecraft version 1.12.1, using forge 14.22.0.2463 and forestry 5.5.0.178.
This was reproduced with Forestry as the only mod installed.

**Comment by mezz** [comment]
Thanks for the report!
That's a strange bug, I'll take a look.

**Comment by freund17** [comment]
What was the problem?

**Comment by mezz** [comment]
The farm used the player to plant saplings, instead of a fake player. This worked before in older versions, and got around some permissions mod issues, but in this Minecraft version it causes issues. Now the farm will always plant by using a fake player that has the credentials of the real player.

**Comment by freund17** [comment]
Ah, ok. Thanks!
