### ISSUE TITLE
Bees not attacking hostile mobs [1.12-1-5.5.0.180]

### ISSUE THREAD

**Issue by ArashiDragon** [ForestryMC/ForestryMC#1835]
Tested while near a hive, lured hostile mobs to hive, even attacked hive until I got stung, but hive never attacked hostile mobs even when hostile mobs were standing on TOP of the hive.

**Comment by mezz** [comment]
I tested this with skeletons and spiders, and the bees sting them occasionally as expected.
Bees do not attack pigmen or endermen, they are not aggressive without the player doing something.
They also do not attack at night, when they are inactive in their hives.

**Comment by ArashiDragon** [comment]
Never even thought about it being night... Oops... *hugs*
