### ISSUE TITLE
[1.12.1] multi-farm blocks invisible in JEI/causing crash

### ISSUE THREAD

**Issue by Rictu5** [ForestryMC/ForestryMC#1836]
The multi farm blocks from forestry aren't appearing in my JEI anymore.
But the farm still exist in world, calling the recipe from one of the blocks crash the game.

![2017-09-02_15 00 19](https://user-images.githubusercontent.com/31549317/29995693-088c841e-8ff0-11e7-80b1-b8b7832c2636.png)

**Forestry** : forestry_1.12.1-5.5.0.181
**JEI** : jei_1.12-4.7.5.85
**Forge** : 1.12 - 14.21.1.2443
**Crash log :** https://gist.github.com/Rictu5/e35cee9cb87cf3d4488cb87b792be1cd

**edit** : tried with the last Forge version (1.12.1 - 14.22.0.2467) and got the same issue.

**Comment by mezz** [comment]
Thanks for the report!
You need to update to the latest version of JEI.
I will update Forestry so that it shows an error message when you do not have the new required version of JEI.
