### ISSUE TITLE
[1.10.2] Farm control block not working

### ISSUE THREAD

**Issue by jzburda** [ForestryMC/ForestryMC#1837]
Modpack: Underdone minecraft 1.10.2 (Custom)'
Version: 5.2.17.376
Issue: Farm control block will not toggle farm even when planting
Applying a redstone signal (Using EnderIO redstone conduits) to a farm control block will not turn off the multifarm. this includes planting and harvesting of trees.

**Comment by Nedelosk** [comment]
Duplicate of #1494
