### ISSUE TITLE
[Suggestion] Make IHiveFrame's getBeeModifier() ItemStack aware

### ISSUE THREAD

**Issue by rwtema** [ForestryMC/ForestryMC#1838]
I've got a idea for a configurable frame, however the bee housing only get's the frame's modifiers through the item alone. I propose, adding an ItemStack aware method to IHiveFrame i.e. getBeeModifier(ItemStack), with a default implementation to call the pre-existing method which should be deprecated.

**Comment by mezz** [comment]
Sure thing, that wont be hard to do.

**Comment by mezz** [comment]
Implemented in version 5.5.1
