### ISSUE TITLE
Server Crash 1.11.2

### ISSUE THREAD

**Issue by SybilGlendevon** [ForestryMC/ForestryMC#1839]
Hey There, 
Just had a crash regarding the butterflies and Animania. Just an FYI

https://gist.github.com/SybilGlendevon/84cbf10100fdc3255d42c4e2d3331e3c

**Comment by mezz** [comment]
Thanks for the report!
This looks like an issue on their side, please report this to animania here: https://github.com/capnkirok/animania/issues

**Comment by mezz** [comment]
This crash has been reported here: https://github.com/capnkirok/animania/issues/313
