### ISSUE TITLE
Newb needing some clarification and possible bug

### ISSUE THREAD

**Issue by gojessi** [ForestryMC/ForestryMC#1841]
Thank you for reporting!

For issues:
 * Try the latest version, it may have fixed the issue already.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

**Comment by gojessi** [comment]
So, I don't really know what I am doing, but trying to understand this forestry mod, which apparently needs several other mods in order to do and build everything, like the capenter machine? (frustrating and totally confused by all this and need some help or a complete how to guide)

But a major problem or big is that none of the forestry recipes are showing up in my recipe book!!! Do I have to download a diff mod for that? Or are recipes located somewhere else? When I look up recipe on internet, I can manually place items into crafting block and make only some of the items, and then it says "new recipe discovered" but does not add it to my recipe book... Need some help with this. Thanks. Using 1.12.1 version on a Mac computer. Thanks.

**Comment by mezz** [comment]
Hello,

Forestry is not compatible with the vanilla recipe book yet.
Mods on 1.12 use JEI to view recipes, you can [download it here](https://mods.curse.com/mc-mods/minecraft/238222-just-enough-items-jei).

Forestry is an old and very big mod, it may not be the simplest one to start with.
The [Forestry wiki here](https://forestryforminecraft.info/) has some good information to get you started.

There are also mod packs that have guide books which help you learn about mods, including Forestry.
They take a long time for people to put together though, so I don't think there are any mod packs with a guide book for 1.12 yet.

**Comment by gojessi** [comment]
Thanks for the quick reply! I am continuing to find out just how complex
the forestry mod is as I continue to read more and more about it. My
husband bought mindcraft for my 7yr old daughter, but she kept asking me
how to do certain things in it and I knew nothing about it, so I decided to
play it so I could help her when she had questions... Big mistake. I was
hooked! I love it! Then I learned about mods! I had no idea the forestry
mod was so complex, or I would have waited to download it. It seems like it
needs a lot of other mods in order to work fully, which is a bit
disappointing. There is no comparable version of the Buildcraft mod for
minecraft version 1.12.1 that I have been able to find. The biggest thing I
have been struggling with, is building the carpenter machine. Which I
finally achieved, but now I have no way of making an engine for it that I
can find... I hope the JEI you included for a recipe book will help. ( I
feel like I am SO behind the times on this game and have only scratched the
surface of its potential!)

Btw, do you know if there is a mod for building a giant ship to sail with
or a motorboat instead of the little rowboat?

Thank you again for your reply and for the info!

-Jessica

On Sep 6, 2017 10:38 PM, "mezz" <notifications@github.com> wrote:

Hello,

Forestry is not compatible with the vanilla recipe book yet.
Mods on 1.12 use JEI to view recipes, you can download it here
<https://mods.curse.com/mc-mods/minecraft/238222-just-enough-items-jei>.

Forestry is an old and very big mod, it may not be the simplest one to
start with.
The Forestry wiki here <https://forestryforminecraft.info/> has some good
information to get you started.

There are also mod packs that have guide books which help you learn about
mods, including Forestry.
They take a long time for people to put together though, so I don't think
there are any mod packs with a guide book for 1.12 yet.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ForestryMC/ForestryMC/issues/1841#issuecomment-327674908>,
or mute the thread

**Comment by mezz** [comment]
Forestry has a few engines of its own, you can search "`@forestry engine`" to see them in JEI.
It's unfortunate that Buildcraft hasn't updated yet. It is being completely rewritten and taking a long time.

There are some mods that let you build giant ships that move. They can be buggy but it's still fun.
https://mods.curse.com/mc-mods/minecraft/228029-davincis-vessels

There used to be a mod with better boats for 1.7.10, but I don't know of one on the latest 1.12 version.

You will probably get better help finding mods on reddit, it has a fairly large modded minecraft community here: https://www.reddit.com/r/feedthebeast/

**Comment by gojessi** [comment]
Thank you sooo much! I'm excited to try things out after the kids leave for
school tomorrow!!!

Thanks again!

-Jessica

**Comment by gojessi** [comment]
Thank you SO MUCH for the link to the JEI mod!!!! I'm still learning how to
use everything, but playing today was way smoother.

Just a question. I am having issues with my chests disappearing, or rather,
becoming invisible at times... When I mouse over them, there is the thin
black outline of the chest, and then I click on it and it opens and becomes
visible again. I have several mods installed and I can only assume it is a
glitch from one of them? Any way to find and fix the issue without
uninstalling some of the mods?

Thanks!
-Jessica

**Comment by mezz** [comment]
I'm the author of JEI, so you just happened to stumble into the right place :)

Unfortunately glitches like that can be hard to track down. The best solution is usually to make a backup copy of your minecraft folder and then start removing handfuls of mods until it's fixed, then report the bug to the mod author on Github.
