### ISSUE TITLE
IBeekeepingLogic references non-api stuff

### ISSUE THREAD

**Issue by bdew** [ForestryMC/ForestryMC#1845]
API interface IBeekeepingLogic is referencing stuff in forestry.core package.

https://github.com/ForestryMC/ForestryMC/blob/mc-1.12/src/main/java/forestry/api/apiculture/IBeekeepingLogic.java#L13-L14

This is causing scalac errors (which i think is less forgiving of missing classes than javac) when using only the API jar.

Any chance that IStreamable / PacketBufferForestry could be moved to the API package or those methods referencing them removed from API?

**Comment by mezz** [comment]
Oops, I messed that up pretty badly.
Will find a fix asap.

**Comment by mezz** [comment]
Fixed in Forestry 5.5.3
