### ISSUE TITLE
CTD when running with Rustic

### ISSUE THREAD

**Issue by Nargath** [ForestryMC/ForestryMC#1846]
MC Version: 1.12.1
Forge Version: 14.22.0.2474
Rustic Version: 0.4.1
Forestry Version: 5.5.5.188

When loading the game from the launcher, I get the attached error log:
https://gist.github.com/Nargath/6a758e9db711faa47df682dd1b9c2bd3

I've reproduced this reliably, and with only Forestry and Rustic in the mods folder

**Comment by Nargath** [comment]
Disabling the new Rustic integration in the config does not stop this crashing

**Comment by Nedelosk** [comment]
This is a Rustic bug. https://github.com/the-realest-stu/Rustic/issues/81

**Comment by viveleroi** [comment]
The issue you've linked was filed by the same OP. Is this actually a bug on their end? It only started for me after updating Forestry to 1.12.1-5.5.5.188.

**Comment by Nedelosk** [comment]
With 5.5.5.188 I have added ore dictionary support to the fermanter. And that breaks the forestry compat of rustic. There is nothing that we can do to fix this. It a bug on their end.

**Comment by Nargath** [comment]
Thanks for that more in depth update on what the issue is Nedelosk :)
I'll report that to the Rustic dev and see what comes of it!
