### ISSUE TITLE
1.12.1 Forestry Crash Server

### ISSUE THREAD

**Issue by ststeppat** [ForestryMC/ForestryMC#1851]
After reboot the world crashes

https://gist.github.com/ststeppat/3f731ac1c2d92904619dfd566c2836ac

I deactivate the greenhouse function in plugins.cfg and the server load his world
 Adds a greenhouse.
 B:forestry.greenhouse=false

**Comment by Nedelosk** [comment]
Thank you for reporting!
Can you please paste the crash report to gist and link it here?

**Comment by ststeppat** [comment]
thank you for reading the report, possible a Conflict with Mod Futurepack ?

https://gist.github.com/ststeppat/a2be228f7956ec90dac0bec038a1bf01

**Comment by Nedelosk** [comment]
@ststeppat Why do you think this crash is caused by forestry ? The crash is caused by the CoFH Core mod.
```
java.lang.Error
	at cofh.core.command.CommandHandler.<clinit>(CommandHandler.java:36)
```

**Comment by ststeppat** [comment]
Ok, but when i disabled the greenhouse function of forestry, it works. It load the world with no conflict.
I report this Problem to CoFH , to.

**Comment by Nedelosk** [comment]
@ststeppat If it loads if you disabled the greenhouse plugin than it should be a forestry bug. 
@KingLemming Any idea what could cause this ?

**Comment by KingLemming** [comment]
Not a clue. I looked over the code, and that's basically not a real error. The game literally can't crash on that line or anywhere near it unless something else is making it crash and we're getting caught in the log somehow.
