### ISSUE TITLE
 Couldn't find resource table forestry:chests/village_naturalist

### ISSUE THREAD

**Issue by Gromyown** [ForestryMC/ForestryMC#1857]
Thank you for reporting!

For issues:
 * Try the latest version, it may have fixed the issue already.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

**Comment by UnPure** [comment]
Because @Gromyown has given almost no imformations, here are a few more things.

The problem he is talking about is a log entry that comes while the client/server is starting.

    [10:43:30] [Server thread/WARN]: Couldn't find resource table forestry:chests/village_naturalist

**Forestry:** 5.5.6.197
**Forge:** 14.22.0.2475

If you need more informations, just tell me!
