### ISSUE TITLE
[1.12.*][5.6.0.200] java.lang.IllegalArgumentException: ItemStack must be for default leaves

### ISSUE THREAD

**Issue by Alaberti** [ForestryMC/ForestryMC#1865]
Crash: https://pastebin.com/eeGjzyiw

I'm not really sure what's happening, but it looks like some of my players are getting ahold of some leaves that aren't rendering? It's causing them to crash to desktop infinitely.

Forestry: 5.6.0.200
MC: 1.12.2
Forge: 14.23.0.2503

**Comment by Nedelosk** [comment]
Same issue like https://github.com/ForestryMC/Binnie/issues/322.

**Comment by Alaberti** [comment]
Might be relevant, but I did want to add that this issue was occurring in a Caverns mod dimension with no trees in it.

**Comment by Nedelosk** [comment]
Fixed with binnie-mods version 2.4.0.79.
