### ISSUE TITLE
Debugging - MC-1.12.2 Forge 509 - Block State Interaction Issues With Pokecube and Forestry

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ForestryMC/ForestryMC#1866]
@Thutmose can explain XD

**Comment by Thutmose** [comment]
It seems that the getDrops for the leaves doesn't account for the passed IBlockAccess being anything other than a World.

https://github.com/ForestryMC/ForestryMC/blob/mc-1.12/src/main/java/forestry/arboriculture/blocks/BlockAbstractLeaves.java#L198

here you cast the handed IBlockAccess as a world, and during some methods I pass in either a ChunkCache, or a custom implementation of IBlockAccess (which extends neither World nor ChunkCache), so it throws a ClassCastException. 

Luckily in this case, where it is thrown doesn't cause any significant issues, but I can see it causing more issues later if something else calls it elsewhere.
