### ISSUE TITLE
java.lang.NoSuchMethodError: forestry.apiculture.genetics.alleles.AlleleBeeSpecies

### ISSUE THREAD

**Issue by Pennywisier** [ForestryMC/ForestryMC#1867]
Crash report: https://pastebin.com/1JyegQij

The game crashed upon loading the mods. 

Forestry: 5.6.0.200
Forge MC: 1.12.2 14.23.0.2512

*p.s. I don't know how to word this any better. Hope the crash report helps.

**Comment by Nedelosk** [comment]
You have to update binnies mod.

**Comment by Pennywisier** [comment]
Ah I see. I was pretty sure that I've updated the relevant mods. But I forgotten about binnie's. Thanks for that and sorry to bug you.
