### ISSUE TITLE
Issue: Analyzer block requires power

### ISSUE THREAD

**Issue by NosajDraw** [ForestryMC/ForestryMC#1881]
From the wiki https://forestryforminecraft.info/breeding:analyzer

The analyzer does not require power to operate but instead needs to be filled with liquid honey. 

However, the block erroneously (I assume) does actually require power.

**Comment by Syncaidius** [comment]
There was a time when it didn't require power, but I always wondered how it analyzed things out of thin air.

In my opinion, it makes more sense to consume power, but maybe a config option can be added to disable the power requirement for those that prefer the old way?

**Comment by NosajDraw** [comment]
So the fix to disparity between the wiki and code is to continue the disparity?

The analyser may well now have "better" code for handling power, but that does nothing to resolve this issue.

**Comment by temp1011** [comment]
You can now change how much power the analyzer uses in the config as a response to syncaidius's comment. The wiki is still wrong but shouldn't be too difficult to edit. You can re-open the issue to get that done.

**Comment by temp1011** [comment]
If I understood where I could create an account on the wiki I would get this done but that would only be the start given how outdated a lot of the wiki is. Maybe it's better to focus efforts  on the ingame manual Nedelosk was looking at...

**Comment by temp1011** [comment]
The analyzer block has an entry in the new manual here https://github.com/ForestryMC/Forestry-Localization/blob/f3a9713e1f71aea6254401381c025206871f8ae8/assets/forestry/manual/en_us/core/analyzer.json. If the power usage needs to be made clearer I suggest editing that.

**Comment by Nedelosk** [comment]
We currently have no access to the wiki, so there is no way for us to change the text.
