### ISSUE TITLE
Can walk into at an angle Peat-Bog Engine and take suffocation damage

### ISSUE THREAD

**Issue by KAfable** [ForestryMC/ForestryMC#1883]
Forge 2517
Forestry 5.6.0.201

If a peat bog is at eye-level with my character (so one block above the ground, I can walk into the pointier end of the engine from an angle and take damage, similar to how I can walk into Mekanism tanks at an angle and take damage.

**Comment by Nedelosk** [comment]
This should be fixed in version 5.7.
