### ISSUE TITLE
Tin can / wax capsule cannot pick up fluid blocks in world

### ISSUE THREAD

**Issue by 3TUSK** [ForestryMC/ForestryMC#1884]
Test with:
* MinecraftForge 14.23.0.2528
* Forestry 5.6.0.201
* Water, Lava, Honey, Biomass, Ethanol, Molten Glass. None of them can be picked up by Forestry tin can. Nor could was capsule.

According to https://ftb.gamepedia.com/Can and https://ftb.gamepedia.com/Wax_Capsule, I consider this as a bug. It may affect older versions, but I don't really get time to do validation.

**Comment by mezz** [comment]
I think I disabled this intentionally because it is very overpowered compared to buckets. I don't remember when I did it though.

**Comment by 3TUSK** [comment]
https://github.com/ForestryMC/ForestryMC/commit/7bd5bb120d2b7ff6cb3bffb5e1d2eff01d393151?

**Comment by mezz** [comment]
Probably that, yeah. 
In a 1.8.9 server I remember filling up a whole stack of cans very rapidly and thinking it was way too easy compared to buckets.

**Comment by 3TUSK** [comment]
Might left this as a configurable option, default to be unable to pick up fluid block?

**Comment by forestbat** [comment]
I don't think tin can can't pick up fluid in the world is a good idea。We need “better buckets” than vanilla to collect liquid——anyway，we can't always use bumps and pipes。

**Comment by SinusoidalC** [comment]
Maybe cans and capsules only collect fluids by Bottling Machine is more balance in most of modpacks. But if there's a modpack with out pipes or pumps, only forestry? That could make cans useless. So I thought that make a configurable option for cans and capsules pick fluid in world can be a good idea.
