### ISSUE TITLE
Crash with newest version

### ISSUE THREAD

**Issue by TimGoll** [ForestryMC/ForestryMC#1885]
Latest version, 1.12.2, crashes on startup. (Doesn't crash without forestry) Here's the crashreport:

https://gist.github.com/TimGoll/59ec4f3d651e3d17ef917be4bc133f80

**Comment by Nedelosk** [comment]
I made some big changes in the newest forestry version 5.7. Seems like Zetta-Industries depents on internal forestry classes that I have renamed in the newest version. Ther is nothing I can do to fix this. They have to fix it. Can you please create a issue at the [repository](https://github.com/marcin212/Zetta-Industries) of Zetta-Industries ?

**Comment by TimGoll** [comment]
Okay. I'll report it to them

**Comment by Nedelosk** [comment]
Thank you
