### ISSUE TITLE
Issue with EleCore - forestry_1.12.2-5.7.0.209

### ISSUE THREAD

**Issue by Deylendor** [ForestryMC/ForestryMC#1886]
Seems version 209 has some problems with EleCore, a rendering library for DeepResonance.

https://gist.github.com/Deylendor/7530c6d4fabcd5aad85e0d6b40060e9a

**Comment by mezz** [comment]
Thanks for the report!
This has been reported to ElecCore here: https://github.com/Elecs-Mods/ElecCore/issues/122
