### ISSUE TITLE
Forestry/Elec Core compatibility issue.

### ISSUE THREAD

**Issue by border999** [ForestryMC/ForestryMC#1887]
I'm having a problem where having both Forestry and ElecCore in my modpack is causing a crash before the game even fully starts up.
I'll link you the crash report, but I'm not sure how much you'll be able to do with it.
https://gist.github.com/border999/510fb8aca2b241367aede96a94dece02

**Comment by mezz** [comment]
Thanks for the report!
This has been reported to ElecCore here: https://github.com/Elecs-Mods/ElecCore/issues/122
