### ISSUE TITLE
Crash on world loading.

### ISSUE THREAD

**Issue by FusionLord** [ForestryMC/ForestryMC#1888]
Crash on world loading with electric engines.

ServerLog: https://gist.github.com/FusionLord/c59d9ac7bdf477056f7d1d5a52b3768a

Minecraft: 1.10.2
Forge: 12.18.3.2511
Forestry: 5.2.17.388

**Comment by temp1011** [comment]
I know this was a long time ago but was it a recent update? Crash is really weird and I think it might be because ash blocks got remapped.

**Comment by Nedelosk** [comment]
This is probably caused by #1543
