### ISSUE TITLE
Update ru_RU.lang

### ISSUE THREAD

**Issue by SawFowl** [ForestryMC/ForestryMC#1889]
I partially updated the Russian translation for mod. https://gist.github.com/Mr-Krab/d30320c95eb0eaecc135136fc623d700

Soon I will also translate the last two parts.
In the language files there are not enough names for several subjects (capsules, cans and other small things).

**Comment by 3TUSK** [comment]
https://github.com/ForestryMC/Forestry-Localization welcomes you.
