### ISSUE TITLE
[1.11.2] Greenhouse stop working after unload chunk

### ISSUE THREAD

**Issue by KorDum** [ForestryMC/ForestryMC#1891]
I build Greenhouse and it's worked. But after chunk unloaded (I think the problem is this) — not working.
Climate Control don't change climate.
Apiary threw the climate into a biome's climate.

![image](https://user-images.githubusercontent.com/1331559/32698427-bdf5bf52-c7b6-11e7-9d38-d481fe000f9c.png)

![image](https://user-images.githubusercontent.com/1331559/32698429-c3acfae6-c7b6-11e7-9087-34eef3ca8a4b.png)

**Comment by KorDum** [comment]
The background of the fields in the interface moves after the cursor =)

**Comment by KorDum** [comment]
After load, unload and load chunk - all working perfectly. I don't know how reproduce bug by steps.

**Comment by KorDum** [comment]
...not worked again after unload chunk and no energy.

**Comment by Amelia-** [comment]
I'm running into the same problem with the version for Minecraft 1.10.2. (Forestry version 5.2.17.388)
In my case the GUI displays the temperature and humidity as both 79% but the apiaries in the greenhouse display them as 20% and 30% which I think is the normal climate for the biome it is in (Extreme Hills).

Changing the climate settings for the greenhouse doesn't seem to matter and yes I know I have to click in the other text box to make them apply. It does however depending on the settings I set, visibly turn the heater, fan, dryer or sprinkler on and off.

Breaking a block of the multi block structure doesn't seem to do anything to the climate either. After restoring the multiblock structure it still has the same climate according to the greenhouse GUI. Whenever I did this yesterday when the greenhouse was still working the climate would rapidly adjust to the biome's climate.

I understand if you don't fix problems for this old 1.10.2 version anymore. I would already be happy if I could find a workaround or a way to reset the greenhouse without rebuilding it completely. Perhaps know which block is responsible for the state of the greenhouse? I already tried breaking the climate control block but that didn't help.

I'll keep experimenting with it and report if I find a way.

**Comment by Amelia-** [comment]
Restarting the server restored the greenhouse.

I have not found what block is the control block if it even works like that. I have tried breaking and replacing the greenhouse control block, climate control block, and the bottom center block.

I remember with Railcraft multiblock structures like the tanks it used to be the bottom center block. You could break any block other than that one and the tank would keep it's contents. Do the Forestry multiblock structures work in the same way and if so which block do I have to break to reset it?
