### ISSUE TITLE
[1.12.2][build 212] Electrical Engine Not Accepting IC2 EU

### ISSUE THREAD

**Issue by Syncaidius** [ForestryMC/ForestryMC#1893]
As of the current build on Jenkins, the electrical engine no longer accepts any form of power from IndustrialCraft 2.

Cables are unable to connect to it:.
![image](https://user-images.githubusercontent.com/2464215/32724111-f2480d30-c867-11e7-888b-6a9c415bacb9.png)

It also refuses to drain batteries:
![image](https://user-images.githubusercontent.com/2464215/32724122-ff2de8bc-c867-11e7-9509-940dd7117031.png)

Edit: Build 201 doesn't have this problem. We use a lot of IC2/forestry in our base so we've reverted temporarily.

**Comment by 3TUSK** [comment]
Can confirm with Forestry 5.7.0.210 and IC2exp 2.8.24-ex112. The error message on the left reads "No electricity in the world (install IndustrialCraft<sup>2</sup>)".

**Comment by tobast** [comment]
To elaborate on that, it works with build 201, and breaks in build 204 (the next 1.12.2 passed build), which corresponds respectively to commits (incl.) ee272de and e9ae149.

At a glance, the most likely breaking point is 88fd031f, but there's no way I can dive into a `277 files changed, 7356 insertions(+), 1925 deletions(-)` commit out of the blue :) I'd have been glad to help.

**Comment by mezz** [comment]
@Nedelosk this seems to be caused by the module refactor, can you take a look?
