### ISSUE TITLE
Recipe Error.  Books and wood = pile of wood.

### ISSUE THREAD

**Issue by madhatr** [ForestryMC/ForestryMC#1895]
Here is a pic, https://imgur.com/a/3XJCg

3 books anywhere and 4 logs.  You must have 4 logs.   

forestry_1.12.2-5.7.0.212
forge-1.12.2-14.23.0.2538-universal

**Comment by mezz** [comment]
Thanks for the report!
This turned out to be a vanilla issue, reported and fixed here: https://github.com/MinecraftForge/MinecraftForge/issues/4557
