### ISSUE TITLE
[1.7.10] Crash on startup cpw.mods.fml.common.LoaderException

### ISSUE THREAD

**Issue by Feptoid** [ForestryMC/ForestryMC#1897]
21.11 21:53:52 [Server] INFO cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraftforge/event/FuelBurnTimeEvent
21.11 21:53:52 [Server] INFO at cpw.mods.fml.common.LoadController.transition(LoadController.java:163) ~[LoadController.class:1.7.10-1614.57]
21.11 21:53:52 [Server] INFO at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559) ~[Loader.class:1.7.10-1614.57]
21.11 21:53:52 [Server] INFO at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88) ~[FMLServerHandler.class:1.7.10-1614.57]
21.11 21:53:52 [Server] INFO at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:319) ~[FMLCommonHandler.class:1.7.10-1614.57]
21.11 21:53:52 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:176) ~[lt.class:?]
21.11 21:53:52 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
21.11 21:53:52 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
21.11 21:53:52 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/event/FuelBurnTimeEvent
21.11 21:53:52 [Server] INFO at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_111]
21.11 21:53:52 [Server] INFO at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_111]
21.11 21:53:52 [Server] INFO at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[?:1.8.0_111]
21.11 21:53:52 [Server] INFO at java.lang.Class.getMethods(Class.java:1615) ~[?:1.8.0_111]
21.11 21:53:52 [Server] INFO at cpw.mods.fml.common.eventhandler.EventBus.register(EventBus.java:60) ~[EventBus.class:1.7.10-1614.57]
21.11 21:53:52 [Server] INFO at forestry.plugins.PluginArboriculture.preInit(PluginArboriculture.java:128) ~[PluginArboriculture.class:?]
21.11 21:53:52 [Server] INFO at forestry.plugins.PluginManager.runPreInit(PluginManager.java:282) ~[PluginManager.class:?]
21.11 21:53:52 [Server] INFO at forestry.Forestry.preInit(Forestry.java:101) ~[Forestry.class:?]
21.11 21:53:52 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
21.11 21:53:52 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
21.11 21:53:52 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
21.11 21:53:52 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
21.11 21:53:52 [Server] INFO at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:1.7.10-1614.57]
21.11 21:53:52 [Server] INFO at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
21.11 21:53:52 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
21.11 21:53:52 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
21.11 21:53:52 [Server] INFO at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]
21.11 21:53:52 [Server] INFO at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[server-1.7.10.jar:?]
21.11 21:53:52 [Server] INFO at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[server-1.7.10.jar:?]
21.11 21:53:52 [Server] INFO at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[server-1.7.10.jar:?]
21.11 21:53:52 [Server] INFO at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[server-1.7.10.jar:?]
21.11 21:53:52 [Server] INFO at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:1.7.10-1614.57]
21.11 21:53:52 [Server] INFO at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:1.7.10-1614.57]
21.11 21:53:52 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
21.11 21:53:52 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
21.11 21:53:52 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
21.11 21:53:52 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
21.11 21:53:52 [Server] INFO at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]
21.11 21:53:52 [Server] INFO at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[server-1.7.10.jar:?]
21.11 21:53:52 [Server] INFO at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[server-1.7.10.jar:?]
21.11 21:53:52 [Server] INFO at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[server-1.7.10.jar:?]
21.11 21:53:52 [Server] INFO at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[server-1.7.10.jar:?]
21.11 21:53:52 [Server] INFO at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) ~[LoadController.class:1.7.10-1614.57]
21.11 21:53:52 [Server] INFO at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556) ~[Loader.class:1.7.10-1614.57]
21.11 21:53:52 [Server] INFO ... 5 more
21.11 21:53:52 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.minecraftforge.event.FuelBurnTimeEvent
21.11 21:53:52 [Server] INFO at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
21.11 21:53:52 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_111]
21.11 21:53:52 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_111]
21.11 21:53:52 [Server] INFO at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_111]
21.11 21:53:52 [Server] INFO at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_111]
21.11 21:53:52 [Server] INFO at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[?:1.8.0_111]
21.11 21:53:52 [Server] INFO at java.lang.Class.getMethods(Class.java:1615) ~[?:1.8.0_111]
21.11 21:53:52 [Server] INFO at cpw.mods.fml.common.eventhandler.EventBus.register(EventBus.java:60) ~[EventBus.class:1.7.10-1614.57]
21.11 21:53:52 [Server] INFO at forestry.plugins.PluginArboriculture.preInit(PluginArboriculture.java:128) ~[PluginArboriculture.class:?]
21.11 21:53:52 [Server] INFO at forestry.plugins.PluginManager.runPreInit(PluginManager.java:282) ~[PluginManager.class:?]
21.11 21:53:52 [Server] INFO at forestry.Forestry.preInit(Forestry.java:101) ~[Forestry.class:?]
21.11 21:53:52 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
21.11 21:53:52 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
21.11 21:53:52 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
21.11 21:53:52 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
21.11 21:53:52 [Server] INFO at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:1.7.10-1614.57]
21.11 21:53:52 [Server] INFO at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
21.11 21:53:52 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
21.11 21:53:52 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
21.11 21:53:52 [Server] INFO at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]
21.11 21:53:52 [Server] INFO at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[server-1.7.10.jar:?]
21.11 21:53:52 [Server] INFO at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[server-1.7.10.jar:?]
21.11 21:53:52 [Server] INFO at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[server-1.7.10.jar:?]
21.11 21:53:52 [Server] INFO at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[server-1.7.10.jar:?]
21.11 21:53:52 [Server] INFO at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:1.7.10-1614.57]
21.11 21:53:52 [Server] INFO at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:1.7.10-1614.57]
21.11 21:53:52 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
21.11 21:53:52 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
21.11 21:53:52 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
21.11 21:53:52 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
21.11 21:53:52 [Server] INFO at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]

I am using thermos 1.7.10 forge version 1566

**Comment by Feptoid** [comment]
FIxed it, was using the wrong version of thermos.

**Comment by Wqrld** [comment]
Old issue, but what version of thermos does work?
