### ISSUE TITLE
To investigate: very bad tickrates on dedicated server

### ISSUE THREAD

**Issue by fabricator77** [ForestryMC/ForestryMC#19]
I'm getting severely high tick times on dedicated server with a compiled build of the current code base. Highest I've seen is 12,000ms, but it goes back to normal when the client leaves the server.

Removing forestry finally cleared the issue.
Been unable to track the cause further however, as running the java profiler causes the client to disconnect.

Blocks/Entities involved
Logs, Planks, leaves (trees and structures)
Bee Hives
Butterflies

**Comment by thr33p10** [comment]
This issue sounds much like what I've been investigating on my server.  Best I could find out with a little testing is found in my post in forestry here: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1277638-forestry-for-minecraft-trees-bees-and-more?comment=9172

Anyway, to summarize:
Butterflies polinate, and left unchecked for weeks can turn entire vanilla forests' leaves (pine or oak, for example) into polinated leaves from forestry.  By using MCedit and turning the leaves back (find/replace method on thousands of chunks) to vanilla ones, I got VAST improvements on tick burst lag.

By tick burst, I mean the server actually runs not bad on the average tick (from 12ms up to 40ms per tick depending on who is running what machines/automation), but every 20 - 60 seconds or so, a huge spike in lag occurs.  This is the lag that vanished when the leaves were changed back.

As a result, my server is running temporarily with butterfly spawns turned to 0 and butterflies at rest to 0.  In addition, having issued the command "/forestry butterfly kill" upon seeing ANY of them left from loading unloaded chunks where they were waiting, I have also had to resort to destroying every forest where the spectacles show me pollinated leaves (we will replant eventually).

One suggestion that I think might help out here:
Can butterflies be made inert but still appear (with limited lifespans too please)?
I.e. I'd love to still have butterflies on but make them so they can't pollinate.  This keeps the leaves from becoming a source of uncontrollable lag.  Bees should be enough for pollination, anyway (and their influence isn't as widespread).

**Comment by CovertJaguar** [comment]
Maybe it would be best if Butterflies didn't pollinate randomly.

**Comment by marcin212** [comment]
I have 4 groups on the server and a lot of chunks loader.
screens: 
https://dl.dropboxusercontent.com/u/25172450/bugs/forestry/22a2390f770f8e2736878b846a98ead6.jpg

https://dl.dropboxusercontent.com/u/25172450/bugs/forestry/2f9c5f46cc59cdb1fc86413a1e274ed1.jpg

snapshot from sampling server(VisualVM):
https://dl.dropboxusercontent.com/u/25172450/bugs/forestry/profiler.nps

forestry: 1.7.10-3.3.0.445-unstable
forge: 10.13.2.1291

**Comment by SirSengir** [comment]
Possible solution would probably be a) a toggle for pollination on servers and b) completing the "life cycle" of butterflies, i.e. having them actually die after a certain time.

**Comment by thr33p10** [comment]
SirSengir, I think both solutions would be good.  If solution A is easier to implement, it would be a helpful stopgap measure for any map where leaf pollination has gotten itself out of hand.

**Comment by mezz** [comment]
I took some steps toward fixing the problem.
1. Butterflies will die after a Minecraft week instead of being immortal.
2. The breeding and pollinating cooldown time is increased 50%.
3. Butterflies will no longer convert all leaves to Forestry leaves, unless they are sure they can pollinate or breed there.
4. The config for spawn constraint now applies to the creation of caterpillars too.

Please test it out and let me know if this is enough to fix the problem. 
It could take a while to be sure, so I'm leaving this issue open.
Thanks!

**Comment by CovertJaguar** [comment]
My root tile entity class has a clock int that is incremented every tick and is initialized with a random value.

**Comment by mezz** [comment]
We just released 3.4.0 stable, it'll probably be a while before this fix reaches a new stable build.

**Comment by Parker8283** [comment]
It might be worth it to do a 3.4.1 stable.

**Comment by thr33p10** [comment]
Our modpack will be built this week using the dev 464 version posted today.  Hopefully I can come back with positive feedback regarding the issue here.  Thanks @mezz for the effort on this!

**Comment by thr33p10** [comment]
Note for authour(s) / coders on this issue.

Having tried on dev 464 for the last 7 days on a live server, we've been happy to see improvements in server load.  Machines running more smoothly and overall TPS improvement.  I have noticed the butterflies having limited lifespan helping to keep from overloading us with the thousands we had before too - although I think using a more conservative config limitation might have more to do with that than anything.

Is there still any possibility of having a config option to stop them from pollinating?  I think it might be something in my case I would like to be able to have the choice to use.

**Comment by thr33p10** [comment]
@mezz A member on my server noticed that some bee flower requirements changed when we moved over to the dev 464 build from the previous stable 3.4.0 (I think).  I hate making a new issue just to point this out, as I'm thinking the flower changes for the bees might be intentional.  Any way of knowing what the new requirements might be (bee)?

A couple example bees that no longer accept their previous "flowers" are:
Embittered bees (nether wart)
Oblivion bees (dragon egg)
Ender bees (dragon egg)

The above are all using their natural traits (no genetic modifications).

Thanks for any help on the question.

**Comment by mezz** [comment]
Thanks for reporting back!
I can add a config option.

I'm moving your other comment to a new issue, the flowering is supposed to work the same as before.

**Comment by thr33p10** [comment]
@mezz I haven't seen the option added for the config (in "lepidopterology.conf" correct?) to enable/disable butterfly pollination.  I've kept up with the latest unstables on the server and run in to no other pressing issues yet.  Once I can neuter the butterflies I think I'll be happy with this issue, but I'll be keeping a watch on the newer one regarding leaf block optimizations... https://github.com/ForestryMC/ForestryMC/issues/552

Thanks!

**Comment by mezz** [comment]
Ok added a config option to lepidopterology.conf and optimized the leaf packet data. This issue should be complete now :)

Please test it out and let me know if you find anything wrong!
