### ISSUE TITLE
1.12.2 Wooden Gear doesnt have a recipe

### ISSUE THREAD

**Issue by MadRatSRP** [ForestryMC/ForestryMC#1903]

**Comment by Nedelosk** [comment]
![2017-12-17_15 06 23](https://user-images.githubusercontent.com/10259214/34080295-e60a0a8e-e33b-11e7-9bbf-22b725d4a4d8.png)
It has one and it works.

**Comment by MadRatSRP** [comment]
Not copper, wooden :)

**Comment by Nedelosk** [comment]
Foretry doesn't has a wooden gear. Only Copper, Tin and Bronze.
