### ISSUE TITLE
Gelid BEE

### ISSUE THREAD

**Issue by lukasmagi** [ForestryMC/ForestryMC#1905]
Gelid bee cause server crash
Blizzy bee not produce secondary product

Direwolf20 1.12.2 - updatet to last wer. of mods (problem still presist)

**Comment by mezz** [comment]
Thanks for the report!
I think those are thermal expansion bees from Magic Bees.
This issue has been reported here: https://github.com/ForestryMC/MagicBees/issues/40
Elec told me they will probably have time to fix it this weekend.
