### ISSUE TITLE
Apiarist's pipe? 

### ISSUE THREAD

**Issue by warplord** [ForestryMC/ForestryMC#1909]
Now that buildcraft is back in the mix, I installed it and forestry in 1.12 and I cannot find the apiarists pipe? Is it gone? Will you bring it back? Automating forestry apiaries is very very tedious without it (and without ender io)

**Comment by SandGrainOne** [comment]
The Apiarist pipe was moved to the BuildCraft compatibility mod. https://github.com/BuildCraft/BuildCraftCompat 

What are you trying to automate? It is difficult to automate the cultivation of a bee without the Apiarist pipe or something similar, but if you are simply automating comb production you can use any other insertion pipe.
