### ISSUE TITLE
[1.12.2] [1.11.2] Tropical hives don't generates in trees with Biomes Bundle

### ISSUE THREAD

**Issue by KorDum** [ForestryMC/ForestryMC#1911]
Tropical hives don't generates in trees with Biomes Bundle. Marshy hives generates instead.

For example:
Biome Jungle Ancient
BiomeTemperature: 0.95
BiomeWetness: 0.9

![image](https://user-images.githubusercontent.com/1331559/34072489-5f8f4160-e299-11e7-8820-d8040be27a15.png)

![image](https://user-images.githubusercontent.com/1331559/34072491-65b173a6-e299-11e7-9a72-07e814d423ec.png)

Why this can happen?

**Comment by temp1011** [comment]
https://github.com/BiomeBundle/BiomeBundle/issues/110 Supposedly it's to do with height? I think this has to be fixed on their side unfortunately.

**Comment by KorDum** [comment]
Thanks! It's not bug in forestry.
