### ISSUE TITLE
Forestry Not Playing Right with Fast Leaf Rendering Options. 

### ISSUE THREAD

**Issue by StoneLegion** [ForestryMC/ForestryMC#1914]
As far as I know this is a forever issue and a really annoying one. Not just for performance but some people prefer the visual look of a solid leaf block.

**Version:**
forestry_1.12.2-5.7.0.215.jar
forge-1.12.2-14.23.1.2566-universal.jar

With Fast Leaf Enabled:
![keezg0h](https://user-images.githubusercontent.com/425853/34084066-7d07bb32-e348-11e7-981c-db06f7d21f1b.png)

I hope something can be done I know they were or are tile entities and might have other rules preventing it. But maybe little hacky work around can be applied to give people optimal performance.

**Comment by KnightMiner** [comment]
I'll mention two things here:

* it's pretty easy to make leaves (or any block) become solid on fast graphics. Just need to check the current render settings in geyBlockRenderLayer and return cutout or solid.
* I'm pretty sure it makes little difference overall. Back in 1.7 leaves would cull extra faces on fast graphics which are now hidden, but that no longer seems to be the case in 1.8+, so patching the cullface logic as well might be ideal.
