### ISSUE TITLE
Translate to Russian version 5.7.0.217

### ISSUE THREAD

**Issue by Podrepny** [ForestryMC/ForestryMC#1915]
Russian translate for forestry_1.12.2-5.7.0.217

Put file to "forestry_1.12.2-5.7.0.217.jar\assets\forestry\lang\ru_RU.lang"

[ru_RU.lang.txt](https://github.com/ForestryMC/ForestryMC/files/1566136/ru_RU.lang.txt)

**Comment by mezz** [comment]
Thanks!
Please submit language changes here: https://github.com/ForestryMC/Forestry-Localization
