### ISSUE TITLE
Recipes Bug

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#1917]
when placing the broken tool into the carpenter, the GUI would show that the recipe would generate the bronze ingots. Now it is blank although it is still processing the tool to ingots. Without it the player doesn't know if the recipe is correct

**Comment by temp1011** [comment]
What version of forestry are you using? With forestry_1.12.2-5.7.0.219 and a few convenience mods in a test setup I got these: 
![brokenpickaxe](https://user-images.githubusercontent.com/34900092/34458372-3fdaef42-edc8-11e7-8414-2ec057c4b1a8.png)
![brokenshovel](https://user-images.githubusercontent.com/34900092/34458373-44dc2f10-edc8-11e7-8b07-9051f26b71b3.png)

Do you think it's a compatibility issue with another mod in your setup?
