### ISSUE TITLE
Crash when looking at butterflies (Rendering Item)

### ISSUE THREAD

**Issue by brisingraerowing** [ForestryMC/ForestryMC#1919]
Thank you for reporting!

[Crash Log](https://gist.github.com/BrisingrAerowing/83046b8f2943ee6676f74193fa354f6f)

Happened when searching 'but' in the creative search tab to find a button and butterflies showed up as well.

**Comment by temp1011** [comment]
@Nedelosk do you think this could fix it? https://github.com/ForestryMC/ForestryMC/commit/53ddaba7fd8efe525d35ab3f270989c897def65d

**Comment by temp1011** [comment]
https://github.com/Railcraft/Railcraft/issues/1366 Similar problem with bee nbt or just not checking if bees are enabled?

**Comment by Nedelosk** [comment]
Just not checking if bees are enabled. 
https://github.com/Railcraft/Railcraft/blob/aba7703d2480073998c5a8a02ad2802362fefaba/src/main/java/mods/railcraft/common/plugins/forestry/ForestryPlugin.java#L354
https://github.com/Railcraft/Railcraft/blob/aba7703d2480073998c5a8a02ad2802362fefaba/src/main/java/mods/railcraft/common/plugins/forestry/ForestryPlugin.java#L348
