### ISSUE TITLE
crash when using centrifuge with honey comb on server(1.12.2) (5.7.0.217)

### ISSUE THREAD

**Issue by SDUBZ** [ForestryMC/ForestryMC#1921]
Forestry: 1.12.2-5.7.0.217
Forge: 1.12.2-2575

crash report:
[crash-2017-12-19_16.01.43-client.txt](https://github.com/ForestryMC/ForestryMC/files/1577480/crash-2017-12-19_16.01.43-client.txt)

Thank  you for reporting!

to be noted: this user was a mac user

**Comment by Nedelosk** [comment]
This crash was caused by minecraft itself not by forestry.
