### ISSUE TITLE
No disabledSetupAPI for some modules

### ISSUE THREAD

**Issue by temp1011** [ForestryMC/ForestryMC#1927]
Inspiration for looking around: https://github.com/ForestryMC/Binnie/issues/331

From what I can see neither the apiculture nor lepidopterology override the default disabledSetupAPI (do nothing). It's possible that a user might disable these but still use an addon that requires them and still crash. Crash [crash-2017-12-28_01.16.41-client.txt](https://github.com/ForestryMC/ForestryMC/files/1590257/crash-2017-12-28_01.16.41-client.txt) is possibly caused by this with binnie-mods-1.12.2-2.5.0.110 and forestry_1.12.2-5.7.0.219 although it could still be on Binnie's side (I can't test with aboriculture because Binnie's has broken disabling in configs at the moment https://github.com/ForestryMC/Binnie/issues/369). However I still think implementing a dummy object for the API is important.

Hope this is useful.

**Comment by Nedelosk** [comment]
Fixed in 1.14
