### ISSUE TITLE
Tree farms not working on 1.12

### ISSUE THREAD

**Issue by mainrs** [ForestryMC/ForestryMC#1931]
Currently tried to create a tree farm using forestry. The trees do not grow for some odd reasons. I changed the farm to crops and those work without any problems.
No idea what I should attach since I coudln't find any relevant information :(

**Comment by temp1011** [comment]
Do you mean that saplings are planted but never grow into trees or are saplings just not planted? Is it a space issue for the type of saplings that you are using?

**Comment by mainrs** [comment]
The saplings do get planted, fertalizer is consumed but the trees never grow. I am using plain old oak saplings.

**Comment by temp1011** [comment]
Huh. It seems to work fine for me.
![treefarm](https://user-images.githubusercontent.com/34900092/34463368-8f7e6b6c-ee51-11e7-9994-95047402ed9d.png)
![treefarminventory](https://user-images.githubusercontent.com/34900092/34463369-93306e90-ee51-11e7-9193-943b97f759e5.png)
Do the trees grow if you bonemeal them or break and replace?

**Comment by mainrs** [comment]
Nop. Tried 4 stacks of bonemeal, nothing happened. I made sure that there is enough room for them to grow (remove invisible blocks (like magical light sources etc)).

**Comment by temp1011** [comment]
Very strange. Do trees not planted by the treefarm grow? (On humus or elsewhere)

**Comment by mainrs** [comment]
Yep, tried oak saplings and dark oak saplings. Both grow normally, either on dirt or humus.
I changed the farm to grow crops instead and it looks like those work without any problems.

**Comment by temp1011** [comment]
Ok I have no idea. Hope someone else better at this than me can help.

**Comment by Nedelosk** [comment]
#1862 ?

**Comment by mainrs** [comment]
Ah, that messes stuff up! Sorry to have bothered you guys :)
