### ISSUE TITLE
StoddCraft Custom Modpack Server Crash

### ISSUE THREAD

**Issue by EcoSage** [ForestryMC/ForestryMC#1936]
Hello,

I have been working with a custom modpack for quite some time now, and have always had difficulties with getting Forestry to work with the server files of the modpack. The client side of the mod works completely fine. Items work correctly, blocks spawn, and the mod seems very stable. As I mentioned before this is not the case when the mod is run server side. Here is a crash report with a fresh install of my server file, which runs completely fine without Forestry:

https://gist.github.com/SamosSage/51ed02f8b2d62974166cd5f875f50478

Thank You,

Samos

**Comment by temp1011** [comment]
https://github.com/ForestryMC/ForestryMC/issues/1897 similar? Could be a version issue. Try updating thermos like the other guy I guess.

**Comment by EcoSage** [comment]
This has solved the issue. Thank You.
