### ISSUE TITLE
1.12.2 Backpacks do not hold previously defined items

### ISSUE THREAD

**Issue by ClaudiusMinimus** [ForestryMC/ForestryMC#1937]
Prior to 1.12.2 I could add doors, ladders, slabs, stairs, and more to the Builder's backpack. I could add stone bricks and other rock-based blocks to the digging backpack. However, I cannot add these items anymore. I was able to add stone bricks to the config file and it worked, but I could not get any variants, slabs, or stairs to work.

To ensure this is not a conflict with another mod, I Installed only the latest Forge and Forestry. I also tried older versions of Forge and Forestry, but the issue persists.

**Comment by Nedelosk** [comment]
Thank you for reporting!

**Comment by temp1011** [comment]
![accepted items](https://user-images.githubusercontent.com/34900092/34643738-5cc23efe-f321-11e7-9eda-9fa35028a8f3.PNG)
Forestry wooden doors work but not vanilla it seems. Wood slabs  and stairs work. Items in pic in inventory don't fit into Builder's backpack. Using Forestry 5.7.0.227.
EDIT: Ladders don't work either. I'm guessing this is just item names in ModuleBackpacks which you might already be fixing for all I know :)

**Comment by Nedelosk** [comment]
@ClaudiusMinimus You probably have to remove the backpack.cfg or you add the following to  S:item.stacks.accepted.
```
               minecraft:acacia_door:0
                minecraft:birch_door:0
                minecraft:brick_block:0
                minecraft:carpet
                minecraft:clay:0
                minecraft:cobblestone_wall
                minecraft:crafting_table:0
                minecraft:dark_oak_door:0
                minecraft:dispenser:0
                minecraft:dropper:0
                minecraft:end_bricks:0
                minecraft:end_rod:0
                minecraft:furnace:0
                minecraft:hardened_clay
                minecraft:heavy_weighted_pressure_plate:0
                minecraft:iron_bars:0
                minecraft:iron_door:0
                minecraft:iron_trapdoor:0
                minecraft:item_frame:0
                minecraft:jungle_door:0
                minecraft:ladder:0
                minecraft:lever:0
                minecraft:light_weighted_pressure_plate:0
                minecraft:nether_brick:0
                minecraft:nether_brick_fence:0
                minecraft:packed_ice:0
                minecraft:purpur_block:0
                minecraft:purpur_pillar:0
                minecraft:purpur_slab:0
                minecraft:purpur_stairs:0
                minecraft:quartz_block
                minecraft:quartz_stairs:0
                minecraft:red_sandstone_stairs:0
                minecraft:redstone_lamp:0
                minecraft:redstone_torch:0
                minecraft:sandstone_stairs:0
                minecraft:sea_lantern:0
                minecraft:sign:0
                minecraft:spruce_door:0
                minecraft:stained_hardened_clay
                minecraft:stone_button:0
                minecraft:stone_pressure_plate:0
                minecraft:stone_slab
                minecraft:stone_slab2
                minecraft:stonebrick
                minecraft:wooden_button:0
                minecraft:wooden_door:0
                minecraft:wooden_pressure_plate:0
                minecraft:wooden_slab
```

**Comment by ClaudiusMinimus** [comment]
It worked perfectly in my test world!

I have not been able to find in the documentation for Forestry or on the MC wiki explaining the syntax for block/item ids - for example in the snippet above used:
                
```
                minecraft:acacia_door:0
                minecraft:birch_door:0
                minecraft:brick_block:0
                minecraft:carpet
                minecraft:clay:0
                minecraft:cobblestone_wall
                minecraft:crafting_table:0
                minecraft:dark_oak_door:0
                minecraft:dispenser:0
                minecraft:dropper:0
                minecraft:end_bricks:0
                minecraft:end_rod:0
                minecraft:furnace:0
                minecraft:hardened_clay
```
Why do some blocks/items use the ":0" at the end of the definition? At first I thought it might be a boolean flag indicating the off state, but I can see that is not the case. (I post this question here, because it is sort of related for others who may want to add/reject blocks/items from a certain backpack.)

Thank you,
CM

**Comment by 3TUSK** [comment]
@ClaudiusMinimus `:0` refers to the metadata of given item (or `ItemStack` to be exact). Example:

````
minecraft:plank:0 // Oak Plank
minecraft:plank:1 // Spruce Plank
minecraft:plank:2 // Birch Plank
minecraft:plank:3 // Jungle Plank
minecraft:plank:4 // Acacia Plank
minecraft:plank:5 // Dark Oak Plank
minecraft:plank   // Notice that this one doesn't specify a metadata -
                  // it means that backpack will match all the six variants above 
````

Some of entries in your snippet have `:0`, IIRC it is due to the fact that non-zero metadata will represent some weird stuff (e.g. block with different orientation).

**Comment by ClaudiusMinimus** [comment]
Thank you, that makes sense.
