### ISSUE TITLE
A way to blacklist hives via a api from spawning in a dimension.

### ISSUE THREAD

**Issue by dmodoomsirius** [ForestryMC/ForestryMC#1940]
Hello is there a way to blacklist hives either a specific hive or all of them via a api so a mod that dimensions are configurable like [AdvancedRocketry](https://github.com/zmaster587/AdvancedRocketry) can blacklist the hives on their side?

**Comment by temp1011** [comment]
https://github.com/ForestryMC/ForestryMC/pull/1939 being worked on at the moment as a config option.

**Comment by temp1011** [comment]
Fixed by https://github.com/ForestryMC/ForestryMC/pull/1941 for general hives in config. Do we need to blacklist specifics or add an api?

**Comment by temp1011** [comment]
IMC added in https://github.com/ForestryMC/ForestryMC/pull/1965. I think this is done now.

**Comment by temp1011** [comment]
I think this really now can be closed.
