### ISSUE TITLE
Forestry Bees Crash my World. [BUG]

### ISSUE THREAD

**Issue by Demonspitfir** [ForestryMC/ForestryMC#1944]
I'm using the acclimator and incubator from Binnie's Genetics. 

Those two machines are causing some major issues. 

Problem 1. World Crashing Bees.

When using the Acclimator on Queen Bees, when I try to re-insert the bees into any hive. It crashes the world. 

I don't know why, what, or how, since I don't know how to read crash reports but I have 3 different reports that all seem to be of the same issue. Since then I've only acclimated Princesses and Drones and the crash doesn't repeat. I chose to save those bees that crash my world so I can do crash tests later. 

I would find that my environment was too cold for a queen to work, and was sad, so I put them in the acclimator and acclimated them to the cold, only to put them back in a hive and seemingly things would work until the crashes. Which weren't immediate, they would take sometime. 

https://pastebin.com/YU5ABP1h
https://pastebin.com/DqvJNTWH
https://pastebin.com/GZuAhYy9

Problem 2: Broken Incubator. 
I was trying to figure out what I could do with all my extra drones and found that making enzymes would be a good idea. Doing some testing with a machine to get a final product before setting up any automation. I run into the same problem everyone else seems to. I can only get 1 enzyme per fresh block place. If I place the block down with 1 bucket of Growth Medium and 1 Sugar I can end up with 1 Enzyme but after that it either says two options. 

Invalid Recipe or No Space in Tank (where I have nothing in there and no amount of Pipes seem to matter.)
With the No Space in Tank issue it goes into "In Progress" but doesn't do anything.

Not sure why this is messing up. 

Note: Names
Genetics.lab_machine.incubator, Info = Genetics.lab_Machine.incubator.info 
Genetics.lab_machine.acclimatiser, Info = genetics.lab+machine.acclimatier.info 

Thank you for reporting!

For issues:
 * Try the latest version, it may have fixed the issue already.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

**Comment by 3TUSK** [comment]
Problem 1 looks like ForestryMC/Binnie#370
Problem 2 looks (partially) like ForestryMC/Binnie#391
The missing localization issue seems to belong to ForestryMC/Binnie#383 or ForestryMC/Binnie#389

None of these issues seem to belong to here.

**Comment by Demonspitfir** [comment]
Yeah, I didn't know where to post the issues, Just knew that it was Forestry Related.

I'll look at both those. 

I'm sure that we can close this issue since those are Binnies Issues not Forestry ones.

**Comment by Demonspitfir** [comment]
Problem 1 is confirmed for ForestryMC/Binnie#370
Problem 2 is Confirmed aswell

The Name issue does look like those other ones as well.

Since all 3 are already reported in the right locations. I'll close this.
