### ISSUE TITLE
Massive server-side lag in 1.10

### ISSUE THREAD

**Issue by SamboyCoding** [ForestryMC/ForestryMC#1949]
I'm 99% certain this is #1843 just in older versions of the game - the same stack is being dumped by tickprofiler. For 1.12, this was fixed in [b9924e](https://github.com/ForestryMC/ForestryMC/commit/b9924e). I'd just like to request that if at all possible, as I see that 1.10 and 1.11 versions of the mod are still being posted, that this fix be backported to 1.10, and probably 1.11 as well. I tried cherrypicking the commit but too much has changed for me to do it myself, but someone with an understanding of forestry may have better luck.

Thanks in advance.

**Comment by temp1011** [comment]
This can be closed now.
