### ISSUE TITLE
Marshy bees causing server crash

### ISSUE THREAD

**Issue by GhostieEcho** [ForestryMC/ForestryMC#1951]
Good evening! (or morning, or afternoon, pick your poison)

I've run into a problem with the marshy bees on my server. After narrowing it down to the marshy bees through trial and error and the crash logs, we tried updating to the most recent version of forestry, and tested it again.  The comment from the person raising the bees was "Also, Bees were acclimated to drier climate".  They gave me a screen shot of the hive as well.  I am running a lot of different mods, so I wouldn't be too surprised if the end result is a conflict of mods, but I think we've troubleshooted to eliminate that possibility.

![](https://cdn.discordapp.com/attachments/402056485737201665/403077347835772933/2018-01-16_22.44.18.png)

[https://gist.github.com/GhostieEcho/29b2fc8570590c86113be1c06f0dcf7a](url)

I tried searching the list of issues already posted, and the only one I found that had "marshy" that was related to server crashes was from 2015, so I felt this was reasonable to post.  Forgive me if it ends up being duplicate despite that.

Thank you!

**Comment by Nedelosk** [comment]
This is bug is caused by binnie's mod. https://github.com/ForestryMC/Binnie/issues/370
