### ISSUE TITLE
Missing Items after Apiarist Proven Frame Trade. (How?)

### ISSUE THREAD

**Issue by Demonspitfir** [ForestryMC/ForestryMC#1953]
I was trading with the Apiarist Villager that I brought to my base and after the trade I seem to be missing some of the following. TiCon Hammer, /Dev/Null Diamond Tier, Apiarist Backpack, Ring of Magnetization. 

I have no idea what happened or where these went but I checked every Possible Chest In my base and not in any of them. I don't know if this is on my end or with the Apiarist. 

If possible someone could try and duplicate this. If it's not possible then close the issue.

Thank you for reporting!

For issues:
 * Try the latest version, it may have fixed the issue already.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

**Comment by Demonspitfir** [comment]
I reverted my save file to before, I did not try to Duplicate this issue. 
If anyone can or has any experiences similar please add the comments.

**Comment by Demonspitfir** [comment]
How is this "Not Forestry" Related. Isn't the Apiarist Villager added by the Forestry Mod?

The Items I lost weren't Forestry yes, but the issue is with the Villager and Inventory and not with what Items I lost.

**Comment by Nedelosk** [comment]
Forestry only adds the villager profession. The villager inventory and trades are handled by forge itself.

**Comment by Demonspitfir** [comment]
I see. That makes sense. It still seems to be a non-issue only thing that I can assume happened was the stacked Items of items that normally don't stack caused an inventory conflict or something.

I consider this closed and final.
