### ISSUE TITLE
Genetic Filter doesn't work ?

### ISSUE THREAD

**Issue by McKazou** [ForestryMC/ForestryMC#1955]
Hi ! 

playing on the 1.12.2-5.7.0.236 version of Forestry. The Genetic filter just doesn't work. It's seems the UI is not what the pipe does.
I use this setup : 
![setup](https://user-images.githubusercontent.com/16335190/35198616-983ef388-fef1-11e7-9a3c-283ec49bf40d.png)

First : take the default setting for the pipe all set to "nocturnal".
![defaultpipe](https://user-images.githubusercontent.com/16335190/35198603-6b464c46-fef1-11e7-8dd0-5bfbdffa4503.PNG)
Every item i could insert in it, pops up. Even a drone with the nocturnal trait.

I set the yellow to "items" then the princess only goes into the yellow chest.
I set the blue to "anythings" then the drone only goes into the blue chest.
I remove all settings and set an other color to "closed" then the princess and the drone goes into this color. 

It seems like some of the settings doesn't work. Like a rotation that countain all settings ?

Thanks

**Comment by Nedelosk** [comment]
Thank you for reporting!
Have you tested it on singleplayer or multiplayer ?

**Comment by AlexIIL** [comment]
This also happens on a multiplayer server.

From some digging around it appears that filters are assigned ID's in order of registration, however modules don't load in any particular order (from 2 client logs, each loaded within about 5 minutes, the order varied dramatically), which causes the ID's to be different between runs (and very likely to be different from client - server). it might be simpler to fix this by sorting the final list of filters, and using ID's based off of the sorted list.

**Comment by McKazou** [comment]
This is a multiplayer world with a custom mod pack including More bees / magic bees / carrier bees. 

After relunching our server, "icons" changed. Like AlexIIL said :p.

**Comment by Nedelosk** [comment]
Should be fixed. Please reopen if it is not.
