### ISSUE TITLE
[1.12.2] Suggestion for improve Database GUI

### ISSUE THREAD

**Issue by KorDum** [ForestryMC/ForestryMC#1957]
@Nedelosk I with the players of my small server used Database and identified a few troubles.
1. Shift + Left Mouse Click place individual into cell of Database. Analysis for not analyzed individual doesn't work automatically. Info of individual doesn't show automatically for already analyzed individual.
![image](https://user-images.githubusercontent.com/1331559/35235540-7e5a61c2-ffb5-11e7-93ab-80ab8b2c3e70.png)

2. Information in the left block is very cumbersome and inconvenient. Can you reduce it indent, font or make in 2 columns?
Maybe?
![-1](https://user-images.githubusercontent.com/1331559/35236421-5596fc84-ffb8-11e7-8ee1-509e0ef29dc3.png)

**Comment by Nedelosk** [comment]
@KorDum
![2018-02-20_22 24 20](https://user-images.githubusercontent.com/10259214/36450026-f5301330-168c-11e8-9e3b-5c6b0dd2d270.png) ?

**Comment by KorDum** [comment]
In the Bee House? Looks comfortably expected.
I would expand the block with the information, because now English words fit into the mouth. And what will happen in other languages?

**Comment by Nedelosk** [comment]
The text automatically splits if the text is to long for the column.
![2018-02-21_17 57 08](https://user-images.githubusercontent.com/10259214/36493769-a9c51f54-1730-11e8-987e-a7d8c2856bbb.png)

**Comment by Nedelosk** [comment]
Current State:
![2018-03-03_19 51 16](https://user-images.githubusercontent.com/10259214/36938053-4fa3ee08-1f1c-11e8-8345-97930b5e91c7.png)
![2018-03-03_19 51 23](https://user-images.githubusercontent.com/10259214/36938054-4fc5c2a8-1f1c-11e8-926f-676685e3c3f9.png)

**Comment by KorDum** [comment]
Cool! When an update?
