### ISSUE TITLE
FTB Revelation 1.2 - Forestry Lepidopterology items crash client when searching creative menu

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#1958]
FTB Revelation 1.2 / Minecraft 1.12.2

Forgive me if this has already been posted. I did not see any existing reports. When searching the creative menu, some keywords crash the client. Viewing the crash report - this is being caused by forestry Lepidopterology items. 

Is it repeatable? Yes, searching “quartz” or “button” for example. 

Workaround is to use JEI or avoid searching known terms.

Disabling Lepidopterology module crashes server with state engine error during startup.

**Comment by ghost** [comment]
Note: This has been reported in the FTB Bug forums for the pack.

**Comment by Nedelosk** [comment]
Thank you for reporting!
Can you please post the crash report ?

**Comment by ghost** [comment]
Nedelosk, I don't have access to it at the moment, but I will ASAP.

**Comment by ghost** [comment]
Crash report
http://paste.feed-the-beast.com/view/d2f8e1c7

**Comment by temp1011** [comment]
https://github.com/ForestryMC/ForestryMC/issues/1924 ?

**Comment by ghost** [comment]
This bug does **not** exist in FTB Revelation pack version 1.3
