### ISSUE TITLE
No vegetable farms in 1.12.2

### ISSUE THREAD

**Issue by LazyDope** [ForestryMC/ForestryMC#1970]
1.12.2 doesn't doesn't have vegetable farms, iron electron tube don't do anything to the MultiFarm
![2018-02-04_16 59 46](https://user-images.githubusercontent.com/27651460/35782857-f5a4a3a2-09cc-11e8-8247-bbdc28b649e1.png)
I don't know if this is intentional or not, or if it's not implemented yet, but they were very useful.

**Comment by Nedelosk** [comment]
We have combined the `Cereal` and the `Vegetable` farms into the `Crops` farm.

**Comment by leagris** [comment]
Could you update the Forestry Wiki accordingly?
http://forestryforminecraft.info/farms:configuration
