### ISSUE TITLE
Latest 1.12 Forestry crashes during loading

### ISSUE THREAD

**Issue by raltus** [ForestryMC/ForestryMC#1971]
I was updating some mods and Twilight Forest needed Forge 14.23.1.2607. The client crashed during loading, so I tried updating to the newest Forge because that fixed a similar problem before. It still crashed with Forestry 5.8.0.242 so I went back a few versions and tried each up until the latest. Every other version of Forestry I tried, up to 5.7.0.238 works fine with the latest versions of Forge. 

https://gist.github.com/raltus/4f42a4e539e9934d9fa19c4ade17138d

**Comment by Nedelosk** [comment]
I don't get any crash if I start the newest version of forestry with the newest version of forge.

**Comment by raltus** [comment]
Sorry, I didn't catch that MultiMC didn't have the right log up in the console when I copied it. I did find the conflict with 240-242 though. It's between forestry and evilcraft. I'm going to open a issue on his page but I'll put the link here as well. Thanks

https://gist.github.com/raltus/6c9fc76cefd33e9de2ffe8f09eec7a7d

**Comment by Nedelosk** [comment]
https://github.com/CyclopsMC/EvilCraft/issues/648
