### ISSUE TITLE
[Feature Request] Support for Animania wool types in recipes

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#1974]
Hey, I'm not sure if this would be something on Animania's side or on Forestry's side, but it would be nice if the Scoop recipe (and whatever others take wool) could use Animania wool (`animania:wool`) as an option instead of `minecraft:wool`.

**Comment by Nedelosk** [comment]
@mezz Is there any reason why we don't use the wool ore dict in the scoop recipe ?

**Comment by mezz** [comment]
I can't think of a good reason why we do not use ore dictionary for the scoop wool.

**Comment by MauveCloud** [comment]
Here's a minor reason I discovered: the "blockWool" ore dict is not automatically registered by Forge - see https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/oredict/OreDictionary.java
It could be simple enough to add code to Forestry to make sure it's registered, though.

**Comment by mezz** [comment]
We should register it then, it is useful as long as other mods agree on the name and use it too.

**Comment by ghost** [comment]
Hey folks, that's fantastic news. I'm always glad to be able to help with mod integration issues!
