### ISSUE TITLE
Sorter recipe uses Forestry bronze gear instead of oredict

### ISSUE THREAD

**Issue by tornewuff** [ForestryMC/ForestryMC#1978]
The recipe for the sorter uses specifically Forestry bronze gears, so can't easily be unified with other mods. It should probably use the oredict bronze gear instead.

(I was going to send a pull request for this but the form for signing the CLA doesn't seem to be working for me).

**Comment by MauveCloud** [comment]
You mean the genetic filter?  That's especially problematic for UniDict users, since that will often remove the Forestry bronze gear recipe in favor of the bronze gear from another mod (such as Thermal Foundation).

**Comment by tornewuff** [comment]
Yeah, that's why I noticed: my pack uses UniDict and has removed the forestry bronze gear recipe, so the genetic filter is uncraftable.
