### ISSUE TITLE
Badly Compressed Packet Client Error

### ISSUE THREAD

**Issue by ChaseRox** [ForestryMC/ForestryMC#1981]
I get the above error whenever anyone walks to far away from our bases and tries to return. Attached is client log. Players can never get back in server after they are disconnected. Deleted forestry and everyone was able to connect again so I'm pretty sure its a forestry issue.

Running latest version of forestry & forge.

https://gist.github.com/ChaseRox/3a99545858d80e110a78c864ecb5f648

**Comment by ChaseRox** [comment]
Has something to do with Alvearies. After doing some testing, when I completely broke the alveary we had it doesn't kick anyone anymore. Alveary had 3 mutators, frame slot and one hatchery. Still kicked people even when it only had one block broke.

**Comment by LemADEC** [comment]
That's one of the symptoms from #2167
