### ISSUE TITLE
[1.12.2] Wrong drop Greenhouse Window

### ISSUE THREAD

**Issue by KorDum** [ForestryMC/ForestryMC#1982]
Forestry 5.8.0.242
When Greenhouse (Roof) Window breaks, it always drops out in an default state - uncolored.

![image](https://user-images.githubusercontent.com/1331559/36063337-bc3d764c-0e8c-11e8-8f4c-a37da3e30de9.png)

![image](https://user-images.githubusercontent.com/1331559/36063357-da1f811e-0e8c-11e8-8d7b-f5f37a29600e.png)

**Comment by temp1011** [comment]
It's weird that pick block works but breaking doesn't since pick block just gets the drops anyway.

**Comment by KorDum** [comment]
I used pickaxe if this is important. Forge 1.12.2 - 14.23.2.2611
