### ISSUE TITLE
[1.12.2] Greenhouse work incorrectly

### ISSUE THREAD

**Issue by KorDum** [ForestryMC/ForestryMC#1983]
Forestry 5.8.0.242
Steps for problem:
1. Build Greenhouse 3x2x3 with 6 Windows (2 opened, 4 closed), 1 Dehumidifier and 3 Heaters (Hot 205% and Arid 9%)
2. Place inside 1 Apiary and 1 Beehouse
3. Place into Apiary Modest Queen (with full life)
4. Bee has error — too cold
5. Put out Queen from Apiary and put in to Beehouse
6. Bee hasn't errors, work as usual (climate correct, all OK)
7. Waiting for life of Queen to spend a little bit (IMPORTANT!)
8. Put out Queen from Beehouse and put in to Apiary
9. Bee hasn't errors, work as usual (climate correct, all OK)

In addition, two players can simultaneously display a different climate in Apiary and Beehouse: in example from below I saw in some apiaries another climate — 60%/60%, another player saw 205%/9% at the same time. Perhaps these two bugs are related.

If you need screenshots, ask me for. I don't know, can you repeat this, a bug like floating

**Comment by KorDum** [comment]
Same problem is also observed after unloading the chunk. And you can repeat all the steps from point 3.

**Comment by marcin212** [comment]
I've been testing Greenhouses with a friend on a server today. I set the parameters of the Greenhouse, and after a moment the grass color changed and the Apiary had the temperature set to 64%. My buddy was seeing 20%.
After changing the world, my view also resets to the default climate. To fix it you need to reconstruct the Greenhouse (to fix the climate) and rebuild the Apiary to see the grass color change.
Video: https://www.youtube.com/watch?v=nFkXPHcQrJs

forestry_1.12.2-5.8.0.267 
forge 14.23.2.2654

**Comment by Nedelosk** [comment]
I think at some point I have to replace the greenhouse with a better system.
