### ISSUE TITLE
[1.12.2] "X-Ray" Leaves

### ISSUE THREAD

**Issue by KorDum** [ForestryMC/ForestryMC#1989]
![image](https://user-images.githubusercontent.com/1331559/36107494-4f3af42a-102b-11e8-89fb-56d256998500.png)

Look at screen, it's x-ray!
From left to right: Vanilla Jungle leaves, Coast Sequoia, Papaya, Zebrawood.
I think the leaves allows you to know the location of all the lava lakes :)

Forestry 5.8.0.242
Forge 1.12.2-14.23.2.2611
OptiFine 1.12.2 HD_U_C8

**Comment by ktole1999** [comment]
does it do this without optifine?

**Comment by KorDum** [comment]
Without Optifine:
![image](https://user-images.githubusercontent.com/1331559/36115248-8dfcf61e-1043-11e8-92d4-a30a5f06ea0a.png)

**Comment by KorDum** [comment]
![image](https://user-images.githubusercontent.com/1331559/36339244-44401910-13d2-11e8-91b7-feaaed58041f.png)

Unfortunately, no changes in 5.8.0.246

**Comment by Nedelosk** [comment]
Fixed with https://github.com/ForestryMC/ForestryMC/commit/f270231e679e0bfa057f37500e60821a2cd9d9c1.
