### ISSUE TITLE
Carpenter does not take materials

### ISSUE THREAD

**Issue by HobbsC** [ForestryMC/ForestryMC#1992]
Thank you for reporting!
I am using the latest version of Forestry and the carpenter does not take any materials. it shows it going into the machine but it does not take away from inventory and it is not accually in the machine almost like a ghost image. It is rather frustrating.
For issues:
 * Try the latest version, it may have fixed the issue already.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

**Comment by Nedelosk** [comment]
The crafting grid slots of the carpenter are ghost slots, so you don't lose the selected crafting recipe if the machine is out of resources. You have to put the items in one of the 18 slots above the inventory.
![2018-02-16_18 10 55](https://user-images.githubusercontent.com/10259214/36319945-caa2eac0-1344-11e8-945e-073ddcf869a4.png)

**Comment by HobbsC** [comment]
Thanks i am new to useing this mod and didn't really understand how the carpenter worked. I thank you for your help and love the mod it is really good.
