### ISSUE TITLE
[1.12.2]Managed Succulent Farm doesn't work

### ISSUE THREAD

**Issue by Heliddy** [ForestryMC/ForestryMC#1993]
Managed arboretum is working properly while the succulent farm seems to have no reaction.
![17](https://user-images.githubusercontent.com/36270952/36294134-8b556788-1319-11e8-89f5-723dacbb3020.png)
![18](https://user-images.githubusercontent.com/36270952/36294160-babf1046-1319-11e8-82c9-94c4d49689e8.png)

Forestry 5.8.0.243

**Comment by Heliddy** [comment]
It is the same with the Manual Succulent Farm.
![19](https://user-images.githubusercontent.com/36270952/36294595-cdead526-131c-11e8-9511-6596cee79cbe.png)
![20](https://user-images.githubusercontent.com/36270952/36294601-d910fa16-131c-11e8-9de5-6235a3914d88.png)

**Comment by Ghent** [comment]
Confirmed that this works in manual mode now.  Should it also work in managed mode?

**Comment by legoj15** [comment]
Hey, hate to bump this, but as of forestry 1.12.2-5.8.2.382 managed succulent farms don't work (place sand and cactus) again
