### ISSUE TITLE
Carpenter on Dire wolf 1.12.2 issue

### ISSUE THREAD

**Issue by minx2018** [ForestryMC/ForestryMC#1994]
Hi, I know this is a long shot but i am either really stupid or just plain stuck and cant find it on google or youtube in the right place. BUT I am having issues with the carpenter, I have a RF supply to it! so it has power. I have water in it and thats fine, I fill the recipe grid to make the handheld analyser and the analyser icon comes up BUT! it wont continue and it says Inventory needs recources. 
I looked at upgrading but it's not Curse ready? and its still classed unstable. 
Help would be lovely even if pointed in the right direction. 

![minecraft](https://user-images.githubusercontent.com/36565518/36341116-63f4fb0c-143d-11e8-822d-834837c7375a.png)

**Comment by Nedelosk** [comment]
The crafting grid slots of the carpenter are ghost slots, so you don't lose the selected crafting recipe if the machine is out of resources. You have to put the items in one of the 18 slots above the player inventory.
![2018-02-16_18 10 55](https://user-images.githubusercontent.com/10259214/36319945-caa2eac0-1344-11e8-945e-073ddcf869a4.png)

**Comment by minx2018** [comment]
Thankyou!

Sent from my iPhone

On 18 Feb 2018, at 12:01 am, Nedelosk <notifications@github.com<mailto:notifications@github.com>> wrote:


The crafting grid slots of the carpenter are ghost slots, so you don't lose the selected crafting recipe if the machine is out of resources. You have to put the items in one of the 18 slots above the inventory.
[2018-02-16_18 10 55]<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F10259214%2F36319945-caa2eac0-1344-11e8-945e-073ddcf869a4.png&data=02%7C01%7C%7C0d694434fb5942bbb3fc08d576068828%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636544692787009682&sdata=2GtxStQGPdVJ4wyvVrIcaOunBKnAth%2FuaNCG8qW%2Fe0U%3D&reserved=0>
