### ISSUE TITLE
[1.12.2] Stairs lighting bug with Optifine

### ISSUE THREAD

**Issue by KorDum** [ForestryMC/ForestryMC#1995]
![image](https://user-images.githubusercontent.com/1331559/36341478-fc560e10-13ff-11e8-948a-d91ff766c832.png)

Is it possible to repair it or is it an Optifine problem?
- Forge: 14.23.2.2611
- Forestry: 5.8.0.246
- Optifine: HD_U_C8

**Comment by Nedelosk** [comment]
Possibly related to #1817

**Comment by temp1011** [comment]
Have you tried changing `disableStairSlabCulling` in the forge config?

**Comment by KorDum** [comment]
@temp1011 Yes, I did. It doesn't resolve the problem.

**Comment by Nedelosk** [comment]
Duplicate of #1817
