### ISSUE TITLE
Paper/Stamps get voided when trying to insert them into the trade station by automation

### ISSUE THREAD

**Issue by LuigiHutch** [ForestryMC/ForestryMC#1999]
- Forge: 14.23.2.2618
- Forestry: 5.8.0.250

When trying to inserting paper and/or stamps into the trade station automatically via a hopper or pipe, instead of the paper/stamps going into their correct slots the items just get voided and never actually enter the trade station

**Comment by temp1011** [comment]
The items do go into the inventory but don't get seen because the GUI doesn't sync when items are put in externally. Not sure why.

**Comment by temp1011** [comment]
This can be closed since it was fixed by #2201
