### ISSUE TITLE
Cannot place Ender Farm in multiplayer

### ISSUE THREAD

**Issue by evan1026** [ForestryMC/ForestryMC#2002]
When I try to place the Ender Farm in multiplayer I get the following in the server log:
[https://gist.github.com/evan1026/f55034bd8f793c7358a696c475b342eb](https://gist.github.com/evan1026/f55034bd8f793c7358a696c475b342eb)

It doesn't actually crash but it does undo me placing the block.

Forestry version is forestry_1.12.2-5.8.0.242

**Comment by Nedelosk** [comment]
Duplicate of #1984
