### ISSUE TITLE
Arboretum in Compact Machine

### ISSUE THREAD

**Issue by shdwdrake8** [ForestryMC/ForestryMC#2003]
Not knowing exactly how the Arboretum worked, I placed one inside my compact machine. The block was uninteractable, had "Waiting for server..." on the tooltip, and when I broke it, it just replaced itself. I went into creative mode and could break it, but placing any other block in its place would turn it into an Arboretum. I restarted the server and the world would crash on load. I am not sure exactly the problem but something about the Arboretum didn't like being in a Compact Machine. I placed one in the overworld and the server just immediately crashed as well. I will post both error logs below.

Arboretum in Compact Machine: https://pastebin.com/snjMZ9Nf
Arboretum in Overworld: https://pastebin.com/RvwZfKqE

I am using the FTB Revelation 1.5.0 pack with no modifications. I would love to have a tree farm so I hope there is an easy fix for this. Thanks.

**Comment by temp1011** [comment]
https://github.com/ForestryMC/ForestryMC/issues/1984
