### ISSUE TITLE
Suggestion: Forestry Discord

### ISSUE THREAD

**Issue by temp1011** [ForestryMC/ForestryMC#2004]
I think it would be nice to have a discord for forestry. @mezz already has a channel which could have a forestry branch on.

**Comment by mezz** [comment]
I think it would be good to create a new channel for Forestry and addons. I can help administrate it and answer questions there though.

**Comment by Nedelosk** [comment]
I created a discord channel especially for Forestry and addons:
https://discord.gg/RFURsD5

**Comment by temp1011** [comment]
Nice!
