### ISSUE TITLE
Hellish in BiomeTweaker

### ISSUE THREAD

**Issue by gdarai** [ForestryMC/ForestryMC#2005]
Can you suggest what to change in biome setting so it would be conscidered Hellish for the bee breeding?
I am trying to use BiomeTweaker for the alterations... I can change biome name, temperature... or is it fixed directly to biome ID? I hope not.

**Comment by Nedelosk** [comment]
The biome needs the biome dictionary type `NETHER`.

**Comment by Nedelosk** [comment]
You can use [taigaBiome.addDicTypes(NETHER)](https://github.com/superckl/BiomeTweaker/wiki/Basic-Script-Commands#adddictypes) to add it.
