### ISSUE TITLE
Make the blocks/items can be crated configurable

### ISSUE THREAD

**Issue by LuigiHutch** [ForestryMC/ForestryMC#2008]
- Forge: 14.23.2.2618
- Forestry: 5.8.0.250

Another feature request, add a config which allows you to choose which blocks/items can be crated.

Im not sure how feasible this would be but hopfully you will consider it.

Kind regards,
LuigiHutch

**Comment by bookerthegeek** [comment]
Would this allow us to set any item to be able to be put into a crate?
