### ISSUE TITLE
[1.12.2] Crash at startup

### ISSUE THREAD

**Issue by Sindarin** [ForestryMC/ForestryMC#2011]
Whenever I am trying to start my Minecraft, it crashes. It seems to me Forestry is causing the crash. I have tried a few different versions of Forestry in the hope it would fix the problem, but it doesn't seem to help. The problem happens during the initializing phase. Crash report linked below. Could anyone help me?
https://gist.github.com/Sindarin/3f0828b84b12c87d68c558d246a093a3

**Comment by temp1011** [comment]
I'm not sure, it's an unexpected crash. Have you tried getting a completely new instance of the modpack (I'm guessing that is where this is from)?

**Comment by Sindarin** [comment]
Thanks, that seems like it has fixed the problem! After comparing a bunch of files, it seems like forestry was missing some configs. This fixed it!

**Comment by Sindarin** [comment]
I have tried a new instance. I discovered then that the pack was working fine at first, but when I copied over the configs of all my mods, the crashing began again. After testing a bunch more with enabling/disabling different mods, I found CubicChunks is causing the problem. Something in their config seems to have conflicted with Forestry, and after deleting my CubicChunks config the problem was fixed. Anyone know what might have caused this problem?

**Comment by temp1011** [comment]
I have no idea. However, as a pretty significant coremod it's definitely possible stuff like that can happen.
EDIT: See also https://github.com/ForestryMC/ForestryMC/issues/1966. I think it's an untested combination. You can try asking at the cubic chunks repo but it seems that for them generating a world with forestry crashes the game (at least from the issues I looked at).
