### ISSUE TITLE
Greenhouse Duplication Bug

### ISSUE THREAD

**Issue by DoragonKeiyou** [ForestryMC/ForestryMC#2018]
Version:  Forestry 1.12.2-5.8.0.250

Using a silk touch pick on a greenhouse block spits out two blocks.  This was done using a tinker's construct pickaxe with silky on it.

**Comment by temp1011** [comment]
Seems to me that silk touch shouldn't be applied to the block in the code since breaking with a normal pick gives the same drops anyway...
