### ISSUE TITLE
[Suggestion] Compatability with TechReborn Rubber Trees in Farm?

### ISSUE THREAD

**Issue by KAfable** [ForestryMC/ForestryMC#2019]
Would it be possible if the Rubber Plantation mode in the Forestry Farm multiblock also supported the TechReborn trees (only seems to support IC2 Trees from what I can see ingame)?

TechReborn - 2.12.3.477
Forestry - 5.8.0.250

**Comment by temp1011** [comment]
I'm writing a full plugin for TechReborn at the moment so I'll make sure to include this.

**Comment by temp1011** [comment]
Equally, I've just managed to break the squeezer by trying to add recipes to it...

**Comment by temp1011** [comment]
![rubber_trees](https://user-images.githubusercontent.com/34900092/36953087-938aadc0-200f-11e8-9d50-a7e6fbe44c4e.png)
Will create a PR once I'm finished sorting out other plugins too.

**Comment by KAfable** [comment]
Hey, just following up on this, has the PR for this been looked at yet?

**Comment by temp1011** [comment]
I think my PR is too large to be reviewed well and some of it doesn't work at the moment. I'll try splitting it up tonight which should hopefully make things easier.

**Comment by temp1011** [comment]
This was implemented in https://github.com/ForestryMC/ForestryMC/pull/2078 so I believe this can be closed.
