### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Keaton1188** [ForestryMC/ForestryMC#2026]
Hey.. we are constantly having this crash on our Revelations server! 

MC Version: 1.12.2

Forestry Version: forestry_1.12.2-5.8.0.242.jar

Gist: https://gist.github.com/Keaton1188/a3de3fad0046c0db1e08cdca24a8f429

**Comment by Nedelosk** [comment]
Duplicate of https://github.com/ForestryMC/Binnie/issues/370.
