### ISSUE TITLE
[1.12.2] Workbench incorrectly shows the recipe if it has been changed through a СraftTweaker

### ISSUE THREAD

**Issue by KorDum** [ForestryMC/ForestryMC#2029]
I changed some recipes with CraftTweaker script and and got a visual bug in Worktable. For examples see screenshots: 2 different recipes don't show me result (but left mouse click can craft it correctrly). Displayed as 64 diamonds.

- Forge 14.23.2.2611
- Forestry 5.8.0.250
- CraftTweaker 4.1.5

9 strings => 1 white wool
![image](https://user-images.githubusercontent.com/1331559/37241664-08ca5c36-246e-11e8-9748-c9a094b094bd.png)

3 Bees wax => 4 wax capsule
![image](https://user-images.githubusercontent.com/1331559/37241670-144732e6-246e-11e8-97ca-7318b3f920d1.png)

**Comment by bookerthegeek** [comment]
@KorDum 

1. Support for this is added through ModTweaker, and issues with it have been requested to go [Here](https://github.com/jaredlll08/ModTweaker/issues) please.
2. Your scripts for these changes? (please paste the scripts to Pastebin or gist for easier reading)
3. Have a great day!

**Comment by KorDum** [comment]
Thanks for answer!
In singleplayer there is no bug. But if multiplayer + server — there is a bug.
I created simple modpack (without ModTweaker):
- Forge 14.23.2.2611
- Forestry 5.8.0.250
- CraftTweaker 4.1.5
- MTLib-3.0.3.jar
and run server and client with simple script:
https://gist.github.com/KorDum/2bc595d2de81f10351dfa50593bb105a

![image](https://user-images.githubusercontent.com/1331559/37250735-c9004d9e-2513-11e8-845d-b0294d7e28af.png)
