### ISSUE TITLE
Lot of memory used

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#2031]
Lots of byte arrays allocated and required more that 260 mbs per session without players.
forestry_1.12.2-5.7.0.238.jar
![image](https://user-images.githubusercontent.com/10179239/37255571-48566cea-255f-11e8-8712-d0f75032af5c.png)

**Comment by mezz** [comment]
Thanks for the report!
It's not clear what is using the memory, and I do not see the same results from other tools.
The inventory has a reference to the tile which has a reference to the whole world, so I am not sure this is actually responsible for all the ram usage you see here.

**Comment by ghost** [comment]
thanks

**Comment by eeeBs** [comment]
Possibly it's TileHive entities? My server is dying in a fire from them. I am on 5.8.0.250 though. Came here looking for a solution.

**Comment by mezz** [comment]
There are a lot of TileHive but I don't think they are a very big problem.  We've already fixed a lot of performance issues with hives so far, I think they should be fairly low impact now. If you can profile and see an issue, then I can look more into it.
