### ISSUE TITLE
AlleleSpecies::getResearchSuitability Enhancement

### ISSUE THREAD

**Issue by RusTit** [ForestryMC/ForestryMC#2034]
I tried to figure out why honey comb from Binny's mod cannot be used in a Escritoire (like a reagent).
And I realized that the problem in checking the item type
`forestry/core/genetics/alleles/AlleleSpecies.java`
```
public float getResearchSuitability(ItemStack itemstack) {
...
        if (ForestryAPI.enabledModules.contains(new ResourceLocation(Constants.MOD_ID, ForestryModuleUids.APICULTURE))) {
			ItemRegistryApiculture beeItems = ModuleApiculture.getItems();
			Item item = itemstack.getItem();
			if (beeItems.honeyDrop == item) {
				return 0.5f;
			} else if (beeItems.honeydew == item) {
				return 0.7f;
			} else if (beeItems.beeComb == item) {
				return 0.4f;
			}
		}
...

```
The type checking is not performed because there is no way to register an additional one like ItemHoneyComb.
```
            } else if (beeItems.beeComb == item) {
				return 0.4f;
			}
```
Perhaps it's worth changing this comparison or adding the possibility of registering new Honecombes?

**Comment by Nedelosk** [comment]
You can add new research catalysts at the species root.
https://github.com/ForestryMC/ForestryMC/blob/e3e4a4341d386dd020866e2d7787916aaa81b073/src/main/java/forestry/api/genetics/ISpeciesRoot.java#L190-L196

**Comment by temp1011** [comment]
Since the other PR is merged does this still need to be implemented or can it be close?

**Comment by RusTit** [comment]
I close, the task is completed.
