### ISSUE TITLE
Weird Fluid Render

### ISSUE THREAD

**Issue by temp1011** [ForestryMC/ForestryMC#2036]
Forestry fluids don't seem to have boundaries when placed next to each other or vanilla in the world. This might be forge/vanilla bug.

I like that ethanol explodes though.

![2018-03-12_13 43 47](https://user-images.githubusercontent.com/34900092/37287129-f30f1d66-25fb-11e8-8fd4-5b8003d799dc.png)
![2018-03-12_13 44 59](https://user-images.githubusercontent.com/34900092/37287141-f82f820e-25fb-11e8-9222-2b5dae0629cf.png)

**Comment by Nedelosk** [comment]
Seems more like a forge bug. It also happens with fluids from other mods. But only with fluids that have the same material.
![2018-03-14_17 20 49](https://user-images.githubusercontent.com/10259214/37415635-2d0a2d88-27ac-11e8-8856-4ff4a6d6fd77.png)
![2018-03-14_17 23 41](https://user-images.githubusercontent.com/10259214/37415763-7a6c1ba4-27ac-11e8-8110-9bc6618490ec.png)

**Comment by temp1011** [comment]
Fair enough. I'm not sure what forge should render instead which is probably why they haven't changed it.
