### ISSUE TITLE
[1.12.2] Villager AI Server Crash

### ISSUE THREAD

**Issue by NielsPilgaard** [ForestryMC/ForestryMC#2040]
Hey!

My server crashed: [Crashlog](https://gist.github.com/NillerMedDild/5710677f54c68bc183eab834665f5975)
Forestry Villager AI seems to be the culprit.

Minecraft 1.12.2
Forge 1.12.2-14.23.2.2624
forestry_1.12.2-5.8.0.252

**Comment by Andvee** [comment]
Similar crash indicating Villager AI on a single-player world.

https://gist.github.com/Andvee/6043e56ce4c38d262ca0495af666ef2e

Minecraft 1.12.2
Forge 1.12.2-14.23.2.2611
Forestry_1.12.2-5.8.0.252

**Comment by temp1011** [comment]
Hmm. Maybe this is an issue with existing worlds but I don't think that's it. For some reason (maybe villagers on a loading border) the task doesn't seem to register right. At least, it keeps hitting the breakpoint instantly as soon as I unpause the game on line 158.
