### ISSUE TITLE
 forestry_1.12.2-5.8.0.256 default backpacks.cfg (specifically Hunter) doesn't pick up mob items 

### ISSUE THREAD

**Issue by darchitectlp** [ForestryMC/ForestryMC#2056]
Default config is missing loads (meats, blaze rods, rotten flesh, etc.). There's a handy list here, if you want it: https://pastebin.com/nFJ1Atsa

**Comment by temp1011** [comment]
I seem to have this as the default config: https://gist.github.com/temp1011/1924b163ded6e63feb3d1d6407011019. Maybe it's going wrong for some reason? It seems to have blaze stuff and rotten flesh in at least.

**Comment by Nedelosk** [comment]
I can't reproduce this. Works fine for me in the newest version.
