### ISSUE TITLE
Soldering Electron tubes in Intricate Circuit Board does not yield correct manual crops

### ISSUE THREAD

**Issue by TheOrionsun** [ForestryMC/ForestryMC#2059]
Hello,

I have an issue with electron tubes and what crop they show when placed into an intricate circuit board.

This is my current survival game:
MC v 1.12.2
Forge v 14.23.2.2634
Forestry v 5.8.0.256

I just created a manual intricate circuit board with the intended crops below using the wiki for placement and electron tube to crop : (note: I see the in game sides are different than what the wiki shows)

North Side - Golden ET - Cactus - gives crop "Arboretum".
East Side - Obsidian ET - Pumpkins/Melons - gives crop "Peat Bog".
South Side - Diamantine ET - Sugar Canes - gives crop "Cocoa Plantation".
West Side - Rubberised ET - Sticky Resin - Worked as wiki shows.

Has the electron tube types been changed for the type of crop one should get according to the wiki?

If so, please post a list of what the electron tube types are intended to give.

Also, could the wiki be updated?

I totally understand that things change and the wiki does not always keep up...

Thank your for your time and the awesome mod!!!

**Comment by temp1011** [comment]
The wiki is wrong. Unfortunately it seems the person who was maintaining it is no longer reachable and has prevented new accounts from being created. I think there is a tool tip for the electron tubes, possibly when soldering GUI is open or when mousing over them in JEI.

**Comment by TheOrionsun** [comment]
Ah, Thank you...That makes sense.

Thanks for the response. I will close with this comment.
