### ISSUE TITLE
[1.12.2] Bottler: Emptied cans are deleted

### ISSUE THREAD

**Issue by Syndesi** [ForestryMC/ForestryMC#2062]
Hi,

if I put any filled tin can into the Bottler, than the fluid is put into the internal tank but the empty can is deleted, therefore a closed system isn't possible.
Is this a wanted feature? And if so, could you please add a config option so that the cans aren't destroyed anymore?

**Comment by temp1011** [comment]
I think this can definitely be a config option for capsules themselves.

**Comment by Syndesi** [comment]
Woah, thank you very much for your fast response :D

**Comment by temp1011** [comment]
No problem.
