### ISSUE TITLE
Recent crash in 1.12.2,

### ISSUE THREAD

**Issue by CarlosMZ12268** [ForestryMC/ForestryMC#2069]
https://gist.github.com/Carlosedu1/fd4802d9898ee880442f294e86dd0b5d

Recent crash I had on 1.12.2, when troubleshooting a few mods. It mentions Forestry several times, which led me to seek help here. Tried it on both recommended and latest forge versions, and all other mods listed in the log are in their latest versions.

**Comment by temp1011** [comment]
~I think the only one of those mods we add a fermenter recipe for is biomes o plenty. Does the crash still happen if you remove that/disable the plugin for it?
Not BOP. Better with mods and better with addons both have newer versions available on curseforge from what I can see. Remove stuff which *shouldn't* be using the fermenter (from what I would expect) like aroma's stuff, bibliocraft, architecturecraft etc. then remove one by one to find the mod. From trying a few things I suspect it's better with addons but I couldn't get the game to launch with it installed (different crash).~
Ignore me

**Comment by Nedelosk** [comment]
@temp1011 Forestry crashes at the factory module and not at the module of another mod.

> 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
> 	at forestry.factory.recipes.FermenterRecipe.<init>(FermenterRecipe.java:35)
> 	at forestry.factory.recipes.FermenterRecipeManager.addRecipe(FermenterRecipeManager.java:37)
> 	at forestry.core.recipes.RecipeUtil.addFermenterRecipes(RecipeUtil.java:49)
> 	at **forestry.factory.ModuleFactory.registerRecipes(ModuleFactory.java:401)**

**Comment by temp1011** [comment]
Hmm well I just successfully launched with better with mods and better with addons so it's not them. I don't think any of the other mods should be a problem though.

**Comment by temp1011** [comment]
Found while looking at an unrelated log: 
```
[17:35:43] [main/INFO]: Potentially Dangerous alternative prefix `minecraft` for name `brown_mushroom`, expected `betterwithmods`. This could be a intended override, but in most cases indicates a broken mod.
[17:35:43] [main/INFO]: Potentially Dangerous alternative prefix `minecraft` for name `red_mushroom`, expected `betterwithmods`. This could be a intended override, but in most cases indicates a broken mod.
```
So I guess mushrooms are being overriden. I'm not sure how much/if things break though.

**Comment by CarlosMZ12268** [comment]
So hey, came to check in to see what's going on here. And by "see what's going on", I mean I recently got this exact same crash recently when tempering with my mod list again. Some mods were the same, others different, but from what I read, Better with Mods seems to be the suspect. How hard of an issue is this, exactly? (please educate me)

**Comment by temp1011** [comment]
I can't tell you 100%. When I tested with just better with nods everything worked fine for me. Maybe it's something to do with loading order?

**Comment by CarlosMZ12268** [comment]
I see. By load order you mean the actual jar files in the mods folder (that are in alphabetical order) or is there any other sorting list? I guess I too will try to isolate the two mods to see where exactly it starts to fail.

**Comment by CarlosMZ12268** [comment]
Liteloader. Liteloader is the one that caused the two mods to not work together. I just took it off the list and it loaded. In the last crash report, it was not in the mod list because I added it by tempering with the version.json file, making the game download it automatically. Now that I added it through the mods folder and took it off, BWM and Forestry worked together.

**Comment by temp1011** [comment]
Was  looking back through old issues, sorry for necro. But this is http://develop.liteloader.com/liteloader/LiteLoader/issues/53

**Comment by Nedelosk** [comment]
https://github.com/mezz/JustEnoughItems/issues/1189#issuecomment-498078956
