### ISSUE TITLE
[1.12.2] Crash from disabling arborculture

### ISSUE THREAD

**Issue by Alan19** [ForestryMC/ForestryMC#2077]
I got a crash from disabling arborculture in the module config. It seems to be having issues with the pollination genes. I'm on the latest forestry version.

Link to crash: [https://gist.github.com/Alan19/2a5ac8a65b8ec10fdd36844b3d391939](url)

**Comment by Nedelosk** [comment]
The link is dead

**Comment by Alan19** [comment]
https://gist.github.com/Alan19/e7c61ac32a581be82a7d642615b0d1f2
Does this work?

**Comment by temp1011** [comment]
https://github.com/ForestryMC/ForestryMC/blob/d621d8a5dfcbae6c1071e38c7cb5f073240e31f6/src/main/java/forestry/core/genetics/alleles/AlleleHelper.java#L59-L63 seems weird that both butterflies and bees must be enabled to to register alleles, maybe I'm missing something though. Plain forestry runs fine. Butterflies require trees too.
