### ISSUE TITLE
Unable to put fuel into the fermenter

### ISSUE THREAD

**Issue by Ruffage** [ForestryMC/ForestryMC#2082]
With the Towncraft Pack I am unable to put fuel sources into the fermenter. Fertilizer, Mulch, etc.

For issues:
 * Try the latest version, it may have fixed the issue already.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

**Comment by ProsperCraft** [comment]
Please upgrade this to a major bug, without biomass, we can't make Ethanol, which means we can't use Binnies mod at all.

**Comment by Nedelosk** [comment]
Major Bugs are only bug that crash the client or server.
