### ISSUE TITLE
non fluid container items being shown in bottler machine

### ISSUE THREAD

**Issue by Zer0Lyfe** [ForestryMC/ForestryMC#2085]
Not sure if this a forestry bug but i got told it was so i'm just reporting it.
https://github.com/GregTechCE/GregTech/issues/22

**Comment by Archengius** [comment]
I suggest using JEI ISubtypeRegistry to determine item subtype, not just thinking that every item which itemstack can have fluid capability is fluid container.

**Comment by mezz** [comment]
I looked into this and replied in the GregTech issue. It turns out it is not a Forestry issue.
