### ISSUE TITLE
Crash on open ui on carpenter

### ISSUE THREAD

**Issue by EchoDel** [ForestryMC/ForestryMC#2086]
Carpenter crashes on forge 2657 with forestry 5.8.0.264
Fresh install of both from the twitch launcher.
[Crash report](https://gist.github.com/redparry/e4dc5a80fc2b1ca07de377675e5c4fc8)

Steps to reproduce.
Start a new world, place a carpenter, right click on UI.

**Comment by Nedelosk** [comment]
The forge version you are using is broken.
Duplicate of #2083.
