### ISSUE TITLE
Client Crash - java.lang.RuntimeException: net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: circular model dependencies

### ISSUE THREAD

**Issue by ProsperCraft** [ForestryMC/ForestryMC#2088]
https://gist.github.com/ProsperCraft/80719bca2723ed826a6159431bd6d814

**Comment by temp1011** [comment]
Does it still happen without foamfix?

**Comment by temp1011** [comment]
Sorry,  not foamfix since same as https://github.com/ForestryMC/ForestryMC/issues/1990 which doesn't have foamfix on mod list
