### ISSUE TITLE
Guide book does not maintain order of category entries.

### ISSUE THREAD

**Issue by PolyacovYury** [ForestryMC/ForestryMC#2094]
Been sitting in the debug console for 2 hours now. There are several issues with the new Guide book, which will be posted separately, when I catch out the root cause of each one.

This one is about the ordering of chapters in the categories. I noticed that the Introductions appear in seemingly random places, grafters and mutations in the Aboriculture section switch places, etc.
Code debug and analysis have shown that you are using a HashSet to store the entry names. And this actually has a good reason: the ResourceUtil for some bizarre reason reads the same file (e.g. /entries/farming.json) twice while loading a category. But I would still prefer them being stored in the Array and using a `for` loop with an `if` statement which would add entry names only if an entry has not been added yet. This way not only the uniqueness of the entries would be maintained, but the ordering as well. Because otherwise a separate introduction makes no sense: it will be noticed after a half of the manual has already been read.

**Comment by Nedelosk** [comment]
Using an Array for that would be very inefficient, because I would always iterate over the whole array to find out if an entry already exists.
