### ISSUE TITLE
Guide book: entry buttons go missing

### ISSUE THREAD

**Issue by PolyacovYury** [ForestryMC/ForestryMC#2096]
Been sitting in the debug console for 5 hours now. There are several issues with the new Guide book, which will be posted separately, when I catch out the root cause of each one.

This is the last one I've noticed. Sometimes the book does not load up properly.
HashMap used to store the categories gets de-synced. It returns size() to be equal, e.g., 29, when there are really 30 items. Because of this, sometimes buttons don't display in all categories. Introduction in Arboriculture goes missing, either Database or Genetic filter in Genetics section get inaccessible, Worktable does not show up ever (this is not caused by this bug only, but also because the `entries/core.json` refers to it as `core/core/worktable`), etc.
The solution would be to fill the entries HashMap not in a concurrent loop, but in a regular `for` loop, like **everything** else is being processed.
(Actually, I wouldn't use the HashMap for this at all, because the list of entries should retain the ordering provided in the .json file, but this would require even more work to be done on your behalf).

**Comment by Nedelosk** [comment]
@PolyacovYury Thanks for helping me to improve the guide and fix some bugs
