### ISSUE TITLE
Dynamic Trees Support

### ISSUE THREAD

**Issue by Dalethium** [ForestryMC/ForestryMC#2097]
I'd love to see support for the dynamic trees mod!

**Comment by Mxater** [comment]
Message from Dynmap github,

Mod Author: Is it possible to create a JSON converter for the assets/models and assets/textures so we can run a command from dynamp to check the mods that are installed and generate the renderdata for Dynmap based on the data the mod provides in the assets folder?

**Comment by Dalethium** [comment]
@Mxater I think you meant to create your own ticker? This is unrelated to dynmap

**Comment by Mxater** [comment]
Oh sorry, I read bad, I will delete comment.

**Comment by Nedelosk** [comment]
We currently don't have enough time to look into things like this. But feel free to make a PR your self.
