### ISSUE TITLE
Copy bee

### ISSUE THREAD

**Issue by TheNullablePrototype** [ForestryMC/ForestryMC#2099]
https://www.youtube.com/watch?v=w80VfBtLHqY&feature=youtu.be

version: 3.6.0.0;
mcversion: 1.7.10.

**Comment by Nedelosk** [comment]
Have you tested it with the last version for 1.7.10 ?
3.6.0.0 is almost 3 years old.

**Comment by TheNullablePrototype** [comment]
No. We haven’t done it. Me made some minor fixes in the mod, but this dupe already existed before the fix. Were there any fixes for this dupe before?
