### ISSUE TITLE
Habitat Locator GUI text is broken

### ISSUE THREAD

**Issue by PolyacovYury** [ForestryMC/ForestryMC#2100]
```java
// GuiHabitatLocator.java, line 88
String str = Translator.translateToLocal("item.for.habitatLocator.name").toUpperCase();
```
I'm pretty sure, it's `item.for.habitatlocator.name` :)
Fixed this on my side by adding a missing key to the .lang files.

**Comment by Nedelosk** [comment]
Its not `item.for.habitatlocator.name` it is `item.for.habitat_locator.name`.
https://github.com/ForestryMC/Forestry-Localization/blob/c6ffa9eb7cd3063f7d5d10afab78e34883ff6846/assets/forestry/lang/en_US.lang#L466
