### ISSUE TITLE
Server log spammed by butterflies

### ISSUE THREAD

**Issue by Neruseru** [ForestryMC/ForestryMC#2102]
In the server log. the message "keeping entity forestry:butterflyge that already exists with UUID 9b73ac06-4ee2-bf91-0a4c63f623ad" appears about once a minute and the only way to stop it is by killing every butterfly with the command.

**Comment by temp1011** [comment]
https://bugs.mojang.com/browse/MC-95649. Seems that this is a vanilla bug. Or forestry is doing something wrong and resuing UUIDs.
