### ISSUE TITLE
[1.7.10] Missing capsules in last build

### ISSUE THREAD

**Issue by Antari-kun** [ForestryMC/ForestryMC#2103]
Hello. I update Forestry mod for minecraft 1.7.10 and i discovered, the oil and fuel (from Buildcraft) capsules (tin,wax,fireproff) are missing. I can`t fill them on Forestry capsules, older version does have.

Forestry build - 4.2.16.64

**Comment by Nedelosk** [comment]
We no longer support the 1.7.10 version of forestry.
