### ISSUE TITLE
Greenhouse window drops in creative mode

### ISSUE THREAD

**Issue by temp1011** [ForestryMC/ForestryMC#2108]
5.8.0.270. Breaking greenhouse window with bare hand in creative still drops the block because it is dropped in `breakBlock()`

`GreenhouseWindow` probably needs flattening into another block to make this work properly. Other ways are the `getDrops` PR in forge (1.13) or a hack similar to the one used for leaves which is overkill.

**Comment by temp1011** [comment]
If this can only be fixed well in 1.13 this issue is a bit pointless since I believe that the greenhouse window may be replaced then. It's not a huge bug anyway.

**Comment by saltycysg** [comment]
not a big problem though
(it seems that there's no tutorial in China about how the greenhouse works  :|  )
