### ISSUE TITLE
Infinite loop on client in Worktable when crafting a multi-result item

### ISSUE THREAD

**Issue by PolyacovYury** [ForestryMC/ForestryMC#2114]
Caught an infinite loop on client upon crafting a Harvestcraft Fresh Water item from a water bucket using shift-click if no crafting result is already in the machine's inventory.

Debug showed that the `shiftItemStackToRangeOpenSlots` function tries to put a freshly-crafted Fresh Water item (no pun intended) into a slot, currently occupied by an empty bucket, where that water used to be, so to speak. If I craft an item manually and put it into any slot and then try to shift-click more items into existence - everything works fine, even the buckets used for crafting get stacked together.

A possible fix would be to change the `count` argument passed to `shiftItemStackToRange` fucntion in `forestry.core.utils.SlotUtil.java` on line 278 from `1` to `inventorySlots.size()`. But this most likely needs a deeper look into, because in a rare occasion of Worktable's internal inventory filling up completely mid-crafting the code would still go into an infinite client-side loop.

**Comment by PolyacovYury** [comment]
No log gets output because it just loops in a for loop in original Minecraft code.
```java
// original Minecraft code
for(itemstack8 = this.transferStackInSlot(p_slotClick_4_, p_slotClick_1_); !itemstack8.isEmpty() && ItemStack.areItemsEqual(slot6.getStack(), itemstack8); itemstack8 = this.transferStackInSlot(p_slotClick_4_, p_slotClick_1_)) {
    itemstack = itemstack8.copy();
}
```
The function slot6.getStack(), and then this.transferStackInSlot() get called over and over and over again. But no log is printed because all code is totally valid.
```java
at forestry.core.utils.SlotUtil
    private static boolean shiftItemStackToRangeOpenSlots(List<Slot> inventorySlots, ItemStack stackToShift, int start, int count) {
        if (stackToShift.isEmpty()) {
            return false;
        }

        boolean changed = false;
        for (int slotIndex = start; !stackToShift.isEmpty() && slotIndex < start + count; slotIndex++) {
            Slot slot = inventorySlots.get(slotIndex);
            ItemStack stackInSlot = slot.getStack();
            if (stackInSlot.isEmpty()) {  // this "if" has no else that would handle a slot being occupied
                int max = Math.min(stackToShift.getMaxStackSize(), slot.getSlotStackLimit());
                stackInSlot = stackToShift.copy();
                stackInSlot.setCount(Math.min(stackToShift.getCount(), max));
                stackToShift.shrink(stackInSlot.getCount());
                slot.putStack(stackInSlot);
                slot.onSlotChanged();
                changed = true;
            }
        }
        return changed;
    }
```
Another "simple" fix would be to do a `count++` in the else clause. But this would also easily crash in a scenario described in the report.

**Comment by PolyacovYury** [comment]
Updated the mod. Now the shift-click is just borked.
The bucket gets thrown out onto the ground and gets immediately picked up by the player (a hopper can't process the item being thrown). Also the crafting result is deleted, so no repeated craft is processed.
Well, at the very least it doesn't hang up the game any more. But it renders the worktable pretty useless.

**Comment by PolyacovYury** [comment]
Um... Nevermind. Still hangs up.
We added a recipe via the CraftTweaker which changed it to 4 Water per bucket. And the Table started working semi-fine, as I described in the previous comment: shift-clicking the result into machine's inventory deleted the crafting result from the grid. After the changes were rolled back - the Table started hanging up again. Basically - the previous behaviour came back - crafting goes fine if an example item of the result is already present in machine's inventory.
Fix this plz :)

**Comment by Nedelosk** [comment]
@mezz How can we fix an endless crafting loop ? The minecraft water bucket creates a Harvestcraft Fresh Water and puts it in the inventory of the worktable. Harvestcraft has a second recipe for Fresh Water which only contains a single Fresh Water as a ingridient, because of that the worktable ends in an endless crafting loop of Fresh Water to Fresh Water.

**Comment by PolyacovYury** [comment]
Maybe adding a check to ignore crafting an item into itself could help?

Also I've found out that we have a Cooking For Blockheads mod, that makes Harvestcraft Fresh Water crafting as simple as shift-clicking a stack of salt directly into player's inventory. But not everyone has access to that mod, thus making a Worktable a feasible solution for them. If it is fixed, that is.

**Comment by mezz** [comment]
I tested this in several ways, following your instructions, but it worked fine in singleplayer and on a server.
Can you try with just Forestry and Harvestcraft? Another mod may be involved in this issue.

**Comment by PolyacovYury** [comment]
Indeed. Will try and add all our mods one by one.

...Well, brilliant. It looks like the bug is in one of our internal dupe fixes. Will debug this inside our team.
Terribly sorry for any inconveniences.

**Comment by Nedelosk** [comment]
Strange. I have tested it in my dev environment and with the normal launcher. Both only with forestry and harvestcraft and it totally freezes my mc clients.

**Comment by mezz** [comment]
I had some other mods in my dev environment, after removing them I was able to reproduce the infinite loop. I'll look into this again now.

**Comment by mezz** [comment]
The vanilla logic has a loop (which you pointed out) where you shift-click and it keeps crafting until you can't craft any more. In the case with the worktable here, it can craft infinite fresh water.

**Comment by mezz** [comment]
I will try to fix this by adding a hack to limit the number of crafting operations the worktable can do in one click, so it only does 64 like the crafting table would. That should also fix this bug.

**Comment by mezz** [comment]
That works well, and fixes the issue people sometimes run into where they craft _way_ more than they expect when shift-clicking in the worktable.
