### ISSUE TITLE
Difference between sapling generated trees and world gen trees

### ISSUE THREAD

**Issue by Shovinus** [ForestryMC/ForestryMC#2118]
Shovinus/ChopDownUpdated#3
Having a problem maping the trees as apparently the ones created under world gen can be different to those created via the saplings.

**Comment by temp1011** [comment]
Looks like an issue with https://github.com/ForestryMC/ForestryMC/blob/mc-1.12/src/main/java/forestry/arboriculture/blocks/BlockDefaultLeaves.java and https://github.com/ForestryMC/ForestryMC/blob/mc-1.12/src/main/java/forestry/arboriculture/blocks/BlockForestryLeaves.java somehow. They both extend `BlockLeaves` though.

**Comment by Nedelosk** [comment]
Every block with the class `BlockDefaultLeaves` don't has a tile entity and every block from `BlockForestryLeaves` has a tile entity that contains the genetic information of the leaf. Every leaf that is a default leaf has the default genetic data and needs no tile entity. We added the system because some world had lags caused by too many tile entities and a vanila bug.

**Comment by Nedelosk** [comment]
Trees that were pre generated should always have default leaves.

**Comment by Shovinus** [comment]
Cool, you got which tree gens which logs with which leaves as a list perchance? :) Just need to create a mapping, don't want to have to keep generating worlds to find them. Thanks in advance :*

**Comment by Shovinus** [comment]
Is it a match of log5:1 matches leaves5:1?

**Comment by Nedelosk** [comment]
No, but I can generate you a list if you wan't.

**Comment by Shovinus** [comment]
Yes please mate

**Comment by Nedelosk** [comment]
@Shovinus 
"{"blocks":["forestry:logs.vanilla.fireproof.0:0","forestry:leaves.default.0:0"]}",
"{"blocks":["minecraft:log:0","forestry:leaves.default.0:0"]}",
"{"blocks":["forestry:logs.vanilla.fireproof.1:1","forestry:leaves.default.0:1"]}",
"{"blocks":["minecraft:log2:1","forestry:leaves.default.0:1"]}",
"{"blocks":["forestry:logs.vanilla.fireproof.0:2","forestry:leaves.default.0:2"]}",
"{"blocks":["minecraft:log:2","forestry:leaves.default.0:2"]}",
"{"blocks":["forestry:logs.fireproof.0:3","forestry:leaves.default.0:3"]}",
"{"blocks":["forestry:logs.0:3","forestry:leaves.default.0:3"]}",
"{"blocks":["forestry:logs.fireproof.3:1","forestry:leaves.default.1:0"]}",
"{"blocks":["forestry:logs.3:1","forestry:leaves.default.1:0"]}",
"{"blocks":["forestry:logs.fireproof.1:0","forestry:leaves.default.1:1"]}",
"{"blocks":["forestry:logs.1:0","forestry:leaves.default.1:1"]}",
"{"blocks":["forestry:logs.fireproof.3:3","forestry:leaves.default.1:2"]}",
"{"blocks":["forestry:logs.3:3","forestry:leaves.default.1:2"]}",
"{"blocks":["forestry:logs.fireproof.5:3","forestry:leaves.default.1:3"]}",
"{"blocks":["forestry:logs.5:3","forestry:leaves.default.1:3"]}",
"{"blocks":["forestry:logs.fireproof.5:1","forestry:leaves.default.2:0"]}",
"{"blocks":["forestry:logs.5:1","forestry:leaves.default.2:0"]}",
"{"blocks":["forestry:logs.fireproof.5:2","forestry:leaves.default.2:1"]}",
"{"blocks":["forestry:logs.5:2","forestry:leaves.default.2:1"]}",
"{"blocks":["forestry:logs.vanilla.fireproof.0:1","forestry:leaves.default.2:2"]}",
"{"blocks":["minecraft:log:1","forestry:leaves.default.2:2"]}",
"{"blocks":["forestry:logs.fireproof.0:0","forestry:leaves.default.2:3"]}",
"{"blocks":["forestry:logs.0:0","forestry:leaves.default.2:3"]}",
"{"blocks":["forestry:logs.fireproof.5:0","forestry:leaves.default.3:0"]}",
"{"blocks":["forestry:logs.5:0","forestry:leaves.default.3:0"]}",
"{"blocks":["forestry:logs.fireproof.1:3","forestry:leaves.default.3:1"]}",
"{"blocks":["forestry:logs.1:3","forestry:leaves.default.3:1"]}",
"{"blocks":["forestry:logs.fireproof.6:0","forestry:leaves.default.3:2"]}",
"{"blocks":["forestry:logs.6:0","forestry:leaves.default.3:2"]}",
"{"blocks":["forestry:logs.vanilla.fireproof.0:3","forestry:leaves.default.3:3"]}",
"{"blocks":["minecraft:log:3","forestry:leaves.default.3:3"]}",
"{"blocks":["forestry:logs.fireproof.0:1","forestry:leaves.default.4:0"]}",
"{"blocks":["forestry:logs.0:1","forestry:leaves.default.4:0"]}",
"{"blocks":["forestry:logs.fireproof.6:1","forestry:leaves.default.4:1"]}",
"{"blocks":["forestry:logs.6:1","forestry:leaves.default.4:1"]}",
"{"blocks":["forestry:logs.fireproof.2:0","forestry:leaves.default.4:2"]}",
"{"blocks":["forestry:logs.2:0","forestry:leaves.default.4:2"]}",
"{"blocks":["forestry:logs.fireproof.2:1","forestry:leaves.default.4:3"]}",
"{"blocks":["forestry:logs.2:1","forestry:leaves.default.4:3"]}",
"{"blocks":["forestry:logs.fireproof.7:0","forestry:leaves.default.5:0"]}",
"{"blocks":["forestry:logs.7:0","forestry:leaves.default.5:0"]}",
"{"blocks":["forestry:logs.fireproof.2:2","forestry:leaves.default.5:1"]}",
"{"blocks":["forestry:logs.2:2","forestry:leaves.default.5:1"]}",
"{"blocks":["forestry:logs.vanilla.fireproof.1:0","forestry:leaves.default.5:2"]}",
"{"blocks":["minecraft:log2:0","forestry:leaves.default.5:2"]}",
"{"blocks":["forestry:logs.fireproof.0:2","forestry:leaves.default.5:3"]}",
"{"blocks":["forestry:logs.0:2","forestry:leaves.default.5:3"]}",
"{"blocks":["forestry:logs.fireproof.6:2","forestry:leaves.default.6:0"]}",
"{"blocks":["forestry:logs.6:2","forestry:leaves.default.6:0"]}",
"{"blocks":["forestry:logs.fireproof.2:3","forestry:leaves.default.6:1"]}",
"{"blocks":["forestry:logs.2:3","forestry:leaves.default.6:1"]}",
"{"blocks":["forestry:logs.fireproof.6:3","forestry:leaves.default.6:2"]}",
"{"blocks":["forestry:logs.6:3","forestry:leaves.default.6:2"]}",
"{"blocks":["forestry:logs.fireproof.1:1","forestry:leaves.default.6:3"]}",
"{"blocks":["forestry:logs.1:1","forestry:leaves.default.6:3"]}",
"{"blocks":["forestry:logs.fireproof.1:2","forestry:leaves.default.7:0"]}",
"{"blocks":["forestry:logs.1:2","forestry:leaves.default.7:0"]}",
"{"blocks":["forestry:logs.fireproof.4:0","forestry:leaves.default.7:1"]}",
"{"blocks":["forestry:logs.4:0","forestry:leaves.default.7:1"]}",
"{"blocks":["forestry:logs.fireproof.3:0","forestry:leaves.default.7:2"]}",
"{"blocks":["forestry:logs.3:0","forestry:leaves.default.7:2"]}",
"{"blocks":["forestry:logs.fireproof.3:2","forestry:leaves.default.7:3"]}",
"{"blocks":["forestry:logs.3:2","forestry:leaves.default.7:3"]}",
"{"blocks":["forestry:logs.fireproof.4:3","forestry:leaves.default.8:0"]}",
"{"blocks":["forestry:logs.4:3","forestry:leaves.default.8:0"]}",
"{"blocks":["forestry:logs.fireproof.4:2","forestry:leaves.default.8:1"]}",
"{"blocks":["forestry:logs.4:2","forestry:leaves.default.8:1"]}",
"{"blocks":["forestry:logs.fireproof.4:1","forestry:leaves.default.8:2"]}",
"{"blocks":["forestry:logs.4:1","forestry:leaves.default.8:2"]}",

**Comment by Nedelosk** [comment]
Do you know that every forestry tree can be genetically modified to have a trunk radius from one to five ?

**Comment by Shovinus** [comment]
I didn't :S tbh the trunk radius is only a helper check, it is to avoid trunks being split, I will leave it as 1, which accounts for trunks up to 2 wide anyway, the issue with setting it higher is that if you have other trees closer it will start thinking they are the same tree if the branches inter connect. 99% of cases the trunk will be 1-2 wide, so will have to just hope the other 1% of times they ignore any glitch.

Thank you for the list :) very useful. Did you download the mod?

**Comment by Nedelosk** [comment]
yes. Why ?

**Comment by Shovinus** [comment]
All done

**Comment by Shovinus** [comment]
Did you like playing with it? You might have better ideas on how to define trees than me tbh. It seems to be fairly reliable now though.

**Comment by Nedelosk** [comment]
I have noticed that you don't move the tile entity of the leaf with the leaf block. This breaks every forestry leaf with a tile entity.
![2018-05-01_22 36 07](https://user-images.githubusercontent.com/10259214/39492509-1e54f7b4-4d90-11e8-8cbd-3002f0bcb7ab.png)
![2018-05-01_22 36 14](https://user-images.githubusercontent.com/10259214/39492510-1e6d3c34-4d90-11e8-9648-1ce3aeb98bf3.png)

**Comment by Shovinus** [comment]
:s This is sapling gen ones not world gen I take it?

**Comment by Nedelosk** [comment]
Sapling

**Comment by Shovinus** [comment]
Weird I swear that wasn't like that before, my original test env was 1.10.2 with basically just forestry installed.

**Comment by Shovinus** [comment]
This is how I drop the block
```
//Use falling entities
EntityFallingBlock fallingBlock = new EntityFallingBlock(world, pair.to.getX() + 0.5,pair.to.getY() + 0.5, pair.to.getZ() + 0.5, state);
```

Where state is the original blocks state and:
```
/*
 * Class to house the falling logs and leaves
*/
public static class EntityFallingBlock extends net.minecraft.entity.item.EntityFallingBlock {

	EntityFallingBlock(World worldIn, double x, double y, double z, IBlockState fallingBlockState) {
		super(worldIn, x, y, z, fallingBlockState);
	}			
	@Nullable
	@Override
	public EntityItem entityDropItem(ItemStack stack, float offsetY) {
		IBlockState state = getBlock();
		// TODO check if this works for none MC leaves
		if (state != null && state.getBlock() instanceof BlockLeaves) {
			BlockLeaves leaves = (BlockLeaves) state.getBlock();
			for (ItemStack item : leaves.getDrops(worldObj, getPosition(), state, 0)) {
				super.entityDropItem(item, offsetY);
			}
			return null;
		}
		return super.entityDropItem(stack, offsetY);
	}
}
```
this is the class used to drop the entity.
I didn't write this, and it was in ternsips original code, I  can see he left in a todo about checking. I am pretty bad at this tbh so I am unsure what I should change. The entity drop is only for if the falling entity break on a part block isn't it?

**Comment by Shovinus** [comment]
Surely the state contains the tile entity though no?
