### ISSUE TITLE
[Crash-1.12.2]Crashed while server starting up

### ISSUE THREAD

**Issue by Tollainmear** [ForestryMC/ForestryMC#2119]
[log](https://gist.github.com/Tollainmear/53eadf1b4af3bd221ae0cef647b46dd0)
[crash-report](https://gist.github.com/Tollainmear/af6ad57772bd8c264d8c2f82f16d7331)

Using:
forge: 2655
Forestry: 5.8.0.283

reply soon if possible plz 😅

**Comment by temp1011** [comment]
https://github.com/ForestryMC/ForestryMC/issues/1888? It could be that a server crash or any exception in shutting down corrupted the save (see https://github.com/MinecraftForge/MinecraftForge/issues/4904).

**Comment by Tollainmear** [comment]
yes, I have referred to these issue this afternoon（ UTC+8）, but it seems like only has problem with forestry :sweat_smile:

**Comment by temp1011** [comment]
OK I think this is a duplicate #1888 so can be closed, unless there are any other problems?

**Comment by Tollainmear** [comment]
of course, thanks for help~
