### ISSUE TITLE
[1.12.2] Ethanol doesn't work on BC combustion engines 

### ISSUE THREAD

**Issue by Schtyger** [ForestryMC/ForestryMC#2121]
Kinda made an entire ethanol plant in my single and just realized that ethanol cant be used as a fuel source for the combustion engine. Is this a bug? I'm pretty sure i remember them being compatible...

**Comment by temp1011** [comment]
https://github.com/ForestryMC/ForestryMC/blob/mc-1.12/src/main/java/forestry/plugins/PluginBuildCraftFuels.java currently not implemented, I assume because buildcraft wasn't updated/was in alpha. Maybe it should be added back.

**Comment by Schtyger** [comment]
What is the link you sent for? Is there anyway to fix that compatability issue or do I just have to wait until a new update of forestry?

**Comment by temp1011** [comment]
The link is the code that would do it but is currently commented out. I think either forestry or BC need to write some code to sort this out so I don't think there's much you can do to fix this unless you open a PR

**Comment by AlexIIL** [comment]
BuildCraft is still in alpha, and the fuel API's will change in the future, so please don't port it yet. 

EDIT: Although if forge's API version checking works it should be possible to just not load the compat classes when we break it in the future.

**Comment by Schtyger** [comment]
So in other words, just wait for buildcraft 8.0 right?

**Comment by AlexIIL** [comment]
Yes, although that we'll move to beta before 8.0.x (which will be the end of breaking changes).

**Comment by Nedelosk** [comment]
We added BuildCraft support back. This should work now.
