### ISSUE TITLE
Game Crashing Constantly By Opening

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#2124]
I tried opening minecraft with a crap ton of mods and one of them is forestry, i tried installing the newst version but they crash, so i went with older versions but they still crash, it doesn't matter what i use i keeps on crashing. Help?

Crash File: https://pastebin.com/D8vkahWL

**Comment by Nedelosk** [comment]
This is a crash of the iron man mod and has been reported already. https://minecraft.curseforge.com/projects/ironman/issues/877

**Comment by temp1011** [comment]
Same error as https://github.com/ForestryMC/ForestryMC/issues/2089: `java.lang.ExceptionInInitializerError` when registering blocks, although that was a different mod I believe. It's sometimes hard to find the same error though because the crash is hidden inside pastebin.
