### ISSUE TITLE
Lumbermill output does not match JEI

### ISSUE THREAD

**Issue by superfluke** [ForestryMC/ForestryMC#2125]
Best summed up by this screenshot, actual output of 1 log on top, JEI info on bottom:
![image](https://user-images.githubusercontent.com/20022336/39679377-98c0a100-516a-11e8-8662-4074debd8fdd.png)

forestry_1.12.2-5.8.0.285
Forge: 14.23.3.2655

**Comment by temp1011** [comment]
The lumbermill is from Binnie's mods so should be reported at https://github.com/ForestryMC/Binnie/issues.
