### ISSUE TITLE
Bottler dupes liquid when draining an item that contains more than 1 bucket of fluid

### ISSUE THREAD

**Issue by superfluke** [ForestryMC/ForestryMC#2126]
Putting a fluid container that has more than 1 bucket of liquid in the bottler will fill the bottler without draining the source container, effectivly duping liquids. Tested with evilcraft tank, TE reservoir, and IE jerrycan all filled with water.  

forestry_1.12.2-5.8.0.285
Forge: 14.23.3.2655

**Comment by temp1011** [comment]
This code seems problematic https://github.com/ForestryMC/ForestryMC/blob/e90ab8caf600feb0efdb793a8726243c92b70b8d/src/main/java/forestry/core/fluids/FluidHelper.java#L150
EDIT: Confirmed just forestry and TE.
