### ISSUE TITLE
Is there a way to stop the forestry manual from being given to the player on world creation?

### ISSUE THREAD

**Issue by coldReactive** [ForestryMC/ForestryMC#2127]
I looked through the configs, and there doesn't seem to be any way to do it. I'm building a modpack with the akashic tome, and I need the book to not be given to the player on world creation so they can instead use a filled akashic tome.

**Comment by temp1011** [comment]
There should be an option in common.cfg:
```
book {
        # Players who enter the world for the first time get a Forester's Manual. [default: true]
        B:spawn=true
    }
```
If it's not there I would suggest backing up your configs and then delete the file and reload minecraft. This should regenerate them with any missing options.
