### ISSUE TITLE
Dynmap Support

### ISSUE THREAD

**Issue by Mxater** [ForestryMC/ForestryMC#2132]
Is there a possibility to provide support for Dynmap?

Searching in Dynmap forums, I found this.

> Mod Author: Is it possible to create a JSON converter for the assets/models and assets/textures so we can run a command from dynamp to check the mods that are installed and generate the renderdata for Dynmap based on the data the mod provides in the assets folder?

**Comment by temp1011** [comment]
I'm pretty sure most of the model data is in json. Is there anything specifically that doesn't work with the plugin?

**Comment by Mxater** [comment]
All models and textures dont work in Dynmap

**Comment by temp1011** [comment]
Do you use this as well https://github.com/webbukkit/DynmapBlockScan?

**Comment by Mxater** [comment]
Yes, I using these mod

**Comment by temp1011** [comment]
Hmm can you upload your log? Seems there are some issues (https://github.com/webbukkit/DynmapBlockScan/issues/20) but I'm not sure how they should be solved. As far as I'm aware forestry doesn't do anything 'wrong' for normal minecraft but idk how this plugin works.

**Comment by Mxater** [comment]
Here is the blockscan log.
http://pasted.co/c07abc3a

**Comment by temp1011** [comment]
Do blocks from other mods eg -enderIO or chisel or ic2 work?

**Comment by Mxater** [comment]
Not all, some blocks of enderIO, Chisel,IC2 and Forestry works

**Comment by temp1011** [comment]
I'm guessing the ones that don't work are the ones that show up in the log with errors?

**Comment by Mxater** [comment]
exactly

**Comment by temp1011** [comment]
To me it looks like the plugin needs to be written differently or someone has to write a plugin for the plugin for each mod used.

**Comment by Mxater** [comment]
So the ideal would be to contact each of the developers?
