### ISSUE TITLE
Biogas Engine Dupes Ethanol

### ISSUE THREAD

**Issue by z64555** [ForestryMC/ForestryMC#2143]
Minecraft Ver: 1.12
Forestry Ver: 5.9.0.591
Found in: Enigmatica 2 Expert 1.25

Ethanol doesn't show up on the list of accepted fuels (Shift+Mouseover tooltip on fuel tank), but it can be placed into the tank with a pipette or plumbing.

When attempting to remove the Ethanol from the engine, it'll fill the pipette but the gauge will not drop, thus allowing you to dupe ethanol a bucket at a time

When trying to run the engine on Ethanol, the Ethanol is consume and no RF is produced.

**Comment by temp1011** [comment]
Seems that some things don't insert into the tank in a normal way. Somehow buckets work fine but pipettes don't.
