### ISSUE TITLE
[5.8.0.295] Tooltip on analyser in hive offset too far.

### ISSUE THREAD

**Issue by Sinxar** [ForestryMC/ForestryMC#2147]
The tooltip when you mouse over a bee with the in-hive bee analyser its way off. I have an image to explain it better. I circled where my cursor is over the bee and where the tooltip pops up.

![2018-06-04_13 09 02](https://user-images.githubusercontent.com/3210315/40940319-68c494fe-6815-11e8-9a40-8365a4e6fb78.png)

**Comment by Nedelosk** [comment]
Fixed: 
![2018-06-14_20 10 15](https://user-images.githubusercontent.com/10259214/41429964-fcc5e652-700e-11e8-805b-3e0c4dcfaf61.png)
