### ISSUE TITLE
Vegetable farm disabled

### ISSUE THREAD

**Issue by Theduskofdeath** [ForestryMC/ForestryMC#2155]
I don't have vegetable farm or any farm that can manage potato / carrot (the iron electron tube only work in engine and the manual vegetable farm don't exist)

**Comment by temp1011** [comment]
Duplicate https://github.com/ForestryMC/ForestryMC/issues/1970. It's now the crops farm. The manual should state this correctly. No one has access to the wiki so that can't be updated.

**Comment by Theduskofdeath** [comment]
Thanks
