### ISSUE TITLE
Some bees seem to corrupt the game

### ISSUE THREAD

**Issue by StephanieUpland** [ForestryMC/ForestryMC#2156]
Hi there! I absolutely love forestry, my goal is to catch'em all! But..
I've had this problem on 2 different modpacks now, playing minecraft version 1.7.10 with the released version of forestry 4.2.16. 
The first modpack (Unabridged) had a few bees which caused my world to lose blocks. If it was just the occasional dirt block, that wouldn't have been a problem, but it made blocks disappear from my big reactor, which did make it a small problem.
I thought that maybe the problem was modpack related, as I couldn't find anyone else with this issue all over the interwebz. 
So I downloaded a new modpack (ABitOfEverything) and started cheering when I created the bees that caused the problem in modpacks #1 without any problems. Unfortunately after a little while longer, it turned out that I still had this issue. So just as before, I used a backup from a few hours ago to go back to a world that didn't have blocks missing here and there. 
Is there maybe a setting wrong in my pc causing this issue? Like I said, I can't find anyone else with this problem, and it's rather frustrating to keep losing a few hours worth of breeding...

**Comment by temp1011** [comment]
What species of bees?

**Comment by StephanieUpland** [comment]
The first modpack it was the fleshy branch, I'm not sure about the second modpack because I create about 10 species simultaneously and this happened about 45 minutes ago, so haven't had a chance yet to try out which species caused it this time

**Comment by temp1011** [comment]
hmm. I wonder if it is an effect of one of the species that you bred. No forestry species have these effects (I think) but clearly you use extrabees too. It seems that there are quite a few bees that can destroy/change blocks from here: https://ftb.gamepedia.com/Effect.

**Comment by StephanieUpland** [comment]
I did just create a vindictive bee, so that may have indeed been the cause, I had no idea that list existed! Thanks for that!

**Comment by StephanieUpland** [comment]
I've moved the vindictive bee out of my base and now there's no more blocks disappearing. Thanks for the help, I had no idea that was one of the side effects of some bees, the issue is now fixed
