### ISSUE TITLE
Crash on attempt to break Dehumidifier while camouflaged as block from Chisel

### ISSUE THREAD

**Issue by Locorock** [ForestryMC/ForestryMC#2157]
The block was also behaving oddly while being camouflaged as a chisel block:
- It kept shutting off due to lack of power, even if power was being provided
- Due to that the greenhouse kept changing levels of humidity back and forth from 66% to 300% (Way off the max change with the unsocketed dehumidifier)

The block stopped all the weird behaviour as i switched the camouflage and broke the block

Crashlog:
[crash-2018-06-10_15.16.36-client.txt](https://github.com/ForestryMC/ForestryMC/files/2087904/crash-2018-06-10_15.16.36-client.txt)

The version is 5.8.0.291

**Comment by temp1011** [comment]
Paste link to avoid downloading file: https://paste.ee/p/Kjb7K

**Comment by temp1011** [comment]
Hmm chisel hooks in here with asm stuff.
