### ISSUE TITLE
Server crash on startup with 1.12.2-5.8.0.296

### ISSUE THREAD

**Issue by DeadSix27** [ForestryMC/ForestryMC#2160]
Crash log: https://0x0.st/sLBb.txt

Client starts fine though.

**Comment by agentwolf88** [comment]
same here

https://paste.ee/p/jYY3D

**Comment by hampsterblade** [comment]
Here's 296 with the changes committed by Nedelosk, since the latest commits aren't compiling on Jenkins.[
[forestry_1.12.2-5.8.0.296.jar.zip](https://github.com/ForestryMC/ForestryMC/files/2104220/forestry_1.12.2-5.8.0.296.jar.zip)

](url)

**Comment by Rsslone** [comment]
+1

**Comment by Morpheus1101** [comment]
I got basically identical crash to #2161 but different line numbers for the java files https://gist.github.com/Morpheus1101/9751aa1224cf542dd348e2ca15b93eba
