### ISSUE TITLE
Forestry Crash version 5.8.0.296 on Server

### ISSUE THREAD

**Issue by royalcw** [ForestryMC/ForestryMC#2162]
Updated to forestry 5.8.0.296 and server crashes with an forestry/api/genetics/IAlyzerPlugin crash related to Apiculture.

Downgraded back to 5.8.0.295 and the crash goes away.
Minecraft 1.12.2
Forge 14.23.4.2705, also tried 2707 and 2708 versions

Issue:  Server crashes on boot but clients boot with no issues.
Fix:  Downgraded Forestry back to 5.8.0.295

Also have career bees installed but removing them did not fix the issue.  Binnie's Mod is not installed nor any other bee addons.  Forestry JEI for bees is installed but no issues with Forestry version 295.

[https://gist.github.com/royalcw/8b6e558ce8030b9f01ab1c1e82550cfb.js](url)

**Comment by Nedelosk** [comment]
Please try Forestry 5.8.0.302. http://jenkins.ic2.player.to/job/Forestry_1.11/302/

**Comment by Pythonic-Rainbow** [comment]
Same here.

```
Caused by: java.lang.NoClassDefFoundError: forestry/api/genetics/IAlyzerPlugin
	at forestry.apiculture.ModuleApiculture.setupAPI(ModuleApiculture.java:206)
	at forestry.modules.InternalModuleHandler.runSetup(InternalModuleHandler.java:72)
	at forestry.Forestry.preInit(Forestry.java:123)
```

**Comment by temp1011** [comment]
I can confirm that launching the server now works as of the build linked above.

**Comment by royalcw** [comment]
Version 5.8.0.302 works fine with the server.  Thank you for the quick response and problem is solved.
