### ISSUE TITLE
Iron Electron Tube not functional in circuit boards for farms.

### ISSUE THREAD

**Issue by wellsie514** [ForestryMC/ForestryMC#2163]
Other electron tubes can be placed in circuit boards. Other tubes have JEI state that they go into farms. 

Iron tubes do not go into circuit boards, nor does JEI indicate that they can. 

I just want to automate potatoes and carrots :(

Great mod though!

**Comment by temp1011** [comment]
https://github.com/ForestryMC/ForestryMC/issues/2155, the electron tube has changed.

**Comment by wellsie514** [comment]
Ohh, that's what I get for using the wiki instead of the manual. Thanks!

**Comment by temp1011** [comment]
Sadly I'm not sure if the wiki can be updated. Glad you've sorted it out.
