### ISSUE TITLE
Very buggy Backpacks and inventory behavior 1.12.2-5.8.0.296+

### ISSUE THREAD

**Issue by SevenMass** [ForestryMC/ForestryMC#2165]
Ever since I've installed 5.8.0.296 I've had issues with the inventory acting very buggy when using forestry backpacks. This problem still exist in 5.8.0.302 and 5.8.0.303.

What happens is this:
I open a backpack, move something in or out, and close it again. 
Right _after_ doing that, moving stuff around in my inventory only visually moves items around, but the items are actually still where they used to be. As soon as I open a different inventory, such as my TE satchel, the inventory snaps back to its previous state. 

In some cases, this even causes duplicates to appear, because only my hotbar snaps back, but not the rest of the inventory. Those duplicates are fake though, I can't actually do anything with them in game. 

In some cases the inventory gets all messed up, where the content of a backpack gets shown in my hotbar. Or where items appear in my armor slots or even crafting slots.

Reverting back to 5.8.0.295 fixes the problem.

**Comment by Nedelosk** [comment]
Can you please post your log file (https://pastebin.com/) and a list of your mods.

**Comment by SevenMass** [comment]
I've tested it with **_only_** Forestry installed, and the buggy behavior still happened.

I've created a gist with the log file from _that_ test, I hope that's o.k.
[Link to gist.](https://gist.github.com/SevenMass/2acf3178296cd1630b0d1d72e621cf2c)

**Comment by SevenMass** [comment]
I failed to mention it in the first post, but I've also tested throwing items on the ground and picking them up again. This also caused duplicates to appear. These dupes stuck around a bit longer, but after quitting and reloading they where gone.

**Comment by ghost** [comment]
I've also noted this bug just now. Definitely something very odd going on with backpack inventories. I can post logs/mod lists if necessary, but I doubt they'd tell you more than SevenMass's information.

Should also note: I'm not sure this should be considered a minor bug, IMO, as it makes the use of backpacks practically impossible -- but it's your call, of course.

**Comment by nghngn** [comment]
I also met this problem,even in the most lastest version  5.8.0.311.
If you need more information,I'd love to give,

**Comment by nghngn** [comment]
I find a detail which might help.
The BUG came after I had crafted and used one more the same backpacks.

**Comment by Nedelosk** [comment]
Seems like I can't reproduce this bug.
