### ISSUE TITLE
Thermal Foundation Compatibility

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#2170]
I can't insert seed oil bucket from thermal Foundation into the carpenter. i can do it with Forestry seed oil bucket, but thermal foundation's one. thanks.

Forge: 2709
Used Forestry: 5.8.0.304
ThermalExpansion-1.12.2-5.5.0.29-universal
ThermalFoundation-1.12.2-2.5.0.19-universal
ThermalDynamics-1.12.2-2.5.1.14-universal
CodeChickenLib-1.12.2-3.1.9.344-universal
CoFHCore-1.12.2-4.5.2.19-universal
CoFHWorld-1.12.2-1.2.0.5-universal

**Comment by temp1011** [comment]
I think king lemming intentionally did this to avoid balance issues

**Comment by ghost** [comment]
balance issues? seed oil is seed oil, whats about the balance...
i can't get the working seed oil bucket, i can get only the thermal foundation's one. so i cant get carpenter work most of the time.

**Comment by ghost** [comment]
also, there are two types of seed oils, i can't use the second one(righten side).
![fsffsfs](https://user-images.githubusercontent.com/24831406/41776226-94a00fea-762f-11e8-9492-396d46027b55.PNG)
i can use the brighter one(leften side)
so please help :( i just don't know which mod adds that righten sided seed oils aren't working.

**Comment by ghost** [comment]
and it's not only seed oil, honey bucket has the same problem. there are 2x types of all honey liquid things, like 2x honey buckets, 2x honey capsule, etc... and can't use the second one. i don't know which mod adds that extra honey bucket and seed oil bucket.

**Comment by ghost** [comment]
Well, i've found which modds add that extra ones.
**Thermal Foundation** adds the extra Seed Oil Bucket that doesn't work with Forestry.
**Biomes O' Plenty** adds the extra Honey Bucket that doesn't work with Forestry.

**Comment by temp1011** [comment]
They're not the same liquids, so they won't work in the recipes. If you think they should be added it's probably best to talk to the authors of those mods to see what they think.

**Comment by temp1011** [comment]
![discord](https://user-images.githubusercontent.com/34900092/41946587-2b91a2d2-79ab-11e8-96a3-225c80e54dc3.png)

**Comment by ghost** [comment]
they are same liquids... In Thermal Expansion, you get seed oil by inserting seeds into a machine, and the same way in Forestry. the only difference is you can get seed oil half of the cost in Thermal Expansion with respect to Forestry.

**Comment by Nedelosk** [comment]
If the Thermal Expansion seed oil can be produced for the half of the cost in Thermal Expansion with respect to Forestry we will not make it compatible because it obviously totally breaks the balance.
The same goes for the Biomes O' Plenty honey.  It has nothing to do with the forestry honey, apart from the name.

**Comment by Lord-Volkner** [comment]
I'm having the same issue in the mod pack I'm playing. The problem in IE: Reloaded is that you can ONLY produce the Thermal Foundations version of seed oil which won't work in the carpenter, which makes the carpenter completely useless, which makes the Forestry mod unplayable.

Clearly it was intended by the mod authors that these two seed oils should not be compatible, but does anyone know how to get around it? Is there something in a config file somewhere?
