### ISSUE TITLE
Greenhouse not changing the climate properly for apiaries

### ISSUE THREAD

**Issue by Adam-Kay** [ForestryMC/ForestryMC#2172]
I've been having this issue for about a week now, and basically what it happening is that it appears that the greenhouse does not change the climate for the bees in the apiary.

It seems totally inconsistent, sometimes the apiary will show 50%-50%, sometimes it will show the greenhouse climate, sometimes the bees will be happy and sometimes they will complain. Mix and match how you wish, I've had all possibilities.

Current Minecraft version: 1.12.2
Current Forge version: 14.23.4.2709
Current Forestry version: forestry_1.12.2-5.8.0.305

![image](https://user-images.githubusercontent.com/10010491/41940799-e4b4cf56-7991-11e8-85a1-e76373c55a74.png)
![image](https://user-images.githubusercontent.com/10010491/41940806-ec4bc8be-7991-11e8-844e-8873615c6786.png)

**Comment by Adam-Kay** [comment]
Bump?
Is there any way to circumnavigate this?

**Comment by Nedelosk** [comment]
The greenhouse is totally broken currently. I already work on a replacement for it.

**Comment by LordFokas** [comment]
@GameSlayar I found that breaking the apiaries, moving them a short distance away, and putting the queens back in will work. After placing the queens you need to wait a minute or two for them to run a couple cycles and then you're good to put your stuff back. Which is stupidly annoying when you have dozens of automated apiaries in greenhouses.
