### ISSUE TITLE
Crash with 311 version but not with 306

### ISSUE THREAD

**Issue by Eden-Mor** [ForestryMC/ForestryMC#2175]
Hello!
Using the latest forestry version 311 I crash [heres the link to the crash log ( https://gist.github.com/Xenooooon/8c8de135926619c98db2edeade9cb6dc )]
Forge Version 14.23.4.2725
Mod List https://paste.ee/p/EZup4

But when I use version 306 of forestry I dont crash, so something must've changed between versions 306 and 311.

Hope you can help me! Thanks!
If you need any more information dont hesitate to ask :)

**Comment by dblsaiko** [comment]
I encountered this issue when writing the BuildCraft support PR too. Fixed it by making Forestry load after BuildCraft. It still works here, no idea why it doesn't for you. Does it still crash when you have only Forestry and BC installed?

**Comment by Eden-Mor** [comment]
With the new forestry this no longer happens. Weird.
