### ISSUE TITLE
Iron Electron Tube has no function on Farms

### ISSUE THREAD

**Issue by Thiago1505** [ForestryMC/ForestryMC#2176]
When trying to use them on a chip, they only have effect on electrical engines
![screenshot_16](https://user-images.githubusercontent.com/40866343/42335493-f56de762-8056-11e8-9901-1628ca75e48d.png)

**Comment by temp1011** [comment]
https://github.com/ForestryMC/ForestryMC/issues/2163

**Comment by Thiago1505** [comment]
oh nvm, sorry

**Comment by temp1011** [comment]
No problem
