### ISSUE TITLE
Wax Capsules & Refractory Capsules not craftable

### ISSUE THREAD

**Issue by samtrion** [ForestryMC/ForestryMC#2183]
After deactivating the module "apiculture" (on purpose) wax capsules and refractory capsules are not craftable.

Forestry Version - 1.12.2-5.8.0.314

**Comment by temp1011** [comment]
They're made of wax which comes from bees.

**Comment by samtrion** [comment]
I am well aware of that. The bug, however, is that the items will still be registered even though bees have been completely disabled.

**Comment by temp1011** [comment]
Seems that wax is actually a core item. Hopefully should be an easy fix.

**Comment by samtrion** [comment]
I think that's not a clean solution. Since I also have no way to get Beewax with deactivated bees.

**Comment by temp1011** [comment]
Emptying wax capsules sometimes gives wax back in one of the machines, but I agree there isn't a good renewable source. However, if someone disables apiculture it would be annoying to lose all liquids
 I'm happy to rework it though

**Comment by samtrion** [comment]
One possibility option would be to deactivate these lines by deactivating "apiculture".

https://github.com/ForestryMC/ForestryMC/blob/mc-1.12/src/main/java/forestry/core/items/ItemRegistryFluids.java#L47-52

**Comment by samtrion** [comment]
I think the liquid loss is not a problem when you disable "apiculture" in an existing world.  This is more about new worlds or modpacks.

**Comment by samtrion** [comment]
The fix, version 319, unfortunately remains unsatisfactory. There are still more than 60 items registered in the JEI and some with broken fluid textures. If beekeeping is disabled, all beekeeping products should not be registered. This includes beeswax and also the liquid capsules of beeswax.

**Comment by temp1011** [comment]
I'm not seeing any broken textures but maybe some more items should be disabled? Which ones do you have in mind? Seems maybe some should have alternative recipes.

**Comment by samtrion** [comment]
You are right, the broken textures are related total another setting. I will open a bug later for this.

**Comment by samtrion** [comment]
#2192 - Issue for broken textures.
