### ISSUE TITLE
[1.12] Compatibility - Agricraft

### ISSUE THREAD

**Issue by LukewarmYeti** [ForestryMC/ForestryMC#2189]
I know that during 1,7.10 forestry had compatibility for Agricraft via crops being harvested (that are plantred on crop sticks) in manual farms. I tried to test the same method used then and it doesn't seem to work. Is there a different method for getting the mods to work together, or has the compat not been re-implemented as Agricraft was late to update to newest versions?

If the compat doesn't exist for 1.12, I don't know how hard it would be to add it back, or whether it was previously made on Agricrafts side (not sure who made the compat), but I'm sure a few people would like the mods to work together again.

**Comment by BorisMulder** [comment]
Anyone looked at this yet? I would appreciate it too :)
