### ISSUE TITLE
Fluid dupe bug (cross-mod)

### ISSUE THREAD

**Issue by bbgott** [ForestryMC/ForestryMC#2198]
I'm opening this issue here to link it to the bug report in the OpenComputers repo that seems to only happen when forestry is installed. I discovered the bug originally with a custom modpack, but was able to narrow it down to just the 2 mods listed in other the bug report to reproduce the bug.

(https://github.com/MightyPirates/OpenComputers/issues/2894)

**Comment by SawFowl** [comment]
There is still such a bug. Watch the video. https://www.youtube.com/watch?v=w_qUx4lDcv0

**Comment by temp1011** [comment]
@Mr-Krab I think this is the issue you are talking about: https://github.com/ForestryMC/ForestryMC/issues/2143. This one doesn't involve pipette if I'm reading correctly.

**Comment by bbgott** [comment]
Upon further investigation, forestry does not seem to be a fault for this bug.  I mistakenly thought Forestry was involved because I was testing with a milk bucket.  Forestry appears to add milk as an in game fluid, so my test didn't work without Forestry at first.
