### ISSUE TITLE
[1.12.2] Single-block farm can break bedrock

### ISSUE THREAD

**Issue by eliskvitka** [ForestryMC/ForestryMC#2200]
Is this is feature?
Single-block farm replaces bedrock and some other blocks, that player can't break (from other mods).
![2018-07-19_23 30 57](https://user-images.githubusercontent.com/8600722/42968655-995a0af8-8bac-11e8-8c55-bf30b632b58b.png)
MC 1.12.2
Forge 14.23.4.2705
Forestry 5.8.1.325

**Comment by temp1011** [comment]
It's also an issue with the multifarm but it's never really been an issue here. Looks like farm logic should be changed.
