### ISSUE TITLE
can't harvest fruit without breaking leaves

### ISSUE THREAD

**Issue by chantrykomori** [ForestryMC/ForestryMC#2208]
trees from Forestry proper can't be harvested with a right-click for me, they have to be broken. in addition, it doesn't seem to matter what level of ripeness it's at - i always get a fruit.

i'm also having a similar problem with Binnie's trees - except they never mature, and never drop anything even when the leaves are broken

**Comment by temp1011** [comment]
Are the leaves meant to be harvested by right click? I couldn't seem to harvest any fruit from completely unripe leaves either, but once the leaves were 50%+ ripe I got fruit.
