### ISSUE TITLE
Odd behavior with butterflies that fly into a Betweenlands portal

### ISSUE THREAD

**Issue by mopsyd** [ForestryMC/ForestryMC#2209]
I have witnessed some strange behavior with butterflies that fly into betweenlands portals. This may also occur with other portal types too, but I haven't noticed if that is the case. I am curious if this also occurs with nether portals, abyssalcraft portals, mystcraft portals, etc, but I'll have to test a bit.

I have placed a bunch of forestry trees around my portal tree from The Betweenlands, which inevitably led to a lot of butterflies flying into the portal. Once they are in the betweenlands dimension, they do not move from the spawn location. Their wings still flutter as if they had landed, but they no longer fly around, and are generally unresponsive to everything around them. They do not respond to damage (they still get hurt, but don't react when hit), etc. This usually results in a large pileup of butterflies immediately inside the portal, even if both the overworld and the betweenlands are both chunk loaded.

I'm not really sure if this is an issue with the dimension or the lack of nearby forestry trees. Unfortunately I do not have any stacktrace to provide you, as there is nothing visible in the console when this occurs. This behavior has been consistent for at least several versions of both mods though, from 1.10 through the current 1.12.2.

Perhaps they should still fly around at least? I have seen pileup of other mobs inside the portal tree also, but all of the rest of them do react when you come through the portal (it was not chunk loaded on the betweenlands side when this occurred).

---------

How to replicate:
- Load Forestry and The Betweenlands
- Put a bunch of forestry trees near a portal tree.
- Go to the Betweenlands at least one time, and go back to the overworld.
- Idle for a bit, so some butterflies spawn. Enclose the area if you want to accelerate the behavior.
- Go back to the Betweenlands. There will be a sizable pile of non-responsive butterflies underfoot.

**Comment by temp1011** [comment]
What is the climate like in the betweenlands?
