### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by matyklug18** [ForestryMC/ForestryMC#2210]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Forestry (forestry)
so i am reporting it here

https://paste.dimdev.org/riqakiwico.mccrash

**Comment by temp1011** [comment]
Does the game load without ironman?

**Comment by matyklug18** [comment]
no, it have another error. but not error with forestry.

**Comment by temp1011** [comment]
Pretty sure ironman is what causes the error with forestry. Other stuff I can't tell without log

**Comment by Nedelosk** [comment]
Duplicate of #2124
