### ISSUE TITLE
[1.12.2] Forestry and LucraftCore Crashes Minecraft While Loading Mods

### ISSUE THREAD

**Issue by PulseBeat02** [ForestryMC/ForestryMC#2212]
Forge was loading mods into Minecraft, when it crashed saying that Forestry and LucraftCore was the cause. Here is the crash-report: https://paste.dimdev.org/udebujiwah.mccrash

I have used the latest version of Forestry, Lucraft Core and Forge.

Forestry Version: 5.8.1.326
Lucraft Core Version: 2.2.3

Forge Version: 14.23.4.2747

**Comment by temp1011** [comment]
This is probably lucraft core causing the issue. See https://github.com/ForestryMC/ForestryMC/issues/2210 for similar crash. I wonder if not explicitly registering blocks with registry events is causing issues on our side.

**Comment by temp1011** [comment]
I have opened an issue with lucraft at https://gitlab.com/lcoremodders/LucraftCore/issues/2. Hopefully things can be sorted out there.

**Comment by nictogen** [comment]
I don't think this really has anything to do with forestry. For some reason, the getCapability method, when passed our (Lucraft Core's Size Changing) capability as a parameter, is returning an instance of Aether II's EntitySpawningInfo capability. Forestry (and Iron Chests), just reveal this. I think it's a problem on Aether II's end.
