### ISSUE TITLE
some errors in console

### ISSUE THREAD

**Issue by Pa4ok** [ForestryMC/ForestryMC#2215]
https://gist.github.com/Pa4ok/9db46085a1b800ffa1d2d58bb1738ec4
forestry version forestry_1.12.2-5.8.1.326

**Comment by Nedelosk** [comment]
The linked error contains no information about the cause of the error. It only contains the type of the error and the source block "forestry:sapling_ge" but not what actually caused the error.

**Comment by Pa4ok** [comment]
sorry
log updated, the link is the same

**Comment by Nedelosk** [comment]
@Pa4ok The link is broken

**Comment by Nedelosk** [comment]
Closed because of no response.
