### ISSUE TITLE
Curseforge wiki link invalid

### ISSUE THREAD

**Issue by Helicaste** [ForestryMC/ForestryMC#2218]
Alright, this is a minor issue with the CurseForge download site located here: https://minecraft.curseforge.com/projects/forestry

When you click the "Wiki" link, shown in-between the "Issues" and "Source" links, it attempts to take you to a website called "forestry.sengir.net."

Either way, just thought that this would be something that should be fixed, the link to the wiki at the bottom of the page works just fine though.

![capture](https://user-images.githubusercontent.com/40724951/43972314-e9024d58-9ca1-11e8-858b-b8c49da0399b.PNG)

**Comment by mezz** [comment]
Thanks, fixed.
