### ISSUE TITLE
Possible bug relating to MFR causing server crash

### ISSUE THREAD

**Issue by skellitor301** [ForestryMC/ForestryMC#2219]
I'm having an issue running a server in 1.10.2 where it keeps crashing on launch. This has started after I've installed Forestry version 5.2.17.388. Although the thing is after doing some searching on the error the crashlog has provided I've been constantly lead to an issue entry on MFR github. I've detailed the issue and provided logs on the entry. Hopefully posting this here can help shed some light on the issue. [Link to MFR entry](https://github.com/skyboy/MineFactoryReloaded/issues/625#issuecomment-412250141)

**Comment by Nedelosk** [comment]
We no longer support the 1.10.2 version of forestry.
