### ISSUE TITLE
Can't make an alveary Hellish temp in overworld

### ISSUE THREAD

**Issue by Rodg88** [ForestryMC/ForestryMC#2225]
It may be intentional, but adding heaters/lava hydro-regulators to get an alveary to over 200 temp from a normal/normal biome, it stays at 'hot', not 'hellish'. Using version 5.8.1.337

**Comment by Nedelosk** [comment]
It never was possible and will never be possible. It is very intentional. You have to go to the hell to get hellish temperature.
