### ISSUE TITLE
Date Palm not dropping dates

### ISSUE THREAD

**Issue by Gunner76th** [ForestryMC/ForestryMC#2226]
I have noticed that the Date Palm seems to not be dropping any fruit. I am on FTB Revelations 2.3.0 which has Forestry 5.8.1.322 on it. All other trees seem to drop fruit as expected, however the Date Palm does not seem to ever produce dates. I right click the pod and nothing happens. 

Is this a bug with the code, or do dates have a less than 25% chance of dropping fruit?

**Comment by temp1011** [comment]
Do the pods drop fruit if you break them?
