### ISSUE TITLE
Farming support for Pam's Harvest Mod, Botaina, Thaumcraft, and other mods.

### ISSUE THREAD

**Issue by CovertJaguar** [ForestryMC/ForestryMC#223]
There are many new mods out there that add various kinds of crops and trees. We should expand our support where possible.

None of these have been tested for current support, or investigated as for how much integration we should provide. Discuss below. I'll be updating the main post with info/concerns as the discussion progresses.

One thing we don't want to do is break the balance of a mod by allowing easy automation of something that should be rare and hard to farm.

General topics:
- [ ] Test generic handling of mods on this list, some mods may already be covered.
- [ ] Right-Click Harvest: Investigate for increased generic crop support.
- [ ] Generic Sapling Support: Somehow wrap generic saplings in low maturation speed sapling wrapper block that would allow support for any sapling in the OreDict.

Mods to support, if I missed any please comment below:
- [x] [Pam's HarvestCraft](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1274678): Flowers, crops, bushes, trees. Two types of crops, normal and regrowth. Fermenter and Squeezer integration? Add Forestry Fruit to Smoothy and Jelly recipes, etc...Some recipes already supported via OreDict. Author looking to add support, perhaps provide help? Plugins for Forestry provided support in the past, integrate from there? High Priority.
- [x] [GrowthCraft](http://growthcraft.wikispaces.com/): Grapes, Rice, Bamboo, Hops, etc... Manually Planted Farms are good for things like Grapes. Work with Author: @MatrexsVigil
- [x] [Witchery](https://sites.google.com/site/witcherymod/): Adds various Trees and Plants, used in Brews and Rituals. Discuss balance. Treents will spawn and kill you for cutting down Trees. Rumored Forestry support.
- [x] [Magical Crops](http://magicalcrops.weebly.com/): Adds crops that mature into mob drops.
- [x] [ExtraBiomesXL](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1282126): Many varieties of trees. May already support Forestry.
- [x] [Biomes O' Plenty](http://biomesoplenty.wikia.com/wiki/Trees): Many new trees and flowers.
- [x] [Plant Mega Pack Mod](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293061): Tons of new plants.
- [ ] [Twilight Forest](http://twilightforest.wikispaces.com/): Adds various Trees and Plants. Some with useful and magical properties.
- [x] [ExtraUtilities](http://ftbwiki.org/Ender-Lily_Seeds): Ender Lilies. Takes a "week" (168 real world minutes) to grow, produces Ender Pearls.
- [x] [DartCraft](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287878): Force Trees, create from a wand and normal saplings. Mod already provides support.
- [x] [Natura](https://github.com/progwml6/Natura): Bushes, Trees, etc... Already supported, slightly bugged on their end. Cotton nor Barley currently work.
- [x] [PneumaticCraft](https://twitter.com/MineMaarten/status/515180680687665153): Just made compatible by author.
- [ ] [Thaumcraft](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292130): Greatwood Trees? Silverwood Trees are no good, create nodes, bad for farming. Various flowers. Discuss balance issues. Look at Golems and emulate what they can do. Support is low priority.
- [ ] [Botaina](http://vazkii.us/mod/Botania/): 16 Flower varients. Farming Flowers is OP, do not allow. Allow Bees to use flowers, but not to spread them? Support is low priority.
- [ ] [IndustrialCraft2](http://wiki.industrial-craft.net/index.php?title=Main_Page): Complicated high maintenance crop breeding. Already provides automation in the mod. Insane crop output when automated. Very low priority.

See [EnderIO](https://github.com/CrazyPants/EnderIO/blob/master/src/main/java/crazypants/enderio/machine/farm/farmers/PlantableFarmer.java) for generic crop handling code.

**Comment by jojomodjo** [comment]
Sorry if I'm late to the party, but I see no mention of Tinkers oreberry bushes at all? It's not something that I've attempted automating, just something I've used early game to get some resources going. Thought I'd add that for discussion, my first dip into these forums so hope I'll be able to contribute more. :)

**Comment by Samtrion** [comment]
For the topic with bees and flowers, see #438

**Comment by Jhary** [comment]
Witchery Trees do sadly not support forestry multifarms. Tested with latest Witchery (0.22) and latest forestry release build (3.4.0.7).
Support for that would be awesome

**Comment by DonnerVarg** [comment]
ExtraBiomesXL trees seem to work well, except the large branching trees. Redwood and Rainbow Eucalyptus both often branch far enough or high enough that the multifarm doesn't collect all the branches. Is there a way to increase the range the multifarm will check? (Very tall fir trees from EBXL seem to work fine, so I'm guessing the others simply branch too far from the trunk for Forestry's detection as-is.)

Also the Rainbow Eucalyptus trees grow elbow logs around the base of the trunk which will overwrite the blocks of the multifarm, breaking it. I know that should be taken care of on the EBXL side, but perhaps an option with the API for other mods to integrate should be added to indicate saplings can only plant x blocks away from the multifarm.

Also, I think we a Botania + Forestry addon from some ambitious developer would be excellent. It would be great to see some interaction like the ideas mentioned above, but I think they're beyond the scope of Forestry and Botania themselves.

**Comment by Nirek-K** [comment]
Saplings growing and destroying blocks is definately on their side, it should just refuse to grow.
I will look into possibly extending the search pattern sanity, if it won't impact performance.
Magic Bees recently started adding Botania integration.
For anyone not following commit logs, Harvestcraft, Natura, BoP, Witchery (from our side), Magical Crops, AgriCraft crop sticks, ExUtils, should all be supported fully. (If you find anything you feel is missing or incomplete feel free to open an issue)
I'm still working on Plant Mega Pack.

**Comment by freyquency** [comment]
Would it be possible to allow Pam's Harvestcraft crops to be planted instead of converting them to the seeds first? It goes against the "no need for seeds" vibe that Harvestcraft has these days and makes automation harder.

**Comment by Nirek-K** [comment]
Use the Orchard mode (and plant them the first time manually as you want them)

**Comment by Nirek-K** [comment]
Growthcraft added to the list. should be most everything now at this stage.

**Comment by InfinityRaider** [comment]
what about ResourcefulCrops by @TehNut?
https://github.com/TehNut/ResourcefulCrops

**Comment by Nirek-K** [comment]
Mrm, things that have custom nonstatic things are probably more easily handled on their side.

**Comment by TehNut** [comment]
Oh right, I never got around to testing/adding support. I'll do that soon-ish.

**Comment by ajthemacboy** [comment]
What's the progress on this?

**Comment by Rumpelstiltskinny** [comment]
Is there any planned support for Harvestcraft fruit trees in Forestry multiblock farms? Is there any way to enable such a feature in 1.10.2, forge 2099, Forestry 5.2.14.267, Harvestcraft 1.10.2g?

I am aware that this topic is very old but I see that it's still open, hence the necro-posting.

**Comment by mezz** [comment]
Can you please copy your question to this new issue? https://github.com/ForestryMC/ForestryMC/issues/1471
I am closing this one since 1.7.10 is done getting new features.
