### ISSUE TITLE
Wood Piles not forming Charcoal Pits

### ISSUE THREAD

**Issue by RiverC** [ForestryMC/ForestryMC#2232]
Unsure if the intended structure of the charcoal pit has changed, but the behavior I'm seeing is that when you light the first pile and cover it, the smoke quickly stops. In cases where the smoke continues, it's because the fire destroyed the first pile and it proceeds to burn away all the wood piles quickly. 

I've tried it with 1x1, 2x2 and 3x3 flat wood piles, with dirt and ash bricks. (ensuring the wood pile is encased on all sides with the same material.)

I'm going to try rolling back to see if I can pinpoint the version at which I began first having the problem.

Thanks!

NOTE: I am using the latest version of Forge and Forestry (Forge: 14.23.4.2757 and Forestry: 339)

Second Note: I haven't been able to find a working version. It has been awhile since I used the pits in our most recent world, and removing recently added mods doesn't seem to help. Tonight I'll test with just forestry and forge versions to see if there's some weird compat issue I've run into here.

Final note: It looks like it's a compat issue with Valkaryian Warfare. (most recent version as of this posting.)

**Comment by saltycysg** [comment]
I think you have built a wrong structure.

**Comment by zetaraku** [comment]
@RiverC You should use **Loam** block to build the pit.
