### ISSUE TITLE
Greenhouse system should be improved

### ISSUE THREAD

**Issue by saltycysg** [ForestryMC/ForestryMC#2235]
Thank you for reporting!

For issues:
 * Try the latest version, it may have fixed the issue already.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

Click here:https://i.loli.net/2018/08/26/5b8259b34b332.png
Greenhouse system is a bit of unstable and could cause some problems.
Hope to see a better greenhouse system:)

**Comment by temp1011** [comment]
It will be replaced in 1.13 hopefully: https://github.com/ForestryMC/ForestryMC/issues/2172#issuecomment-405090682.
The code is at: https://github.com/ForestryMC/ForestryMC/tree/habitat-former
