### ISSUE TITLE
Crash When clicking on the forestry manual book

### ISSUE THREAD

**Issue by starkimax** [ForestryMC/ForestryMC#2236]
My game crash when I'm clicking on the manual book that we get when first spawn.
Some people say that's cause by the forge version that fail on ready the .lang file cause it return null.
But my game still crash with the lastest version on forge.

[crash1.txt](https://github.com/ForestryMC/ForestryMC/files/2321485/crash1.txt)

**Comment by temp1011** [comment]
Does this happen with clean install of assets?

**Comment by starkimax** [comment]
What do you mean by "clean". It's actually on a custom launcher.
I upload assets from the original minecraft 1.12.2 on a server using fillezilla (ftp).
Then the launcher download the assets from the server, so there is no reason for the assets to be corrupted.

Do you think my game crash because of the assets ?

**Comment by temp1011** [comment]
I'm not sure. Opening the book seemed to work fine for me with forge 14.23.4.2751 in intellij.

**Comment by temp1011** [comment]
Apparently there was a broken build of forge so .2758 was re released. Does that or .2751 solve this?

**Comment by Nedelosk** [comment]
I am closing this because of no answer.
