### ISSUE TITLE
[Suggestion] Charcoal pit config

### ISSUE THREAD

**Issue by Agrax** [ForestryMC/ForestryMC#2238]
I would like to be able to nerf charcoal pit a tad bit. Dirt as a fireproof material giving 12 charcoal per wood pile is kinda OP. Ik i can very easily just tweak how much wood does a wood pile need via CT, but imho we need a tiny bit better scaling in our modpack. Dirt<netherrack. Could you please consider adding such a config, please?

**Comment by temp1011** [comment]
See https://github.com/jaredlll08/ModTweaker/pull/678 for the modtweaker side of things.

**Comment by Agrax** [comment]
Works smoothly. Thanks
