### ISSUE TITLE
Minor kinda major issue.

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [ForestryMC/ForestryMC#2239]
In my forestry config file i made sure Buildcrafts MJ is on, and guess what kenesis pipes dont connect. I cannot really give a log but can you try to reproduce. Im on the latest forestry and buildcraft for 1.12.2. I also did try installing BC Compat but nothing

**Comment by temp1011** [comment]
![engine](https://user-images.githubusercontent.com/34900092/45059503-25c33a80-b094-11e8-84aa-89bbc2278866.png)
hmm, seems to work fine for me with https://minecraft.curseforge.com/projects/buildcraft/files/2560476. The buildcraft version shouldn't be an issue though unless things have changed a lot.
