### ISSUE TITLE
Forestry GreenHouse Lag spikes [1.12.2] 

### ISSUE THREAD

**Issue by HaniXP** [ForestryMC/ForestryMC#2251]
I dont really know.. this happens randomly at anytime but not most of the time. i mean i am encountering this type of big lag rarely for 3 times right now..

I am using forestry_1.12.2-5.8.1.341.jar which is the latest version ofc,

and i am also playing it on a modpack called HeartBeat Lite = https://www.technicpack.net/modpack/heartbeat-lite.1246190

heres a very short log for it : 

https://gist.github.com/AgentHani/53a2dacc16b7879a8ba9d873ec640d2c

**Comment by darthvader45** [comment]
I've also had this issue with the mod, but thankfully the latest beta should put this issue to rest for me.

Didn't even have any greenhouses remotely near my base too.
