### ISSUE TITLE
Crash when loading minecraft

### ISSUE THREAD

**Issue by kellixon** [ForestryMC/ForestryMC#2257]
MC 1.12.2. Forestry 5.8.1.344.
After the Forge update.
1.12.2 - 14.23.4.2759 - good.
                      |
                     \/
1.12.2 - 14.23.4.2764 - crash.
Crash report - https://gist.github.com/kellixon/e33ab2b6a70a5dd0b8352bc6fd4618f0

**Comment by bl4ckscor3** [comment]
Using Forge build 2763, Minecraft starts without any problem.

**Comment by Pythonic-Rainbow** [comment]
2763 causes client stutter?

**Comment by Convergence2738** [comment]
Can confirm this crash. I am getting it as well.

**Comment by NickelHub** [comment]
Still happens in MC 1.12.2. Forestry 5.8.1.344 with Forge 2764.
[crash-2018-09-28_18.41.40-client.txt](https://github.com/ForestryMC/ForestryMC/files/2429011/crash-2018-09-28_18.41.40-client.txt)

**Comment by Draskh** [comment]
Still happens with Forge 2764 and Forestry 5.8.1.345,
[crash-2018-09-28_18.41.40-client.txt](https://github.com/ForestryMC/ForestryMC/files/2429018/crash-2018-09-28_18.41.40-client.txt)

**Comment by Nedelosk** [comment]
@NickelHub Already fixed https://github.com/ForestryMC/ForestryMC/commit/813c3820fd01e591ce13392bb5af9a1e926af4e5

**Comment by Nedelosk** [comment]
http://jenkins.ic2.player.to/job/Forestry_1.11/346/

**Comment by Draskh** [comment]
Thanks.

**Comment by temp1011** [comment]
Was this a problem with forge? https://github.com/MinecraftForge/MinecraftForge/pull/5170

**Comment by kellixon** [comment]
Forge 2765 + Forestry 5.8.1.347 - all good. Closed.

**Comment by bl4ckscor3** [comment]
@temp1011 Yes. Forge 2765 works with Forestry versions that don't have this fix.
