### ISSUE TITLE
Compatibility with Forge 14.23.4.2705 (recommended version for 1.12.2)

### ISSUE THREAD

**Issue by BrainStone** [ForestryMC/ForestryMC#2258]
I have noticed that Forestry requires at least 14.23.4.2749. Is there are particular reason for that? I'm asking because I plan to run a Modded Survival Server with Sponge. And SpongeForge is only compatible with the recommended version of Forge (currently 14.23.4.2705).

So if possible, it would be incredibly nice to have that mod being built against the recommended version of Forge, so that it can be used with SpongeForge servers.

If there's nothing specific you need that got added in the few versions, it shouldn't be much more than changing the Forge version in the build.gradle file.

**Comment by lOmicronl** [comment]
Huh? I'm running the 5.8.1.322.jar with Forge 2705 just fine. Have been for weeks. Forestry does not complain about a wrong Forge version, and there are no issues ingame. This is the newest version the Twitch launcher offers me for download.

**Comment by BrainStone** [comment]
The latest beta version requires 14.23.4.2749 or higher if I'm not mistaken.

But regardless SpongeForge is supposed to work fine with higher versions of Forge.
