### ISSUE TITLE
[1.12.2] Blacklist for tree generation does not work

### ISSUE THREAD

**Issue by Draskh** [ForestryMC/ForestryMC#2261]
Forge: 2765
Forestry: 5.8.1.348
Abyssalcraft: 1.9.4.13

I added a blacklist (-> [here](https://pastebin.com/QLFDSR4T)) to the config, but it seems that wasn't applied to world generation. The world type is Biomes O'Plenty.
![2018-10-02_10 07 41](https://user-images.githubusercontent.com/26455012/46336687-d852d280-c62b-11e8-8e94-47f06e2d933f.png)
![2018-10-02_10 07 07](https://user-images.githubusercontent.com/26455012/46336688-d852d280-c62b-11e8-98ca-598c4b1a6e6e.png)

**Comment by xemnes** [comment]
This is still an issue in 5.8.2.422 even though it says its apparently fixed. ive set the biomes i dont want specific trees to spawn in (because baobab should never spawn in a forest) and it just ignores it. i also have dynamic trees forestry installed if that makes any difference.
