### ISSUE TITLE
Charcoal Pit causes increasing memory usage until the game freezes/crashes

### ISSUE THREAD

**Issue by gwpantazes** [ForestryMC/ForestryMC#2264]
See [the log here](https://gist.github.com/gwpantazes/7e7cab12c7d4281e4fe1a6912d0422d1).

Reproducible in this environment:

- Minecraft 1.12.2 (modded) forge-14.23.4.2760
- Stoneblock by kasparsu Version 1.0.17
   - Forestry - forestry+1.12.2-5.8.1.344.jar
   - 5493 MB memory allocated

> Try the latest version, it may have fixed the issue already.

Sorry, I'm not sure how to try the most recent version, but thought I'd file this issue anyway just so that this is a known issue. I tried searching existing issues, and this could possibly be related to #1878 because it has to deal with Charcoal Pit, but since this issue causes a crash I consider this more critical of a bug.

My initial guess of what's happening from a black-box perspective is that the charcoal pit functionality has a memory leak or something. The game runs fine as long as I don't use the charcoal pit functionality.

# Steps to Reproduce
Note: I'm framing this from the Stoneblock modpack perspective because that's where it's reproducing the bug for me. If this bug reproduces in other packs or from a simply vanilla+forestry environment, can someone please update here?

1. Boot up a new Stoneblock world with cheats/creative
2. Make a 2 width, 3 long, 1 tall charcoal pit out of clay
3. Put in the woodpiles, light the corner woodpile with a flint and steel, and seal up the charcoal pit
4. Let it burn / wait.
5. Observe that after a while, the game will start to stagger / slow, and eventually will freeze and crash. See [the log](https://gist.github.com/gwpantazes/7e7cab12c7d4281e4fe1a6912d0422d1) for the error messages.

**Comment by gwpantazes** [comment]
Attaching a timelapse video of the memory usage from around the time I seal up the charcoal pit until the crash. It seems like the memory issue only becomes a problem when the charcoal pit is becoming ash.

[Charcoal Pit Memory Crash Timelapse.mp4.zip](https://github.com/ForestryMC/ForestryMC/files/2453572/Charcoal.Pit.Memory.Crash.Timelapse.zip)

**Comment by gwpantazes** [comment]
Also tried in FTB Revelation to compare, and couldn't reproduce. Even with less RAM allocated overall, the game didn't crash when using the charcoal pit.

FTB Revelation Version 2.5.0
Minecraft Version: 1.12.2 (modded) forge-14.23.4.2759
Forestry: forestry_1.12.2-5.8.1.322.jar

Unfortunately, since the forestry version is earlier, it's not possible to rule out that the newer version in Stoneblock (forestry+1.12.2-5.8.1.344.jar) has a new bug.

Although, due to this Stoneblock pack issue ([Why is forestry in the pack and so disabled? #290](https://github.com/Sunekaer/stoneBlock/issues/290)), I'm starting to lean towards it being a purely Stoneblock pack bug. I'll work on confirming so we can close this issue.

**Comment by temp1011** [comment]
It's possible that there is an issue where there is a leak I think. Should only happen if the charcoal pit doesn't have the correct walls on latest. I will try to fix this. The structure of stoneblock is what makes it possible.

**Comment by temp1011** [comment]
updating to 5.8.1.350 may work if you remove the old wood piles in the world.

**Comment by gwpantazes** [comment]
I reproduced the crash on the new release Stoneblock v1.0.20 (forge-14.23.5.2768) which has forestry_1.12.2-5.8.1.350.jar. [See the log here](https://gist.github.com/gwpantazes/1f1b7a16d047bc034c7a1d673566155e). The old wood piles were already removed, I used a new charcoal pit in the test world to reproduce the crash.

I can try doing a 5.8.1.350 or newer build isolated with just vanilla to try to reproduce the crash, it might take me a bit to figure out how to install though since I usually play with FTB modpacks. Please bear with me if it takes a few days, I've been a bit busy lately.

**Comment by temp1011** [comment]
.354 (or whatever is latest) I hope would fix the crash.

**Comment by gwpantazes** [comment]
Tried with just vanilla 1.12.2, Forge 14.23.5.2768, and each of these Forestry versions to try to isolate the bug to a simpler environment:
- 5.8.1.350 = Didn't hang / freeze (this is the version in Stoneblock 1.0.20 that DID reproduce the crash)
- 5.8.1.351 = Didn't hang / freeze
- 5.8.2.354 = Diidn't hang / freeze

Since Stoneblock v1.0.20 uses forge-14.23.5.2768 and forestry_1.12.2-5.8.1.350.jar, not being able to reproduce with an isolated forestry mod environment makes me think it's a Stoneblock issue. I also couldn't reproduce the crash in FTB Revelations. Does that sound convincing enough to narrow it down to the Stoneblock pack?

**Comment by countergram** [comment]
Can reproduce on enigmatica 2 expert as well (repeatedly in flat test worlds, using both the Forestry version that came with, and the latest available [356]). Make a 8x2x8 or so pit with dirt, hang around for a bit and the game becomes unplayable.

In a new test world, tried making a "floating" pit and did not have the issue, so it may have something to do with a dirt pit connected to/embedded in the ground and/or interaction with grass spread.

**Comment by Nedelosk** [comment]
@countergram @gwpantazes Can you please check if this is fixed in the newest version of forestry?

**Comment by countergram** [comment]
Still happening in 5.8.2.358 which is the latest in Twitch. To reproduce, start a new default superflat world, build an 8x2x8 section of wood pile on or 1 block into the ground, cover with dirt, light, and wait. It does OK for quite a while, then memory usage starts dramatically increasing and the game freezes.

**Comment by Nedelosk** [comment]
@countergram Could you please test this with the newest version from Jenkins [5.8.2.362](http://jenkins.ic2.player.to/job/Forestry_1.11/362/)? Curseforge / Twitch always needs a long time to approve the files.

**Comment by countergram** [comment]
Looking good on that version.

**Comment by Nedelosk** [comment]
Thank you for testing
