### ISSUE TITLE
Manual Arboretum doesn't replace sand with humus

### ISSUE THREAD

**Issue by Attacker0922** [ForestryMC/ForestryMC#2266]
Manual Arboretum doesn't replace sand with humus.
![2018-10-08_21 29 58](https://user-images.githubusercontent.com/34370777/46609000-702b5180-cb41-11e8-8b0f-dcc4ee2b4da7.png)
i wait for a minute, but don't change.
![2018-10-08_21 30 31](https://user-images.githubusercontent.com/34370777/46609049-a2d54a00-cb41-11e8-9968-4fd7c2113298.png)
machine have water and dirt, fertilizer. what's a problem? its intention? or bug?
(i used google translate and my poor brain. sorry for my poor english.)

**Comment by zetaraku** [comment]
Try placing humus in the machine, or try the Managed version of the farm?

**Comment by Nedelosk** [comment]
Closed because of no response.
