### ISSUE TITLE
Crash with 'update neighbors'

### ISSUE THREAD

**Issue by EdenComp** [ForestryMC/ForestryMC#2267]
PS : I'm sorry if forestry is not the problem, but my server crash with Forestry and I can't remove this mod

08.10 19:05:34 [Server] Forestry Greenhouse/INFO [forestry]: Starting greenhouse thread
08.10 19:05:34 [Server] Server thread/INFO [FML]: Unloading dimension -1
08.10 19:05:34 [Server] Server thread/INFO [FML]: Unloading dimension 1
08.10 19:05:34 [Server] Server thread/INFO [FML]: Unloading dimension -17
08.10 19:05:34 [Server] Server thread/ERROR [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$WorldTickEvent@2db08e83:
08.10 19:05:34 [Server] INFO net.minecraft.util.ReportedException: Exception while updating neighbours
08.10 19:05:34 [Server] INFO at net.minecraft.world.World.func_190524_a(World.java:571) ~[amu.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.world.World.func_175685_c(World.java:491) ~[amu.class:?]
08.10 19:05:34 [Server] INFO at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52) ~[TileCore.class:?]
08.10 19:05:34 [Server] INFO at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203) ~[TileGrid.class:?]
08.10 19:05:34 [Server] INFO at cofh.thermaldynamics.duct.tiles.DuctUnit.onNeighborBlockChange(DuctUnit.java:283) ~[DuctUnit.class:?]
08.10 19:05:34 [Server] INFO at cofh.thermaldynamics.multiblock.MultiBlockFormer.checkMultiBlock(MultiBlockFormer.java:33) ~[MultiBlockFormer.class:?]
08.10 19:05:34 [Server] INFO at cofh.thermaldynamics.multiblock.MultiBlockFormer.formGrid(MultiBlockFormer.java:23) ~[MultiBlockFormer.class:?]
08.10 19:05:34 [Server] INFO at cofh.thermaldynamics.duct.tiles.DuctUnit.formGrid(DuctUnit.java:252) ~[DuctUnit.class:?]
08.10 19:05:34 [Server] INFO at cofh.thermaldynamics.duct.tiles.DuctUnit.singleTick(DuctUnit.java:349) ~[DuctUnit.class:?]
08.10 19:05:34 [Server] INFO at cofh.thermaldynamics.util.WorldGridList.tickEnd(WorldGridList.java:84) ~[WorldGridList.class:?]
08.10 19:05:34 [Server] INFO at cofh.thermaldynamics.util.TickHandler.tick(TickHandler.java:93) ~[TickHandler.class:?]
08.10 19:05:34 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_319_TickHandler_tick_WorldTickEvent.invoke(.dynamic) ~[?:?]
08.10 19:05:34 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
08.10 19:05:34 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
08.10 19:05:34 [Server] INFO at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:273) [FMLCommonHandler.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:776) [MinecraftServer.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
08.10 19:05:34 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
08.10 19:05:34 [Server] INFO Caused by: java.lang.StackOverflowError
08.10 19:05:34 [Server] INFO at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_181]
08.10 19:05:34 [Server] INFO at java.lang.ClassLoader.checkPackageAccess(ClassLoader.java:500) ~[?:1.8.0_181]
08.10 19:05:34 [Server] INFO at net.minecraft.world.World.func_190524_a(World.java:554) ~[amu.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.world.World.func_175685_c(World.java:491) ~[amu.class:?]
08.10 19:05:34 [Server] INFO at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52) ~[TileCore.class:?]
08.10 19:05:34 [Server] INFO at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203) ~[TileGrid.class:?]
08.10 19:05:34 [Server] INFO at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:154) ~[BlockCoreTile.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481) ~[awu$a.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.world.World.func_190524_a(World.java:550) ~[amu.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.world.World.func_175685_c(World.java:491) ~[amu.class:?]
08.10 19:05:34 [Server] INFO at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52) ~[TileCore.class:?]
08.10 19:05:34 [Server] INFO at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203) ~[TileGrid.class:?]
08.10 19:05:34 [Server] INFO at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:154) ~[BlockCoreTile.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481) ~[awu$a.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.world.World.func_190524_a(World.java:550) ~[amu.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.world.World.func_175685_c(World.java:491) ~[amu.class:?]
08.10 19:05:34 [Server] INFO at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52) ~[TileCore.class:?]
08.10 19:05:34 [Server] INFO at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203) ~[TileGrid.class:?]
08.10 19:05:34 [Server] INFO at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:154) ~[BlockCoreTile.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481) ~[awu$a.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.world.World.func_190524_a(World.java:550) ~[amu.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.world.World.func_175685_c(World.java:491) ~[amu.class:?]
08.10 19:05:34 [Server] INFO at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52) ~[TileCore.class:?]
08.10 19:05:34 [Server] INFO at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203) ~[TileGrid.class:?]
08.10 19:05:34 [Server] INFO at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:154) ~[BlockCoreTile.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481) ~[awu$a.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.world.World.func_190524_a(World.java:550) ~[amu.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.world.World.func_175685_c(World.java:491) ~[amu.class:?]
08.10 19:05:34 [Server] INFO at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52) ~[TileCore.class:?]
08.10 19:05:34 [Server] INFO at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203) ~[TileGrid.class:?]
08.10 19:05:34 [Server] INFO at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:154) ~[BlockCoreTile.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481) ~[awu$a.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.world.World.func_190524_a(World.java:550) ~[amu.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.world.World.func_175685_c(World.java:491) ~[amu.class:?]
08.10 19:05:34 [Server] INFO at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52) ~[TileCore.class:?]
08.10 19:05:34 [Server] INFO at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203) ~[TileGrid.class:?]
08.10 19:05:34 [Server] INFO at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:154) ~[BlockCoreTile.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481) ~[awu$a.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.world.World.func_190524_a(World.java:550) ~[amu.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.world.World.func_175685_c(World.java:491) ~[amu.class:?]
08.10 19:05:34 [Server] INFO at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52) ~[TileCore.class:?]
08.10 19:05:34 [Server] INFO at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203) ~[TileGrid.class:?]
08.10 19:05:34 [Server] INFO at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:154) ~[BlockCoreTile.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481) ~[awu$a.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.world.World.func_190524_a(World.java:550) ~[amu.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.world.World.func_175685_c(World.java:491) ~[amu.class:?]
08.10 19:05:34 [Server] INFO at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52) ~[TileCore.class:?]
08.10 19:05:34 [Server] INFO at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203) ~[TileGrid.class:?]
08.10 19:05:34 [Server] INFO at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:154) ~[BlockCoreTile.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481) ~[awu$a.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.world.World.func_190524_a(World.java:550) ~[amu.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.world.World.func_175685_c(World.java:491) ~[amu.class:?]
08.10 19:05:34 [Server] INFO at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52) ~[TileCore.class:?]
08.10 19:05:34 [Server] INFO at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203) ~[TileGrid.class:?]
08.10 19:05:34 [Server] INFO at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:154) ~[BlockCoreTile.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481) ~[awu$a.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.world.World.func_190524_a(World.java:550) ~[amu.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.world.World.func_175685_c(World.java:491) ~[amu.class:?]
08.10 19:05:34 [Server] INFO at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52) ~[TileCore.class:?]
08.10 19:05:34 [Server] INFO at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203) ~[TileGrid.class:?]
08.10 19:05:34 [Server] INFO at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:154) ~[BlockCoreTile.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481) ~[awu$a.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.world.World.func_190524_a(World.java:550) ~[amu.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.world.World.func_175685_c(World.java:491) ~[amu.class:?]
08.10 19:05:34 [Server] INFO at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52) ~[TileCore.class:?]
08.10 19:05:34 [Server] INFO at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203) ~[TileGrid.class:?]
08.10 19:05:34 [Server] INFO at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:154) ~[BlockCoreTile.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481) ~[awu$a.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.world.World.func_190524_a(World.java:550) ~[amu.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.world.World.func_175685_c(World.java:491) ~[amu.class:?]
08.10 19:05:34 [Server] INFO at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52) ~[TileCore.class:?]
08.10 19:05:34 [Server] INFO at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203) ~[TileGrid.class:?]
08.10 19:05:34 [Server] INFO at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:154) ~[BlockCoreTile.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481) ~[awu$a.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.world.World.func_190524_a(World.java:550) ~[amu.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.world.World.func_175685_c(World.java:491) ~[amu.class:?]
08.10 19:05:34 [Server] INFO at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52) ~[TileCore.class:?]
08.10 19:05:34 [Server] INFO at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203) ~[TileGrid.class:?]
08.10 19:05:34 [Server] INFO at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:154) ~[BlockCoreTile.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481) ~[awu$a.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.world.World.func_190524_a(World.java:550) ~[amu.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.world.World.func_175685_c(World.java:496) ~[amu.class:?]
08.10 19:05:34 [Server] INFO at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52) ~[TileCore.class:?]
08.10 19:05:34 [Server] INFO at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203) ~[TileGrid.class:?]
08.10 19:05:34 [Server] INFO at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:154) ~[BlockCoreTile.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481) ~[awu$a.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.world.World.func_190524_a(World.java:550) ~[amu.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.world.World.func_175685_c(World.java:492) ~[amu.class:?]
08.10 19:05:34 [Server] INFO at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52) ~[TileCore.class:?]
08.10 19:05:34 [Server] INFO at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203) ~[TileGrid.class:?]
08.10 19:05:34 [Server] INFO at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:154) ~[BlockCoreTile.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481) ~[awu$a.class:?]
08.10 19:05:34 [Server] INFO at net.minecraft.world.World.func_190524_a(World.java:550) ~[amu.class:?]
08.10 19:05:35 [Multicraft] Server shut down (starting)
08.10 19:05:35 [Multicraft] Restarting crashed server in 2.0 seconds
08.10 19:05:35 [Multicraft] Server stopped

**Comment by Nedelosk** [comment]
Seems like a crash of Thermal Dynamics. Please report it to there Github repository. https://github.com/CoFH/Feedback
