### ISSUE TITLE
Strange Apiary bug

### ISSUE THREAD

**Issue by Adam-Kay** [ForestryMC/ForestryMC#2269]
### Specs:
Minecraft version: 1.12.2
Forge version: forge-14.23.4.2766
Forestry version: forestry_1.12.2-5.8.2.352

### Overview
Did not crash, but here is a log of the error that occured:
 **[Gist](https://gist.github.com/GameSlayar/b28f466c750b9399268a048d48c5946d)**

First off, I could not even load my old world running the new version of Forestry. I saw it was a problem with the apiaries from the error code so I rolled back to a previous version of Forestry, removed the apiaries from the world, and then reloaded the game with the most recent Forestry update (listed above). This allowed me to load the world in fine, but when I placed an apiary down, 3 things happened:

1. OneProbe gave me a strange error message on the block description saying "waiting for server". Note everything else on the server, including tile entities like chests, is working fine.
2. Right-clicking on the apiary did nothing, and did not open a GUI of any kind.
3. In my server console, a lot of reoccurring red text and the error message listed above at the Gist link. This code kept repeating itself whenever I attempted to interact with the apiary (I think)

**[Here's an imgur album](https://imgur.com/a/6QlqRfY)** with a few screenshots in order of what happened.

It seems to be a problem with my world I think? Because when I tried reproducing it in a seperate world with just Forestry, the Apiary worked normally. It seems like it might be a bad interaction with another mod. Hopefully I can somehow recover my world and still be able to use apiaries?

**Comment by Nedelosk** [comment]
The issue has nothing to do with your world. It was a bug on our side and should be fixed with the next version. http://jenkins.ic2.player.to/job/Forestry_1.11/354/
