### ISSUE TITLE
Some "hint" texts in Chinese lack context

### ISSUE THREAD

**Issue by bbbbbbbbba** [ForestryMC/ForestryMC#2274]
In en_us.lang:

    for.hints.flowerjungle.desc=Jungle flowers are ferns or vines.
    for.hints.flowerjungle.tag=What's a jungle flower?
    for.hints.flowernether.desc=Netherwart are the nether flowers.
    for.hints.flowernether.tag=What's a nether flower?

In zh_cn.lang:

    for.hints.flowerjungle.desc=指蕨类和藤蔓。 # "They are ferns or vines."
    for.hints.flowerjungle.tag=什么是丛林花？
    for.hints.flowernether.desc=指地狱疣。 # "They are Netherwart."
    for.hints.flowernether.tag=什么是下界花？

In the game, the "desc" strings sometimes appear without the "tag" strings, leaving the player wondering what they are supposed to mean.

This probably affects some other languages and/or other strings. In particular, zh_tw.lang seems to have the same problem.

**Comment by zetaraku** [comment]
Maybe you should provide a screenshot?

**Comment by bbbbbbbbba** [comment]
So this is the thing: in the bee house GUI, if you leave the purple "hint" tab open, it will be still open when you use the GUI the next time. Since the "desc" text is shown in the tab itself (when it is open), and the "tag" text is a hover text (that displays whether the tab is open or closed), if you leave the "hint" tab open from the last time, then you will see the answer before the question.

![2018-10-29_09 19 06](https://user-images.githubusercontent.com/6083021/47664258-e842d100-db5b-11e8-858e-ba0d627e4d29.png)
![2018-10-29_09 19 44](https://user-images.githubusercontent.com/6083021/47664257-e842d100-db5b-11e8-874f-5d5663ae7dea.png)

**Comment by zetaraku** [comment]
Oh, I see the problem.
```
# en_us.lang
for.hints.flowerjungle.desc=Jungle flowers are ferns or vines.
```
```
# zh_cn.lang
for.hints.flowerjungle.desc=指蕨类和藤蔓。 # "They are ferns or vines."
```
The meaning of "**Jungle flowers** are" should not be translated into "**They** are".

The Chinese translation assumed the context of the tag and omitted it in the description.
The description (desc) should be self-complete, not just an "Answer" depending on the "Question" (tag).
Updating the lang file will fix it.

**Comment by Nedelosk** [comment]
@bbbbbbbbba, @zetaraku Feel free to make a PR and fix this issue.

**Comment by zetaraku** [comment]
@bbbbbbbbba I have done it. Can you take a look for the zh_cn translation at #2290?

**Comment by bbbbbbbbba** [comment]
@zetaraku Looks good to me :)
