### ISSUE TITLE
[1.12.2] Hives no longer deal damage to players/mobs.

### ISSUE THREAD

**Issue by SonicX8000** [ForestryMC/ForestryMC#2289]
Minecraft: 1.12.2
Forge: 14.23.5.2772
Mods: 1
*forestry_1.12.2-5.8.2.362*

Info:
I recall in older versions that... when near a hive... it will slowly damage you. If you left-clicked it by mistake then you get swarmed and take damage rapidly.

In the current version of the mod, as far as I know... being near the hive no longer deals damage and if I smack it and get swarmed it deals no damage to me or any mobs. Game difficulty was set on Hard.

I've tried checking the config and noticed these lines...

    hivedamage {
        # The bees only attack the player if he starts to destroy the hive. [default: false]
        B:onlyOnAttack=false

        # Whether bees can damage other entities than the player. [default: false]
        B:onlyPlayers=false

        # Whether bees can damage a player playing on peaceful mode. [default: false]
        B:peaceful=false

        # Whether bees can damage a player while they are underwater. [default: true]
        B:underwater=true
    }

I assume "onlyOnAttack" just disables the slow damage being dealt while being near the hive but apparently having it set to FALSE prevents the hives from dealing damage to players/mobs. If set to TRUE the will hive only damage players/mobs if you smack it. You will still take damage if you destroy the hive no matter if false/true.

Is this intended by any chance?

**Comment by zetaraku** [comment]
Can confirm that. The player only takes damage once when the hive is completely destroyed.
It is unreasonable not being bitten when you're breaking a unsmoked beehive. 😄 

Here is the description in the lang file too:
https://github.com/ForestryMC/ForestryMC/blob/15207773d5371efb442cdcf01d021eaf4041bb40/src/main/resources/assets/forestry/lang/en_us.lang#L1824-L1825

**Comment by SonicX8000** [comment]
Is it intended for the Hives to not damage you at all with the config option "onlyOnAttack" set to 'False' though?

In older versions when you're near a Hive you take damage very slowly and take damage rapidly when you bother it if that option was set to 'False'.

**Comment by zetaraku** [comment]
Since it says "only", so I think the opposite should be "not only".

**Comment by shortybsd** [comment]
Has this not been looked at yet by the devs? Currently running forestry_1.12.2-5.8.2.380 and zero damage. I can smack a hive and see the bees coming after me, yet no damage.

Also with version forestry_1.12.2-5.8.1.322 the bee damage works like normal. Also note: the config from the older version doesn't have options for 

```
       # The bees only attack the player if he starts to destroy the hive. [default: false]
        B:onlyOnAttack=false

        # Whether bees can damage other entities than the player. [default: false]
        B:onlyPlayers=false
```

**Comment by SniperHauss89** [comment]
I'm very curious about this issue as well. I've been maintaining a small server for a few months and didn't realize when this behavior first started. I'm all for realism and liked how it was in older versions as well. Hoping this is just a bug.

**Comment by temp1011** [comment]
This is definitely a bug.
