### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by ScienceDrummer** [ForestryMC/ForestryMC#2292]
I believe it's this mod, please correct me if wrong.

https://paste.dimdev.org/sawehenuca.mccrash

**Comment by temp1011** [comment]
That's a weird crash. Does it happen a lot?

**Comment by ScienceDrummer** [comment]
Every time I have a mod that adds additional bees to the game it seems.

**Comment by MauveCloud** [comment]
Did you actually install Forestry?  Searching the linked crashlog for it only finds it in the stacktrace (not in the list of mods below), so I'm wondering if you installed a mod that requires Forestry without installing Forestry itself.

**Comment by ScienceDrummer** [comment]
Funny, because now it's saying that it's not even installed when I clearly have it. 

https://imgur.com/a/U3q8ycs

**Comment by temp1011** [comment]
Seems like something is wrong with your install but I don't know what.

**Comment by ScienceDrummer** [comment]
Was working perfectly before it updated to a certain version.

**Comment by ScienceDrummer** [comment]
Ok, figured out why it wasn't detecting it. The file never downloaded so I got an empty shell of the mod. Let me try it out now.
