### ISSUE TITLE
Charcoal amount.base option not working as expected

### ISSUE THREAD

**Issue by pyure** [ForestryMC/ForestryMC#2294]
Greetings Forestry Team,

The new config option (I:amount.base) for the charcoal pits does not seem to be working as desired.  Our team (Infitech) ran a series of tests and observed a couple of odd behaviours.

Setting to 7 and 8, we got expected results when shoveling the ash block.  For some other numbers (2,3) no charcoal was dropped.

In cases where the drop worked correctly, the ash block had meta data corresponding to the expected number.  We observed other cases where the meta data was always 0.

We weren't able to confirm 100% if the zero drops corresponded to 0 meta data (its hard to test due to the wait times)

Version: **forestry_1.12.2-5.8.2.365.jar**
Forge: **2771**

**Comment by Agrax** [comment]
Bump. Any news on that @Nedelosk? We'd appreciate a solution or at least an update providing us with the ETA :P
