### ISSUE TITLE
Missing Recipe on update. 1.12.2-5.8.2.371

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#2295]
Hi. 
I miss the recipe forestry:frame_proven.

Please give update for 1.12.2

Thanks

![missing_frame_recipe](https://user-images.githubusercontent.com/10398117/48291088-6c0e8e80-e475-11e8-880b-6a36762711be.PNG)

**Comment by Nedelosk** [comment]
There is no recipe for the proven frame. You have to buy it from a villager.

**Comment by ghost** [comment]
Thanks.
