### ISSUE TITLE
Why missing blocks on update? 1.12.2-5.8.2.371

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#2296]
Watch out the picture, please. 

![forestry_missing_blocks](https://user-images.githubusercontent.com/10398117/48290725-23a2a100-e474-11e8-81f5-daadd14e8453.PNG)

**Comment by Nedelosk** [comment]
They were removed because they had no real use.

**Comment by ghost** [comment]
Thanks.
