### ISSUE TITLE
Beta Versions - Crated Oak, Spruce, Birch, Jungle, Acacia, and Dark Oak Sapling items cause severe game lag

### ISSUE THREAD

**Issue by TheOrionsun** [ForestryMC/ForestryMC#2299]
Hello,

I have been testing the beta versions of Forestry and found an issue that caused my survival game to come to a standstill (Severe Lag). I found the issue when using JEI mod and did a search where the Crated xxx Saplings would show on the screen. No issues until the items are displayed.

I created a new creative game with only Forestry mod loading and then tested back to each Bata release until I found where it started to create lag. Beta version 1.12.2-5.8.1.328 tests out OK. The next Beta release 1.12.2-5.8.1.334 starts to lag out with any of the crated saplings showing on the screen. If the item is in the inventory and it is closed all is ok, but open inventory where the item is displayed and lag starts. So, get lag only when the item is shown on the display.

To recreate issue: 
Minecraft version 1.12.2
Forestry version Beta 1.12.2-5.8.1.334 to most recent Beta version.
Java versions; 1.8.0_171 and then tried most recent java 8 version 1.8.0_191.

I realise these are Beta versions and may have bugs, so this is just an FYI before there is another release version...

Thank you for your excellent Mod and all the time everyone working on Forestry has given.

TheOrionSun

**Comment by Nedelosk** [comment]
@mezz Any idea what could cause this?

**Comment by mezz** [comment]
They may be a bit slow to render in general, and if you have all of them on-screen at once it could add up.
Are crate models cached?

**Comment by TheOrionsun** [comment]
The crated saplings are the only crated items that do it. All the other crated items are fine (no lag) when shown without the crated saplings showing on the screen. In my test I used just one crated oak sapling placed in my inventory...

**Comment by mezz** [comment]
I tested this on my machine and didn't see any kind of slowdown.

The changes between 328 and 334 are here Nedelosk:
https://github.com/ForestryMC/ForestryMC/compare/fdee27254da0d7f52485209b1f35a6faef4b8036..4a3e40d299f6e0c64ae3c58f0092877b1b1a8a78
There's definitely a change to the crate rendering code, but it's not clear why that would impact some machines and not others.

**Comment by TheOrionsun** [comment]
It may be my system or drivers.

I have a GeForce GTX 1080 with driver version 416.34 - I see there is an update...

Is there a version of Forge that is not supported? Current version is 14.23.5.2772.

Did you test using twitch/curse to create a profile?

Anything else you can think of I may try?

**Comment by TheOrionsun** [comment]
I think it may have been a resource pack. I tested again with just Forestry loading and noticed there was still  one vanilla resource pack loading that changed the resolution of the saplings. I removed the resource pack and all works fine now.

Sorry to waste your time mezz, Nedelosk and anyone else...

I will have to see why these textures are causing an issue when none of the other crates had an issue.

Thank you for all your time and all the time you put into this mod...

**Comment by TheOrionsun** [comment]
I changed the textures of the saplings, which were at 512x512, to 256x256 and the fps went from 1 to 4. So, I dropped them to vanilia default of 16x16 and have no fps drop from on screen to not on screen.

How these sapling textures are rendering on the crate texture looks to be the issue (not able to increase textures above 16x16 and not have lag). I have all blocks rendered at 512x512 for the other crates with no issues. 

I am not able to look at the changes between 328 and 334 and see why the rendering is different for the sapling crates compared to the other item crates. 

Do the saplings crates render differently than the other item crates?

mezz, can you try increasing the texture resolution of saplings and see if you can confirm the issue? 

Thank you,

**Comment by mezz** [comment]
Ok the 512 texture pack was definitely the missing piece, I was able to replicate the issue.
For my testing I am using the SapixCraft Resource Pack 512x.

I think it is because of the large number of quads.

The 512x sapling in-hand has 2152 quads, and just 1 quad in inventory.
The crate in-hand has 4138 quads from each facing in the hand and in the inventory (28966 total quads).

**Comment by mezz** [comment]
With some small tweaks I was able to get the crate rendering for saplings down to 16 quads (even with a 512x texture pack), which clears up the performances issue.

**Comment by mezz** [comment]
It's up on curseforge now as beta 1.12.2-5.8.2.373

**Comment by TheOrionsun** [comment]
Awesome, I will test it today...

Thank you for all your time with this issue.
