### ISSUE TITLE
Skyblock

### ISSUE THREAD

**Issue by Gysburi** [ForestryMC/ForestryMC#2303]
Hives don't spawn in skyblock maps...
There is any way to force spawn? 
Please make hives craftable or add a special hive wich change when placed in a biome.

**Comment by Nedelosk** [comment]
Like many other mods, forestry does not support skyblock by itself. `ExNihilo` added the `Scented Artificial Hive` in older mc versions. But the current port of `ExNihilo` for 1.12 has nothing like this.
https://github.com/BloodyMods/ExNihiloCreatio/issues/114
