### ISSUE TITLE
wax cast just... unusable

### ISSUE THREAD

**Issue by Azutte** [ForestryMC/ForestryMC#2304]
forestry_1.12.2-5.8.2.366, the version in the latest dw20 ( @FTBTeam ) 
[an illustrative video](https://www.youtube.com/watch?v=ouldFU7k_LA)

**Comment by Azutte** [comment]
shown with enchantment, bug existed without enchantment, opted to see if it changed anything (no)

**Comment by temp1011** [comment]
![recipe](https://user-images.githubusercontent.com/34900092/48955516-33c38180-ef46-11e8-91e3-0e3db01c918e.png)
Does this recipe work?

**Comment by Azutte** [comment]
![2018-11-23_16 18 05](https://user-images.githubusercontent.com/6581284/48962856-69af3880-ef3b-11e8-86fb-4c1e8955f07c.png)
No, not even if I warm it up with another recipe first, I just can't click the cast into it.

**Comment by Azutte** [comment]
both casts I'm trying have a metadata of zero, I can't insert it (into that slot) via side or top, I can't JEI [+] it into the slot.

**Comment by temp1011** [comment]
I tried as well in the DW20 pack and it didn't work. So it seems like there is a conflict/recipe change somewhere that breaks this.

**Comment by temp1011** [comment]
The fix wasn't explained but here is the same issue: https://github.com/AllTheMods/ATM-3/issues/752

**Comment by TheXTrunner** [comment]
this issue hasn't been solved yet? I'm playing on FTB Revelation which has forestry 8.1 I think, and the wax cast doesn't work

**Comment by temp1011** [comment]
Please try without baubles, forgot to comment on this issue too

**Comment by TheXTrunner** [comment]
that's gonna be tough, can't disable it without also disabling thaumcraft, astral sorcery and another dependency that i forgot

**Comment by temp1011** [comment]
Sure, but you could create a test world and it might prove that at least it causes the conflict.

I used `FTBPresentsDirewolf20112-2.5.0-1.12.2` and disabled:
```
astralsorcery-1.12.2-1.10.11.jar.disabled
Baubles-1.12-1.5.2.jar.disabled
Botania r1.10-360.jar.disabled
Thaumcraft-1.12.2-6.1.BETA26.jar.disabled
ThaumicJEI-1.12.2-1.5.5-23.jar.disabled
```
Then the wax cast worked fine. So there is a cross mod conflict with one of these (baubles almost certainly). 

I haven't looked far enough to work out whether this is something weird that forestry is doing but given lots of other mods seem to work fine I would say it's quite likely that baubles is causing this issue.

**Comment by TheXTrunner** [comment]
Ok baubles had apparently a ton of dependencies, after disabling quite a lot of mods I got to make the wax cast work, here's the complete list:
```
Modpack: FTB Revelation (Modified)
Mods:
ActuallyBaubles-1.12-1.1.jar.disabled
astralsorcery-1.12.2-1.10.20.jar.disabled
Baubles-1.12-1.5.2.jar.disabled
Botania r1.10-361.jar.disabled
deepresonance-1.12-1.8.0.jar.disabled
EmbersRekindled-1.12.jar.disabled
EnderIO-1.12.2-5.1.51.jar.disabled
Exchangers-1.12.2-2.8.jar.disabled
IntegrationForegoing-1.12.2-1.9.jar.disabled
mcjtylib-1.12-3.5.4.jar.disabled
nice-1.12-0.4.0.jar.disabled.
notenoughwands-1.12-1.8.1.jar.disabled
rftools-1.12-7.72.jar.disabled
rftoolsctrl-1.12-2.0.2.jar.disabled
rftoolspower-1.12-1.2.0.jar.disabled
secretroomsmod-1.12.2-5.6.4.jar.disabled
SimplyJetpacks2-1.12.2-2.2.13.66.jar.disabled
Soot-1.5.jar.disabled
haumcraft-1.12.2-6.1.BETA26.jar.disabled
ThaumicInventoryScanning_1.12.2-2.0.10.jar.disabled
ThaumicJEI-1.12.2-1.6.0-27.jar.disabled
theoneprobe-1.12-1.4.28.jar.disabled
topaddons-1.12.2-1.11.0.jar.disabled
twilightforest-1.12.2-3.9.984-universal.jar.disabled
WirelessCraftingTerminal-1.12.2-3.12.93.jar.disabled
xnet-1.12-1.8.2.jar.disabled
```

**Comment by temp1011** [comment]
Thanks for investigating! I've narrowed this down a bit further and I suspect that Astral Sorcery is the culprit here. I've opened an issue on their tracker: https://github.com/HellFirePvP/AstralSorcery/issues/1191
