### ISSUE TITLE
[1.12.2] java.lang.ArrayIndexOutOfBoundsException 

### ISSUE THREAD

**Issue by MokahTGS** [ForestryMC/ForestryMC#2306]
forestry_1.12.2-5.8.2.374
Forge 2768

Crash Log: https://pastebin.com/NFJqwBi0

Full mod list: https://pastebin.com/J5w3TyBA

**Comment by temp1011** [comment]
Looks like foamfix parallel model baking conflicts with the latest changes to crate rendering.

**Comment by temp1011** [comment]
Can't reproduce with foamfix parallel model baking turned on, though. But this could be some kind of specific race condition I guess? Maybe I am just wrong.

**Comment by temp1011** [comment]
Looks like this is a problem with foamfix (https://github.com/AllTheMods/ATM-3/issues/781), but it is intermittent.
