### ISSUE TITLE
White Screen on startup

### ISSUE THREAD

**Issue by rivcior** [ForestryMC/ForestryMC#2307]
Hello when i starting minecraft with forestry for minecraft 1.2.5 for a 2 seconds i have mojang logo then white screen when i look to launcher log there are written...  -58 item slot already occupied by forestry.ItemResource@3b60cc97 while adding forestry.ItemResource@2cbb1bd5

What can i do?

**Comment by temp1011** [comment]
Not sure, pretty sure the code for those versions isn't available and 1.2.5 definitely isn't supported. So I would just try removing other mods/other troubleshooting to work it out. Also, a full log would probably say more.

**Comment by rivcior** [comment]
Here's the log
Forestry: MinecraftForge minor version mismatch, expecting 3.0.x, may lead to unexpected behavior
--
20:09:32 | game | CONFLICT @ -58 item slot already occupied by forestry.ItemResource@358fcf9a while adding forestry.ItemResource@61a3e853
20:09:32 | game | IndustrialCraft 2: MinecraftForge minor version mismatch, expecting 3.3.x, may lead to unexpected behavior
20:09:32 | game | [IC2] Config loaded from C:\Users\Kuba\AppData\Roaming\.minecraft\config\IC2.cfg
20:09:32 | game | [IC2] Using 32 audio sources.
20:09:32 | game | Exception in thread "Minecraft main thread" java.lang.NoSuchMethodError: ic2.api.Ic2Recipes.addMatterAmplifier(Laan;I)V
20:09:32 | game | at mod_IC2.load(mod_IC2.java:485)
20:09:32 | game | at cpw.mods.fml.common.modloader.ModLoaderModContainer.init(ModLoaderModContainer.java:356)
20:09:32 | game | at cpw.mods.fml.common.Loader.modInit(Loader.java:273)
20:09:32 | game | at cpw.mods.fml.common.Loader.initializeMods(Loader.java:628)
20:09:32 | game | at cpw.mods.fml.client.FMLClientHandler.onLoadComplete(FMLClientHandler.java:223)
20:09:32 | game | at net.minecraft.client.Minecraft.a(Minecraft.java:429)
20:09:32 | game | at net.minecraft.client.Minecraft.run(Minecraft.java:738)
20:09:32 | game | at java.lang.Thread.run(Thread.java:745)
20:09:43 | monitor | Process ended with exit code 0

**Comment by temp1011** [comment]
```
Forestry: MinecraftForge minor version mismatch, expecting 3.0.x, may lead to unexpected behavior
```
This might be your problem..

**Comment by rivcior** [comment]
Do you know how can i fix it
(i have 3.4.* forge)

**Comment by temp1011** [comment]
Looks like there are lots of old versions of forge available at http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.2.5.html. Or a different version of forestry might help.

**Comment by rivcior** [comment]
??? how can i install different version forestry for minecraft 1.2.5 there is only 1
for this version

**Comment by Nedelosk** [comment]
Sorry but we no longer support versions that old. We do not even have an active developer that was active around that time.
