### ISSUE TITLE
Lighting problems with stairs

### ISSUE THREAD

**Issue by huangvincent170** [ForestryMC/ForestryMC#2321]
Minecraft 1.12.2, Forestry v. 5.8.2.374
No other mods installed

Smooth Lighting: off causes lightning problems with forestry stairs.

Smooth Lighting off:
![2018-12-18_18 11 42](https://user-images.githubusercontent.com/45437908/50188762-ada21d00-02f0-11e9-8209-a4c85f7d5084.png)

Smooth Lighting minimum:
![2018-12-18_18 11 50](https://user-images.githubusercontent.com/45437908/50188774-b8f54880-02f0-11e9-8534-44c51cb6524e.png)

**Comment by eliavah** [comment]
@Nedelosk  the dark lightning seems to be able to spawn monsters as well. i have vanilla stairs without the lighting error *still says sky 0 and block 0 lighting like the forestry) that doesn't spawn mobs, and the forestry stairs seem to spawn mobs on top of all my roofs (with lights near the stairs)

**Comment by devtolove** [comment]
I, too, faced this kind of problem a long time ago, somewhere even open discussion on the subject. My nephew is playing meincraft and also faced with the problem of lighting in the game, after so many years they have not fixed it ... Can take advantage of several ways to solve the [lighting bug in Minecraft](https://techdap.com/minecraft-fix-lighting-errors/), I used the cache clearing and it helped this time
