### ISSUE TITLE
[1.12.2] Cherry tree are broken in latest build

### ISSUE THREAD

**Issue by martyna777** [ForestryMC/ForestryMC#2325]
Today I change build too 5.8.2.374 and I notice that ther's no fruid dots on my cherry tree.
I destroy couple leaf blocko, and then chop tree and don't get any cherry fruids.

![tree](https://user-images.githubusercontent.com/46083478/50382538-7d68ce80-06a2-11e9-85fc-168cdab6f81e.png)

**Comment by Nedelosk** [comment]
We changed the fruit system in the last versions of forestry. Unfortunately, there was no way to update the old trees to the new system. But every tree you plant now should have fruits again. Not on every leaf but now they will definitely give you the fruit and not only with a small chance.
