### ISSUE TITLE
Forestry invalid named sapling causes crash because of language

### ISSUE THREAD

**Issue by nrslow** [ForestryMC/ForestryMC#2329]
https://pastebin.com/CBg6LT3L

FTB Continuum 1.5.2 version. Help please :/

**Comment by temp1011** [comment]
Continuum issue: https://github.com/FTBTeam/FTB-Continuum/issues/509.

I'm not sure how this occured.

**Comment by Arkzenir** [comment]
I had the same issue, have you tried changing your system language to English, reinstalling everything and trying again?

**Comment by Nedelosk** [comment]
Closed because of no response.
