### ISSUE TITLE
Questions about the single and multi-block farms

### ISSUE THREAD

**Issue by Flaksmith** [ForestryMC/ForestryMC#2331]
I'm just getting back into modded MC after not touching the game for at least 5 years, last time I was using forestry you guys were phasing out the old single block farms and loggers etc. in favour of the multi-block farms. Now I see that the single block ones are back(?) and have new recipes (iirc the original ones had their recipes removed entirely), however I can't find any information on the wiki (still says they're obsolete) about them and how they differ from the mulit-block farms. Neither the 3 (lol) ftb wikis, nor about 10 different google searches could give me the answer either, and the irc linked from the forestry wiki seems dead, so I'm hoping anyone here can kindly fill me in as I'm really out of the loop. Thanks.

**Comment by TheSledgeHammer** [comment]
Both single and multi-block farms are valid. They are nearly identical to the originals in how they work. Each single block farm can only do what the name suggests. A peat-bog farm can only grow peat, an arboriculture will only do trees... etc.
The difference is multi-block farms can be of different sizes, not a fixed size, can have up to four different types i.e. peat, trees, nether wart and generic farm (wheat, potatoes etc) on a single multi-block farm. Can be fully automated or manual i.e. will harvest and plant crops using an internal inventory. Single block farms may be able to do the last point as well (automated) but often requires a more complicated setup to get working.

**Comment by Flaksmith** [comment]
That really clears things up for me, thanks!
