### ISSUE TITLE
Automatic tree farm not working

### ISSUE THREAD

**Issue by Neuromantix** [ForestryMC/ForestryMC#2352]
Automatic tree farm don't normal work - trees grows, but all saplings goes to production slots, not sapling slots. I use vanilla oak saplings and forestry apple oak saplings - nothing change. If i put saplings in sapling slot manually - works fine.
screenshot https://imgur.com/a/jnGG1zW

**Comment by Nedelosk** [comment]
This is not a bug it is a feature. #1087
