### ISSUE TITLE
[question] is someone having obsolete MC 1.6.4-2.3.1.1 development files from sengir?

### ISSUE THREAD

**Issue by leagris** [ForestryMC/ForestryMC#2357]
I try to reconstruct the development environment for an old 1.6.4 mod that depends on forestry-A-2.3.1.1

I'd need the API zip and the deobfuscated jar files:
`forestry-A-2.3.1.1_dev.jar`
`forestry-api-2.3.1.1.zip`

or at least:
`forestry-A-2.3.0.1_dev.jar`
`forestry-api-2.3.0.1.zip`

Web archive.org only has a directory index snapshot.

https://web.archive.org/web/20170305033507/http://forestry.sengir.net/files/forestry/releases/2.3.0.1

**Comment by Manuepolis23** [comment]
http://jenkins.ic2.player.to/job/Forestry/4/
this may be useful

**Comment by leagris** [comment]
The IC2 jenkins only has Forestry 4 that is not forestry 2.3, not even forestry 3

**Comment by temp1011** [comment]
https://mcarchive.net/mods/forestry has the non dev version. Maybe your best option is to decompile and use that.
