### ISSUE TITLE
Farm Multiblock Inventory crash

### ISSUE THREAD

**Issue by btrainn** [ForestryMC/ForestryMC#2362]
I am having problems with the farm multiblock.  I built the structure and went inside the inventory, I crashed. 
I reinstalled forestry to the latest version but, I think it has made the problem worse.
I got a different error after reinstallation, so im going to post both crash logs
Error Before
https://gist.github.com/btrainn/a540974e127bcc1ab124966a69fcd977
Error After
https://gist.github.com/btrainn/11a976629118c3c634018113b5a5c71b

If you have a solution please help, I would like my world back

**Comment by Nedelosk** [comment]
The first crash was fixed with one of the last updates. I have no idea what causes the second crash.
