### ISSUE TITLE
Bugs head

### ISSUE THREAD

**Issue by TheKlimoT** [ForestryMC/ForestryMC#2364]
I I put my head on, then dropped it, and picked it up, and I got dressed right away 
https://gamestores.pictures/images/2019/02/09/MJEPw.png

**Comment by TheKlimoT** [comment]
[](https://gamestores.pictures/images/2019/02/09/MJEPw.png)

**Comment by Nedelosk** [comment]
Seems more like a bug of minecraft and not a bug of forestry.

**Comment by TheKlimoT** [comment]
it's not bug minecraft, i go test singleplayer, and multiplayer.... i delete forestry... bugs invise.
