### ISSUE TITLE
Single block farms: North isn't North

### ISSUE THREAD

**Issue by Nightcaste** [ForestryMC/ForestryMC#2367]
I have built a few of the single block farms, like the crop farm, mushroom farm, and ender farm.  In the UI, the slots for the seeds are labelled N, S, E, W.  This would lead one to believe that this allows you to control which plants are being grown on the North, South, East, and West sides of the farm.  The problem is that the seeds placed in the North slot end up planted on the East side of the farm.  I have not yet tried more than two plants at a time, so I am not sure if the other directions are also rotated.

The pack is Enigmatica 2 Expert mode, version 1.54.  
The Forestry version is 5.8.2.382

**Comment by temp1011** [comment]
Looks like there is an off by one error somewhere, I'll try and track it down
