### ISSUE TITLE
java.lang.NullPointerException: Rendering ingredient 

### ISSUE THREAD

**Issue by steuberj** [ForestryMC/ForestryMC#2368]
First had issue when typing "Cr" into the JEI search bar before promptly crashing.  I can no longer open the inventory without the game freezing and setting me back to the launcher.  Presumably something called "Crated Pollen" is causing this crash? [Line 80 in the log!]

I was using Forestry version:
forestry_1.12.2-5.8.2.382.jar 

Crash log:
https://gist.github.com/Flookh/3945628ae08dc749b7024e7987aae07d

**Comment by temp1011** [comment]
See https://github.com/mezz/JustEnoughItems/issues/1462
