### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by NavedNoor** [ForestryMC/ForestryMC#2369]
The server crashed after placing the Multifarm Blocks and trying to access it. Server stops when you try to join, can't play anymore. Have a look at the crash log:
https://gist.github.com/NavedNoor/4030dcea50905ef07a1bc337759345e5

**Comment by temp1011** [comment]
Duplicate of https://github.com/ForestryMC/ForestryMC/issues/2340? Updating should fix this.
