### ISSUE TITLE
Forestry Multifarm Crash

### ISSUE THREAD

**Issue by BipBip21** [ForestryMC/ForestryMC#2370]
Thank you for reporting!

For issues:
 * Try the latest version, it may have fixed the issue already.
 * If you crashed, please paste the crash log to [gist](https://pastebin.com/qbfne5jG link it here.
Hello, I have a problem. I created my personal mod set. I had a problem when I put farm hatch into a multi-farm. Minecraft crashes. Please, help. I already put an earlier version. Logs I have attached.

**Comment by temp1011** [comment]
https://github.com/ForestryMC/ForestryMC/issues/2340

**Comment by BipBip21** [comment]
> 
> 
> #2340

After deleting buildcraft start working

**Comment by temp1011** [comment]
Updating forestry should also fix this

**Comment by BipBip21** [comment]
> 
> 
> Updating forestry should also fix this

Thanks, it works, now with buildcraft.
