### ISSUE TITLE
Farm Control not responding to signal

### ISSUE THREAD

**Issue by Purple-Towel** [ForestryMC/ForestryMC#2377]
I'm experiencing an issue with my multifarm not responding properly to any levers placed on either the sides or the top with the 5.8.2.383 build. I tried several variations of placing redstone down and having the lever be placed in different positions but it doesn't seem to help at all wherever I place things.

**Comment by Spauldo** [comment]
I'm seeing the same thing on 5.8.2.387.  Farm works fine otherwise.

Edit: Actually, it seems like it stops planting, but harvesting keeps going.  This is on a tree farm - I haven't tested other farms.

**Comment by ilightwas** [comment]
I experienced the same behavior on 5.8.2.387, side deactivation don't stop the farm planting or gathering. It only stops if it's a top redstone signal, in which case stop the whole farm.

edit: I figured out that the side turn off only works if the control block is placed bellow the dark line formed by the multiblock.
