### ISSUE TITLE
BottlerRecipeMaker#getBottlerRecipes is slow

### ISSUE THREAD

**Issue by ichttt** [ForestryMC/ForestryMC#2381]
So, I'm profiling the start of a large modpack right now (All The Mods Remix) and found that BottlerRecipeMaker#getBottlerRecipes takes a long time to complete.
![Screenshot](https://user-images.githubusercontent.com/20151702/53695018-a601f880-3db6-11e9-9d74-a4f04b0297cb.png)
The largest amount of time is spend on copying the itemstack, so my question is if the itemstack needs to be copied at all.
I sadly do not know this code well enough to judge this.

**Comment by temp1011** [comment]
Build 5.8.2.384 should work better with this, but if there is still a hotspot things can probably be improved more.

**Comment by temp1011** [comment]
did this help @ichttt ?

**Comment by ichttt** [comment]
Yes, it improved things a lot from what I could see

**Comment by temp1011** [comment]
cool, let us know if there's anything else that is slow
