### ISSUE TITLE
Leaves causing crash? ("ItemStack must be for default leaves.")

### ISSUE THREAD

**Issue by Starra** [ForestryMC/ForestryMC#2385]
I was using the Illuminati Pet from the Inventory Pets mod and it gave me Grammar Leaves, which caused my world to crash. 

This is the crash report from when it happened yesterday: [https://pastebin.com/ddv3W5JQ](https://pastebin.com/ddv3W5JQ)
And this is the crash report from when I tried to load the world up again today: [https://pastebin.com/Y93vC3ms](https://pastebin.com/Y93vC3ms)

I'm not sure if it's the same issue as [this](https://github.com/ForestryMC/ForestryMC/issues/1865), since I don't have Binnie's Mods installed.

Apologies if this is somehow not Forestry related.

**Comment by temp1011** [comment]
Seems like https://github.com/ForestryMC/ForestryMC/issues/2336

**Comment by Starra** [comment]
You're right, it appears to be the same issue. I somehow didn't catch that one, my bad!

**Comment by kreezxil** [comment]
Is this the same crash then?

I had a player report that their client crashed out while harvesting leaves.

https://pastebin.com/ch0ViS6B

forestry: 1.12.2-5.8.2.387
forge: 14.23.5.2821
