### ISSUE TITLE
Server crashed upon placing multi-farm

### ISSUE THREAD

**Issue by Tsutek** [ForestryMC/ForestryMC#2386]
Not sure whats causing this but help would be greatly appreciated. Error happened as soon as the last block of a multi-farm was placed. 

Thanks in advance.

https://gist.github.com/Tsutek/579bfc5c844323984ab349bb972f344b

**Comment by temp1011** [comment]
Looks same as https://github.com/ForestryMC/ForestryMC/issues/2370. Updating forestry will fix this.

**Comment by turbodiesel4598** [comment]
Using latest Forestry and Buildcraft, this error seems to have resaurfaced. Looks like the BuildCraft Transport API's name has changed again, and so the method does not exist and calling it crashes the game.
