### ISSUE TITLE
Multifarm structure with Agricraft

### ISSUE THREAD

**Issue by AyyItsShanye** [ForestryMC/ForestryMC#2387]
I've been trying to automate the production of soybeans from Pam's Harvestcraft, using Forestry's multifarm structure. However, the machine refuses to harvest any of the plants. I have it set to manual orchard, but it won't harvest any plants I give it, even vanilla crops. If anyone could help, I'd greatly appreciate it. Thanks!
![image](https://user-images.githubusercontent.com/48456428/54157393-37581700-4416-11e9-95ca-07d70a4f2c0d.png)
![image](https://user-images.githubusercontent.com/48456428/54157404-3d4df800-4416-11e9-8310-a8b647a074fe.png)
![image](https://user-images.githubusercontent.com/48456428/54157410-43dc6f80-4416-11e9-9dfb-fcea0ca2cb9c.png)

**Comment by Nedelosk** [comment]
There currently is no compatibility with Agricraft. #2189
