### ISSUE TITLE
Tried building each size farm, it claims the farm is too large, despite following wiki

### ISSUE THREAD

**Issue by Solverbolt** [ForestryMC/ForestryMC#2392]
Playing on FTB Ultimate Reloaded Version 1.0.1,  MC version 1.12.2, 
Does not matter the size, followed directions very carefully, it wont register it as a valid build. Regardless of how i do it. If i have just central structure though, it will give a gui but wont work as it does not have the petals section, but if I build the petals section, both according to wiki, and what forestry is telling me, trying each, it wont register as valid

**Comment by Solverbolt** [comment]
the error its giving me is that it can only be, at most, 5 blocks wide, which means that it wont form for anything more than the base size of the central tower

**Comment by MauveCloud** [comment]
A screenshot might help to confirm, but it sounds like you are trying to use the "farm block" block to lay out the farmland area (the "petals" as you call it), instead of using the substrate block (e.g. stone bricks, smooth sandstone, bricks) for that part.

**Comment by Solverbolt** [comment]
![image](https://user-images.githubusercontent.com/38087746/54657389-7c1f2600-4a86-11e9-9d89-735f92db9d77.png)

**Comment by Solverbolt** [comment]
that is what the wiki showed to do

**Comment by MauveCloud** [comment]
Which wiki are you following?  Either that wiki was wrong, or you misinterpreted it.  That's definitely not the way to build a multifarm.  Admittedly, https://forestryforminecraft.info/farms:structure doesn't have a good sample picture.  The left picture at https://ftbwiki.org/MultiFarm might help you.

**Comment by Solverbolt** [comment]
I have done it that way also in the picture, the picture above, is the latest attempt. 
![image](https://user-images.githubusercontent.com/38087746/54658106-239d5800-4a89-11e9-9c7b-2ab7c291e999.png)

this is the only way it seems to form, but otherwise, it wont work because it has no space to work on

**Comment by Solverbolt** [comment]
but even then, the Automated Farm single block structure does not recognize any fertilizer, of any kind. so it wont operate. as it was setup more than 64 blocks away from the base, and it still decided to just build the farm in the middle of the base. After everything else, it does not surprise me that this mod is also failing to live up to the old luster it once had.
