### ISSUE TITLE
There is a terrible problem with the Alveary fans and heaters

### ISSUE THREAD

**Issue by Artdigy** [ForestryMC/ForestryMC#2393]
For some reason, even if I use a CREATIVE engine from buildcraft, the heaters and fans will be fine charged on their own if there's one or two, with the lights being their solid colors respectively, but if I add one more, or move away for a bit and come back, the lights flicker, and the fans and heaters only work in half intervals or less, acting like they're not receiving enough power.

I thought to myself, hey, Buildcraft is in Alpha, maybe the kinesis pipes are just busted. So I used an energy bridge from the converters mod to use RF pipes, yet it still wont work! This is aggravating because bees work slower or wont work at all in the conditions it has, and even when I removed all fans from an Alveary and replaced them with heaters, it said it was COLD at 30 degress for the longest time! I don't know whats causing this

**Comment by Artdigy** [comment]
Is this being investigated? I thought it might have been things like the extra bees mods which would transport power throughout with  one block connection, HOWEVER, it doesn't work either way. It seems to fix itself EVENTUALLY, and sometimes in conjunction with a hygroregulator, but it shouldn't be doing this

**Comment by temp1011** [comment]
I couldn't see anything similar, but maybe I'm not reproducing this correctly. Could you send a picture of your setup?

**Comment by Artdigy** [comment]
Well, I'm not doing anything any differently than anyone else. The problem got bad so I tried to see if a buildcraft creative engine would solve the problem, but it didn't. I'm not sure if it's power consumption or not. I might be overlooking this too. Here are some screenshots.
![2019-03-30_18 10 23](https://user-images.githubusercontent.com/39284349/55282285-6b3ca300-5317-11e9-89c0-b3df03c3359c.png)
![2019-03-30_18 10 28](https://user-images.githubusercontent.com/39284349/55282286-6b3ca300-5317-11e9-8ffc-bb12ee4b9bad.png)
![2019-03-30_18 10 29](https://user-images.githubusercontent.com/39284349/55282287-6b3ca300-5317-11e9-9c30-6e0b154f11d9.png)
![2019-03-30_18 10 39](https://user-images.githubusercontent.com/39284349/55282288-6b3ca300-5317-11e9-9ecd-0808db05522d.png)
![2019-03-30_18 10 48](https://user-images.githubusercontent.com/39284349/55282289-6b3ca300-5317-11e9-8498-a902edde0332.png)
![2019-03-30_18 10 55](https://user-images.githubusercontent.com/39284349/55282290-6b3ca300-5317-11e9-850c-63d00888b815.png)
![2019-03-30_18 11 05](https://user-images.githubusercontent.com/39284349/55282291-6b3ca300-5317-11e9-8e56-85d59be7706b.png)

**Comment by Artdigy** [comment]
The other alvearys I tried using the alveary transmission, and an energy gate to convert it to RF, to see if buildcraft pipes were the problem, but I just cant figure it out.

**Comment by Artdigy** [comment]
Upon my own examination, I realize it's because I'm dividing the power too much with neighboring pipes. My only question, how can I have it be distributed evenly, and at the right amount of power? I can't imagine needing a multitude of engines

**Comment by Artdigy** [comment]
Ugh. nevermind. it STILL flickers even if one engine is attached to one block only

**Comment by Artdigy** [comment]
Okay upon examination, they work but I just underestimated the absurd amount of power that they need to operate.

**Comment by legoj15** [comment]
Just curious @Artdigy, but did you wrench the creative engines? By default, they have a pitiful 1-2 MJ/s and can be upped to like,  256 MJ/s after right clicking with a BC/Forestry wrench

**Comment by Artdigy** [comment]
I feel like a moron. No, I have not. I was unaware of that.

**Comment by Artdigy** [comment]
If its just a problem of power consumption, why are heaters and fans so demanding? What engines would be good for powering these?

**Comment by bookerthegeek** [comment]
Depends. What version of minecraft are you playing?
