### ISSUE TITLE
Forestry + JEI = Crates crash?

### ISSUE THREAD

**Issue by Sataana** [ForestryMC/ForestryMC#2395]
Cross post: https://github.com/mezz/JustEnoughItems/issues/1538#issue-428441127

In short

Having the issue when I tried to look up "clay"
Inset huge crash report [here](https://gist.github.com/Sataana/dd96a1992dbd2593bd0e5221b2933952)
Does anyone know of a known fix?
Optifine not installed.
Did install FoamFix, BetterFPS & Surge

**Comment by bookerthegeek** [comment]
This is most likely a JEI issue and should be reported over [HERE](https://github.com/mezz/JustEnoughItems/issues)

**Comment by Sataana** [comment]
Done [HERE](https://github.com/mezz/JustEnoughItems/issues/1538#issue-428441127)
Seems like downgrading JEI fixed it.
