### ISSUE TITLE
request: mailbox across server

### ISSUE THREAD

**Issue by jaz000** [ForestryMC/ForestryMC#2396]
So this is a cheeky request I know ...

Could the mailbox feature be made to allow posting of letters between servers (running on the same host).

I was thinking if the mailbox file that contains a players data was always opened read and closed around each operation then it might be possible to send items between servers is you created symbolic links between a users mailbox files in 2 different minecraft servers. (This doesn't work - I tried :) I think the file is cached until server restart ?).

I think to get this to work you would need to at least:
-flush the mailbox file after each operation and read it before each operation
-set a mailbox file location in config (so 2 servers could point to the same files)
-filter out invalid items attached to letters (if the servers had different mods installed)
-and probably not get notification of letters sent from another server, unless you polled the file occasionally.

This is probably probably a mad request but it would be so cool I had to ask - feel free to close and say it's too complicated!

**Comment by Nedelosk** [comment]
I think this is much too complicated for vanilla forestry.
