### ISSUE TITLE
Config option to hide (un)crating recipes from JEI

### ISSUE THREAD

**Issue by MatthiasMann** [ForestryMC/ForestryMC#2398]
Version:
forestry_1.12.2-5.8.2.387

As these recipes exist for nearly every item it would be good to have a way to remove them from JEI

**Comment by TheDeviantCrafter** [comment]
JEI recently added CraftTweaker support for hiding entire recipe tabs. [Here's the documentation](https://crafttweaker.readthedocs.io/en/latest/#Mods/JEI/JEI/)
