### ISSUE TITLE
apiculture=false + lepidopterology=false == crash?

### ISSUE THREAD

**Issue by Aevaris** [ForestryMC/ForestryMC#2400]
Hi,

Using the latest 1.12.2 beta (1.12.2-5.8.2.387.jar), if I set apiculture = false and lepidopterology = false, I crash on initialization of binnie's botany.
https://pastebin.com/tLs2bTx3

If either of them are enabled, things work. But both false = kablooie.

**Comment by Nedelosk** [comment]
Seems like a bug of Binnie. Please report it at https://github.com/ForestryMC/Binnie.
