### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by bigenergy** [ForestryMC/ForestryMC#2401]
Forestry 5.8.2.387 
Forge 14.23.5.2814

https://pastebin.com/5FRSArqY

**Comment by temp1011** [comment]
Does it happen without bukkit? I don't think bukkit and forge play well together

**Comment by bigenergy** [comment]
I tested this problem in pure forge.

**Comment by temp1011** [comment]
Can you post the pure forge crash report then please? This one has ```    at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.updateInventory(CraftPlayer.java:622)```

**Comment by Nedelosk** [comment]
I will close this because we didn't get a response.
