### ISSUE TITLE
Cannot solder Iron Tubes to Circuit Boards

### ISSUE THREAD

**Issue by Lalarian** [ForestryMC/ForestryMC#2407]
Hello!

I'm using Forestry forestry_1.12.2-5.8.2.387.jar with forge-1.12.2-14.23.5.2814.
When I try soldering iron tubes to a circuit board, for making a managed vegatable farm, the UI won't accept the iron tubes in the tube slots. I just can't put them there. All other kinds of tubes are working.
Same bug was already in Forestry version 383 at least, so I upgraded to 387, but the problem remains.
Also in the item decription of the iron tube there only is the function 'in electronical stimulators' listed, but no other function.

**Comment by temp1011** [comment]
see https://github.com/ForestryMC/ForestryMC/issues/1970, the configuration of farms has changed and should be documented in the ingame manual.
