### ISSUE TITLE
Crash when trying to pipe items out of Autofarm

### ISSUE THREAD

**Issue by Rockin132** [ForestryMC/ForestryMC#2408]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LibLoader (# LibLoader.jar)
  BCModPlugin (backpacks+1.12.2+-+3.5.5.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  CoreMod (TickProfiler-1.12-0.0.7.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 04/05/19 16:07
Description: Ticking block entity

java.lang.NoClassDefFoundError: net/minecraft/client/multiplayer/WorldClient
	at buildcraft.transport.net.MessageMultiPipeItem.<clinit>(MessageMultiPipeItem.java:130)
	at buildcraft.transport.net.PipeItemMessageQueue.lambda$appendTravellingItem$1(PipeItemMessageQueue.java:48)
	at java.util.Map.computeIfAbsent(Unknown Source)
	at buildcraft.transport.net.PipeItemMessageQueue.appendTravellingItem(PipeItemMessageQueue.java:48)
	at buildcraft.transport.pipe.flow.PipeFlowItems.sendItemDataToClient(PipeFlowItems.java:155)
	at buildcraft.transport.pipe.flow.PipeFlowItems.addItemTryMerge(PipeFlowItems.java:597)
	at buildcraft.transport.pipe.flow.PipeFlowItems.insertItemEvents(PipeFlowItems.java:585)
	at buildcraft.transport.pipe.flow.PipeFlowItems.tryExtractItems(PipeFlowItems.java:213)
	at buildcraft.transport.pipe.behaviour.PipeBehaviourWood.extractItems(PipeBehaviourWood.java:101)
	at buildcraft.transport.pipe.behaviour.PipeBehaviourWood.extract(PipeBehaviourWood.java:81)
	at buildcraft.transport.pipe.behaviour.PipeBehaviourWood.receivePower(PipeBehaviourWood.java:124)
	at buildcraft.lib.engine.TileEngineBase_BC8.sendPower(TileEngineBase_BC8.java:387)
	at buildcraft.lib.engine.TileEngineBase_BC8.func_73660_a(TileEngineBase_BC8.java:319)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.multiplayer.WorldClient
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 20 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@76911385 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 22 more
Caused by: java.lang.RuntimeException: Attempted to load class bsb for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	... 24 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at buildcraft.transport.net.MessageMultiPipeItem.<clinit>(MessageMultiPipeItem.java:130)
	at buildcraft.transport.net.PipeItemMessageQueue.lambda$appendTravellingItem$1(PipeItemMessageQueue.java:48)
	at java.util.Map.computeIfAbsent(Unknown Source)
	at buildcraft.transport.net.PipeItemMessageQueue.appendTravellingItem(PipeItemMessageQueue.java:48)
	at buildcraft.transport.pipe.flow.PipeFlowItems.sendItemDataToClient(PipeFlowItems.java:155)
	at buildcraft.transport.pipe.flow.PipeFlowItems.addItemTryMerge(PipeFlowItems.java:597)
	at buildcraft.transport.pipe.flow.PipeFlowItems.insertItemEvents(PipeFlowItems.java:585)
	at buildcraft.transport.pipe.flow.PipeFlowItems.tryExtractItems(PipeFlowItems.java:213)
	at buildcraft.transport.pipe.behaviour.PipeBehaviourWood.extractItems(PipeBehaviourWood.java:101)
	at buildcraft.transport.pipe.behaviour.PipeBehaviourWood.extract(PipeBehaviourWood.java:81)
	at buildcraft.transport.pipe.behaviour.PipeBehaviourWood.receivePower(PipeBehaviourWood.java:124)
	at buildcraft.lib.engine.TileEngineBase_BC8.sendPower(TileEngineBase_BC8.java:387)
	at buildcraft.lib.engine.TileEngineBase_BC8.func_73660_a(TileEngineBase_BC8.java:319)

-- Block entity being ticked --
Details:
	Name: buildcraftcore:engine.wood // buildcraft.core.tile.TileEngineRedstone_BC8
	Block type: ID #699 (tile.engineBlock // buildcraft.core.block.BlockEngine_BC8 // buildcraftcore:engine)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-289,66,34), Chunk: (at 15,4,2 in -19,2; contains blocks -304,0,32 to -289,255,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #699 (tile.engineBlock // buildcraft.core.block.BlockEngine_BC8 // buildcraftcore:engine)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: TestWorld
	All players: 1 total; [EntityPlayerMP['Rockin132'/1812, l='TestWorld', x=-282.22, y=66.75, z=35.66]]
	Chunk stats: ServerChunkCache: 505 Drop: 0
	Level seed: -277973575818318736
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-239,64,-65), Chunk: (at 1,4,15 in -15,-5; contains blocks -240,0,-80 to -225,255,-65), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 2903892 game time, 11657 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 117275 (now: false), thunder time: 106095 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3128624688 bytes (2983 MB) / 4749000704 bytes (4529 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 2 total; -Xms2048M -Xmx6G
	IntCache: cache: 0, tcache: 0, allocated: 14, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2836 53 mods loaded, 53 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version              | Source                                                      | Signature                                |
	|:------ |:--------------------- |:-------------------- |:----------------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft             | 1.12.2               | minecraft.jar                                               | None                                     |
	| LCHIJA | mcp                   | 9.42                 | minecraft.jar                                               | None                                     |
	| LCHIJA | FML                   | 8.0.99.99            | forge.jar                                                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                 | 14.23.5.2836         | forge.jar                                                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | bspkrscore            | 7.6.0.1              | [1.12]bspkrsCore-universal-7.6.0.1.jar                      | None                                     |
	| LCHIJA | treecapitator         | 1.43.0               | [1.12]TreeCapitator-client-1.43.0.jar                       | None                                     |
	| LCHIJA | buildcraftlib         | 7.99.24              | buildcraft-all-7.99.24.jar                                  | None                                     |
	| LCHIJA | buildcraftcore        | 7.99.24              | buildcraft-all-7.99.24.jar                                  | None                                     |
	| LCHIJA | buildcraftfactory     | 7.99.24              | buildcraft-all-7.99.24.jar                                  | None                                     |
	| LCHIJA | buildcrafttransport   | 7.99.24              | buildcraft-all-7.99.24.jar                                  | None                                     |
	| LCHIJA | buildcraftsilicon     | 7.99.24              | buildcraft-all-7.99.24.jar                                  | None                                     |
	| LCHIJA | additionalpipes       | 6.0.0.8              | additionalpipes-6.0.0.8.jar                                 | None                                     |
	| LCHIJA | ic2                   | 2.8.125-ex112        | industrialcraft-2-2.8.125-ex112.jar                         | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | advanced_machines     | 61.0.1               | Advanced+Machines-61.0.1.jar                                | None                                     |
	| LCHIJA | advanced_solar_panels | 4.3.0                | Advanced+Solar+Panels-4.3.0.jar                             | None                                     |
	| LCHIJA | backpacks16840        | 3.5.5                | backpacks+1.12.2+-+3.5.5.jar                                | None                                     |
	| LCHIJA | baubles               | 1.5.2                | Baubles-1.12-1.5.2.jar                                      | None                                     |
	| LCHIJA | forgelin              | 1.8.2                | Forgelin-1.8.2.jar                                          | None                                     |
	| LCHIJA | jei                   | 4.15.0.277           | jei_1.12.2-4.15.0.277.jar                                   | None                                     |
	| LCHIJA | bcoreprocessing       | 1                    | bc-ore-processing-7.99.15-1.jar                             | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | bibliocraft           | 2.4.5                | BiblioCraft[v2.4.5][MC1.12.2].jar                           | None                                     |
	| LCHIJA | buildcraftenergy      | 7.99.24              | buildcraft-all-7.99.24.jar                                  | None                                     |
	| LCHIJA | forestry              | 5.8.2.387            | forestry_1.12.2-5.8.2.387.jar                               | None                                     |
	| LCHIJA | binniecore            | 2.5.1.188            | binnie-mods-1.12.2-2.5.1.188.jar                            | None                                     |
	| LCHIJA | binniedesign          | 2.5.1.188            | binnie-mods-1.12.2-2.5.1.188.jar                            | None                                     |
	| LCHIJA | genetics              | 2.5.1.188            | binnie-mods-1.12.2-2.5.1.188.jar                            | None                                     |
	| LCHIJA | botany                | 2.5.1.188            | binnie-mods-1.12.2-2.5.1.188.jar                            | None                                     |
	| LCHIJA | extrabees             | 2.5.1.188            | binnie-mods-1.12.2-2.5.1.188.jar                            | None                                     |
	| LCHIJA | extratrees            | 2.5.1.188            | binnie-mods-1.12.2-2.5.1.188.jar                            | None                                     |
	| LCHIJA | buildcraftbuilders    | 7.99.24              | buildcraft-all-7.99.24.jar                                  | None                                     |
	| LCHIJA | buildcraftcompat      | 7.99.24              | buildcraft-all-7.99.24.jar                                  | None                                     |
	| LCHIJA | buildcraftrobotics    | 7.99.24              | buildcraft-all-7.99.24.jar                                  | None                                     |
	| LCHIJA | chameleon             | 1.12-4.1.3           | Chameleon-1.12-4.1.3.jar                                    | None                                     |
	| LCHIJA | codechickenlib        | 3.2.2.353            | CodeChickenLib-1.12.2-3.2.2.353-universal.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | doggytalents          | 1.14.2.438           | DoggyTalents-1.12.2-1.14.2.438-universal.jar                | None                                     |
	| LCHIJA | forgemultipartcbe     | 2.6.1.81             | ForgeMultipart-1.12.2-2.6.1.81-universal.jar                | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | microblockcbe         | 2.6.1.81             | ForgeMultipart-1.12.2-2.6.1.81-universal.jar                | None                                     |
	| LCHIJA | minecraftmultipartcbe | 2.6.1.81             | ForgeMultipart-1.12.2-2.6.1.81-universal.jar                | None                                     |
	| LCHIJA | inventorytweaks       | 1.64+dev.146.2180b27 | InventoryTweaks-1.64+dev.146.jar                            | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironchest             | 1.12.2-7.0.59.842    | ironchest-1.12.2-7.0.59.842.jar                             | None                                     |
	| LCHIJA | irontanks             | 2.1.0-beta.5         | irontanks-2.1.0-beta.5.jar                                  | None                                     |
	| LCHIJA | mantle                | 1.12-1.3.3.49        | Mantle-1.12-1.3.3.49.jar                                    | None                                     |
	| LCHIJA | mobcontroller         | 1.1                  | MobController-1.12.2-1.1.jar                                | None                                     |
	| LCHIJA | mrtjpcore             | 2.1.3.35             | MrTJPCore-1.12.2-2.1.3.35-universal.jar                     | None                                     |
	| LCHIJA | nei                   | 2.4.2                | NotEnoughItems-1.12.2-2.4.2.240-universal.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | harvestcraft          | 1.12.2zb             | Pam's+HarvestCraft+1.12.2zc+The+7mm+Kidney+Stone+Update.jar | None                                     |
	| LCHIJA | projectred-core       | 4.9.1.92             | ProjectRed-1.12.2-4.9.1.92-Base.jar                         | None                                     |
	| LCHIJA | thaumcraft            | 6.1.BETA26           | Thaumcraft-1.12.2-6.1.BETA26.jar                            | None                                     |
	| LCHIJA | railcraft             | 12.0.0               | railcraft-12.0.0.jar                                        | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCHIJA | storagedrawers        | 1.12-5.3.5           | StorageDrawers-1.12.2-5.3.8.jar                             | None                                     |
	| LCHIJA | tconstruct            | 1.12.2-2.12.0.135    | TConstruct-1.12.2-2.12.0.135.jar                            | None                                     |
	| LCHIJA | tickprofiler          | 1.12-0.0.7           | TickProfiler-1.12-0.0.7.jar                                 | None                                     |
	| LCHIJA | wrcbe                 | 2.3.1                | WR-CBE-1.12.2-2.3.1.30-universal.jar                        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |

	Loaded coremods (and transformers): 
LibLoader (# LibLoader.jar)
  
BCModPlugin (backpacks+1.12.2+-+3.5.5.jar)
  brad16840.core.ClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  invtweaks.forge.asm.ContainerTransformer
CoreMod (TickProfiler-1.12-0.0.7.jar)
  
ForgelinPlugin (Forgelin-1.8.2.jar)
  
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['Rockin132'/1812, l='TestWorld', x=-282.22, y=66.75, z=35.66]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by MauveCloud** [comment]
> buildcraft-all-7.99.24.jar 

Try 7.99.24.1 - I just looked, and the changelog mentions fixing such a crash.  Apparently reported to BuildCraft as https://github.com/BuildCraft/BuildCraft/issues/4399

**Comment by Rockin132** [comment]
> > buildcraft-all-7.99.24.jar
> 
> Try 7.99.24.1 - I just looked, and the changelog mentions fixing such a crash. Apparently reported to BuildCraft as [BuildCraft/BuildCraft#4399](https://github.com/BuildCraft/BuildCraft/issues/4399)



Thanks I'll give it a try

EDIT: This seems to have solved it as far as I can tell, cheers.
