### ISSUE TITLE
ProxyGreenhouseClient IllegalAccessException to BiomeColorHelper$ColorResolver with latest OpenJ9 JVM

### ISSUE THREAD

**Issue by ChipWolf** [ForestryMC/ForestryMC#2409]
Crash occurs with the latest OpenJ9 JRE of the OpenJDK platform. Seems not to occur with Hotspot, no other mods are affected.

https://gist.github.com/ChipWolf/181264254176166f7a790a9921ce80af

**Comment by ChipWolf** [comment]
Apologies, I note this is the release version of Forestry not the current beta. I'll close this issue for now.

**Comment by bs2609** [comment]
Update Forge to 2815+
