### ISSUE TITLE
Exception right after placing Peat Engine

### ISSUE THREAD

**Issue by Alekcvp** [ForestryMC/ForestryMC#2410]
After placing the peat engine the game crashes in 5 sec and world is not loading anymore.

https://pastebin.com/t9dnCBVj

**Comment by Alekcvp** [comment]
Incompatibility with buildcraft 7.99 :(

**Comment by MauveCloud** [comment]
From your log:

> forestry_1.12.2-5.8.2.374.jar

That's not the latest build.  According to comments in PR #2344, this has been fixed as of build 381.

**Comment by temp1011** [comment]
duplicate #2340 I believe
