### ISSUE TITLE
leaves causing crashes

### ISSUE THREAD

**Issue by kreezxil** [ForestryMC/ForestryMC#2411]
I went ahead and updated my Forestry to the latest version again in hopes it would generate crash reports you could use.

Apparently the player got the following npe in JEI when trying to view Binnie's mods cranberries. However you can see the top mod indicated is forestry.

https://paste.dimdev.org/worikebaci.mccrash

**Comment by temp1011** [comment]
`    at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)`
Does removing optifine fix the problem?

**Comment by kreezxil** [comment]
oh, I didn't realize the player added optifine to my pack. I don't support optifine.

**Comment by kreezxil** [comment]
I've closed it on my end because I don't support optifine. If you also don't support optifine feel free to close it there too.

**Comment by temp1011** [comment]
This should be fixed by #2431
