### ISSUE TITLE
(1.12.2) server crash

### ISSUE THREAD

**Issue by Cronosus** [ForestryMC/ForestryMC#2412]
Hello
today our server crashed with this:
https://paste.ee/p/Udq81

Forestry: 5.8.2.387
Server: Mohist (bukkit+forge) with forge 14.23.5.2837

**Comment by temp1011** [comment]
seems like #2401 , #2365 . I'm pretty sure this is just a problem with bukkit and forge.

**Comment by Cronosus** [comment]
we tried to investigate.. maybe is farm placed in more than one chunk

**Comment by temp1011** [comment]
Does this still occur after updating Mohist?

**Comment by Cronosus** [comment]
honestly i dont tried again, and now we reverted server back to 1.7.10 for many reasons
but mohist still have same libraries, then i don't think its fixed already, but maybe dev builds...
