### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Sunekaer** [ForestryMC/ForestryMC#2413]
https://github.com/FTBTeam/FTB-Builders-Paradise/issues/21

log: https://paste.feed-the-beast.com/view/ac74a5a4

was going to excavate blue leaves from a tree with a tinkers mattock containing a silky jewel. As soon as I hit the button to excavate the leaves, the game crashed.

**Comment by temp1011** [comment]
Looks like https://github.com/ForestryMC/ForestryMC/issues/2336 but the info about using excavate is interesting, no one has mentioned that before. It looks like at some point I should try and isolate which mods from the  pack cause this.

**Comment by temp1011** [comment]
fixed by #2431 I believe
