### ISSUE TITLE
[1.7.10] Problem with Forestry and Pam's HarvestCraft

### ISSUE THREAD

**Issue by demycat** [ForestryMC/ForestryMC#2416]
Hello, I have a problem with crafting a wax capsule, in fact, Nei shows craft that I can craft a wax capsule (wax from Pam 's HarvestCraft mod), but when I use craft I expose it to the table, I cannot craft them .
How to fix this?

Version Forestry: forestry_1.7.10-4.2.16.64
Version Pam's HarvestCraft: Pam's HarvestCraft 1.7.10Lb
![2019-05-27_14 53 10](https://user-images.githubusercontent.com/34833284/58419511-7f8cea00-8093-11e9-9b9f-d4d83e27464c.png)
![2019-05-27_14 54 21](https://user-images.githubusercontent.com/34833284/58419513-7f8cea00-8093-11e9-86d9-823a61459d0f.png)

**Comment by Nedelosk** [comment]
I don't think we will make any changes on the 1.7.10 version of forestry.
