### ISSUE TITLE
Crash MultiFarms 1.12.2

### ISSUE THREAD

**Issue by Dimiral** [ForestryMC/ForestryMC#2418]
I started building a multi-farm and Minecraft just crashed. Now the world does not start, but there is no backup :(
Crast report: https://gist.github.com/Dimiral/21b4f8deaa9b5ee130c95bdd4ca81b84

**Comment by temp1011** [comment]
duplicate #2340, need to update forestry.

**Comment by Dimiral** [comment]
Does not work
Crash report: https://gist.github.com/Dimiral/e92ced892a29256bdd1a197f0c375137

**Comment by Dimiral** [comment]
I started to reinstall mods and found that Forestry conflicts with BuildCraft Transport. Namely, when you put Farm Hatch
Crash report: https://gist.github.com/Dimiral/c9cacdaa0ef36a6d9f4c99a069c69d0e

**Comment by temp1011** [comment]
You still have an old version: ``` | LCHIJA | forestry | 5.8.1.322 | forestry_1.12.2-5.8.1.322.jar | None |```. You need to update to the latest beta which can be found here: https://minecraft.curseforge.com/projects/forestry/files/2684780.
Note: version 5.8.2.374 is too old as well I think which is why you still crashed.

**Comment by meelock** [comment]
Still broken on 5.8.2.387, https://paste.dimdev.org/ticexemomo.mccrash
