### ISSUE TITLE
Crash Forestry after building alveary[1.12.2]

### ISSUE THREAD

**Issue by VladGev** [ForestryMC/ForestryMC#2419]
Hello everyone i hope you can help me going through this.

I'm running into a problem with forestry,
Yesterday after finally building my first alveary, i automated it, placed a princess and a drone inside.
the production went fine, managed to get a few combs and called it a day...
Today when i launch the game, the game crash at the world's loading.
I had a similar problem a few days ago with the multifarm but updating forestry solved the issue...

https://gist.github.com/VladGev/1ed71d9fb4a9674529fc3be2f502637f

Any idea ?

**Comment by Nedelosk** [comment]
Seems like your world got corrupted. Do you have more information about your setup?

**Comment by Nedelosk** [comment]
I will close this because we didn't get a response.
