### ISSUE TITLE
Arboretum doesn't respect Habitat Former

### ISSUE THREAD

**Issue by pyure** [ForestryMC/ForestryMC#2420]
Greetings team,

I set up a habitat former adjacent to an Arboretum machine (in a hot/arid desert) and extended its range to 10 blocks.  The Arboretum did not "notice" that the environment had improved.

It doesn't "feel" intended given that they both operate on the same heat/humidity mechanics.

**Comment by temp1011** [comment]
The habitat former was a replacement for the greenhouse, not sure if that worked on trees either.
