### ISSUE TITLE
Forestry trees still spawn when disabled in config

### ISSUE THREAD

**Issue by netmc** [ForestryMC/ForestryMC#2425]
Even when setting forestry trees to false in the common.cfg file, forestry trees still spawn.
---------------------
world {

    generate {
        B:trees=false
---------------------

It appears however that setting the rarity to 0 in the arboriculture.cfg file does work:
---------------------

    global {
        D:rarity=0.0

---------------------

This was tested in forestry_1.12.2-5.8.2.387.

**Comment by temp1011** [comment]
The global rarity option was removed in https://github.com/ForestryMC/ForestryMC/commit/2c8ed4855d87658522cb2217ce0b4c19d59b6a65. Regenerating your configs should remove the generate trees option.

**Comment by Nedelosk** [comment]
To disable the generation of all trees you have to set the rarity in the "arboriculture.cfg" config in the "global" category to "0.0".  The old options from "common.cfg" were removed to allow more control over the rarity and spawn biomes of every tree species.
