### ISSUE TITLE
Forestry Fruit Icons causing IllegalArgumentException

### ISSUE THREAD

**Issue by JamesYeoman** [ForestryMC/ForestryMC#2428]
[Crashlog](https://gist.github.com/JamesYeoman/86f9c9fd042ab2e18073ab3f52d9ad9f)

Using veinminer, I cannot configure the blocklist if the fruits exist. I have confirmed that it is the fruits by adding all the forestry items into the blocklist via the config file individually. All of the leaves are all fine but when I got to the fruit, that's when the crashes started.

This is the same issue that #1868 was having but the root cause doesn't seem to have been discovered until now.

The IDs that I have found to be troublesome are
 - `forestry:leaves.default.fruit.0`
 - `forestry:leaves.default.fruit.1`

**Comment by MrMetric** [comment]
I've submitted a fix: #2431
