### ISSUE TITLE
Game crash upon loading new chucks.

### ISSUE THREAD

**Issue by CapturedCherry-zz** [ForestryMC/ForestryMC#2432]
Thank you for reporting!

When loading a chuck some times the game will crash with the following crash log. I'm not 100% sure if it is a forestry issues or if its a different mod. https://gist.github.com/RiptideC27/fa5f509b5b6838352eaae5715594f480
I'm using the latest version of Forestry and forge.
Any help would be great thank you.

**Comment by otavio-silva** [comment]
I have this same issue. Did you had any luck with it?

**Comment by CapturedCherry-zz** [comment]
Nope. I have yet to find any fix for this issues.

**Comment by otavio-silva** [comment]
I did something that is definitely not the ideal solution, but seems to be working. In the function `public boolean hasCapability(Capability<?> capability, @Nullable EnumFacing facing)` there's just the code `return (facing == getFacing() && energyManager.hasCapability(capability)) || super.hasCapability(capability, facing)`, so I encapsulated it in a `try-catch`, so if `getFacing` gives an error the function return `false`. I'm testing in the areas where the errors always occurs in my world, and the error looks like it's gone by now.

**Comment by temp1011** [comment]
Hmm have you enabled/disabled any modules recently? This looks like the block has just disappeared from the world.

**Comment by otavio-silva** [comment]
Not really, the only thing I did was change compiling info to match with my Forge version, and also Binnie and IndustrialCraft 2 versions. Other than that, nothing. Also, since when I changed it, that error vanished completely.

**Comment by temp1011** [comment]
This should be fixed by https://github.com/ForestryMC/ForestryMC/commit/322c6652c126b4c0a97c7367eedcd855b9f9cf7b
