### ISSUE TITLE
Butterflies dont pollinate

### ISSUE THREAD

**Issue by poulhp** [ForestryMC/ForestryMC#2435]
* **Modpack Version**:  FTB Revelation 3.0.1

* **Issue**: Butterflies dont pollinate leaves on their own, I have changed the config file to allow this, default says true but was false.
But stille dont work. Tryed doing it on a new world super flat, creavtive and made a glass dome filled it with forestry trees and butterflies and nothing happend.
Tryed the same thing in FTB Infinity evolved, and within 5-10 min I had 20+ pollinated leaves.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Yes, read above

* **Mod/s Affected**: No idea, cant find the root problem.

* **Known Fix**: None

**Comment by Nedelosk** [comment]
I can't confirm this bug. I tested it with the newest version and it worked.
