### ISSUE TITLE
[1.12.2.] [sugguestion] move Recipe Registration to RegistryEvent.Register<IRecipe>

### ISSUE THREAD

**Issue by ToMe25** [ForestryMC/ForestryMC#2438]
I would suggest you to move the full recipe registration from init to `RegistryEvent.Register<IRecipe>` for more Mod compatibility until #2111 eventually happens.

**Comment by Nedelosk** [comment]
I don't think we will do such a drastic change in 1.12.2. But definitely, something that we will do in 1.13/1.14.
