### ISSUE TITLE
{1.12.2} forestry world crashing after 3 minutes

### ISSUE THREAD

**Issue by NikichMan** [ForestryMC/ForestryMC#2439]
Can somebody please help me
https://paste.dimdev.org/usutodujaz.mccrash

**Comment by temp1011** [comment]
Could you post the full log please? I can't tell why this is because of forestry from the crash report.

**Comment by temp1011** [comment]
If this is due to forestry, it's almost definitely something to do with butterflies. But I am suspicious that no forestry code is in the stacktrace. Seems that the reason we have this crash report is VanillaFix (for whatever reason) blames forestry for the crash.
