### ISSUE TITLE
Crash on launch, not always. only certain times

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#2443]
https://pastebin.com/rFss6wZL

It only crashes at random times. Above is crash report

**Comment by temp1011** [comment]
The pastebin link is broken

**Comment by ghost** [comment]
here, sorry 
https://pastebin.com/qJkZPT0B

**Comment by temp1011** [comment]
Foamfix parallel model baking looks suspicious here. Does the crash still occur if that is disabled?

**Comment by hellot1m** [comment]
Was having the same issue with the latest forestry update. Changed the setting back to false in FoamFix and i am able to launch. One thing i found weird is that it worked when loading my modpack from twitch but kept throwing this exact error when using MultiMC

disabling this foamfix feature works.. but would love to continue to use this feature.

**Comment by asiekierka** [comment]
Don't use parallel model baking.
