### ISSUE TITLE
Unable to open Apiary - NullPointerException

### ISSUE THREAD

**Issue by Advaluti2** [ForestryMC/ForestryMC#2444]
Hi, been havign some trouble with the Bee House and Apiary with an error occuring when trying to open them. You can find the latest.log excerpt with the error shown relating to `TileBeeHousingBase.getCapability` and `PacketClimateListenerUpdateRequest`.

https://pastebin.com/G39nFrgi

**Comment by temp1011** [comment]
```[14:39:14] [Netty Server IO #1/INFO]: Client attempting to join with 80 mods : buildcraftlib@7.99.24.1,ctgui@1.0.0,...,forestry@5.8.2.386,binniedesign@2.5.1.188,betteradvancements@0.1.0.77```

Does this still occur on build 5.8.2.394?

**Comment by Advaluti2** [comment]
Removed forestry JAR and installed 394 and the error still occurs

**Comment by Advaluti2** [comment]
Just deleted the config files for Forestry and fixed it, most likely something I changed previously. Thanks for the help.

**Comment by temp1011** [comment]
Ah, perhaps this was due to having apiculture enabled and climatology disabled?

**Comment by MasterEnderman** [comment]
it was i had the same issue. reenabling climatology fixed it. because it doesn't tell in the config that the climatology module is required for apiculture.

**Comment by temp1011** [comment]
I've submitted a fix
