### ISSUE TITLE
Habitat Former doesn't impact farms

### ISSUE THREAD

**Issue by tannergooding** [ForestryMC/ForestryMC#2445]
### Issue

Using forestry_1.12.2-5.8.2.387, it doesn't appear as though the habitat former is impacting farms as the UI always reports the ambient biome temperature/humidity. I have validated that it is correctly impacting the habit information for bees.

### Expected Behavior

I would expect that it impacts all forestry habitat information.

**Comment by tannergooding** [comment]
Just wanted to call out that, even if this doesn't actually change the biome (and therefore impact crop growth). It can still be used to impact resource consumption (like water), for example.

**Comment by temp1011** [comment]
This should be fixed (https://github.com/ForestryMC/ForestryMC/issues/2420). Can you try the latest version?

**Comment by tannergooding** [comment]
Confirmed working in latest version. Thanks!
