### ISSUE TITLE
Not sure if this is just Forestry but i have a server Ticking entity

### ISSUE THREAD

**Issue by xXUnholyWolfXx** [ForestryMC/ForestryMC#2447]
My server is crashing and giving me this error report.. but i can not find the butterfly.. and i have removed all the inventorypets so im running out of ideas

[Error Log](https://gist.github.com/xXUnholyWolfXx/1d51cd493dd330810a2d0e8c92245fb2) and link it here.

**Comment by temp1011** [comment]
`	| LCHIJA | inventorypets        | 2.0.2                    | inventorypets-1.12-2.0.2.jar                    | None                                     |`
Seems like inventory pets is still present in your loaded mod list.
