### ISSUE TITLE
No tubes for potatoes/carrots?

### ISSUE THREAD

**Issue by octavarium5858** [ForestryMC/ForestryMC#2448]
Hi

so i recently got into Forestry again after many years and i realised the farming system has changed dramatically. As i started to learn about it i realised that there is no tube for potatoes or carrots (as the iron tubes only has 1 function whereas previously it had the "vegetables" tag 
with automatic). It seems like the iron tube is a part of IC2 and not Forestry? i thought i might report this issue to notify you of this and potentially add a tube for Carrots and potatoes.

regards Octavarium

**Comment by temp1011** [comment]
See https://github.com/ForestryMC/ForestryMC/issues/1970. Use the crops farm now.
