### ISSUE TITLE
Bees should breed by themselves

### ISSUE THREAD

**Issue by HatcheryRoosters** [ForestryMC/ForestryMC#2450]
Bees should be able to breed by themselves so I don't have to do it myself, saves time for some players.

**Comment by SandGrainOne** [comment]
In the current version of Forestry you would normally combine two bees in one housing. These will breed automatically and in some cases result in a mutation and give a new spicies. This can already be automated. Maybe not too well in Forestry alone, but there exists a lot of very advanced logistics mods you can use. Even BuildCraft could work.

What part of this would you want to change?
