### ISSUE TITLE
Forestry Farm not fully work

### ISSUE THREAD

**Issue by Dankhar** [ForestryMC/ForestryMC#2451]
Hello!
My farm only works 3/4, this last element it does not build or maintain, simply ignores, I tried to use an intricate circuit with 4 sides with arboretum but it does not work.
Version: 1.7.10
For issues:
![image](https://user-images.githubusercontent.com/54476839/63638747-3f211600-c65a-11e9-8cdf-e295e9436e4e.png)

**Comment by temp1011** [comment]
@Nedelosk are we still supporting 1.7.10?

**Comment by Nedelosk** [comment]
No, missed the version information.
