### ISSUE TITLE
NoSuchMethodError:forestry.core.utils.InventoryUtil.internal_moveOneItemToPipe

### ISSUE THREAD

**Issue by Jase2z** [ForestryMC/ForestryMC#2452]
Game crashes right after toon appears in world. This started after I finished a 3x3x4 farm made from mossy brick blocks.

crash log:  https://gist.github.com/Jase2z/cd0cc1347fb90b2e757823284914e95a

**Comment by temp1011** [comment]
Please try with the latest version of buildcraft (7.99.24.2)

**Comment by Jase2z** [comment]
new crash log:   https://gist.github.com/Jase2z/79e67aa19b46bfed8365ecb6b50b09f7

I had removed forestry to keep playing. Now I updated to buildcraft 7.99.24.2, added forestry zip back into mods and regenerated my world.
The moment I add the last farm block to the 3x3x4 structure the server crashes and it continues to crash every time I try to reload it.
Just to note, there are no buildcraft pipes on my server, and there isn't anything trying to interact with the farm structure I built either.

**Comment by Jase2z** [comment]
I used to the beta 5.8.2.394 instead of the release and MC stopped crashing.

**Comment by temp1011** [comment]
The last release build of forestry was quite a long time ago but unfortunately curseforge puts it right at the top of the page. The latest beta will have more bug fixes in.
