### ISSUE TITLE
Crash with Assassin Bee Queen trying to procreate.

### ISSUE THREAD

**Issue by UnambiguousUsername** [ForestryMC/ForestryMC#2453]
Minecraft version 1.12.2 running FTB Revelation modpack (plus/minus couple of mods).

After putting an Assassin Bee Queen into my Industrial Apiary the game crashed once the needs of it to procreate were met. After loading the game up again, it crashed once the Assassing Bee Queen was ready to go, but this time with a different block/entity. The industrial apiary was being powered by the EnderIO Ender Energy Conduit.

First crash: https://pastebin.com/D9F5R2YC
Second crash: https://pastebin.com/AX1UNBAs

**Comment by temp1011** [comment]
This looks like the same crash as https://github.com/rwtema/Careerbees/issues/23
