### ISSUE TITLE
Most recipe of Carpenter doesn't work

### ISSUE THREAD

**Issue by evileyecc1** [ForestryMC/ForestryMC#2454]
Forestry Version:forestry_1.12.2-5.8.2.394
I am update from 322 because the farm crash when open gui.But when i try to make a Soldering Iron.The Carpenter say no recipe.
![image](https://user-images.githubusercontent.com/22828359/64012719-cb4aa600-cb50-11e9-9e56-7f7844d743a9.png)

**Comment by temp1011** [comment]
You need water as well for the recipe

**Comment by evileyecc1** [comment]
OK.It's work now.Because i put a water bucket in the right top and doesn't work.I thought it was a bug
