### ISSUE TITLE
Game crash when I open the farm

### ISSUE THREAD

**Issue by scottctd** [ForestryMC/ForestryMC#2455]
For forestry_1.12.2-5.8.1.322.
After I finshed up my farm multiple block, I attempted to open that. Yet i failed, and the game crashed.
I cant join that world again until i delete or replace the forestry. Plus, in my other modpack, the farm can be normally used. I am so confused, please give me the resolutions. **Thanks!!**

Here is the report---
https://paste.ubuntu.com/p/V7NJzVG4zZ/

**Comment by scottctd** [comment]
Moreover, all the mods that in my modpack are lasted, including some popular tech and magic mods.

**Comment by scottctd** [comment]
Secondary attemp --Failed.

https://paste.ubuntu.com/p/JqN88gr8s8/

**Comment by scottctd** [comment]
I believe there are some mods that conflict with forestry but i am unable to find that....

HELP ME PLEASE

**Comment by scottctd** [comment]
MOOOOOORE OVER, after the tree farm harvest the trees, it cannot return the saplings into the saplings inventory and it just regard the saplings as the output. 

I just ... encounter those problems and cannot find solutions.

**Comment by temp1011** [comment]
Updating forestry should fix this
