### ISSUE TITLE
Peat-fired engine causing crashes

### ISSUE THREAD

**Issue by Alex34fggh** [ForestryMC/ForestryMC#2458]
Here's the crash report.
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 9/5/19 2:07 PM
Description: Ticking block entity

java.lang.NoSuchMethodError: forestry.core.utils.InventoryUtil.internal_moveOneItemToPipe(Lnet/minecraftforge/items/IItemHandler;Lforestry/core/tiles/AdjacentTileCache;[Lnet/minecraft/util/EnumFacing;)Z
	at forestry.core.utils.InventoryUtil.moveOneItemToPipe(InventoryUtil.java:82)
	at forestry.core.utils.InventoryUtil.moveOneItemToPipe(InventoryUtil.java:77)
	at forestry.energy.tiles.TileEnginePeat.dumpStash(TileEnginePeat.java:237)
	at forestry.energy.tiles.TileEnginePeat.updateServerSide(TileEnginePeat.java:107)
	at forestry.core.tiles.TileForestry.func_73660_a(TileForestry.java:97)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at forestry.core.utils.InventoryUtil.moveOneItemToPipe(InventoryUtil.java:82)
	at forestry.core.utils.InventoryUtil.moveOneItemToPipe(InventoryUtil.java:77)
	at forestry.energy.tiles.TileEnginePeat.dumpStash(TileEnginePeat.java:237)
	at forestry.energy.tiles.TileEnginePeat.updateServerSide(TileEnginePeat.java:107)
	at forestry.core.tiles.TileForestry.func_73660_a(TileForestry.java:97)

-- Block entity being ticked --
Details:
	Name: forestry:peat // forestry.energy.tiles.TileEnginePeat
	Block type: ID #521 (tile.for.engine_peat // forestry.energy.blocks.BlockEngine // forestry:engine_peat)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (-126,64,247), Chunk: (at 2,4,7 in -8,15; contains blocks -128,0,240 to -113,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #521 (tile.for.engine_peat // forestry.energy.blocks.BlockEngine // forestry:engine_peat)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 8598940408125444895
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-124,64,248), Chunk: (at 4,4,8 in -8,15; contains blocks -128,0,240 to -113,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 709 game time, 709 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 161770 (now: false), thunder time: 157943 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 858859504 bytes (819 MB) / 1392508928 bytes (1328 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx2048m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 14, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version      | Source                           | Signature                                |
	|:------ |:------------------- |:------------ |:-------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2       | minecraft.jar                    | None                                     |
	| LCHIJA | mcp                 | 9.42         | minecraft.jar                    | None                                     |
	| LCHIJA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2838.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2838 | forge-1.12.2-14.23.5.2838.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | buildcraftlib       | 7.99.24.2    | buildcraft-all-7.99.24.2 (1).jar | None                                     |
	| LCHIJA | buildcraftcore      | 7.99.24.2    | buildcraft-all-7.99.24.2 (1).jar | None                                     |
	| LCHIJA | buildcraftbuilders  | 7.99.24.2    | buildcraft-all-7.99.24.2 (1).jar | None                                     |
	| LCHIJA | buildcrafttransport | 7.99.24.2    | buildcraft-all-7.99.24.2 (1).jar | None                                     |
	| LCHIJA | buildcraftsilicon   | 7.99.24.2    | buildcraft-all-7.99.24.2 (1).jar | None                                     |
	| LCHIJA | buildcraftenergy    | 7.99.24.2    | buildcraft-all-7.99.24.2 (1).jar | None                                     |
	| LCHIJA | forestry            | 5.8.1.322    | forestry_1.12.2-5.8.1.322.jar    | None                                     |
	| LCHIJA | buildcraftcompat    | 7.99.24.2    | buildcraft-all-7.99.24.2 (1).jar | None                                     |
	| LCHIJA | buildcraftfactory   | 7.99.24.2    | buildcraft-all-7.99.24.2 (1).jar | None                                     |
	| LCHIJA | buildcraftrobotics  | 7.99.24.2    | buildcraft-all-7.99.24.2 (1).jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by temp1011** [comment]
Please update forestry to fix this

**Comment by Alex34fggh** [comment]
I just updated .Thanks
