### ISSUE TITLE
1.12.2: Thermionic Fabricator not crafting glass items

### ISSUE THREAD

**Issue by afroJezuz** [ForestryMC/ForestryMC#2459]
I'm playing FTB: Revelations' latest beta release.

As stated, all glass items (stained/drinking) will not craft.

It won't accept a wax mold, regardless of power, regardless of JEI auto-place it will not warm and melt down components.

However, it will craft everything else associated with the machine.

Is there a reason it won't accept a wax mold?
Is the wax mold what defines a working recipe?
Is there a non-creative workaround or config adjustment that can make it work?

**Comment by temp1011** [comment]
Seems like the same issue as https://github.com/ForestryMC/ForestryMC/issues/2304. There was a similar issue linked in that ticket (https://github.com/AllTheMods/ATM-3/issues/752) so I would guess there is a mod conflict somewhere.
