### ISSUE TITLE
Server - refuses to grow trees

### ISSUE THREAD

**Issue by snowe2010** [ForestryMC/ForestryMC#2461]
No crash, nothing I can see in reported error logs. 

Version : 5.8.2.387

With a Managed Arboretum, Forestry manages to plant all the saplings, fertilize them fine, and grow at least one tree. After that all trees fail to grow. If I destroy a bunch of saplings _sometimes_ trees will then grow, but not often. I've waited about 18 days in game and still no trees have grown. I've verified the farm is receiving all required items and it's in a wide open field so there's nothing above it.

**Comment by temp1011** [comment]
I'm not sure what it causing this for you. It could be worth testing this out in creative and using `/gamerule randomTickSpeed 100` (or some other very high value) to check that only one tree will grow and not others.

**Comment by snowe2010** [comment]
I really don't know what is happening. The trees grow fine if I crank the ticks to like 2000, but I left a chunkloader in the area yesterday and when I came back absolutely 0 trees had grown. I've left it sitting here for about an hour now and still no trees have grown (on default tick), but as soon as I change the ticks they grow fine. I'm currently trying to test whether creative mode or the default tick is the reason. At least a _single tree_ should grow during an entire day correct? I'm getting no tree growth at all, over multiple days.

**Comment by snowe2010** [comment]
running it at a high speed seems to indicate to me that the trees aren't growing because they are directly next to other saplings. When some of the humus runs out of fertilizer and then turns to sand, if there are like two blocks next to a single sapling then that sapling succeeds at growing. Otherwise the trees do not grow at all.

**Comment by temp1011** [comment]
Interesting. What species of tree are you trying to grow?

**Comment by snowe2010** [comment]
Spruce, but I tried with Oak as well. I can actually destroy a large amount of the humus and trees will suddenly start growing, but as soon as the entire field is full of humus again trees stop growing.

**Comment by snowe2010** [comment]
So, trees will suddenly grow if only a few patches of humus are there, and the rest is sand. This definitely seems related to adjacent saplings. Should I try with a different type of sapling? Where in the code does growth handling occur?

**Comment by temp1011** [comment]
Most of the growth stuff is handled in `TileSapling` I believe.

**Comment by temp1011** [comment]
I tried to reproduce in a test world but things did grow for vanilla oak and forestry apple oak. Test world is at https://github.com/ForestryMC/ForestryMC/commit/b4771511e3e2e2b79a3e09630c70f519dcbeaabc.
![farm_running](https://user-images.githubusercontent.com/34900092/64690083-7def0280-d487-11e9-9e49-bf8463759497.png)

So I guess we need to isolate the cause further. What does your setup look like?

**Comment by snowe2010** [comment]
I can upload my whole instance if that would help.

**Comment by temp1011** [comment]
Yep that would be great

**Comment by snowe2010** [comment]
https://www.dropbox.com/s/6nzzdo69qa4pw68/ABitOfEverything.7z?dl=0

**Comment by snowe2010** [comment]
Hope that link works.

**Comment by temp1011** [comment]
Which mod causes vanilla trees to grow to different shapes?

**Comment by temp1011** [comment]
That is what's causing the problem AFAICT because it's trying to grow giant trees but there are saplings/multifarm blocks in the way. If you try with apple oak things seem to run fine.

**Comment by snowe2010** [comment]
I am not sure. I did not create the modpack and this is my first time using it. Awesome find though.

**Comment by temp1011** [comment]
The mod that causes the big trees is Recurrent Complex.
You can disable the big trees by setting `saplingTriggerChance` to 0 in `reccomplex.cfg`.
I haven't tested a forestry multifarm yet but I assume with a normal sapling growth the multifarm will work fine.
