### ISSUE TITLE
Farm multi structure crashes world and does not allow it to reload. 

### ISSUE THREAD

**Issue by GrimmDemon** [ForestryMC/ForestryMC#2475]
MC version: 1.12.2
Forge version: 1.12.2-14.23.5.2837
Forestry version: 1.12.2-5.8.1.322 (cannot find a later version than this on curseforge)
The farm multi structure totally crashes my worlds when I complete the initial structure, no platform yet. When I try to reload the world after restarting minecraft and it crashes the game again, the world is totally busted. I can supply the crash log if necessary. I don't want to delete my world, is there any hope for reloading it after the forestry version is updated? This the same version that the peat fired engine gives me a crash when I go into the gui. I read other threads that there is an update, but I cannot find it. Pls help, I'd really appreciate it.

**Comment by temp1011** [comment]
[Here](https://www.curseforge.com/minecraft/mc-mods/forestry/files/2755279) is a newer version. Unfortunately curseforge shows the year old release build much more prominently than the recent betas.

If you are still crashing after updating then the crash report/log would be useful

**Comment by GrimmDemon** [comment]
It seems like the update works perfectly. Thanks a million for the help.
The world loads successfully and the farm multi structure works too.
Much appreciated

**Comment by temp1011** [comment]
No problem :)
