### ISSUE TITLE
built a forestry farm then crashed now world wont load in

### ISSUE THREAD

**Issue by robotalec** [ForestryMC/ForestryMC#2477]
I am using the Minecraft 1.12 version of forestry and when I built a farm multiblock structure the game crashed now the world will not load. attached is a crash report I am using the latest version of forestry.
[crash-2019-09-22_14.50.34-server.txt](https://github.com/ForestryMC/ForestryMC/files/3640167/crash-2019-09-22_14.50.34-server.txt)

**Comment by temp1011** [comment]
The new curseforge website layout shows the very old last release build above the latest beta ones. Your crash should be fixed by the version of forestry from here: https://www.curseforge.com/minecraft/mc-mods/forestry/files/2755279.
