### ISSUE TITLE
Disabling specific sides of a farm does not work

### ISSUE THREAD

**Issue by Flow86** [ForestryMC/ForestryMC#248]
Hi,

I build a large farm with different stuff on each side. Now I have the problem that I can't disable specific sides of the farm.

I tried:

![fail1](https://cloud.githubusercontent.com/assets/656249/4433905/eeef4fd2-46f5-11e4-80e5-9c41972c284d.png)
![fail2](https://cloud.githubusercontent.com/assets/656249/4433904/eeee8016-46f5-11e4-8e8b-a1fc2343ca04.png)

only disabling the complete farm worked, not only one side like specified in the (old/new) wiki

**Comment by mezz** [comment]
Ok this is fixed now. To disable the sides, the redstone signal must come from the side (like the bottom picture).
