### ISSUE TITLE
Farm stopped working on two opposing corners

### ISSUE THREAD

**Issue by jojomodjo** [ForestryMC/ForestryMC#2481]
It was working fine yesterday, logged into the server today, and only two sides are working. (opposite corners) Tried replacing the chip, breaking the farm and replacing it but no luck so far. Any idea why it is doing this?

On FTB DW20 V2.5.0

**Comment by Nedelosk** [comment]
Probably related to: #2451

**Comment by Nedelosk** [comment]
Could you please make some screenshots of your farm layout?

**Comment by Nedelosk** [comment]
Closed because of no response.
