### ISSUE TITLE
[1.12.2] - Forestry Cherries do not stack.

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#2494]
![image](https://user-images.githubusercontent.com/44342726/67058179-9b308400-f14b-11e9-8b47-db6d8ff3dc60.png)

Forestry Cherries do not stack and/or glitch out when stacking.

Involved Mods:
- Forestry
- FoodFunk (removed, issue still present)
- MouseTweaks
- Pams HarvestCraft

**Comment by ghost** [comment]
^ FoodFunk has not been tested, I was meant to say that MouseTweaks was removed and it was still present.

**Comment by temp1011** [comment]
I would guess this is something to do with whatever causes the rotting (foodfunk?)

**Comment by ghost** [comment]
due to foodfunk, sorry for late reply.
