### ISSUE TITLE
[1.12.2] Peat engines cause Ticking block entity crash

### ISSUE THREAD

**Issue by SpaceKn1ght** [ForestryMC/ForestryMC#2495]
https://gist.github.com/SpaceKn1ght/f42a2faba26f634cd3eaa661d93d5769

I'm using forestry_1.12.2-5.8.1.322 and it always seems to crash as soon as I place peat engine next to another thing (for example cables, another peat engine). I do use other mods, but everything seems to  be compatible, aside from Advanced Rocketry, whose rocket assembler seems to crash the game as well. None of the other engines give me this issue.

**Comment by temp1011** [comment]
The version you are using is very old. Please try with the latest beta from here: https://www.curseforge.com/minecraft/mc-mods/forestry/files/2806589

**Comment by Nedelosk** [comment]
Closed because of no response.
