### ISSUE TITLE
[1.12.2] Bees in alvearies disappeared after a power outage

### ISSUE THREAD

**Issue by Squaredude** [ForestryMC/ForestryMC#2500]
Single player world, using:
Minecraft 1.12.2
Forge 14.23.5.2838
Forestry 5.8.2.394
FTB Continuum 1.6.0

There was a one second power outage today while I was playing.

Computer rebooted, and when I opened up Minecraft it wouldn't load the world. It crashed to desktop. So I looked up the issue, and after following a suggestion to delete the "advancements" folder, the world loaded.

Everything seemed fine, until I walked up to the alvearies and realized they were all empty.

All were Pristine queens, so there is no reason for them to be gone. And there were several drones stacked for them to continue working without my intervention, which also disappeared.

Not sure how helpful this might be, and there's obviously no crash report.

**Comment by brisingraerowing** [comment]
I would say this was caused by minor world data corruption when the power went out. Things like this are why backups are important. I use Aroma Backup (usually), but you can do whatever you wish. I also sync the backups folder to another drive in the event of an issue (though my current setup doesn't do that yet).

**Comment by Squaredude** [comment]
If so, the world got corrupted alvearies for life, because it happened again without power outage sometime later. I gave up on that save shortly after that, and now I'm done with Minecraft until Forge/Fabric sort themselves out.

So I'll just go ahead and close this.

**Comment by soncemvo** [comment]
Can confirm, this bug. Its related to https://github.com/ForestryMC/Binnie/issues/623
