### ISSUE TITLE
Can't raise Marshy Bees! [1.12.2]

### ISSUE THREAD

**Issue by CircusSeal** [ForestryMC/ForestryMC#2501]
I'm trying to raise Marshy Bees in an Apiary. The flowers they require are mushrooms, but here's the problem: Mushrooms need darkness to be planted, but when I tried to plant a mushroom and put the apiary next to it, it told me it needed to have the sun directly above it. So, I can't get it to work because of this paradox.

**Comment by SandGrainOne** [comment]
Mushrooms doesn't need complete darkness. It is enough to have a shade. You can also place the Apiary a few blocks away from the Mushrooms. I don't remember the exact numbers; light levels or distance, but there should be a lot of room to find a good solution. Good luck.

Edit: Forestry also makes it possible to craft Mycelium. You can plant Musrooms on Mycelium at any light level.
