### ISSUE TITLE
1.12.2 i guess all versions

### ISSUE THREAD

**Issue by Ezoteric** [ForestryMC/ForestryMC#2507]
The pod texture in MC has changed. pod 0 and 2 are merged into 0 so they share their texture.

I fixed this for sphax by changing the json 2 files to look for texture 0 and merged the 2 textures in texture 0

**Comment by Nedelosk** [comment]
As far as I can say there are still 3 textures for the 3 stages. At least in version 1.12.2 and 1.15.2.
