### ISSUE TITLE
[1.12] Butterflies won't spawn

### ISSUE THREAD

**Issue by angiioh** [ForestryMC/ForestryMC#2511]
I've tried researching this, but most people seem to have had troubles in the past with too many butterflies...but in my case, butterflies aren't spawning from the forestry trees. I have a lime tree and a cherry tree grown in the plains biome, but there aren't any butterflies. When I've played with forestry in the past, I never ran into this problem.

Thanks!

**Comment by AhiVT** [comment]
Post your forestry config file

**Comment by Nedelosk** [comment]
Closed because of no response.

**Comment by DeadSix27** [comment]
> 
> 
> Closed because of no response.

I actually experience the same issue, I noticed that I have no butterflies when the world-type is "gardenofglass" from botania.
BiomesOPlenty type works, will need to investigate further.
