### ISSUE TITLE
[Suggestion] Piston breaks ash block in Charcoal Pit

### ISSUE THREAD

**Issue by reserveword** [ForestryMC/ForestryMC#2512]
Ash is fragile so that it breaks when moved by piston.
It can be useful in automating Charcoal Pit.

**Comment by Nedelosk** [comment]
https://github.com/ForestryMC/ForestryMC/commit/861560136a00d0bdcdce00c3b002bb35c079235b#diff-dcceac490bd386e5796fa995287299dcR85-R89
