### ISSUE TITLE
Help me plz game crach

### ISSUE THREAD

**Issue by MoonGhost18** [ForestryMC/ForestryMC#2513]
[game crash report 3.txt](https://github.com/ForestryMC/ForestryMC/files/4070746/game.crash.report.3.txt)

I have no idea what to do but forestry is metioned so i was thinking you might know!!!

**Comment by inspiiree** [comment]
Same issue here, this is the crash report I get (server)
https://pastebin.com/raw/gusXrBgV

**Comment by Nedelosk** [comment]
Duplicate of https://github.com/ForestryMC/Binnie/issues/626
