### ISSUE TITLE
[Compatibility Request] add rubber tree breeding

### ISSUE THREAD

**Issue by assassinzghost** [ForestryMC/ForestryMC#2514]
Would it be possible to add a tree breeding recipe for IC2/ Tech Reborn rubber trees? 
The functionality only needs to make the leaves/sapling obtainable.

**Comment by Nedelosk** [comment]
There currently is no plan to add custom breeding into forestry. Maybe we will think about that if the port of 1.15 is more finished.

**Comment by Nedelosk** [comment]
Duplicate of #1482
