### ISSUE TITLE
Crashing Foamfix + Forestry

### ISSUE THREAD

**Issue by Kittensworth** [ForestryMC/ForestryMC#2515]
Mined up an item and when I hovered over it, crashed minecraft. Accidentally selected it on my hotbar, not only does it crash the game, I can't even play. Currently playing on a server with Engineer's Life modpack. Posting to Foamfix as well.

https://paste.dimdev.org/unelejefib.mccrash

**Comment by AhiVT** [comment]
I've designed a fix for this bug and will be opening a Pull Request for it tomorrow. If you'd like it now, DM me on Discord: Dunkel#0001

**Comment by AhiVT** [comment]
#2505 #2502 are duplicate issues of this bug.
@kreezxil @warmist I'm pinging you because you've also experienced this bug and I may have a solution for you.

**Comment by warmist** [comment]
@Kexerval are talking about: #2506 ? Either way thanks for the fix.

**Comment by AhiVT** [comment]
@warmist Sorry I definitely meant the `IllegalArgumentException` #2505

**Comment by Nedelosk** [comment]
Duplicate of #2502
