### ISSUE TITLE
BlockResourceOre is missing case label for enum constant BRONZE

### ISSUE THREAD

**Issue by AhiVT** [ForestryMC/ForestryMC#2517]
https://github.com/ForestryMC/ForestryMC/blob/6587ca9627f9652a233f5ef1c7098b35cda4b777/src/main/java/forestry/core/blocks/BlockResourceOre.java#L72-L97

This was brought to my attention as a warning in my IDE. This may be leading to the crashes that #2516 mitigates.

**Comment by Nedelosk** [comment]
https://github.com/ForestryMC/ForestryMC/commit/aeef331d742dc8bb7e05331b1df7ff5e3e469400
