### ISSUE TITLE
Editing Rarity for Trees that Do Not Spawn by Default Does Not Cause Them to Spawn

### ISSUE THREAD

**Issue by Doublehelix13** [ForestryMC/ForestryMC#2527]
Because it can be very annoying to find arborists that will trade for Giant Sequoia pollen or saplings, I wanted to make it so Giant Sequoias spawn rarely in the world.  I first set the rarity of the Giant Sequoia to 1.0 in the arboriculture file to see what biomes they spawn in, but after hours of exploring a wide variety of biomes found none.  As a test, I set the rarity of the Hill Cherry and the Coastal Sequoia trees to 1.0, and found that in the biomes the Hill Cherry spawns in, tons of Hill Cherry trees spawn, as expected, but Coastal Sequoias and Giant Sequoias were nowhere to be found.  This is version 5.8.2.414 for Minecraft 1.12.2.

**Comment by Nedelosk** [comment]
![2020-02-26_19 45 13](https://user-images.githubusercontent.com/10259214/75460358-a7daa980-5981-11ea-988a-c71ccdaeac19.png)
Works great now
