### ISSUE TITLE
Possible bug with autofarm saplings collection?

### ISSUE THREAD

**Issue by Kilmatar** [ForestryMC/ForestryMC#2528]
Maybe this is a defined behavior but it looks like an error.
1. Simple autofarm with oak trees
2. Farm collect logs, apples and saplings
The problem in a saplings collect logic - they are all going to output instead of filling internal buffer first. So it leads to internal saplings buffer emptying and farm stops working

**Comment by Kilmatar** [comment]
Forgot to add details:
MK: 1.12.2
Forestry: 5.8.2.409

**Comment by Nedelosk** [comment]
This is defined behaviour so you can automatically fill a new type of saplings in without worrying about the old sapling type.
