### ISSUE TITLE
AE crafting JEI auto-add

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#2540]
Self explanatory. Tried to auto-add from jei the crafting recipe for an apiary and get a connection lost with the following info:
"Internal Exception: java.lang.IllegalArguementException: Payload may not be larger than 32767 bytes"
As with last issue, can just reconnect to the server with no issue.

Manually putting the items into the crafting grid of the terminal works fine. Whether all components of the recipe are available in the system or not makes no difference.

modlist can be found in #2539's crash report

**Comment by ianlavr** [comment]
I think this bug isnt Forestry related. This is more of a AE2 bug.
