### ISSUE TITLE
papaya stairs have a weird shadow texture 

### ISSUE THREAD

**Issue by epicyeeto** [ForestryMC/ForestryMC#2580]
have this texture that 
![2020-10-26_18 54 12](https://user-images.githubusercontent.com/73504007/97237695-0b8dce80-17be-11eb-9a27-f8262aae7b09.png)
doesn't look right

**Comment by ianlavr** [comment]
I dont think that this is Forestry issue. I think that all Minecraft stairs can do that? But it looks different from what i remember... I remember this bug going around 1.7.10 version of Minecraft. Maybe it is Forestry related.

**Comment by epicyeeto** [comment]
3 years we did it 🥹

**Comment by thedarkcolour** [comment]
still figuring out how to post a jar on CurseForge because some things are broken
