### ISSUE TITLE
Not an Issue but will u update to 1.16?

### ISSUE THREAD

**Issue by SK808** [ForestryMC/ForestryMC#2587]
Not an Issue but will u update to 1.16?

I think a lot of people would love to see this mod update to 1.16, I know Minecraft already has bees and such but maybe it could be tweaked to support 1.16 as well! :D

**Comment by ramidzkh** [comment]
There are multiple disabled or missing features. Look at the description of https://github.com/ForestryMC/ForestryMC/pull/2586 if you want to see what needs to be done

**Comment by Nedelosk** [comment]
We are currently working on an update but it still needs some time to finish.

**Comment by SK808** [comment]
ok :D
