### ISSUE TITLE
[1.16.5] SnowParticleType for invalid dist DEDICATED_SERVER

### ISSUE THREAD

**Issue by Drackonic** [ForestryMC/ForestryMC#2597]
I am able to start and successfully load the mod in the Minecraft client with a built jar from the 1.16.5 branch but a server will not start creating the error at load time of "java.lang.RuntimeException: Attempted to load class/forestry/core/particles/SnowParticleType for invalid dist DEDICATED_SERVER"

Forge Version: 36.1.13
OS: Windows 10 64bit

Crash Report here. https://pastebin.com/bCnGVShM

**Comment by Nedelosk** [comment]
I will fix this, but could you please report bugs for the test version on the forestry discord like it is described in the #info channel.

**Comment by Nedelosk** [comment]
your help is much appreciated
