### ISSUE TITLE
[1.12.2] Tree Blacklist either not working or incorrectly added

### ISSUE THREAD

**Issue by Librv** [ForestryMC/ForestryMC#2598]
Hello!
I added to the default common.cfg , under the ore generation section, the [tree section](https://pastebin.com/w3Zan3fV), but it seems like it does nothing, since the trees [keep generating](https://i.nuuls.com/8Y_dU.png) in the blacklisted biomes. I looked at issues reported by other users on the tree blacklisting problem and, since I do not have Dynamic Trees, I can't really find the issue here, unless I'm placing the blacklist in the wrong place (the more likely one) or it's the mod itself.
Thanks in advance.

**Comment by Primitive-Human** [comment]
Which Forestry version (not MC version) are you running? 
And is there an arboriculture.cfg file in your Forestry folder?

**Comment by Librv** [comment]
5.8.2.422, and yes, there is an arboriculture.cfg file, so I guess I have to use that one to configure the tree generation, thanks! I'll close the issue.
