### ISSUE TITLE
1.18.1 port issue list

### ISSUE THREAD

**Issue by ramidzkh** [ForestryMC/ForestryMC#2630]
Issue list for everything broken in the update/1.18.x branch

**Comment by ramidzkh** [comment]
[Spawning butterflies crashes the server](https://gist.github.com/ramidzkh/6ed34a88570851c71f39f5d5fcd7e3f2)

Edit: Fixed in https://github.com/ForestryMC/ForestryMC/commit/8ca585377fab73d6a155ea79d0c31eef3d8555d8 but I could not get it to crash the server initially

**Comment by r3dj4ck0424** [comment]
Deepslate apatite ore currently has no texture (and is generating above y=0
![2022-01-28_19 23 31](https://user-images.githubusercontent.com/51569477/151498837-e219072d-674b-4e01-a2bd-dd6c38bd1e42.png)
)
Actually, none of the ore textures seem to be in place (along with the raw tin texture)

**Comment by r3dj4ck0424** [comment]
Bee houses, apiaries, and alvearies currently don't appear to be functioning (and the bee houses aren't accepting hopper inputs)

**Comment by r3dj4ck0424** [comment]
Forestry trees don't appear to be dropping saplings or fruit unless a grafter is used

**Comment by ramidzkh** [comment]
Most blocks are missing their preferred harvest tool. Need to 'revert' https://github.com/ForestryMC/ForestryMC/commit/76b0b47e00df623cc6076c3a6649ee425d77423d and https://github.com/ForestryMC/ForestryMC/commit/a7a86de4ee335ecb8cfa623605462ce6bedde636 to use tags instead

Edit: Partially fixed by https://github.com/ForestryMC/ForestryMC/commit/d799619fd618c10702915c3d3e2c86f48bd59472

**Comment by r3dj4ck0424** [comment]
The temperature of plains is currently listed as 'icy' by the (broken) bee house GUI and habitat locator. I suspect temperature isn't being set properly for biomes.

Edit: Fixed by https://github.com/ForestryMC/ForestryMC/commit/0c0471bbacffb73187be539aa6b48579ed2a32c7

**Comment by ramidzkh** [comment]
Item interaction inside inventory GUIs are impossible

Edit: Partially fixed by https://github.com/ForestryMC/ForestryMC/commit/6346eff5199d2a4dac598f686a001c7d99383b30

**Comment by ramidzkh** [comment]
Ledger rendering is broken

Edit: Fixed by https://github.com/ForestryMC/ForestryMC/commit/d77c4c6591fefdc797528bc5b7e1f630a467e351

**Comment by ramidzkh** [comment]
Bees can just change species when relogging
Edit: Only in apiaries, not in player inventory

**Comment by Tony-Starling** [comment]
Client crash if player pick up items and have backpack in inventory
