### ISSUE TITLE
Multifarm does not accept/use fertilizer

### ISSUE THREAD

**Issue by Hansie211** [ForestryMC/ForestryMC#2631]
I can not insert any stack of fertilizer into the multifarm, if the stack amount is >1. If I insert them 1 by 1, I can only stack 2 inside the farm at max.
With the use of a hopper, I can store upto 64 fertilizer items. However, if the multifarm has used 1 fertilizer, it will not grab the next one. It will stop working and say it's missing fertilizer. If I remove all the fertilizer and insert just 1, it will work again (until it is out of fertilizer).

**Comment by ramidzkh** [comment]
Confirmed, testing the fix right now
