### ISSUE TITLE
Genetics API artifact?

### ISSUE THREAD

**Issue by bdew** [ForestryMC/ForestryMC#2638]
I'm looking to update my mods that work with Forestry to 1.16 - JEI Bees and later Gendustry

Forestry API jar only has forestry.api package but it references a bunch of stuff from genetics.api - is that available somewhere else? Or if not could it be included in the api artifact?

**Comment by ramidzkh** [comment]
Ah I only fixed this on the 1.18.1 update branch. I'll fix this along with the next issue I fix on 1.16.5
