### ISSUE TITLE
Serious RAM bug

### ISSUE THREAD

**Issue by Gartebex-Ugandi** [ForestryMC/ForestryMC#2674]
Thank you for reporting!

For issues:
 * Try the latest version, it may have fixed the issue already.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.
For some reason, when you left a world and then join again, it will use more ram than before. Also side note, backpack textures go away then.

Before:
![Ram bug 1](https://user-images.githubusercontent.com/102457574/180815068-23ee4fc9-8d25-4ca4-a16f-be0821a38409.png)

After:
![Ram bug 2](https://user-images.githubusercontent.com/102457574/180815103-3fb53c5d-37a4-4b7e-b0b1-b5953c7c779a.png)

**Comment by ramidzkh** [comment]
Please re-open with something like the [Spark profile](https://spark.lucko.me/)
