### ISSUE TITLE
Forestry error

### ISSUE THREAD

**Issue by Pepper1212** [ForestryMC/ForestryMC#2676]
Hi! I am using forge 1.16.5 36.2.35 with forestry mod version 6.0.14. My game crashes and this message appears: 
 
Failure message: Forestry (forestry) encountered an error during the common_setup event phase
		net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: ic2:crop_res:2

Full crash report: https://gist.github.com/Pepper1212/29b8ca9314f23d3e988b760ea4bf13e7

I have no idea what to do, please help!!!

**Comment by ramidzkh** [comment]
IC2 integration was removed, should no longer happen
