### ISSUE TITLE
Walk-on particles

### ISSUE THREAD

**Issue by xJon** [ForestryMC/ForestryMC#2677]
(Using the latest version) walking on machines renders missing-texture particles:
![image](https://user-images.githubusercontent.com/8945347/181905064-4e705426-469c-4b0e-896a-84f4892fdc09.png)

**Comment by xJon** [comment]
Same issue with special chests (e.g. Arborist's Chest).

**Comment by thedarkcolour** [comment]
which version is "latest version" ?

**Comment by xJon** [comment]
@thedarkcolour I was referring to 1.12.2, `5.8.2.422`.

**Comment by xJon** [comment]
Resolved in https://github.com/ACGaming/UniversalTweaks/pull/447.
