### ISSUE TITLE
[1.12.2][5.8.2.422] Bio Generator explode IC2 machines

### ISSUE THREAD

**Issue by fandasliz** [ForestryMC/ForestryMC#2690]
Bio generator works fine when going without stopping but when stopped It can store up to 30k eu and then It will explode basically any IC2 machine. I tried looking into config files but didn't find anything related to eu output. I have a short video for demonstration.
Used IC22: IC2Classic 1.12-1.5.5.2.1
Modpack: Tekkit 2

Youtube: https://www.youtube.com/watch?v=hP7Z7bJxj5E

Thanks.

**Comment by xJon** [comment]
This was also reported over https://github.com/xJon/Tekkit-2/issues/66, and apparently it's on Forestry's end.
