### ISSUE TITLE
Infinity Charcoal

### ISSUE THREAD

**Issue by Mat1212fr** [ForestryMC/ForestryMC#2698]
Hey, just a random bug, I hope there is one because it's a little CHEAT. I leave you with the pictures : 
![image](https://user-images.githubusercontent.com/99351856/212470658-a53d4b27-f4fb-4855-9a44-443ffb526395.png)
A charcoal gives 9 ???
So please, fix that !
Thanks

**Comment by PokeMaserJ** [comment]
It would help the devs for you to give what version of Forestry, and the game version. Just a heads up. Can't really tell from just a screen shot either of those

**Comment by Mat1212fr** [comment]
Sorry, the version is forestry-1.16.5-6.0.14
