### ISSUE TITLE
Crash when placing or breaking farm block (1.12.2)

### ISSUE THREAD

**Issue by vainlaind4in** [ForestryMC/ForestryMC#2710]
Forestry Version: 5.8.2.422

After placing a farm block, game freezes for a bit, and then crashes with this crash report
https://gist.github.com/vainlaind4in/1eaea43035ab1235574939d479931085

**Comment by McModknower** [comment]
That looks like Fancy Block Particles causes forestry to try and get the world of the block before the block is properly placed.

Try disabling Fancy Block Particles for the farm block and any other block that causes a crash on placement.

**Comment by vainlaind4in** [comment]
> That looks like Fancy Block Particles causes forestry to try and get the world of the block before the block is properly placed.
> 
> Try disabling Fancy Block Particles for the farm block and any other block that causes a crash on placement.

Yeah I have had this problem with many other blocks in this modpack. I just disabled the placing animation outright just to not have this happen to other blocks.
