### ISSUE TITLE
Mated butterflies not laying caterpillars.

### ISSUE THREAD

**Issue by Nymbala** [ForestryMC/ForestryMC#2717]
Hi there! I was playing a modpack with one of the forestry add-ons, specifically Binnie's mods. I have bred a few butterflies by getting their serums in an escritoire and combining them by hand, but when I drop them near or on forestry leaves and wait a few days, I don't see any cocoons under the leaves so I don't know if they are indeed laying their offspring. What's more, when I use a scoop on these leaves after a few days have passed and have checked for caterpillars, I don't get any. Am I doing something wrong or is this a bug I don't know about?

**Comment by thedarkcolour** [comment]
It is a bug :D
