### ISSUE TITLE
1.20.1 version bounty [Non-Issue]

### ISSUE THREAD

**Issue by border999** [ForestryMC/ForestryMC#2719]
I’m putting a bounty on a port of this mod to 1.20.1. I’m willing to pay as high as 150-300 USD

**Comment by FrozenGalaxy** [comment]
Include gendustry, preferably binnies and I'd add money too. But with 1.20.4 in mind later.

**Comment by thedarkcolour** [comment]
I'm here to claim my bounty :) my Discord is @thedarkcolour, we can talk more there
[1.19.2 and 1.20.1 port](https://www.curseforge.com/minecraft/mc-mods/forestry-community-edition)
Here's my Ko-fi: [https://ko-fi.com/thedarkcolour](https://ko-fi.com/thedarkcolour)

**Comment by FrozenGalaxy** [comment]
Awesome work! You planning on Binnies mods? Then I'll def add my share to the bounty too, like i mentioned in the early post.

**Comment by thedarkcolour** [comment]
I'm going to port Gendustry, and I know someone else was working on a Binnie's port. Binnie's is a huge mod though, so that probably won't be coming for a while.

**Comment by FrozenGalaxy** [comment]
> I'm going to port Gendustry, and I know someone else was working on a Binnie's port. Binnie's is a huge mod though, so that probably won't be coming for a while.

does the binnie port have an active repo here?
also glad you're going to port gendustry

**Comment by thedarkcolour** [comment]
Unfortunately it's a private repo and hasn't been updated in two months. The author is @jasonsherrmann

**Comment by FrozenGalaxy** [comment]
that doesnt sound promising 🙃

**Comment by border999** [comment]
@thedarkcolour seen and noted, I should be getting paid tomorrow or Friday so you can expect your bounty in the next couple days. And I will apologize for not immediately having the bounty on hand for you. It's been almost a year since I posted this and I honestly forgot about this until I saw the notification.

**Comment by border999** [comment]
bargain made, bargain completed.

**Comment by jasonsherrmann** [comment]
> that doesnt sound promising 🙃

I couldn't agree more. I'm working with @thedarkcolour on a plan to move forward.

**Comment by FrozenGalaxy** [comment]
> > that doesnt sound promising 🙃
> 
> I couldn't agree more. I'm working with @thedarkcolour on a plan to move forward.

Ah, glad to hear of you! DM me if you guys need  any help, I do not really have spare time to learn MC Forge, but I know generic java and can do other stuff.
