### ISSUE TITLE
 Where is the code for version 1.12.2 responsible for breeding new species of bees?

### ISSUE THREAD

**Issue by cruel11110** [ForestryMC/ForestryMC#2722]
I decided to mutate a bee that can only be obtained on Easter, I thought it was Orthodox Easter, but it turned out that it was Catholic Easter. Is it possible to somehow change the desired output time by changing the code? If not, can I ask for this to be fixed in future updates?

**Comment by thedarkcolour** [comment]
The Easter bee time range can be found in BeeDefinition.java
