### ISSUE TITLE
Allow Butterflies to live indefinitely

### ISSUE THREAD

**Issue by xJon** [ForestryMC/ForestryMC#2724]
Currently trying to keep butterflies inside of an enclosed modded building causes them over time to all die as they randomly take suffocation damage.

**Comment by thedarkcolour** [comment]
This is actually caused by the butterflies' exhaustion mechanic. If they cannot find somewhere to land after a certain period, they will die.

**Comment by xJon** [comment]
@thedarkcolour That's interesting, but are you sure that's the case? Because they keep dying in areas where they can land, e.g. a greenhouse build or just inside a house. There's at least plenty of floor areas.

**Comment by xJon** [comment]
Apparently butterflies have a maximum lifespan (thanks @Nessiesson). Would be nice if this was configurable.

**Comment by xJon** [comment]
@thedarkcolour @ACGaming Do you know whether there will still be a spawn cap on them if they are configured not to die? Just worried of an overpopulation.

**Comment by thedarkcolour** [comment]
They are supposed to respect spawn caps, although the code for this might be broken in 1.12. I haven't tested that yet.

**Comment by xJon** [comment]
Would need to be tested before or after the update is released.
