### ISSUE TITLE
Any plans to add a mod to Modrinth? (enhancement)

### ISSUE THREAD

**Issue by Alter73** [ForestryMC/ForestryMC#2732]
Hi! I just make quite a lot of modpacks in the Modrinth launcher and a lot of mods have moved there. It is also possible because the service is developed only for Minecraft. It would be much more convenient if Forestry was also in Modrinth, otherwise I have to download it separately for each modpack and check for its updates, but this is very inconvenient when creating modpacks.

**Comment by thedarkcolour** [comment]
I do not have access to Forestry's Modrinth. New updates for 1.12 are available at [Forestry CE's Modrinth](https://modrinth.com/mod/forestry-community-edition/versions).
