### ISSUE TITLE
Villagers should register more deals while increasing tier level and prices

### ISSUE THREAD

**Issue by leagris** [ForestryMC/ForestryMC#286]
As of now, Forestry villagers only register a very limited number of fixed deals.

It should add more and varied deals to better match vanilla villagers as well as scale it to larger number of species in Forestry.

Given villagers unlock next deal when player completed previous ones, I propose this:
For each specie tier, randomly select one or two species for saplings, planks, bees.
Weight emerald cost on tier level.
Add deals from lower to higher tier.

Expected outcome:
- Player have more appropriate number of deals from a single villager, (no need to farm kill villagers)
- Player need to complete lower tier deals to reach, unlock higher tiers
- Chances of getting higher tier deals like the very high tier (non breadable)  giant sequoia sapling are better with this new system, while cost of getting it is higher and require to take care of villager reputation (have to complete all lower deals).

**Comment by mezz** [comment]
I looked into this and it will only be possible in 1.8.  
1.7.10 has random trades, but 1.8 introduces tiers!

**Comment by mezz** [comment]
Villagers are broken in 1.8 and it is not being fixed, this will be possible in 1.9.
