### ISSUE TITLE
Config option for multifarm size

### ISSUE THREAD

**Issue by algul** [ForestryMC/ForestryMC#293]
Would it be possible to add config option to set multifarm size to pre-buffed value please? Or to set the value myself. While the buff to the size is nice, I find myself not needing bigger farms, but rather more of them.

**Comment by mezz** [comment]
I just fixed this issue https://github.com/ForestryMC/ForestryMC/issues/251, so the config isn't really needed.
To separate farms, you can now just leave a gap in the platforms or add a block in the way and it will work correctly.
