### ISSUE TITLE
Energy Tab on machines renders incorrect info

### ISSUE THREAD

**Issue by adudney** [ForestryMC/ForestryMC#295]
![2014-10-22_15 00 11](https://cloud.githubusercontent.com/assets/246232/4744281/e98c438c-5a2e-11e4-8485-526ff836dadb.png)

This still is being powered by 2 combustion engines, one of which is not outputting energy because the still is full of energy, even though the tab says it is empty. Also the info displayed is wildly incorrect, as https://github.com/ForestryMC/ForestryMC/blob/dev/src/main/java/forestry/factory/gadgets/MachineStill.java#L142 states that the max input per connection should be 1100RF, not 1650RF, and the max stored should be 8000RF, not 12000RF.

This happens with other machines as well, such as the fermenter. (https://github.com/ForestryMC/ForestryMC/blob/dev/src/main/java/forestry/factory/gadgets/MachineFermenter.java#L199)

![2014-10-22_15 05 38](https://cloud.githubusercontent.com/assets/246232/4744315/301990fc-5a2f-11e4-9e6f-35d75ee218f0.png)

This is using Buildcraft Beta 6.1.3, so it is completely based on RF.

**Comment by mezz** [comment]
Whew, finally fixed this one now that the network stuff has been redone.
Available in the [unstable build](http://jenkins.ic2.player.to/job/Forestry_Dev/).
