### ISSUE TITLE
No crossbreeding outcome for new 1.7 tree species

### ISSUE THREAD

**Issue by leagris** [ForestryMC/ForestryMC#298]
MC 1.7 introduced new tree species @binnie567 implemented in Forestry with commit 5a34974 on August, 6 about Issue #48.

Though, as of now, there is no crossbreeding mutation outcome from these species.

We still should have proper mutations outcomes from Dark Oak and Acacia.

Lack of implemented mutation cause glitches in researching with the Escritoire game.
Placing these saplings in an Escritoire, lead to a no reward game.

Maybe it should be considered fair to add fruits and saplings, as research rewards as to pair bee species researches rewarding with, some combs and drops additionally to research notes.

**Comment by faminecode** [comment]
Further to this issue, the Dark Oak and Acacia saplings are not accepted by the fermenter.

**Comment by CovertJaguar** [comment]
@faminecode Please open a new issue.

**Comment by Nirek-K** [comment]
I fixed that some time ago.
