### ISSUE TITLE
Crop breeding idea

### ISSUE THREAD

**Issue by McBossKiller** [ForestryMC/ForestryMC#316]
bees can breed trees, but the new butterflies don't do much. Maybe they should pollinate crops to make new crops, such as breeding wheat crops can have a chance to give you barley. Instead of bee houses there can be butterfly cages.

**Comment by McBossKiller** [comment]
I thought this would be a great idea since butterflies barely have any uses

**Comment by VileTouch** [comment]
butterfles pollinate leaf blocks just like bees. if not better

**Comment by mezz** [comment]
This would be a very large feature, and there are already mods that do crop breeding.
For now I'm focused on maintenance and bug fixes.
