### ISSUE TITLE
Crossbreeding Trees and Biomes O'Plenty 1.7.10

### ISSUE THREAD

**Issue by Lankoran** [ForestryMC/ForestryMC#386]
I'm looking to see if there is a list any one knows of where the biomes have been detailed for the compatability between these mods, i've just setup a second test setup in a seasonal forest after what i will now call the "Shrubland Fiasco". and after 4 hours running loaded i'm still not seeing a single leaf pollinated. I'm aware there are alternatives through pollen, and manually doing it. but i'd rather doing it automatically if i can.

I'm seeing quite a lot of butterflies around the area, so i believe something might be happening, but as of yet, even with the spectacles (this time!) no signs of pollination. am i just doomed to fail attempting this in any BoP Biome?

**Comment by mezz** [comment]
Any luck @Lankoran ?

**Comment by mezz** [comment]
@Lankoran ?
