### ISSUE TITLE
Replace Apiarist's Pipe with a sorting block

### ISSUE THREAD

**Issue by mezz** [ForestryMC/ForestryMC#396]
> The Apiarist Pipe should be replaced with a block that is more generic and compatible with more inventory management systems. It should also support Trees and Butterflies.

**Comment by asiekierka** [comment]
If this is ever done, notify me beforehand - I would like to reinstantiate the Apiarist's Pipe as part of BuildCraftCompat if it is removed from here.

**Comment by mezz** [comment]
The block would basically be a retexture that has support for other mods in addition to BC.

**Comment by asiekierka** [comment]
That, or manually present PRs for updating to BuildCraft versions as they come. In general, I am going to go to lengths to ensure that the Apiarist's Pipe stays, even as an alternative to a sorting block.

**Comment by mezz** [comment]
@CovertJaguar thoughts on moving the apiarist's pipe to BuildCraftCompat?
Seems like a fine idea to me. Forestry can implement the sorting block and BuildCraftCompat can keep the nice looking pipe up to date.

**Comment by CovertJaguar** [comment]
I'm fine with that.

**Comment by Nedelosk** [comment]
I think you have moved the apiarist pipe from forestry to bc compat.

**Comment by Nedelosk** [comment]
Any idea how the block should work ?

**Comment by mezz** [comment]
This block should work similarly to the Apiarist Pipe in BuildcraftCompat.
The GUI should be pretty much the same.
When an item is inserted, it should immediately output the item to a side according to the gui configuration. It should not accept items that it can't output somewhere.

**Comment by Nedelosk** [comment]
@mezz What do you think about the block model ? 
![2018-01-08_04 43 11](https://user-images.githubusercontent.com/10259214/34658346-79977b1c-f42e-11e7-97c0-c0a75663e3f2.png)

**Comment by mezz** [comment]
Looks very good! I think I would prefer colored band to be at the end before the connection (2 voxels over from where it is now), and make the pipe a bit wider. It will have a more "simple" look that way which may fit better with Forestry.

**Comment by Nedelosk** [comment]
![2018-01-08_13 52 11](https://user-images.githubusercontent.com/10259214/34671488-265d1c7a-f47b-11e7-96ab-98755c613a6b.png)
?

**Comment by mezz** [comment]
I think that looks great!
