### ISSUE TITLE
Bee House Crash on worldgen

### ISSUE THREAD

**Issue by earthcrafterman** [ForestryMC/ForestryMC#417]
I got this when I started a new world today, it doesn't occur every world so I assume it has to do with Forestry expecting a village where there's not. I've set the village rate to 0, but I can't seem to find an option to disable village forestry gen strange enough. I've heard about a base.cfg, but that wasn't generated either.

Here's my crash:
http://pastebin.com/i7MRd30m

**Comment by mezz** [comment]
Added a line in the crashlog to help if any modules are disabled https://github.com/ForestryMC/ForestryMC/commit/ca9c99c2832ba24a2519d78d1686dbf4604e829f
