### ISSUE TITLE
Problem client/server ?

### ISSUE THREAD

**Issue by quienti** [ForestryMC/ForestryMC#418]
Client : http://pastebin.com/myVsB7zP
Server : http://pastebin.com/dDw32ByA

I have this error in client log and the server, and this server don't respond with anything other mods or Minecraft O.o
5 minutes to open a simple chest of Minecraft
Maybe it's not Forestry, but it's my only possibility at this time ^^

With Forestry unstable 3.3.0.379

**Comment by quienti** [comment]
I have no problem, thank you :)

**Comment by mezz** [comment]
Glad to hear, thanks!
