### ISSUE TITLE
Server crashes at forestry.farming.gadgets.BlockMushroom.tickGermling (Forestry + Nature Overhaul 1.7.10)

### ISSUE THREAD

**Issue by Viperwow** [ForestryMC/ForestryMC#423]
Hello, I've played about two days on my server, then decided to use Nature Overhaul (I backuped existing world before it). ~1 day after server crashed with log:
http://pastebin.com/a8yF4RFz

After a crash I've tried to start server without using Nature Overhaul (so I've deleted it and its configs too for both client and server) at same world. But again I've got the same crash report by server.

Is it Forestry issue? (because I got only "forestry" in crash log and cannot contact with Nature overhaul author)
Didn't tested on client world.

p.s. I'd found player with this problem http://www.minecraftforum.net/forums/support/modded-client-support/2302278-crash-report-pls-help

But I does not have optifine on client or server.

p.p.s. Only without Nature Overhaul and with backuped world it give no crashes (World already little bit affected with Nature Overhaul, but not so hard as tested one)

**Comment by Viperwow** [comment]
Thanks for your promptly work! No crashes for an hour of server work time with both Forestry and Nature Overhaul on. Seems everything do what it should do.

**Comment by mezz** [comment]
Glad to hear, thanks
