### ISSUE TITLE
Possible issue with Forestry and Hardcore Ender Expansion

### ISSUE THREAD

**Issue by Sunconure11** [ForestryMC/ForestryMC#424]
Although most of these are from Extra Trees and Bees, one of these bugged recipes might be from Forestry.

http://pastebin.com/iQbejwDa

**Comment by mezz** [comment]
I doubt this breaks anything but it's nice to know, I'll clean those up. Thanks for report!

**Comment by mezz** [comment]
I looked carefully and neither of the missing recipes is created by Forestry, they just use Forestry items. Hope that helps.
