### ISSUE TITLE
Duplication of liquids

### ISSUE THREAD

**Issue by WinSide** [ForestryMC/ForestryMC#425]
If you click a capsule or can with the liquid to the tank from buildkraft and there is no place in the Inventor, the capsule is not being spent, and the liquid is added

**Comment by mezz** [comment]
Hm that's not good. Thanks for the report!

**Comment by mezz** [comment]
Turns out to be a BuildCraft tank bug. I submitted it to them.

**Comment by WinSide** [comment]
mezz, even if there is a bug fill capsules with liquid and Inventor no place is filled capsules are placed in a slot armor :D
![2015-01-02_14 50 01](https://cloud.githubusercontent.com/assets/7656576/5594663/4730196c-928f-11e4-9aa0-b7f39e700db3.png)

**Comment by mezz** [comment]
uhmm please make a new bug report for that haha

**Comment by WinSide** [comment]
Ok
