### ISSUE TITLE
Farm Hatch is pushing automatically items into pipe from sidewalls.

### ISSUE THREAD

**Issue by marcin212** [ForestryMC/ForestryMC#430]

**Comment by mezz** [comment]
Thanks for the report. Can you post a picture?

**Comment by marcin212** [comment]
screen: https://dl.dropboxusercontent.com/u/25172450/bugs/58e5ec23d08147cf22fb9ba93aaf3b30.png

**Comment by mezz** [comment]
This is expected, the farm hatch automatically pushes its outputs to BuildCraft pipes.

**Comment by marcin212** [comment]
I think and wiki 'think' that auto push should be only down side.
From wiki:
```
Extracting Items

Any item that is harvested by the MultiFarm is automatically ejected by the Farm Hatches into inventories or Buildcraft Transport Pipes directly below them. Pipes can be used to extract from other sides.
```

**Comment by mezz** [comment]
I see, thanks.

**Comment by mezz** [comment]
Fixed in the latest unstable.

**Comment by CovertJaguar** [comment]
I actually changed this intentionally when I rewrote the hatch code. I always thought it was a silly restriction.

**Comment by CovertJaguar** [comment]
The ITileFilter change actually changes behavior away from what it was before the rewrite. Should give that a second look.
