### ISSUE TITLE
Invisible leaves

### ISSUE THREAD

**Issue by marcin212** [ForestryMC/ForestryMC#431]
We have Red Spruce tree farm and generate invisible Apple Oak leaves.
screen: https://dl.dropboxusercontent.com/u/25172450/bugs/4c653baca0b520eb0613ff5b1d258d97.png

**Comment by mezz** [comment]
Thanks for the report!
This one was really tough to figure out. Fixed in the latest unstable.

**Comment by CovertJaguar** [comment]
See line note: https://github.com/ForestryMC/ForestryMC/commit/e5979367ee2bb7f0c7ab4902ca090386c18f435f#diff-37d943715881d01c905433601f828a32R184

**Comment by CovertJaguar** [comment]
@mezz how did you duplicate this? Planting and cutting down trees seems to not result in invisible leaves no matter what code I revert.

**Comment by mezz** [comment]
@CovertJaguar  
You have to plant and bonemeal a tree, remove the trunk wood, then plant and bonemeal another one next to it. All the floating leaves will have their meta value updated for leaf decay, and will immediately turn invisible (tile entity on client is removed, still exists on server).

**Comment by CovertJaguar** [comment]
Very odd...that does work, but makes me wonder why normal single tree decay doesn't trigger it.

**Comment by CovertJaguar** [comment]
I suspect adding markBlockForUpdate() mearly masks the real problem, since beginLeafDecay() is called on all blocks in the area whenever a leaf or log is removed.

**Comment by mezz** [comment]
If you comment out `super.beginLeafDecay()` the problem should go away

**Comment by CovertJaguar** [comment]
Calling markBlockForUpdate() on the client side only seems to be sufficient. Which means the client still has the correct tile entity (and data), since all markBlockBlockForUpdate() does on the client is force mini-chunk rerender.

It seems that every leaf block, that had beginLeadDecay() called on it, in the render mini-chunk that is updated when the tree grows, will not render correctly for some reason. I cannot explain why this is, but I doubt that we will get much benefit from pursuing the issue further. Getting rid of the hugely inefficient net spam created by calling markBlockForUpdate() on the server is good enough for me.

**Comment by CovertJaguar** [comment]
Gah, I take that back. Don't know what I did, but its not working anymore.

**Comment by mezz** [comment]
I don't think the leaf decay is called on client side. Maybe check
minecraft's blockLeaf (super) for some weird special behavior when it has
its meta set?

**Comment by CovertJaguar** [comment]
beginLeafDecay() is call by the the leaf and log breakBlock() function, which I believe is called on both sides.

The original function appears to be trying to avoid a bunch of net spam and rerender cost by changing the metadata from both sides.

**Comment by CovertJaguar** [comment]
Hmm....calling setBlockMetadata() only the server still results in the same behavior. That is...unexpected.

**Comment by CovertJaguar** [comment]
I think I found the cause, its in Chunk.fillChunk(). This code handles bulk chunk data packets from the server. It copies the data into the chunk data arrays then compares the cached block and meta of tile entities to the new data, deleting them if the don't match. I don't see any clean work arounds, but I'll keep looking.

**Comment by CovertJaguar** [comment]
Alright, I've verified that beginLeafDecay() is indeed NOT called on the client. Which means the client and server are not synchronized, hence the TE deletion.

**Comment by CovertJaguar** [comment]
This appears to be a forge bug technically. TileEntity.shouldRefresh() is supposed to prevent this, and does, except in bulk data packets.

**Comment by mezz** [comment]
Interesting, that would make sense! Thanks for taking a closer look.

**Comment by CovertJaguar** [comment]
We may have to survive with invisible leaves until 1.8. It seems the added network traffic is significant.

**Comment by leagris** [comment]
To weight in favor of a forge issue:
This issue started around forge-1.7.10-10.13.2.1232 or 1230.
If I remember right, it worked correctly in forge 1208

**Comment by CovertJaguar** [comment]
The Forge fix has now been merged into both 1.7 and 1.8. I'm going to remove our workaround as it is causing bandwidth issues for some people.

**Comment by CovertJaguar** [comment]
I am fairly confident this issue is now resolved, but if anyone still experiences this issue with Forge 1.7.10-10.13.2.1283 or 1.8-11.14.0.1282 and newer, please report it here.
