### ISSUE TITLE
Skipping beeHouse server

### ISSUE THREAD

**Issue by quienti** [ForestryMC/ForestryMC#437]
Me again ^^

I'll try to explain my problem...
I wanted to update my modpack client and server this morning
With last build of Forestry (unstable 395)

And on startup, I have this message :
[WARNING] Failed Piece with Forestry:BeeHouse
[WARNING] Skipping Piece with id Forestry:BeeHouse

In general, this message means that the block is removed from the server. (Lost all my apiary and my bees ? Very bad news and ideas ^^)

BUT, I can't check on my server because I have a crash with a other mod (Unrelated to this post)

This is the server error : http://pastebin.com/TybBk0rE
And the full log of my server : https://www.dropbox.com/s/qbpdm9v2ktvwfp8/fml-server-latest.log?dl=0

**Comment by mezz** [comment]
Thanks for the full log! I'll take a close look at this issue.

**Comment by mezz** [comment]
The issue should be fixed, please try the latest unstable and report back. I'll reopen this if there are still issues.

**Comment by quienti** [comment]
Work fine
Thank you :D
