### ISSUE TITLE
Offer: FlowerProvider Rewrite

### ISSUE THREAD

**Issue by Samtrion** [ForestryMC/ForestryMC#438]
Hi,

Forestry is one of my favorite mods for minecraft, but the current flower provider system lacks some functionality especially in a modded minecraft with BoP, Botania, Natura and other nature/terrain based mods.
I would like to offer to rewrite the current flower provider system (including API). If you agree to this idea, I would start working and sending a pull request when i'm done.

__Planned Features (at the moment):__

* Ability to register all types of flowers for bees, not only for plains (Vanilla, Snow, Cacti, Gourd, etc.)
	* The ability to define whether this plant is used only as an acceptable plant for the bees or it is planted.
* Ability to add/extend the "growth rules" for all flower types.

	e.g. fertilizer rules for BoP Apple/Persimmon Tree or Natura Berry Bushes, like Melon or Wheat
* Weighted distribution of flowers, based on registered values. 

	e.g. All Vanilla Flowers have a value of 1.0, Botania Flowers have a value of 0.15
	10000 calls growFlower

| FlowerName | Weight | Appearance |
| ------------ | ------------: | ------------: |
| Botania1 | 0.15 | 250 |
| Botania2 | 0.15 | 242 |
| Botania3 | 0.15 | 238 |
| Botania4 | 0.15 | 248 |
| Botania5 | 0.15 | 238 |
| Botania6 | 0.15 | 226 |
| Botania7 | 0.15 | 239 |
| Botania8 | 0.15 | 214 |
| Botania9 | 0.15 | 251 |
| Botania10 | 0.15 | 261 |
| Botania11 | 0.15 | 260 |
| Botania12 | 0.15 | 229 |
| Botania13 | 0.15 | 215 |
| Botania14 | 0.15 | 219 |
| Botania15 | 0.15 | 211 |
| Botania16 | 0.15 | 231 |
| Minecraft1 | 1.00 | 1546 |
| Minecraft2 | 1.00 | 1532 |
| Minecraft3 | 1.00 | 1543 |
| Minecraft4 | 1.00 | 1607 |

	If other plants are added, the distribution is slightly shifted.

| FlowerName | Weight | Appearance |
| ------------ | ------------: | ------------: |
| Botania1 | 0.15 | 180 |
| Botania2 | 0.15 | 185 |
| Botania3 | 0.15 | 188 |
| Botania4 | 0.15 | 198 |
| Botania5 | 0.15 | 176 |
| Botania6 | 0.15 | 199 |
| Botania7 | 0.15 | 177 |
| Botania8 | 0.15 | 195 |
| Botania9 | 0.15 | 179 |
| Botania10 | 0.15 | 160 |
| Botania11 | 0.15 | 210 |
| Botania12 | 0.15 | 195 |
| Botania13 | 0.15 | 179 |
| Botania14 | 0.15 | 204 |
| Botania15 | 0.15 | 196 |
| Botania16 | 0.15 | 196 |
| BoP1 | 0.80 | 993 |
| BoP2 | 0.80 | 1023 |
| Minecraft1 | 1.00 | 1211 |
| Minecraft2 | 1.00 | 1327 |
| Minecraft3 | 1.00 | 1233 |
| Minecraft4 | 1.00 | 1196 |

I am open to other suggestions / requests.

sam

PS: There is a problem with the CLA (https://www.clahub.com/agreements/ForestryMC/ForestryMC).
I get the following error message: "We're sorry, but something went wrong."

**Comment by mezz** [comment]
I like the idea and I'm happy to help with whatever you need!

The only issue is that we have to keep backward compatability with the API. Deprecate, but support.

The CLA thing only needs to be resolved before the PR. It's a buggy piece of junk so hopefully it sorts itself out like it always seems to.

**Comment by Samtrion** [comment]
For the moment, I would say it is sufficient if we declare FlowerManager.plainFlowers deprecated..

**Comment by mezz** [comment]
Sounds good.

**Comment by Samtrion** [comment]
Still no luck for me with the CLA.
Is there another way for signing the CLA?

**Comment by CovertJaguar** [comment]
I think posting your information here along with a link to the CLA should suffice.

**Comment by CovertJaguar** [comment]
This issue may be relevant: https://github.com/clahub/clahub/issues/56

**Comment by Samtrion** [comment]
Please contact me in IRC#forestry-dev under my username samtrion, so i can send you the CLA in private.

**Comment by SirSengir** [comment]
A possible solution for the CLA-problem might be to "sign" it in the repo and include that in the PR. (That would document the fact that the corresponding Github-account agreed to it.) Not optimal, but better than trying to keep track of that outside CLAHub and the repo.
