### ISSUE TITLE
[Request] REPOST license request.

### ISSUE THREAD

**Issue by SinusoidalC** [ForestryMC/ForestryMC#440]
Well, I have played forestry for a long time and now I'd like to share the happiness of playing this mod in my community.
Because of the reasons above, I'm going to repost the forestry to www.mcbbs.net . Which is the biggist MC fourm in China.

I'm just a reposter so I promise to obey these following rules.
1, Always clarify that you are the origin author.(I'll write down your names.)
2, Provide the origin download link. But on account of the poor internet condition, I'll put mod file to my netdisk and provide an alternative link. It will be an absloutely free and ad-free. I won't earn even a cent from it.
3, Always obey EULA.
4, Never change your mod source code.(Include repackage, recompile and redistribute.)
5, In consideration of your income, I'll provide your paetron link(if you have) in my thread. Give you my netdisk link and let you make your adfly link is also ok if you really want ; ).

**Comment by mezz** [comment]
@SirSengir I think you're the only one who can answer this question

**Comment by asiekierka** [comment]
@SinusoidalC - Forestry is under the LGPLv3, obey that license and you'll be fine

**Comment by iTitus** [comment]
If you do not respect the license the website will probably be another candidate for #StopModReposts ;)

**Comment by SirSengir** [comment]
See the license. It is pretty clear. Short and incomplete version: If you redistribute only unmodified official releases, a link to this Github and original download page should cover you.
