### ISSUE TITLE
UBC integration

### ISSUE THREAD

**Issue by Adaptivity** [ForestryMC/ForestryMC#441]
UBC integration will changes textures of ores. Instruction how to add it located here: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293503-underground-biomes-constructs under spoiler: "For modders: How to set up UB textures for your ores".
It's pretty much simple and don't take a lot of time. Metallurgy and Tinkers Construct already have this integration. An example how this integration was added in Tinkers Construct here: https://github.com/SlimeKnights/TinkersConstruct/commit/0972d78077d4290f578c54b99b24e98d6e2cf011 and here: https://github.com/SlimeKnights/TinkersConstruct/commit/c94fc4310fd8412c78dfdca488efc991eca39234

**Comment by mezz** [comment]
Interesting, seems like a cool mod.

**Comment by mezz** [comment]
The code is done but I can't get this mod to load in 1.7.10 at all.

**Comment by Adaptivity** [comment]
Strange. Latest version from here: http://minecraft.curseforge.com/mc-mods/72744-undergroundbiomesconstructs/files working flawlessly for me.

**Comment by Parker8283** [comment]
@mezz, double check you have a deobfed version.

**Comment by mezz** [comment]
Could be my forge version is too high (10.13.2.1286)?
I deobfed it using BON2 for the dev environment.

I'll try a few more things...

**Comment by mezz** [comment]
Looks like it has some reflective code that doesn't work in a deobfed environment.
Added issue here: https://github.com/Zeno410/UndergroundBiomesConstructs1.7/issues/3
Going to check in an obfuscated environment.

Maybe you should optionally translate those strings in BON2.1 @Parker8283 ? ;)

**Comment by Parker8283** [comment]
Something tells me that that may cause more problems than it's worth :P

**Comment by mezz** [comment]
Yeah, probably.

UBC integration is in the latest unstable build!

**Comment by mezz** [comment]
Support has been removed, and added here instead:
https://github.com/mallrat208/UBC-Ore-Registrar/

There were some issues with the registration in some odd cases, and I'd rather it be all together in one mod that handles the integration well.

**Comment by Adaptivity** [comment]
You know that previous worlds will lose all UBC ores? Probably should be reverted again...

**Comment by mezz** [comment]
Even if you add UBC Ore Registrar?

**Comment by Adaptivity** [comment]
Didn't tried it but do you think ALL Foresty users have UBC Ore Registrar? I think better to remove support in 1.8 version.

**Comment by Vexatos** [comment]
@Adaptivity I think it's better to export it to another mod. Keep in mind there is no UBC integration in and release yet, as far as I know. You were so far only able to get it in dev builds anyway.

**Comment by Adaptivity** [comment]
Yes, it's better and I'm ok with it. But I'm worry about other user's worlds. Forestry 3.4.0 release has UBC support and that's might be a problem.

**Comment by mezz** [comment]
Your concern is very appreciated (I don't want to make breaking changes either), but in this case I checked and Forestry 3.4.0 does not have UBC support.
