### ISSUE TITLE
Greenhouse Multiblock Structure

### ISSUE THREAD

**Issue by jojomodjo** [ForestryMC/ForestryMC#442]
I've had this idea in my head for a good while. I have no idea if it would be possible, but it could be pretty cool to have large multiblock greenhouse structures, they could have fans, heaters etc and whatever is placed inside the structure (be it bees, trees or in case of Binnie's Mods theres potential for the botany flowers too) they will think that it is a warmer/colder/wetter/drier biome than it actually was. 

There is even potential for developing another block that would make it into a 'butterfly house', with hatching blocks for caterpillars and cocoons. It could be the start of developing butterflies further, with options of attracting specific species from using a certain combo of flowers and trees.  

I think that the greenhouses themselves would be quite power intensive to keep the balance in no longer having to go seek the correct biome/temperature. Some sort of control block to adjust and set the humidity and temperature could be a nice touch. The more extreme the temperature/humidity is, the higher the power consumption. 

Aesthetically, they would be a cool looking addition for any builder to add to their creations.

**Comment by jojomodjo** [comment]
With reference to the butterfly house structure, the control block could make use of circuit boards and electron tubes for different operations, whether it be creating eggs/caterpillars, hatchery for cocoons, or attracting new species.

**Comment by CovertJaguar** [comment]
Could be pretty cool. I built a cactus farm in a glass dome once, back before multi-farms were a thing.

**Comment by Nedelosk** [comment]
Do you have an idea, how could this look? @jojomodjo

**Comment by leagris** [comment]
IMAO, I'd say look should remain as flexible as possible for design.
I'd define it with similar algorithms as village, inside/outside villager houses. 
So lets maybe draw minimal requirements defining what is a greenhouse.

A greenhouse is a closed space with a controlled environment suitable for agriculture.
Closed space is defined by, having a roof of some kind (any block) upward (no limit).
Ground is within closed space if all surrounding (same Y) blocks in a 5x5 diamond  have roof at any height.

```
  R
 RRR
RRRRR
 RRR
  R
```

A Roof is made of any block (transparent or opaque)

Environmental control is only possible if structure has walls.
Walls can be any kind of blocks in horizontal reach distance of the controller and fill up to height 4.

Vents blocks must be within reach area of the environmental controller and allow lowering temperature. Can be passive (openings), or active (fans, air conditioners)

Heaters blocks must be within reach area of the environmental controller.
Any transparent block with a sunlight level act as a passive heater.

Moisteners, dryers, sprinklers blocks must be within reach area of the environmental controller.
Any open sky block (roof air hole) act as passive humidity device (icorporate biome humidity into the whole structure). Any roof block other than air, act as passive drier.

**Comment by Nedelosk** [comment]
Can you make a picture.I can't imagine this without a picture.

**Comment by Nedelosk** [comment]
Can you make a picture.I can't imagine this without a picture.

**Comment by jojomodjo** [comment]
I envisaged it as glass structure all over, maybe be specific "greenhouse" blocks (think like a multifarm block) that actually appear glass in texture, and still be able to see through them. I don't know much about the nitty gritty of the mechanics about it, but a sloped roof would look the best but I imagine it maybe quite difficult to implement this sort of shape into a multi-block structure, especially as it will have variables on placement of heating controls etc. I'll boot up MC later this evening and do a little design of how I imagine it.

**Comment by jojomodjo** [comment]
Again, might be off here, but the space inside the greenhouse would essentially become a variable biome. Possibly a biome generated? Is that even possible within a set space? I think it will have to to  create a biome of some because of the ways bees etc work. For example, the infernal branch can only be bred in the nether, the temperature and humidity are not the MUST HAVE requirement. (If I'm right in thinking.) Otherwise it may require altering the way bees and flowers work, which would make the greenhouse inaccessible to other mods that make use of temperature. What we are really looking at is a way to generate a small biome within the constrains of a multi-block structure. A starting point could be having no heating controls and start with a "hot house" and a "cool house".
Sorry if I'm rambling. I got excited when I saw the reply, I've imagined this for so very long but lack any skills to do anything about it myself!

**Comment by Nedelosk** [comment]
@leagris Can you make a picture ?

**Comment by Nedelosk** [comment]
When it's possible, i will make that in 1.9 or 1.8.9.

**Comment by jojomodjo** [comment]
![2015-12-13_20 56 51](https://cloud.githubusercontent.com/assets/10377321/11769309/29e45adc-a1dc-11e5-843c-65d759a43990.png)
Had a little play. Would it be possible for the actual multiblock structure to be just the frame, then the player can choose what type of glass or design to use around it? Would it be too intensive to have massive structures like the one on the far left of picture, or would you need to make several smaller greenhouses joined together to make a large one? Just some thoughts!

**Comment by Nedelosk** [comment]
At the moment I haven't a ideas for the roof of the greenhouse. Has anyone an idea for a custom roof ?

**Comment by jojomodjo** [comment]
Something standard in build or something that can transform into a multiblock structure?

**Comment by Nedelosk** [comment]
A custom greenhouse roof for a greenhouse multiblock.

**Comment by Nedelosk** [comment]
I have created a greenhouse multiblock, it will come with the 1.8.9 Version of Forestry.
![2016-03-17_20 09 50](https://cloud.githubusercontent.com/assets/10259214/13857886/3a3fac20-ec7c-11e5-8d9e-7cdab3f4479f.png)

**Comment by jojomodjo** [comment]
So excited for this!!!!! You guys are the best!!

**Comment by Quartz101** [comment]
:( Backport it plz? ;(

**Comment by hron84** [comment]
Talking about greenhouses, I really recommend you to take a look into SonarSonic/Calculator. It has a controller block that builds an entire greenhouse structure from any kind of wood/glass blocks and the built multiblocks are just awesome. If you ask @SonarSonic, he will help you on this.

**Comment by jojomodjo** [comment]
Had a good play in creative today to try and work a few things out, thought I'd update the wiki but wanted to check if everything I have sussed is correct?

Base can be 5x5, 7x7, 9x9 (I assume it can go bigger by any odd number?) and must be made of a solid layer of greenhouse blocks. Height must be at least 5.
Is there limit on how tall it can go?
Roof is domed as in picture, and finishes with a 3x3 space at the top.
Dirt can be placed inside the greenhouse but must be entirely encased within the multiblock structure.

Sprinklers increase humidity (and rotate when active)
Dryers lower humidity
Heaters raise temperature (light up red when active)
Fans lower temperature

Gear box for inputting power
Valve for inputting water

Windows seem to be decorative, I couldn't see any changes in climate when added. (Or are changes very slow like below?)

Bee house does not work in the greenhouse.
Apiary and alveary recognise change in temperature, quickly, but takes a while for humidity to reach the correct levels.

Looking forward to playing with this properly in survival! :)

**Comment by chanzie** [comment]
I did fine with a flat roof in the latest build alhtough vibrant quartz glass should never be attempted as a camo block
