### ISSUE TITLE
Half slabs render incorrectly

### ISSUE THREAD

**Issue by retep998** [ForestryMC/ForestryMC#444]
Slabs placed in the lower half render correctly while slabs in the upper half appear to be attempting to render slabs with a different ID.
![](http://puu.sh/edFkX/4f68eb4856.jpg)
Using Forestry 3.3.0.405 and Forge 10.13.2.1272

**Comment by mezz** [comment]
Interesting, thanks for the report!

**Comment by mezz** [comment]
Fixed in the latest unstable build.

**Comment by retep998** [comment]
Confirmed fixed
![](http://puu.sh/edZM1/913f346e56.jpg)

**Comment by mezz** [comment]
Thanks!
