### ISSUE TITLE
Hellish Climate

### ISSUE THREAD

**Issue by F3UR10** [ForestryMC/ForestryMC#445]
Hi,
we found a bug.

Since 3.0.6 if you place an apiary in nether it only says Hot climate at 200°C.
in 3.0.5 it was hellish and our demonic bees worked.
But Alveary still says hellish in nether.
Pls fix it :)

Thx a lot.

F3UR10

**Comment by mezz** [comment]
Thanks for the report!
That's not good at all.

**Comment by mezz** [comment]
![2015-01-09_20 27 58](https://cloud.githubusercontent.com/assets/916092/5690443/614fc7c0-983e-11e4-8331-68982204011e.png)

Fixed in the latest unstable

**Comment by F3UR10** [comment]
Thank you very much. It was a schock seeing bees in nether wont work :)
