### ISSUE TITLE
Client crashes randomly when I open farm GUI

### ISSUE THREAD

**Issue by marcin212** [ForestryMC/ForestryMC#447]
crash-log: http://pastebin.com/rhzuXi8g
forestry: 3.3.0.409-unstable
forge: 1.7.10-10.13.2.1284

**Comment by marcin212** [comment]
Probably fixed by: https://github.com/MinecraftForge/MinecraftForge/pull/1635

**Comment by mezz** [comment]
That's definitely it, thanks!
