### ISSUE TITLE
Invisible saplings

### ISSUE THREAD

**Issue by marcin212** [ForestryMC/ForestryMC#448]
screen: https://dl.dropboxusercontent.com/u/25172450/bugs/dce292463563cee6860aeb056b9c7866.png
Similar to #431

**Comment by liach** [comment]
I think you should press F3 to check the Forge version. You had better use build 1283 or later. If you are on the Cauldron server, then hard to help you.

**Comment by marcin212** [comment]
I have:
forestry: 3.3.0.409-unstable
forge: 1.7.10-10.13.2.1284

**Comment by liach** [comment]
Singleplayer? Do you have Optifine?

**Comment by marcin212** [comment]
Multiplayer, without Optifine

**Comment by liach** [comment]
Do you know the Forge version of the server? If it's cauldron I couldn't help; the bug CovertJaguar has fixed is not only on client side.

**Comment by marcin212** [comment]
pure forge from http://files.minecraftforge.net/ on client and server

**Comment by mezz** [comment]
Thanks for the report!
Also thanks liach, you are asking the right questions.

I think in this case it is actually a Forestry issue, since our sapling tiles do not override `shouldRefresh` like the leaves do. I'll take a look.

**Comment by CovertJaguar** [comment]
I'm not aware of anything that actually changed the metadata of Saplings, which is a requirement of the aforementioned bug.

However if something is, since the tile doesn't override shouldRefresh() to ignore metadata, then yes, this could happen. Even with the latest version of Forge.

**Comment by mezz** [comment]
Adding `shouldRefresh` fixes the bug, but I'd like to address the question Covert brings up... why are they being updated at all?

**Comment by mezz** [comment]
I believe it is an issue with growing Forestry trees. Growing a vanilla oak next to our saplings does not cause any issue.

**Comment by marcin212** [comment]
I have only Apple Oak Sapling in farm.

**Comment by marcin212** [comment]
Ok, It is weird. My fences turned into Oak fences. When I login to game again different parts of sapling disappear and fences swapped to Oak. screen: http://i.gyazo.com/03b6a460856b7a656249ace183949262.png
I did upgrade forge, forestry and OpenComputers today.

**Comment by mezz** [comment]
Ok the difference is that growing a forestry tree causes a chunk update because of the large number of tiles to sync, while a vanilla tree does not.

With the new forge patch, every tile entity in the updated chunk has `shouldRefresh` called on it.
It is now very important for tile entities to implement `shouldRefresh`.

**Comment by CovertJaguar** [comment]
Vanilla has no concept of checking whether metadata changed, and Vanilla has no concept of blocks using metadata to create different tile entities in a single block. Vanilla only check that the block changed, hence the "oldBlock != newBlock" default for vanilla blocks.

**Comment by mezz** [comment]
shouldn't it be 
```java
if (isVanilla)
{
    return oldBlock != newBlock;
} 
else 
{
    return oldBlock != newBlock || oldMeta != newMeta;
}
```

Right now if it's not vanilla it returns true always

**Comment by CovertJaguar** [comment]
Hmm...fair point. Before I think it was only called explicitly when the block or metadata changed.

**Comment by CovertJaguar** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/1634

**Comment by marcin212** [comment]
fixed by https://github.com/MinecraftForge/MinecraftForge/pull/1635
