### ISSUE TITLE
Farm doesnt use all the farmland while all sides are active

### ISSUE THREAD

**Issue by M4tt1z1n** [ForestryMC/ForestryMC#449]
Normal multifarm 36 farmblocks 3*4
wheat on all sides, but one side just doesnt work.
Dirt wont be placed and so on.
Its also not a chunk border.
http://www.youscreen.de/rewmodia92.jpg
http://www.youscreen.de/lfopctbc44.jpg
the dirt in the picture above always changes form 20 ro 19 and back, like its trying to place the dirt.
http://www.youscreen.de/arrkmsya42.jpg
normal setup...

**Comment by mezz** [comment]
Thanks for the report!
I'll take a look.

**Comment by M4tt1z1n** [comment]
The left side now is also weird. It places the dirt, plants the seeds and the wheat grows but it wont be harvested. The middle areas work just perfect:
http://www.youscreen.de/axcvsemg11.jpg

**Comment by mezz** [comment]
Do you have problems with all farms or only wheat farms?

**Comment by mezz** [comment]
![2015-01-14_23 00 19](https://cloud.githubusercontent.com/assets/916092/5753659/2fc3fddc-9c41-11e4-8f69-ff70a7a5e210.png)

The wheat farm works correctly in my test world. What version of Forestry are you using?

**Comment by M4tt1z1n** [comment]
Cant look it up right now, i use the direwolf 20 ftb pack 1.7.10 version  1.0.3

**Comment by M4tt1z1n** [comment]
It should be version 3.3.0

**Comment by mezz** [comment]
I changed the way the farmland lays out in [the latest unstable version](http://jenkins.ic2.player.to/job/Forestry_Dev/). 
When you get a chance can you update and try it out?

**Comment by M4tt1z1n** [comment]
With the unstable version the bugged side works now.
It places dirt, seeds and it harvests.
BUT
it now places dirt on every stone brick in the area xD
http://www.youscreen.de/qxucsyif24.jpg
my road with sides of stonebricks is 2 blocks away from the smallest farm...
Btw with the unstable version froge gives me some warnings.
Can u take a look and say me wether i should use the old version or can safely use the unstable one?
http://pastebin.com/qXvictcN

**Comment by mezz** [comment]
Thanks for taking a look! Those aren't warnings, just info, they're fine.

It looks like the new problem is a different issue, same as the one about
farms overlapping #251. I will close this and work on that one next.
