### ISSUE TITLE
Flickering render in JABBA barrels

### ISSUE THREAD

**Issue by Adaptivity** [ForestryMC/ForestryMC#450]
Forestry's Saplings, Pollens, Leaves flickering in JABBA barrels. Tested on Forestry 410, Forge 1284, without Optifine. It might be JABBA issue but saplings and leaves from other mods rendered properly in barrels.

**Comment by mezz** [comment]
Thanks for the report, I'll check it out.

**Comment by mezz** [comment]
This looks like JABBA does not correctly render items with multiple render passes.
I tested and it has the same issue with vanilla Minecraft potions.

Can you add info to their issue? 
https://bitbucket.org/ProfMobius/jabba/issue/94/visual-bug

**Comment by Adaptivity** [comment]
Done.
