### ISSUE TITLE
MultiFarms overlapping each other

### ISSUE THREAD

**Issue by flyingPhoenix** [ForestryMC/ForestryMC#453]
I'm running 4 maxed out multi-farms right next to each other, with a 3 block gap in between, but they keep trying to plant on other farms area. This cause then to keep swaping the blocks (like, farmland/humus), destroying the blocks and the crops. It only seems to happen in a little portion of the area, just the one that's with farmland in the screenshot.

By breaking one farm the other one plants all the area, but as soon as you reform it, they start to overlap again.

Now it's just happening with the Tree/Wheat. It happened with the Wart/Sugar Cane ones, but just breaking the soil fixed it, which doesn't help anymore for the Tree/Wheat ones.

![2015-01-15_11 26 06](https://cloud.githubusercontent.com/assets/9591604/5758180/045d0792-9caa-11e4-9e47-eb7e964f3245.png)
![2015-01-15_11 25 59](https://cloud.githubusercontent.com/assets/9591604/5758181/046bac3e-9caa-11e4-9fa3-f064634687be.png)

Running 1.7.10, Forestry 3.3.0.6

**Comment by SandGrainOne** [comment]
The reach of the farms are a lot longer now. I think the reach was boosted x3. My advice is to make them 3x3 instead of 5x5. Or move them a lot further apart. 

Test a little bit in a creative world to get a feel for the new sizes. They are enourmous.

**Comment by flyingPhoenix** [comment]
That's really weird, that came to my mind right away, but I've tried disabling one of then, removing the  soil and giving the other one more valid space, but it was still planting only on that same spot, and leaving all the other extra space.. Gotta test a bit more though..
