### ISSUE TITLE
Fences

### ISSUE THREAD

**Issue by Cronosus** [ForestryMC/ForestryMC#454]
fences not connect to fence gate

![2015-01-15_16 39 10](https://cloud.githubusercontent.com/assets/5349950/5760485/30fc471a-9cd5-11e4-9aef-57866e1aa9ba.png)

**Comment by mezz** [comment]
Thanks for the report!

**Comment by CovertJaguar** [comment]
This requires a new function on Block (isFence(world, x,y,z)) be implemented in Forge.

**Comment by mezz** [comment]
![2015-01-15_20 35 52](https://cloud.githubusercontent.com/assets/916092/5771666/809148ae-9cf6-11e4-96cc-4016b97a2333.png)

I updated the logic to match Minecraft's and extended the `block == Blocks.fence_gate` into `block instanceof BlockFenceGate`. Works to vanilla and natura fence gates, so it's an improvement if not perfect.

**Comment by CovertJaguar** [comment]
Pretty sure it doesn't work on my Gate Tracks. ;)

**Comment by mezz** [comment]
Hmm Covert... about that...
![2015-01-17_15 44 05](https://cloud.githubusercontent.com/assets/916092/5790821/be885368-9e5f-11e4-8707-aa3b6d5bcd04.png)

**Comment by mezz** [comment]
I did find a minor issue though, dumb vanilla fences.
![2015-01-17_15 46 30](https://cloud.githubusercontent.com/assets/916092/5790831/104221a2-9e60-11e4-868b-e6eda57017a1.png)

**Comment by CovertJaguar** [comment]
Yep.
