### ISSUE TITLE
EnderIO Item Conduit cannot extract from Farm Hatch

### ISSUE THREAD

**Issue by ChatFawkes** [ForestryMC/ForestryMC#456]
Forestry Version: 3.3.0.418
EnderIO Version: 2.2.6.323

Conduits don't extract directly from the hatch blocks. You can see that in the following pictures:

![2015-01-15_18 31 57](https://cloud.githubusercontent.com/assets/8399472/5769102/f37b7586-9ce4-11e4-8f82-d66e384682fe.png)

![2015-01-15_18 33 08](https://cloud.githubusercontent.com/assets/8399472/5769108/0b86d756-9ce5-11e4-908f-c2b12e95b8d7.png)

![2015-01-15_18 36 40](https://cloud.githubusercontent.com/assets/8399472/5769136/843cd5ce-9ce5-11e4-83cb-37ebcd449350.png)

The In/Out conduit mode doesn't work either. Currently a temporary solution that I've found is to either use a chest or Item Buffer (from EnderIO) and have a conduit extract from that. Seems like it needs some kind of inventory in between the item conduits and the hatch block.

**Comment by mezz** [comment]
Thanks for the report!
Fixed in the latest unstable.
