### ISSUE TITLE
Crash the Game missing Forestry Water Can

### ISSUE THREAD

**Issue by Dream-Master** [ForestryMC/ForestryMC#458]
I get this error: Forestry 421, and Extra Bees  binnie-mods-2.0-pre4.jar
https://gist.github.com/Dream-Master/ebdf886c1d0e960972a7#file-gistfile1-txt

**Comment by grydian** [comment]
Binnie says his mod is not compatible with unstable forestry builds.  Here is a link to his issue on his bitbucket.

https://bitbucket.org/binnie567/binnie-mods/issue/135/crash-on-startup-with-latest-forestry

**Comment by Dream-Master** [comment]
Ok thanks than i using old Binnie pre 3
