### ISSUE TITLE
Thermionic Fabricator

### ISSUE THREAD

**Issue by blockbreaker1361** [ForestryMC/ForestryMC#459]
The Thermionic Fabricator is not i-sided and needs to be fixed. If you hook up some sort of pipes/conduits to any side, except the bottom, nothing gets pulled out. If you hook up something to the bottom, then everything gets pulled out. The slots need to be fixed.

**Comment by mezz** [comment]
Thanks for the report!
nventories have been redone in the unstable branch. Have you tried with the latest unstable version of Forestry? http://jenkins.ic2.player.to/job/Forestry_Dev/

**Comment by blockbreaker1361** [comment]
I just tried the Thermionic Fabricator in the latest dev build and I was still not able to pull out of it with any kind of pipes/conduits.

**Comment by CovertJaguar** [comment]
I merely migrated what inventory code already existed in most cases, if it didn't already have the proper support it probably still doesn't.

**Comment by mezz** [comment]
Added the ability to automate the Thermionic Fabricator in the latest unstable build.
It now takes ghost items for the recipe, and automatically crafts to keeps its output slot stocked. Automation can remove the items from the output slot.
