### ISSUE TITLE
dupe with beealyzer and obsidian pipe

### ISSUE THREAD

**Issue by SharpBlades** [ForestryMC/ForestryMC#462]
https://www.youtube.com/watch?v=zputCqcValc

**Comment by mezz** [comment]
Thanks for the report!
This does not happen with the latest Forestry Unstable and BuildCraft 6.3.
What versions are you using?
Please update and see if it is fixed for you.

**Comment by SharpBlades** [comment]
Forestry build 422 and lasted dev BC

**Comment by mezz** [comment]
Can you give me a list of steps? I have:
1. set up an obsidian pipe into a chest
2. open beealyzer and put bees in
3. close beealyzer

All that happens for me is the bees go into the obsidian pipe like they should.
Thanks

**Comment by SharpBlades** [comment]
hmmm, its work on server and not work on single

**Comment by mezz** [comment]
Tried single player and on server but no issue. Are you sure the server and client versions match?

**Comment by SharpBlades** [comment]
hmmm... its problem in my dupe preventing system... with all mods works perfectly but not with Forestry T_T
on this problem my system cast closeScreen() on ItemTossEvent

**Comment by SharpBlades** [comment]
it seems that Forestry is throwing items out of the analyzer with some hack

**Comment by mezz** [comment]
That would have been nice to tell me before sending me on some gild goose chase, thanks -_-

**Comment by mezz** [comment]
On inventory close, we do
`player.dropPlayerItemWithRandomChoice(stack, true);`
which is pretty normal.
