### ISSUE TITLE
Biome Analyzer

### ISSUE THREAD

**Issue by mezz** [ForestryMC/ForestryMC#463]
Sometimes it's tough to figure out the temperature and humidity of the biome you're in.
Forestry should have a biome analyzer item that helps you find the right biome for a bee.

**Comment by M4tt1z1n** [comment]
yeah, that would be really cool.

**Comment by SirSengir** [comment]
"R.I.P. Habitat Locator 2012-2014" - Anybody have a resurrection spell handy?

**Comment by mezz** [comment]
With Minecraft adding new biomes, and mods like Biomes o' Plenty and Extra Biomes XL, I think the habitat locator needs some big changes. This would be the spiritual successor.

**Comment by mezz** [comment]
Resurrected the Habitat Locator!
Everything works pretty well now.
Added a tooltip telling you about the biome you're in, with the current temperature and humidity.
Also improved its ability to locate distant biomes, pointing in the right direction, and handling the new biomes and other mod's biomes. Woo!

**Comment by inbflat** [comment]
I can't find the habitat locator, and a recipe I found online doesn't work. Is it gone from the modpack?

infinity 1.3.4
minecraft 1.7.10
forestry 3.4.0.7

**Comment by mezz** [comment]
You need forestry 3.5

**Comment by inbflat** [comment]
ah. cool, thanks.. :)
