### ISSUE TITLE
Breaking a farm block shows red brick particles

### ISSUE THREAD

**Issue by mezz** [ForestryMC/ForestryMC#464]
No matter what kind of farm block texture, the "breaking" particles that fly off are red brick.

**Comment by CovertJaguar** [comment]
This requires completely overriding the default particle effects handler.

https://github.com/CovertJaguar/Railcraft/blob/master/src/main/java/mods/railcraft/common/blocks/ore/BlockOre.java#L286

**Comment by mezz** [comment]
Thanks Covert, that saved me a lot of headache.
