### ISSUE TITLE
Carpenters work badly with automation.

### ISSUE THREAD

**Issue by Kubuxu** [ForestryMC/ForestryMC#467]
Items pushed to carpenter by hoppers end up first in output slot. This means it is almost not possible to automate carpenter.
Also crates are filling up internal buffer which means that automation of crating is also extremely difficult.

**Comment by CovertJaguar** [comment]
Sounds like the slot rules are wrong.

**Comment by mezz** [comment]
Thanks for the report!
Fixed in the latest unstable
