### ISSUE TITLE
Burn time of wooden slabs should be 150 ticks

### ISSUE THREAD

**Issue by oldjunyi** [ForestryMC/ForestryMC#469]
Otherwise it will be a better fuel than charcoal :)

**Comment by mezz** [comment]
Thanks for the report!

**Comment by mezz** [comment]
I added the correct handler to Forestry, but it looks like a bug in FML is preventing it from taking effect.

Closing this issue, you can subscribe to this one instead:
https://github.com/MinecraftForge/FML/issues/559

**Comment by ScottKillen** [comment]
I have release a private fix for this since a fix for 1.7.10 will **not** be forthcoming: https://github.com/MinecraftModArchive/MinecraftForge/releases/tag/10.13.4.1558%2BfuelFix
