### ISSUE TITLE
Engines don't seem to output directly into Machines

### ISSUE THREAD

**Issue by ChatFawkes** [ForestryMC/ForestryMC#470]
Forestry Version: 3.3.0.422

None of the engines seem to output directly into machines (tested on various TE machines and EnderIO machines). Examples below:

![2015-01-21_18 21 27](https://cloud.githubusercontent.com/assets/8399472/5847481/e17eb88c-a19b-11e4-96ce-e55bde7fe63d.png)

![2015-01-21_18 21 40](https://cloud.githubusercontent.com/assets/8399472/5847483/e5bd947c-a19b-11e4-9da2-6f2a22a008b1.png)

![2015-01-21_18 22 09](https://cloud.githubusercontent.com/assets/8399472/5847486/eb5db8b2-a19b-11e4-9ef8-c037195cb6cc.png)

![2015-01-21_18 24 26](https://cloud.githubusercontent.com/assets/8399472/5847489/ee99f2e8-a19b-11e4-81b5-72376f21fe15.png)

They do however directly output to the Energy Cells (Thermal Expansion) and Capacitor Banks (EnderIO).

**Comment by mezz** [comment]
Thanks for the report!
Strange. Might have to do with the way they handle the updated RF API that has `IEnergyProvider`. I'll take a look.

**Comment by mezz** [comment]
Fixed in the latest unstable, will go in the next stable build too.
