### ISSUE TITLE
Crash with Thaumic Tinkerer Ichorium Axe

### ISSUE THREAD

**Issue by Keridos** [ForestryMC/ForestryMC#472]
This happens when using the tree mode of the axe to harvest a tree instantly with some trees: https://paste.ee/p/JLh3t

Forestry 3.3.0.6

**Comment by mezz** [comment]
Thanks for the report!
Looks like you were actually in Square mode since you broke some leaves.

I pushed a defensive fix to prevent crashes, but this most likely has to do with Forge. 
You can update to 10.13.2.1286 or higher to fix leaf tile entity issues.
