### ISSUE TITLE
Crash Server - MailBox

### ISSUE THREAD

**Issue by YouTy6bl4** [ForestryMC/ForestryMC#474]
Please fix a crash server on MailBox.

**Comment by iTitus** [comment]
Crash report?
When does it happen?
Versions?
Other mods?

**Comment by YouTy6bl4** [comment]
Versions: 1.7.10
Version Forestry: 3.3.0.6
Crash: https://yadi.sk/i/6U3Ufugne3tzp +My mods

**Comment by mezz** [comment]
There have been a lot of changes, we are getting ready for 3.4.0.
Can you please try with the latest unstable forestry?
forestry_1.7.10-3.3.0.435-unstable.jar
http://jenkins.ic2.player.to/job/Forestry_Dev/

**Comment by mezz** [comment]
@YouTy6bl4 have you tried with the latest version?

**Comment by YouTy6bl4** [comment]
@mezz, yes, tried.

**Comment by mezz** [comment]
@YouTy6bl4 can you please post a full crash report,  including the mod list?
Posting to http://gist.github.com has no size limit.
Thank you.

**Comment by mezz** [comment]
I think this bug was fixed along with this one: #518
Can you confirm?

**Comment by YouTy6bl4** [comment]
@mezz, the problem is already solved, but I don't risk of set mailbox. But the version mods: 3.4.0.7
