### ISSUE TITLE
Forestry and NEI bug

### ISSUE THREAD

**Issue by Exy-mat** [ForestryMC/ForestryMC#476]
Hi :)

Today I've installed some mods in my own modpack and when I was looking for a forestry recipes in NEI (using the "r"), nothing has happened. And it's the same with every blocs and items recipes, without bees, because the NEI plugin for forestry still functionnal.
I'm using :
 -CodeChickenCore	1.0.4.29
 -NotEnoughItems	1.0.3.74
 -Forge 10.13.2.1286

**Comment by mezz** [comment]
You are missing [the NEI Integration mod](http://www.curse.com/mc-mods/minecraft/225251-nei-integration), it adds recipes for Forestry.
