### ISSUE TITLE
Set a Code Style for Forestry

### ISSUE THREAD

**Issue by Parker8283** [ForestryMC/ForestryMC#477]
As I begin working on a 1.8 port, I've seen about three different coding styles in different places. To combat this, I think that the rules should be posted somewhere, and possibly a formatting profile to import to IDEs. Also, I think the repo should be run through the formatter after all this is decided.

**Comment by mezz** [comment]
I'll come up with something, this is a good idea.

**Comment by mezz** [comment]
Added. Let me know if there's anything wrong with the formatting-settings.jar

**Comment by Parker8283** [comment]
Thanks for this! I'll test out the JAR tonight *(hopefully)*

**Comment by CovertJaguar** [comment]
Is this some kind of eclipse magic? If so, I'm going to need more details.

**Comment by Parker8283** [comment]
It's actually IntelliJ magic. Don't know if Eclipse can import an IntelliJ code style profile, but there might be a plugin for it.

**Comment by mezz** [comment]
Here's info, @CovertJaguar :
https://www.jetbrains.com/idea/help/exporting-and-importing-settings.html

**Comment by CovertJaguar** [comment]
I actually use Netbeans. ;)

**Comment by Parker8283** [comment]
Ah well, don't know if NETBEANS can import an IntelliJ code style profile, but there might be a plugin for it :P
