### ISSUE TITLE
Manual peat bog doesn't replace bog earth

### ISSUE THREAD

**Issue by mconwa01** [ForestryMC/ForestryMC#478]
A manual peat bog doesn't replace the mature bog earth it harvests with new bog earth.

If the gaps that it leaves are then filled with dirt by the player, the dirt is then replaced with bog earth--perhaps a relic of the old behavior that left dirt behind when harvesting peat.

Version 3.3.0.6

**Comment by mezz** [comment]
Thanks for the report!
Can you try on the latest unstable version? There have been come changes to the farm since 3.3.0.

**Comment by mconwa01** [comment]
Thanks for responding!
Same behavior in both 3.4.0.7 and 3.3.0.452-unstable.

**Comment by mezz** [comment]
I put it back the way it was before. 
Now it works fine, fixed in the latest unstable!
