### ISSUE TITLE
Jenkins Site is down

### ISSUE THREAD

**Issue by Dream-Master** [ForestryMC/ForestryMC#482]
Jenkins Site is down. Cant download any version.

**Comment by Chocohead** [comment]
Forestry is hosted on Player's Jenkins, and IC2's is down as well.

**Comment by Parker8283** [comment]
I assume @sfPlayer1 already knows and is working on it.

**Comment by liach** [comment]
Though its player's fault, we just need to fork and use
gradlew setupCIWorkspace build
.

**Comment by Parker8283** [comment]
You can build without forking.

Also, it's up again.
