### ISSUE TITLE
Can't play selected world or create new world after updating

### ISSUE THREAD

**Issue by Staegrin** [ForestryMC/ForestryMC#494]
After updating to forestry_1.7.10-3.4.0.7 I can't play selected world or create new world. 

fml log:
https://gist.github.com/Staegrin/8dd53c22ef2e6cc85e1a

console log:
https://gist.github.com/Staegrin/911419c0290fb05a54ff

Clicking either "play selected world" or "create new world" simply send you back to the title screen.
No individual crash log is generated. Going back to version forestry_1.7.10-3.3.0.6 solves the problem somehow.

Will do further testing.

**Comment by laz2727** [comment]
Symptoms look like basic server startup lag Forge has as a tradition for
first updated versions. Have you tried waiting?

**Comment by Staegrin** [comment]
Waiting? 
Clicking either "play selected world" or "create new world" simply send you back to the title screen.

No matter how many times you click it always goes back instantly to the title screen without any message like loading the world or anything else.

On what should I be waiting?

I'm using version forge-1.7.10-10.13.2.1291-universal of forge if this helps with your answer. 
(Not sure if clear but I'm actually curious and I don't mean to sound angry/insulting)

**Comment by Parker8283** [comment]
Try with just Forestry installed.

**Comment by Staegrin** [comment]
Doing so currently. Works with thermal forestry on its own. Now I'm ading all the other mods to it one by one to see where the conflict lies.

**Comment by Parker8283** [comment]
Well then this issue is closed then. Report it to the other mod's author when you find out,
