### ISSUE TITLE
Crash Bee pollinate

### ISSUE THREAD

**Issue by Dream-Master** [ForestryMC/ForestryMC#499]
I get two Server crashes.

https://gist.github.com/Dream-Master/b5bf6784fd32b0442cf3#file-gistfile1-txt

https://gist.github.com/Dream-Master/94cc7bc0af0c60dbc314#file-gistfile1-txt

**Comment by mezz** [comment]
Thanks for the report!
Looks like I really messed up pollination for other mods. Fixed in the latest unstable!
