### ISSUE TITLE
Ghost Items

### ISSUE THREAD

**Issue by Wolfseverest93** [ForestryMC/ForestryMC#500]
As the title implies, I've encountered "ghost items" in other words: items that look like they are there, to both the player and the game, affecting the game, but when you go to retrieve them its as if they never existed to begin with. However, this majorly affects gameplay in that it renders the automatic farms from bees to the multiblock structure: USELESS. You'll find yourself constantly having to go double click these fake items out of the retrieval inventory of your machines constantly in order to make any use of them, and that ruins their purpose...

**Comment by mezz** [comment]
Thanks for the report!
Can you describe how you get this problem? 
Does it only affect multiblocks?

**Comment by Wolfseverest93** [comment]
so far it has affected the multiblock farm, and apiaries, and only happens when I have a buildcraft pipe attached to them to put items such as dirt or fertilizer in. When pulling items out however there hasn't been any problem. For now I've re-setup my farms to have manual input since the only other pipes I've found available are extra utilities but those won't connect to any of the blocks in forestry.

**Comment by mezz** [comment]
Which version of Forestry are you using?

**Comment by Wolfseverest93** [comment]
With apiaries it makes the honeycomb that gets pulled out glitch into a ghost item that takes up every open slot in the inventory of the block, making it so my automation can't replace the dead bees, similar with multiblock farms, whatever it picks up first takes up any empty slots as a ghost item preventing further cultivation from entering the inventory, as well as replacement items. I'm using the latest stable build to my knowledge, 3.2.0.5

**Comment by mezz** [comment]
Forestry is up to 3.4.0, good day sir!
http://www.curse.com/mc-mods/minecraft/forestry
 (please let me know if that fixes it. It should :bee: )

**Comment by Wolfseverest93** [comment]
alright, updating away. sad the autoupdate function of the mod didn't alert me XD i'll run some tests and make sure and will reply right away if it wasn't fixed

**Comment by mezz** [comment]
Alright, I'll leave this issue open until you report back.

**Comment by CovertJaguar** [comment]
Ghost items typically only exist on the client, not the server.

**Comment by Wolfseverest93** [comment]
it still has the issue when using buildcraft pipes to insert so i came to a compromise and decided to make the ender io conduits for use for the farm blocks. starting to look like a buildcraft problem so i'll go notify them in case it is. i know im using the latest of theirs because i updated it yesterday.

**Comment by mezz** [comment]
If Ender IO works fine, it sounds like a BC problem.
Here's their issue tracker, please make sure to link back to this issue.
https://github.com/BuildCraft/BuildCraft/issues
Thanks!
