### ISSUE TITLE
Mulitfarm gui blanking out on ErrorState

### ISSUE THREAD

**Issue by Nirek-K** [ForestryMC/ForestryMC#502]
The Multifarm gui appears to blank out clientside when changing from ErrorState OK from doing work, to any of the setErrorStates i.e. in a low power situation where power is provided intermittently and work is not constant. Low Farmland can also cause this when farm base is not complete.

**Comment by mezz** [comment]
Thanks for the report!
Should be fixed in the latest unstable build. Let me know if you see anything wrong.
