### ISSUE TITLE
BC pipes don't connect to Apiary

### ISSUE THREAD

**Issue by Marius8** [ForestryMC/ForestryMC#503]
I am using Foresty_dev build 459 and Buildcraft 6.3.6 (as well as some other mods).
I encountered this issue, while trying to set up an automatism for the Apiary.
On the Alveary the BC pipes connect normal.

Edit: forge build 10.13.2.1277

**Comment by mezz** [comment]
Thanks for the report!
Works fine for me with BC 6.3.5. Are you sure you're not trying to connect to a Bee House instead of an Apiary?

**Comment by Marius8** [comment]
No, i am trying to connect an Apiary, (I have a Bee House something around 10 blocks away).
I fell back to BC 6.3.4, and I do encounter the same problem (don't have 6.3.5 and it's not on BC website as previous version dl)

**Comment by marcin212** [comment]
I have BC 6.3.6 and forestry_1.7.10-3.5.0.458-unstable. 
Screen from server:
https://dl.dropboxusercontent.com/u/25172450/bugs/forestry/4ba1e24ada7c34142ece36e1ba130db5.png

**Comment by Marius8** [comment]
got it working, thanks!
looks like it was a problem with upgrading from the latest stable to the unstable build. (BC whole time 6.3.X)
because the ONLY thing I didn't try before, worked... breaking and replacing the Apiary......
