### ISSUE TITLE
Make NaturalistEye pretty

### ISSUE THREAD

**Issue by mezz** [ForestryMC/ForestryMC#504]
Grey leaves are ugly, pollinated leaves should be nice to look at.

**Comment by VileTouch** [comment]
you mean the glasses? if that's the intended look, your best bet would be a double sized texture. there's already one made in faithful 32x32

unless you want to radically change the look of it?

**Comment by mezz** [comment]
![2015-08-01_01 24 28](https://cloud.githubusercontent.com/assets/916092/9021229/16b6e010-37ec-11e5-8e53-b5b2390bb0c0.png)

The view with the spectacles is more subtle now, but still easy to tell. Every tree already had an unused secondary color for this purpose, so I'm using those.

If you find any pollinated leaves are too hard to see, reply here or make an issue and I can tweak the color.
