### ISSUE TITLE
Improve log textures to tile more smoothly

### ISSUE THREAD

**Issue by mezz** [ForestryMC/ForestryMC#505]
![2015-02-08_00 43 06](https://cloud.githubusercontent.com/assets/916092/6095962/828f7774-af2b-11e4-9ace-f3bd19bb547b.png)

Some of the log textures look bad for trees with wide trunks.
In particular Wenge, Baobab, and Mohogany have strong vertical stripes. There are others too though.

**Comment by mezz** [comment]
@xupaosso could you take this on? Your new log textures tile very well.

**Comment by xupaosso** [comment]
Sure! I can take care of this.

**Comment by mezz** [comment]
![2015-02-20_23 36 30](https://cloud.githubusercontent.com/assets/916092/6313326/58492d92-b959-11e4-9097-a09b4dcdd2b7.png)
![2015-02-20_23 34 49](https://cloud.githubusercontent.com/assets/916092/6313327/5a0af5e8-b959-11e4-9312-f8bf70600dab.png)

Before and after.
Looks great, thanks!
