### ISSUE TITLE
[MINOR] Config descriptions incomplete

### ISSUE THREAD

**Issue by ZeekDaGeek** [ForestryMC/ForestryMC#506]
In Forestry 3.4.0.7 the config desciptions seem to have been cut short:

Parts with ** are missing.

= set to false if harvesters should output all harvested products regardless of side a pipe is att**ached to**
harvesters.sidesensitive=true
...
= set to false if farms should output all harvested products regardless of side a pipe is att**ached to**
planters.sidesensitive=true
...
= set to false to disable apple pickup by appropriate ha**rvesters**
tweaks.apple.pickup.enabled=true
...
= set to true to disable some nagging and warnings (e.g. Gr**egTech).**
tweaks.nags.disabled=false

**Comment by mezz** [comment]
Thanks for the report!
I removed those config options in 3.4.0 since they were for non-existent old stuff. 
I'm not sure why they ended up cut off like that. You can safely remove them.

**Comment by Nentify** [comment]
Mine were doing this too. https://github.com/Tekkify/Tekkify/commit/a7a3162a259548cf3761c979de065c00866af3bf
