### ISSUE TITLE
Implement Config GUI

### ISSUE THREAD

**Issue by Adaptivity** [ForestryMC/ForestryMC#507]
Since a lot of mods already doing it. Also, it should be localizable. Example: https://github.com/MinecraftForge/MinecraftForge/commit/04c2ed554d9f9e22a6fd9a37a150cd48c7292d24

**Comment by mezz** [comment]
Is this actually useful? If this is what I think it is, I added it for JEI but you can only access it before you load a world.
Making things localizable is always good though.

**Comment by Adaptivity** [comment]
Yes, you think correctly. You can do it for 1.8 if it take too much time.

**Comment by Lunatrius** [comment]
Factorization adds a `/f mods` command that opens that GUI, but there's also InGame Mod Configs, which overrides the current FML "test 1/2" GUI.

**Comment by mezz** [comment]
Migrate Configs files to Forge Configuration:
- [x] apiculture
- [X] backpacks
- [x] common
- [x] debug
- [x] fluids
- [x] game modes
- [x] lepidopterology
- [X] modules

Next Steps:
- [x] Add config menu
- [x] Add localization

**Comment by mezz** [comment]
Backpack config migrated: https://github.com/ForestryMC/ForestryMC/issues/694

**Comment by mezz** [comment]
Ok added everything. New configs, localization, and in-game gui.
The gui is not great. I'm going to try some of the config gui mods and see what else needs to be done.

**Comment by mezz** [comment]
Seems to work fine, if someone needs more they can create a new issue.
