### ISSUE TITLE
No farmland

### ISSUE THREAD

**Issue by marcin212** [ForestryMC/ForestryMC#510]
My farms don't work after update to last unstable. I have error in farm GUI: No Farmland.
-forestry_1.7.10-3.5.0.464-unstable
-forge-10.13.2.1291

**Comment by Jhary** [comment]
Same issue here when using the current forestry dev branch. Bricks are layed out properly, GUI says "No farm land". Switch to stable forestry in same instance. Loading the world and everything works.

**Comment by mezz** [comment]
What kinds of farms? I'll take a look.

**Comment by marcin212** [comment]
stone brick, arboretum(without circuit)

**Comment by Jhary** [comment]
dito, stonebrick - arboretum (but with chipset)

**Comment by mezz** [comment]
Should be fixed, [please try the latest unstable 466](http://jenkins.ic2.player.to/job/Forestry_Dev/) and report back.
If it's still not working, please post a screenshot showing your farmland and farm multiblock.
Thanks!

**Comment by mezz** [comment]
Nope, looks like it's not fixed yet

**Comment by mezz** [comment]
Should be fixed, [please try the latest unstable 467](http://jenkins.ic2.player.to/job/Forestry_Dev/) and report back.
If it's still not working, please post a screenshot showing your farmland and farm multiblock.
Thanks!

**Comment by marcin212** [comment]
It works fine for me.
