### ISSUE TITLE
Move to 1.8

### ISSUE THREAD

**Issue by mezz** [ForestryMC/ForestryMC#512]
Notes from Parker8283:
- [ ] Get it working
  - [X] cpw.mods -> net.minecraftforge
  - [X] BlockPos
  - [x] EnumFacing
  - [ ] Fix Rendering
    - [ ] JSON All the blocks
    - [ ] Replace IIcon with TextureAtlasSprite
    - [ ] Anything with IIconRegister can probably be removed
  - [ ] Fix remaining compile errors
- [ ] Cleanup
  - [x] Remove deprecated things from the Forestry API
  - [ ] Probably replace IVect with BlockPos

**Comment by mezz** [comment]
JSON is completely awful for all the stairs and fences.
There must be a saner solution. @Parker8283 what are your thoughts?

**Comment by Parker8283** [comment]
It's not advised to work around it. Believe me, there are ways, but the whole point is to allow resource pack makers to change the model. The inheritance system in the block and item models make it a little easier. Also, (you saw considering you starred it) I'm making a program that makes making the JSONs easier.

So, yes, there are ways to avoid the JSON system, but none are advised. This will be like ripping off a band-aid. This will be painful, but it will be done at some point. As long as the JSONs were written right, you will probably never have to touch them again.

**Comment by Nedelosk** [comment]
https://github.com/ForestryMC/ForestryMC/pull/812
