### ISSUE TITLE
Bees not accepting their flowers

### ISSUE THREAD

**Issue by mezz** [ForestryMC/ForestryMC#513]
thr33p10 commented:

>A member on my server noticed that some bee flower requirements changed when we moved over to the dev 464 build from the previous stable 3.4.0 (I think). I hate making a new issue just to point this out, as I'm thinking the flower changes for the bees might be intentional. Any way of knowing what the new requirements might be (bee)?

>A couple example bees that no longer accept their previous "flowers" are:
Embittered bees (nether wart)
Oblivion bees (dragon egg)
Ender bees (dragon egg)

>The above are all using their natural traits (no genetic modifications).

>Thanks for any help on the question.

**Comment by Amelia-** [comment]
I've noticed problems with this too.
I cannot get any of the bees to work with their flowers when those are in a flower pot (flowers, ferns and cactii, have not tried mushrooms yet).
Bees that need nether wart only seem to work when the nether wart in it's first growth stage or something.
Bees with the jungle pollination trait don't seem to be able to use vines anymore, just ferns.
I noticed some problems with cactii pollination as well.

I'll add more information if I run into any.

**Comment by mezz** [comment]
Ender bees are working fine, and Oblivion and Embittered bees are not from Forestry.

I'll take a look at the issues with other flowers. I don't think the flower pots have worked for a long while, but I think I can fix those in this issue too.

**Comment by mezz** [comment]
Everything should be fixed in the [latest unstable version](http://jenkins.ic2.player.to/job/Forestry_Dev/) now. 
Please try it out and report back, thanks!

**Comment by Amelia-** [comment]
It all seems to work well after the change you did.
