### ISSUE TITLE
[Bug] Multifarms Sizing Issue

### ISSUE THREAD

**Issue by Kris1432** [ForestryMC/ForestryMC#514]
I currently have the smallest Multifarm structure (3x3x4) and its planting for the max size Multifarm.

**Comment by SandGrainOne** [comment]
Do you know of the Multifarm resizing change? What you see might be on purpose.

**Comment by Kris1432** [comment]
I have always just followed the official wiki on this. what changed?

**Comment by Kris1432** [comment]
my reference: http://forestry.sengir.net/wiki.new/doku.php?id=farms:structure

**Comment by Jhary** [comment]
The wiki has to be updated regarding the farm sizes. The smallest farm is able to go out 9 blocks in every direction from the multiblock. That is 21x21 including the 3x3 multiblock.

**Comment by Kris1432** [comment]
ok, then this issue can be closed. thanks.

**Comment by Sandriell** [comment]
The formula for determining the size of the farms is " 2* (x * 3) + x ", where "x" is the width of your central structure- which in your case is 3.
