### ISSUE TITLE
Multifarm inventory full

### ISSUE THREAD

**Issue by NapB9** [ForestryMC/ForestryMC#516]
Hi,

I am using Forestry 3.3.0.6 on DireWolf20 1.7.10 - server.  On multiple farm types (I've tried Managed Farm & Managed Arboretum), I run into the same problem of the inventory filling up - despite there being a powered wooden BC pipe automatically extracting the items.  Although it appears in my screenshot that Oak wood is filling up the inventory, in fact it is a glitch.  If I take the wood out & put it in my inventory, it eventually disappears like it never existed.

The farms will work fine for a couple of hours, sending out items normally - but then this glitch happens, preventing any items from being extracted & suspending any farm activity due to the "full" inventory.  Any thoughts?

![multifarm glitch 1](https://cloud.githubusercontent.com/assets/11050325/6239097/8a5f7878-b6ce-11e4-9fb1-5f95025f8d60.png)

**Comment by mezz** [comment]
Thanks for the report!
I've made some progress on the farm recently, can you see if the [latest unstable version](http://jenkins.ic2.player.to/job/Forestry_Dev/) fixes the problem for you?

**Comment by NapB9** [comment]
Thanks for the quick reply & suggestion.  I will load it onto my server tonight (Feb 18th) & report back most likely tomorrow (Feb 19th) to let you know.  Great mod by the way, one of my favorites!

**Comment by NapB9** [comment]
It looks like the latest version fixed the bug with the inventory filling up, thanks!  There is a separate issue with the placement of dirt blocks on the crop farm; I'll open a separate ticket for that if you're not aware of it when I'm able to take some screenshots.  Thanks again.
