### ISSUE TITLE
NPE when disabling the storage module

### ISSUE THREAD

**Issue by doushio9967** [ForestryMC/ForestryMC#517]
Hello.
As per the title, disabling storage in modules.cfg nets me this crash on startup:
http://pastebin.com/uFSWnvq1

Forestry b469.

And on the topic on forestry storage; It would be nice if the setting for crates and backpacks were separate, as some people might only wanna disable one and not the other (I was mainly looking to disable the backpacks when I ran into this bug).

Thanks for your time.

**Comment by mezz** [comment]
Thanks for the report!
Fixed in the latest unstable build.

Can I ask why you are disabling the backpack? I can add a config but I want to understand the reason too, since I don't want to add a lot of very uncommon options. Thanks

**Comment by doushio9967** [comment]
F..fast! Thank you very much!

I am doing decently hardcore playthrough with betterstorage backpacks as the only acceptable carriable extra storage, since most other mods' backpacks and bags act more like 'magic' storage that you can fill your inventory with it (and sometime stuff in other backpacks for essentially infinite storage).
They were basically not fitting in with the playstyle I was going for, so I was looking to disable them. Crates, on the other hand, require machines and permanent setup, so they were deemed ok.

But there's no pressure, in the worst case I'll go the minetweaker route.

**Comment by CovertJaguar** [comment]
Hmm...I wonder if Railcraft will explode if the Storage module is disabled...

**Comment by doushio9967** [comment]
From my limited testing I saw no problems. Backpacks were obviously gone, while the creosote related carpenter recipes were still there, atleast according to NEI.

But I did uncover more forestry bugs related to storage while checking railcraft, so I'll go post a new issue.
