### ISSUE TITLE
Trade Stations crashes client.

### ISSUE THREAD

**Issue by marcin212** [ForestryMC/ForestryMC#518]
The problem occurs most probably after a server restart if there are unclaimed Trade Stations (placed, but never opened). The client crashes when they are right-clicked.
log: https://gist.github.com/serekk11/9e75f4ac7ea3bd892096
forestry_1.7.10-3.5.0.469-unstable

**Comment by mezz** [comment]
Thanks for the report! Fixed in the latest unstable build.
