### ISSUE TITLE
Visual state of the analyzer is not updated when a bee enters or leaves the analyzing state

### ISSUE THREAD

**Issue by Ioandar** [ForestryMC/ForestryMC#519]
The Forestry Analyzer had that cool feature to show the bee that is currently analyzed in the Model, so you can see from outside which bee is currently being worked on. 

At the moment the analyzer Model only updates when you open the gui.

When you pipe Bees in and out the Model does not show the currently analyzed bee anymore.

forestry_1.7.10-3.5.0.471-unstable

**Comment by mezz** [comment]
Thanks for the report!
Good catch, this has bugged me too but I forgot to add it to the issue tracker.

**Comment by mezz** [comment]
Fixed in [the latest unstable build](http://jenkins.ic2.player.to/job/Forestry_Dev/). Check it out! :)

**Comment by Ioandar** [comment]
@mezz 

Yay, the cool feature is working again! I totally forgot to thank you for fixing that and all the other work you do. TYVM!
