### ISSUE TITLE
Please move recipe registration out of PostInit

### ISSUE THREAD

**Issue by purpleposeidon** [ForestryMC/ForestryMC#520]
Registering the bulk of your recipes in PostInit is really obnoxious for mods that inspect recipes, which are quite a few. Forestry adds a nice variety of woods, and barrels can't be made for them if the recipes are registered too late.

**Comment by mezz** [comment]
Thanks for the suggestion!
However I'm not sure I understand your needs exactly. 
The items and blocks for woods are registered in PreInit, so you can use them in your recipes any time after. They are also registered in the ore dictionary so that you can easily access them and know how they are used.
What do you need the recipe for?
Please let me know, thanks!

**Comment by CovertJaguar** [comment]
Sounds more like a Ore Dictionary registration timing issue than anything to do with when Forestry registers its recipes.

**Comment by mezz** [comment]
@purpleposeidon ?

**Comment by purpleposeidon** [comment]
Factorization creates the barrel recipes, in PostInit, by iterating over the logs in the OreDictionary, and testing the usual crafting recipes to discover their associated slabs. PluginArboriculture.registerRecipes is called by PluginManager in post-init, so the recipes are not guaranteed to exist at that point.

Best practice is to initialize everything that doesn't depend on other mods in PreInit.

**Comment by Vexatos** [comment]
@purpleposeidon how about an "after:Forestry" in your `@Mod` dependencies? Would make FZ load after Forestry and would probably fix this issue.

**Comment by Kubuxu** [comment]
@Vexatos this would require FZ to load after every mod adding wood. Ore Dictionary should be fully populated when entering postInit otherwise it is almost useless for other mods.

**Comment by Vexatos** [comment]
There still is LoadComplete, but I doubt anyone would ever want to use that :wink:

**Comment by mezz** [comment]
I think the request makes sense. I'll move things around soon, but it could take a while to test it properly before I submit the change.

**Comment by mezz** [comment]
Ok, implemented in [the latest unstable build](http://jenkins.ic2.player.to/job/Forestry_Dev/).
I checked carefully, hopefully there are no issues.
