### ISSUE TITLE
Endless Apatite vein generation

### ISSUE THREAD

**Issue by ultrasn0w** [ForestryMC/ForestryMC#521]
I simply tried to create a new world and after waiting more then 10 Minutes on the "Downloading Terrain" screen I checked the log and saw this:
http://pastebin.com/vTsF31F2
I have not modified any Forestry config or installed new mods till the last time it worked, I am truly confused.
Also happens with latest unstable.
If this is not a bug related to Forestry I am lost, this is the last possible cause....

**Comment by Parker8283** [comment]
In what ways did you modify the world before generating? (World type? (Superflat, amplified, etc)) Have you tried creating another world and seeing if the issue persists? I agree, this is weird, though I have not run into this issue in testing.

**Comment by ultrasn0w** [comment]
After doing the last thing possible I deleted all configs and tried again.
It worked, so I resored all my settings I had before and found out it was because I set Render Distance to Extreme+ in OptiFine.... Sorry for causing confusion/trouble.. this Issue can be deleted.

**Comment by Parker8283** [comment]
You can't delete issues on GitHub.
