### ISSUE TITLE
Direct redstone signals will disable Forestry's powered machines does not work properly

### ISSUE THREAD

**Issue by WinSide** [ForestryMC/ForestryMC#522]
So works
![2015-02-20_10 15 33](https://cloud.githubusercontent.com/assets/7656576/6280521/9a78d91c-b8e9-11e4-8623-476d0f3d9fc8.png)
but it does not work, even if the lever next to the block
![2015-02-20_10 15 51](https://cloud.githubusercontent.com/assets/7656576/6280531/cf45d172-b8e9-11e4-898a-76b9f97f6573.png)

**Comment by mezz** [comment]
Thanks for the report!
The redstone signal only works directly so that this change doesn't accidentally break existing builds. 
I can change it to work with any redstone signal for the 1.8 version, since there will not be perfect backward compatibility.

**Comment by asiekierka** [comment]
"The 1.8 version."

I gave up on not breaking things as I know 1.8 is very far away - I'm just keeping all non-urgent breaking changes for a major release, like 7.0.0.

**Comment by mezz** [comment]
Agreed, it may be the next major version, we'll see how things go.

**Comment by WinSide** [comment]
@mezz, what the problem is to add?

**Comment by mezz** [comment]
Now that there is an error tab that says when the machine is disabled by redstone, this is ready to add.

**Comment by mezz** [comment]
Added in the [latest unstable build](http://jenkins.ic2.player.to/job/Forestry_Dev/).
