### ISSUE TITLE
Add config for Received letters HUD Placement

### ISSUE THREAD

**Issue by marcin212** [ForestryMC/ForestryMC#524]
Would it be possible to add a config option for choosing where to display the received letters information (in which corner of the screen, for example).

**Comment by mezz** [comment]
Note to self: should be able to add this in `TickHandlerMailClient`

**Comment by mezz** [comment]
Added in the latest unstable build:
![2015-11-20_15 25 54](https://cloud.githubusercontent.com/assets/916092/11314594/d682e234-8f9b-11e5-8fdf-68fc2b9946fb.png)
