### ISSUE TITLE
Electrical Engine "output" Much lower than Production when powering lasers, causes stutter.

### ISSUE THREAD

**Issue by GotchaGimmeThanks** [ForestryMC/ForestryMC#525]
I think that there may be a bug with the electrical engine.

When trying to operate a laser, it takes two electrical engines to do so, even if the single electrical engine has circuit boards greatly boosting it's power, that power just gets stored. However two weaker electrical engines producing far less RF can power it smoothly (and a combustion engine is working smoothly in my game currently, at far less RF.)

I'm having this problem both with and without the use of Kinesis pipes.

**Comment by mezz** [comment]
Thanks for the report!
Can you try with a mod other than Buildcraft? For instance, electrical engine -> energy storage from another mod.

It's my suspicion that the bug is with Buildcraft, since there have been a few in the past.
Thank you!

**Comment by asiekierka** [comment]
@GotchaGimmeThanks - are you using 6.4.0+? If not, there are many energy bugs in previous versions and thus the report should be closed.

Also ,remember each laser has a power limit of 40 RF/t.

**Comment by mezz** [comment]
Forestry engines output in big pulses, two per stroke animation. This sometimes exposes problems in mods that expect a constant trickle. Pipes should work to buffer the energy though.

**Comment by asiekierka** [comment]
Lasers also buffer the energy.

**Comment by GotchaGimmeThanks** [comment]
I can tell you that the problem stopped when i switched to those flux
cables from thermal expansion, so yes, seems to be a problem related to
build craft pipes

**Comment by mezz** [comment]
@asiekierka the forestry engines average out to a low RF/t, but each pulse is 10 times their RF/t rating (since they output once every 10 ticks).

**Comment by asiekierka** [comment]
@GotchaGimmeThanks - use BC 6.4.0+

**Comment by Requia** [comment]
This issue is still present in buildcraft 6.4.3

**Comment by Requia** [comment]
Problem is unique to buildcraft machines though, possibly still not forestry.
