### ISSUE TITLE
Carpenter NPE when storage is disabled

### ISSUE THREAD

**Issue by doushio9967** [ForestryMC/ForestryMC#526]
Hello again!

Related to #517 
The 4 wood -> crates recipe still exist in the carpenter when you disable the storage module, albeit with an empty/blank output according to the forestry handler in NEI.
Putting in wood/water/energy in and trying to craft them gets you this NPE:
http://pastebin.com/uCUVgRyf
 
Even if you enable the storage module again it'll crash with an identical stacktrace, until you mcedit out the machine.

Thanks.

**Comment by mezz** [comment]
Thanks for the report!
Fixed in the latest unstable build.
