### ISSUE TITLE
Incorrect hardness for wooden blocks

### ISSUE THREAD

**Issue by Adaptivity** [ForestryMC/ForestryMC#527]
Not sure if it intentional or not but... "Bee House", "Apiary" and "Apiarist's Chest" have stone(?) hardness. So, they requires pickaxe to break them. Also, this tooltip http://i.imgur.com/4iRDTj1.jpg hardcoded. Not sure if it comes from Forestry or Waila.

**Comment by mezz** [comment]
Thanks for the report!
I'll fix that, it makes sense.
The Waila error is probably not Forestry, I don't know what it's about.
