### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Dream-Master** [ForestryMC/ForestryMC#528]
Server Crash four times this day.

https://gist.github.com/Dream-Master/a0044a6145d4233cd684#file-gistfile1-txt

**Comment by mezz** [comment]
Thanks for the report!
Should be fixed in the latest unstable.

Somehow you have an ItemStack that has a null item in the Alveary. 
Please let me know what kind of bees and products you have in the Alveary at (1424, 61, -2503).

**Comment by Dream-Master** [comment]
On those coords - Invincible bees, but as far as i remeber the error was also on the space station, those were frugal and refined. Could be something with extra bees?

**Comment by mezz** [comment]
I think it's worth reporting to Binnie's tracker, you can link back here.
There will be no more crashes from it interacting with Forestry, but I didn't do anything to remove the broken ItemStacks. it's possible that they could fill up the Alveary, or cause a crash when you pick them up or use them somehow.

**Comment by Dream-Master** [comment]
Ok  tanks I will test it with the latest unstable build.
