### ISSUE TITLE
Multifarm speed upgrade request

### ISSUE THREAD

**Issue by estebes** [ForestryMC/ForestryMC#529]
I'm loving using multifarms but i've been facing a problem. Basically a maxed size multifarm or even just a large one struggles a lot to deal with "faster maturation" trees. If somekind of block for the multifarm could be added that used more energy fertilizer and water but would speed the farm that would be amazing.

**Comment by CovertJaguar** [comment]
Faster farm == more lag?

**Comment by kremsy** [comment]
Isnt the farm already way too fast anyways?

**Comment by estebes** [comment]
Not fast enough to deal with op trees :D

**Comment by mezz** [comment]
Should be fixed by the giant farm refactor. Just add another powered gearbox and it should run faster. You can keep adding more if needed.
https://github.com/ForestryMC/ForestryMC/commit/aa47599278bd55eef126d398737501a71f984e39
