### ISSUE TITLE
Unable to add Additional Flower Blocks via Apiculture.conf

### ISSUE THREAD

**Issue by Bunsan** [ForestryMC/ForestryMC#531]
I'm trying to integrate Terrafirmacraft with forestry and wish to register their flowers as valid for apiaries. However this is not functioning. This is what I've entered to attempt to figure out where issue is.

`beekeeping.flowers.custom=terrafirmacraft:Flowers:*;terrafirmacraft:Flowers2;474:*;475`

This results in the console print out of:
`[Client thread/WARN] [Forestry]: Failed to add flower of (terrafirmacraft:Flowers:*) to vanilla flower provider since it isnt formatted properly.
[Client thread/WARN] [Forestry]: Failed to add flower of (terrafirmacraft:Flowers2) to vanilla flower provider since it couldnt be found.
[Client thread/WARN] [Forestry]: Failed to add flower of (474:*) to vanilla flower provider since it couldnt be found.
 [Client thread/WARN] [Forestry]: Failed to add flower of (475) to vanilla flower provider since it couldnt be found.`

I then tested with the Backpack.conf and was able to success fully add both: terrafirmacraft:Flowers:* and terrafirmacraft:Flowers2 to the miners backpack. So something is specifically wrong with the ability to add additional flower blocks as it can't find the specified block despite correct syntax and also that it is unable to accept ModID:blockName:meta.

I've tested this in forestry_1.7.10-3.5.0.473-unstable, forestry_1.7.10-3.4.0.7 and forestry_1.7.10-3.3.0.6.
I'm running forge build 1291, TFC 0.79.15.538.

**Comment by mezz** [comment]
Thanks for the report!
Sorry for the headache, I don't think this was ever updated for 1.7.10 like the backpack was. I'll fix it up.

**Comment by mezz** [comment]
Should be fixed in the latest unstable version.
I combined the string parsing code for backpacks and flowers so they work the same now.
Please let me know if you find any other issues!

**Comment by Bunsan** [comment]
Thank you for fast fix. I is working as expected now.
