### ISSUE TITLE
Leaves name with waila

### ISSUE THREAD

**Issue by quienti** [ForestryMC/ForestryMC#532]
I don't know if it's really Forestry, but all leaves have no name with waila :/
![2015-02-27_14 04 28](https://cloud.githubusercontent.com/assets/7326954/6418681/72142eee-beb7-11e4-83dc-ccb22992cfc7.png)

Forestry : 3.5.0.473
Waila : 1.5.9

**Comment by mezz** [comment]
Thanks for the report!

Looks like it's WAILA's fault, but we can work around it.
https://bitbucket.org/ProfMobius/waila/issue/153/158-mc-1710-doesnt-respect-new

Fixed in the latest unstable build.
