### ISSUE TITLE
Backpack and full inventory lag out the server

### ISSUE THREAD

**Issue by christianvdstap** [ForestryMC/ForestryMC#533]
If a player has a full backpack and stands on an item it will cause the server to lag out and potentially crash if the player stands to long on the item.

The nps file is attached here:
http://forum.industrial-craft.net/index.php?page=Thread&postID=181639#post181639

Installed mods:
forge-1.7.10-10.13.2.1263-universal.jar
AdminCommandsToolbox-0.0.2a_1.7.10.jar
AppleCore-mc1.7.10-1.1.0+89.1415c.jar                                                               
BiblioCraft[v1.9.2][MC1.7.10].jar                                       
BiblioWoods[Forestry][v1.7].jar                 
Carpenter's Blocks v3.3.5 - MC 1.7.10.jar
Chisel2_DEV-2.3.5.005a8c5.jar           
CodeChickenCore-1.7.10-1.0.4.35-universal.jar                                    
ExtraCells-1.7.10-2.2.53b82.jar              
GTExtras-0.2.1.jar                                            
MineTweaker3-1.7.10-3.0.9C.jar                                 
MobiusCore-1.2.3_1.7.10.jar                           
Morpheus-1.7.10-1.5.26.jar            
NotEnoughItems-1.7.10-1.0.4.83-universal.jar                         
Railcraft_1.7.10-9.5.0.0.jar  
Thaumcraft-1.7.10-4.2.3.4.jar
UndergroundBiomesConstructs-1.7.2-0.7.jar
appliedenergistics2-rv2-beta-8.jar                                 
eirairc-mc1.7.10-v1.7.56.jar           
fastcraft-1.19.jar  
forestry_1.7.10-3.5.0.473-unstable.jar
gregtech_1.7.10-6.00.09.jar                                                                                                                  
ihl-tools_n_machines-0.528-1.7.10.jar
immibis-core-59.0.7.jar
industrialcraft-2-2.2.684-experimental.jar
redlogic-59.1.9.jar
sampler-1.17.jar

**Comment by Nexey** [comment]
I can help reproducing the lag. Actually I'm the one who found that bug, so if you need help reproducing it, you can just invite me on the server.
Also the item doesn't have to target the backpack. I can stand on 50 stacks of seeds and have one miner's backpack to reproduce this lag. I can also stand on 50 rings from Thaumcraft and have one digger's backpack to reprocude this lag again. The items / blocks you're trying to pick up doesn't need to match the backpack.
Please note that this bug haven't been tested with RC's backpacks.

**Comment by mezz** [comment]
Thanks for the report!
Should be fixed in the latest unstable. 
I tested it carefully, but I'd like to know I didn't miss something. Please let me know if it fixed the problem on your server.

**Comment by christianvdstap** [comment]
Hi mezz,

We just tested it on the server and the it seems to be fixed. Thanks!

**Comment by mezz** [comment]
Good to hear, thanks for confirming!
