### ISSUE TITLE
"Ghost" leaf blocks in multifarm

### ISSUE THREAD

**Issue by j4bb3rw0xx0r** [ForestryMC/ForestryMC#534]
Version 1.7.10-3.3.06 (Direwolf20 Modpack), SMP server
Symptom: Max size multifarm, no circuit. Previously planted vanilla oak saplings, switched to bred Blue Mahoe. Noticed trees growing leaves in odd patterns with lots of gaps. The empty spaces register in Waila as Apple Oak Leaves and behave as if there is a leaf block present (obstructing movement, dropping apples/saplings, causing butterflies to acquire pollen). The blocks respawned 10-20 minutes after being broken, I'm assuming they're left behind after the advanced trees are harvested.

Built a new farm with the same advanced saplings in a different location, to ensure that the previous presence of vanilla saplings wasn't a factor. Same behavior occurred in the new farm after a few iterations of tree growth/harvesting.

**Comment by mezz** [comment]
Thanks for the report!
You should update Forge to 10.13.2.1291, it sounds like this bug: #431
Please let me know if you still have the problem with the latest Forge and I'll reopen this issue.
