### ISSUE TITLE
Multifarms outgrowing their maximum size

### ISSUE THREAD

**Issue by shanodin** [ForestryMC/ForestryMC#535]
Minecraft version 1.7.10
Forestry version 1.7.10-3.3.0.6
Forge version 7.10.85.1291

Having an issue where a multifarm will grow to the maximum size possible because my building was the same material as my farm (stone brick). However switching to smooth sandstone farm didn't resolve. Rebuilt building out of stone brick slabs has sorted out the problem where it would eat bits of my walls, but having a new problem where my two side by side farms (3x3 farm blocks, the smallest size) are conflicting and keep taking bites out of each other, even though they shouldn't be able to reach. Attached image shows the peat bog taking a bite out of the potato farm next to it, on blocks it shouldn't even be able to reach.

![2015-03-01_07 06 39](https://cloud.githubusercontent.com/assets/11253682/6429785/9e5b8940-bfe1-11e4-90ff-e5951c3e5e49.png)

**Comment by laz2727** [comment]
If farms are bigger than you think, you most likely think wrong.

2015-03-01 13:13 GMT+06:00 shanodin <notifications@github.com>:

**Comment by mezz** [comment]
Farms are much bigger now, their radius is 3 times the width of the farm multiblock.
See #329 and related.
The latest unstable version of Forestry will let you stop their spread by leaving a gap in the base or building a wall in between the farms.

**Comment by shanodin** [comment]
Fantastic,  thanks so much for the speedy response!
