### ISSUE TITLE
Flowertype Option in Add Additional Flower Config [Requested Feature]

### ISSUE THREAD

**Issue by Bunsan** [ForestryMC/ForestryMC#536]
I'd like to request, if it is possible, that the config for adding additional flowers be modified to allow the addition of more than just vanilla flower type. With the [API change to FlowerManager](https://github.com/ForestryMC/ForestryAPI/commit/84af8e56fa874fb0a0ed15d3b4ee10f92c7aa763) to have the various flower types (I'm not well versed in java so I may be reading this wrong) it would seem possible split the config up into different flowertypes, akin to how backpacks are split by type.

**Comment by mezz** [comment]
Thanks for the idea, it should be possible and sounds like a good enhancement.

**Comment by mezz** [comment]
This is implemented in the [latest unstable build](http://jenkins.ic2.player.to/job/Forestry_Dev/).
