### ISSUE TITLE
farmland spread over several layers

### ISSUE THREAD

**Issue by JoeD91** [ForestryMC/ForestryMC#543]
With the new size increase the farmland spread over several layers, including blocks that aren't connected to the farmbase

http://imgur.com/pu3R7Lm

http://i.imgur.com/OuwrTvr.png (there is even more farmland underground)

**Comment by mezz** [comment]
Thanks for the report!
Please try the latest unstable build. http://jenkins.ic2.player.to/job/Forestry_Dev/
Each side can be on its own level, but they should not spread to the wrong places anymore.

**Comment by JoeD91** [comment]
The version I used was 3.4.0.7 used in the FTB Infinity pack. I will definitly give the unstable build a try

**Comment by mezz** [comment]
There are some big farm fixes/changes in the works for 3.5. Haven't had enough time to declare it stable yet, but the problem you pointed out should be fixed.

**Comment by JoeD91** [comment]
just gave it a try, it is fixed which is wonderful. Thank you for your great work.

**Comment by mezz** [comment]
Good to hear, thanks for reporting back.
