### ISSUE TITLE
[Rubberized Tubes Question] shows up a GT Error because using IC2 rubber

### ISSUE THREAD

**Issue by Dream-Master** [ForestryMC/ForestryMC#544]
![image](https://cloud.githubusercontent.com/assets/2970688/6505179/a45380da-c33f-11e4-8ff1-f9252b47d3cf.png)

I make new recipes with Modtweaker 2 but this recipes i cant remove. I think Gt disabled rubber from IC2 and that's why shown this error. Is it possible to get Rubber Bars from Gt inside the Recipes when Gt is installed? What is different in this recipes to the other Tubes?

My Modtweaker code:
````````````````````````````````````````````````````````````````
// --- Rubberrised Electron Tubes
mods.forestry.ThermionicFabricator.removeCasts(<Forestry:thermionicTubes:8>);

// --- Rubberrised Electron Tubes
mods.forestry.ThermionicFabricator.addCast(<liquid:glass> * 1152, [
[null, <gregtech:gt.metaitem.02:22880>, null], 
[<gregtech:gt.metaitem.02:19305>, <gregtech:gt.metaitem.02:22880>, <gregtech:gt.metaitem.02:19305>], 
[<gregtech:gt.metaitem.01:26086>, <gregtech:gt.metaitem.01:17308>, <gregtech:gt.metaitem.01:26086>]], 
null, <Forestry:thermionicTubes:8>);
``````````````````````````````````````````````````````````````````````````````````

Other Tubes works fine with new recipes:

![image](https://cloud.githubusercontent.com/assets/2970688/6505280/a079aee8-c340-11e4-8855-a993dae4d0a0.png)

**Comment by mezz** [comment]
The code for the rubberized electron tube is here:
https://github.com/ForestryMC/ForestryMC/blob/dev/src/main/java/forestry/plugins/PluginIC2.java#L273-L278
It uses the oredict names for IC2's rubber. Gregtech may add or remove oredict names, I have no idea, so I wrote it to be pretty resilient to those kinds of changes.

Hope I could help, but I don't know how Modtweaker works. 
If you still don't know what to do, you should ask them and link back to here, I can help them out if they need more info.

**Comment by Dream-Master** [comment]
Thanks for you help. I will asking Greg too.

**Comment by leagris** [comment]
@mezz Please look at the issue because @gregoriust describe it as:
> A Recipe used an OreDict Item as Output directly, without copying it before!!!
> Said Item will be renamed to make the invalid Recipe visible.
> Please check all Recipes outputting this Item, and report the Recipes to their Owner.
> The Owner of the Recipe, NOT the Owner of the Item!!!
> And ONLY Recipes which are OUTPUTTING the Item, sorry but I don't want failed Bug Reports.

@Dream-Master As Item changed name tells you, look at log file

**Comment by GregoriusT** [comment]
Said Recipe is a CRAFTING Recipe, not a Machine Recipe, find the
Crafting Recipe outputting Rubber and the Mod adding it.

Also I do not remove OreDict Names, because that is impossible to do
without causing major Bugs.

2015-03-06 10:54 GMT, Léa Gris <notifications@github.com>:

**Comment by Dream-Master** [comment]
Ok thanks that everyBody now talking about this Error. But which mod cause this error? Maybe we'll find it.

**Comment by GregoriusT** [comment]
The thing is, whenever this Error occurs it renames the Item to make
it visible, and every OreDict based Recipe Handler can no longer
accept a regular un-renamed Item, what is causing Forestry to break.

If there were another way of making the Recipe properly visible I
would do it the other way.

But again, it is the fault of the Mod adding the invalid Crafting
Recipe, not my fault and probably also not Forestrys fault (since I
doubt Forestry adds that particular Crafting Recipe).

2015-03-06 11:14 GMT, Martin <notifications@github.com>:

**Comment by Dream-Master** [comment]
@GregoriusT
So it could be every Mod in my Pack causing this error or only Mods using rubber ? I only want to find out what Mod causing it and contact the Mod Author.
Thanks for your help.

**Comment by GregoriusT** [comment]
Go in NEI. Find the Crafting Recipe outputting renamed Rubber, find
the Mod adding the Crafting Recipe outputting renamed Rubber.

I thought the Log already stated exactly what I just explained to you.
Can't you read?

2015-03-06 11:56 GMT, Martin <notifications@github.com>:

**Comment by Dream-Master** [comment]
After long testin I think it have nothing to do with GT ERR 01. I make a pack only with forge 1263 ,nei, Gt 5.07.07,Ic2 2.2.2.687 forestry 3.5.0.484, minetweaker 3.09c and modtweaker 0.7.1b. The Gt Error not appear but i cant remove the recipes. So i asking the Modtweaker Author. Thanks for help and sorry for my annoying Questions.

**Comment by jaredlll08** [comment]
@mezz All I do is something along the lines of "recipes.remove(recipe)"

**Comment by Dream-Master** [comment]
My solution double remove and it works:
````````````````````````````````````````````````````````````````````````````````````````````````
// --- Rubberrised Electron Tubes
mods.forestry.ThermionicFabricator.removeCasts(<Forestry:thermionicTubes:8>);
mods.forestry.ThermionicFabricator.removeCasts(<Forestry:thermionicTubes:8>);
``````````````````````````````````````````````````````````````````````````````````````````

Thanks Guys for your time.
