### ISSUE TITLE
Forestry Machines not properly storing rotation

### ISSUE THREAD

**Issue by Vexatos** [ForestryMC/ForestryMC#545]
If you try to destroy a carpenter (probably any forestry machine) and you don't have permission to break it, it still shows the breaking animation, it breaks but then visually gets replaced, but without remembering its orientation/rotation. Is there any way to make it unbreakable if you try to break it but you can't (because you're not the owner)?

**Comment by Vexatos** [comment]
It appears it also doesn't save its owner when broken. It just sais "Derelict".

**Comment by mezz** [comment]
Sounds like a client/server sync issue. I'll take a look.

**Comment by mezz** [comment]
Thanks for the report @Vexatos, keep them coming! See the Forge issue for some more info.
