### ISSUE TITLE
Wheat farm is planting outside of the default multiblock range.

### ISSUE THREAD

**Issue by killerscorpion** [ForestryMC/ForestryMC#546]
Forestry 1.3.0.7
FML 1307
Minecraft 1.7.10

I made 2 4x4x4 multifarms that are sitting close to each other. One is a wheat farm and the other is the default tree farm. The wheat farm is placing soil and seeds on the tree farm even though its outside of the 5 block max range according to the wiki. I attached a picture to show this. In this picture the tree farm is only setup, as in there is no gearbox or valve or hatch blocks  installed yet. The wheat farm is placing wheat in the tree farms territory.
![2015-03-05_19 58 49](https://cloud.githubusercontent.com/assets/10732882/6520094/2a67746e-c373-11e4-8e7c-90736b1896ea.png)

**Comment by mezz** [comment]
Thanks for the report!
Please try the latest unstable build. http://jenkins.ic2.player.to/job/Forestry_Dev/
The problem you pointed out should be fixed.

**Comment by killerscorpion** [comment]
i did that and it fixed it but then my wheat farm suddenly started turning into a square shape and got rid of the diamond. should i open a new issue?

**Comment by mezz** [comment]
The new farms spread farther than before (they are bigger), but the farmland should only spread onto valid farm base blocks like bricks, stone bricks, etc.

**Comment by killerscorpion** [comment]
its spreading where there are no stone bricks.

**Comment by mezz** [comment]
Ok, please open a new bug for that (with a picture please). That shouldn't happen.

As a workaround for now, you can place stone bricks in the way of the farmland to stop it from spreading there.
