### ISSUE TITLE
wheat farm removes diamond shape and places farmland in "invalid" spaces.

### ISSUE THREAD

**Issue by killerscorpion** [ForestryMC/ForestryMC#547]
Forestry dev build 484
FML 1307
Minecraft 1.7.10

I updated to build 484 from the stabe version of 1.3.0.7 and my wheat farm suddenly started placing farmland in invalid spots. In other words its placing farmland where there should be stone bricks for example but there isn't stone bricks there. Also the wheat farm is no longer a diamond shape, its a sort of square shape. The picture attached shows a tree farm (left) of the layout of the wheat farm, a simple 4x4x4 multifarm with stone bricks as the structure base. the tree farm (left) is the same layout as the wheat farm (right) but as you can see the wheat farm is not a diamond and is placing farmland outside of the stone brick layout. 
![2015-03-05_21 47 40](https://cloud.githubusercontent.com/assets/10732882/6520853/2b8c10c0-c382-11e4-95bc-70f523c3da1c.png)

**Comment by mezz** [comment]
Great report, thanks. I'll take a look.

**Comment by retep998** [comment]
Another issue with multifarm placement is that before I could place blocks in the soil area to put torches on and the farm would just work around them. Now the farm is ignoring the entire row behind a non-soil block.
![](http://puu.sh/gpWaa/2fce9bafc9.png)

**Comment by XFactHD** [comment]
I am having the same bug, that the soil exceeds the base layout made out of bricks. I am using the biggest farm layout. Also, when the farm places water source blocks in the area that overlaps the structure base, it doesn't flow down and needs a block update near it to start flowing.

**Comment by CovertJaguar** [comment]
Farms were modified so that wouldn't overlap into the area of other farms if there was a non-base block between them. This is likely the reason that your Torch blocks are causing the Farm to ignore sections.
