### ISSUE TITLE
Allow Biomass creation from PlantMagaPack's Kelp.

### ISSUE THREAD

**Issue by Kubuxu** [ForestryMC/ForestryMC#549]
It is resource with fun farming technique.
I am suggesting default 100mB water to 100mB biomass ratio.
Pinging @Nirek-K as I was told by mezz.

**Comment by Nirek-K** [comment]
I've been meaning to sit down and actually have a look at that mod and see what was supportable.
Should be able to hash out at least some basic stuff.

**Comment by mezz** [comment]
Implemented by this PR from Nirek: https://github.com/ForestryMC/ForestryMC/pull/562
