### ISSUE TITLE
Inability to craft Scented Panelling

### ISSUE THREAD

**Issue by JasonMcRay** [ForestryMC/ForestryMC#553]
Few players of my modpack InfiTech 2 are reporting that Scented Paneling is sometimes not craftable in carpenter. It shows in NEI, but when they put needed items in the carpenter, sometimes it doesnt work.

I have been provided with 2 FML logs from the server session it was not craftable:
https://www.dropbox.com/s/0tq6k3sk3h10o0v/fml-server-1.log?dl=0
https://www.dropbox.com/s/zz6x4x3f1utnavy/fml-server-latest.log?dl=0

Using forestry 3.4.0.7 on forge 1263.

**Comment by Dream-Master** [comment]
Now Modtweaker 2 have Forestry support. (only a quick solution so long it is fixed)

**Comment by mezz** [comment]
Thanks for the report!
@JasonMcRay I took a close look at the log but didn't find anything out of place.
I made some changes to the carpenter recently, can you see if someone can replicate the issue on [the latest unstable build](http://jenkins.ic2.player.to/job/Forestry_Dev/)? Hopefully it's already fixed, I wasn't able to reproduce the issue myself. If they can, please have them provide a screenshot with texture packs disabled. Thank you!

**Comment by JasonMcRay** [comment]
I just tested the latest unstable build. And it doesnt work at all.
Also in release build I have found out, that if I use a honey in the can to fill up the carpenter, it will not work. But if I use bucket of honey, it works.

**Comment by leagris** [comment]
@JasonMcRay I use unstable builds of Forestry and it works perfectly as expected.
The carpenter needs fluid honey. So you can not put drops directly. It needs either fluid containers with fluid honey (buckets, wax capsules, IC2 cells… Or through piping fluid honey.
You can get fluid honey out of honey drops with a squeezer.

**Comment by JasonMcRay** [comment]
I am using liquid honey, i never said I used honey drops

**Comment by mezz** [comment]
https://github.com/JasonMcRay/InfiTech-1.7/issues/144#issuecomment-88588405
Looks to be resolved, they had the wrong honey. This is an issue with the transition between older versions and 3.4.0 and hopefully shouldn't come up too often.
