### ISSUE TITLE
Backpack performance issue

### ISSUE THREAD

**Issue by Slind14** [ForestryMC/ForestryMC#554]
Hey,

just a small heads up on the backpack issue where there is quite some room for performance improvements:
![](https://i.imgur.com/gvL8kiz.png)
(one backpack filled with many different ore's on a server with +20 players)

**Comment by mezz** [comment]
Thanks for the report!
I recently optimized that call quite a lot for this issue: #533
Can you try again with [the latest unstable build](http://jenkins.ic2.player.to/job/Forestry_Dev/) to see if it's fixed?

**Comment by mezz** [comment]
Hi @Slind14, any findings?

**Comment by Slind14** [comment]
I'll what I can find out, but to be honest I don't have a proper test setup.

**Comment by Slind14** [comment]
as said before I don't have a proper testsetup but from what I did (filling it with all sorts of different blocks (id's)) it seemed solved. Thank you.
