### ISSUE TITLE
Bad naming caused a Maven repo broke down

### ISSUE THREAD

**Issue by Daryout** [ForestryMC/ForestryMC#555]
Well, after trying to fix that ForgeGradle dependencies error, I found that's not my fault. Your repo iat  maven.ic2.player.to got a complete mistake (or I'm a jerk) that you name your items "forestry**_**X.X.X-XXXX-dev.jar" (which gradle CAN'T understand) instead of "forestry**-**X.X.X-XXXX-dev.jar" (which gradle CAN understand).Please try to change that bad naming.

**Comment by Daryout** [comment]
I've tried these
`
	compile "net.sengir:forestry.forestry_1.7.10:3.4.0.7:dev"
`
`
	compile "net.sengir.forestry:forestry_1.7.10:3.4.0.7:dev"
`
None of these works.

**Comment by Daryout** [comment]
well, just one more try fixed it
`compile "net.sengir.forestry:forestry_${config.cb_minecraft_version}:${config.forestry_version}:dev"`

**Comment by mezz** [comment]
Gradle is frustrating. Thanks for posting the solution instead of just closing the issue!
