### ISSUE TITLE
Crash on startup in custom pack

### ISSUE THREAD

**Issue by Qohelethh** [ForestryMC/ForestryMC#556]
I get this crash on startup and I can't figure out why.

https://gist.github.com/Qohelethh/dbe466900f3c176f6ae0

**Comment by mezz** [comment]
Thanks for the report!

This probably has something to do with it:

>Forestry : Info: The following plugins have been disabled in the config: energy, factory, farming, storage, buildcraft.fuels, buildcraft.recipes, buildcraft.statements, buildcraft.transport, propolis.pipe, equivelent.exchange, farm.craftory, industrialcraft

Disabling lots of plugins is still not entirely perfect because there are a lot of interactions and configurations to test. I'll take a look at this one soon.

**Comment by Qohelethh** [comment]
Re-enabling the factory and energy components solved the crash.

**Comment by mezz** [comment]
Cool! I'll reopen this so I remember to make sure it works with the configuration you had before.
