### ISSUE TITLE
Analyzer - NPE Ticking block entity - server crash

### ISSUE THREAD

**Issue by Terpo** [ForestryMC/ForestryMC#557]
Server crash when a player took out an analyzed bee from the analyzer. 
http://pastebin.com/FXevrfG6

forge 1291
binnie-mods-2.0-pre8
gendustry-fu-mc1710-1.4.9.19
forestry_1.7.10-3.5.0.485-unstable.jar
all mods: http://blog.terpo.org/upload/mc/modlist.txt

**Comment by mezz** [comment]
Thanks for the report!
Should be fixed in [the latest unstable build](http://jenkins.ic2.player.to/job/Forestry_Dev/).
