### ISSUE TITLE
All Forestry Fluid Can Be Duplicated

### ISSUE THREAD

**Issue by 3TUSK** [ForestryMC/ForestryMC#559]
Using Forge 1291 (as recommended), Forestry 4.5.0.486 (as the latest) ONLY
Steps (under survival mode):
1.You have a ethanol bucket (for example), right click to dump ethanol on the ground
2.Then you get a empty vanilla bucket. Right click the fluid source block.
3.Then you will find that the source block is still here, and you have a ethanol bucket.
(4.Repeat 3. to get infinity ethanol :) )
While Buildcraft Fuel bucket doesn't have such a problem.
Hope to get reply soon. Also thanks for your time.

**Comment by mezz** [comment]
Thanks for the report!
Fixed in [the latest unstable build](http://jenkins.ic2.player.to/job/Forestry_Dev/).
There will most likely be a stable build soon with this patch as well.
