### ISSUE TITLE
Infinite Ethanol 

### ISSUE THREAD

**Issue by GroundScore** [ForestryMC/ForestryMC#565]
This glitch is simple and easy to replicate, you dump out a bucket of Ethanol, try to scoop it up, you got Ethanol for days. i am running the latest Java sdk, on Ubuntu 14.10 if you are interested.

**Comment by mezz** [comment]
Thanks for the report!
This is a duplicate issue, already fixed: https://github.com/ForestryMC/ForestryMC/issues/559
