### ISSUE TITLE
Habitat Locator icon is broken on 32x + texture packs

### ISSUE THREAD

**Issue by mezz** [ForestryMC/ForestryMC#566]
![2015-03-26_22 18 59](https://cloud.githubusercontent.com/assets/916092/6862947/3196d8c6-d406-11e4-8a84-d0f41c524ab4.png)

wat

**Comment by mezz** [comment]
![2015-03-26_22 21 19](https://cloud.githubusercontent.com/assets/916092/6862975/9190a69e-d406-11e4-90cf-b017272a06c7.png)

**Comment by leagris** [comment]
Hooray!
For the record, it was a very old bug:
http://www.minecraftforge.net/forum/index.php/topic,11300.msg58043.html#msg58043
https://bitbucket.org/sengir/forestry/issue/507/habitat-locator-texture-mc16
