### ISSUE TITLE
My machines aren't being powered (1.7.10)

### ISSUE THREAD

**Issue by Mikraken23** [ForestryMC/ForestryMC#569]
I've set up my machines according to all of the guides I could find, even following youtube videos step by step. My engines are producing power, but the power isn't flowing through my kinesis pipes to power the machines. Attached is a sample of what I have (I only added the redstone wires because nothing else was working, and it still isn't):
![2015-03-27_20 41 03](https://cloud.githubusercontent.com/assets/11689715/6879713/d4fcb6aa-d4c1-11e4-9a19-35377331281c.png)

**Comment by Mikraken23** [comment]
Also, that pump that's supposed to be moving on the engine never moves. Whenever I place any engine, I can't get it to face any direction except west.

**Comment by mezz** [comment]
Thanks for the report!
What versions of BuildCraft and Forestry are you using? In 1.7.10 there has been a migration from MJ to RF, and you will need to have recent versions for the mods to work together.

**Comment by Mikraken23** [comment]
Forestry is 1.7.10, and Buildcraft is also (stable version). Which versions should I be using?

**Comment by mezz** [comment]
I mean the versions of the mods. 
Latest Forestry is 3.4.0, latest BuildCraft is 6.4.5

**Comment by Mikraken23** [comment]
Oh, let me see...

**Comment by Mikraken23** [comment]
Forestry is 3.4.0.7, and I'm not sure which Buildcraft it is, but I think it is also 6.4.5. Do you have a link that I can download from just to make sure it's the right version?

**Comment by mezz** [comment]
Forestry is here: http://www.curse.com/mc-mods/minecraft/forestry
BuildCraft is here: http://www.mod-buildcraft.com/pages/download.html

**Comment by mezz** [comment]
Oops didn't mean to close the issue yet

**Comment by Mikraken23** [comment]
Okay, excellent! It turns out Buildcraft wasn't the right version, which is why it wasn't working. I just logged in to test it and it's running fine now. Thank you so much!

**Comment by mezz** [comment]
Cool, glad it's working now. Please let us know if you find any other issues!
