### ISSUE TITLE
Apatite Generation boom in 1.7.10-3.4.0.7

### ISSUE THREAD

**Issue by VileTouch** [ForestryMC/ForestryMC#570]
It should be fairly obvious to anyone using latest version. upon installation, apparently ALL apatite veins in the world are regenerated. that wouldn't be a problem if the generation was throttled to a portion of the available resources, but as it is, once it starts happening it will take any and all available memory and processor time until a point nothing can run. not even minecraft itself.
The issue only appears upon a stack trace and there's no way in game of knowing what is going on.

As a test i increased java's xmx from my usual 1536m to 2048m then 4096m then 8192m just to see how far it would go. well, it would always eat every available resource to the maximum no matter how much it is given.

**Comment by mezz** [comment]
Thanks for the report!
Did you turn on retrogen in the config file?

**Comment by mezz** [comment]
@VileTouch ?

**Comment by VileTouch** [comment]
sorry, i discovered my logs folder was gone (too many backup files said little brother ¬¬ ) so i'm trying to reproduce the error again while i consider what method of torture should i use on him.

**Comment by VileTouch** [comment]
I finally produced a log showing the issue... somewhat.
Created a new world and naturally, apatite started generating until it hit the memory limit and MC crashed.
What happened before was that apatite regenerated in an existing (multi-gigabyte) large world. but after disabling it once it never happened again.

anyway, here's the file: http://ge.tt/53CfzfD2/v/0

**Comment by mezz** [comment]
Absolutely strange.
The code to generate Forestry ores is called directly by FML, and Forestry's retrogen is not enabled.
Do you think some other mod is set to change worldgen, like CoFHCore's Ore Generation?

**Comment by VileTouch** [comment]
that could be a possibility. though it doesn't explain why the out of memory crashes would stop and never show up again after disabling apatite generation... however there is another factor that was resolved recently: myscraft's world profiling was creating the same issue with biomes o' plenty. (latest updates fixed that). could it have been related?

and speaking of updates, congratulations on the latest forestry update. the performance increase is massive! (easily over 100% faster)

**Comment by MysteriousAges** [comment]
It's possible that if the apatite veins are too large, they're passing over a chunk boundary and causing a chain-load-regen loop.

**Comment by mezz** [comment]
@VileTouch I'm sorry but I haven't been able to reproduce this issue. 
I think something is messing with the apatite generation, leading to what Myst said.
The apatite veins are normally big, and if something messes it up they could endlessly load more chunks until the game crashes.

**Comment by mezz** [comment]
I've still never had this happen with regular Forestry. 
Going to close the issue unless there is a way to reproduce it.
