### ISSUE TITLE
Add a link to Crafting Guide

### ISSUE THREAD

**Issue by andrewminer** [ForestryMC/ForestryMC#572]
I've been working on a project to make it easier to deal with complex mods (especially tech mods), and @sheldongriffin recently added support for Forestry. The gist of the site is that you tell it what item(s) you want to make, and it will figure out all the raw ingredients you need along with step-by-step instructions. For example, here's how you make a [farm control, hatch, valve and a bunch of farm blocks](http://crafting-guide.com/craft/25.farm_block_bricks:farm_control_bricks:farm_hatch_bricks:farm_valve_bricks).

The maintainers of mods I've added (e.g., BuildCraft / Applied Energistics / EnderIO) have found it useful to include links to Crafting Guide in their official documentation, and I was hoping you would feel the same. I'd be happy to make the changes to the wiki myself if you like the idea.

Thanks!

**Comment by VileTouch** [comment]
I wonder if you've ever used [NEI](http://chickenbones.net/Pages/links.html) before.

**Comment by andrewminer** [comment]
Naturally!  NEI is terrific, and I use it constantly. However, Crafting Guide goes quite a bit further than NEI.  If you follow the link above, you'll see that Crafting Guide computes all the recipes all the way back to raw materials, and then takes you step by step through the process of creating whatever it is you're after.  Moreover, it can do so for many different items at once.  As another example, here's the crafting guide for making an [entire IC2 QuantumSuit](http://crafting-guide.com/craft/quantumsuit_bodyarmor:quantumsuit_boots:quantumsuit_helmet:quantumsuit_leggings).

**Comment by Xariyl** [comment]
The Crafting Guide makes for a great out-of-game Wiki and resource planner for any builds you have in mind. It is highly recommended and praised within the communities of the respective supported mods.

**Comment by VileTouch** [comment]
@Xariyl : that i must agree

**Comment by andrewminer** [comment]
@ForestryMC Any opinion on adding a link?

**Comment by KamranMackey** [comment]
@andrewminer, ask @mezz. He's one of the main devs.

**Comment by mezz** [comment]
Seems useful, I can add it next time I'm messing with the site.

**Comment by mezz** [comment]
[Page added](http://forestry.sengir.net/wiki.new/doku.php?id=other:craftguide), the link is at the bottom of the leftside navigation box.
