### ISSUE TITLE
Vanilla Acacia and Dark Oak saplings can't be used in the fermenter

### ISSUE THREAD

**Issue by doushio9967** [ForestryMC/ForestryMC#573]
While saplings with genome data will work, the untouched vanilla types won't.

https://github.com/ForestryMC/ForestryMC/blob/dev/src/main/java/forestry/plugins/PluginFactory.java#L331
Looks like only meta 0-3 gets registered?

Forestry b506.
Thanks.

**Comment by mezz** [comment]
Thanks for the report!
And thanks @Nirek-K for the fast fix.
