### ISSUE TITLE
MineTweaker, Forestry, TiC, TE compatibility

### ISSUE THREAD

**Issue by Xariyl** [ForestryMC/ForestryMC#577]
An issue noted when working with our beta modpack. Building a TE sawmill within a Forestry work table, MineTweaked to use a Tinker's axe instead of vanilla, crashes you out of the game.

Crash report: http://pastebin.com/7RE5Kp4s

Modpack initial report: https://github.com/AlexTheGre4t/MCTNG/issues/31

**Comment by mezz** [comment]
Thanks for the report!
This is a tough one, it looks like the Tinker's Axe has no TagCompound. I'll check to see that the worktable isn't removing it somehow.

**Comment by mezz** [comment]
Since the worktable handles other recipes with items that have tag compounds just fine (all the Forestry woods, many other things tested) I'm going to say that this issue is most likely with MineTweaker, TiC or IguanaTweaks.

**Comment by Xariyl** [comment]
Iguana's does do some interesting stuff to the tools. I'll do some more testing. Thanks.

**Comment by jadedcat** [comment]
There is no good way to use TiCon crafted tools in recipes with modtweaker. You can however use just the tool part, like the flint pickaxe head. but noe the full pickaxe.

**Comment by Xariyl** [comment]
That's a good idea. I'll probably do that,  thank you.
