### ISSUE TITLE
Changing Centrifuge Recipes with Minetweaker/Modtweaker

### ISSUE THREAD

**Issue by Voidi** [ForestryMC/ForestryMC#579]
It seems that the centrifuge don't accept a recipe with Metadata '*' Wildcard 

https://github.com/jaredlll08/ModTweaker2/issues/37#issuecomment-71387523

Is this a bug in Forestry or did Modtweaker something wrong?

**Comment by mezz** [comment]
Thanks for the report!
Looks like a bug on our side, I'll fix this soon.

**Comment by mezz** [comment]
Should be fixed in the latest unstable build
