### ISSUE TITLE
Add a way to register items to work as fertilizer in farms

### ISSUE THREAD

**Issue by Vexatos** [ForestryMC/ForestryMC#580]
Currently Forestry's Apatite fertilizer is the only item that is allowed to be used as fertilizer in Forestry farms. It would be nice if there was a way to register other items as farm-compatible fertilizer; not sure if that would be good or if that would break the farms' balance too much...

**Comment by mezz** [comment]
I think special care has been taken to prevent other fertilizers from working in the farm (no oredict name for fertilizer, no way to register fertilizers, few other uses for apatite, it's basically the only non-easily-renewable resource to power the farm). This seems to be against the intended design.

**Comment by Adaptivity** [comment]
There are a lot of mods which adds own fertilizers. Not sure if it break balance since you shouldn't register *everything* that have fertilizer in name. Basically you should just add whitelist with acceptable fertilizers(which shouldn't break balance) and allow players to extend it to their taste.

**Comment by mezz** [comment]
I see, that makes sense. Modpacks should have that flexibility.

**Comment by Vexatos** [comment]
I was just thinking that there might be mods regisering their fertilizer as farm-compatible fertilizer when those types of fertilizer are much easier to get than the apatite one. Not sure if that would break balance; if it doesn't go ahead and add something to the API for that.

**Comment by Yulife** [comment]
Yeah, API would be neat. Then Modtweaker could hook into that - custom fertilizers! Looking forward to it.

**Comment by SirSengir** [comment]
The restriction to the non-renewable Apatite is intended design. Designs can change though. ;)

Problem with "fertilizer" added by mods usually is, that most of those are very, very easy to obtain and often extremly easy to make renewable - effectively invalidating the whole fertilizer mechanic. (Currently you need to find a way to make Apatite renewable and the only way I know of is a bee in MagicBees.)

If an API were added, it should offer the ability to adjust the effectiveness on a per-fertilizer basis. (I.e. have different fertilizers yield different fertilizerValues in https://github.com/ForestryMC/ForestryMC/blob/dev/src/main/java/forestry/farming/gadgets/TileFarmPlain.java#L650)

**Comment by Vexatos** [comment]
@SirSengir That is exactly what I was worried about. Thanks for clarifying.
