### ISSUE TITLE
Carpenter dont work

### ISSUE THREAD

**Issue by Kanol** [ForestryMC/ForestryMC#584]
I had just update forestry from 496 unstable to 514 unstable and when i shell out recipe in carpenter and give it all items and liquids and energy for the recipe it dont do anything. For this recipe it must to make scented paneling.
![image](https://cloud.githubusercontent.com/assets/10697310/6966435/809dd700-d972-11e4-81ee-d2b0b62b38a7.png)

**Comment by wilkemeyer** [comment]
I can confirm the bug,  tested today - Build 510 has introduced it.

With 509 everthing is fine.

**Comment by mezz** [comment]
Thanks for the report!
Fixed in the latest unstable, Build 515
