### ISSUE TITLE
Unlimited fluids in forestry_1.7.10-3.4.0.7?

### ISSUE THREAD

**Issue by louieDep** [ForestryMC/ForestryMC#585]
Folks, 

If a Forestry fluid is placed in the world, it is not removed after a successful manual bucket fill. Seems to be true for honey, seed oil, biomass and juice. I can't replicate this with non-Forestry fluids.

The "in world" fluid can be removed with a BC pump, but can't be removed bucket-based automation. A block drop will replace the fluid.

-LouieDep

**Comment by mezz** [comment]
Thanks for the report!
This has already been fixed and will be in version 3.5.0, coming very soon.
https://github.com/ForestryMC/ForestryMC/issues/559

Please let us know if you find anything else.
