### ISSUE TITLE
java.lang.RuntimeException: Tried to make a crate without an item

### ISSUE THREAD

**Issue by iarspider** [ForestryMC/ForestryMC#588]
Forestry 3.5.0.8 crashes on startup with this error. 
Crash log: http://paste.ee/p/AChBc
Client log: https://gist.github.com/iarspider/491eb268dcb681e7ab0a

**Comment by Nirek-K** [comment]
Not seeing this on my client, do you have any nonstandard config options set, for either mod? Forestry/Natura, disabled modules or similar?

**Comment by Nirek-K** [comment]
Still no idea how you're getting a null there, for some reason it's not finding the maple sapling, but the referenced commit/pr should fix the issue at least in not crashing. Give the unstable generated from it when it gets pulled a try.
