### ISSUE TITLE
Forestry 3.5 Crashes With Ex Nihlio

### ISSUE THREAD

**Issue by Amaxter** [ForestryMC/ForestryMC#595]
Forestry 3.4 versions worked fine with Ex Nihlio but with the 3.5.2.10 update I get the following crash:
http://pastebin.com/iq0Lh76k 
(This happens with the stable and beta versions of Ex Nihlio)

**Comment by Adaptivity** [comment]
https://github.com/ForestryMC/ForestryMC/issues/590

**Comment by mezz** [comment]
Thanks for the report! 
Please report this to Ex Nihilo
