### ISSUE TITLE
Crash when accessing Thermionic Fabricator

### ISSUE THREAD

**Issue by Dean4Devil** [ForestryMC/ForestryMC#604]
Accessing a Thermionic Fabricator crashes at `net.minecraftforge.fluids.FluidRegistry.isFluidRegistered(FluidRegistry.java:97)`

Full crash report with both stable and latest version of can be found [here](https://gist.github.com/Dean4Devil/b777f2c0f34c111c443d)

While I use Java 1.8 a friend of mine uses 1.7 and crashes the same way.
We also observed a similar crash with Tinkers Construct, so maybe its a Minecraft Forge issue rather than a Forestry one?

**Comment by Dean4Devil** [comment]
This is an error with Forge. Downgrading to stable Forge (10.13.2.1291) fixes the error.

**Comment by mezz** [comment]
Thanks for the report!
Can you please find the issue or report it to Forge? Without a report, the problem may end up in the next stable Forge. https://github.com/MinecraftForge/MinecraftForge/issues

**Comment by mezz** [comment]
Fixed in Forestry in the latest unstable version.

**Comment by mezz** [comment]
This is also fixed in Stable 3.5.4 now.

**Comment by LuisFuchs** [comment]
Hello mezz,
if 3.5.4 is stable & recommended, push the direct downloadable version on curse from 3.5.3 to 3.5.4, else people will get the buggy version.

Kind regards

**Comment by mezz** [comment]
Thanks, I didn't realize it was the wrong version. It should always be the latest automatically. I contacted Curse and they fixed it right away.
