### ISSUE TITLE
breeding assistance

### ISSUE THREAD

**Issue by chemfun** [ForestryMC/ForestryMC#606]
My students did well this year with the tree breeding.  I've been playing with the latest stable version of forestry and I'm unclear on how to breed butterflies.  Is it possible to manually breed butterflies like trees and bees?

**Comment by mezz** [comment]
I don't think many people know how. However, I was able to find out by looking at the code and trying it out in my game:

To catch a butterfly, chase after it with a scoop and hold right-click.
Then you can research the butterfly in the [escritoire matching minigame](http://ftbwiki.org/Escritoire).
If you research successfully, it will give you some butterfly serum with the same genome. 
You can then combine a butterfly with a serum in any crafting table to mate it manually.
The genome works the same way as the bees and trees, so you have a small chance to get a mutation that results in a new butterfly when it lays its caterpillars on leaves.

The Flutterlyzer has a blank mutations page so there's no way to know how to breed them, I'll see if I can fix that soon.

**Comment by CovertJaguar** [comment]
I was thinking that Butterflies would work well as wandering status inflictors. Heath regen, speed boosts, slows (give them a trait for whether their status affects enemies or friendlies or both). That kind of thing.

**Comment by chemfun** [comment]
That would be cool, I could place butterflies in specific locations. 

For my classroom genetics use, it would be nice if butterflies could breed with "simple Mendelian genetics." 

Ideally if we could breed with dominant and recessive traits that would be the ideal.  The ability to create a specific butterfly with specific traits would be sweet. 


If this effected the status that would be cool too. The Mendelian traits don't matter as much to me, as much as being able to breed and get results that are repeatable. That's why the trees were so ideal (though not quite Mendelian)
