### ISSUE TITLE
Fluid Registry crash on right clicking squeezer ( minecraft forge 1365 ) 

### ISSUE THREAD

**Issue by KristjanKr** [ForestryMC/ForestryMC#608]
For the love of god, please fix this!
Crash log:
http://paste.ee/p/nzh33

**Comment by mezz** [comment]
The latest Forge made a breaking change to fluids. I'll fix this soon. For now just use the stable Forge.

**Comment by mezz** [comment]
Fixed in Forestry in the latest unstable version.
