### ISSUE TITLE
Forge fluidstack crash (unstable build)

### ISSUE THREAD

**Issue by Tsunayoshi** [ForestryMC/ForestryMC#609]
This happend on opening any block with a fluid inside
http://pastebin.com/Nc8VuNqt

forge-1.7.10-10.13.3.1370-1.7.10
forestry_1.7.10-3.6.0.527-unstable

**Comment by Chocohead** [comment]
Already been fixed in 528: https://github.com/ForestryMC/ForestryMC/commit/b8b7ea328f2212938a369f693930912306ae392b

**Comment by Tsunayoshi** [comment]
Wohoo nice work!!!

**Comment by mezz** [comment]
Dupe of https://github.com/ForestryMC/ForestryMC/issues/604
