### ISSUE TITLE
Escritoire and Mystical Bees

### ISSUE THREAD

**Issue by Fishbone5618** [ForestryMC/ForestryMC#610]
Running FTB Infinity 1.3.4.  Was researching the Mystical Bee in the Escitoire and on a successful research, I did not get any combs or research notes.  Tried 4 different times. Received nothing.

**Comment by mezz** [comment]
Thanks for the report!
Please grab [the latest Magic Bees from curse](http://www.curse.com/mc-mods/minecraft/magic-bees), we've updated it recently.
If you still have the issue, please report to the [Magic Bees issue tracker](https://github.com/MagicBees/MagicBees/issues). Thanks!

**Comment by Fishbone5618** [comment]
thanks for the quick response, I have updated Magic Bees, but will be a few
hours before i can test it. Thanks again for all the work you do to make
Minecraft better.
