### ISSUE TITLE
Server is crashing after the latest update.

### ISSUE THREAD

**Issue by ZPinka** [ForestryMC/ForestryMC#617]
One of my players is into Forestry and since the update it seems some butterflies are causing the crash. 

Here is the crash log:

https://gist.github.com/mezz/9c13bfe9a87ac9a533d2

I hope anyone can help. Thanks in advance.

**Comment by mezz** [comment]
Thanks for the report!
Please host crash logs on gist or pastebin so they don't take up the whole issue.
Unfortunately this looks like an issue with Binnie's mods. 
It has been reported here: https://bitbucket.org/binnie567/binnie-mods/issue/215/abstractmethoderror-crash-server
Related issue: https://github.com/ForestryMC/ForestryMC/issues/601
