### ISSUE TITLE
PneumaticCraft Farm problem

### ISSUE THREAD

**Issue by Deathwinng** [ForestryMC/ForestryMC#618]
Hello! This mod is my favorite farming mod! But I have bug when I try to make PneumaticCraft farm. When I first build it everything is ok, but when I re-load my world it won't work anymore, all contents in the farm disappear and sometimes the circuit for farm configuration disappear to. When I try to place another circuit nothing happens and the circuit disappears but when I close the farm GUI it pops out of me, and if I open the farm again the circuit is there, but it's not showing the configuration properly:
![2015-04-14_14 42 30](https://cloud.githubusercontent.com/assets/11708611/7135978/96d6ff06-e2b4-11e4-8915-ab7bbb1891be.png) 
Also I can put everything but seeds in it.

Even Minecraft crashed once, here's the [Crash Report](http://pastebin.com/w6sJgLi5)

Summed up: lots of weird stuff happening :D
And sorry if I can't explain it good but English is not my main language :)

Playing Single player on [The 1.7.10 Pack](http://www.technicpack.net/modpack/the-1710-pack.453902) with Foresrty version 3.5.3.11

**Comment by mezz** [comment]
Thanks for the report!
The PneumaticCraft farm support is actually added on their side, and I think @MineMaarten is aware of the problem here: https://github.com/MineMaarten/PneumaticCraft/issues/443
Please let us know if you find any other problems.

**Comment by MineMaarten** [comment]
Hey @Deathwinng , could you find the logs from when this happened? Forestry crashed silently here, and I'm not sure why (it works fine in my dev environment).

@mezz : This issue was mentioned by Quetzi at some point to me, and his issue was that seeds weren't accepted in the slots, as seeds for the farm. I'm trying to find out why that happened suddenty now, it used to work. If you've got any insights let me know :)

**Comment by Deathwinng** [comment]
@MineMaarten [This](http://paste.ubuntu.com/10828202/) is the full log of when the crash happened.

**Comment by MineMaarten** [comment]
ok, that's fixed. I used some reflection into Forestry to make my compatibilty work without having to copy entire classes from Forestry. Which is sensitive to changes Forestry makes, which happened :P.

Still working on that other issue now.

**Comment by mezz** [comment]
Every time you reflect I cry, let me know what you need so I can make an
API and avoid breaking you :D

**Comment by MineMaarten** [comment]
Well, to add support for a simple plant, you need to implement IFarmLogic. The problem with that is that without any reflection and only access to the Forestry API, you need to design the entire logic for this. Watering, usage of fertilizer/resources/water, block placement.

This is why I reflected into Forestry to start off with a default Farm logic (FarmLogicVegetable in this case), and added hacks to allow my seeds to be recognized as seeds.

This all can be seen here: https://github.com/MineMaarten/PneumaticCraft/blob/master/src/pneumaticCraft/common/thirdparty/forestry/FarmLogicPlasticNormal.java

So I think the solution might be to add some interface that can be used for very simple plants that are similar to normal crops. So at least the implementer doesn't have to do all that I just described, but just has to supply what's necessary (the IFarmable).

This would be great, imo ;)

**Comment by mezz** [comment]
This will take a while since it likely involves some internal restructuring, but sounds like a good idea. Added a new issue so I can get to it eventually.

**Comment by MaartenKok8** [comment]
FYI, I won't fix the forestry support that broke a while back, as my plants will soon be removed, and Oil has taken its place already. Still, this API change is probably nice for other implementers :)
