### ISSUE TITLE
Remaining MJ String

### ISSUE THREAD

**Issue by ultrasn0w** [ForestryMC/ForestryMC#619]
Just found a MJ String in a machine GUI.
https://i.imgur.com/vO9htpj.png

Greetings
ultrasn0wz

**Comment by mezz** [comment]
Thanks for the report!
That machine is from Binnie's Mods, please let them know: https://bitbucket.org/binnie567/binnie-mods/issues

**Comment by ultrasn0w** [comment]
Oh, sorry for reporting on the wrong Git, I'll do so :)
