### ISSUE TITLE
Electric Engine Funnyness

### ISSUE THREAD

**Issue by Chocohead** [ForestryMC/ForestryMC#62]
IC2 Cables attach to Electric Engines from any side, including the MJ output, which shouldn't happen.
![2014-07-15_16 48 47](https://cloud.githubusercontent.com/assets/4021725/3590914/28dcafb4-0c5e-11e4-842f-c8162455ee4d.png)
^ Bad

**Comment by mezz** [comment]
There isn't anything Forestry can do on this, so I am closing it. 
Please reply here if IC2 updates their energy API and I can reopen it.

**Comment by laz2727** [comment]
You maybe can fix Mekanism one by configuring the cable into push mode. Or
maybe it isn't in pull mode at the battery to begin with.

2015-03-02 8:52 GMT+06:00 mezz <notifications@github.com>:
