### ISSUE TITLE
Provide publish/subscribe mechanism for species, mutation resistration

### ISSUE THREAD

**Issue by MysteriousAges** [ForestryMC/ForestryMC#620]
Enhancement for next version of API to avoid the issue of mod load timings.

Species/Mutation registry publishes a registration event for other mods to subscribe to, pushes event info to subscribers. This would be in preference over polling the registry for finding out what bee/tree/butterfly species and mutations exist.

Thoughts?

**Comment by mezz** [comment]
Can you show me what you'd use it for so I can get it right? 
I'm already starting a small refactor of the internals of species and mutation registration.

**Comment by MysteriousAges** [comment]
My idea was that mods like Extra Bees could register to the event during preInit, and then catch every registration that occurs so they don't have to worry about load order.
