### ISSUE TITLE
Arboretum Not Showing in Creative Inventory, NEI, or Crafting Table

### ISSUE THREAD

**Issue by NightSlasher324** [ForestryMC/ForestryMC#621]
I don't know if this is normal but I am using Minecraft version 1.6.4 with Forestry-A-2.3.1.1 and the Arboretum machine is not showing up in my creative inventory or NEI inventory. Even when I use the items in a crafting table, nothing appears as if the block doesn't exist. Is there a way to fix this.

**Comment by leagris** [comment]
The Arboretum is deprecated as a single sturdy block.
You need to build a Multifarm.
Multifarm act as Arboretum by default.
You then can choose to configure your Multifarm for other purpose with proper circuit boards.

**Comment by Parker8283** [comment]
1.6.4 is no longer supported.

**Comment by NightSlasher324** [comment]
Thank you Leagris, very helpful.
