### ISSUE TITLE
Crash at the opening of the carpenter

### ISSUE THREAD

**Issue by fazilov** [ForestryMC/ForestryMC#625]
when I try to open a carpenter minecraft just crash 
log 
https://gist.github.com/mezz/783459f89e2954502c87

**Comment by mezz** [comment]
Thanks for the report!
This is a duplicate of #604
Please use the latest unstable build of Forestry if you are using the latest Forge. Forestry 3.5.3 works with the "recommended" version of Forge.
I will probably fix it soon so that the latest unstable build will work with any Forge.
