### ISSUE TITLE
 Cannot create a fluidstack from a null fluid

### ISSUE THREAD

**Issue by LiEyWe** [ForestryMC/ForestryMC#631]
Every time I try to open any gui with fluid, the game crashes.

Crash log: http://pastebin.com/xF4xe4Ys

**Comment by Parker8283** [comment]
Post the ENTIRE file

**Comment by LiEyWe** [comment]
sry, forgot about that... 
here is the entire file http://pastebin.com/J6qYArjM

**Comment by mezz** [comment]
Thanks for the report!
Please update to Forestry 3.5.4, it should fix this issue.
