### ISSUE TITLE
[Orchard Bug]

### ISSUE THREAD

**Issue by whitestarx0312** [ForestryMC/ForestryMC#632]
Forge: forge-10.13.2.1352
Forestry: 3.5.4.13

Upon building a multiblock orchard farm (any type brick), I discovered that I cannot input dirt so that the farm can turn it into humus and begin farming. Once the farm is built and you put in the circuit board, it locks you out and won't let you input any dirt. 

Workaround: Take out the circuit board using a soldering iron, insert dirt, reinsert circuit board. It will then take the dirt and place it on your farm layout.

Just thought I should report this because it left me confused for a good hour.

**Comment by Nirek-K** [comment]
'Orchard' farm tube does not place blocks at all, it only harvests ripe fruits and crops. It expects manually built fruit trees/etc. to be built and does not require humus. This is also why it won't accept dirt in this mode. If you mean something else other than Orchard, please reopen.
