### ISSUE TITLE
Fluidstack problem with new forge

### ISSUE THREAD

**Issue by MySt1k** [ForestryMC/ForestryMC#634]
Crash-report happend on right-click on an analyzer
http://pastebin.com/aYgqTm0J

Forge forge-1.7.10-10.13.3.1370-1.7.10
forestry_1.7.10-3.6.0.527-unstable

**Comment by Nirek-K** [comment]
Update to unstable 533+

**Comment by mezz** [comment]
Thanks for the report!
Duplicates #604
