### ISSUE TITLE
Ticking block: Bottler Issue

### ISSUE THREAD

**Issue by accessdenied0** [ForestryMC/ForestryMC#635]
Dear Forestry developing team,

I did an setup in my world a system with Brewcraft to bottle up Potions for me. I could do so, but as I tried to restart the world next day it crashed. http://pastebin.com/Hazt9CwM

I hope some of you can help here,

access_denied

**Comment by mezz** [comment]
Thanks for the report!
Looks like a simple problem, I can fix this soon. 
We are looping over a list and adding or removing from it at the same time. The only way to do that without crashing in Java is to use an iterator.

**Comment by accessdenied0** [comment]
Dear @mezz,

I thank you for you very kind response, I'm glad I was able to help.

access_denied

**Comment by mezz** [comment]
I think the problem may be more complicated actually. Please remove the old mod "NEI Plugins Unofficial" and add the new version, called [NEI Integration](http://www.curse.com/mc-mods/minecraft/225251-nei-integration). If that doesn't fix the issue, please post here again with a new crash log. Thanks!

**Comment by mezz** [comment]
@accessdenied0 did it work?
