### ISSUE TITLE
[Crash]

### ISSUE THREAD

**Issue by Dream-Master** [ForestryMC/ForestryMC#636]
MC crash with forestry_1.7.10-3.6.0.539-unstable, binnie-mods-2.0-pre8 and magicbees-1.7.10-2.2.3

https://gist.github.com/Dream-Master/db9aeb7cbff2d8d74cfc#file-gistfile1-txt

Posted in Magic Bees git too:
https://github.com/MagicBees/MagicBees/issues/45

Posted at binnies Bitbucket too
https://bitbucket.org/binnie567/binnie-mods/issue/227/crash-server

with forestry_1.7.10-3.6.0.536-unstable it works well

**Comment by mezz** [comment]
Thanks for the report!
I removed old deprecated methods from the API, addon mods need to update. This crash is from ISidedInventory being removed.
