### ISSUE TITLE
Carpenter Crashing from fluid

### ISSUE THREAD

**Issue by JackzTaEpic** [ForestryMC/ForestryMC#637]
Hello. I have created my own modpack, and one of the installed mods is Forestry for Minecraft.
I was playing survival and wanted to create an item in forestry, but it required the carpenter. I crafted the carpenter and placed it down. My base is one block above the water, and the carpenter was above the blocks of the water.

For the first time I clicked it, I keep getting something about fluids. Error log:
http://pastebin.com/SMBt5SSd

**Comment by Nirek-K** [comment]
Update to unstable 533+ or stable 3.5.4
Duplicate of #604
