### ISSUE TITLE
Backpack bug

### ISSUE THREAD

**Issue by SnakeFang** [ForestryMC/ForestryMC#641]
If you open a forestry backpack, and take something out, then the inventory is forcefully closed, for example by dying, being kicked, or going into a nether portal block, the backpack inventory doesn't update and the item is duplicated.

**Comment by mezz** [comment]
Thanks for the report!
I tried quite a lot but was unable to reproduce this bug. What version of Forestry are you using?

**Comment by SnakeFang** [comment]
Thanks for replying. I'm using the recommended Forestry version, recommended Forge, and OptiFine (I don't think that'll help with a client and server dupe). I can always reproduce this, and made a short video showing how it is done.  https://www.dropbox.com/s/tbqlv5rglejrfgv/Dupe.mp4

**Comment by mezz** [comment]
Thank you, I was holding them with the mouse as I went through, instead of
moving them to my inventory. I'll take a look soon.

**Comment by mezz** [comment]
It looks like Minecraft handles this situation strangely, from what I can see it doesn't close the inventory on the server correctly. 
The solution is to make the backpack save changes to its inventory every time an item is moved, instead of when it's closed.

**Comment by mezz** [comment]
Wrapping this one up soon, lots of testing to do since the NBT format for storing the items is changing.
