### ISSUE TITLE
Client crash when opening Multifarm GUI

### ISSUE THREAD

**Issue by j2997** [ForestryMC/ForestryMC#642]
I recently updated forestry, and whenever I attempt to open a Multifarm GUI, the client (not the server) crashes to desktop. Other than that, the game appears to run fine. Initially I wondered if this was a Forge bug, however upon further examination I discovered that other mods displaying fluids in a GUI (i.e. Thermal Expansion and Big Reactors) had no issue, and that theory seemed to be less likely (but still possible). I have posted a pastebin of the log below, and this was tested on Forge 1395 with Forestry version 3.5.3.11. Any help would be appreciated!

http://pastebin.com/4st77mtf

**Comment by Nirek-K** [comment]
Update to unstable 533-536 or stable 3.5.4
Duplicate of #604

**Comment by j2997** [comment]
Thanks so much!
