### ISSUE TITLE
Mycelium: java.util.NoSuchElementException

### ISSUE THREAD

**Issue by ultrasn0w** [ForestryMC/ForestryMC#646]
Hey there,
I currently have set up a automated Apiary with Boggy Bees.
They have Mushroom and Mycel as effect.
After I let the Bees alone for a day or two I sometimes get this crash on my server:
http://pastebin.com/BJykB16U

Greetings
ultrasn0w

**Comment by Nirek-K** [comment]
Should be fixed by c705486472480846830d7c7952ec9e8c674b35c1
