### ISSUE TITLE
Suggestion: Chalk for marking trees.

### ISSUE THREAD

**Issue by Sandriell** [ForestryMC/ForestryMC#647]
A way to mark the trunk of trees with an "X" using chalk, or something silimiar, that are to be chopped down. Would be very useful in multiplayer for one person to mark the trees to be removed while the other person follows behind with an axe.

Like how it is done in real-life: http://s0.geograph.org.uk/geophotos/02/21/17/2211712_4bf0ddd9.jpg

**Comment by CovertJaguar** [comment]
This could be done in the same way that Fire currently works. I think it would be great not just for trees, but for marking anything.

**Comment by XFactHD** [comment]
If it works like fire, it shouldn't be erasable by punching it, but with something like a black board sponge.
