### ISSUE TITLE
Ticking Entity crash

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [ForestryMC/ForestryMC#649]
I'm crashing...randomly...no idea why... http://hastebin.com/juvazozafa.1c

**Comment by Nirek-K** [comment]
Duplicate of #646, should be fixed by c705486472480846830d7c7952ec9e8c674b35c1

**Comment by Nirek-K** [comment]
S'Ok, as to the issue, as you can see from the linked one, all that really effects is waterproof bee sealant, and pipe autoextraction, should be fine otherwise.
