### ISSUE TITLE
[apiculture] Crash Ticking block entity

### ISSUE THREAD

**Issue by MySt1k** [ForestryMC/ForestryMC#650]
http://pastebin.com/BYHgVReu

forestry_1.7.10-3.6.0.546-unstable

**Comment by Nirek-K** [comment]
Should also be fixed by c705486472480846830d7c7952ec9e8c674b35c1
related to #646

**Comment by Nirek-K** [comment]
Gah, so it is.

**Comment by Nirek-K** [comment]
Should be fixed with unstable 547.
