### ISSUE TITLE
TARDIS mod power transfer

### ISSUE THREAD

**Issue by Durpady** [ForestryMC/ForestryMC#651]
A recently released mod located at http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2420176-tardis-mod adds, as its name describes, a TARDIS to Minecraft.  One of its features is the ability to pipe items, fluids, and RF energy through it.  Railcraft, Buildcraft, and Binnie machines will successfully receive RF from appropriately-equipped Roundels; Forestry machines, however, will not, whether directly adjacent to the Roundel, or when they're mutually connected to a Buildcraft Kinesis Pipe.  Since the aforementioned machines do receive power, I'm guessing this is a problem on your end.  Forestry 3.5.4.13, TARDIS mod version 0.95-43.

**Comment by mezz** [comment]
Thanks for the report!

Looks like a buggy mod, it just crashed without warning when I didn't have Thaumcraft...
And crashed again for no reason.

Anyway, it works fine with the latest versions (Forestry 3.5.6, TARDIS 0.98-68, darkcore-0.2-16, CoFHCore 3.0.2-262)

![2015-05-15_22 39 42](https://cloud.githubusercontent.com/assets/916092/7664877/65c62fba-fb53-11e4-8f3f-edacb7a21457.png)

![2015-05-15_22 41 56](https://cloud.githubusercontent.com/assets/916092/7664884/a523651a-fb53-11e4-9b50-a76344a92016.png)
