### ISSUE TITLE
There have a BUG with forestry.Bottler in Server!

### ISSUE THREAD

**Issue by Antecer** [ForestryMC/ForestryMC#652]
Server:cauldron-1.7.10-1.1370.01.0-server.jar
Forestry:forestry_1.7.10-3.6.0.546-unstable.jar and forestry_1.7.10-3.5.4.13.jar

This Bug makes the machine can copy liquid in server！
In the server,the machine liquid not less.

But in single game，this error does not exist,it's only in server.

**Comment by Parker8283** [comment]
Have you tried with a Forge server instead of a Cauldron server?

**Comment by Antecer** [comment]
ok，i will test it.

**Comment by Antecer** [comment]
yeah! This BUG also in Forge server!
sever:minecraft_server.1.7.10.jar
forge:forge-1.7.10-10.13.3.1400-1.7.10-universal.jar

Step1：Put one liquid cell in the machine.
Step2：Put one empty cell in the machine.
Step3：this cell will be full with the liquid and this liquid will be consumed.
Step4：Put one liquid cell in the machine again，this cell also be full,but the liquid can't be consumed.

**Comment by mezz** [comment]
Thanks for the report!
Fixed in the latest unstable build, and just submitted a fixed version 3.5.6 to Curse.

**Comment by Antecer** [comment]
There is a serious BUG with the forestry_1.7.10-3.5.6.15.jar

because my server Crash!

---- Minecraft Crash Report ----
>
> // Everything's going to plan. No, really, that was supposed to happen.
>
>
>> Time: 15-5-10 下午4:26
>
> Description: Exception in server tick loop
>
>
>> Duplicate Mods:
>
> Forestry :
>> F:\GameSoft\Minecraft我的世界\1.7.10原版服务器\mods\[F]forestry_1.7.10-3.6.0.546-unstable.jar
>
> Forestry :
>> F:\GameSoft\Minecraft我的世界\1.7.10原版服务器\mods\[F]forestry_1.7.10-3.5.6.15.jar
>
>
>> cpw.mods.fml.common.DuplicateModsFoundException
>
> at cpw.mods.fml.common.Loader.identifyDuplicates(Loader.java:401)
>
> at cpw.mods.fml.common.Loader.identifyMods(Loader.java:363)
>
> at cpw.mods.fml.common.Loader.loadMods(Loader.java:487)
>
> at
>> cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
>
> at
>> cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
>
> at
>> net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
>
> at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
>
> at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
>
>
>>
>> A detailed walkthrough of the error, its code path and all known details
>> is as follows:
>
>
>> ---------------------------------------------------------------------------------------
>
>
>> -- System Details --
>
> Details:
>
> Minecraft Version: 1.7.10
>
> Operating System: Windows 8.1 (amd64) version 6.3
>
> Java Version: 1.8.0_45, Oracle Corporation
>
> Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle
>> Corporation
>
> Memory: 4670417200 bytes (4454 MB) / 4811390976 bytes (4588 MB) up to
>> 6681526272 bytes (6372 MB)
>
> JVM Flags: 2 total; -Xms4G -Xmx7G
>
> AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
>
> IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
>
> FML: MCP v9.05 FML v7.10.138.1400 Minecraft Forge 10.13.3.1400 29 mods
>> loaded, 0 mods active
>
> mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)
>
> FML{7.10.138.1400} [Forge Mod Loader]
>> (forge-1.7.10-10.13.3.1400-1.7.10-universal.jar)
>
> Forge{10.13.3.1400} [Minecraft Forge]
>> (forge-1.7.10-10.13.3.1400-1.7.10-universal.jar)
>
> appliedenergistics2-core{rv2-stable-1} [AppliedEnergistics2 Core]
>> (minecraft.jar)
>
> OmniOcularCore{1.0} [Omni Ocular Core] (minecraft.jar)
>
> CodeChickenCore{1.0.6.43} [CodeChicken Core] (minecraft.jar)
>
> NotEnoughItems{1.0.4.106} [Not Enough Items]
>> ([NEI]NotEnoughItems-1.7.10-1.0.4.106-universal.jar)
>
> OpenEye{0.6} [OpenEye] (OpenEye-0.6-1.7.10.jar)
>
> <CoFH ASM>{000} [CoFH ASM] (minecraft.jar)
>
> appliedenergistics2{rv2-stable-1} [Applied Energistics 2]
>> ([AE]appliedenergistics2-rv2-stable-1.jar)
>
> BuildCraft|Compat{6.4.0} [BuildCraft Compat]
>> ([BC+]buildcraft-compat-6.4.2.jar)
>
> BuildCraft|Silicon{6.4.14} [BC Silicon] ([BC]buildcraft-6.4.14.jar)
>
> BuildCraft|Core{6.4.14} [BuildCraft] ([BC]buildcraft-6.4.14.jar)
>
> BuildCraft|Transport{6.4.14} [BC Transport] ([BC]buildcraft-6.4.14.jar)
>
> BuildCraft|Builders{6.4.14} [BC Builders] ([BC]buildcraft-6.4.14.jar)
>
> BuildCraft|Energy{6.4.14} [BC Energy] ([BC]buildcraft-6.4.14.jar)
>
> BuildCraft|Factory{6.4.14} [BC Factory] ([BC]buildcraft-6.4.14.jar)
>
> Forestry{3.5.6.15} [Forestry for Minecraft]
>> ([F]forestry_1.7.10-3.5.6.15.jar)
>
> Forestry{3.6.0.546-unstable} [Forestry for Minecraft]
>> ([F]forestry_1.7.10-3.6.0.546-unstable.jar)
>
> AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels]
>> ([IC+]AdvancedSolarPanel-1.7.10-3.5.1.jar)
>
> IC2{2.2.719-experimental} [IndustrialCraft 2]
>> ([IC]industrialcraft-2-2.2.719-experimental.jar)
>
> LogisticsPipes{0.8.3.118} [Logistics Pipes]
>> ([LP]logisticspipes-0.8.3.118.jar)
>
> NBTEdit{1.7.2.2} [In-game NBTEdit] ([NEI+]NBTEdit_1.7.10.jar)
>
> OmniOcular{@VERSION@} [Omni Ocular]
>> ([NEI+]OmniOcular-1.7.10-1.0build51.jar)
>
> Waila{1.5.10} [Waila] ([NEI+]Waila-1.5.10_1.7.10.jar)
>
> PowerConverters{1.7.10_3.2.2-jenkins.70} [Power Converters]
>> ([PC]PowerConverters-1.7.10_3.2.2-jenkins.70.jar)
>
> CoFHCore{1.7.10R3.0.2} [CoFH Core] ([TE]CoFHCore-[1.7.10]3.0.2-262.jar)
>
> ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion]
>> ([TE]ThermalExpansion-[1.7.10]4.0.1-182.jar)
>
> ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation]
>> ([TE]ThermalFoundation-[1.7.10]1.0.0-81.jar)
>
> Profiler Position: N/A (disabled)
>
> Is Modded: Definitely; Server brand changed to 'fml,forge'
>
> Type: Dedicated Server (map_server.txt)
>
>
2015-05-10 9:02 GMT+08:00 mezz <notifications@github.com>:

**Comment by mezz** [comment]
You have 2 forestry jars, please delete one.

**Comment by Antecer** [comment]
I'm sorry，I didn't notice that.
but when i delete the other one,the Server also Crashed !

this is my crash-reports:

> ---- Minecraft Crash Report ----
>
> // Uh... Did I do that?
>
>
>> Time: 15-5-10 下午4:38
>
> Description: Exception in server tick loop
>
>
>> java.lang.NumberFormatException: For input string: "0.0"
>
> at java.lang.NumberFormatException.forInputString(Unknown Source)
>
> at java.lang.Integer.parseInt(Unknown Source)
>
> at java.lang.Integer.parseInt(Unknown Source)
>
> at forestry.plugins.PluginApiculture.doInit(PluginApiculture.java:304)
>
> at forestry.plugins.PluginManager.runInit(PluginManager.java:285)
>
> at forestry.core.ForestryCore.init(ForestryCore.java:114)
>
> at forestry.Forestry.init(Forestry.java:112)
>
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>
> at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>
> at java.lang.reflect.Method.invoke(Unknown Source)
>
> at
>> cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
>
> at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
>
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>
> at java.lang.reflect.Method.invoke(Unknown Source)
>
> at
>> com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
>
> at
>> com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
>
> at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
>
> at
>> com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
>
> at com.google.common.eventbus.EventBus.post(EventBus.java:275)
>
> at
>> cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
>
> at
>> cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
>
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>
> at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>
> at java.lang.reflect.Method.invoke(Unknown Source)
>
> at
>> com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
>
> at
>> com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
>
> at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
>
> at
>> com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
>
> at com.google.common.eventbus.EventBus.post(EventBus.java:275)
>
> at
>> cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
>
> at cpw.mods.fml.common.Loader.initializeMods(Loader.java:713)
>
> at
>> cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
>
> at
>> cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
>
> at
>> net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
>
> at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
>
> at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
>
>
>>
>> A detailed walkthrough of the error, its code path and all known details
>> is as follows:
>
>
>> ---------------------------------------------------------------------------------------
>
>
>> -- System Details --
>
> Details:
>
> Minecraft Version: 1.7.10
>
> Operating System: Windows 8.1 (amd64) version 6.3
>
> Java Version: 1.8.0_45, Oracle Corporation
>
> Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle
>> Corporation
>
> Memory: 4748976360 bytes (4528 MB) / 5011668992 bytes (4779 MB) up to
>> 6681526272 bytes (6372 MB)
>
> JVM Flags: 2 total; -Xms4G -Xmx7G
>
> AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
>
> IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
>
> FML: MCP v9.05 FML v7.10.138.1400 Minecraft Forge 10.13.3.1400 28 mods
>> loaded, 28 mods active
>
> mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)
>> Unloaded->Constructed->Pre-initialized->Initialized
>
> FML{7.10.138.1400} [Forge Mod Loader]
>> (forge-1.7.10-10.13.3.1400-1.7.10-universal.jar)
>> Unloaded->Constructed->Pre-initialized->Initialized
>
> Forge{10.13.3.1400} [Minecraft Forge]
>> (forge-1.7.10-10.13.3.1400-1.7.10-universal.jar)
>> Unloaded->Constructed->Pre-initialized->Initialized
>
> appliedenergistics2-core{rv2-stable-1} [AppliedEnergistics2 Core]
>> (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
>
> OmniOcularCore{1.0} [Omni Ocular Core] (minecraft.jar)
>> Unloaded->Constructed->Pre-initialized->Initialized
>
> CodeChickenCore{1.0.6.43} [CodeChicken Core] (minecraft.jar)
>> Unloaded->Constructed->Pre-initialized->Initialized
>
> NotEnoughItems{1.0.4.106} [Not Enough Items]
>> ([NEI]NotEnoughItems-1.7.10-1.0.4.106-universal.jar)
>> Unloaded->Constructed->Pre-initialized->Initialized
>
> OpenEye{0.6} [OpenEye] (OpenEye-0.6-1.7.10.jar)
>> Unloaded->Constructed->Pre-initialized->Initialized
>
> <CoFH ASM>{000} [CoFH ASM] (minecraft.jar)
>> Unloaded->Constructed->Pre-initialized->Initialized
>
> appliedenergistics2{rv2-stable-1} [Applied Energistics 2]
>> ([AE]appliedenergistics2-rv2-stable-1.jar)
>> Unloaded->Constructed->Pre-initialized->Initialized
>
> CoFHCore{1.7.10R3.0.2} [CoFH Core] ([TE]CoFHCore-[1.7.10]3.0.2-262.jar)
>> Unloaded->Constructed->Pre-initialized->Initialized
>
> BuildCraft|Core{6.4.14} [BuildCraft] ([BC]buildcraft-6.4.14.jar)
>> Unloaded->Constructed->Pre-initialized->Initialized
>
> BuildCraft|Compat{6.4.0} [BuildCraft Compat]
>> ([BC+]buildcraft-compat-6.4.2.jar)
>> Unloaded->Constructed->Pre-initialized->Initialized
>
> BuildCraft|Transport{6.4.14} [BC Transport] ([BC]buildcraft-6.4.14.jar)
>> Unloaded->Constructed->Pre-initialized->Initialized
>
> BuildCraft|Silicon{6.4.14} [BC Silicon] ([BC]buildcraft-6.4.14.jar)
>> Unloaded->Constructed->Pre-initialized->Initialized
>
> BuildCraft|Builders{6.4.14} [BC Builders] ([BC]buildcraft-6.4.14.jar)
>> Unloaded->Constructed->Pre-initialized->Initialized
>
> BuildCraft|Energy{6.4.14} [BC Energy] ([BC]buildcraft-6.4.14.jar)
>> Unloaded->Constructed->Pre-initialized->Initialized
>
> BuildCraft|Factory{6.4.14} [BC Factory] ([BC]buildcraft-6.4.14.jar)
>> Unloaded->Constructed->Pre-initialized->Initialized
>
> IC2{2.2.719-experimental} [IndustrialCraft 2]
>> ([IC]industrialcraft-2-2.2.719-experimental.jar)
>> Unloaded->Constructed->Pre-initialized->Initialized
>
> Forestry{3.5.6.15} [Forestry for Minecraft]
>> ([F]forestry_1.7.10-3.5.6.15.jar)
>> Unloaded->Constructed->Pre-initialized->Errored
>
> AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels]
>> ([IC+]AdvancedSolarPanel-1.7.10-3.5.1.jar)
>> Unloaded->Constructed->Pre-initialized->Initialized
>
> ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation]
>> ([TE]ThermalFoundation-[1.7.10]1.0.0-81.jar)
>> Unloaded->Constructed->Pre-initialized->Initialized
>
> ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion]
>> ([TE]ThermalExpansion-[1.7.10]4.0.1-182.jar)
>> Unloaded->Constructed->Pre-initialized->Initialized
>
> LogisticsPipes{0.8.3.118} [Logistics Pipes]
>> ([LP]logisticspipes-0.8.3.118.jar)
>> Unloaded->Constructed->Pre-initialized->Initialized
>
> NBTEdit{1.7.2.2} [In-game NBTEdit] ([NEI+]NBTEdit_1.7.10.jar)
>> Unloaded->Constructed->Pre-initialized->Initialized
>
> Waila{1.5.10} [Waila] ([NEI+]Waila-1.5.10_1.7.10.jar)
>> Unloaded->Constructed->Pre-initialized->Initialized
>
> OmniOcular{@VERSION@} [Omni Ocular]
>> ([NEI+]OmniOcular-1.7.10-1.0build51.jar)
>> Unloaded->Constructed->Pre-initialized->Initialized
>
> PowerConverters{1.7.10_3.2.2-jenkins.70} [Power Converters]
>> ([PC]PowerConverters-1.7.10_3.2.2-jenkins.70.jar)
>> Unloaded->Constructed->Pre-initialized->Initialized
>
> AE2 Version: stable rv2-stable-1 for Forge 10.13.2.1291
>
> CoFHCore: -[1.7.10]3.0.2-262
>
> ThermalFoundation: -[1.7.10]1.0.0-81
>
> ThermalExpansion: -[1.7.10]4.0.1-182
>
> Profiler Position: N/A (disabled)
>
> Is Modded: Definitely; Server brand changed to 'fml,forge'
>
> Type: Dedicated Server (map_server.txt)
>
>
2015-05-10 16:36 GMT+08:00 mezz <notifications@github.com>:

**Comment by Nirek-K** [comment]
You need to change the secondprincess option in apicutlure.conf to read 0 instead of 0.0, it got changed to a float in one of the unstables which didn't get pulled into the bugfix

**Comment by mezz** [comment]
It is a bad idea to go from unstable build to stable right now. There will be more problems. Please use unstable if you have used it before.

**Comment by Antecer** [comment]
Thanks! After change the config,my server work fine.

2015-05-10 16:44 GMT+08:00 Nirek-K <notifications@github.com>:
