### ISSUE TITLE
Add legacy code to allow Binnies mod work

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [ForestryMC/ForestryMC#655]
I like Forestry, I like Binnie's mod. Both together are awesome. Problem is, with the latest update, Binnie's mod don't work anymore. And Binnie is updating really slow, so either ditch Binnies mod until he updates, or stay with older Forestry version.

I don't know how feasible it is, but would it be possible to add some sort of legacy code, to allow BInnie mod to work until further notice?

Crashes I'm getting are these: http://hastebin.com/royeyotagu.1c

**Comment by mezz** [comment]
In this case I deprecated an interface more than half a year ago (warned that it would be deleted), and after all that time Binnie's mods are still depending on it.   
I am making efforts to keep backward compatibility and waited a generous length of time, but it is not possible to move forward without ever changing the API.
I have asked Binnie in the past if I can contribute bug fixes to his mod, but he is not around often and difficult to get a hold of.

**Comment by mezz** [comment]
I gave in, Binnie never seems to update. Added back ISpecialInventory to the API https://github.com/ForestryMC/ForestryMC/commit/a2944ce4e6af7a1d0746c8e9e466189bee703ce1
