### ISSUE TITLE
Custom tooltips no longer working

### ISSUE THREAD

**Issue by Adaptivity** [ForestryMC/ForestryMC#657]
Not sure since version it's so but custom tooltips not working on 3.5.6 and latest unstable. Also, @mezz  can you make tooltips to work with addons? Similar like you've done with allele strings.

Some more broken stuff:
1) Maturity custom strings no longer working too...
2) Metabolism strings missing.

Also, I need custom tooltip names for *for.gui.flyer*

**Comment by mezz** [comment]
Thanks for the report!
Can you screenshot some things that are broken?
I'm not 100% sure what things you are referring to and it's difficult for me to hunt down since I only read English.

I will be adding more API helpers with localization support as time goes on, but it's a slow process.

**Comment by Adaptivity** [comment]
Just try to add custom strings into en_US.lang: *forestry.allele.maturity.anyadjective (slowest, slower etc.)* and *for.tooltip.worker.anyadjective (slowest, slower etc.)*

**Comment by mezz** [comment]
Cool, all issues should be fixed. Let me know if you find anything else.
