### ISSUE TITLE
Looking to Talk to Someone About Forestry Screenshots for a Guidebook

### ISSUE THREAD

**Issue by heuronaut** [ForestryMC/ForestryMC#659]
Sorry to post here, I know this is for more technical issues, but I'm looking for someone to talk to about getting some screenshots of Forestry to use in a Minecraft guidebook. I'm an author, and this book is aiming to be finished in the next few days. If anyone could help me, even if you have some screenshots of your own, or if you know who I could talk to, please let me know.

Thanks guys
-heuronaut

**Comment by mezz** [comment]
Sorry for being defensive, but this request makes me a bit uncomfortable. 
Didn't you make things in the process of writing the guide book?
What role does Forestry play, and what are you looking for in a screenshot?
Maybe you can explain more?

**Comment by heuronaut** [comment]
The book is actually complete now, unfortunately we couldn't include your
mod, though we wanted to. I'll expain why we asked for help anyways, though.

We certainly did shoot a lot of our own shots, but think about it this way:
there were 80 mods in the book, each one of which you have to learn and
build in and then take the shots. That's a minimum of 2 hours and probably
more for each mod to get a truly great shot that we think would promote the
mod well enough. That's at least 160 hours, not including any writing,
editing, finding of mods, general research, designing, back and forth with
the publisher and everything else going into a book.

It's just me doing all of this work plus one designer who doesn't play, and
I don't make very much on these books or have very much time to meet
deadlines.

I'd absolutely love to have enough time to go in and play every single mod
thoroughly to get my own shots, but this book is not about how to play each
mod, it's about profiling a series of mods and trying to encourage people
to get into mods and play them. We wanted to make it a celebration of the
mod community and to really try and get you guys some traffic and some more
attention.

With that in mind not only is there no way for me to spend enough time with
each mod to do this and still be able to complete the book in time for the
publisher (and we gotta make a decent wage, food is expensive!), most of
the shots I will take will be nothing compared to what people who have
spent many countless hours in the mod could do.

I really wanted to include Forestry, and did go in and try to take my own
shots, but I simply couldn't get ones I was happy enough with on the short
deadline, so we had to cut your segment. I'd love to include you for
another book in some way, we do a lot of Minecraft guides, so if you are
interested let me know. If not, we understand.

Thanks

-Trevor

**Comment by mezz** [comment]
I'm sorry you have to work under such poor conditions and a short deadline.
Unfortunately I only work in my spare time, so I can't respond with any urgency. 

Perhaps with more planning we can help out in the future.

**Comment by MysteriousAges** [comment]
Honestly, if you're looking for Forestry-related screenshots, you might want to ask on the Feed the Beast subreddit - you'll find a lot of active players there with an inclination towards showing off their builds.

www.reddit.com/r/feedthebeast/
