### ISSUE TITLE
Electrical Engine not functioning

### ISSUE THREAD

**Issue by SynfulChaot** [ForestryMC/ForestryMC#660]
In my current test world, the Forestry Electrical Engine, while registering EU energy input from connected EU sources, does not actually store or output any RF to connected machines.  I have connected EU sources both directly and via cables for input.  I have also connected various BC and TE machines and energy cells, both directly connected and connected via both TD fluxducts and BC kinesis pipes.  In no combination will the Electrical Engine actually produce any RF.

I will note that I am testing on the most recent version of the mods (forestry_1.7.10-3.5.6.15 and industrialcraft-2-2.2.719-experimental).

**Comment by mezz** [comment]
Thanks for the report!
Confirmed, taking a look.

**Comment by mezz** [comment]
Never mind, it works fine. I just forgot to use a lever.
Did you activate it with a lever?

**Comment by SynfulChaot** [comment]
Yeah.  I totally forgot they needed a redstone signal.  Just tested and confirmed (l)user error.

>.<

**Comment by mezz** [comment]
Cool! I'll keep this in mind for when I overhaul error messages.

**Comment by SynfulChaot** [comment]
Probably not a bad idea.  Dynamos spoiled me.

**Comment by mezz** [comment]
Added a new error message, check it out at the bottom here: https://github.com/ForestryMC/ForestryMC/issues/666
