### ISSUE TITLE
Refactor error states, display multiple error states

### ISSUE THREAD

**Issue by mezz** [ForestryMC/ForestryMC#666]
Forestry machines can only have one error state at at time, which greatly complicates the error logic.
It would be better to have multiple error states at a time, with an empty list indicating that everything is "OK".
We could also display all the errors on the left of the machine, instead of just one on the right.

This is a fairly big project, and involves refactoring all the error handling code. It's worth doing, the current code has difficult bugs due to the complexity.

The current code also has a network cost: machines send their error state every time they're updated, sometimes multiple times per work cycle. Machines should only send error states over the network at the end of their update.

**Comment by mezz** [comment]
Done! It's in the latest unstable.

![2015-05-17_01 08 37](https://cloud.githubusercontent.com/assets/916092/7669622/b65ca8ca-fc32-11e4-9f7c-aaae9fa451ec.png)

![2015-05-16_22 08 44](https://cloud.githubusercontent.com/assets/916092/7669623/c3483ce8-fc32-11e4-8a46-40fbb24ec5e8.png)

**Comment by CovertJaguar** [comment]
And you said this would be hard!

**Comment by SirSengir** [comment]
My original system was just way too horrible. This looks much, much nicer!

**Comment by SynfulChaot** [comment]
This is wonderful!
