### ISSUE TITLE
Fluxed Bee/Beealyzer crash

### ISSUE THREAD

**Issue by scain001** [ForestryMC/ForestryMC#667]
When putting a fluxed queen into a the 3 slot in a beealyzer the game crashes, tested on both single and mulitplayer infinity pack.  Also the secondary output used to be a fluxed electrum nugget, now there is a timer indicating a secondary output but no item is listed.

**Comment by mezz** [comment]
Thanks for the report!
Can you post the crash report to http://gist.github.com?

**Comment by scain001** [comment]
Sure, I'm new to bug reporting.  Hope I did this correctly.

https://gist.github.com/scain001/047905f428cd284d1891

**Comment by mezz** [comment]
It looks like this is something wrong with the Magic Bees mod.
I'll put a check on Forestry's side so it does not crash, but it looks like the bee has a missing product.
Please add a new issue here: https://github.com/MagicBees/MagicBees/issues
