### ISSUE TITLE
I found a bee, is this a bug

### ISSUE THREAD

**Issue by Harus** [ForestryMC/ForestryMC#670]

**Comment by leagris** [comment]
What is your issue about?
What kind of bee did you found?
How did you found it?
What is the ordictionary name of this bee?
Witch mod does it belong to?
How is it an issue or worth a bug report?

**Comment by mezz** [comment]
Bees are flying insects closely related to wasps and ants, and are known for their role in pollination and for producing honey and beeswax. Bees are a monophyletic lineage within the superfamily Apoidea, presently considered as a clade Anthophila.

A bug is, formally, an insect of the order Hemiptera, known as the "true bugs" which does not include bees. Informally, it can refer to any insect, including bees.

:bee:

**Comment by leagris** [comment]
:wink:
