### ISSUE TITLE
Maximum flowering allele removed?

### ISSUE THREAD

**Issue by bdew** [ForestryMC/ForestryMC#677]
Maximum flowering allele seems to have went MIA in 6afee76beebd6a475bc72a2063b55da030adfb4f. Is this intended?

Also it's still refered to in [legacy conversion](https://github.com/ForestryMC/ForestryMC/blob/7b476b39c27bff4bd69b83d4ec54805f0517b8b2/src/main/java/forestry/core/genetics/alleles/Allele.java#L325) which is probably not a good idea

**Comment by mezz** [comment]
That's a mistake, thanks. 
I think its value is insanely high, but I did not mean to remove it.

**Comment by SirSengir** [comment]
If the legacy-stuff is what I think it is, it can be removed. I don't think there is a snowball's chance in hell to upgrade from a map using the int-IDs for alleles to a current version. I changed that back when ExtraBees first became a thing.

**Comment by mezz** [comment]
Cool, I just deprecated it since I wasn't sure. I'll remove it, yay.
