### ISSUE TITLE
Buildcraft Builder Support

### ISSUE THREAD

**Issue by LouisHutch** [ForestryMC/ForestryMC#678]
Currently, The Builder from Buildcraft is unable to place down Forestry Tile Entitys. This is due to the builder operates by only placing down tile entities which are 'whitelisted'.

It would be really useful for forestry to add support for the builder as it has many uses such as it is helpful for building the multifarms etc. Support can be added either through forestry itself or through BC Compat I believe.

Buildcraft 6.4.15
Buildcraft Compat 6.4.0
Forestry: 3.5.6.15

![2015-05-21_14 16 00](https://cloud.githubusercontent.com/assets/9326429/7749408/325e25d0-ffc5-11e4-9d7b-a50c738c10b9.png)
Left = Blocks recorded by the Architect table, Right = Blocks placed by the Builder

**Comment by mezz** [comment]
Thanks for the report!
I think this is best for BC Compat. Can you make a new issues and link back here?
https://github.com/BuildCraft/BuildcraftCompat/issues

Ideally the builder should be able to copy all Forestry blocks.
