### ISSUE TITLE
Worktable causes dupe bug when upgrading EnderIO basic capacitor banks

### ISSUE THREAD

**Issue by MatthiasMann** [ForestryMC/ForestryMC#679]
The worktable will only consume basic cap banks which have 0 energy stored.
If you have one with 0 energy and one with energy - the one with energy stays in the work table's inventory.

At the same time - having only basic cap banks in the inventory the crafting doesn't work.

PS: as that came up in the chat - the crafting recipe requires 2 basic capacitor banks.

This is the EnderIO recipe:
https://github.com/SleepyTrousers/EnderIO/blob/master/src/main/java/crazypants/enderio/machine/UpgradeCapBankRecipe.java
https://github.com/SleepyTrousers/EnderIO/blob/26ea2388e1e40a451b43e0392aef8f9d2cb21e74/src/main/java/crazypants/enderio/machine/MachineRecipes.java#L150

**Comment by CovertJaguar** [comment]
Generally, if a crafter isn't presenting itself as a player using a crafting bench (fake players with fake inventories and fake crafting bench grid) to the recipe...weird stuff will happen.

**Comment by mezz** [comment]
Thanks for the report!
Fixed in the latest unstable build.
