### ISSUE TITLE
Server crashing due to aviaries

### ISSUE THREAD

**Issue by toma678** [ForestryMC/ForestryMC#681]
Hi,

Whenever I load the server, the game crashes, traces back to the field (of an array?) "temperature" not being found. This leads me to believe it's an error possibly between Bo'P and Foresty.

Thanks,

Toma

http://pastebin.com/1cu8NJ1w <-- Error log

**Comment by mezz** [comment]
Thanks for the report!
Can you post a full crash report (not the server log)? 
BiomeGenBase is part of Minecraft and has a public field called temperature... there's no pretty much way it's missing. 
Are you using Cauldron or something like that?

**Comment by CovertJaguar** [comment]
@mezz I don't remember the exact details, but I know some of those fields/methods on BiomeGenBase are client only. Maybe that's what's happening?

**Comment by mezz** [comment]
That's the first thing I thought of too, but `temperature` and its getter are available on both sides.
`getFloatRainfall()` is marked @ClientOnly, but the field `rainfall` is both sides.

**Comment by toma678** [comment]
Apologies for the wrong log, was a long night last night.

Correct log:
http://pastebin.com/u0LGsWY5

Modlist:

AE2
Bibliocraft
Binnie mods
Biomes O' Plenty
Botania
Buildcraft
ChickenChunks (CodeChickenCore)
Thermal Expansion/Foundation/Redstone Arsenal (CoFH Core)
EnderIO
EnderStorage
Forestry
Galacticraft (MicDoodleCore, Planets)
Iron Chests
Jabba
Mantle
MFR
NEI
PowerConverters
Railcraft
Thaumcraft
Twilight Forest

**Comment by CovertJaguar** [comment]
Well I see Java 7 without permgen flags...could be the issue.

**Comment by toma678** [comment]
I guess now is a good a time to upgrade to Java 8 and take permgen out of the equation then... I'll post back when I've got the new installation running, and have tested the server

**Comment by toma678** [comment]
Exactly the same issue. When it tries to update the block, it dies because the "temperature" field is missing. I've set 256MB Permgen, full running command below:

java -Xms1536M -Xmx1536M -XX:MaxPermSize=256M -jar forge-1.7.10-10.13.2.1263-universal.jar --nogui

**Comment by mezz** [comment]
I asked around for ideas and concluded that another mod must change BiomeGenBase's temperature field with assembly or an access transformer. Forge has left the field untouched.
The quickest way to figure this out is to make a copy of your world and remove half your mods, and keep narrowing down until you find the one causing the problem. Once you find it, I can help yell at them :+1: 

Also someone pointed out you should update AE2 to rv2 or it will crash with EnderIO down the line. https://github.com/SleepyTrousers/EnderIO/issues/2042

**Comment by bdew** [comment]
Um, maybe i'm missing something but his crash shows an attempt to access the unobfuscated name of that field?

He does have the right (not -dev) forestry jar in the log, but this class is part of the API. Might be some mod packaging the API without reobfuscating it correctly.

**Comment by CovertJaguar** [comment]
@bdew That actually makes a lot of sense. Now all that remains is finding which mod is doing that.

**Comment by leagris** [comment]
> aviaries
Did Forestry add :penguin: Pigeons breeding lately? :innocent:

**Comment by CovertJaguar** [comment]
@toma678 I could probably tell which mod was the culprit if we had a FML log instead of just a crash log.

**Comment by toma678** [comment]
Apologies, I've been very busy, I should have the answers by tomorrow. Sorry to be a pain.

**Comment by toma678** [comment]
http://toma678.com/fml-server-3.log

Apologies for the wait. The main error trace says something about IBee..?

**Comment by bdew** [comment]
> 22:51:27] [Server thread/ERROR] [Forestry/]: Forestry API error: IBee is loaded from jar:file:/home/mc/serv/mods/forestry_1.7.10-3.6.0.535-unstable-api.jar!/forestry/api/apiculture/IBee.class

The forestry_whatever-api.jar is meant for developers, not for installing in normal MC. Remove it.

**Comment by toma678** [comment]
Seems to have fixed the issue, thanks for your help guys!
