### ISSUE TITLE
Have Forestry Machines keep their Inventory when broken

### ISSUE THREAD

**Issue by mezz** [ForestryMC/ForestryMC#682]
It would be convenient to pick up a Machine full of bees and honey and move it without needing 10 pipettes and an extra inventory.
Strongboxes and portable tanks are pretty cheap compared to Forestry Machines, so they wont be overpowered if people use them as portable storage.

**Comment by Vexatos** [comment]
This should only apply to the storage, e.g. Lepidopterologist's Chests. Actual machine should drop their contents when broken. Also, I'd say shift-right click the chests with a wrench to make them drop _with_ their contents, just like most mods do it. I do not think normal machines should keep their contents as it just doesn't make much sense. Comparing against mods that do have this feature is a bad idea, in my o(pi)nion.

**Comment by mezz** [comment]
I suppose. How about adding something like the JABBA dolly or Mekanism cardboard box?
Currently, moving a full carpenter across a room is a pretty big task.

**Comment by SynfulChaot** [comment]
Having an in-mod method to do so might be nice.  Not everyone who runs Forestry also runs JABBA, after all.

**Comment by mezz** [comment]
Closing this, it may come up again but I doubt it will end up being implemented as described here.
