### ISSUE TITLE
Multifarm "no power"

### ISSUE THREAD

**Issue by CourtArtanis** [ForestryMC/ForestryMC#684]
Hi,
For some reason my farm keeps saying "no power" even though it's connected to a leadstone energy cell (via EnderIO Energy Conduit) the cell is outputting energy, and being charged enough.

It's getting 200rf/t, is this enough? Or am I missing something?

http://i.imgur.com/igjz275.png

**Comment by mezz** [comment]
Please backup your world and try [the latest unstable build](http://jenkins.ic2.player.to/job/Forestry_Dev/). It should fix that problem, let me know!

**Comment by CourtArtanis** [comment]
For reference, I'm using the latest recommended build forestry_1.7.10-3.5.6.15.
Updating to the latest Unstable forestry_1.7.10-3.6.0.568 fixed the problem.

Thanks @mezz 

For anyone else, binnie-mods needs updating to the latest "pre-8" in order to be compatible with the latest unstable Forestry build.

**Comment by mezz** [comment]
Glad it works now, thanks for reporting back.
