### ISSUE TITLE
Extractor Mk3 no longer extracts saplings from Multifarm

### ISSUE THREAD

**Issue by CourtArtanis** [ForestryMC/ForestryMC#685]
Hi,
After updating to the unstable build as per #684 , my LP Extractor mk3 module will no longer extract saplings from the farm hatch. I also tried changing the extract orientation to see if that would change anything.
The module happily extracts sand/logs/apples, but leaves the Apple Oak saplings in the farm inventory. I've also tried an Advanced module to specify extraction. No change.

Worth noting: The saplings also will no longer drop from a hopper into a JABBA barrel, this worked prior to the update (Farm Extract via LP > vanilla hopper > JABBA)

Any ideas?
Thanks

**Comment by mezz** [comment]
Hi thanks for the report!
Did you find out what was wrong?

**Comment by CourtArtanis** [comment]
I didn't @mezz no, I am trying a dev LP build to see if there's any change, but apart from that I have no idea :(

**Comment by mezz** [comment]
I'm not entirely clear on what you're doing. Are you trying to extract from the saplings area of the farm inventory? Nothing should be able to pull from that, only add to it. Once it's full, saplings will go to the output area.

Which of these scenarios are you describing?

Trying to pull items from the farm's input areas:   `You can't do that. We can discuss.`
Only LP has the issue, some other pipe from another mod works:   `Something is broken with LP.`
All mods fail to extract saplings from the farm's output area:  `Something is broken with Forestry.`

I hope this can clarify things a little.

**Comment by CourtArtanis** [comment]
It was my fault, for some reason the route set for saplings had unset(?) itself, so the saplings had nowhere to go, therefore the extractor wasn't pulling the saplings from the output inventory. It was a stupid mistake, apologies for wasting time.

**Comment by mezz** [comment]
Ah interesting, glad you fixed it. Thanks for reporting back!
