### ISSUE TITLE
colored wood recipies not working

### ISSUE THREAD

**Issue by TheMrCaveman** [ForestryMC/ForestryMC#690]
All slab recipie from colored wood slabs return oak wood slabs
fences doors and so on do excactly the same. so no matter what wood i use it always retuns in oak wood from crafting table!

**Comment by mezz** [comment]
Thanks for the report!
Which version of Forestry are you using? It works fine in the latest dev build.

**Comment by TheMrCaveman** [comment]
Hey, we are using 3.5.6.15 and dev builds do not work here because we have binnies mod installed as well.

**Comment by Landrash** [comment]
@TheMrCaveman Suggestion is that you make a new instance with your current mods, excluding the incompatible ones and try with the latest dev build. Test the same thing and report back since it's generally hard to recreate other instances completely.

**Comment by TheMrCaveman** [comment]
okay did that, tried latest dev version. Same problem, so i decided to see if it is caused by forge. And tried all builds from 1343 and up. But this did not fix it. Also tried recent cauldron builds but that also did not fix it.

**Comment by mezz** [comment]
I got a chance to watch the video and those planks are from another mod. Looks like Extra Trees.
[Please resubmit this issue to Binnie's bug tracker here.](https://bitbucket.org/binnie567/binnie-mods/issues?status=new&status=open)
