### ISSUE TITLE
Ethanol doesn't work on EnderIO Combustion Engine

### ISSUE THREAD

**Issue by RaineAndrews** [ForestryMC/ForestryMC#693]
Before you say this should be in EnderIO, hear me out.  It is only Ethanol that isn't going into it, all other fluids valid for it are working as intended.

Related Mods:

Forestry *6.15
Forge *3.142
EnderIO *8.381

**Comment by RaineAndrews** [comment]
updated to latest forge (.1420) in hopes it would help.  It didn't.

**Comment by mezz** [comment]
I think EnderIO uses Buildcraft's fuel registry for that. Are you using a version of BC that is compatible with Forestry (BC 6)?

**Comment by RaineAndrews** [comment]
I'm not using buildcraft.  Is that the problem?

**Comment by mezz** [comment]
That's probably the issue.

@tterrag1098 is there a way for Forestry to add ethanol as a fuel for EnderIO without depending on BuildCraft?

Here's the previous discussion https://github.com/ForestryMC/ForestryMC/issues/309 and https://github.com/SleepyTrousers/EnderIO/issues/1187

**Comment by mezz** [comment]
tonius responded on IRC:
> IMC messages https://github.com/SleepyTrousers/EnderIO/blob/master/src/main/java/crazypants/enderio/api/IMC.java#L102

I'll add it as a fuel this way.

**Comment by mezz** [comment]
Found a small issue, made a PR. https://github.com/SleepyTrousers/EnderIO/pull/2530
When Forestry's fix for this is in, it will depend on a future version of EnderIO to work correctly.

**Comment by RaineAndrews** [comment]
So is this a bug, or do I need buildcraft to use ethanol as a fuel?

**Comment by mezz** [comment]
Right now you need Buildcraft, but I'm adding compatibility with EnderIO directly so that you will not need Buildcraft.

**Comment by RaineAndrews** [comment]
Nice!  Thanks a lot :+1:
