### ISSUE TITLE
Backpack oredict is too liberal

### ISSUE THREAD

**Issue by mezz** [ForestryMC/ForestryMC#694]
![fr8zsmo](https://cloud.githubusercontent.com/assets/916092/7903447/a649c534-0791-11e5-8d51-3b77ad8b816b.jpg)

[Post on reddit here](http://www.reddit.com/r/feedthebeast/comments/37zcvo/why_is_there_raw_chicken_in_my_miners_backpack/)

Ideally Forestry should also expose the rules for picking things up in a giant config file, which would work as a blacklist too (solving https://github.com/ForestryMC/ForestryMC/issues/672).

**Comment by saulrh** [comment]
Instead of a single giant config file, could I suggest a sorted config directory? It'd be cool if mod authors could distribute configs with their mods, and per-mod config files would make that straightforward without blocking non-authors. Sorting would be so that submod, pack, or challenge map authors can override each other, but it might also be painful.

**Comment by mezz** [comment]
I really just mean it will be one "rule" per line, like an oredict tag or item name, with a way to set it to enabled or disabled. 
Ideally it wouldn't actually be too long. I'll think about making it more structured once it's working well.

**Comment by mezz** [comment]
I dumped the OreDict for many mods and added better default options.
Here's a ton of OreDict stuff for those interested: https://gist.github.com/mezz/cf5d1a055e0c7fdb6cab

Then added a better config, so that almost everything can be changed.
Here's an example config, with the default settings + several other mods installed. (Items from BoP and Railcraft are added by those mods)
https://gist.github.com/mezz/332db99ae7a60c516caa

The config is based on what's registered in your OreDictionary when it's first created. If you add more mods and want it to try to add them, delete the config and let Forestry recreate it.

Also made Forestry automatically migrate any old backpack configs to the new format, so people who have already set things up will not have to copy them over.
