### ISSUE TITLE
Ticon Autosmelt on Forestry Ores

### ISSUE THREAD

**Issue by LouisHutch** [ForestryMC/ForestryMC#696]
Forestry_1.7.10-3.5.6.15
TConstruct-1.7.10-1.8.5

When I go to mine either Copper ore or Tin ore from Forestry using a Tinkers Construct  pickaxe with the Autosmelt modifier on it, I recieve apatite from the ore instead of the intended ingot. But when I mine Apatite ore with the pick, i still recieve Apatite

It does not happen with Vanilla ores or regular Tinkers Construct ores.
I suspect its some sort of metadata issue.

**Comment by mezz** [comment]
Thanks for the report!

The three ores are all the same base block with different meta. 
They all smelt fine in a furnace, so I think this is an issue with Ticon's implementation.

**Comment by mezz** [comment]
Hmm just found this bug, saying they think it's a Forestry bug.
https://github.com/SlimeKnights/TinkersConstruct/issues/1466

@bonii-xx what is Forestry doing wrong?

**Comment by bonii-xx** [comment]
Block.damageDropped seems to always return copper metadata.

**Comment by mezz** [comment]
Thanks, that saved me some time! 
Tested and fixed in the latest unstable build.
