### ISSUE TITLE
Worktable uncraftable

### ISSUE THREAD

**Issue by thrassoss** [ForestryMC/ForestryMC#698]
A worktable seems uncraftable.  Tried it on a clean install with the following combo's;
 forestry_1.7.10-3.6.0.568-unstable/forge 1.7.10  1352
 forestry_1.7.10-3.6.0.568-unstable/forge 1.7.10  1422
 forestry_1.7.10-3.6.0.577-unstable/forge 1.7.10  1422

**Comment by laz2727** [comment]
TF uncrafter? Maybe that's because Forestry uses custom crafting handler.

**Comment by thrassoss** [comment]
I'm not sure what your asking, Twilight Forest Uncrafting table?
I tried crafting a worktable in a vanilla crafting table along with several other crafting systems in the modpack I play.  I then did a fresh 1.7.10 install and added nothing but forge and foresrty.  I still can't get a Worktable to craft.  It shows no item in the results slot and nothing happens when I click on that slot.

**Comment by mezz** [comment]
Thanks for the report!
Fixed in the latest unstable build.
