### ISSUE TITLE
Crash when using items or machines

### ISSUE THREAD

**Issue by panda2134** [ForestryMC/ForestryMC#700]
I put the mod into my  modpack and i had a strange bug:if i use an item or a machine,minecraft will crash with a line of words:"An error has occurred,the connection was terminated"
here's the log:http://pastebin.ca/3016939

**Comment by mezz** [comment]
Thanks for the report!
Can you post the crash report instead of the server log? Thank you

**Comment by panda2134** [comment]
Sorry,there's no crash report:(
But i can give u my modpack so you can test it yourself

**Comment by mezz** [comment]
Can you please force a crash by pressing F3 + C for 10 seconds while in a single-player world and send the crash log?
Unfortunately you have a crazy number of errors going on and I have no idea how to interpret what is going wrong from the log you posted alone.

**Comment by panda2134** [comment]
But when to force a crash?when the error screen are showing? sorry idk:(

**Comment by mezz** [comment]
If you get an error screen, you have a crash report in your Minecraft folder. It is in the "crash-reports" folder, next to "saves" and "resourcepacks".
If you do not get an error screen, then you can press F3 + C for 10 seconds in a single-player to get one.

**Comment by panda2134** [comment]
![forestry_bug](https://cloud.githubusercontent.com/assets/7239200/8008081/616594ee-0bd2-11e5-8da1-96f7e028344c.PNG)
here's the picture
but no crash report was generated:(
and that's all
do u need the modpack to test the bug?
(p.s. i know what a crash report is :grinning:   i means mc didn't generate a crash report  )

**Comment by mezz** [comment]
You are on a multi-player world?
Please press F3 + C for 10 seconds in a single-player world to generate a crash report...

**Comment by panda2134** [comment]
no i'm sure i'm in a single-player world

**Comment by panda2134** [comment]
https://gist.github.com/mezz/064b9d3cc5751d7f7350

**Comment by mezz** [comment]
Thank you, I was going to ask a 4th time -_-.

**Comment by mezz** [comment]
Try running without Binnie's mods, I'm not sure it's working with the latest Forestry.

**Comment by panda2134** [comment]
still crash...
as before...

**Comment by mezz** [comment]
Try removing Tails as well, it also shows up in your first log.

This crash is not from Forestry alone, I think .

The best way to figure out this kind of problem is copying your world and removing half the mods at a time to see which is causing the crash.

You can also try making a backup and seeing if you have the same problem in the [latest dev version of Forestry](http://jenkins.ic2.player.to/job/Forestry_Dev/).

**Comment by mezz** [comment]
I think I found the problem!
`* CoFHAPI|energy (1.7.10R1.0.0) from funky-locomotion-1.7.10-beta-5c.jar`

Funky Locomotion is using an older version of `CoFHAPI|energy`
Forestry's Engines need `1.7.10R1.0.2`

**Comment by panda2134** [comment]
Thx but how to replace it with a newer version?
2015年6月7日 下午4:35于 "mezz" notifications@github.com写道：

**Comment by panda2134** [comment]
Btw, I removed funky locomotion but it still crash

**Comment by mezz** [comment]
Sorry I'm not able to help you more. 
Since you are making your own modpack, you will have to try removing other mods until it works. 

If you find out anything more, please report back as a new issue and I will work to fix it. 
Thanks!
