### ISSUE TITLE
Newes Forestry are not loading :(

### ISSUE THREAD

**Issue by ferrari314** [ForestryMC/ForestryMC#702]
Hello. Newest Forestry version is broken! Game not loading. Crash text:
Without forestry all working good.

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 05.06.15 20:34
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: buildcraft/core/CreativeTabBuildCraft
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:723)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: buildcraft/core/CreativeTabBuildCraft
	at forestry.pipes.proxy.ProxyPipes.initPropolisPipe(ProxyPipes.java:35)
	at forestry.pipes.proxy.ClientProxyPipes.initPropolisPipe(ClientProxyPipes.java:28)
	at forestry.plugins.PluginPropolisPipe.postInit(PluginPropolisPipe.java:64)
	at forestry.plugins.PluginManager.runPostInit(PluginManager.java:296)
	at forestry.core.ForestryCore.postInit(ForestryCore.java:118)
	at forestry.core.ForestryClient.postInit(ForestryClient.java:41)
	at forestry.Forestry.postInit(Forestry.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:721)
	... 10 more
Caused by: java.lang.ClassNotFoundException: buildcraft.core.CreativeTabBuildCraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 43 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_40, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 932466552 bytes (889 MB) / 1848115200 bytes (1762 MB) up to 3780640768 bytes (3605 MB)
	Mod Pack: Unknown / None
	LiteLoader Mods: 1 loaded mod(s)
          - VoxelMap version 1.2.0
	LaunchWrapper: 37 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: optifine.OptiFineClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: net.minecraftforge.classloading.FluidIdTransformer
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: com.rebelkeithy.dualhotbar.DualHotbarTransformer
          - Transformer: mariculture.fishery.VanillaOverride
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: cofh.asm.CoFHAccessTransformer
          - Transformer: mariculture.core.AccessTransformers
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: cofh.asm.CoFHClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.JoinGamePacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ServerChatPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderCallbackInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LoginSuccessPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CustomPayloadPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ServerCustomPayloadPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ChatPacketTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 1 total; -Xmx4056M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.3.1428 Optifine OptiFine_1.7.10_HD_A4 86 mods loaded, 86 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Forge{10.13.3.1428} [Minecraft Forge] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CodeChickenCore{1.0.6.43} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ivtoolkit{IvToolkit} [1.0.4] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NotEnoughItems{1.0.4.107} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.107-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	debug{1.0} [debug] (Dense_Ores_Mod_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	lightsabers{0.7.1} [Advanced Lightsabers Mod] (Advanced-Lightsaber-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	IC2{2.2.601-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.601-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel-1.7.10-3.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	abm{0.1} [Anime Battle Mod] (Anime-Battle-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	betterstorage{0.9.2.107} [BetterStorage] (BetterStorage.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BiblioCraft{1.9.1} [BiblioCraft] (BiblioCraft[v1.9.1][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1019-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CoFHCore{1.7.10R3.0.2} [CoFH Core] (CoFHCore-[1.7.10]3.0.2-262.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Core{7.0.5} [BuildCraft] (buildcraft-7.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Silicon{7.0.5} [BC Silicon] (buildcraft-7.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Factory{7.0.5} [BC Factory] (buildcraft-7.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Energy{7.0.5} [BC Energy] (buildcraft-7.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Builders{7.0.5} [BC Builders] (buildcraft-7.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Robotics{7.0.5} [BC Robotics] (buildcraft-7.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Transport{7.0.5} [BC Transport] (buildcraft-7.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	cwm{3.0} [Catoon Weapons Mod] (Cartoon-Weapons-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Railcraft{9.6.1.0} [Railcraft] (Railcraft_1.7.10-9.6.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	chisel{2.3.10.37} [Chisel 2] (Chisel2-2.3.10.37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (CustomMobSpawner 3.3.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	dualhotbar{1.5} [Dual Hotbar] (Dual-Hotbars-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	dungeonpack{1.7.10-1.0} [Dungeon Pack] (Dungeon-Pack-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Enchiridion{1.1} [Enchiridion] (Enchiridion-1.7.X-1.2b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	EnderIO{1.7.10-2.2.7.325} [Ender IO] (EnderIO_1.7.10_2.2.7.325.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	EE3{0.2.234} [Equivalent Exchange 3] (Equivalent-Exchange-3-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	exnihilo{1.34} [Ex Nihilo] (Ex-Nihilo-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MCP_API{1.4} [MC+ API] (FirePit.v.1.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MCP_FirePit{1.0.3} [MC+ FirePit] (FirePit.v.1.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Forestry{3.5.6.15} [Forestry for Minecraft] (forestry_1.7.10-3.5.6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Errored
	hearts{1.0} [Hearts] (HeartCrystal.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	IronChest{6.0.56.739} [Iron Chest] (ironchest-1.7.10-6.0.56.739-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	JABBA{1.2.1} [JABBA] (Jabba.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	lucky{5.1.0} [Lucky Block] (Lucky-Block-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	lycanitesmobs{1.10.0c - MC 1.7.10} [Lycanites Mobs] (LycanitesMobsComplete 1.10.0c [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	arcticmobs{1.10.0c - MC 1.7.10} [Lycanites Arctic Mobs] (LycanitesMobsComplete 1.10.0c [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	demonmobs{1.10.0c - MC 1.7.10} [Lycanites Demon Mobs] (LycanitesMobsComplete 1.10.0c [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	desertmobs{1.10.0c - MC 1.7.10} [Lycanites Desert Mobs] (LycanitesMobsComplete 1.10.0c [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	forestmobs{1.10.0c - MC 1.7.10} [Lycanites Forest Mobs] (LycanitesMobsComplete 1.10.0c [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	freshwatermobs{1.10.0c - MC 1.7.10} [Lycanites Freshwater Mobs] (LycanitesMobsComplete 1.10.0c [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	infernomobs{1.10.0c - MC 1.7.10} [Lycanites Inferno Mobs] (LycanitesMobsComplete 1.10.0c [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	junglemobs{1.10.0c - MC 1.7.10} [Lycanites Jungle Mobs] (LycanitesMobsComplete 1.10.0c [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	mountainmobs{1.10.0c - MC 1.7.10} [Lycanites Mountain Mobs] (LycanitesMobsComplete 1.10.0c [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	plainsmobs{1.10.0c - MC 1.7.10} [Lycanites Plains Mobs] (LycanitesMobsComplete 1.10.0c [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	saltwatermobs{1.10.0c - MC 1.7.10} [Lycanites Saltwater Mobs] (LycanitesMobsComplete 1.10.0c [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	swampmobs{1.10.0c - MC 1.7.10} [Lycanites Swamp Mobs] (LycanitesMobsComplete 1.10.0c [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	magicalcrops{1.7.2 - 0.1 ALPHA} [Magical Crops] (magicalcrops-1.7.10_0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MapWriter{2.1.2} [MapWriter] (MapWriter-1.7.10-2.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0-81.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.1-182.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct] (TConstruct-1.7.10-1.8.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Mariculture{1.2.3d} [Mariculture] (Mariculture-1.7.10-1.2.3d.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	minepainter{0.2.6} [MinePainter] (minepainter-0.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (MoCreatures.v.6.3.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MorePistons{1.7.10-1.5.1.3} [More Pistons] (More-Pistons-Mod-by-Jiraiyah-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MSM3{3.0.0a} [More Swords 3] (MoreSwords.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	neiintegration{1.0.2} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NetherOres{1.7.10R2.3.0RC4} [Nether Ores] (NetherOres.vv2.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	placeableitems{1.4} [Placeable Items Mod] (placeableitems-1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	plantmegapack{4.02} [Plant Mega Pack] (plant_mega_pack_mod_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	randomite{2.0} [Randomite] (RandomiteOre.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	AS_Ruins{13.4} [Ruins Spawning System] (Ruins-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	simpleores{1.4.3} [SimpleOres 2] (SimpleOres-Mod-1.7.10-Plugins.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	aestheticsplugin{1.0.0} [SimpleOres 2 Aesthetics Plugin] (SimpleOres-Mod-1.7.10-Plugins.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	fusionplugin{1.4.3} [SimpleOres 2 Fusion Plugin] (SimpleOres-Mod-1.7.10-Plugins.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	netherrocks{1.1.2} [SimpleOres 2 Netherrocks Plugin] (SimpleOres-Mod-1.7.10-Plugins.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	snapdoors{1.7.10-1.1.0} [SnapDoors] (SnapDoors-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	thaumcraftneiplugin{1.7.10-1.7} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	TheSteveMod{1.1.0} [TheSteveMod] (TheSteveBotMod.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	TiCTooltips{1.2.4} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	bspkrsCore{6.10} [bspkrsCore] ([1.7.2]bspkrsCore-universal-6.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Treecapitator{1.7.2} [Treecapitator] (Tree-Capitator-Mod-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	wildcaves3{0.4.3.6} [Wild Caves 3] (Wild-Caves-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	yegamolchattels{1.1} [Ye Gamol Chattels] (Ye-Gamol-Chattels-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	denseores{1.0} [Dense Ores] (Dense_Ores_Mod_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CoFHCore: -[1.7.10]3.0.2-262
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	ThermalFoundation: -[1.7.10]1.0.0-81
	ThermalExpansion: -[1.7.10]4.0.1-182
	TConstruct Environment: Environment healthy.
	NetherOres: Lacking version information.
	Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Optifine
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.

**Comment by mezz** [comment]
Thanks for the report!
You will need to use the latest Unstable build or wait for the new build coming out tonight.

**Comment by mezz** [comment]
Forestry 3.5.7 has been released and resolve this issue.
