### ISSUE TITLE
Improve the probability system for centrifuge outputs

### ISSUE THREAD

**Issue by TinkerWorX** [ForestryMC/ForestryMC#703]
Current, we are limited to an integer in the [1; 100] range. It would be great with a float in the [0.00;1:00] range to give us more freedom to create very low chance outputs. So basically add support for `HashMap<ItemStack, float>`.

Another improvement would be a way to add multiple things in the same probability range, but limited to only one output. Something like `HashMap<ItemStack[], float>` where it will pick a random `ItemStack` from the `ItemStack[]`. For example, I could add `ItemStack[dirt, sand, gravel], 0.10f`, which would give a 10% chance to get either one dirt or one sand or one gravel, but never two at a time.

**Comment by mezz** [comment]
Thanks for the suggestion!
I added float support to the `CentrifugeManager`, and also created a way to make custom recipes that implement whatever logic you want for their output (with `getProducts`).

https://github.com/ForestryMC/ForestryAPI/blob/master/forestry/api/recipes/ICentrifugeManager.java

https://github.com/ForestryMC/ForestryAPI/blob/master/forestry/api/recipes/ICentrifugeRecipe.java
