### ISSUE TITLE
forestry.farming.gui Crashing on Forestry_1.7.10-3.5.7.16 and BC 7.0.6

### ISSUE THREAD

**Issue by Antecer** [ForestryMC/ForestryMC#709]
Crashes when right clicking on the forestry.farming

https://gist.github.com/mezz/942eba5871fba5b3d5c7

**Comment by mezz** [comment]
Thanks for the report!
Can you backup your world and see if it still happens on [the latest dev release](http://jenkins.ic2.player.to/job/Forestry_Dev/)?

**Comment by Antecer** [comment]
it works good on the latest dev release!

**Comment by mezz** [comment]
Great, thanks! I need to get Forestry 3.6.0 out soon
