### ISSUE TITLE
Game Crash With Forestry & Pam's harvest the nether mods installed

### ISSUE THREAD

**Issue by aaron1985** [ForestryMC/ForestryMC#711]
I thought i would let you know when forestry and Pam's harvest the nether mods install together cause the client to crash while loading and you don't get into the game at all.

**Comment by aaron1985** [comment]
i think my computer was been silly as now the error wont happen.

**Comment by mezz** [comment]
Thanks for the follow-up!
Feel free to report any time you see something weird.
