### ISSUE TITLE
Crash Forestry and Computronics

### ISSUE THREAD

**Issue by Dream-Master** [ForestryMC/ForestryMC#712]
My Game crash.Using forestry unstable 3.6.0.582 asie lib 0.42/0.4.1 computronics 1.5.2/1.5.1 and open computers version 1.5.12.26

https://gist.github.com/Dream-Master/431474af7e2b9f30949e#file-gistfile1-txt

https://github.com/asiekierka/Computronics/issues/136

**Comment by Vexatos** [comment]
See asiekierka/Computronics#136 for an answer.

**Comment by Dream-Master** [comment]
Thanks
