### ISSUE TITLE
isHellish implementation for alvearies

### ISSUE THREAD

**Issue by binnie567** [ForestryMC/ForestryMC#713]
Alvearies do not currently take into account the isHellish() modifier in IBeeModifier, which allows the nether to be simulated. More specifically, the  EnumTemperature getTemperature() method of TileAlvearyPlain needs to also check if isHellish() is true, and if it is return EnumTemperature.HELLISH

**Comment by mezz** [comment]
Thanks for the report!
I'll fix this soon.
