### ISSUE TITLE
Id scrambling

### ISSUE THREAD

**Issue by banjomarx** [ForestryMC/ForestryMC#714]
First of all this may be difficult to reproduce since i have a HEAVILY modded cauldron server (we are talking over 180 mods) but after hours and hours  (lit 12 hours) i managed to narrow down the source of the issue with my last update to forestry. for some reason when i added forestry it completely scrambled the mod ids on my server, causing all kinds of issues like meta data on weird blocks  and general instability of server. idk whats going on tbh but i removed forestry and it was fixed (i had to reload a backup in between removing each mod of course)

**Comment by mezz** [comment]
Thanks for the report!
There's no way Forestry can change IDs around. Forge takes care of all that in 1.7.10.
Unfortunately I'm not able to help with this.
