### ISSUE TITLE
Crash when looking up Comb Recipes in NEI

### ISSUE THREAD

**Issue by Dyonovan** [ForestryMC/ForestryMC#715]
Getting a client crash when looking up usages for Gendustry combs in nei.

Crash Report: http://pastebin.com/d35xgGYV

If you need any other information, just let me know.

**Comment by Dyonovan** [comment]
One sec. It looks like its NEI integration. Will look further into it.

**Comment by Dyonovan** [comment]
Never mind. Fixed in NEI Integration. Sorry for this.

http://minecraft.curseforge.com/mc-mods/225251-nei-integration/files/2241992

**Comment by mezz** [comment]
Thanks for the report and resolution!
