### ISSUE TITLE
Crash when looking up bee mutations in NEI

### ISSUE THREAD

**Issue by Dyonovan** [ForestryMC/ForestryMC#716]
CrashLog: http://puu.sh/ihUAG/8bfb846b3a.txt
Forestry Version: 1.7.10-3.6.0.583-unstable
NEI Version: 1.7.10-1.0.5.110

**Comment by mezz** [comment]
same as this one: https://github.com/ForestryMC/ForestryMC/issues/715

**Comment by mezz** [comment]
It's something else, sorry.
