### ISSUE TITLE
Missing minimum version

### ISSUE THREAD

**Issue by Beanius** [ForestryMC/ForestryMC#717]
Getting the message that i need Forestry: Minimum version required is 3.6.0.581

**Comment by Nirek-K** [comment]
That means you're using something that requires an unstable build of 581 or greater, which is the newest Binnie's Mods and Nei Integration,
Unstable builds being here: http://jenkins.ic2.player.to/job/Forestry_Dev/

**Comment by Beanius** [comment]
Aye thank you! tried to find the unstable files :D
