### ISSUE TITLE
Dupe with Thermionic Fabricator

### ISSUE THREAD

**Issue by jahpickney** [ForestryMC/ForestryMC#719]
When crafting Electron Tubes I was able to take one extra crafting after running out of materials. This happened once when I used tin (Thermal Foundation), once with bronze (Forestry), and once with rubber bars (MineFactory Reloaded). However, when I used iron a couple minutes later it didn't happen. This started happening after I updated to 3.5.7.16 following the Buildcraft update. Almost forgot, I'm using Forge 10.13.3.1428.

**Comment by mezz** [comment]
Thanks for the report!
The Thermionic Fabricator auto-crafts one item. When you pick it up, it crafts another one.
Are you sure the extra one you got wasn't created from resources in its inventory?

**Comment by jahpickney** [comment]
No, after picking up the last craftable item I exited the interface. At this point there was nothing in the output slot . When I opened the interface again there was an item in the output slot even though there weren't enough materials to make another one.

**Comment by mezz** [comment]
Please back up your world and try [the latest unstable build](http://jenkins.ic2.player.to/job/Forestry_Dev/). 
I was not able to replicate the problem there, even after making stacks of tubes.
Thanks!

**Comment by jahpickney** [comment]
Okay. Thank you and you're welcome!
