### ISSUE TITLE
Crash upon putting a tropical bee in the Habitat Locator

### ISSUE THREAD

**Issue by Kalbuck** [ForestryMC/ForestryMC#721]
I put a bee in once, wanted to see the results again. Upon putting the same bee in the locator again, game crashed after I put a honey drop in. Using Forge 1428 and Forestry 3.6.15.

https://gist.github.com/Kalbuck/f4306f6f55bc37ad9a21

**Comment by mezz** [comment]
Thanks for the report!
I was able to replicate the crash.

**Comment by mezz** [comment]
Fixed in the [latest unstable build](http://jenkins.ic2.player.to/job/Forestry_Dev/).
