### ISSUE TITLE
Apiarist's Pipe Not Craftable

### ISSUE THREAD

**Issue by gazebomom** [ForestryMC/ForestryMC#722]
As of BuildCraft version 7.0.0, the Forestry Apiarist's Pipe is no longer craftable.

It works with BuildCraft version 6.4.17

Forestry Versions tested: 3.5.7.16, 3.5.6.15 (and others in between)

I am reporting this bug to both BuildCraft and Forestry.

**Comment by mezz** [comment]
Thanks for the report!
The pipe has moved to Buildcraft Compat, for use with BC 7.0+.
Make sure you have it updated too.

**Comment by gazebomom** [comment]
Confirmed. I am able to craft the pipe with BuildCraft Compat 7.0.8 and BuildCraft 7.0.8.

Thanks!
