### ISSUE TITLE
Alveary does not form using Oredictionary name slabWood

### ISSUE THREAD

**Issue by leagris** [ForestryMC/ForestryMC#723]
It look like the Alveary top wooden slabs are not using Ore Dictionary name slabWood.
So currently an Alveary will not form from Thaumcraft Greadwood slabs.

**Comment by Nirek-K** [comment]
Should be fixed by https://github.com/ForestryMC/ForestryMC/commit/4851a7089326feacc284122b32af995b27c77c40
