### ISSUE TITLE
Custom soil support in MultiFarms

### ISSUE THREAD

**Issue by binnie567** [ForestryMC/ForestryMC#725]
In FarmLogic, the static method canBreakSoil checks an Immutable set of what Forestry considers to be soil that can be replaced by the farm. This means that custom soils cause the farm not to work. Any chance of a way to add new ones? Even if it's not in the API, just maybe a change to the set so it can be accessed and altered

**Comment by mezz** [comment]
This definitely needs to be revised. I put it in there because at one point multifarms were destroying things that they shouldn't. They're a bit more well behaved now.
