### ISSUE TITLE
Leaves name doesn't show properly?

### ISSUE THREAD

**Issue by 3TUSK** [ForestryMC/ForestryMC#729]
While I am randomly browsing NEI, I saw these weird things:
![2015-06-19_17 11 49](https://cloud.githubusercontent.com/assets/9113033/8250520/375da8e6-16a7-11e5-9922-662d927352ba.png)
![2015-06-19_17 11 55](https://cloud.githubusercontent.com/assets/9113033/8250623/08d31b5e-16a8-11e5-8929-c1205796d39e.png)
![2015-06-19_17 12 16](https://cloud.githubusercontent.com/assets/9113033/8250624/09e3c052-16a8-11e5-887d-890601ae3d36.png)

The name of leaves doesn't show properly in not only NEI but also creative inventory:
![2015-06-19_17 22 56](https://cloud.githubusercontent.com/assets/9113033/8250611/fb488280-16a7-11e5-8604-09d06c51a868.png)
![2015-06-19_17 23 04](https://cloud.githubusercontent.com/assets/9113033/8250615/fff823c6-16a7-11e5-888a-2863d46326ef.png)

Change to other language, and the problem is still here. E.g.: Under zh_CN:
![2015-06-19_17 27 52](https://cloud.githubusercontent.com/assets/9113033/8250683/8929ff0c-16a8-11e5-890e-8cd58365f47b.png)

But there is no problem with raw log:
![2015-06-19_17 29 50](https://cloud.githubusercontent.com/assets/9113033/8250722/dc12b59c-16a8-11e5-8f71-6eed29a60fbc.png)

Not sure if there is relations between this problem and [this](https://github.com/ForestryMC/ForestryMC/blob/dev/src/main/java/forestry/arboriculture/items/ItemLeavesBlock.java#L30)
I am using Forge 1355, Forestry 3.6.0.599 Unstable, NEI 1.0.4.105.
I hope I can get reply soon. Thanks for your time.

**Comment by mezz** [comment]
Thanks for the report!
I'll fix it this weekend.

**Comment by mezz** [comment]
Fixed in unstable and upcoming 3.6.0

**Comment by 3TUSK** [comment]
Thx a lot
