### ISSUE TITLE
Forestry (1.7.10-3.6.0.604-unstable) crashes NEI when looking up recipes.

### ISSUE THREAD

**Issue by NathanMalta** [ForestryMC/ForestryMC#731]
I downloaded the latest version of forestry to fix corrupted leaves in my world. Minecraft crashed when I attempted to look up the recipe for buildcraft robots, and vanilla chests.  Here is the crash report: http://pastebin.com/4wtQCfQr

**Comment by mezz** [comment]
Thanks for the report!
neiintegration has a beta version for compatibility with Forestry's Unstable build.
[You can find it here, under "other" downloads.](http://www.curse.com/mc-mods/minecraft/225251-nei-integration#t1:other-downloads)

Forestry 3.6.0 is coming out soon, and this process will become less convoluted.
