### ISSUE TITLE
Crash viewing Letter

### ISSUE THREAD

**Issue by ferrari314** [ForestryMC/ForestryMC#732]
Hello. Today I cant use inventory.
I have this bug

https://gist.github.com/mezz/11ecad941ee454f2a452

**Comment by mezz** [comment]
Thanks for the report!
Can you backup your world and try with [the unstable build](http://jenkins.ic2.player.to/job/Forestry_Dev/)?

**Comment by ferrari314** [comment]
Good evening my friends. Thanks for you ansver. I'm trying to  use unstable build and get this crash after starting world.
https://gist.github.com/ferrari314/c84512f2233e96d6bbcf

**Comment by mezz** [comment]
Thanks! I'll take a look soon.

**Comment by mezz** [comment]
Fixed in [the latest unstable build](http://jenkins.ic2.player.to/job/Forestry_Dev/) and the upcoming Stable 3.6.0.
