### ISSUE TITLE
Unable to download forestry (Deprecated versions)

### ISSUE THREAD

**Issue by TEXASSTYLE** [ForestryMC/ForestryMC#733]
Ohai, So I'm unable to download forestry 1.2.5 (the latest one of them. but this issue seems to apply for all of those downloads) because of Dropbox being messy saying:

Error (429)
This account's public links are generating too much traffic and have been temporarily disabled!

I know this isn't really a bug or anything but I'm wondering if you guys could fix it? I really want to get forestry for that version.

And for gods sake, can't find how to place the label on this post...

**Comment by Chocohead** [comment]
http://forestry.sengir.net/files/forestry/releases/

Use this instead. 1.4.8.7 is missing, but it's just 1.4.8.6 with an updated IC2 API.

**Comment by Parker8283** [comment]
Still think it would be a good idea if Sengir transferred the builds that are on his dropbox onto that directory on his website.

**Comment by mezz** [comment]
@SirSengir are the ancient 1.2.5 builds [listed here](http://forestry.sengir.net/wiki.new/doku.php?id=main:deprecatedversions) available anywhere?

**Comment by AnrDaemon** [comment]
http://forestry.sengir.net/files/forestry/releases/1.4.8.7/forestry-client-A-1.4.8.7.jar
http://forestry.sengir.net/files/forestry/releases/1.4.8.7/forestry-client-A-1.4.8.7_bc2.2.jar
http://forestry.sengir.net/files/forestry/releases/1.4.8.7/forestry-server-A-1.4.8.7.jar
http://forestry.sengir.net/files/forestry/releases/1.4.8.7/forestry-server-A-1.4.8.7_bc2.2.jar
http://forestry.sengir.net/files/forestry/releases/1.4.8.7/CHANGELOG.txt

A little bit of guesswork goes a long way.
