### ISSUE TITLE
backpack crash at 3.7.0.612 u

### ISSUE THREAD

**Issue by ferrari314** [ForestryMC/ForestryMC#734]
Install 612u version for patch letters bug, but have new trouble :( FAIL

https://gist.github.com/ferrari314/24eb5d673b002b291f2e

**Comment by ferrari314** [comment]
I think it problem similar like a letters bug. May be all items programmed on this metods need revision?
:)

**Comment by mezz** [comment]
Thanks for the report!
This one is most likely from a mod that adds backpacks. The last time I saw it was from Mariculture. Can you make a copy of your world without mods that add backpacks to see?

**Comment by ferrari314** [comment]
This bug is unstabled. After reload minecraft crash is gone. Without mods all wok good too, of course.
One stability point, what I said: bug released in creative page select, but one time at day.
It's all what I saw. If I find more sign, I'm posted it here.
Thanx for you work =)

**Comment by mezz** [comment]
Thanks!
