### ISSUE TITLE
rewrite arboretum multifarms so they dont need so many updates per tick

### ISSUE THREAD

**Issue by Starless2001** [ForestryMC/ForestryMC#735]
arboretum farms cause a lot of lag to players close to them. I think maybe it has something to do with the constant update of the arboretum appearance being sent to the client? I don't know but maybe if the constant leaves decay, apple dropping and cutting of wood was replaced by mathematical formulas that would dictate the output of the farm, and the appearance of the farm would remain constant then this machine would cause less overhead

**Comment by mezz** [comment]
[Forestry 3.6.0](http://www.curse.com/mc-mods/minecraft/forestry) just came out, can you try and see if that improves things?
The multifarm moves pretty slowly, it really shouldn't cause more problems than a couple people chopping trees.
If you think leaves are to blame, you might want to try out the [Fast Leaf Decay](http://minecraft.curseforge.com/mc-mods/230976-fastleafdecay) mod as well.

**Comment by Starless2001** [comment]
Thanks I will download the new Forestry. I really don't know what the problem is, if it's the leaves or something else, but people I talked about this said the multifarm are notorious for causing a lot of lag, so I thought maybe it was worthy making this suggestion, since Forestry is such an important mod, essential to anyone who enjoys machines and automation.

**Comment by marcin212** [comment]
Probably Leaves decay generates light updates. Can you turn off smooth lighting and set fast graphic for test?

**Comment by Starless2001** [comment]
They had their settings on minimal and they used to lag severely, nevertheless. We started a new world and I don't have an arboretum yet, but I remember when I was on the nether, where there were no buildings or machines, my minecraft ran at 500+ fps (I have a fairly powerful custom built PC). near the arboretum it dropped to as low as 30 something.

**Comment by leagris** [comment]
@Starless2001 Did you find an improvement with recent Forestry as suggested by @mezz?
Arboretums generate extensive client side work on updates.
Leaf blocks are all tiles with lots of data. Each decay, growth cause client side updates and server load. @mezz has reworked a lighter tile leaf data.
There is still work to be done on saplings.
Arboretum is causing lots of sapling items to fall on the ground.
Each sapling has a full genome, UUID, texture pixels and signature payload. It is planned to reduce client data to the minimal rendering requirements.

This makes me think, leaf decay, saplings and apple fruit falls shall be simulated and added to the multifarm inventory without generating real item entities that fall on farm ground to be picked up later.

@mezz is working on improving multi-block structures handling.
Maybe there is something to be done here. Like making forestry trees multi-block structures, sharing genome data for all the tree structure, handling trees as a whole with interaction method. Chop, decay, growgth, ripening... rather handling each leaf, fruit, log sapling individually.

**Comment by Starless2001** [comment]
@leagris yes, that's my idea: instead of actually dropping the stuff and making the leaves decay, everything should be just math: given E power, N trees planted, then a certain number of saplings, wood and apples should appear into the inventory of the multifarm. the use of fertilizer and the turning of soil into sand should be a function of the total amount of output accumulated since the last time a fertilizer unit was used and the last time a block of soil has turned to sand.

the multifarm could even have a cool futuristic look with a glass dome over it or something, maybe. whatever it takes to reduce the generation of entities and client updates.

**Comment by mezz** [comment]
The new multiblock code is in unstable, which is now Forestry 4.0 since it breaks compatibility. I will be experimenting with multiblock trees, leaf harvesting/breaking to collect items directly, and other possible optimizations. I will also be looking at how we do rendering.

I will not be virtualizing the farm, or making it futuristic. Sorry but that does not fit with the theme of Forestry.

**Comment by mezz** [comment]
Thanks for the input everybody!

Looked into multiblock trees and it would be extremely complicated for a small gain. It may be done in the future but it would be a huge feature.

Added a new issue for leaf-destroying farm here https://github.com/ForestryMC/ForestryMC/issues/796

Lighter genome data is here: https://github.com/ForestryMC/ForestryMC/issues/561

Closing this issue. If I missed something, please open a new (specific) issue.
