### ISSUE TITLE
Configuration option for #489

### ISSUE THREAD

**Issue by asiekierka** [ForestryMC/ForestryMC#736]
Worktables being autocrafters partially nullifies BuildCraft's rather fragile autocrafting balance, while not impacting most other modpacks. It would be nice if there was a config option for this, keeping it on by defualt (that is, autocrafting on): https://github.com/ForestryMC/ForestryMC/commit/b18cee80cbaa3ddfed0d7003111df7f91f05700d

**Comment by asiekierka** [comment]
Oh. It doesn't autocraft. Freaked out for a sec.

**Comment by mezz** [comment]
Yep, definitely agree with you. No worries
