### ISSUE TITLE
Full blocks not working as flowers

### ISSUE THREAD

**Issue by grydian** [ForestryMC/ForestryMC#737]
I know 611 says it fixed this issue however I am using forestry_1.7.10-3.7.0.612-unstable and I cannot get modest bees to see the cactus as a flower.  I tried using different apiaries from different mods and none worked.

**Comment by bdew** [comment]
The problem is that cacus blocks change their metadata to keep track of growing progress. Forestry only checks for meta 0.

**Comment by bdew** [comment]
For a temporary fix you can change apiculture.cfg - find section "flowerscacti" and add to "S:accepted" list all the variants:

```
                minecraft:cactus:1
                minecraft:cactus:2
                minecraft:cactus:3
                minecraft:cactus:4
                minecraft:cactus:5
                minecraft:cactus:6
                minecraft:cactus:7
                minecraft:cactus:8
                minecraft:cactus:9
                minecraft:cactus:10
                minecraft:cactus:11
                minecraft:cactus:12
                minecraft:cactus:13
                minecraft:cactus:14
                minecraft:cactus:15
```

**Comment by mezz** [comment]
Thanks for the report!
Should be fixed in the latest unstable build.
