### ISSUE TITLE
Non-fruit leaf blocks accept an infinite amount of fertilizer

### ISSUE THREAD

**Issue by leagris** [ForestryMC/ForestryMC#738]
Right-clicking with fertilizer on fruit leaf blocks or pods grow fruits to maturity and it is fine where it stop accepting more fertilizer once fruit reach max maturation stage.

Right-clicking with fertilizer on leaf blocks with no fruit, consume an infinite amount of fertilizer.

I think if leaf block does not have fruit to mature, it shall not accept righ-click fertilization at all.

**Comment by mezz** [comment]
Thanks for the report! Fixed in the latest unstable.
