### ISSUE TITLE
Crash on 3.6.0 when I load world

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#739]
When I load my world, some of the chunks load, then I get this error that appears in the console that is formatted like a crash-report file. However, the server doesn't 'crash', everything just stops but players can still move around. Players just can't chat, move, interact with anything and mobs don't move etc.

Crash/error thing: http://pastebin.com/x0jDGEpa

Edit: I am using KCauldron and Forge 1448 if that is of any relevance.

**Comment by ghost** [comment]
Build 569 runs fine, 570 is where this crash appears.

**Comment by mezz** [comment]
Thanks for the report!
Fixed it as well as some UI issues with the Trade Station, going to create Stable 3.6.1 with the changes shortly.
