### ISSUE TITLE
Blank apiculture.cfg with non-english locale

### ISSUE THREAD

**Issue by utel** [ForestryMC/ForestryMC#740]
Crash report http://pastebin.com/HDU46NLx

Build 1.7.10-3.6.0.603 work well, but 1.7.10-3.6.0.604 and up being crashed.

**Comment by mezz** [comment]
Thanks for the report!

Are you using the Beyond Reality pack? They have an issue here: https://github.com/Beyond-Reality/BeyondRealityModPack/issues/258

You should be able to delete apiculture.cfg and Forestry will generate a new one.

**Comment by utel** [comment]
I deleted mod/forestry.jar , and folder config/forestry, download new forestry_1.7.10-3.7.0.615-unstable.jar and run new game. I installed 4 of the apiary and waited... game crushed...
http://pastebin.com/sFgYZwmd

Ok. I'm no using Beyond Reality pack, I'm using my my pack, I'm trying to update all the mods in time,
and I understand that the error can be due to incompatible mods... due to the obsolescence of some fashion... and I deleted all mods and all configs except forestry and started a new game... crash again
http://pastebin.com/bjfYWdf5

I'm using forge 1.7.10-10.13.2.1291 and i'm not update it, because not all mods have updated support for the latest forge version, modpack working bed...

Help pls! :(

**Comment by mezz** [comment]
Can you paste your fml server log from just after you deleted the forestry config folder? It should give me a better idea of how to fix the problem.
http://gist.github.com will allow you to upload the very large file.

**Comment by utel** [comment]
I'm not have fml server log..
Sorry - fml-client-latest.log -this is not the file that need?
https://gist.github.com/utel/c1aa0140439dd638a753

**Comment by mezz** [comment]
That's the right file, thanks.

**Comment by mezz** [comment]
I'm not sure you deleted the forestry config files before this log. It has references to Railcraft in the backpack configs, which would only show up if you ran the game with Railcraft.

If you can get me the  fml-client-latest.log after you delete the config folder, it would be valuable to fixing this bug.

Once you have that, you can try to just [use this as your apiculture.cfg](https://gist.github.com/mezz/ef7e5776070babaaef50) and it should work. I just copied it from a fresh setup, generated by Forestry after deleting the config file.

**Comment by utel** [comment]
I removed everything again and installed again forestry and forge. crash...
https://gist.github.com/utel/a1a86611d43386fe2b48

I replaced the contents of the file apiculture.cfg from your link... and... work...

I installed all my mods again and updated forestry to 619. Work. Fine. 

Thank you.)

PS. perhaps I need to clean the system and reinstall all over again.

**Comment by mezz** [comment]
Thanks! I think I got it.

Is your system language something besides English, and does it use a comma (,) for decimals?
I think the parsing code is getting broken by java's system localization, since it expects periods (.).

**Comment by mezz** [comment]
Can try the [latest unstable build 620+](http://jenkins.ic2.player.to/job/Forestry_Dev/) and remove apiculture.cfg one last time? 
It should work correctly now.
Thanks for your patience with this issue!

**Comment by utel** [comment]
I removed apiculture.cfg and installed forestry 3.7.0.621. Works fine, stable.
Thank you for your work!)

**Comment by mezz** [comment]
Excellent, thanks!
