### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by QORTEC** [ForestryMC/ForestryMC#741]
Crash Log:
http://paste.ubuntu.com/11786868/

Versions:
Forestry 3.6.1.18
Forge 10.13.3.1408

If you need more information I an happy to provide it

**Comment by mezz** [comment]
Thanks for the report!
This is an incompatibility with an old Computronics.  https://github.com/asiekierka/Computronics/issues/127
@Vexatos recently released a new version to work with Forestry 3.6.
