### ISSUE TITLE
Hopper doesn't fill last spot of Carpenter inventory

### ISSUE THREAD

**Issue by Zyin055** [ForestryMC/ForestryMC#742]
When attempting to automate the Carpenters for my AE2 system I noticed that the last slot (#18) of the Carpenter's inventory doesn't fill up with items when being pumped in with a Hopper.  I've also confirmed that this also happens with ME Export Bus and Mekanism's Logistical Transporter pipes.

I am playing the Regrowth 0.7.4 modpack which uses Forestry 1.7.10 3.4.0.7.

http://i.imgur.com/sPspVUf.png

http://i.imgur.com/ArI7jNx.png

**Comment by mezz** [comment]
Thanks for the report!
Fixed in the [latest unstable build](http://jenkins.ic2.player.to/job/Forestry_Dev/).
