### ISSUE TITLE
Bees cant find flowers after update

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#744]
All my bees suddenly stopped detecting any flower after i update forge and forestry.

I am running:
Forge: 10.13.4.1481
Forestry: 1.7.10-3.7.0.621-unstable

**Comment by mezz** [comment]
Thanks for the report! 
Which bees and which flowers are not working?
Can you please post what's in your `config/forestry/apiculture.cfg` file to http://gist.github.com?

**Comment by ghost** [comment]
https://gist.github.com/techmago/c3ee8fdc32ce7361d241

All bees!
i got in the farm: industrious, tropical, cultived, majestic and imperial. 
Everything was fine before i updated the jar. 

This happens on alveary, bee houses and apiarys

**Comment by mezz** [comment]
Ok your config is missing everything. There was a bug in recent unstable versions where it would make a blank config if your system language isn't English.  https://github.com/ForestryMC/ForestryMC/issues/740

Try deleting `config/forestry/apiculture.cfg` and it should create it correctly!

**Comment by ghost** [comment]
well, i tried first to delete only apiculture.cfg, and i tried to delete the hole foresty config folder. in both cases, the game crashes in the first run (https://gist.github.com/techmago/55ffa390dc58ea6484a3)
and in the second run, it run, but the apiculture.cfg is recreated "missing everything"

**Comment by ghost** [comment]
I run minecraft in the default English, but the system wide language is pt-br

**Comment by mezz** [comment]
For now, [use this as your apiculture.cfg](https://gist.github.com/mezz/ef7e5776070babaaef50) and it should work. I'll set my system language differently and try to fix it.

**Comment by ghost** [comment]
Yep, it is working with the provided file.
Thanx!
