### ISSUE TITLE
Backpacks accept wrong items on pickup

### ISSUE THREAD

**Issue by leagris** [ForestryMC/ForestryMC#745]
- forge-1.7.10-10.13.3.1403-1.7.10
- forestry_1.7.10-3.7.0.606

A Builder's Woven Backpack will pick-up ([¹](#user-content-notes))`minecraft:sandstone` items if no room left into a Digger's Woven Backpack or Player Inventory; while still refusing it to be moved-in manually.

[`backpacks.cfg`](https://gist.github.com/leagris/f225001d03b16353382d)

``` YAML
    digger {
        # Add itemStacks for the digger's backpack here in the format 'modid:name:meta'. For wildcard metadata the format is 'modid:name'.
        S:item.stacks <
            minecraft:sandstone:0
         >

    builder {
        # Add itemStacks for the builder's backpack here in the format 'modid:name:meta'. For wildcard metadata the format is 'modid:name'.
        S:item.stacks <
            minecraft:sandstone:1
            minecraft:sandstone:2
         >
```
##### <a name="notes"></a>Notes
1. Same glitch apply with other items

**Comment by mezz** [comment]
Thanks for the very clear report!
Embarrassing, it's only working with oreDict, not items.

**Comment by mezz** [comment]
Thankfully this does not effect Stable 3.6.
Fixed in the latest unstable build.
