### ISSUE TITLE
Minor Multifarm texture bug

### ISSUE THREAD

**Issue by yepidoodles** [ForestryMC/ForestryMC#747]
This is server side (Not tested in Single player) 

After a multifarm has been made, and the area with it in has been unloaded, the farm valve has changed from smooth sandstone to mossy stone brick, this has happened in 3 different farms on my server, all with different bricks, and they've changed to the same mossy stone brick, however the farm still works fine and when you take the block out, it turns back to the original brick type. I made a gif of myself putting the block back after taking it out

https://gyazo.com/5cc92a304919d4689595c1b2018b9d6a

I understand there's not much you can do with this information, but I felt you would want to know.

Thanks,
Alice (yepidoodles)
DragonTechMC

**Comment by mezz** [comment]
Thanks for the report!
You described the problem and gave steps to reproduce, which is plenty of information in this case. 
I'll take a look this weekend.

**Comment by DrakoAlcarus** [comment]
Same in my case. Farm is pure brick, but valve turns to mossy stone brick.

**Comment by mezz** [comment]
Fixed in the muilblock refactor.
https://github.com/ForestryMC/ForestryMC/commit/aa47599278bd55eef126d398737501a71f984e39
