### ISSUE TITLE
Farm Hatch Not Working

### ISSUE THREAD

**Issue by panda2134** [ForestryMC/ForestryMC#749]
Farm Hatch doesn't put the wood what the farm harvested into the container near it.
I deleted other mods but it still doesn't work.
Forestry Version:forestry_1.7.10-3.5.6.15

**Comment by panda2134** [comment]
Images:http://imgur.com/a/x0tq2

**Comment by Nirek-K** [comment]
Farm hatch puts items into inventories/bc pipes below the hatch only, via gravity.
