### ISSUE TITLE
Thermionic Fabricator Item Pull

### ISSUE THREAD

**Issue by Megistus** [ForestryMC/ForestryMC#752]
Items pulled into the top of the Thermionic Fabricator pull into the Glass and Wax Cast slots, but then begin to fill the resource inventory afterward. For automation purposes, it would be better if anything that is pushed into the top of the Fabricator not fill the resource inventory.

Thanks!

**Comment by mezz** [comment]
Thanks for the report!
That makes sense. When we re-did all the inventories, we lost some side-specific functions.

**Comment by Nirek-K** [comment]
Fabricator Inventory should now reject items (via insertion) that aren't used by the crafting grid.
