### ISSUE TITLE
Initializing game

### ISSUE THREAD

**Issue by MoonDroper** [ForestryMC/ForestryMC#753]
https://gist.github.com/mezz/3a4cdb97d1e45b3861eb

**Comment by Parker8283** [comment]
Might be a Binnie's mods problem. Try to replicate with just Forestry.

**Comment by MoonDroper** [comment]
:( Ok..

**Comment by MoonDroper** [comment]
Error without binnie's mod.. :""(

https://gist.github.com/mezz/c1780dbaf68e77ce9363

**Comment by Parker8283** [comment]
I said with JUST Forestry.

**Comment by MoonDroper** [comment]
Sorry.. My bad english.. :/
Forestry with binnie's mod normal start, without errors.

**Comment by Parker8283** [comment]
Then it's most likely not Forestry's problem. In looking at where the code errored, it is probably a cross mod interaction. Your best bet is to keep adding mods (specifically ones that add bees) until you find one that causes your first error. Then report it to that mod author. I highly doubt it's actually Forestry, given the information you've given.
