### ISSUE TITLE
Bees don't work with flowers in AgriCraft crops

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#754]
As the title says, Forestry bees don't recognize flowers if they are planted in AgriCraft crops. This poses a problem in mod packs which have the AgriCraft's option to disable vanilla farming turned on.

**Comment by Nirek-K** [comment]
Give Unstable [#629](http://jenkins.ic2.player.to/job/Forestry_Dev/629/artifact/build/dist/forestry_1.7.10-3.7.0.629-unstable.jar) a try.

**Comment by ghost** [comment]
Excellent! Thank you very much!
