### ISSUE TITLE
Make the Apiarist's Pipe sort larvae

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#755]
I am not sure how many people actually use the Apiarist's Pipe, but I found it to be quite usefull when automating Bees with BuildCraft. However it bugs me that it is unable to sort larvae.

**Comment by mezz** [comment]
Thanks for the report!
That makes sense. You should also report this to the [BuildCraft Compatability project](https://github.com/BuildCraft/BuildcraftCompat), because the Apiarist's Pipe has been moved there for BuildCraft version 7.

**Comment by mezz** [comment]
Making a note that this has been reported to BC Compat here: https://github.com/BuildCraft/BuildcraftCompat/issues/34

**Comment by mezz** [comment]
Closing this since I just removed the Apiarist's Pipe from this project, any fix will be for BC Compat,
