### ISSUE TITLE
Forestry crashing with listed mods.

### ISSUE THREAD

**Issue by DarQuing** [ForestryMC/ForestryMC#756]
After adding Forestry, my Minecraft started crashing to the launcher. The mods I use are: Tinkers Construct, Extra TiC, TiC Tooltips, Iguana Tinker Tweaks, Not Enough Items, Thaumcraft NEI, Thaumcraft, Thaumic Tinkerer, Automagy, Thaumcraft Node Tracker, JABBA, Witching Gadgets, Traveller's Gear, Backpack, Travellers Gear, ProjectE, Damage Indicators, and Journey Map

http://pastebin.com/6MGs3iNC

Thank you for your time! :)

**Comment by Parker8283** [comment]
This appears to be a problem with Tinkers Construct, and since Forestry doesn't mess with TCon, it's not our problem.

**Comment by mezz** [comment]
@DarQuing you probably have a mod that includes an old version of the RF API.
Your fml crash log will include a list of APIs loaded, and which .jar they come from.
If you post it to pastebin here, I can help out.

**Comment by Parker8283** [comment]
They did. Look in the OP. The error is a missing TCon class :P

**Comment by mezz** [comment]
The missing TCon class error is
`Caused by: java.lang.ClassNotFoundException: cofh.api.energy.IEnergyContainerItem`
which is probably caused by a mod (coremod?) with an old RF API

**Comment by Parker8283** [comment]
Oh my, I missed that! Anyways, BDLib is the thing lists apis in crash reports IIRC. But still not our problem in the end, I guess.

**Comment by mezz** [comment]
Yeah but like... :bee: nice :)

**Comment by Parker8283** [comment]
🐝

**Comment by Parker8283** [comment]
I wasn't saying you shouldn't help, just making sure it isn't our problem. :bee:

Most likely it's a mod loading before TCon providing an incomplete RF API, and claiming that they are providing the entire api with the annotation. Because that class has always existed as long as RF has existed, so this is a weird one.

**Comment by DarQuing** [comment]
Is there a way to change the order the mods load in? Or should I go through all the mods and see if there are updates for them? I'm quite new to modded Minecraft, and normally I use modpacks, but I wanted to try using just a few mods that I know I like (namely TiCon and Thaumcraft), so assume I know nothing, because I don't.

**Comment by mezz** [comment]
You want to check for updates. The RF API probably needs to match for all the mods to work together.
If you are really new, I suggest using a pre-made pack and removing mods you don't want. It'll be an easier start.

**Comment by DarQuing** [comment]
I've been using packs, I'm just never sure which mods to take out that won't also break the pack. I'm using as few mods as possible because I know those are the ones I like using the most.
