### ISSUE TITLE
Add fireproof versions of all Forestry wooden items

### ISSUE THREAD

**Issue by jprocket45** [ForestryMC/ForestryMC#758]
Teak Wood Planks ( Fireproof ) do not turn into Teak Wood Slabs ( fireproof ) they turn into oak wood slabs . Still happening in current unstable build... loaded up just Forestry and NEI in curse to see if this was not a mod conflict seems it is not still same issue thanks!

**Comment by mezz** [comment]
Thanks for the report!
Right now there are only fireproof Logs and Planks. 

To support every wood Forestry item, I will need to be a little smarter about how I create them. Thankfully I have a pretty good idea of what I need to do now. I'll keep this here as a reminder!

**Comment by mezz** [comment]
Added fireproof versions of all the wood blocks in the latest unstable build.
