### ISSUE TITLE
[Major Bug] World Corrupt - Invalid Bee Data on Update

### ISSUE THREAD

**Issue by Eladkay** [ForestryMC/ForestryMC#759]
https://gist.github.com/Eladkay/e8bca15373b0aa86cff1

I knew the world would be corrupted when I broke the chest with the invalid bees... :) Backed it up.

**Comment by Kubuxu** [comment]
In the crashlog itself there is a fix: https://gist.github.com/Eladkay/e8bca15373b0aa86cff1#file-gistfile1-txt-L9

EDIT: Oh ok. I didn't know that Forestry was removing a bee allele on its own.

**Comment by mezz** [comment]
Thanks for the report!
This was fixed just a few hours ago, please grab the latest version from Curse. 

There is no need to clear invalid chromosomes in this case. It was a Forestry error.
