### ISSUE TITLE
Add better Moistener and Fermenter integration with ModTweaker

### ISSUE THREAD

**Issue by Starless2001** [ForestryMC/ForestryMC#766]
I understand this would probably require a rewrite of a lot of code, but I was thinking both Moistener and Fermenter shouldn't have "fuels". the things they use for fuel, wheat and mulch, compost, fertilizer, should be part of the recipe. This way you could do whole new things with them, integrating forestry with other mods, for transforming fluids and items into others, without making the recipe look a little stupid for using wheat or mulch.

**Comment by Nedelosk** [comment]
Before we add a better integration for ModTweaker in forestry, we need a integration for ModTweaker  in forestry.

**Comment by temp1011** [comment]
http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Forestry_Support pretty sure this can be closed.
