### ISSUE TITLE
[1.7.10] Dupe with any a bag from any mods

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#767]
https://youtu.be/T-593gZyo6I

This method works for bags of Forestry

Fix the bug in your mod please.

**Comment by Kubuxu** [comment]
Why is this error in forestry. You have shown bag from Thermal Expansion. I don't see any connection with Forestry.

**Comment by ghost** [comment]
I did not bother showing all the bags of all the mods, showing an example bags TE. But this method works for all bags, including for Forestry

**Comment by Kubuxu** [comment]
Shift-click in forestry changes modes. I am not able to reproduce it.

**Comment by KingLemming** [comment]
Shift click on the item in the bag, @Kubuxu. However, this video is using outdated mods and doesn't happen in TE either.

Even so, make sure it's completely non-applicable.
