### ISSUE TITLE
Save circuit board data on Electric engines when broken.

### ISSUE THREAD

**Issue by Nirek-K** [ForestryMC/ForestryMC#768]
Breaking the engine with a circuit board installed destroys the board. Should probably keep the board in it, or possibly just drop the board.

**Comment by Chocohead** [comment]
But surely the point of having to use the soldering iron to remove it was to encourage you to be careful?

**Comment by mezz** [comment]
I think this makes plenty of sense.

**Comment by mezz** [comment]
When a machine is broken, it will drop its circuit board just like it was an item in its inventory.
I also added a tooltip when you hover over the circuit board in the machine that says "Removable with a Soldering Iron"
