### ISSUE TITLE
Clean Install with forestry only => crash & invalid config (bees accespt no flowers)

### ISSUE THREAD

**Issue by xenexelen** [ForestryMC/ForestryMC#769]
Testet with forestry_1.7.10-4.0.0.641-unstable.jar (No other Mods installed) and empty config-folder

After the first start, i get this crash-report:
https://gist.github.com/xenexelen/b5eaf99a83de16b48e71

After the second start, no bee can find his regular flowers. apiculture.cfg:
https://gist.github.com/xenexelen/9894131262f555e2cf39

Next try: i copy my apiculture.cfg-file from a early version. apiculture.cfg (old version):
https://gist.github.com/xenexelen/6503724740f475215e9b

Now the flowers are found.

Next change:
I set "B:clear.invalid.chromosomes=true" (common.cfg)
=> All bee-queen (from regular bees in creative tab) are destroyed

**Comment by xenexelen** [comment]
Sorry - i see this is an duplicate from 744, only the last info is new.

**Comment by mezz** [comment]
Thanks for the report!
This is actually a separate issue. I'll take a look at solving it.

Also `clear.invalid.chromosomes=true` is only really useful if you removed an addon mod. .. I'll take a look though.

**Comment by mezz** [comment]
I pushed a fix for the broken config file in the latest dev build.

**Comment by mezz** [comment]
With the latest dev build of Forestry, `clear.invalid.chromosomes` appears to be working correctly as well.
