### ISSUE TITLE
Forestry config files still not working as expected

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#772]
I just get the latest's build an try to make forestry regenerate all its config. It crashed.

How to reproduce:
1. remove all forestry config files.
2. run minecraft
3. crash.

Running:
forestry_1.7.10-4.0.0.644-unstable
Minecraft Forge 10.13.4.1490

Crash:
https://gist.github.com/techmago/2c976f1d4a3b8abc3e69

**Comment by ghost** [comment]
- it crashes with my old config files too
  I had to fallback to build 629 in order to play.
  All builds between 644 - 640 crashed for me (the ones i tested)

**Comment by Nirek-K** [comment]
none of the addons will work with 640+ without updates, that's a crash because of gendustry.

**Comment by ghost** [comment]
oh
sorry then.
really, 639 is fine :)
