### ISSUE TITLE
question about world.

### ISSUE THREAD

**Issue by lightning02** [ForestryMC/ForestryMC#774]
Matierials and stuff of your mod will generate only in new chunks? Or even in old chunks of my world?

**Comment by mezz** [comment]
By default: only new chunks.  
If you want to have it generate in old chunks, go to the `config/forestry/common.cfg` and enable `world.generate.retrogen.normal`.

> Creates Forestry world generation in chunks that were created before the mod was added.

**Comment by lightning02** [comment]
Also its  addon?

**Comment by mezz** [comment]
This also effects magic bees.  I don't know about Binnie's mods.
