### ISSUE TITLE
Found Chromosome with invalid Alleles (Forestry 4.0)

### ISSUE THREAD

**Issue by Akai1** [ForestryMC/ForestryMC#775]
Server is crashing when player joins.

http://pastebin.com/hhV8EJJe

**Comment by mezz** [comment]
Thanks for the report!
Can you paste your server log to http://gist.github.com? (it allows large files)

**Comment by Akai1** [comment]
Replicated the crash in sp.

https://gist.github.com/Akai1/48874aa1a47a4164ad9e

**Comment by mezz** [comment]
Thanks! Should be fixed in the latest unstable build.
