### ISSUE TITLE
Crash when search recipe in NEI

### ISSUE THREAD

**Issue by bakaxyf** [ForestryMC/ForestryMC#782]
[crash report and log](https://gist.github.com/bakaxyf/51de9d7b4a0adfee2b67)
Used:
forge10.13.4.1448
NotEnoughItems-1.7.10-1.0.5.111-universal
CodeChickenCore-1.7.10-1.0.7.46-universal
NEIIntegration-MC1.7.10-1.0.11
forestry_1.7.10-4.0.0.653-unstable

**Comment by liach** [comment]
Report to [here](https://github.com/Tonius/NEI-Integration/issues/new). NEIIntegration needs an update.

**Comment by bakaxyf** [comment]
All recipes, not only processing by forestry's machine.

**Comment by bakaxyf** [comment]
https://github.com/Tonius/NEI-Integration/issues/84

**Comment by mezz** [comment]
Thanks for the report and linking to the other report!
