### ISSUE TITLE
Suggestion (Comb Chest)

### ISSUE THREAD

**Issue by porteriscool** [ForestryMC/ForestryMC#784]
As there is already an apiarist chest for bees, a new suggestion that would be appreciated would to add a chest just for combs. This is not a demand, but it would be very appreciated if it could be added, and if not thats alright with me.

**Comment by MysteriousAges** [comment]
Should wait on this one until #808 is resolved one way or another.

**Comment by bakaxyf** [comment]
Any progress?

**Comment by mezz** [comment]
I'd like to do some tweaking to the existing chests first. The GUI on the side of the naturalist's chests doesn't really make sense, and especially doesn't make sense for combs. https://github.com/ForestryMC/ForestryMC/issues/954

**Comment by bakaxyf** [comment]
OK

**Comment by LuigiHutch** [comment]
What would a comb chest do that a normal chest couldn't?

**Comment by mezz** [comment]
It would hold way more combs than a normal chest

**Comment by ghost** [comment]
Iron Chests or Storage Drawers or JABBA barrels are your friend. You can also just make more normal chests, or spin them into stuff like honey which can be further refined and stored. Do you feel that adding this would solve problems that couldn't be solved previously? Apiarist chests have functions other than storage, but this is just a bigger chest which is already present in other mods. You can currently store almost 3.5k combs(of a single type) in one double chest. If you have more than that you may want to refine them into something else..

**Comment by mezz** [comment]
I think @victicdin makes a compelling argument. Any response @porteriscool ?
