### ISSUE TITLE
Problem with GenDustry compatibility

### ISSUE THREAD

**Issue by davv1** [ForestryMC/ForestryMC#785]
https://gist.github.com/davv1/94105d0f60864484ed45

Issue shows for all Forestry-unstable with rev 640+(after changing Forestry's version to 4.0[introduction of Refactor]) when it's coming to initialization.
Tested with all Gendustry's rev 107+

If it helps: I tested Gendustry 107 and 113 with Forestry-unstable 639, both works, so it's more like a Forestry problem.
If need more infos/logs, just tell. :)

**Comment by bdew** [comment]
Forestry unstable 4.0 has incompatible API changes, so the normal builds of Gendustry won't work with it.

There's a sepearate branch of Gendustry for forestry unstable, see here http://jenkins.bdew.net/job/gendustry-1.7.10-fu/

**Comment by davv1** [comment]
Does this have same features as normal branch of Gendustry?

**Comment by bdew** [comment]
See my response in the other issue.

**Comment by mezz** [comment]
Thanks bdew

**Comment by davv1** [comment]
Thanks guys for your help.
