### ISSUE TITLE
Extrem short bee-lifespan?

### ISSUE THREAD

**Issue by xenexelen** [ForestryMC/ForestryMC#786]
Only Forestry is installed (unmodified config [beekeeping mode=NORMAL...]).
The lifespan from normal bees is only ~1/4-1/8 day. Is this really normal?

Edit: In some cases, the beequeen is instand dead (with progeny, but without honey combs).

Minecraft 1.7.10
MCP 9.0.5
FML 7.10.112.1370
Minecraft Forge 10.13.3.1370
Forestry 4.0.0.653-unstable

Also tested with Forge 10.13.4.1448

**Comment by SandGrainOne** [comment]
Bees from hives have (for the most part?) the Lifespan trait "Shortest" which is 4.5 minute.

**Comment by PrincessOfEvil** [comment]
It's not really a bad thing. Vanilla breeding is slow enough as it is, and
free scrap/l.dna/genetic trash can't hurt either.

**Comment by xenexelen** [comment]
I test it, in a normal "Beehouse" (The forestry-page says lifetime x 3.0) the "Shortest" lifespan is ~30sec (and in some cases 0sec...).

**Comment by PrincessOfEvil** [comment]
Isn't 30 secs, like, two life ticks? Maybe you have debug on, check the
longest one.

**Comment by xenexelen** [comment]
Within a fresh world, i had place 14 Beehouses and put in each of them a meadows drone+princess. I need 33sec to place them all. The last die ~170sec later.

After i start MC a second time: i place Apiary (The forestry wiki says livespan-factor is 1) and check the time. More instand death, than other (at last ~60%), in each other try the lifebar is instandly lose ~1/8-1/2. And now i get the same result for the beehouses...

If shortest Lifespan should be ~4,5min (270sec), in a beehouse (x3) it should be ~810sec (~a little more than one half of a ingame day).

@laz2727 I think it is a bad thing. Because i don't think all players woul'd play only for beegenetic. I want honey comb, treepollination, not only change bees...

**Comment by mezz** [comment]
Thanks for the report!
I messed with the beekeeping logic in 4.0 so it's probably a bug there.

**Comment by xenexelen** [comment]
Additional info: in some cases when i put a drone and a princess, i get not a queen only lose the drone.

**Comment by mezz** [comment]
Fixed in the latest unstable build.
