### ISSUE TITLE
Alveary Heater turning off

### ISSUE THREAD

**Issue by Fabboz** [ForestryMC/ForestryMC#787]
I'm using the forestry 3.6.3 release.
I have made an alveary with two heaters powered by thermal expansion fluxducts and an energy cell and it work well, the temperature raise and the heater blocks turn red its all ok and i'm happy =) ..... 
the problem come when i restart thegame.
Immediately after the world loading (at the start of the world) the heaters of the alveary are turned off fully charged and not working, i have to rebuild the alveary to make it working.
Another solution is to disconnect the power source and leave the heaters use all the power of themself and the fluxduct before closing the world and reconnect it at the start of the world.

i'm very happy if someone can fix that bug.

**Comment by mezz** [comment]
Thanks for the report!
This has been fixed in the unstable version. The unstable version is Forestry 4.0 and has world-breaking changes though. Multiblocks will lose their inventories and any wooden blocks will disappear. Be sure to make a backup if you try it out!
