### ISSUE TITLE
Exception Thrown on Accessing Any Stack With Bee in It

### ISSUE THREAD

**Issue by ApothecaryOfLight** [ForestryMC/ForestryMC#788]
I don't have the expertise to find out where this is coming from, so I've posted it on the three bug-trackers of the three mod families involved.

I have ONLY the following mods installed (I've also downgraded all three levels, trying each set of regressed versions):
CompterCraft1.73
forestry_1.7.10-3.6.3.20
OpenModsLib-1.7.10-0.8
OpenPeripheral-1.7.10-AIO-5

In Minecraft 1.7.10 using Forge 10.13.2.1291 and Forge 10.13.4.1448.

When I querry any information from a bee slot (such as getQueen/getDrone or getStackInSlot) I recieve the following error:

lua:1: forestry.api.apiculture.IBee.isIrregularMating()Z

I've tried downgrading and upgrading ALL the mods involved, but can't seem to escape it. That doesn't make any sense to me, because I had bee analyzing working without problem just a few weeks ago.

I've looked at the Forestry source, and could not find any reference to isIrregularMating, and what I could find suggested that it has been deprecated. But I cannot find where this call is coming from.

Please help me!

**Comment by DarkApothecary** [comment]
For archival purposes: this was fixed by upgrading to development builds of the openmods set. Deleting.

**Comment by ApothecaryOfLight** [comment]
For archival purposes: this was fixed by upgrading to development builds of the openmods set. Deleting.

**Comment by mezz** [comment]
Thanks for the clear report and solution!
