### ISSUE TITLE
Crash with BoP and Extrabiomes [Forestry 4.0]

### ISSUE THREAD

**Issue by Neuromantix** [ForestryMC/ForestryMC#790]
I write about this crashes on Extrabiomes topic http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1282126-extrabiomesxl-universal-3-16-2-for-mc-1-7-10?comment=14880 and github https://github.com/ExtrabiomesXL/ExtrabiomesXL/issues/436
and BoP topic http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286162-biomes-o-plenty-over-75-new-biomes-plants-and-more?comment=10783
But biomes mods teams answers "This Forestry problem"
How can this be solved?

**Comment by NDufy** [comment]
Forestry version ?

**Comment by SandGrainOne** [comment]
This is linked to version 4. A version tagged as unstable and still in development. It is not recommended to use this version in any actual gameplay outside taking part in testing.

This is still usefull input so I'm leaving it up to mezz to decide how to proceed.

**Comment by Neuromantix** [comment]
Last working version - unstable 639 Higger version dont't work

**Comment by mezz** [comment]
Judging by their response I will probably need to make a PR .

**Comment by mezz** [comment]
PR made for ExtraBiomes: https://github.com/ExtrabiomesXL/ExtrabiomesXL/pull/438

**Comment by mezz** [comment]
Asking if we can move the BoP compatibility to Forestry https://github.com/Glitchfiend/BiomesOPlenty/issues/518#issuecomment-131489922

**Comment by mezz** [comment]
Got confirmation, moved BoP compatibility to Forestry https://github.com/ForestryMC/ForestryMC/commit/c56f09897c68f2bb5630861c05fc17bd2aa479cb

**Comment by mezz** [comment]
The only thing left is for ExtraBiomes to accept the PR or come up with some other solution they like better. Going to close this issue.
