### ISSUE TITLE
[3.6] Sheared decorative leaf blocks don't stack

### ISSUE THREAD

**Issue by leagris** [ForestryMC/ForestryMC#792]
Sheared leaf blocks are non-stackable.

Decorative Sheared Forestry leaf blocks retain specific Tags including but not exclusively and absolutely unneeded Genome data.

They also retain X: Y: and Z: location they where placed when shearing!!!

So: If you shear pollinated leaf blocks, they will not stack.

Expected behaviour:
Sheared leaf blocks, shall be stripped of any non-common data and only retrain the minimum texture and colour references.

**Comment by mezz** [comment]
Thanks for the report!
Fixed in the latest unstable.
