### ISSUE TITLE
Magneticraft Inserters can put frames into Apiaries. 

### ISSUE THREAD

**Issue by HarrisFauntleroy** [ForestryMC/ForestryMC#793]
I was under the impression that these couldn't be automated - Though the stacking frames is probably negating the negative a bit

![2015-08-15_14 15 16](https://cloud.githubusercontent.com/assets/7843312/9287447/60c8019e-4358-11e5-805a-2f1b5d16ef2b.png)
![2015-08-15_14 15 18](https://cloud.githubusercontent.com/assets/7843312/9287445/60c7c9d6-4358-11e5-80cf-c36270df25b7.png)
![2015-08-15_14 15 15](https://cloud.githubusercontent.com/assets/7843312/9287446/60c7da70-4358-11e5-8e53-848cbb4f2baf.png)

**Comment by Nirek-K** [comment]
They are not meant to be automated no, those slots were mistakenly leaked the outside in one of the inventory cleanups/rewrites, will be fixed.

**Comment by mezz** [comment]
Thanks for the report!
Fixed in the latest unstable build.
