### ISSUE TITLE
Better migration from Forestry 3 to 4

### ISSUE THREAD

**Issue by mezz** [ForestryMC/ForestryMC#795]
Currently, the wood items disappear. They should migrate to the new type automatically.

Also multiblocks lose their inventories. Look into keeping them if possible.

**Comment by mezz** [comment]
Unfortunately this is not going to happen.
I tried a variety of ways, but there is no good solution to this problem.
4.0 will break a variety of blocks, which can be expected of a major release.
The Forestry 3 branch will receive bug fixes where requested/possible.

**Comment by SandGrainOne** [comment]
Could you create a list of precautions we should do before updating?
- Remove the content from Multiblock farms?
- Remove bees from Alvearies?
- Empty speciality chests?

I don't mind needing to replace building blocks, but I would hate to loose breeding progress.

**Comment by mezz** [comment]
I will have a full writeup when I announce 4.0 beta, but here's the migration plan right now:
- Remove contents from Farms and Alvearies.
- Gather saplings from your living trees because woods will be broken and the leaves might start to decay if there's a block update or something.

After updating:
- Break and rebuild Farms and Alvearies if they're not detecting the structure
- Plant trees

I'm looking at how to handle one last breaking changes, for the Bee House / Apiary / Apiarist's Chest. That issue is here: https://github.com/ForestryMC/ForestryMC/issues/821
EDIT: No need to worry about Bee House / Apiary / Apiarist's Chest, they migrate fine now.
The Arborist's and Lepidopterologist's chests will be fine as well.

Wood stuff will break: logs, planks, fences, slabs. Stained glass will disappear (hardly anyone using that though).

**Comment by labpaw** [comment]
Wait @mezz, do you want to say that you splitted two blocks from each other without breaking the world? That an interesting thing since I thought that this is impossible (I need this for Natura, you know :) you might got some Github notifications about it). Glad to know that this is possible :)

**Comment by mezz** [comment]
@Adaptivity It's possible, just super ugly and not fun to support. I decided against doing it for the woods because there are so many, it would be insanity. It took me a few hours just to test this one and make sure it was working right...
Have a look: https://github.com/ForestryMC/ForestryMC/commit/a188bbd43ae89ff6fa959d8b95fb9855b9123bdd

**Comment by leagris** [comment]
> Wood stuff will break: logs, planks, fences, slabs. Stained glass will
> disappear (hardly anyone using that though).
> Forestry village house using Forestry wood planks and stairs will be
> ravaged open.

My sympathy goes to the upcoming homeless villagers, begging for a safe
night in neighbour's houses.
