### ISSUE TITLE
Chipset upgrades for Machines

### ISSUE THREAD

**Issue by mezz** [ForestryMC/ForestryMC#797]
Idea from @Nirek-K :
The Carpenter, Centrifuge, and Squeezer could use some modest upgrade options.
Add a chipset slot (like the electrical engine) and some minor upgrades.
User slightly more power -> go slightly faster, up to 25% faster per electron tube.

**Comment by SandGrainOne** [comment]
Using 2 machines instead of simply upgrading one should be a viable option. In terms of power usage it should probably even be the preferred solution.

**Comment by mezz** [comment]
Agreed.
The upgrades will be less efficient than using 2 machines, but it will take up less space.

**Comment by mezz** [comment]
After a long discussion with @Nirek-K and @Vexatos about upgrades, I've decided the upgrades will only be for the Centrifuge and Squeezer for now. (Nirek has some ideas for other kinds of upgrades but I would want to add those later, not for the Forestry 4.0 release)

> raintank and moistener don't really make sense to have a circuit
> I'm going to just stick to the Centrifuge and Squeezer for now because they are mechanical and can be sped up
> fermentation takes time, can't be sped up, same with distilling
> and the bottler is pretty fast already
> fabricator is never slow either
