### ISSUE TITLE
Use ore dictionary in recipes where possible

### ISSUE THREAD

**Issue by labpaw** [ForestryMC/ForestryMC#801]
Forestry lack of ore dictionary support in its recipes. There are a lot of stuff using Items.redstone, Blocks.glass, Items.diamond and etc. What about changing these to ore dictionary counterparts?
Also, you might want to register chests under chestWood and use this in recipes (This was done in Forge 1.8 but this is needed for ganymedes01's mods for 1.7.10).

**Comment by mezz** [comment]
Yeah, sure! Forestry isn't picky about that kind of thing, so ore dictionary makes sense.
I usually add them as I see them, but haven't made an effort to do them all yet.

**Comment by Nirek-K** [comment]
I think I got all of them with https://github.com/ForestryMC/ForestryMC/commit/def51bada11bae88204c592571511e4a84bf08bd atleast of the ones that are in the dictionary by default with just forge. https://github.com/ForestryMC/ForestryMC/commit/79e0fabacbfb5f36585fb25e4f2f29232ac1ae27 for the chest buisness.

**Comment by mezz** [comment]
Sand is just "sand" huh? Mojang...
Quickly checked all the recipes and it looks good Nirek :+1: 
The only weird one I saw was multi-colored spectacles but I don't think it's a real problem haha

**Comment by labpaw** [comment]
[Blocks.stone -> "stone"](https://github.com/ForestryMC/ForestryMC/blob/79e0fabacbfb5f36585fb25e4f2f29232ac1ae27/src/main/java/forestry/plugins/PluginStorage.java#L596) maybe?
[Blocks.glass_pane -> paneGlassColorless](https://github.com/ForestryMC/ForestryMC/blob/79e0fabacbfb5f36585fb25e4f2f29232ac1ae27/src/main/java/forestry/plugins/PluginCore.java#L426) (should match better I guess) or paneGlass
[ingotGold here](https://github.com/ForestryMC/ForestryMC/blob/79e0fabacbfb5f36585fb25e4f2f29232ac1ae27/src/main/java/forestry/plugins/PluginFactory.java#L291)?
[gemDiamond](https://github.com/ForestryMC/ForestryMC/blob/79e0fabacbfb5f36585fb25e4f2f29232ac1ae27/src/main/java/forestry/plugins/PluginStorage.java#L618)?
[Blocks.stone -> "stone"](https://github.com/ForestryMC/ForestryMC/blob/79e0fabacbfb5f36585fb25e4f2f29232ac1ae27/src/main/java/forestry/plugins/PluginApiculture.java#L703)?
@mezz what about using blockGlassColorless in such recipes then?

**Comment by Nirek-K** [comment]
Figured I would miss some :p I'll get to those in a minute, re the color thing, not like colored/tinted glasses aren't a thing, don't think it would make a difference really.
Edit: and should be done with https://github.com/ForestryMC/ForestryMC/commit/19c13abd45ded786ce861d0e71e28abb88bdef95

**Comment by labpaw** [comment]
Thanks! That should be all of them.

**Comment by labpaw** [comment]
One more minor thing: Can you change [this](https://github.com/ForestryMC/ForestryMC/blob/19c13abd45ded786ce861d0e71e28abb88bdef95/src/main/java/forestry/plugins/PluginFactory.java#L231) to craftingTableWood and register this in OreDict? ganymedes01's Wood Stuff mod now adds plank based crafting tables.

**Comment by labpaw** [comment]
That was fast! Thanks again!
