### ISSUE TITLE
Support for Immersive Engineering Industrial Hemp

### ISSUE THREAD

**Issue by angelnc1989** [ForestryMC/ForestryMC#803]
Multi Farm support for IE Industrial Hemp would be great.

Mod: http://www.curse.com/mc-mods/minecraft/231951-immersive-engineering
Github: https://github.com/BluSunrize/ImmersiveEngineering

**Comment by Nirek-K** [comment]
Already exists in dev b5120991d5675c96355a34b913925d84ddb4187c

**Comment by Nirek-K** [comment]
To add to that, use unstable [639](http://jenkins.ic2.player.to/job/Forestry_Dev/639/artifact/build/dist/forestry_1.7.10-3.7.0.639-unstable.jar) if you want access to that now (don't go beyond 639 as it's alpha forestry 4 and incompatible with most addons and possibly worldbreaking)

**Comment by angelnc1989** [comment]
Thanks. I'll try 639.
