### ISSUE TITLE
Input for Molten Glass missing in native NEI Integration for the Thermionic Fabricator

### ISSUE THREAD

**Issue by Yulife** [ForestryMC/ForestryMC#804]
**Forge Version**: 1492
**Forestry Version**: 1.7.10-4.0.0.682-unstable
The input for the Thermionic Fabricator that uses glass to create molten glass is missing in the NEI Integration. [Pic](http://i.imgur.com/W6ukMbt.png)

**Comment by mezz** [comment]
Thanks for the report!
Fixed in the latest unstable build.

**Comment by Yulife** [comment]
:smile:
