### ISSUE TITLE
Implement no recipe conflict feature for worktables

### ISSUE THREAD

**Issue by labpaw** [ForestryMC/ForestryMC#805]
@ganymedes01 said that it's ok to see how he's done this in Gany's Surface mod.
[Here you can see how it was done for vanilla crafting table](https://github.com/ganymedes01/Gany-s-Surface/blob/master/src/main/java/ganymedes01/ganyssurface/client/gui/inventory/GuiCraftingTable.java). I would like to use this feature in Forestry's worktable.

**Comment by mezz** [comment]
Yep I've been thinking of adding this too. 
Here's a small commit that I thought might help us along, to get all the matching recipes instead of one: https://github.com/ForestryMC/ForestryMC/commit/1da8001b925da901acdb2eb98600cbe34fd425af
