### ISSUE TITLE
Make chests use the same model as the vanilla chest

### ISSUE THREAD

**Issue by buttilda** [ForestryMC/ForestryMC#806]
Forestry's chests still use the ancient full-block chest. Would be nice to see them updated to the vanilla model with the animated lid.

I looked into doing it myself briefly a while back and I couldn't find a way to do it without breaking existing worlds. I'm not very familiar with Forestry's source, so maybe it was just me being a derp.

I'd be willing to do this myself if I could figure out how to do it without breaking existing worlds (perhaps someone could point me in the right direction?), or if I was told that doing so was ok (the recent changes to the planks will already break old worlds, so maybe this is the right time to sneak this in?)

**Comment by Vexatos** [comment]
Actually they look quite cool together with [Cyclopean Chests](https://github.com/purpleposeidon/CyclopeanChests) :wink:

**Comment by mezz** [comment]
I'm trying to clean up world-breaking changes before the 4.0 release, see the issue here: https://github.com/ForestryMC/ForestryMC/issues/795

If you want, you can implement this in a branch and we can figure it out later.

**Comment by buttilda** [comment]
super :3 I'll get started :D
