### ISSUE TITLE
Add direction labels to circuit board for farm configurations

### ISSUE THREAD

**Issue by Indemnity83** [ForestryMC/ForestryMC#807]
It is very frustrating when setting up a managed or unmanaged farm because there doesn't seem to be any documentation or in game hints as to which position on the circuit board corresponds to which direction when inserted into the farm (from my testing it appears to be North, South, West, East?)

I think it would be very helpful to add a N, S, W, E label to the positions in the soldering iron GUI to help hint at the appropriate configuration when on the managed or unmanaged farm options.

**Comment by mezz** [comment]
Makes sense, thanks for the suggestion!

Note to self/implementer: This needs to be a little more advanced to handle the smaller circuit boards, since I believe one circuit slot can change multiple areas.

**Comment by mezz** [comment]
@Indemnity83 This should be the documentation you're looking for (the image under "Farm Orientation"):
http://forestry.sengir.net/wiki.new/doku.php?id=farms:programming#farm_orientation

You're correct, N S W E

**Comment by mezz** [comment]
![2015-10-03_22 08 21](https://cloud.githubusercontent.com/assets/916092/10266488/56b4ba3c-6a1b-11e5-8228-f943181fd570.png)

This has been added to the latest unstable build, and some other related things have been cleaned up. Now the circuits are put in clockwise from north: N E S W. Check it out!

**Comment by Indemnity83** [comment]
Awesome! Thanks. It looks good, and the order is more logical now too.
