### ISSUE TITLE
Stained Glass = Redundant?

### ISSUE THREAD

**Issue by buttilda** [ForestryMC/ForestryMC#809]
Sorry if this has already been discussed somewhere. I did a search on the repository and couldn't find anything.

Since vanilla added it's own coloured glass having one as well that looks very similar seems rather unnecessary... Why not remove them (making existing ones turn into the vanilla blocks) ?

For the picky players that will say they like the look of the Forestry ones better than the vanilla ones... there's always resource packs. The Forestry team could even publish one itself.

The crafting recipe using the Thermionic Fabricator could be maintained, but yielding (or course) the vanilla glass. I think it would be cool to have it as an alternative method of acquiring it that doesn't require sand.

**Comment by labpaw** [comment]
I'm almost completely sure that I suggested (or someone else) to remove stained glass too but the answer was "no". There are a lot of mods that adding their own stained glass and their authors won't remove it. However, maybe Forestry devs decision have changed.

**Comment by buttilda** [comment]
The only mod I can think of that also adds the feature is MFR, but their stained glass is not only for decoration, so I think it's "more okay", since theirs has an intricate and expensive recipes (though I still think it's somewhat repetitive)

**Comment by leagris** [comment]
Compared to Forestry stained glass. Vanilla stained glass recipe are OP.
I'd suggest forestry to suppress vanilla recipes for glass and yes, remove its now duplicate stained glass implementation.

**Comment by SandGrainOne** [comment]
When mods alters how a player obtain any resource used by other mods, it produce a lot of discontent. It is possible with a small unknown mod or plugin, but a mod with an existing presence should be very carefull with things like that. 

That being said I do whish more mods would do just that. Complexifying the crafting of building materials. Give the player more substantial reasons to automate the process.

**Comment by buttilda** [comment]
Could simply make it a config option whether or not to disable the vanilla recipe for the glass.

If you ask me... I think that since it's just a building material, there's no point being so concerned over it, it wouldn't break the balance of the mod if they suddenly became easier to get.

**Comment by mezz** [comment]
Agreed, there is no real purpose for Forestry's stained glass any more.
We should not change vanilla's recipe, it would be too unexpected. How about boosting the Forestry recipe to create more stained glass than the vanilla recipe?

**Comment by mezz** [comment]
Here's the previous comments on stained glass: https://github.com/ForestryMC/ForestryMC/issues/357

**Comment by buttilda** [comment]
I like the idea of making the Forestry recipe produce more glass.
What should the new quantity be? I think somewhere between 4-8, but Im not sure about an exact value. (I'm asking because I'm willing to submit a PR to fix this issue myself)

**Comment by Prospector** [comment]
Made a texture pack for the old textures https://www.dropbox.com/s/0vo21nz7dg7q4da/ForestryGlass.zip?dl=1
