### ISSUE TITLE
Game crashed after i catch the butterfly. Now, every time i load - crash instantly.

### ISSUE THREAD

**Issue by slayerain** [ForestryMC/ForestryMC#813]
Here is crash report, can anyone help me to solve this problem?

https://gist.github.com/mezz/7d34ef6a46d3fb3b46e6

**Comment by slayerain** [comment]
OK!.. It def was a butterfly. I opened map with MCEdit and found green item - where suppose to be a butterfly which i caught . I selected area and remove blocks with item, game loaded successfully.
Of course it is temporary solution, obviously that butterfly cause crash, which is weird bc another butterfly i caught didn't cause any problems. I think it was diana fritillary butterfly. Problem stays open!

**Comment by slayerain** [comment]
Hm... does anyone even check this forum? Have new information about this bug.
So. I built big building with auto-farm one on each other. On the top (obviously) the farm without scheme - doing trees. There generates butterflies under the dome. If i catch butterfly on the ground around beehives - nothing happens, but only i catch butterfly on my farm - crash instantly.

**Comment by Nirek-K** [comment]
This looks like it may be the same/related to #775 though that one was found in 4.0, have to wait for mezz to be back to be sure (he's currently away and will be back in the next few days) You could try updating to latest unstable and see if it's fixed, but doing so would make forestry wood vanish, and some addons can't cope with 4.0 yet. (definately make backups before trying that route, if you have worlds that matter to you)

**Comment by slayerain** [comment]
i see... well, i planing to stay on my map for a while, so i try not to put unstable versions. thought if report bug, he could make a bugfix that will be safely applyable on old version. 4.0 for 1.7.10?

**Comment by Nirek-K** [comment]
Forestry 4.0 is everything after unstable 639, it's for 1.7, it just has api breaking changes and refactors that addons will have to update for, and currently wood blocks disappear because they were rewritten (that will likely be changed before release in the next week or 2, better migration from 3.6->4) as well as multiblock inventories vanish (because they too were completely rewritten)

**Comment by mezz** [comment]
Thanks for the report! 
Sorry for the delay, I'll take a look soon.

**Comment by mezz** [comment]
Yep Nirek is right, it's the same issue. I'll port the fix to the stable branch.

**Comment by mezz** [comment]
This issue is from a farm trying to pick up a butterfly. It tries to read its genome as if the butterfly were a sapling.

Forestry Stable 3.6.4 has the fix and has just been uploaded to Curse. It will be available soon.
http://minecraft.curseforge.com/mc-mods/59751-forestry/files
