### ISSUE TITLE
GT crash related to recipe output

### ISSUE THREAD

**Issue by Leftorius** [ForestryMC/ForestryMC#814]
http://pastebin.com/fpnbdQHB
forestry_1.7.10-3.7.0.639-unstable works fine
all above doesn't work anymore and this crash does show up

**Comment by Nirek-K** [comment]
640+ is Forestry 4 alpha, which includes several api breaking changes, it's something on his end to fix.

**Comment by Nirek-K** [comment]
It 'should' see release sometime in the next week or two, assuming no gamebreaking explosions are found before then.

**Comment by mezz** [comment]
I don't know, it seems possible that the message is correct and we have a broken crafting recipe.

> Seems another Mod added a Crafting Recipe with null Output. Tell the Developer of said Mod to fix that.
