### ISSUE TITLE
Exception during loading Alveary Heater

### ISSUE THREAD

**Issue by SirJorah** [ForestryMC/ForestryMC#816]
Forestry stable 3.6.3.20
MC 1.7.10
Forge 10.13.4.1492

https://gist.github.com/mezz/6a946b836fb209942e90

**Comment by mezz** [comment]
Thanks for the report!
I'll take a look soon.

**Comment by mezz** [comment]
Forestry Stable 3.6.4 has the fix and has just been uploaded to Curse. It will be available soon.
http://minecraft.curseforge.com/mc-mods/59751-forestry/files
