### ISSUE TITLE
[3.6.x] BeekeepingLogic overwrites queen with old data

### ISSUE THREAD

**Issue by bdew** [ForestryMC/ForestryMC#817]
Happens if you swap a queen in any kind of bee housing without taking the old one out, on next bee tick the new queen will be overwritten.

This happens because the _queen_ field in BeekeepingLogic will only be unset (and then reloaded) if the queen itemstack is null or not a queen item. As long as it stays any kind of queen it will keep using the old data, and overwrite the item after the next bee tick.

Only occurs in 3.6, the new code in 4.0 detects that the itemStack was changed and reloads the data.

I'm not sure if you plan to make any more 3.6 bugfix releases but if you do i can make a fix PR.

(I also would really like to backport #815 to 3.6 if there will be another release)

**Comment by mezz** [comment]
Thanks for the report! BeekeepingLogic has been tricky to get right.
I'm happy to create more 3.6 builds with clear and simple bug fixes like these.
I'd like to get a 4.0 beta out in a week or two, and stable a bit after that. These fixes for 3.6 will be appreciated in the meantime.

**Comment by bdew** [comment]
Yay!
