### ISSUE TITLE
Thermionic Fabricator not working in Unstable

### ISSUE THREAD

**Issue by Bunsan** [ForestryMC/ForestryMC#819]
Tested latest unstable build 691 in both forge 10.13.4.1448 and 10.13.4.1492. Occurred in build 677 as well, have not tested any earlier version. The instance also contained NEI and dependencies along with NBTedit and WAILA. 

Thermionic Fabricator will not melt sand or glass. 

I connected a biogas engine directly to the machine. It fills the energy buffer. When sand or glass is put in melting slot the temperature marker does appear, but the temperature does not increase. 

The engine will run when glass or sand is placed in the slot for melting. However it does not output any energy and fills its buffer. Placing a valid recipe in the crafting interface and items in inventory does not effect. 

Using NBTedit I put 2000mb of liquid glass into tank 0. This allowed a craft to complete. Interestingly the volume of liquid glass continually decreases, independent of crafting. Using NBTedit I filled the tank with water, it's level was maintained, although I'm not sure if that is informative. 

So it seems it can accept energy, but not use energy (internal buffer does fill). It can signal to the biogas engine that it requires energy when glass is in melting slot. This is disabled by giving fabricator a RS signal as expected. It can have a fluid in tank 0, which is reflected in the GUI, but if fluid is liquid glass it continually drains. 

Let me know if you require more info.

**Comment by mezz** [comment]
Thanks for the thorough report! I will take a look soon.

**Comment by mezz** [comment]
Found the fix. When we changed the way machines use energy, each work cycle took 4x more energy, but the fabricator was still producing the same amount of heat. Increasing the amount of heat produced per cycle by 4x makes it work like before.
