### ISSUE TITLE
Forestry 3.6.5 crash on startup?

### ISSUE THREAD

**Issue by ButterChicken** [ForestryMC/ForestryMC#820]
Seems like version 3.6.5 of forestry uploaded on curseforge causes crash on startup. Using custom modpack.

Pastebin:
http://pastebin.com/AHLbWERZ

**Comment by mezz** [comment]
Thanks for the report!

Unfortunately I seriously doubt this is caused by Forestry.

Try updating Forge to the latest, you have `Forge 10.13.4.1448` and I spotted this in the recent change logs:

> Build 1.7.10-10.13.4.1452-1.7.10:
>     LexManos: Include the thread state in the potential error handleing for SplashProgress.

 If that doesn't work, please try removing Forestry and see what happens.

**Comment by ButterChicken** [comment]
Hi :grinning: 

Yes updating to latest version Forge 10.13.4.1492 fixes the crash. Thanks!

On a side note, removing Forestry 3.6.5 or downgrading to 3.6.4 also fixes the crash (using Forge 10.13.4.1448)
