### ISSUE TITLE
bee house and apiary in version 691 - invisible

### ISSUE THREAD

**Issue by utel** [ForestryMC/ForestryMC#821]
bee house and apiary in version 691 - invisible)))  uncomfortable to play)))

in 690 - works fine)

Thank)

**Comment by mezz** [comment]
Thanks for the report!
That's extremely weird. I'll take a look.

Edit: confirmed

**Comment by mezz** [comment]
Dev notes:
The new apiarist's chest shares a block with the bee house and apiary. Since @ganymedes01 changed the chest blocks to use TESR, the regular blocks have no renderer and become invisible.

I'm thinking I should split the block into two.

**Comment by buttilda** [comment]
Oh so THAT's why back when I first tried converting the chests to TESRs I realised I couldn't do it without splitting them into a new block.
Sorry about that ):

**Comment by buttilda** [comment]
~~This can, though, be done without having to do any breaking change. I have an ideathat might work. I'll send a PR as soon as I can~~ Nvm, it wouldn't work.

**Comment by mezz** [comment]
I moved the Apiarist's Chest to a new block. It should migrate automatically without losing its inventory. This should fix the invisible Bee Houses and Apiaries.
