### ISSUE TITLE
went to create Treealyzer, got a client crash.

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#822]
I had put the items to make the treealyzer in the carpenter and I got a client crash. 
http://puu.sh/k7aZ7/d883bdcf20.txt

Tried logging in thinking it may have been a fluke:
http://puu.sh/k7b2D/fed74e0518.txt

Started looking on these forums and noticed that forestry was updated so I updated the server and the client to the most current one.. tried running it again and still crashed.
http://puu.sh/k7b3G/1284291a47.txt

Can't get my client to log in.. Not really willing to delete character data, but I am willing to move it to see if I am able to log in.

**Comment by Nirek-K** [comment]
The first crash looks to be something related to "Lavaboat" doing something..bad, which is probably what's causing your issues.

**Comment by liach** [comment]
The first crash is simple, entity id conflict.

**Comment by mezz** [comment]
Thanks for the report!
I don't see anything here specific to Forestry, it's probably a coincidence that you were crafting a treealyzer when it crashed. Try temporarily removing the lava boat mod.

**Comment by ghost** [comment]
Removed lavaboad mod from the server and the client... for whatever reason that did fix it even though the lava boats have never been used.

**Comment by mezz** [comment]
Glad it worked. I really have no idea. Try reporting it to them and see if they know!

**Comment by ghost** [comment]
Thanks. I'm sending it to him now. Not that I use it, but maybe someone does with Forestry
