### ISSUE TITLE
BuildCraft planter robot and Forestry saplings

### ISSUE THREAD

**Issue by Amelia-** [ForestryMC/ForestryMC#824]
They do not like each other, well the robot doesn't seem to like the saplings and does not want to pick them up or plant them.
There is an issue about it on the BuildCraft GitHub here: https://github.com/BuildCraft/BuildcraftCompat/issues/12 and it is stated there that it is on the Forestry side so I decided to report the issue here.
I am currently using Forestry 3.6.5.23, BuildCraft 7.0.23 and BuildCraft Compat 7.0.12 and the issue is present with that combination.

**Comment by mezz** [comment]
They should work fine at this point, it's checked off the list (i.e. fixed by Forestry).
@asiekierka any idea what the issue might be? Saplings implement the `IGrowable` interface.

**Comment by asiekierka** [comment]
I think what happened is that we fixed it but then forgot to implement IGrowable back after the 7.0 crop system rewrite.

**Comment by mezz** [comment]
Talked with asie on IRC, fixed on their side.
