### ISSUE TITLE
Legacy support for Binnie Mods until Binnie updates his?

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [ForestryMC/ForestryMC#825]
Howdy,

I'd ask if it were possible to add some sort of legacy support to the unstable builds for Binnie's latest Binnie Mods until Binnie updates his mods again?

Binnie has quite long downtimes in between his updates, and I love using Binnie's mods with forestry. However, Forestry has a very fast update pace, and thus Binnie's mods don't work anymore.

**Comment by mezz** [comment]
I will avoid breaking the API but I can't avoid breaking Forestry-internal things that Binnie's mods depend on. I am working on better APIs for Binnie's mods and others, to have a stable contract that I can avoid breaking in the future.

For now the legacy support is the Stable builds. They still receive bug fixes and they truly avoid breaking things as much as possible.
