### ISSUE TITLE
Only add blocks to backpacks if storage module is enabled

### ISSUE THREAD

**Issue by labpaw** [ForestryMC/ForestryMC#826]
If you have storage module disabled in Forestry 691 unstable and Biomes O Plenty is installed, you'll get a crash. Should be really easy to fix, just make sure that storage module is enabled before adding Biomes O Plenty blocks to backpacks.
Versions:
BoP 1394
Forestry 691 unstable
Forge 1492
Log: http://pastebin.com/ADQKVGg1

**Comment by mezz** [comment]
Thanks for the report! Should be an easy fix.

**Comment by mezz** [comment]
The other plugins already check for the storage module. The BoP plugin didn't because I ported the backpack part directly from their code without thinking too much about it. Fixed in unstable.
