### ISSUE TITLE
Request compatibility with Erebus Bucket of Honey 

### ISSUE THREAD

**Issue by vadis365** [ForestryMC/ForestryMC#831]
Could you tell me if you register your items anywhere in the oreDict?
If so, where? I would like to make The Erebus bucket of honey/honey fluid interchangeable with honey from forestry for some cross mod goodness.

**Comment by Nirek-K** [comment]
The fluid honey is named for.honey  , honey drops the item are in the oreD as dropHoney. depending on the specifics I might be interested in making it as a plugin in forestry internal. Feel free to pop in on irc and/or write it here.

**Comment by vadis365** [comment]
We have giant worker bees and giant flowers that have a basic farming system implemented whereby wild bees are tamed, homed on a honeycomb container block, fly to a flower, collect nectar and put it in the 'honeycomb' block. Nectar is smelted in to honey drips (until an evaporation chamber and centrifuge blocks are made).
The system is due for an update on the bees' flying and pathing AI as it was coded over a year ago and can be implemented better now. We have a basic fluid honey and buckets etc. I would ideally like to make this system compatible with forestry honey as it would provide a good cross mod platform for bio-fueled engines and an alternative build tree for Erebus users to implement some features of Forestry (and vice versa). And who wouldn't want to see giant bees flying around and powering their forestry machines? ;)

Some pictures from when we 1st made them.
http://imgur.com/a/M6Jmz

**Comment by vadis365** [comment]
Created a new issue on the Erebus Git with regards to this
https://github.com/ganymedes01/TheErebus/issues/335
I think it would probably be better to handle it at our end for the time being as The Erebus is in a state of flux often (code-wise and team availability).

**Comment by vadis365** [comment]
Hello,
Tested a few things out and found out our honey is registered the same as your old legacy honey in the Fluid registry therefore the support you have added to the Still allows for easy conversion of the Fluid. I have added oreDict names for the Erebus 'Honey Drip' to be compatible with the forestry 'Honey Drop' which allows for some cross mod crafting. Unfortunately it seems the Forestry Squeezer will not accept the Erebus 'Honey Drip'. Is this something to do with mod specific items only being allowed in the Gui/Container or is the Squeezer not oreDict sensitive on item input? With the use of Build Craft and Thermal Expansion (for some automation crafting and fluid extraction) I have found that The Erebus Worker Bees can now indeed provide honey to process in the Forestry Squeezer which can power Forestry Bio-gas Engines :)
Thanks for your insight and helpfulness - I guess I should close this issue as, well, it is no longer an issue.
Thanks again,
Vadis365 (The Erebus)

**Comment by vadis365** [comment]
*Post Script
Erebus honey production (pre-Still conversion) :P
http://imgur.com/hrh3Sye
http://imgur.com/LLGpnci

**Comment by Nirek-K** [comment]
I don't think the squeezer pulls from the oreD for that particular recipe. Unless you mean a recipe you're adding on your side.  Adding a recipe with the api should be pretty straightforward, or I can plop it in a plugin, just need the modID and full item name

**Comment by vadis365** [comment]
MOD_ID = "erebus";
erebus.ModItems.materials
metadata is 21 for honeyDrip

Item Registry here:
https://github.com/ganymedes01/TheErebus/blob/master/src/main/java/erebus/ModItems.java

ItemMaterials here:
https://github.com/ganymedes01/TheErebus/blob/master/src/main/java/erebus/item/ItemMaterials.java

I hope this is what you need ;)

**Comment by Nirek-K** [comment]
https://github.com/ForestryMC/ForestryMC/commit/901318c2b08ceceb90b6239e54472c2aa4d3b635 give that a try, unstable 699, (note unstable is forestry 4 alpha and won't work with most other addon mods)

**Comment by vadis365** [comment]
Thanks mate. I'll give it a try and report back :)
