### ISSUE TITLE
Request: Allow Backpack upgrades when bees are disabled

### ISSUE THREAD

**Issue by JFMillerUSA** [ForestryMC/ForestryMC#832]
I don't use Bees in forestry. Can there be a better way to upgrade the backpacks. Plus More backpacks addon crashes my minecraft.

**Comment by mezz** [comment]
Hello, thanks for the suggestion.
Can you be more specific? What kind of upgrades are you looking for?

**Comment by JFMillerUSA** [comment]
using woven silk, any other way to make woven silk with out bees. Or maybe just upgrade back pack to next level with same setup like miners with wool, string, iron ingot and instead of chest use old Miners Back Pack.

**Comment by mezz** [comment]
Ah that makes sense.
I think ideally there should be an alternate recipe for woven silk when bees are disabled.
