### ISSUE TITLE
Carpenter destroys fluid containers that use IFluidContainerItem in the container slot.

### ISSUE THREAD

**Issue by EXTER7** [ForestryMC/ForestryMC#834]
When placing a fluid container that implements IFluidContainerItem (like TE portable tanks) in the Carpenter's container slot, the container is destroyed completely instead of returning the empty container.

**Comment by mezz** [comment]
Thanks for the report!
Confirmed, taking a look.

**Comment by mezz** [comment]
Fixed in the unstable build, should be included in the next stable patch at well.

**Comment by mezz** [comment]
Submitted Forestry 3.6.7 to Curse with this fix.
