### ISSUE TITLE
No remote version authority for Update Checker

### ISSUE THREAD

**Issue by bookerthegeek** [ForestryMC/ForestryMC#840]
[15:39:04] [Thread-14/WARN] [Forestry]: Unable to read from remote version authority.

This is with the Forestry version 3.6.6.24

Does not crash the game.

**Comment by mezz** [comment]
Thanks for the report!
The update checker hasn't worked in a long time, but it's good to have an issue here to keep track of it.

**Comment by Holi0317** [comment]
Just a suggestion,

How about putting changelog and version to Github? Like what Vazkii has done for Botania.

As Github does not have traffic control, fetching version will most likely to success.

**Comment by mezz** [comment]
Since Forestry is on NotEnoughMods, you can use the [VersionChecker mod](http://www.curse.com/mc-mods/minecraft/221140-version-checker) to see if Forestry is updated.
I will remove Forestry's version checker in 1.8+
