### ISSUE TITLE
Can't remove private chest

### ISSUE THREAD

**Issue by Avarones** [ForestryMC/ForestryMC#841]
Hello.

I am playing The-1.7.10-Pack from Technic updated.
Earlier I set to my apiarist chest to be private (single player, I dont know why I did that lol). Now I started to play again and it doesnt open, I am receiving the following message:

Avarones is the owner of this machine and has locked access.

What can I do to solve it? I cant destroy it, even in creative mode =/

**Comment by mezz** [comment]
Server operators should be able to remove private inventories, enter `/op Avarones` at the chat and then try.

I'll test this out, I'm not sure why you'd get locked out in the first place.

**Comment by Avarones** [comment]
Hey mezz, thanks for answering. 

The game doesnt recognize the command /op.. I receive back a message; "Unknown command. Try /help for a list of commands"

And yes, I am an Idiot, its my first time with forestry, and when I saw the new menus I clicked on them to test what happens...

**Comment by mezz** [comment]
I tried to do what you did but I had no problem accessing my own private machine.
Do you have a cracked Minecraft or something? Forestry uses Mojang's authentication server to figure out if you're the real owner, instead of just depending on the user name.

**Comment by Avarones** [comment]
Its not cracked, I am using a Mojang account with a copy of the game active on Technic Launcher. That's why I dont understand what is happening, I'm playing with "Avarones" account, and the game say that just Avarones can open it.

**Comment by liach** [comment]
He is not playing a dedicated server but an integrated one. There is no `/op` command on the integrated server. So you might want to open your save game to the network in pause menu and choose to allow cheat.

**Comment by Nirek-K** [comment]
In SSP it can get a bit weird as to if you're an op, in your own game. If you didn't enable cheats when you started the world, you're not op, which is dumb but whatever. You can 'Open to LAN' to be able to enable cheats and salvage a world like that. (There are other oddities if you login while auth servers are down, your gameprofile will also be different)

**Comment by Avarones** [comment]
Well, I Opened to LAN, set /gamemode 1 (creative) and tried to destroy it or to enter /op.

Both failed, getting same error that I had before

**Comment by mezz** [comment]
@Avarones make sure you choose "Allow Cheats: ON" from the "Open To Lan" option screen. Creative mode isn't enough by itself.

**Comment by Avarones** [comment]
Yes, I did it, that's why I could use /gamemode.

**Comment by mezz** [comment]
Ok sorry this is such a huge pain. Time to break out the big guns.

Install this mod: [In-game NBT edit](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286750-in-game-nbtedit-edit-mob-spawners-attributes-in)

Get near the machine, looking at it, and then type `/nbtedit`
Click the arrow next to the `ROOT` tag compound, and then the `owner` tag and please take a screenshot with F2 and post it here so I can find out what is happening exactly.

To fix your issue, select the `Access` tag and edit it so the value is 0 and save it. This will set the machine to public access again.

**Comment by Avarones** [comment]
Ok, I'm going to try to install it inside the Technic modded game, I never tried before.

**Comment by Avarones** [comment]
I think you guys are hating me hahaha

I did it, but when I type /nbtedit, I "lose connection", and I receive: A fatal error has occured, this connection is terminated.

**Comment by mezz** [comment]
Ugh sorry, looks like the topic I posted doesn't have the right version for 1.7.10.
Here it is: https://github.com/MoeBoy76/NBTEdit/releases
Use `NBTEdit-1.7.10-2.0.jar`

**Comment by Avarones** [comment]
Same thing happening =/ it closes the connection

**Comment by mezz** [comment]
That means the "server" part of the game crashed. Can you post the latest crash log from the `crash-reports` folder to www.pastebin.com and link it here? The `crash-reports` folder is next to the `mods` folder you installed the mod.

**Comment by Avarones** [comment]
I can do it, but the last file there were updated 09-23, I dont think it generated a log there.

**Comment by mezz** [comment]
Ok post your latest server log instead then, in the `logs` folder (same place as mods and crash-logs)

**Comment by Avarones** [comment]
Done

http://pastebin.com/rsH1i4X8

**Comment by mezz** [comment]
Ok it looks like you're failing client authentication with Mojang.

```
[03:18:54] [Client thread/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@3f8d0785[id=cc14e562-fdaa-4c40-a79e-75a4477c3ec5,name=Avarones,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
```

The log shows it's caused by Morph and it's a known issue apparently: https://github.com/iChun/Morph/issues/600

The problem should go away after a while.

**Comment by mezz** [comment]
@Avarones did you have any luck now that a few days have passed?

**Comment by Avarones** [comment]
Hey mezz, Nop, today I tried again and the error kept occuring. So I started a new game, I felt frustrated with some mistakes (including this one) and Started again :smile:
