### ISSUE TITLE
Villager trading showcase Log with wildcard meta

### ISSUE THREAD

**Issue by leagris** [ForestryMC/ForestryMC#846]
Forestry stable 3.6.6.24

Villager logWood showcase has a wildcard meta: `Oak Wood (#0017:32767)`, then an all bark jungle log is shown:

![2015-09-26_13 48 29](https://cloud.githubusercontent.com/assets/1111474/10117402/1486885e-6456-11e5-9e97-a8ff36935a67.png)

I think it should be best to rotate icons from OreDictionary list name logWood as it is done with NEI Recipes.

**Comment by mezz** [comment]
Thanks for the report!
That's some pretty weird looking "oak wood" you have there haha

**Comment by mezz** [comment]
Looks like this problem has not been solved before. The code is very inflexible because it's mostly vanilla code, but I'll see what's possible.

One possible backup solution is to have the villager only accept one type of vanilla wood planks, making it a bit harder to satisfy the request.

**Comment by mezz** [comment]
Unfortunately the item displayed is the same item used to compare for the trade, and there's no way around it.

**Comment by mezz** [comment]
Fixed by this commit, the villagers now accept specific planks.
https://github.com/ForestryMC/ForestryMC/commit/fb7cd3ee096db729b07b0be9162a5c25ccf4eaf5
