### ISSUE TITLE
Trade Station does not empty to attached conduit/transport pipe: Forestry 3.6.3.20 &  3.6.7.25

### ISSUE THREAD

**Issue by Deweyoxberg** [ForestryMC/ForestryMC#847]
The Trade Station availabe in Forestry 3.6.3.20 and 3.6.725 does not empty into attached inventories/pipes/conduit.

We have tried Ender IO item conduit, BC transport pipes and a basic logistics pipe. We can pump IN to the Trade Station but cannot pump out; is there a specific face which must be used for export?

We did verify the access is set to shared.

A BC gate set to export does do a pump animation but nothing happens.

**Comment by Nirek-K** [comment]
At one point you could pull product from it, looks like it got lost at some point along the way, will give it a prod.

**Comment by Deweyoxberg** [comment]
Wonderful news! Excited to keep my eyes out for this. Thanks for such a speedy reply.

**Comment by Nirek-K** [comment]
Should be fixed in the unstable from that commit (711), might get backported to the next stable.
