### ISSUE TITLE
Smallest farm size is 17x17 instead of 21x21

### ISSUE THREAD

**Issue by estebes** [ForestryMC/ForestryMC#848]
http://i.imgur.com/pf6yv2t.jpg
Using forestry 4.0.0.700

**Comment by mezz** [comment]
There is a config option for the size in `forestry/common.cfg` now.

```
# Sets the size multiplier of the farmland. [range: 1 ~ 3, default: 2]
tweaks.farms.size
```

1 is the old size, 3 is the size from recent versions.
Version 4.0 is going with the size in between.

**Comment by estebes** [comment]
Thanks. Did not catch that in the changelogs
