### ISSUE TITLE
Incompatibility with ModTweaker and MineTweaker [Forestry 4.0]

### ISSUE THREAD

**Issue by Filvandrel** [ForestryMC/ForestryMC#850]
https://gist.github.com/mezz/3237b128bef899aea4c6

**Comment by liach** [comment]
Ask ModTweaker author to upgrade. `at modtweaker2.mods.forestry.Forestry.(Forestry.java:17)`

**Comment by Filvandrel** [comment]
I've deleted ModTweaker, and got this:

https://gist.github.com/mezz/01197491956fc69905a6

**Comment by Nirek-K** [comment]
That 2nd one is the same as issue 849.

**Comment by mezz** [comment]
Dupe of #849: Reika's DragonAPI is not compatible with Forestry 4.0 beta yet.

**Comment by mezz** [comment]
Actually leaving this open for the first crash, with ModTweaker/MineTweaker as part of the crash.

**Comment by mezz** [comment]
ModTweaker is working on an update: https://github.com/jaredlll08/ModTweaker2/issues/252

**Comment by mezz** [comment]
ModTweaker has a pre-release version available here: https://github.com/Voidi/ModTweaker2/releases/tag/0.9.5
