### ISSUE TITLE
Request for re-addition of arboretum and peat bog.

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#852]
Here is the old code for Forestry before their removal if a porter wants reference material:

https://github.com/ForestryMC/ForestryLegacy

My personal suggestion is limit the Arboretum and Logger to vanilla trees.

**Comment by nanakisan** [comment]
I agree entirely with the idea of using only vanilla trees as well. However it should also be able to only harvest vanilla tier 1 forestry trees. Such as the apple tree and subsequent fruit trees.

**Comment by LuigiHutch** [comment]
Well someone had started porting the old farms to 1.7.10 as an addon. See:
https://github.com/covers1624/LegacyFarms

**Comment by PrincessOfEvil** [comment]
Maybe we could add them as low-tier versions.

2015-09-28 19:28 GMT+06:00 LuigiHutch notifications@github.com:

**Comment by immibis** [comment]
AFAIK, they were removed because the new farms made them redundant. What do they add that isn't in the new farms?

**Comment by SandGrainOne** [comment]
There where 2 reasons for why I didn't immediatly approve of the new farms.
1. They removed the need for logistics between a planter and a harvester. (I don't like it when mods remove the player involvement in automation.)
2. Specifically for the Arboretum the multifarm removed the need to craft Humus. (For the same reason as above.)

When that is said I'm still against adding the old farms back. Point 1 was a tiny one as I needed 3 pices of piping. The second one can be "fixed" with multifarms.

**Comment by immibis** [comment]
IMO, there's not much point in including two game mechanics where one is clearly superior, just in case players want to use the weaker one to give themself more stuff to do. That means adding the old farms is pointless unless multifarms are also removed.
