### ISSUE TITLE
Wooden blocks Rendering Translucent.

### ISSUE THREAD

**Issue by Bunsan** [ForestryMC/ForestryMC#854]
So I've noticed an issue with rendering of all wooden items. I have not come across other items, but have not tested extensively yet.

This is tested in forge 1448 with Forestry 4.0.0.27. Other mods present are notenoughitems-1.7.10-1.0.5.111-universal and codechickencore-1.7.10-1.0.7.47-universal.

All these issues are shown in this album. http://imgur.com/a/NTYlT
To summarize. 
- If player has enchanted item in hotbar, does not need to be held, the wooden items in hotbar render translucent. 
- If item is dropped on ground it will render translucent when certain blocks around it are highlighted. It also appears translucent while being picked up.
- If player has enchanted item in personal inventory or any TE inventory, highlighting some but not all inventory slots will cause items to render translucent. This is inconsistent. The same effect is seen if enchanted item is placed in player crafting interface. In addition it also effects the armour gui and GUI title text.

**Comment by mezz** [comment]
Thanks for the report!
That's super strange looking, I'm sure it's a simple OpenGL mistake. I'll see if I can reproduce the issue.

**Comment by Bunsan** [comment]
If it helps diagnose I'm on a Mac running 10.10.5. AMD Radeon HD 6770M 512MB. Can't seem to figure out what OpenGL version.

Edit: apparently OpenGL 4.1

**Comment by mezz** [comment]
Ok confirmed it's happening and I have the opposite setup from you, Windows with Nvidia.
I typically have weird effects with enchantments (potions and bees have a solid glowing background) so I don't really notice issues like this. I'll see what I did with the farm blocks to make sure they render right.

**Comment by mezz** [comment]
Looks like I wrote the Farm ItemBlock renderer with extremely defensive OpenGL, should be an easy fix to copy that to the other renderers.

**Comment by mezz** [comment]
[Fixed and uploaded Forestry 4.0.1 to curseforge](http://minecraft.curseforge.com/mc-mods/59751-forestry/files). Should be up soon.
