### ISSUE TITLE
Crash when clicking the fluid slot in NEI squeezer recipe

### ISSUE THREAD

**Issue by oldjunyi** [ForestryMC/ForestryMC#856]
![temp](https://cloud.githubusercontent.com/assets/641817/10168110/e906ca72-66fd-11e5-9959-a48f5030b954.png)

crash-report: https://gist.github.com/oldjunyi/4a969cfdbbcd6a4ed9f3
fml-client-latest.log: https://gist.github.com/oldjunyi/6c5d0df7fcb1aaa29eaf

**Comment by leagris** [comment]
NEI may not yet be compatible with Forestry 4
https://gist.github.com/oldjunyi/4a969cfdbbcd6a4ed9f3#file-crash-2015-09-29_23-06-04-client-txt-L101

**Comment by mezz** [comment]
Thanks for the report!
It should be compatible, NEI Integration is built in to Forestry 4.
I'll take a look.

**Comment by mezz** [comment]
Fixed in the latest unstable build, will be included in the next 4.0 patch as well.
