### ISSUE TITLE
Crash with Binnies Mod pre14 [Forestry 4.0]

### ISSUE THREAD

**Issue by Dream-Master** [ForestryMC/ForestryMC#857]
Using Forestry 4.0.2.30 and Binnies Mod pre14

https://gist.github.com/Dream-Master/e17f52f06eb399258d9a#file-forestry

**Comment by mezz** [comment]
Forestry 4.0 breaks some API stuff, it'll probably be a while before Binnie updates.
It has been reported here: 
https://bitbucket.org/binnie567/binnie-mods/issues/334/crash-with-newest-forestry-4

**Comment by stclaus4** [comment]
is this all forestry 4.0 or is it fixed in a version yet? I got 10.39 and it seems still broken

**Comment by Parker8283** [comment]
This is all forestry 4.x.x.x versions.

**Comment by Unrepentant-Atheist** [comment]
It's not just Binnie's mods...a few other mods also break due Forestry doing some stuff....

**Comment by mezz** [comment]
So far these are the known incompatibilities. If you know of more please report them.
https://github.com/ForestryMC/ForestryMC/labels/Incompatibility

**Comment by mezz** [comment]
This can be worked around with [Chocohead's Binnie Patcher](http://forum.feed-the-beast.com/threads/1-7-10-binnie-patcher.143722/)

Report issues here: https://github.com/Chocohead/Binnie-Patcher/issues
