### ISSUE TITLE
GT Tools support in Worktable not completly fixed

### ISSUE THREAD

**Issue by antkatcin** [ForestryMC/ForestryMC#858]
While testing https://github.com/ForestryMC/ForestryMC/issues/750 issue i found another one. Order of the GT tools in table inventory is important. Worktable works good only if required tool goes first. E.g. take a look to screenshot. Everything works fine until you put file after any of the hammers in table inventory:
![gt_tools_work_fine](https://cloud.githubusercontent.com/assets/3091327/10178057/5b27ff56-671f-11e5-8480-9fe585e3562d.png)
![gt_tools_not_working](https://cloud.githubusercontent.com/assets/3091327/10178069/63b2c30e-671f-11e5-8e42-5ab587a56504.png)
Tested with version 1.7.10-3.6.9.28

**Comment by mezz** [comment]
Thanks for the report!
I see the problem, both tools use the same item with different meta.
To the worktable, they look like different damages on the same tool, so it tries to use the hammer and fails.
