### ISSUE TITLE
Multi Farm using single tube upgrade cannot set the direction

### ISSUE THREAD

**Issue by sfchipan** [ForestryMC/ForestryMC#859]
![20150929170607](https://cloud.githubusercontent.com/assets/4555814/10211488/427ad3ea-6826-11e5-84b3-f5a82d753545.jpg)
It seems that if just one tube used to upgrade it can only put into the first slot.
Could you make other direction available? Thanks.

**Comment by mezz** [comment]
![2015-10-03_22 50 48](https://cloud.githubusercontent.com/assets/916092/10266632/3eb63810-6a21-11e5-9ac6-d7c3f70c17a7.png)

Thanks for the report!
Fixed in the latest unstable build.
