### ISSUE TITLE
The output of orchard farm

### ISSUE THREAD

**Issue by sfchipan** [ForestryMC/ForestryMC#860]
![1](https://cloud.githubusercontent.com/assets/4555814/10211693/5069de36-6828-11e5-8f4e-621dcd3027b3.JPG)
![2](https://cloud.githubusercontent.com/assets/4555814/10211697/627cb904-6828-11e5-82f8-6a29bed4a08c.JPG)
When the orchard farm havest wheat, the output seems more than usual. I test it using just one block. The output is totally 4 seeds. (three in the gui, one have been plant again)

**Comment by Nirek-K** [comment]
In theory it can be 1 more than standard, yes. Running orchard costs significantly more water/fert per action though.
