### ISSUE TITLE
client crash - updating screen events - worktable

### ISSUE THREAD

**Issue by Terpo** [ForestryMC/ForestryMC#861]
http://pastebin.com/iQ6y2P45

Its a more or less random crash when using the forestry worktable. My server member told me that there are sometimes problems that you can't craft the item even if the ingredients are there.

forestry_1.7.10-3.6.7.25.jar
Forge #1448
http://blog.terpo.org/upload/mc/modlist.txt
no optifine

**Comment by mezz** [comment]
Thanks for the report!
@Terpo Can you let me know what you were crafting so I can reproduce the issue?

**Comment by Terpo** [comment]
My member can't remember what he was crafting. I did not get such a crash, but I will try to reproduce it somehow^^.

OK... now I got some recipes: mainly gendustry stuff: he was crafting most of the machine like the mutatron and so on ;)

**Comment by mezz** [comment]
The crash should be fixed in 3.6.10. I'll be uploading it shortly.
If the worktable is still giving them trouble, they may need to wait for Forestry 4.0 stable.
