### ISSUE TITLE
Forestry incompatible with Highlands

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ForestryMC/ForestryMC#866]
https://gist.github.com/DPxKnightxZero/950dd154f15efe7b3e2f

**Comment by mezz** [comment]
Looks like Highlands is trying to use an old version of Forestry's Flowers API and crashing.
Unfortunately I don't think the 1.7.10 version has been updated in over a year https://github.com/fabricator77/Highlands

**Comment by P3rf3ctXZer0** [comment]
Anyway to attempt backwards compatibility or could you use Highlands source and make necessary fixes? I would honestly do it myself but I lack the understanding of Java ... I am mentally incapable of dealing with numbers and code so I resigned myself as a debugger.

**Comment by mezz** [comment]
I tried to get it up and running but it depends on a much older version of Forge, so I can't get it to work well with Forestry at all. It would require a minor update to Highlands but I'm not sure anyone is making new releases for 1.7.10, all the recent development is for 1.8.

**Comment by labpaw** [comment]
This can be easily fixed. The most important problem here is that fabricator77 isn't updated source code to 2.2.3 version of Highlands.

**Comment by P3rf3ctXZer0** [comment]
Can't someone with skill just update it? Clearly since this is old it needs to be updated.

**Comment by mezz** [comment]
@fabricator77 would you accept a PR to Highlands to update it for Forge 1.7.10 and Forestry 4.0?

**Comment by mezz** [comment]
Fixed in the latest unstable build
