### ISSUE TITLE
Last tin can won't be consumed in GUI

### ISSUE THREAD

**Issue by sfchipan** [ForestryMC/ForestryMC#868]
https://youtu.be/tQGMv10L2Fs
version: 4.0.6.736

**Comment by mezz** [comment]
Thanks for the report!
I thought it should keep the can if there is only 1 in the slot... but it just looks like a bug. I will make it consume all the cans.

By the way, I see you have a video spotlight of Forestry!
I don't understand Chinese but it looks like you explain Forestry very well.

**Comment by sfchipan** [comment]
I just thought if a empty can stay in there, it will block other water can be transported in farm with pipes.
Thanks! Forestry is one of my favorite old mods. Its content is also innovative and original by now. So I think it is a great contribution for the whole mod community.

**Comment by mezz** [comment]
Fixed in the latest unstable build
