### ISSUE TITLE
Analyzer turns pollen into saplings

### ISSUE THREAD

**Issue by eissceda** [ForestryMC/ForestryMC#870]
The analyzer turns pollen placed inside into saplings before he analyzes them.

I detected this in an older version (3.6.3.20) where I tossed some into an analyzer to find out why they don't stack.
But it also happens in the latest version (4.0.6.34) with no other mods enabled.

**Comment by mezz** [comment]
Thanks for the report!
I'll fix this soon.

**Comment by mezz** [comment]
![2015-10-06_20 17 59](https://cloud.githubusercontent.com/assets/916092/10328600/dbba67ca-6c6b-11e5-9ca3-f0715294f893.png)

Works now, I'll release minor updates for 3.6 and 4.0
