### ISSUE TITLE
Crash with BoP installed

### ISSUE THREAD

**Issue by KIdWither** [ForestryMC/ForestryMC#871]
After installing Forestry version 4.0.6.34 , I received the crash bellow with BoP version 2.1.0.1067. So I moved the mod over to a separate instance to get the crash log for just Forestry and BoP.

Crash log: http://pastebin.com/yKEGpmAS

**Comment by mezz** [comment]
Thanks for the report!
It looks like they made an update for Forestry recently, try grabbing the latest 1.7.10 version (2.1.0.1396+) from here: http://files.minecraftforge.net/BiomesOPlenty/

**Comment by labpaw** [comment]
1395+ should work fine.

**Comment by KIdWither** [comment]
Ok thanks did not know the curse version of BoP was out of date.

**Comment by KIdWither** [comment]
Sorry had no idea that I an out dated version of BoP and that was causing the error

**Comment by mezz** [comment]
Cool, glad it's resolved.
