### ISSUE TITLE
Add trees to world generation

### ISSUE THREAD

**Issue by mezz** [ForestryMC/ForestryMC#872]
There should be some basic, nice-looking Forestry trees spawning in the wild.
- Config option to disable
- Should only be added once https://github.com/ForestryMC/ForestryMC/issues/853 is complete (better looking trees with more branches).
- Trees should have basic stats, not highly desirable ones obtained through breeding
- Climate-specific generation, like the bee hives

The purpose is to make the world look nicer and make it easier to obtain different Forestry woods and leaves.
This will need to be tested with Biomes O Plenty and ExtraBiomesXL.
It must not greatly short-circuit the mod's progression.

**Comment by leagris** [comment]
4.1.0.775-unstable
Command: `/forestry tree spawnforest <treespecie>`
Tree base don't follow terrain shape but is all deployed at player feet y coordinate.
This cause some trunks floating mid-air or replacing ground blocks.

Would be nice to allow some wildcards for species, weight, density and diameter
Could look like:
`/forestry tree spawnforest  <specie>[:<weight>][,<specie>[:weight]][,…] [<diameter] [<density>]`
specie: specie name or default (worldgen rule usually biome dependant), or \* for any
weight: between 0.0 and 1.0
diameter: int blocks (default 16 blocks)
density: count/diameter (default 4)

Samples:
`/forestry tree spawnforest default` Generate worldgen default forest on 16 blocks diameter max 4 trees

`/forestry tree spawnforest appleoak:.33,birch:.66 64 20` Generate 1/3 oaks, 2/3 birches on a 64 blocks diameter disk with 20 trees per 64 blocks.

`/forestry tree spawnforest *oak` generate any kind of oak (dark, apple) on 16 blocks diameter at 4 trees per 16 blocks.
