### ISSUE TITLE
Crash with NEI Integration

### ISSUE THREAD

**Issue by Marti2203** [ForestryMC/ForestryMC#873]
I tried to check a recipe in NEI and the game crashed. Here is a crash report  http://pastebin.com/FZLLCRtJ

**Comment by KIdWither** [comment]
The crash happens when NEI integrations forestry module is loaded (same thing happened to me), just go into the configs and disable forestry integration

**Comment by Marti2203** [comment]
Thank you.

**Comment by mezz** [comment]
Yep, NEI Integration is built in to Forestry 4.
Hopefully it can auto-detect Forestry 4 and disable integration.
Check here for any updates: https://github.com/Tonius/NEI-Integration/issues/84

**Comment by mezz** [comment]
NEI Integration has an updated version that works with Forestry 4.
