### ISSUE TITLE
Crash (Gendustry) [Forestry 4.0]

### ISSUE THREAD

**Issue by tomownu21** [ForestryMC/ForestryMC#874]
http://pastebin.com/kk88fH6U
keep geting this crash i have tryed downgrading and updating and nothing seems to work

**Comment by mezz** [comment]
Gendustry has a "fu" (Forestry Unstable) build that works with Forestry 4.
[You can find it here under "Other Downloads".](http://www.curse.com/mc-mods/minecraft/gendustry#t1:other-downloads)
