### ISSUE TITLE
HarvestCraft compatibility: wrong recipe.

### ISSUE THREAD

**Issue by OneEyeMaker** [ForestryMC/ForestryMC#876]
Hello.
I found one incorrect fermenter recipe with HarvestCraft item: I can get biomass from Mustard seed. 
There are two items in HarvestCraft with that name - 'seed' = `harvestcraft:mustardseedItem` and 'fruit' = `harvestcraft:mustardseedsItem`. Now there is registered fermenter recipe with wrong one (`harvestcraft:mustardseedItem`, not `harvestcraft:mustardseedsItem`), and there's no squeezer recipe, that produces seed oil from `harvestcraft:mustardseedItem`.

Please fix it there: https://github.com/ForestryMC/ForestryMC/blob/dev/src/main/java/forestry/plugins/PluginHarvestCraft.java

P. S. Sorry for my English, I'm from Russia.

**Comment by mezz** [comment]
Thanks for the report!
@Nirek-K can you take a look?
