### ISSUE TITLE
Add config option for the "overworked bees" productivity level

### ISSUE THREAD

**Issue by mezz** [ForestryMC/ForestryMC#878]
If pristine bees are overworked, they can become ignoble.
Right now it's hard-coded at 16x production, might as well make it configurable.

**Comment by leagris** [comment]
If you add mean to degrade pristine bees, then please add mean to cure ignoble to pristine running it a few cycles with an Alveary stabilizer (for example).

**Comment by SandGrainOne** [comment]
He is making an existing feature configurable. Even back when there where normal and swarmer bees it was possible for bees to degrade if you overworked them. 

Impossible in normal Forestry, and hard even with a few special frames from other mods.

**Comment by Vexatos** [comment]
@SandGrainOne MagicBees adds a Botania flower doing this for mana.

**Comment by mezz** [comment]
I think bees shouldn't be able to produce more than 16x, and I should take out the degradation mechanic.
This behavior is hidden and unexpected.
