### ISSUE TITLE
Incompatibility between Ex Nihilo 1.38-46 and Forestry 4.0.6.34

### ISSUE THREAD

**Issue by 3TUSK** [ForestryMC/ForestryMC#882]
While I was testing my own public modpack, game immediately crashed after a scented artificial hive was placed. 
Environment: Forge 10.13.4.1448.
The [crash-report](https://gist.github.com/3TUSK/fbe01f805ed31f8ea941) has indicates that the problem is on the end of Ex Nihilo, but I believe it is better to leave this issue here so that people can know what happened actually.

Btw I am not sure whether the maintenance of Ex Nihilo for 1.7.10 is stopped or not...

**Comment by liach** [comment]
Maybe exnihilo is only compatible with Forestry 3.x.

**Comment by mezz** [comment]
The Ex Nihilo repo is here: https://bitbucket.org/Erasmus_Crowley/ex-nihilo
Definitely needs an update for Forestry 4, but it looks like it hasn't been touched since February. I'll see if I can contact the author and make a PR.

**Comment by Lunatrius** [comment]
Pretty sure the correct repo is this one: https://bitbucket.org/MikeLydeamore/ex-nihilo

**Comment by mezz** [comment]
Ah ok, I'll make PR there. Thanks

**Comment by mezz** [comment]
Opened and tested a PR to update Ex Nihilo for Forestry 4:
https://bitbucket.org/MikeLydeamore/ex-nihilo/pull-requests/6/update-for-forestry-4-compatibility/diff

**Comment by 3TUSK** [comment]
<s>So we can just wait for a new release? All right, thanks for that!</s>
http://minecraft.curseforge.com/projects/ex-nihilo/files/2262077
Okay so we get the new update. Appreciate!
