### ISSUE TITLE
ExtrabiomesXL saplings not fermenting with Honey

### ISSUE THREAD

**Issue by JasonMcRay** [ForestryMC/ForestryMC#883]
EXBL Saplings can't be processed into Biomass in Fermenter with Honey.

According to NEI it requires fluid.honey (which cannot be obtained) (as opposed to other sapplings from Forestry or Vanilla which requires Honey).
![2015-10-11_20 50 58](https://cloud.githubusercontent.com/assets/4236895/10418392/d1820366-7059-11e5-892f-2a2f21ca5e9d.png)

Tested with:
FT: 4.0.8.36
+
EXBL: 3.16.3
Inside InfiTech 2 modpack

and second test was done with earlier versions where the issue is also happening:
FT: 3.6.10.1
+
EXBL: 3.16.2
Inside InfiTech 2 modpack

**Comment by mezz** [comment]
Thanks for the report!
Interesting. We moved away from "fluid.honey" when placeable fluids were added, because it conflicted with BiomesOPlenty honey. Rather than make them update their plugin I'm just going to convert any recipe that mistakenly uses "fluid.honey" to Forestry's honey.

**Comment by mezz** [comment]
![2015-10-11_19 02 13](https://cloud.githubusercontent.com/assets/916092/10420545/0eef788c-704b-11e5-8ff1-085ef97f5adc.png)

Fixed in the latest unstable build, it'll make its way into the next 4.0 release as well.
