### ISSUE TITLE
Forestry crashing BiomeOPlenty Crash Report

### ISSUE THREAD

**Issue by CitiesXL2815** [ForestryMC/ForestryMC#884]
https://gist.github.com/mezz/d92a3e47d30d1841422c

**Comment by mezz** [comment]
Thanks for the report! 
This is a duplicate of https://github.com/ForestryMC/ForestryMC/issues/871

Please update BoP, they have a new version that is compatible with Forestry 4 here: http://files.minecraftforge.net/BiomesOPlenty/.
