### ISSUE TITLE
Forestry 4 incompatible with ExtraBiomes XL

### ISSUE THREAD

**Issue by Biochao** [ForestryMC/ForestryMC#891]
Crash: http://pastebin.com/MFs8ePGb

They will not be fixing this issue:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1282126-extrabiomesxl-universal-3-16-2-for-mc-1-7-10?comment=14906

**Comment by mezz** [comment]
Thanks for the report!
I already fixed this in ExtrabiomesXL, I guess @ScottKillen forgot. Scott, please stop being a butthead.
https://github.com/ExtrabiomesXL/ExtrabiomesXL/issues/436

> A build containing this fix is now uploaded to Curse as 3.16.3 (http://minecraft.curseforge.com/mc-mods/60041-extrabiomesxl/files/2252754).

**Comment by ScottKillen** [comment]
@mezz Then where would the drama be?

You are right. We have had some organizational issues, but that is no excuse. I apologize for causing trouble and general nincompoopery. :grinning:
