### ISSUE TITLE
[3.6.3.20] Removing items from a machine prefers the hotbar

### ISSUE THREAD

**Issue by Hexicube** [ForestryMC/ForestryMC#893]
Tested with the centrifuge, bee boxes, and apiaries. When shift-clicking to remove items, they will go into an empty slot on the hot-bar instead of onto an existing stack not on the hot-bar.

Easy method of testing:
- Add 1 honeydew to inventory
- Centrifuge a dripping comb
- Shift-click the honeydew out of the centrifuge

If you have space on the hot-bar, that will be taken by the honeydew, left-to-right, unless honeydew is already specifically on the hot-bar. For obvious reasons, it correctly stacks if the hot-bar is full.

**Comment by mezz** [comment]
Thanks for the report!
Fixed, it will be in Forestry 3.6.12 and 4.0.10 on Curse soon.
