### ISSUE TITLE
Confused - What is the latest version?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ForestryMC/ForestryMC#896]
I noticed there is a 3.X.X.X and 4.X.X.X which is an issue.

**Comment by mezz** [comment]
4.0 is latest but some addons are not compatible with it yet, so I'm continuing to include bug fixes for the 3.6 branch as well.
[You can see a list of the incompatible addons here.](https://github.com/ForestryMC/ForestryMC/labels/Incompatibility)

Also the 4.0 branch will break some things from 3.6 worlds, so some people are holding off upgrading for a while.

**Comment by P3rf3ctXZer0** [comment]
Does this means the highlands will work again if I use the older version?

**Comment by mezz** [comment]
I don't think so, Highlands has not worked in a long while and the maintainer hasn't responded to my poking them. You could use a _very_ old version, like 3.5 or earlier maybe, I'm not sure where the break happened exactly.
