### ISSUE TITLE
Bee territory

### ISSUE THREAD

**Issue by sfchipan** [ForestryMC/ForestryMC#897]
![0](https://cloud.githubusercontent.com/assets/4555814/10562895/05246484-75a5-11e5-9e2b-72b3127427c9.JPG)
![1](https://cloud.githubusercontent.com/assets/4555814/10562899/20cfe460-75a5-11e5-9620-26ae7cfd697b.png)
The actual territory seems not the territory in beealyzer. I don't know if the territory has changed after some version. If that is so hoping to adjust the data in beealyzer.

**Comment by mezz** [comment]
Thanks for the report!

Pollination is 3x the territory... for some reason. 
I think it would make sense to have it match the territory.

The life bar is a bug, I will split it into another issue: https://github.com/ForestryMC/ForestryMC/issues/900

**Comment by leagris** [comment]
The main reason I see for 3xterritory is to allow placement of bees close enough to tree leafs while having a chance to keep sunlight over bee houses/apiaries/alvearies.
Taller trees are also very difficult to crossbreed unless you dig deep holes or platforms to plant trees

**Comment by mezz** [comment]
I think that makes sense. Maybe the beealyzer should show "large", "largest" etc instead of a number. The number is misleading.

**Comment by leagris** [comment]
The beealyzer could show in-world overlay of bee zones relative to block pointed (effect, pollination, area), or by holding an analyzed bee

The treealyzer could show in-world overlay of likely tree, shape and girt disposition relative holded alyzer or analyzed sapling (position of master sapling on 2x2, 3x3 and 4x4)

Same for butterfly.

Or all the above given player wears spectacles while holding an analysed bee/sapling/butterfly/pollen/larvae

**Comment by mezz** [comment]
@leagris I think that would be interested but it would be a fairly big commitment to code it. Can you make a new issue/enhancement?

Going to close this issue by changing the number to a name.

**Comment by mezz** [comment]
![2015-10-22_14 00 42](https://cloud.githubusercontent.com/assets/916092/10678146/55ec7fb4-78c5-11e5-8766-d90ae25caa24.png)
