### ISSUE TITLE
Multifarm don't plant  forestry's saplings

### ISSUE THREAD

**Issue by Krysinski** [ForestryMC/ForestryMC#902]
Multifarm isn't plant forestry's saplings when owner is offline. But all is normal with vanilla saplings (then they will be changed to forestry's saplings and wouldn't work)
forestry_1.7.10-4.1.0.757-unstable
server KCauldron

**Comment by mezz** [comment]
Thanks for the report!
I did some testing and this is working fine. I think it may be an issue with KCauldron.
Can you try without KCauldron?

**Comment by Krysinski** [comment]
I supose that it will work without KCauldron. I find this issue about a year ago on my server, but we linked     this problem with KCauldron all time. Some time ago i try to test this again and find that multifarm plant saplings when owner is offline. This give me a hope about fixing this issue.
Its strange, what is different between vanilla's and forestry's saplings?
I cant try it without KCauldron. I cant use other platform for server, KCauldron is very functional for me.
Thanks anywhere.

**Comment by mezz** [comment]
I'm not sure why Forestry saplings would be any different, I'm a assuming the underlying issue is with the farm using a fake player to plant the saplings. I've seen issues with fake players in cauldron before. Maybe you can check your server log for errors relating to it.

**Comment by Krysinski** [comment]
I check my server log, there is no any errors or message. If both saplings types are in farm inventory, farm get and plant only vanilla. With forestry saplings in farm inventory there is like no saplings almost.

**Comment by leagris** [comment]
> when owner is offline
1. Are chunks loaded, by witch mod?
2. Is the farm within world spawn area chunks?
3. Isn't there an issue in the way Forestry handle player UUID owner field in saplings and multifarm where access can't be granted if owner is offline.
4. @Krysinski Where these Forestry saplings created/upgraded from version 3.6 to 4.0?

**Comment by Krysinski** [comment]
1. by other players or by anchors RC
2. No. We tested 2 farm in different parts of world in long distance from spawn
3. how test this?
4. I replace old saplings from my farm and load vanilla saplings to. This issue has been in 3.6 too.
   i trying to post issue on https://gitlab.prok.pw/Prototik/KCauldron/issues, but cant sign up(

**Comment by Krysinski** [comment]
I post this https://gitlab.prok.pw/KCauldron/KCauldron/issues/225 and link it to here

**Comment by mezz** [comment]
I'm going to close this issue for now since it seems to be a KCauldron issue. 
If they find something I need to do, we can reopen it.

**Comment by spannerman79** [comment]
This is an issue on @Krysinski end as this is a fakeplayer permission issue.

On my kcauldron setup, with the area chunkloaded multifarm plants any and all saplings of any kind while my secondary minecraft account is offline.

**Comment by mezz** [comment]
Thanks @spannerman79. 
Do you have any more information I can point people to, so they can get set up correctly?

**Comment by spannerman79** [comment]
I'm trying to pinpoint in your code where you have placed your fakeplayer announcement - example https://github.com/aidancbrady/Mekanism/commit/77db81bcf0c0eaaa7f3757e7b1a610b804491253

Its that fakeplayer that must have the correct permissions.  I'm on an older version of your mod and I would assume you would want to give current up to date information to other users

**Comment by mezz** [comment]
https://github.com/ForestryMC/ForestryMC/blob/dev/src/main/java/forestry/core/utils/PlayerUtil.java#L71-L74
Forestry creates a fake player with the user's gameprofile if the user is offline.

**Comment by spannerman79** [comment]
Ah well in that case its a specific plugin issue that @Krysinski has.  With kCauldron (i am not sure if you know) there are many forms of greif type protection.  [Towny Advanced](http://towny.palmergames.com/) requires the user to be actually online and to be logged in once.

Grief Prevention Plus should run without an issue as that's what I use on my server (dependent on how the server is actually setup of course)

Modifyworld + PEX has _major_ issues with fake players and was never resolved due to bloodmc moving to Sponge dev team.

kCauldron can be complicated and not meant for someone that "wants to run a forge server with some plugins" without serious work setting up everything first beforehand.

**Comment by mezz** [comment]
I don't know anything about kCauldron, thanks for filling me in! 
I will send people here in the future if they have issues.

**Comment by spannerman79** [comment]
No problems.

And just for myself (when I do update your mod on my server) the fakeplayer is the actual name of the owner?  Example `Bob` with UUID `somerandomstring` places down machine, goes offline, the fakeplayer is exactly `Bob` with that exact users UUID?

**Comment by mezz** [comment]
Yes, that's the idea, the machines store the full username and UUID. The only difference is that Bob would be an instance of `FakePlayer`.

My intention was to allow Bob to run his farm in areas that he has permission whether he is online or offline, instead of Bob running his farm anywhere that the `[Forestry Farm]` fake player has permission. Maybe not a good idea if nothing can support it, I honestly don't know.

**Comment by spannerman79** [comment]
I _think_ that is a much better implementation (in theory anyway lol)

Usually with a fakeplayer it covers **all** of that mod/s activity, where you have tied the machine owner as a fakeplayer with the users exact name and UUID for which permission based systems depend on.

I'm not a java dev but I would assume that is close to being ready for [Sponge](https://spongepowered.org/)

**Comment by Krysinski** [comment]
I find what problem: addon modifyworld for PermissionEX plugin. After deleting this allways work fine. Thanks to all for help.

**Comment by Krysinski** [comment]
I suppose that this issue starts from PEX version where modifyworld start been standalone plugin.
