### ISSUE TITLE
AE system don't work with multifarm

### ISSUE THREAD

**Issue by Neuromantix** [ForestryMC/ForestryMC#906]
After update AE system don't see multifarm hatches as inventory and don't work with it without reload farm or AE system.

**Comment by mezz** [comment]
Thanks for the report!
After updating to version 4, all multiblocks need to be remade. Is that what happened?

**Comment by Neuromantix** [comment]
I don't full remade farm - 1 or 2 blocks reinstall and new circuit board inserted

**Comment by mezz** [comment]
Ok this is normal for upgrading to Forestry 4.
The [changelog here](https://www.reddit.com/r/feedthebeast/comments/3mmlwd/forestry_40_beta/) talks about this.

Also see https://github.com/ForestryMC/ForestryMC/issues/907#issuecomment-150488996
