### ISSUE TITLE
Alvearies empty after an update

### ISSUE THREAD

**Issue by JasonMcRay** [ForestryMC/ForestryMC#907]
My modpack has updated Forestry (from Forestry 3.x to 4.0.10.39) and players have reported that all their bees inside all multiblock Alvearies were gone. Apiaries and Bee Houses were fine. Only Alvearies were totally empty (from bees and their products). I see it has been reported at #378 and supposedly fixed, but either it was not, or its back.

**Comment by mezz** [comment]
Thanks for the report!
This is an expected part of upgrading to Forestry 4, and only happens during the upgrade. 
You can see the change log and important information for upgrading to Forestry 4 here: https://www.reddit.com/r/feedthebeast/comments/3mmlwd/forestry_40_beta/

**Comment by JasonMcRay** [comment]
Oh... Sorry I read through that thread when I was updating the pack, but i must have missed that... Thank you.

**Comment by mezz** [comment]
No problem, it's a bit long! 

I may end up linking people here so TLDR: Things to look for:
- Wood items will break (logs, planks, slabs, fences).
- Multiblocks will lose their inventories and may need to be broken and rebuilt.
- Forestry Stained Glass has been removed.
- Apiarist's pipe has been moved to BuildCraft Compat for BuildCraft 7.
- Farms are slightly smaller than last release, and there is a config option in common.cfg called tweaks.farms.size.
