### ISSUE TITLE
Highlands Compatibility Crash.

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#908]
When i updated to 4.x.x. version of Forestry i start getting crashes with Highlands.
Could you add config-option to disable compatibility with it?
http://pastebin.com/QzG8JGHr

**Comment by bakaxyf** [comment]
https://github.com/ForestryMC/ForestryMC/issues/866

**Comment by mezz** [comment]
The issue is actually coming from Highlands trying to access a part of Forestry that no longer exists.
I'm adding back plainFlowers, hopefully that's the only part missing.
@cpbplus Can you try the latest dev build to see if it works? http://jenkins.ic2.player.to/job/Forestry_Dev/

**Comment by ghost** [comment]
@mezz
It works now.
But with Gregtech i get this:
http://pastebin.com/ykRwhz79 i think this normal because it is dev version?

**Comment by carminaburana123** [comment]
Hello I tried with the latest dev version. It does work indeed. It also solves the problem with Biomes o'plenty.

**Comment by mezz** [comment]
@cpbplus Thanks. Please post that as a new issue.

@carminaburana123 Thanks. Biomes O Plenty updated to fix that already though, you can get the new version here: http://files.minecraftforge.net/BiomesOPlenty/
