### ISSUE TITLE
Unable to breed tree traits (FT 4, InfiTech 2 Pack)

### ISSUE THREAD

**Issue by JasonMcRay** [ForestryMC/ForestryMC#909]
This is quote from InfiTech 2 thread:

> Can't breed traits for trees in anymore. Not only did I lose my high sappiness, faster mature and high sapling trees with the update (they reverted to the baseline), but when I try to remake them they reset to the baseline when grown/grafted.

Using build 39, is it possible that: https://github.com/ForestryMC/ForestryMC/commit/3beacb998d079cbfbe84a11ed2f26f6e0df86bb1 is actually fix for this?

http://forum.feed-the-beast.com/threads/1-7-10-infitech-2-modpack-v3-1-16-gregtech-balanced-hard-mode-modpack-updated-10-21-2015.50185/page-392#post-1476606

**Comment by mezz** [comment]
Thanks for the report!
Yes that is the issue, the fix is in stable 4.0.11.
