### ISSUE TITLE
GAME CRASH WITH LAST 2 UPDATES

### ISSUE THREAD

**Issue by toticorrea** [ForestryMC/ForestryMC#910]
Same crash ocurred when I start the game with last 2 versions of Forestry. Once I go back to the 3.6.9.28 version everything is fine.

CRASH LOG:

https://gist.github.com/mezz/85a32c53aa21c7de48eb

**Comment by erkro1** [comment]
I believe 769 should fix that
http://ic2api.player.to:8080/job/Forestry_Dev/769/

**Comment by mezz** [comment]
Thanks for the report! 
This is a duplicate of #871

Please update BoP, they have a new version that is compatible with Forestry 4 here: http://files.minecraftforge.net/BiomesOPlenty/.
