### ISSUE TITLE
Multifarms do not harvest wood from forestry saplings

### ISSUE THREAD

**Issue by Haggle1996** [ForestryMC/ForestryMC#914]
With 4.0.11 SSP, multifarms do not harvest wood from Forestry saplings. Vanilla saplings planted in the multifarm harvest wood without issue.

**Comment by mezz** [comment]
Thanks for the report!
Works fine for me. Can you try the latest unstable build? http://jenkins.ic2.player.to/job/Forestry_Dev/

![2015-10-24_22 36 15](https://cloud.githubusercontent.com/assets/916092/10714197/ac128ce0-7a9f-11e5-9229-fb23801e080a.png)

**Comment by Haggle1996** [comment]
No joy with the latest unstable build. It does harvest the trees; however, it does not output any wood blocks (falling saplings are gathered). The saplings were spawned from NEI, though not certain that would have any impact. Have tried mahoe and the two sequoias.

Here's a sample of the log from load to a tree growing and harvesting; I'll retry with a minimal modset, see if its a mod interaction.

https://gist.githubusercontent.com/Haggle1996/bf10f57b2679c4e3d2bd/raw/6f56bb62a21475e6c3c4e41391d7db4707baea65/gistfile1.txt

**Comment by mezz** [comment]
I see, that's a bit different. I can confirm that the farm is not storing the wood blocks it breaks.

**Comment by Haggle1996** [comment]
Also fails to harvest with minimal modset (NEI, Waila, Forestry). Looking forward for the update. :)

**Comment by mezz** [comment]
I pushed a fix, please try out the latest unstable build and see if you can get anything weird to happen while harvesting logs.
http://jenkins.ic2.player.to/job/Forestry_Dev/

**Comment by Haggle1996** [comment]
Confirmed this is fixed with the latest unstable. Thanks for the quick turnaround. And no, nothing seems weird. Same genes on the sapling. Saplings drop and are collected. Wood ends up in the chest. All is right with the world. :)
