### ISSUE TITLE
Forestry multi-farm reports no power / water if at least a single ring of 'base' blocks aren't surrounding the farm

### ISSUE THREAD

**Issue by Preladon** [ForestryMC/ForestryMC#916]
Playing regrowth 0.82 (Forestry 3.6.6.24) and had no end of problems making my multifarm work.  It reported on the left hand side that it had no water (it was full from a buildcraft pump), no fertilizer (I put a full stack of fertilizer, crafted from saltpetre, in it) and that it had no blocks for farmland.

I needed to build a full ring around the outside of the (in this case) stone bricks, and then all of the error messages on the left hand side disappeared and the farm started to work as expected.

Odd case, I realise, but I shouldn't have to build out on all sides of the farm to make it work, I'd have though - I may only want to use one side (at least initially).

Not sure if this bug has been fixed since, as it looks like this isn't the most up to date, but it is in a 'current' pack, so thought worth sharing.

**Comment by mezz** [comment]
Thanks for the report! 
Current packs are way behind on updates unfortunately. If you know your pack is behind, please bug them to update. Stable Forestry 3.6 is at version 3.6.12.

The new version of Forestry is 4.0 and has completely rewritten the multiblock code including farms. It breaks some things when you update from 3.6 though. [Here's a changelog including info on things that will break.](https://www.reddit.com/r/feedthebeast/comments/3mmlwd/forestry_40_beta/) 

Please back up your world and try to see if updating to Forestry 4 fixes the issue. [You can get it here](http://www.curse.com/mc-mods/Minecraft/forestry).

**Comment by mezz** [comment]
I have just tested farms a bit with the latest version, and it does not have this problem any more.
