### ISSUE TITLE
Crash with new forestry, unsure of cause

### ISSUE THREAD

**Issue by SneakyDevil** [ForestryMC/ForestryMC#917]
https://gist.github.com/SneakyDevil/fe5827411c69e3942bab

Just did a round of updates. Originally assumed it was biblocraft, updated bilbocraft, issue persists.

**Comment by mezz** [comment]
Thanks for the report!
You need to update ModTweaker2. You can get more responsive help in the IRC channel [#forestry](http://webchat.esper.net/?nick=ForestryGithub...&channels=forestry&prompt=1) or [#FTB](http://webchat.esper.net/?nick=ForestryGithub...&channels=ftb&prompt=1).
