### ISSUE TITLE
Machines ambient occlusion does not render at some angles

### ISSUE THREAD

**Issue by leagris** [ForestryMC/ForestryMC#919]
There may be other mods no properly resetting OpenGL states or Forestry missing some extra initializations in render.
At some angles or while looking other blocks, ambient occlusion is not always rendered on machines.

**Comment by mezz** [comment]
Thanks for the report!
Probably both, OpenGL with modded is the wild west. The best practice is to write my code to be very conservative and try to set up any state it needs. I'll see if I can repro this.

**Comment by mezz** [comment]
I'm not able to see the problem with just Forestry, can you post a picture? It might only show up when another mod is rendering something too.

**Comment by leagris** [comment]
![2015-10-25_21 43 31](https://cloud.githubusercontent.com/assets/1111474/10717747/bb4b57b0-7b61-11e5-8e23-2ee9e54ec68e.png)
![2015-10-25_21 43 33](https://cloud.githubusercontent.com/assets/1111474/10717748/c6301bb6-7b61-11e5-93d9-beb96ba7baf4.png)
![2015-10-25_21 43 42](https://cloud.githubusercontent.com/assets/1111474/10717749/c6335f2e-7b61-11e5-88f0-77dfed55f8c8.png)
![2015-10-25_21 43 52](https://cloud.githubusercontent.com/assets/1111474/10717750/c635c822-7b61-11e5-8ea7-ca57309e87ff.png)

**Comment by mezz** [comment]
Thanks! Can you list some of the mods for the nearby machines? I think that's Railcraft and Thermal Expansion but I don't know for sure with the texture pack.

**Comment by leagris** [comment]
EnderIO-1.7.10-2.3.0.414_beta.jar
Railcraft_1.7.10-9.7.0.0.jar
appliedenergistics2-rv3-alpha-9.jar
ExtraCells-1.7.10-2.3.0b142.jar
extrautilities-1.2.5.jar
BiblioCraft[v1.11.3][MC1.7.10].jar
BiblioWoods[Forestry][v1.7].jar
Carpenters Blocks v3.3.7 - MC 1.7.10.jar
Chisel2-2.5.0.43.jar
ProjectRed-1.7.10-4.7.0pre9.92-Lighting.jar
ironchest-1.7.10-6.0.62.742-universal.jar

You can see same glitch affecting Ironchest(diamond chest) and BiblioWood tool rack

**Comment by Player3324** [comment]
IMO the best way to avoid the problem in the first place is rendering the static machine parts from the world renderer (isbrh@1.7/model@1.8+). TESR lighting is just a rough approximation and slower anyway.

The picture indicates something changing the gl state without resetting it, which wouldn't be a Forestry bug, unless it does so likewise.

**Comment by mezz** [comment]
![2015-10-25_14 39 00](https://cloud.githubusercontent.com/assets/916092/10718035/65c598d6-7b26-11e5-8a94-1bf48d9d9333.png)

I tried a bunch of stuff but wasn't able to reproduce the issue.
I should use ISBRH but I need to figure out how to do it.

**Comment by leagris** [comment]
Restarted with reduced permgen. Now it only show light glitch on one of the bibliowoods toolrack.
Maybe it is bibliowoods having an issue.
And the permgen space change may displace a race condition where the GL state is not restored.
Not even sure it is 100% caused by Forestry. Maybe bibliowoods.

**Comment by Player3324** [comment]
No this is certainly not related. The problem depends on the render order of everything in the view area, including objects behind walls, which is not arbitrary and varies between runs. As soon as the faulty rendering code executed, everything afterwards will be potentially incorrect. The block at fault will always render correctly unless there's multiple instances of this issue happening at the same time.

**Comment by leagris** [comment]
Ok found out the offending block/mod
Applied Energistics2 inscriber when loaded with a press is causing the issue.
Thank you for you help. I will go report this to AE2
