### ISSUE TITLE
Backpacks no longer accept items

### ISSUE THREAD

**Issue by inucune** [ForestryMC/ForestryMC#920]
In version 1.7.10-4.1.0.44, backpacks (as a whole) do not automatically pick up items nor can they be manually inserted into the backpack. Observed in survival, confirmed in creative.

**Comment by mezz** [comment]
Thanks for the report!
Try deleting your backpack config file in the `config/forestry/` folder.

**Comment by inucune** [comment]
deleted config/foresty/backpacks on client and server. Issue resolved. Thanks. Closing ticket.
