### ISSUE TITLE
New tree branching generate non-connected logs

### ISSUE THREAD

**Issue by leagris** [ForestryMC/ForestryMC#922]
The new branching mechanic has non-connected logs that spawn.
The multi farm does not cut these down and huge mass of leaves with a few logs persist.
It is blocking any further trees from spawning.

**Comment by mezz** [comment]
Hmm I was careful to make sure they connect. I'll test it out a bit and see if it's caused by the trees or the farm.

Which type of tree are you growing?

**Comment by PaulMadsen** [comment]
I am experiencing the same issue.  I am growing a 3x3 blue mahoe with the large height trait.  It happens about once every 10-15 minutes but when it does it shuts down a large section of the multifarm to further tree growth.

**Comment by PaulMadsen** [comment]
![2015-10-25_18 21 28](https://cloud.githubusercontent.com/assets/1664282/10719026/7564f420-7b45-11e5-97f3-72e27c7c477a.png)
![2015-10-25_18 21 58](https://cloud.githubusercontent.com/assets/1664282/10719027/7568add6-7b45-11e5-8986-4e586f00a20a.png)
![2015-10-25_18 22 09](https://cloud.githubusercontent.com/assets/1664282/10719028/75699c50-7b45-11e5-8bd7-edf6bd3b4612.png)

**Comment by PaulMadsen** [comment]
It looks like the logs are connected but the tree farm isn't eating the farther reaching logs.

**Comment by PaulMadsen** [comment]
Might actually be both unconnected logs and the tree farm not having enough horizontal reach.

**Comment by mezz** [comment]
It looks like the farm had a branch limit of about 5 blocks. I extended it, and the farm harvests the trees fine now. I wasn't able to find trees with gaps in the branches. 

Please let me know if you still have the issue with the latest unstable build and I can reopen this.

**Comment by PaulMadsen** [comment]
The problem persists in forestry 4.2.0.814-unstable.

**Comment by mezz** [comment]
Any details?

**Comment by PaulMadsen** [comment]
Details are the same as before.  Unconnected logs are generated but not removed.  Because of this a mass of leaves remains preventing further tree growth.

**Comment by yopale** [comment]
Bug still there 27 dic 2015 last built

**Comment by leagris** [comment]
This branching glitch is not a minor issue when you try to run an arboretum multi-farm and it get stuck in a few cycles.
@mezz instead of letting this bug rot with uncertainty or trying to fix/find a reliable branching rule for each specie; I suggest either to:
- Have tree branching within a multi-farm land area disabled.
- Or even add a global branching config option marked experimental like the alternate 3D rendering of bees.
