### ISSUE TITLE
Alvearies get desconected of any pipe on server start.

### ISSUE THREAD

**Issue by Buuz135** [ForestryMC/ForestryMC#923]
Version: forestry_1.7.10-4.1.0.775-unstable.jar

On server start alvearies get desconected of any pipes but they are still working. When the block gets updated, the alveary stops working and the pipe gets connected. After removing the block the alveary forms again. It only happens if you update the block next to the pipe, not the other ones.

The issue probably happens on world load too.

![2015-10-26_10 07 08](https://cloud.githubusercontent.com/assets/3874674/10725104/dade8198-7bc9-11e5-82b2-c0c6dcad7c4e.png)
![2015-10-26_10 07 21](https://cloud.githubusercontent.com/assets/3874674/10725108/e051bc26-7bc9-11e5-85b9-74708ebdb9eb.png)
![2015-10-26_10 07 31](https://cloud.githubusercontent.com/assets/3874674/10725111/e230409e-7bc9-11e5-81d6-9dceda8d55a9.png)

**Comment by JasonMcRay** [comment]
Possible problem is that Alveary is not updating neighbour blocks when its formed, thus causing issues with blocks requireing access to the inventory

**Comment by mezz** [comment]
Thanks for the report!
I think I actually take this into account, when an Alveary is formed it should notify its neighbors.
The pipe shouldn't connect to the unformed Alveary... that's an issue too.

Unfortunately, I haven't been able to reproduce this yet. I'm testing on a server so it's a bit slow to try things. If you have more specific repro steps please let me know.

**Comment by mezz** [comment]
Ok got it to happen, investigating.

**Comment by mezz** [comment]
@JasonMcRay was correct mostly, thanks. I fixed that and also the issue where pipes would connect to unformed multiblocks.

Pushed a fix to the latest unstable build. Please let me know if there are any issues.

**Comment by JasonMcRay** [comment]
Will it cause problems if I will update to unstable and then after it is pushed to stable will revert back to stable?

**Comment by mezz** [comment]
I don't think there would be an issue but I wouldn't downgrade. I plan to release 4.1.0 soon.
