### ISSUE TITLE
NEI doesn't show combs processes nor crafting recipes

### ISSUE THREAD

**Issue by AlexPlus117** [ForestryMC/ForestryMC#927]
NEI doesn't show any combs processes nor some crafting recipes like squeezer's, analyzer's, apiary's... Is it a Forestry bug or NEI's one?
![2015-10-27_19 40 40](https://cloud.githubusercontent.com/assets/8421361/10768681/a466bcc4-7ce2-11e5-8a56-366f54c67b21.png)
P.S.: I'm using Forestry 3.6.12 and NEI Addons 1.12.11

**Comment by Nirek-K** [comment]
3.6 requires NEIIntegration, 4.0+ provides it from forestry itself.

**Comment by AlexPlus117** [comment]
I'm already using NEI Integration, but it doesn't work the same.

**Comment by Nirek-K** [comment]
You're likely using a version that already removed the forestry integration for the things you are finding missing.

**Comment by AlexPlus117** [comment]
Yes, you're right! I'm using NEI Integration 1.0.13, but I need 1.0.12... Now all works, thank you!
