### ISSUE TITLE
EXBL Fermenting Issues

### ISSUE THREAD

**Issue by JasonMcRay** [ForestryMC/ForestryMC#928]
I am unable to ferment Extrabiomes Saplings.

With Water I can process EXBL sapling once. Then if there is Biomass inside the Fermenter (output) i cant process any more EXBL saplings (vanilla saplings work fine) and fermenter gives: No Recipe

With Fruit juice I cant process EXBL sapplings at all (vanilla again works fine). Fermenter gives No Recipe

With honey same as with water... I can process EXBL sapling once.

Tested with Forestry 4.1.0.44 and EXBL 3.16.3

**Comment by mezz** [comment]
Thanks for the report!
Edit: I was able to reproduce the issue.
I'll start testing and see what it might be.

**Comment by JasonMcRay** [comment]
I usually dig holes, but i digged through logs this time around :) Unfortunately was not able to find anything at all about fermenter in the log :(

**Comment by mezz** [comment]
Ok I think I figured it out: the Extrabiomes recipes require at least one bucket of fluid. So you add one bucket and it works for just one sapling before the level dips too low. Can you confirm that this is the same issue?

**Comment by JasonMcRay** [comment]
That seems like it is correct. 1000mB of water, processing is fine. Dips to 900mB - no longer processes.

**Comment by mezz** [comment]
Fixed in the latest unstable build
