### ISSUE TITLE
Bottler doesn't work with some mod Fluid Containers.

### ISSUE THREAD

**Issue by Voidi** [ForestryMC/ForestryMC#929]
If tested this only with forestry version 1.7.10-4.1.0.44.
It seems you cannot empty Bottle from Mariculture into the machine tank and fill Tanks from OpenBlocks.

**Comment by mezz** [comment]
Thanks for the report!
Mariculture has a lot of strange liquid containers, I'm finding edge cases all over the place. Should be nice when I fix it all up.

**Comment by mezz** [comment]
Ok the bottler should work with all kinds of crazy stuff now.
