### ISSUE TITLE
Fireproof Wood doesn't work in regular wood recipes

### ISSUE THREAD

**Issue by Nex4rius** [ForestryMC/ForestryMC#930]
The fireproof wood and planks don't have any oredict tags so they wont be included in any wood recipes. https://github.com/JasonMcRay/InfiTech-1.7/issues/406

**Comment by mezz** [comment]
Thanks for the report!
Also they have burn time because of a FML/Forge issue: https://github.com/MinecraftForge/FML/issues/559
I could change the material to something other than wood but I'm not sure what the consequences would be.

**Comment by mezz** [comment]
I did some testing with a "fireproof wood" material but there is no way to allow axes to harvest it in adventure mode (without allowing _everything_ to harvest it).

**Comment by ScottKillen** [comment]
I have release a private fix for this since a fix for 1.7.10 will **not** be forthcoming: https://github.com/MinecraftModArchive/MinecraftForge/releases/tag/10.13.4.1558%2BfuelFix
