### ISSUE TITLE
Any suggestions (forestry.api.apiculture.IAlleleBeeSpecies.getProducts)

### ISSUE THREAD

**Issue by Gamingdaredevil** [ForestryMC/ForestryMC#931]
https://gist.github.com/mezz/bae3c5feaef8858ed8da

**Comment by mezz** [comment]
Thanks for the report!
I need the full crash log (including the list of mods) to know for sure. By cutting it short, you limit the information I can use. 
I suspect you are using the latest Forestry 4 with Binnie's mods, which are not compatible.

**Comment by mezz** [comment]
@Gamingdaredevil was that the problem?

**Comment by Gamingdaredevil** [comment]
thanks

**Comment by mezz** [comment]
Dupe of #857
