### ISSUE TITLE
The coolant ability of crushed ice is abnormal

### ISSUE THREAD

**Issue by sfchipan** [ForestryMC/ForestryMC#932]
The data of crushed ice is 10 from 'addCoolant(Fluids.ICE.getFluid(), 10F)'. But the data of water is just 0.0023 in Buildcraft. Maybe the amount haven't been updated?

**Comment by Nirek-K** [comment]
It's intended to be significantly better than water, did BC change it's design?

**Comment by mezz** [comment]
@asiekierka can you enlighten us on coolant values?

**Comment by asiekierka** [comment]
0.0023 is the constant value for water which I think is supposed to mean degrees cooled per mB? For reference, ice gives 1.5x cooling in BC7, and packed ice 2x cooling.

**Comment by mezz** [comment]
~~Ok, I think the ice was intended to be 10x water but it is not done correctly. I think a value like packed ice would be appropriate.~~

Edit: Looking at wikis, it is intended to be 6x better than water. It's pretty tough to make so that makes sense to me.
