### ISSUE TITLE
Invalid ore dictionary registration in forge

### ISSUE THREAD

**Issue by loordgek** [ForestryMC/ForestryMC#933]
http://paste.ee/p/tfvlN

**Comment by leagris** [comment]
`[16:28:40] [Client thread/ERROR] [FML]: Caught exception from Avaritia
java.lang.NullPointerException|`
Not forestry related

**Comment by loordgek** [comment]
if you read the full log you find Forestry

**Comment by loordgek** [comment]
http://paste.ee/p/qBJaJ forge build 1541

**Comment by mezz** [comment]
Thanks for the report! Fixed in the latest unstable build.
Also Forge 1541 turns this into a warning instead of crashing.
