### ISSUE TITLE
Farm blocks uncraftable beside basics

### ISSUE THREAD

**Issue by leagris** [ForestryMC/ForestryMC#935]
In current 4.1 dev builds, it is impossible to craft any Farm block beside basics. (gearbox, controller...)

See: https://github.com/Beyond-Reality/BeyondRealityModPack/issues/336

Confirmed with:
forge-1.7.10-10.13.4.1492-1.7.10-universal.jar
forestry_1.7.10-4.1.0.787-unstable.jar alone (no other mod)

**Comment by mezz** [comment]
Thanks, fixed in the latest unstable build.
