### ISSUE TITLE
Crash after updating

### ISSUE THREAD

**Issue by Peca21** [ForestryMC/ForestryMC#939]
Minecraft crashes during loading after updating forestry from forestry_1.7.10-3.6.10.1 to forestry_1.7.10-4.0.11.40.
Crash: http://pastebin.com/iVDvEgT0

**Comment by mezz** [comment]
Thanks for the report!
It looks like there's an error with Biomes O Plenty. Try updating it to the latest version.

**Comment by Peca21** [comment]
Updating Biomes O Plenty fixed the crash. I didn't see the updatye because its an alpha version.
