### ISSUE TITLE
queen crash

### ISSUE THREAD

**Issue by VanironCZ** [ForestryMC/ForestryMC#943]
Hello guys,
i got problem on my server when 2 random bees placed into apiary will sometimes produce new bee called just "queen" (without any prefix or so) which will crash server immediately. Getting closer to that apiary will crash server again and again. Only removing it from far away with worldedit works. Any ideas how to fix it?

I am using version 3.6.11.2 from curse site, crash log here:
http://pastebin.com/raw.php?i=HXdd9mBX

**Comment by mezz** [comment]
Thanks for the report!
Please try with the latest Forestry 4 version. There are some big changes though, [check here for details on what to look out for](https://github.com/Beyond-Reality/BeyondRealityModPack/issues/323).

**Comment by VanironCZ** [comment]
Will it be compatible with old world? i am afraid of ids change or some others problems maybe coming with it..

**Comment by mezz** [comment]
Multiblocks will lose their inventories and forestry wood items will disappear. It will not corrupt the world though. Make a backup of your server folder and you have nothing to fear.

**Comment by VanironCZ** [comment]
Ok i will try and let you know later.

**Comment by leagris** [comment]
About the your invalid queen crashing.
There is likely some princess and drones with broken genes inside your alveary.
You can fix this by editing `config/forestry/common.cfg`
Setting to clear invalid chromosomes.

``` yaml
genetics {
    # Clears chromosomes which contain invalid alleles. Might rescue your save if it is crashing after the removal of a bee addon. [default: false]
    B:clear.invalid.chromosomes=true
#...
}
```

**Comment by VanironCZ** [comment]
Setting config value to true is working. Thanks :)
