### ISSUE TITLE
Compatibility Request Ic2 Classic (Speiger) Activate ic2 Module if Ic2 Classic is installed

### ISSUE THREAD

**Issue by Okkasionen** [ForestryMC/ForestryMC#946]
-Enable Biogenerator
-Enable Rubber Farm
-Enable sticky resin from centrifuge recipe
etc...

Thanks for reading

**Comment by LuigiHutch** [comment]
IC2 Classic already activates IC2 module with IC2 Classic Installed. It loads items such as: Electrical Engine, Bio generator and Rubberised electron tube what are all only loaded when the IC2 module is loaded.

Tested With Forestry 4.1.1.46 and IC2 Classic 1.1.2.1

**Comment by Okkasionen** [comment]
WRONG WRONG WRON IM DUMB WYH AM I LIVING ANYMORe
QUIT
