### ISSUE TITLE
Server Halted after World Edit

### ISSUE THREAD

**Issue by Morketh** [ForestryMC/ForestryMC#947]
I uploaded a schematic file for World Edit of a bridge that a buddy of mine built. After pasting the build the server promptly halted and refuses to start now.

Error logs are posted here:
https://gist.github.com/Morketh/7e3ffed2a245b53d15c8

From what i can tell its something to do with Forestry? seems a bit odd as the schematic used was only of Vanilla Minecraft blocks. If anyone would like to duplicate the results i can provide the Schematic file in question

**Comment by mezz** [comment]
Thanks for the report!
This looks to be caused by a corrupt Forestry Mailbox. Is there a mailbox accidentally included in the schematic?

**Comment by Morketh** [comment]
At first i thought there was some kind of forestry mailbox or something but its all just vanilla blocks ive loaded the world save up on Single Player in order to create the schematic file. 
in case youd like a look at the file
http://ci-main.no-ip.org/Bridge98.schematic

i did go back and look at the world save and there were some bats in the building (not sure if they could be type cast to a mailbox by the server)

**Comment by mezz** [comment]
The crash says there's a mailbox at (x, y, z) (399,56,15) can you take a look?

**Comment by Morketh** [comment]
i will defiantly go have a look and see whats causing it.

**Comment by Morketh** [comment]
well at those coordinates on the Single player map it was empty Supper Flat world and is not related to the build at all
and on the Multiplayer server it is just an ocean. However that is roughly where i was placing the Bridge before the server crashed. (i got it back online using a Forge Essentials Backup). My guess is a block got messed up in translation in the schematic file? Copy/Paste on single player worked just fine with no issues and no crash.

**Comment by Morketh** [comment]
![2015-11-02_17 03 01](https://cloud.githubusercontent.com/assets/6291631/10898297/57f3627c-8186-11e5-9427-8fa010b30f63.png)
![2015-11-02_17 06 29](https://cloud.githubusercontent.com/assets/6291631/10898298/57f844fe-8186-11e5-9e74-c2f8defef5cb.png)
![2015-11-02_17 24 54](https://cloud.githubusercontent.com/assets/6291631/10898339/b86afac0-8186-11e5-9ba6-d35fea5f0abe.png)

First 2 photos are of the areas in question on both SSP and SMP (corresponding to the coordinates given in the log files) the 3rd is of the build in question. Im entirely at a loss as to what this could be

**Comment by mezz** [comment]
Unfortunately I have no idea why it is creating the wrong block.
I think you have to find somewhere else to ask, there's nothing in Forestry that would make world edit place mailboxes.
