### ISSUE TITLE
Error in Console Forestry NEI Integration

### ISSUE THREAD

**Issue by Xen1290** [ForestryMC/ForestryMC#948]
Hi, here the error:
https://gist.github.com/Xen1290/346f1acea5dbdd02967c
Forestry 4.1.1

**Comment by mezz** [comment]
Thanks for the report!
Should be fixed in the latest unstable build.
Next time please give the full log, it's helpful to know what mods are involved.

**Comment by Xen1290** [comment]
Oh sorry ! I'll do that next time!
