### ISSUE TITLE
Cant input into carpenter any liquid expect Water

### ISSUE THREAD

**Issue by hxpx** [ForestryMC/ForestryMC#949]
Forestry 4.1.1.46 on Forge 1388 / Minecraft 1.7.10,installed with gregtech, endrio,gendustry,magic bees. 

When using interface carpenter i can input water with buckits,capsules,pipes.
But when i'm trying any another fluid like seed oil that just not doable to place capsule or bukkit into slot. Or when i'm using pipes to transfer liquid carpenter just dont accept that liquid.

**Comment by mezz** [comment]
Thanks for the report!
It's working fine for me though. Are you sure there isn't a small amount of water in the tank?

**Comment by hxpx** [comment]
Yea i'm pretty sure, i'm has been drained all of water out from carpenter.There're may be conflict with gregtech 5 unnoffical? http://forum.industrial-craft.net/index.php?page=Thread&threadID=11488&pageNo=1 this mod

**Comment by mezz** [comment]
Maybe. @Blood-Asp any idea if GT5 changes carpenter recipes or something?

**Comment by mezz** [comment]
I think I figured it out. Can you try the latest unstable build and see if it works?

**Comment by hxpx** [comment]
Hello, @mezz #949 fix op. Our carpenter start working well with a liquids!Thank you so much for your work!

**Comment by Schlauchiboy** [comment]
Now have the same issue. Using newest version. Need help
