### ISSUE TITLE
Mutation Condition is hardcoded localization

### ISSUE THREAD

**Issue by bakaxyf** [ForestryMC/ForestryMC#950]
![hj az7ibrv659566c cjc o](https://cloud.githubusercontent.com/assets/10368307/10944281/75ac332e-8353-11e5-9ae2-b51bc7cabcfc.jpg)

**Comment by liach** [comment]
Close this as #951 described this issue in a more accurate way.

**Comment by 3TUSK** [comment]
I really want to say the screenshot is issued under Creative Common 0. But I can't. Sad.
