### ISSUE TITLE
Hardcoded research note description?

### ISSUE THREAD

**Issue by 3TUSK** [ForestryMC/ForestryMC#951]
One of my friend (@IamAchang) shared a screenshot with me:
![img_5678](https://cloud.githubusercontent.com/assets/9113033/10944046/389c022a-82e5-11e5-8031-aa0546fef3eb.JPG)
As the screenshot shown, there are some unlocalized stuff. Then I took a look at the actual codes, and found something:
- [Related line in `ItemResearchNote.java` (all hardcoded entries are listed below)](https://github.com/ForestryMC/ForestryMC/blob/dev/src/main/java/forestry/core/genetics/ItemResearchNote.java#L103)  
  - [Hardcoded description of biome restriction](https://github.com/ForestryMC/ForestryMC/blob/55866d6a64c3ef1ac84fb6b2b9dd4ce17272bfdf/src/main/java/forestry/core/genetics/mutations/MutationConditionBiome.java#L49-L52)  
  - [Hardcoded description of daylight restriction](https://github.com/ForestryMC/ForestryMC/blob/55866d6a64c3ef1ac84fb6b2b9dd4ce17272bfdf/src/main/java/forestry/core/genetics/mutations/MutationConditionDaytime.java#L38-L40)  
  - [Hardcoded description of humidity restriction](https://github.com/ForestryMC/ForestryMC/blob/55866d6a64c3ef1ac84fb6b2b9dd4ce17272bfdf/src/main/java/forestry/core/genetics/mutations/MutationConditionHumidity.java#L44-L46)  
  - [Hardcoded description of position restriction](https://github.com/ForestryMC/ForestryMC/blob/55866d6a64c3ef1ac84fb6b2b9dd4ce17272bfdf/src/main/java/forestry/core/genetics/mutations/MutationConditionRequiresResource.java#L39)  
  - [Hardcoded description of temperature restriction](https://github.com/ForestryMC/ForestryMC/blob/55866d6a64c3ef1ac84fb6b2b9dd4ce17272bfdf/src/main/java/forestry/core/genetics/mutations/MutationConditionTemperature.java#L45-L47)  
  - [Hardcoded description of IRL time range restriction](https://github.com/ForestryMC/ForestryMC/blob/55866d6a64c3ef1ac84fb6b2b9dd4ce17272bfdf/src/main/java/forestry/core/genetics/mutations/MutationConditionTimeLimited.java#L57)  

Is it possible to make those entries localizable? Thanks for your time.

**Comment by mezz** [comment]
Thanks for the report!
I would like everything to be localizable, so don't hesitate to report :)
It's easy for me to overlook because I only play in English.

**Comment by mezz** [comment]
Fixed in the latest dev build

**Comment by 3TUSK** [comment]
Thanks for your time again!
