### ISSUE TITLE
startup crash.

### ISSUE THREAD

**Issue by stclaus4** [ForestryMC/ForestryMC#952]
I had this crash, and I need help fixing it thanks. I'm a bit of a noob with these things
http://pastebin.com/ryM4FqQy

**Comment by mezz** [comment]
Thanks for the report!
This is an immersive engineering issue, see here: https://github.com/BluSunrize/ImmersiveEngineering/issues/586

The solution is 

> Update to Forestry 4.0.+ or disable the Foresty module in the IE config.

Since Forestry 4 does not work with Binnie's mods yet, I recommend the latter.

**Comment by mezz** [comment]
I made PR to Immersive Engineering that should let it work with any version of Forestry
https://github.com/BluSunrize/ImmersiveEngineering/pull/597
