### ISSUE TITLE
Potential bug with lumbermill and fireproof wood

### ISSUE THREAD

**Issue by jojomodjo** [ForestryMC/ForestryMC#953]
Playing on FTB Direwolf 1.7

I noticed earlier in the week that I was being kicked from our whitelist server when I attempted to put Fireproof wood in the lumbermill. I checked to see if a crash report was generated, but nothing.

The more irritating concern is when fireproof wood is put into a BC chute. I did this accidentally, and soon as the wood went through the chute and hit the lumbermill, it kicked off everyone in the chunk, and no one could get back on the server until the region was rolled back to the previous save. 

I asked the boss if there was any crash reports from the server end, and he said that there was nothing as such, just a tick bug out. 

Attempted recreation in single player mode, manual attempting to add a stack causes the same issue. Doing the same with a BC chute screws up any new map- every time you try to rejoin it boots you off again. 

As a further note, it seems to be activated from using shift+click. When recreating the issue, I noticed you didn't even need to click, merely hovering over the the fireproof wood while holding shift while using the lumbermill causes the crash.

**Comment by mezz** [comment]
Thanks for the report!
The Lumbermill is actually from Binnie's Extra Trees.  
[You can copy the issue to their issue tracker here.](https://bitbucket.org/binnie567/binnie-mods/issues?status=new&status=open) I didn't see anything like this crash posted already.
