### ISSUE TITLE
Improve chest GUI

### ISSUE THREAD

**Issue by mezz** [ForestryMC/ForestryMC#954]
The species information on the side isn't really usable right now, just taking up room.

**Comment by mezz** [comment]
![apiaristinventory2](https://cloud.githubusercontent.com/assets/916092/11168471/415bc39c-8b45-11e5-9048-eb638447f76e.png)

I was thinking something like this for the apiarist inventory but it would be a huge pain to align all the slots correctly. Not sure what I want instead.

**Comment by leagris** [comment]
One thing that make the specialized chest useful is the display of extra information about mutations.
One issue with current chest is, it is incompatible with InvTeweaks sorting.
Maybe these chests could implement some sorting and searching based on specie, type (queen,princess,drone,pristine...)
Ideally, I'd like a database/me type device specialised for Forestry;
Then maybe a whole new database machine could implement something as an extension cross-breed between an Apiarist chest + Alyzer + Almanac + Me device.

Something where one can:
- Sort based on specie, kind, genes/traits...
- Lock last instance of a bee/sapling/butterfly/larvae,pollen so it can not be removed by piping it out
- Display extended information about an item
- Browse a full breeding tree
- And eventually play an escritoire discovery game.
