### ISSUE TITLE
Butterfly hitboxes are too low

### ISSUE THREAD

**Issue by mezz** [ForestryMC/ForestryMC#956]
![2015-11-07_16 10](https://cloud.githubusercontent.com/assets/916092/11018032/39310460-856a-11e5-9738-6ce9d0c4e983.png)

This causes them to suffocate in ceilings and it makes them very hard to catch.
(also this screenshot is after I doubled the height of the hitbox!)

**Comment by leagris** [comment]
Hehe, I always thought is was kind of intentional. Catching a butterfly in real life require its share of  skill, thoroughness and patience.

**Comment by mezz** [comment]
I think I will make it have a % chance to catch if you hit it, so it's still difficult. Right now you can hit it tons of times and never catch it unless you know that the hitbox is weird!

**Comment by leagris** [comment]
You should have a chance of damaging/killing the butterfly in the process.
