### ISSUE TITLE
Forestry block placement crash (compatibility issue)

### ISSUE THREAD

**Issue by TheYorkshireman** [ForestryMC/ForestryMC#958]
Firstly, you'll be aware that i use many mods. But it appears that Forestry is the only one that does this. When placing forestry blocks such as beehouses or beechests on plant blocks generated by other mods (tested on biomes o'plenty grasses and shrubs, extrabiomes plants) the game encounters a problem it can't handle and crashes off. Obviously it doesn't do this when the blocks are placed on vanilla MC plant blocks, it just replaces them normally. Here's the last bug report - 

https://gist.github.com/mezz/5dcf79e18a685263ade3

If you want any more details or bug reports ( i have plenty and can make many more/test fixes ) just message me on twitter @asahurren. And sorry for taking forever to send this to you, i'm a bit crap.
Thanks for your time!

**Comment by mezz** [comment]
Thanks for the report!
Should be fixed in the latest unstable build. Please let me know if you run into any other issues. Just a crash report and a line about what you did to get it would be very helpful.
