### ISSUE TITLE
Fireproof wood have fuel value

### ISSUE THREAD

**Issue by leagris** [ForestryMC/ForestryMC#960]
Can burn Fireproof logs, planks, slabs, stairs in a furnace.

https://github.com/Blood-Asp/GT5-Unofficial/issues/309

Please also reconsider that NBT WoodType that make recipe handling complicated for no reason.
Wood items (not blocks) should use meta instead of NBT.

**Comment by mezz** [comment]
Thanks for the report!
The fireproof woods have a burn time because of a FML/Forge issue: MinecraftForge/FML#559
I tried to work around it but it broke more things than it fixed. The only solution is to make the material something besides wood, but then axes can't mine it.

I will make the wood items use damage values instead of NBT. I may as well do that now since it will only get uglier if I wait longer.

**Comment by liach** [comment]
Actually not so much related to that FML issue... It is to set a new fuel value that is bigger than the original one. You cannot set the fuel value of an item stack smaller via `IFuelHandler`.

**Comment by ScottKillen** [comment]
@liach You cannot set the fuel value of anything made of wood via `IFuelHandler`.

**Comment by ScottKillen** [comment]
@Mezz See the bottom of MinecraftForge/MinecraftForge#1847. If we could somehow convince the lex, et al that this is indeed a bug, we might see a resolution in 1.7.10. (It was always meant to be a fix in 1.7.10---but due to a snafu with the forge devs it never got merged before 1.7.10 switched to bugs only.

The list of mod issues because of this bug grows...

**Comment by mezz** [comment]
Thanks @ScottKillen I'll take a look

**Comment by ScottKillen** [comment]
Thank you!

**Comment by ScottKillen** [comment]
I have release a private fix for this since a fix for 1.7.10 will **not** be forthcoming: https://github.com/MinecraftModArchive/MinecraftForge/releases/tag/10.13.4.1558%2BfuelFix

**Comment by mezz** [comment]
It's not? I didn't see anything happen in the Forge discussion...

**Comment by ScottKillen** [comment]
cpw told me on IRC

They have closed 1.7.10 to only bug fixes and do not believe this is a bug.

**Comment by mezz** [comment]
Boo. Onward to 1.8

**Comment by ScottKillen** [comment]
Indeed. I am going to make a note about the alternate version on my mods curseforge page...thought I would let you know so you could have that option if you wanted.

**Comment by ScottKillen** [comment]
This is how I listed it:

![2015-11-15 15_52_34-overview - ancient trees - mods - projects - minecraft curseforge](https://cloud.githubusercontent.com/assets/1509989/11170990/dd284c34-8bb1-11e5-92fd-e5e324e3435b.png)

**Comment by Parker8283** [comment]
Instead of a whole new forge, why not just create a coremod to fix it? I know lex and cpw hate coremods, but that way people can just use the standard forge.

**Comment by ScottKillen** [comment]
lol...Because I have no idea how to do it. Show me where to start and I am happy to do it.

**Comment by Parker8283** [comment]
Just looked at your patch, I could probably crank that out in about half an hour. I'll get on that right now.

**Comment by ScottKillen** [comment]
Excellent!

I have always considered ASM a bit of a dark art...and never had the need to learn (nor the time) but I always wanted to.

The only thing my patch doesn't fix is if someone wants to _remove_ a vanilla fuel. (Should be easy though...If IFuelHandler returns < 0 have getItemBurnTime() return 0).

**Comment by mezz** [comment]
I'm not in such dire need of this being fixed, I'll direct people here if they ask about it.

**Comment by ScottKillen** [comment]
Just found out that cpw does not want my fork out there...looks like I'm gonna learn about coremods.

**Comment by Parker8283** [comment]
Got you covered man. :P

Though knowing ASM is nice, so go crazy.

**Comment by mezz** [comment]
cpw's pinging you on IRC @ScottKillen, I think there was a misunderstanding.

**Comment by mezz** [comment]
You can hold off, @Parker8283. They're going to merge the bugfix version into 1.7.10 only

**Comment by Parker8283** [comment]
Thankfully, I was having computer problems, otherwise I would've had an env setup. Glad it's being fixed though!

**Comment by ScottKillen** [comment]
Thanks for the support guys!
