### ISSUE TITLE
Crash with CMIP mod on local server

### ISSUE THREAD

**Issue by leagris** [ForestryMC/ForestryMC#961]
Playing/creating a world on local server cause a crash in Forestry when CMIP mod Load
https://github.com/Elecs-Mods/CMIP

NoClassDefFoundError: forestry/core/tiles/IRestrictedAccessTile

Issue does not exist on remote servers because CMIP is a client-side mod.
CMIP use Forestry4 API: forestry_1.7.10-4.0.5.33-dev.jar

https://github.com/Beyond-Reality/BeyondRealityModPack/issues/348

It look like another client-side/server-side code issue.

**Comment by mezz** [comment]
This is a CMIP issue, I'll pass this along to their github: https://github.com/Elecs-Mods/CMIP/issues/6
