### ISSUE TITLE
Big wiki issue

### ISSUE THREAD

**Issue by Rainbow-Spike** [ForestryMC/ForestryMC#962]
1) Uncorrect wiki header http://smages.com/images/pic2015111kek.png Rewrite /lib/tpl/arctic/main.php without red strings, because its outdated thing

2) Uncorrect title image's width on wiki http://smages.com/images/pic2015111fcf.png 1024х screen resolution. http://smages.com/images/pic2015111ckc.png Rewrite to {{:main_butterfly.jpg?590}}

3) Ugly URI http://smages.com/images/pic2015111krk.png Here doku.php?id= part can be removed.
Set 'mod_rewrite' module in Apache
And config .htaccess root file as recommended in https://www.dokuwiki.org/rewrite#apache
THEN set option 'userewrite' as '.htaccess' http://smages.com/images/pic2015111nyn.png in wiki config as recommended in https://www.dokuwiki.org/config:userewrite

4) https://www.dokuwiki.org/plugin:imagebox is recommended as MediaWiki-like image styling feature. Replace all {{ to [{{ and all }} to }}] in all /data/pages/ files

**Comment by HanPrower** [comment]
The wiki has been redone so some of your points have been covered before I saw this issue.

I'm not sure about adding the imagebox plugin. I feel most of the images are relatively self explanatory without needing captions (or boxes around them which would just add visual clutter).

If you have any other ideas though you can post on the forum: http://forum.forestryforminecraft.info/index.php

@mezz you can probably close this? :)

**Comment by Rainbow-Spike** [comment]
Ok
