### ISSUE TITLE
Scoop doesn't scoop in Adventure Mode

### ISSUE THREAD

**Issue by chrisbecke** [ForestryMC/ForestryMC#964]
In adventure mode, the scoop is not the appropriate tool to open Hives and thus cannot be used. Tested on a Curious Hive using a Forestry Scoop - I assume the hives all share the same base class but this might be a Magic bees issue.

The grafter, also, cannot be used to break leaf blocks.

Interestingly - Thaumcrafts Primal Crusher - which does not break Hives unless they are directly targetted - can actually target and break world hives.

**Comment by mezz** [comment]
Thanks for the report!
It was a Forestry issue. Fixed in the latest unstable build.
