### ISSUE TITLE
Trees drop only one wood block when harvested with TiCon lumber axe

### ISSUE THREAD

**Issue by mx86** [ForestryMC/ForestryMC#967]
Using 4.2.0.823, only affecting trees using Forestry specific wood. Vanilla axes work fine, as does Thaumcraft's axe.

Sneaking while using the lumber axe does seem to work fine though, it breaks the wood blocks in its AoE and they drop properly. It's only when harvesting the whole tree.

Also noticed when messing with this in a test world, all of the Forestry trees are only growing with Larch, Chestnut, and Kapok wood depending on the block's orientation. I got the saplings from NEI if that would matter, but saplings that drop from leaves seem to behave the same.

**Comment by mezz** [comment]
Thanks for the report!
I fixed the issue with trees growing the wrong wood. 
[Please report the TiCon issue to them here.](https://github.com/SlimeKnights/TinkersConstruct/issues) They may have a better idea of what it is.
