### ISSUE TITLE
Ores generate in the Twilight Forest even with the config set to false

### ISSUE THREAD

**Issue by Shahelion** [ForestryMC/ForestryMC#968]
What the title says. It works properly in the overworld (at least I haven't found any yet), and this is the only ore to ignore the config setting, for ANY mod in the pack.

**Comment by mezz** [comment]
Thanks for the report!
I'm sure this ore isn't being generated by Forestry in a normal way if you have it disabled in the config. Do you have retrogen accidentally enabled in the config?

**Comment by Shahelion** [comment]
I haven't touched any retrogen (never have).

The only Copper Ore I have enabled in the pack is from Immersive Engineering (same with other applicable ores) and that is generating in the Forest as well, as it should.

![2015-11-16_16 39 37](https://cloud.githubusercontent.com/assets/6917535/11208379/ae7bf8c6-8ccf-11e5-85e9-f7de291394d1.png)

common.cfg: http://hastebin.com/itudedavux.vbs

**Comment by mezz** [comment]
Twilight forest must be detecting the ore block and using it with its own ore generation. The config option doesn't remove the forestry ore block entirely, just disables generation. I guess the solution is to remove it entirely when disabled. I'll fix this soon.

**Comment by Shahelion** [comment]
It looks like Tin Ore is having the same issue.

**Comment by mezz** [comment]
I created a new world and wasn't able to see this issue.
There were no Forestry copper or tin ores in the Twilight Forest when they were disabled.

Either the ores were placed before you disabled them, or some other ore generation method is creating them, like CoFH oregen which is commonly used to generate every kind of ores in big packs.

**Comment by Shahelion** [comment]
So it seems that ores are now generating in the overworld as well, despite still being disabled. I made a new world and noticed this almost right away. Same pack, but a few less mods.

**Comment by mezz** [comment]
You need to find the mod that is generating ores. 
At this point I am 100% sure it is not Forestry alone.
What is your mod list?

**Comment by Shahelion** [comment]
Sorry it took so long:

http://hastebin.com/cogahunayi.coffee

Ignore the states, this was copied from a recent (unrelated) crash report.

**Comment by mezz** [comment]
Sorry I'm not able to debug this. If you want to find the culprit you will have to remove mods until the problem goes away.
