### ISSUE TITLE
clay/marshy bee crashes the game

### ISSUE THREAD

**Issue by wkalinin** [ForestryMC/ForestryMC#969]
Steps to reproduce: 
1. place apiary in swampland
2. put clay princess 
3. put a marshy drone there

Version 4.1.1.46
(mod list and call stack in pastebin: http://pastebin.com/VUMxY3yZ)

**Comment by mezz** [comment]
Thanks for the report!
What mod is the clay bee from?

**Comment by mezz** [comment]
Ah it's from the gregtech bees in GT5 Unofficial experimental.
I have reported it here: https://github.com/Blood-Asp/GT5-Unofficial/issues/319
Dupe of https://github.com/ForestryMC/ForestryMC/issues/963

**Comment by wkalinin** [comment]
Thanks for the quick reply, I'll nag Blood Asp then!
