### ISSUE TITLE
Forestry (Alveary Hygroregulator)

### ISSUE THREAD

**Issue by caliber691** [ForestryMC/ForestryMC#970]
Hello, I've been trying this mod forestry and it seem to work fine. The Alveary Hygroregulator is only fine when it is only empty, but when you put a lava or water in it the game crashes. You can still load the world but when you open again the Alveary Hygroregulator it will crash again. Here is the crash report:
https://gist.github.com/mezz/59eab0b680a9be62db7e

**Comment by XFactHD** [comment]
Try updating to at least Forge version .1448.

**Comment by caliber691** [comment]
Thanks, it worked.

**Comment by mezz** [comment]
Thanks  for the report!
I'm going to update the minimum Forge version so it alerts you when it's below .1448.
