### ISSUE TITLE
Thermionic Fabricator reports Has Work in BC gate when glass is in glass slot

### ISSUE THREAD

**Issue by UntouchedWagons** [ForestryMC/ForestryMC#974]
If you attach a BC pipe to a thermionic fabricator, put a gate on it, set the gate to Has Work -> Nothing and put glass into the TF's glass slot, the Has Work conditional will be true even though there's no actual work available for the fabricator. This, in my opinion, defeats the purpose of the Has Work conditional since it can't be used to cut off power to a fabricator when it's not doing anything.

I'm using Forestry 3.6.6.24 in FTB Infinity Expert mode, that version is quite old compared to the unstable builds available but I don't think updating it is practical in this instance.

**Comment by SandGrainOne** [comment]
The fabricator use power to keep the glass smelted. As long as it has glass to smelt, it has work. This is not the first machine to consume a little bit of power just to be ready when you need it. The actual craft costs no power and can be done instantly.

I've honestly never felt the need to fully automate the Fabricator, but I do think it is important to have machines with different designs to introduce different challenges.

You can still use Has Work. Just add the glass together with the other resources. Find the correct ratio of glass and make sure there are nothing more to smelt once all your crafts are completed.

**Comment by UntouchedWagons** [comment]
Automating the TF is necessary in FTB Infinity Hard Mode because electron tubes are used quite a bit. I found that using Gold AND Gates set to "Items In Inventory" with each ingredient listed works.

**Comment by Nirek-K** [comment]
I added some QoL changes to the Fabricator that should make it somewhat easiesr to use/automate (large internal tank, you can now melt sandstone directly) Feel free to reopen/comment if there's any other ideas.
