### ISSUE TITLE
Crash with Storage module disabled and GrowthCraft [Forestry 4.x]

### ISSUE THREAD

**Issue by MoreThanHidden** [ForestryMC/ForestryMC#975]
Attached Crash log:
[crash-2015-11-21_11.51.39-client.txt](https://github.com/ForestryMC/ForestryMC/files/40739/crash-2015-11-21_11.51.39-client.txt)

Errors with both original and community editions of growthcraft.

**Comment by mezz** [comment]
Thanks for the report!
Please update to Forestry 4.2. It seems to be working fine on this version.

**Comment by MoreThanHidden** [comment]
Sorry should have attached the 4.2 crash, I had tried reverting but it's the same issue:
[crash-2015-11-22_12.12.17-server.txt](https://github.com/ForestryMC/ForestryMC/files/40984/crash-2015-11-22_12.12.17-server.txt)

**Comment by mezz** [comment]
Ah, it's crashing because the Storage module is disabled. I'll submit a fix shortly.

**Comment by mezz** [comment]
[You can get the latest build here.](http://jenkins.ic2.player.to/job/Forestry_Dev/)

**Comment by MoreThanHidden** [comment]
Thanks, Yeah, no crash with Latest version.
