### ISSUE TITLE
Bee Housing

### ISSUE THREAD

**Issue by CraftYourWay** [ForestryMC/ForestryMC#977]
when placing a bee housing i get an error

https://gist.github.com/mezz/0bbcef88fb4e5a8a0a42

please help me to fix i get it in the server and client just for placing a bee housing now i cant delete the bee housing cause my game keeps crashing

**Comment by mezz** [comment]
Thanks for the report!
I'm not sure how you got this problem, but it seems to be caused by a queen ItemStack with no NBT. 
I pushed a fix, updating to build 4.2.0.842-unstable or higher should fix the issue.
