### ISSUE TITLE
Localization issue

### ISSUE THREAD

**Issue by bakaxyf** [ForestryMC/ForestryMC#978]
#### Localization missing
1. [Maximum speed of flowering](https://github.com/ForestryMC/Forestry-Localization/blob/master/assets/forestry/lang/en_US.lang#L1713)
   ![iok f 0lat0 hf3 ze5 s](https://cloud.githubusercontent.com/assets/10368307/11319230/c3c02a5c-90aa-11e5-94db-7c06c1beaa59.jpg)
2. Apiarist's Pipe
   ![image](https://cloud.githubusercontent.com/assets/10368307/11319152/d92b534c-90a7-11e5-9e77-bfcc7a22a4a5.png)
#### Hardcoded localization
1. mail's  localization 

[Please find your order attached.](https://github.com/ForestryMC/ForestryMC/blob/dev/src/main/java/forestry/mail/TradeStation.java#L211)
![vgvycwu9f5rtc9 lqgr t](https://cloud.githubusercontent.com/assets/10368307/11319275/3bc07a88-90ac-11e5-8ad6-08cd4cd375d7.png)

[order(s) from `someone` were filled.](https://github.com/ForestryMC/ForestryMC/blob/dev/src/main/java/forestry/mail/TradeStation.java#L270)
![18d2akz2cs c4i irox bhc](https://cloud.githubusercontent.com/assets/10368307/11319267/f4126f98-90ab-11e5-9c01-850c1053e798.png)
1. [Attempt No.](https://github.com/ForestryMC/ForestryMC/blob/dev/src/main/java/forestry/core/gui/GuiEscritoire.java#L96)

![image](https://cloud.githubusercontent.com/assets/10368307/11319291/768c1500-90ac-11e5-8844-38cffc76a956.png)

**Comment by mezz** [comment]
Thanks for the report!
Fixed in the latest unstable build.

Letter text is only written once, so the new localization will only apply to new letters.
The apiarist's pipe only exists in BuildcraftCompat now, and I see you reported it there already.
