### ISSUE TITLE
Bio Generator crashing the game

### ISSUE THREAD

**Issue by Native91** [ForestryMC/ForestryMC#979]
I placed down a BioGas Engine, and now my game is crashing every time I go to the world.

Crash log:
http://pastebin.com/isF5MfZP

**Comment by mezz** [comment]
Thanks for the report! 
Looks like you're actually using the Bio Generator, which is for use with IC2's EU.
It's definitely broken, I'll fix it shortly.

**Comment by Native91** [comment]
It might have something to do with the texture, since it had a part that was purple and black.

**Comment by mezz** [comment]
I messed with a lot stuff lately and didn't test with IC2 so I didn't see this problem.
Fixed in the latest unstable build.
