### ISSUE TITLE
[Issue]+[Enhancement] Unamanged farm with Multiple Vegetables Replanting the Wrong Type

### ISSUE THREAD

**Issue by mikeloeven** [ForestryMC/ForestryMC#982]
So i have a multifarm with 2 unmanaged vegetable sides one is supposed to be carrots and the other potatoes. however over time the farm will generally replace carrots with potatoes and potatoes with carrots eventually resulting in a situation where both vegetable sections are completely replaced with one or the other. 

There needs to be a check when replacing vegetables to make sure that they are being replanted with the correct type if the seeds are available so that you do not get situations where the farm starts mixing crops and prevents one vegetable take over the whole farm otherwise this behavior defeats the purpose of independently configurable sides.

Perhaps the best solution would be to configure the multifarm UI with 8 seed inputs and 8 Soil inputs and configure each slot with a input filter. Match each pair of inputs to one side of the farm thus making sure that when replanting the farm each side is only drawing dirt and seeds from the matching soil and seed slots. the configurable input filter will make sure that pipe systems will input seeds and soil into the correct slot. in all these changes will make it easier to have multiple crops of the same type in the farm without having one of them take over the farm or having them become mixed up

**Comment by Nirek-K** [comment]
Use the orchard tube and manually setup your farm if you want a specific/complex layout. (this will do what you want, orchard can handle most crops with the exception of melons/reeds/netherwart)
Related: #498

**Comment by mikeloeven** [comment]
First of all vegetables are not trees secondly your suggestion is a workaround not a fix. my suggestion still stands Saying to use a different type of tube means your admitting that manual vegetable farms are fundamentally flawed. my solution is a simple and elegant and solves what is a fairly major issue. 4 inputs mapped to each side 2 soil 2 seed filter mechanism to make sure pipes systems are inserting into the right slots. nuff said no excuse not to implement.

**Comment by Nirek-K** [comment]
Orchard as in manual->copper tubes.

**Comment by mikeloeven** [comment]
Its still a dirty workaround and not a fix
