### ISSUE TITLE
Analyzer recipe

### ISSUE THREAD

**Issue by leagris** [ForestryMC/ForestryMC#984]
Flutterlyzer should be an alternative to Treealyzer and Beealyzer in Analyzer recipe

Flutterlyzer should be renamed Flutteralyzer in line with other alyzers

To be honest, all these *alyzer items should be merged into a single portableAnalyzer.

**Comment by mezz** [comment]
I have been slowly cleaning up the code to move towards merging them. I'll leave this issue open until it's finished.

**Comment by mezz** [comment]
These are being merged, starting here https://github.com/ForestryMC/ForestryMC/commit/7ae7e62c0cc52dc69c0b4ffa4e9cb6b1914a3205
