### ISSUE TITLE
Forestry version of acacia sapling cannot be obtained

### ISSUE THREAD

**Issue by EBrarian** [ForestryMC/ForestryMC#986]
When putting a vanilla acacia sapling in the treealyzer, it produces a desert acacia sapling instead of the forestry version of the regular acacia sapling.

The forestry version of the regular acacia sapling is required for further tree breeding such as the Padauk tree.

Forestry verson : forestry_1.7.10-4.2.0.47.jar

**Comment by leagris** [comment]
I confirm
Forestryfication of a vanilla Acacia should give a Forestry Acacia and not a Forestry Desert_Acacia.

**Comment by mezz** [comment]
Thanks for the report!
Fixed in the latest unstable build.
