### ISSUE TITLE
IndexOutOfBounds crash, probably backpack related

### ISSUE THREAD

**Issue by JasonMcRay** [ForestryMC/ForestryMC#988]
Was unable to recreate it on demand, but sometimes when interacting with inventories with backpack in your hand causes crash.

@ghoulsblade said:

> while rclicking enderchest with backpack at a short lagspike from the server, rclicking 2-3 times with the backpack in empty air afterwards as it didnt react, then it crashed after about 5 seconds standstill. Mousewheel was moved to select the backpack in hotbar as well, not sure if that plays a role.
> So far it looks to me that the crash only happens when trying repeatedly to open a backpack during a lagspike from the server (e.g. internet connection hickup, or some non-minecraft related backup job or similar starting on the server)

crash: https://paste.ee/p/FImGy
Modpack: InfiTech 2
Forestry: 4.0.11.40 (sorry for slightly outdated version used, but currently we can't use later versions because of crash with GT - needs to be fixed on GT side; so if this is fixed in later FT version, sorry)

As said we are not sure what is exact cause, but so fat it appears to be related really with Backpacks.

**Comment by mezz** [comment]
I gave it a good shot but wasn't able to reproduce the issue with the latest Forestry.
I redid Forestry's networking code in between this version and the one you're using, which may have fixed the problem. I think there was a race condition where the server and client would try to open different inventories from each other (one backpack, one ender chest), which is no longer possible with the new network code.

**Comment by JasonMcRay** [comment]
havent heard any more issues, so closing this as resolved :)
