### ISSUE TITLE
Mekanism can't recognise Forestry saplings

### ISSUE THREAD

**Issue by TehStoneMan** [ForestryMC/ForestryMC#989]
Trying to use Forestry saplings in a Mekanism crusher does not work. Vanilla saplings and saplings from other mods work fine.

The crusher is supposed to convert saplings into Mekanism bio-fuel, but even though NEI recognizes it as a valid recipe, Forestry saplings are not accepted by the machine.

**Comment by mezz** [comment]
Thanks for the report!
This seems like something for Mekanism, looks like it has been reported here: https://github.com/aidancbrady/Mekanism/issues/2832
