### ISSUE TITLE
I can only make recipes that require farm blocks with nether quartz pillar farm blocks

### ISSUE THREAD

**Issue by alanmh** [ForestryMC/ForestryMC#991]
Nothing else
The recipes don't exist

**Comment by nerclid** [comment]
same issue, forestry_1.7.10-4.2.0.47.jar, forge1.7.10-10.13.4.1558, 
![ss](https://cloud.githubusercontent.com/assets/3346166/11491907/fe0840ca-97ab-11e5-8a96-282acc766050.jpg)

**Comment by mezz** [comment]
Thanks for the report!
Try the latest unstable version and see if that fixes it: http://jenkins.ic2.player.to/job/Forestry_Dev/

**Comment by Kriiks** [comment]
Same problem here too. Tried to load with recommended unstable build, but that just crashed for me.
[crash-2015-12-02_17.49.30-server.txt](https://github.com/ForestryMC/ForestryMC/files/49900/crash-2015-12-02_17.49.30-server.txt)

**Comment by mezz** [comment]
@Kriiks you grabbed the dev jar, it's only for development. Try `forestry_1.7.10-4.2.1.851-unstable.jar`.

**Comment by Kriiks** [comment]
Oops, true. Tried now with right version, farmblock recipes are working properly.

Just noticed some missing forestry blocks message while loading up with this version:
There are 7 missing blocks and items in this save.
...
Missing Blocks/Items:
Forestry:waxCapsuleOil
Forestry:waxCapsuleFuel
Forestry:canFuel
Forestry:refractoryOil
Forestry:refractoryFuel
Forestry:bucketSeedoil
Forestry:canOil

I hope it was intended :)

edit: maybe not completely fine. When i stared to place my farm blocks I noticed that my mossy brick farmblocks valve, hatch, control and gearbox all turned magically into normal stone brick versions.
Crafting mossy brick version gives you actually normal stone brick block.

**Comment by mezz** [comment]
@Kriiks I had no trouble crafting or placing mossy farm parts. Maybe your server does not have the same Forestry version and disagrees on the recipe?

The missing items are normal, if you don't have BuildCraft there's no point in having containers for fuel and oil.

**Comment by Kriiks** [comment]
I had right version of Forestry on client and on server, but wrong outcome was caused by Gany's Surface crafting table allowing you to alter outcome and defaulting wrong type. Didn't notice this first, sorry for false alarm!
But I do have Buildcraft 7.1.13, so if missing blocks were supposed to mean missing Buildcraft, then I'm still bit confused.
