### ISSUE TITLE
Server: forestry.core.items.ItemCrated

### ISSUE THREAD

**Issue by Morketh** [ForestryMC/ForestryMC#993]
Console Printout [here](https://gist.github.com/Morketh/788f8b1ea428be5dc53b) well turned the server on for the first time in a week and received this error. The server fatally crashed during startup with this error [here](https://gist.github.com/Morketh/e703c2e7a63263b3c461) yes i know thats a Computercraft error. im using a series of Logistics Pipes and Computercraft computers to run a factory and at one end is a Forestry Treefarm and a Carpenter to crate up extra junk (cobblestone, dirt, sapplings, any item that hits 5K,....etc) now im not exactly sure why LogisticsPipes would be complaining about those items (are they UUID's?), i posted this here to be thorough in my investigation.

**Comment by mezz** [comment]
This is very strange. 
To me this seems to be a Logistics Pipes issue. There isn't anything special about the Forestry crates in this context, they're just items traveling in a pipe.

**Comment by Morketh** [comment]
I thought as much and as far as I'm aware that part of the factory was shut down prior to the shutdown of the server so no items should have been in any pipe during startup.

**Comment by mezz** [comment]
I will close this issue for now, if some information points towards Forestry again just post here and I'll reopen it.
