### ISSUE TITLE
Peat-fired Engine no longer accepts Bituminous Peat

### ISSUE THREAD

**Issue by damnedsky** [ForestryMC/ForestryMC#994]
Hello! I am currently using forestry_1.7.10-4.2.1.851-unstable.jar because of issue #991 but this seems to exclude  Bituminous Peat as a fuel source from Peat-fired Engines. Thank you for your time!

**Comment by mezz** [comment]
Thanks for the report!
Fixed in the latest unstable build.
I'll be releasing a new stable build soon as well.
