### ISSUE TITLE
java.lang.NoClassDefFoundError: binnie/extrabees/apiary/TileExtraBeeAlveary

### ISSUE THREAD

**Issue by Sasikaa** [ForestryMC/ForestryMC#996]
The NEW forestry and Gendustry. Put it my DNS techpack, and crash with startup!
This is my crash log:
http://pastebin.com/4w15Djpa

My Binnies mod using when this CRASHLOG generated:
bdlib-1.9.3.107-mc1.7.10
binnie-mods-2.0-pre14
forestry_1.7.10-4.2.1.48.jar
gendustry-1.6.3.129-mc1.7.10.jar

**Comment by mezz** [comment]
Thanks for the report!
Duplicate of https://github.com/ForestryMC/ForestryMC/issues/857
