### ISSUE TITLE
ticking crash

### ISSUE THREAD

**Issue by adamsonich** [ForestryMC/ForestryMC#997]
Description: Ticking block entity

java.lang.NoClassDefFoundError: forestry/core/gadgets/TileAnalyzer
    at li.cil.oc.integration.forestry.DriverAnalyzer.getTileEntityClass(DriverAnalyzer.scala:15)
    at li.cil.oc.api.prefab.DriverTileEntity.worksWith(DriverTileEntity.java:11)
    at li.cil.oc.server.driver.Registry$$anonfun$2.apply(Registry.scala:70)
    at li.cil.oc.server.driver.Registry$$anonfun$2.apply(Registry.scala:70)
...
-- Block entity being ticked --
Details:
    Name: RCHiddenTile // mods.railcraft.common.blocks.hidden.TileHidden
    Block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (99,62,514), Chunk: (at 3,3,2 in 6,32; contains blocks 96,0,512 to 111,255,527), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
    Actual block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
    Actual block data value: 0 / 0x0 / 0b0000

forge: 1490
forestry_1.7.10-4.0.10.39
Railcraft_1.7.10-9.7.0.0

which version is stable in 4.2? i will try to update.

**Comment by mezz** [comment]
Thanks for the report!
I think this is a crash from OpenComputers, I reported it here: https://github.com/MightyPirates/OpenComputers/issues/1551

You can get the [latest stable version of Forestry on Curse](http://www.curse.com/mc-mods/minecraft/forestry).
