### ISSUE TITLE
Forestry Wood Logs Placement Issue

### ISSUE THREAD

**Issue by LuigiHutch** [ForestryMC/ForestryMC#999]
Forestry_1.7.10-4.2.1.48

Forestry wood logs dont place like vanilla logs. See image for reference:

![2015-12-04_21 14 15](https://cloud.githubusercontent.com/assets/9326429/11601607/285d84ac-9acc-11e5-81a7-1d150e34ae73.png)

Edit: Also can you make it so you can rotate them with a wrench like vanilla logs.
Edit 2: Ooh, 999th issue \o/

**Comment by leagris** [comment]
Appear to only affect Ipe, Paduk, Cocobolo, ZebraWood logs

**Comment by LuigiHutch** [comment]
The stairs placement is also broken :(
